var annotated =
[
    [ "_KineticProto", "struct___kinetic_proto.html", "struct___kinetic_proto" ],
    [ "ByteBuffer", "struct_byte_buffer.html", "struct_byte_buffer" ],
    [ "Kinetic_KeyValue", "struct_kinetic___key_value.html", "struct_kinetic___key_value" ],
    [ "KineticConnection", "struct_kinetic_connection.html", "struct_kinetic_connection" ],
    [ "KineticHMAC", "struct_kinetic_h_m_a_c.html", "struct_kinetic_h_m_a_c" ],
    [ "KineticMessage", "struct_kinetic_message.html", "struct_kinetic_message" ],
    [ "KineticOperation", "struct_kinetic_operation.html", "struct_kinetic_operation" ],
    [ "KineticPDU", "struct_kinetic_p_d_u.html", "struct_kinetic_p_d_u" ],
    [ "KineticProto_Body", "struct___kinetic_proto___body.html", "struct___kinetic_proto___body" ],
    [ "KineticProto_Command", "struct___kinetic_proto___command.html", "struct___kinetic_proto___command" ],
    [ "KineticProto_GetLog", "struct___kinetic_proto___get_log.html", "struct___kinetic_proto___get_log" ],
    [ "KineticProto_GetLog_Capacity", "struct___kinetic_proto___get_log___capacity.html", "struct___kinetic_proto___get_log___capacity" ],
    [ "KineticProto_GetLog_Configuration", "struct___kinetic_proto___get_log___configuration.html", "struct___kinetic_proto___get_log___configuration" ],
    [ "KineticProto_GetLog_Configuration_Interface", "struct___kinetic_proto___get_log___configuration___interface.html", "struct___kinetic_proto___get_log___configuration___interface" ],
    [ "KineticProto_GetLog_Device", "struct___kinetic_proto___get_log___device.html", "struct___kinetic_proto___get_log___device" ],
    [ "KineticProto_GetLog_Limits", "struct___kinetic_proto___get_log___limits.html", "struct___kinetic_proto___get_log___limits" ],
    [ "KineticProto_GetLog_Statistics", "struct___kinetic_proto___get_log___statistics.html", "struct___kinetic_proto___get_log___statistics" ],
    [ "KineticProto_GetLog_Temperature", "struct___kinetic_proto___get_log___temperature.html", "struct___kinetic_proto___get_log___temperature" ],
    [ "KineticProto_GetLog_Utilization", "struct___kinetic_proto___get_log___utilization.html", "struct___kinetic_proto___get_log___utilization" ],
    [ "KineticProto_Header", "struct___kinetic_proto___header.html", "struct___kinetic_proto___header" ],
    [ "KineticProto_KeyValue", "struct___kinetic_proto___key_value.html", "struct___kinetic_proto___key_value" ],
    [ "KineticProto_P2POperation", "struct___kinetic_proto___p2_p_operation.html", "struct___kinetic_proto___p2_p_operation" ],
    [ "KineticProto_P2POperation_Operation", "struct___kinetic_proto___p2_p_operation___operation.html", "struct___kinetic_proto___p2_p_operation___operation" ],
    [ "KineticProto_P2POperation_Peer", "struct___kinetic_proto___p2_p_operation___peer.html", "struct___kinetic_proto___p2_p_operation___peer" ],
    [ "KineticProto_Range", "struct___kinetic_proto___range.html", "struct___kinetic_proto___range" ],
    [ "KineticProto_Security", "struct___kinetic_proto___security.html", "struct___kinetic_proto___security" ],
    [ "KineticProto_Security_ACL", "struct___kinetic_proto___security___a_c_l.html", "struct___kinetic_proto___security___a_c_l" ],
    [ "KineticProto_Security_ACL_Scope", "struct___kinetic_proto___security___a_c_l___scope.html", "struct___kinetic_proto___security___a_c_l___scope" ],
    [ "KineticProto_Setup", "struct___kinetic_proto___setup.html", "struct___kinetic_proto___setup" ],
    [ "KineticProto_Status", "struct___kinetic_proto___status.html", "struct___kinetic_proto___status" ]
];