.TH "Com__Seagate__Kinetic__Proto__Command" 3 "Fri Mar 13 2015" "Version v0.12.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Com__Seagate__Kinetic__Proto__Command \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic\&.pb-c\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "ProtobufCMessage \fBbase\fP"
.br
.ti -1c
.RI "Com__Seagate__Kinetic__Proto__Command__Header * \fBheader\fP"
.br
.ti -1c
.RI "Com__Seagate__Kinetic__Proto__Command__Body * \fBbody\fP"
.br
.ti -1c
.RI "Com__Seagate__Kinetic__Proto__Command__Status * \fBstatus\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1173 of file kinetic\&.pb-c\&.h\&.
.SH "Field Documentation"
.PP 
.SS "ProtobufCMessage Com__Seagate__Kinetic__Proto__Command::base"

.PP
Definition at line 1175 of file kinetic\&.pb-c\&.h\&.
.SS "Com__Seagate__Kinetic__Proto__Command__Header* Com__Seagate__Kinetic__Proto__Command::header"

.PP
Definition at line 1179 of file kinetic\&.pb-c\&.h\&.
.SS "Com__Seagate__Kinetic__Proto__Command__Body* Com__Seagate__Kinetic__Proto__Command::body"

.PP
Definition at line 1183 of file kinetic\&.pb-c\&.h\&.
.SS "Com__Seagate__Kinetic__Proto__Command__Status* Com__Seagate__Kinetic__Proto__Command::status"

.PP
Definition at line 1187 of file kinetic\&.pb-c\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
