.TH "Com__Seagate__Kinetic__Proto__Command__GetLog" 3 "Fri Mar 13 2015" "Version v0.12.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Com__Seagate__Kinetic__Proto__Command__GetLog \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic\&.pb-c\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "ProtobufCMessage \fBbase\fP"
.br
.ti -1c
.RI "size_t \fBn_types\fP"
.br
.ti -1c
.RI "\fBCom__Seagate__Kinetic__Proto__Command__GetLog__Type\fP * \fBtypes\fP"
.br
.ti -1c
.RI "size_t \fBn_utilizations\fP"
.br
.ti -1c
.RI "Com__Seagate__Kinetic__Proto__Command__GetLog__Utilization ** \fButilizations\fP"
.br
.ti -1c
.RI "size_t \fBn_temperatures\fP"
.br
.ti -1c
.RI "Com__Seagate__Kinetic__Proto__Command__GetLog__Temperature ** \fBtemperatures\fP"
.br
.ti -1c
.RI "Com__Seagate__Kinetic__Proto__Command__GetLog__Capacity * \fBcapacity\fP"
.br
.ti -1c
.RI "Com__Seagate__Kinetic__Proto__Command__GetLog__Configuration * \fBconfiguration\fP"
.br
.ti -1c
.RI "size_t \fBn_statistics\fP"
.br
.ti -1c
.RI "Com__Seagate__Kinetic__Proto__Command__GetLog__Statistics ** \fBstatistics\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_messages\fP"
.br
.ti -1c
.RI "ProtobufCBinaryData \fBmessages\fP"
.br
.ti -1c
.RI "Com__Seagate__Kinetic__Proto__Command__GetLog__Limits * \fBlimits\fP"
.br
.ti -1c
.RI "Com__Seagate__Kinetic__Proto__Command__GetLog__Device * \fBdevice\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1047 of file kinetic\&.pb-c\&.h\&.
.SH "Field Documentation"
.PP 
.SS "ProtobufCMessage Com__Seagate__Kinetic__Proto__Command__GetLog::base"

.PP
Definition at line 1049 of file kinetic\&.pb-c\&.h\&.
.SS "size_t Com__Seagate__Kinetic__Proto__Command__GetLog::n_types"

.PP
Definition at line 1050 of file kinetic\&.pb-c\&.h\&.
.SS "\fBCom__Seagate__Kinetic__Proto__Command__GetLog__Type\fP* Com__Seagate__Kinetic__Proto__Command__GetLog::types"

.PP
Definition at line 1051 of file kinetic\&.pb-c\&.h\&.
.SS "size_t Com__Seagate__Kinetic__Proto__Command__GetLog::n_utilizations"

.PP
Definition at line 1052 of file kinetic\&.pb-c\&.h\&.
.SS "Com__Seagate__Kinetic__Proto__Command__GetLog__Utilization** Com__Seagate__Kinetic__Proto__Command__GetLog::utilizations"

.PP
Definition at line 1053 of file kinetic\&.pb-c\&.h\&.
.SS "size_t Com__Seagate__Kinetic__Proto__Command__GetLog::n_temperatures"

.PP
Definition at line 1054 of file kinetic\&.pb-c\&.h\&.
.SS "Com__Seagate__Kinetic__Proto__Command__GetLog__Temperature** Com__Seagate__Kinetic__Proto__Command__GetLog::temperatures"

.PP
Definition at line 1055 of file kinetic\&.pb-c\&.h\&.
.SS "Com__Seagate__Kinetic__Proto__Command__GetLog__Capacity* Com__Seagate__Kinetic__Proto__Command__GetLog::capacity"

.PP
Definition at line 1056 of file kinetic\&.pb-c\&.h\&.
.SS "Com__Seagate__Kinetic__Proto__Command__GetLog__Configuration* Com__Seagate__Kinetic__Proto__Command__GetLog::configuration"

.PP
Definition at line 1057 of file kinetic\&.pb-c\&.h\&.
.SS "size_t Com__Seagate__Kinetic__Proto__Command__GetLog::n_statistics"

.PP
Definition at line 1058 of file kinetic\&.pb-c\&.h\&.
.SS "Com__Seagate__Kinetic__Proto__Command__GetLog__Statistics** Com__Seagate__Kinetic__Proto__Command__GetLog::statistics"

.PP
Definition at line 1059 of file kinetic\&.pb-c\&.h\&.
.SS "protobuf_c_boolean Com__Seagate__Kinetic__Proto__Command__GetLog::has_messages"

.PP
Definition at line 1060 of file kinetic\&.pb-c\&.h\&.
.SS "ProtobufCBinaryData Com__Seagate__Kinetic__Proto__Command__GetLog::messages"

.PP
Definition at line 1061 of file kinetic\&.pb-c\&.h\&.
.SS "Com__Seagate__Kinetic__Proto__Command__GetLog__Limits* Com__Seagate__Kinetic__Proto__Command__GetLog::limits"

.PP
Definition at line 1062 of file kinetic\&.pb-c\&.h\&.
.SS "Com__Seagate__Kinetic__Proto__Command__GetLog__Device* Com__Seagate__Kinetic__Proto__Command__GetLog::device"

.PP
Definition at line 1063 of file kinetic\&.pb-c\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
