.TH "Com__Seagate__Kinetic__Proto__Command__GetLog__Temperature" 3 "Fri Mar 13 2015" "Version v0.12.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Com__Seagate__Kinetic__Proto__Command__GetLog__Temperature \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic\&.pb-c\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "ProtobufCMessage \fBbase\fP"
.br
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_current\fP"
.br
.ti -1c
.RI "float \fBcurrent\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_minimum\fP"
.br
.ti -1c
.RI "float \fBminimum\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_maximum\fP"
.br
.ti -1c
.RI "float \fBmaximum\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_target\fP"
.br
.ti -1c
.RI "float \fBtarget\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 847 of file kinetic\&.pb-c\&.h\&.
.SH "Field Documentation"
.PP 
.SS "ProtobufCMessage Com__Seagate__Kinetic__Proto__Command__GetLog__Temperature::base"

.PP
Definition at line 849 of file kinetic\&.pb-c\&.h\&.
.SS "char* Com__Seagate__Kinetic__Proto__Command__GetLog__Temperature::name"

.PP
Definition at line 855 of file kinetic\&.pb-c\&.h\&.
.SS "protobuf_c_boolean Com__Seagate__Kinetic__Proto__Command__GetLog__Temperature::has_current"

.PP
Definition at line 859 of file kinetic\&.pb-c\&.h\&.
.SS "float Com__Seagate__Kinetic__Proto__Command__GetLog__Temperature::current"

.PP
Definition at line 860 of file kinetic\&.pb-c\&.h\&.
.SS "protobuf_c_boolean Com__Seagate__Kinetic__Proto__Command__GetLog__Temperature::has_minimum"

.PP
Definition at line 861 of file kinetic\&.pb-c\&.h\&.
.SS "float Com__Seagate__Kinetic__Proto__Command__GetLog__Temperature::minimum"

.PP
Definition at line 862 of file kinetic\&.pb-c\&.h\&.
.SS "protobuf_c_boolean Com__Seagate__Kinetic__Proto__Command__GetLog__Temperature::has_maximum"

.PP
Definition at line 863 of file kinetic\&.pb-c\&.h\&.
.SS "float Com__Seagate__Kinetic__Proto__Command__GetLog__Temperature::maximum"

.PP
Definition at line 864 of file kinetic\&.pb-c\&.h\&.
.SS "protobuf_c_boolean Com__Seagate__Kinetic__Proto__Command__GetLog__Temperature::has_target"

.PP
Definition at line 865 of file kinetic\&.pb-c\&.h\&.
.SS "float Com__Seagate__Kinetic__Proto__Command__GetLog__Temperature::target"

.PP
Definition at line 866 of file kinetic\&.pb-c\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
