.TH "Com__Seagate__Kinetic__Proto__Command__Security__ACL__Scope" 3 "Fri Mar 13 2015" "Version v0.12.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Com__Seagate__Kinetic__Proto__Command__Security__ACL__Scope \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic\&.pb-c\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "ProtobufCMessage \fBbase\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_offset\fP"
.br
.ti -1c
.RI "int64_t \fBoffset\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_value\fP"
.br
.ti -1c
.RI "ProtobufCBinaryData \fBvalue\fP"
.br
.ti -1c
.RI "size_t \fBn_permission\fP"
.br
.ti -1c
.RI "\fBCom__Seagate__Kinetic__Proto__Command__Security__ACL__Permission\fP * \fBpermission\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_tlsrequired\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBtlsrequired\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1070 of file kinetic\&.pb-c\&.h\&.
.SH "Field Documentation"
.PP 
.SS "ProtobufCMessage Com__Seagate__Kinetic__Proto__Command__Security__ACL__Scope::base"

.PP
Definition at line 1072 of file kinetic\&.pb-c\&.h\&.
.SS "protobuf_c_boolean Com__Seagate__Kinetic__Proto__Command__Security__ACL__Scope::has_offset"

.PP
Definition at line 1073 of file kinetic\&.pb-c\&.h\&.
.SS "int64_t Com__Seagate__Kinetic__Proto__Command__Security__ACL__Scope::offset"

.PP
Definition at line 1074 of file kinetic\&.pb-c\&.h\&.
.SS "protobuf_c_boolean Com__Seagate__Kinetic__Proto__Command__Security__ACL__Scope::has_value"

.PP
Definition at line 1075 of file kinetic\&.pb-c\&.h\&.
.SS "ProtobufCBinaryData Com__Seagate__Kinetic__Proto__Command__Security__ACL__Scope::value"

.PP
Definition at line 1076 of file kinetic\&.pb-c\&.h\&.
.SS "size_t Com__Seagate__Kinetic__Proto__Command__Security__ACL__Scope::n_permission"

.PP
Definition at line 1080 of file kinetic\&.pb-c\&.h\&.
.SS "\fBCom__Seagate__Kinetic__Proto__Command__Security__ACL__Permission\fP* Com__Seagate__Kinetic__Proto__Command__Security__ACL__Scope::permission"

.PP
Definition at line 1081 of file kinetic\&.pb-c\&.h\&.
.SS "protobuf_c_boolean Com__Seagate__Kinetic__Proto__Command__Security__ACL__Scope::has_tlsrequired"

.PP
Definition at line 1085 of file kinetic\&.pb-c\&.h\&.
.SS "protobuf_c_boolean Com__Seagate__Kinetic__Proto__Command__Security__ACL__Scope::tlsrequired"

.PP
Definition at line 1086 of file kinetic\&.pb-c\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
