.TH "Com__Seagate__Kinetic__Proto__Command__GetLog__Capacity" 3 "Fri Mar 13 2015" "Version v0.12.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Com__Seagate__Kinetic__Proto__Command__GetLog__Capacity \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic\&.pb-c\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "ProtobufCMessage \fBbase\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_nominalcapacityinbytes\fP"
.br
.ti -1c
.RI "uint64_t \fBnominalcapacityinbytes\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_portionfull\fP"
.br
.ti -1c
.RI "float \fBportionfull\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 876 of file kinetic\&.pb-c\&.h\&.
.SH "Field Documentation"
.PP 
.SS "ProtobufCMessage Com__Seagate__Kinetic__Proto__Command__GetLog__Capacity::base"

.PP
Definition at line 878 of file kinetic\&.pb-c\&.h\&.
.SS "protobuf_c_boolean Com__Seagate__Kinetic__Proto__Command__GetLog__Capacity::has_nominalcapacityinbytes"

.PP
Definition at line 882 of file kinetic\&.pb-c\&.h\&.
.SS "uint64_t Com__Seagate__Kinetic__Proto__Command__GetLog__Capacity::nominalcapacityinbytes"

.PP
Definition at line 883 of file kinetic\&.pb-c\&.h\&.
.SS "protobuf_c_boolean Com__Seagate__Kinetic__Proto__Command__GetLog__Capacity::has_portionfull"

.PP
Definition at line 884 of file kinetic\&.pb-c\&.h\&.
.SS "float Com__Seagate__Kinetic__Proto__Command__GetLog__Capacity::portionfull"

.PP
Definition at line 885 of file kinetic\&.pb-c\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
