.TH "Com__Seagate__Kinetic__Proto__Message__HMACauth" 3 "Fri Mar 13 2015" "Version v0.12.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Com__Seagate__Kinetic__Proto__Message__HMACauth \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic\&.pb-c\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "ProtobufCMessage \fBbase\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_identity\fP"
.br
.ti -1c
.RI "int64_t \fBidentity\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_hmac\fP"
.br
.ti -1c
.RI "ProtobufCBinaryData \fBhmac\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 399 of file kinetic\&.pb-c\&.h\&.
.SH "Field Documentation"
.PP 
.SS "ProtobufCMessage Com__Seagate__Kinetic__Proto__Message__HMACauth::base"

.PP
Definition at line 401 of file kinetic\&.pb-c\&.h\&.
.SS "protobuf_c_boolean Com__Seagate__Kinetic__Proto__Message__HMACauth::has_identity"

.PP
Definition at line 406 of file kinetic\&.pb-c\&.h\&.
.SS "int64_t Com__Seagate__Kinetic__Proto__Message__HMACauth::identity"

.PP
Definition at line 407 of file kinetic\&.pb-c\&.h\&.
.SS "protobuf_c_boolean Com__Seagate__Kinetic__Proto__Message__HMACauth::has_hmac"

.PP
Definition at line 408 of file kinetic\&.pb-c\&.h\&.
.SS "ProtobufCBinaryData Com__Seagate__Kinetic__Proto__Message__HMACauth::hmac"

.PP
Definition at line 409 of file kinetic\&.pb-c\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
