.TH "Com__Seagate__Kinetic__Proto__Command__GetLog__Configuration" 3 "Fri Mar 13 2015" "Version v0.12.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Com__Seagate__Kinetic__Proto__Command__GetLog__Configuration \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic\&.pb-c\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "ProtobufCMessage \fBbase\fP"
.br
.ti -1c
.RI "char * \fBvendor\fP"
.br
.ti -1c
.RI "char * \fBmodel\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_serialnumber\fP"
.br
.ti -1c
.RI "ProtobufCBinaryData \fBserialnumber\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_worldwidename\fP"
.br
.ti -1c
.RI "ProtobufCBinaryData \fBworldwidename\fP"
.br
.ti -1c
.RI "char * \fBversion\fP"
.br
.ti -1c
.RI "char * \fBcompilationdate\fP"
.br
.ti -1c
.RI "char * \fBsourcehash\fP"
.br
.ti -1c
.RI "char * \fBprotocolversion\fP"
.br
.ti -1c
.RI "char * \fBprotocolcompilationdate\fP"
.br
.ti -1c
.RI "char * \fBprotocolsourcehash\fP"
.br
.ti -1c
.RI "size_t \fBn_interface\fP"
.br
.ti -1c
.RI "Com__Seagate__Kinetic__Proto__Command__GetLog__Configuration__Interface ** \fBinterface\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_port\fP"
.br
.ti -1c
.RI "int32_t \fBport\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_tlsport\fP"
.br
.ti -1c
.RI "int32_t \fBtlsport\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 911 of file kinetic\&.pb-c\&.h\&.
.SH "Field Documentation"
.PP 
.SS "ProtobufCMessage Com__Seagate__Kinetic__Proto__Command__GetLog__Configuration::base"

.PP
Definition at line 913 of file kinetic\&.pb-c\&.h\&.
.SS "char* Com__Seagate__Kinetic__Proto__Command__GetLog__Configuration::vendor"

.PP
Definition at line 917 of file kinetic\&.pb-c\&.h\&.
.SS "char* Com__Seagate__Kinetic__Proto__Command__GetLog__Configuration::model"

.PP
Definition at line 922 of file kinetic\&.pb-c\&.h\&.
.SS "protobuf_c_boolean Com__Seagate__Kinetic__Proto__Command__GetLog__Configuration::has_serialnumber"

.PP
Definition at line 926 of file kinetic\&.pb-c\&.h\&.
.SS "ProtobufCBinaryData Com__Seagate__Kinetic__Proto__Command__GetLog__Configuration::serialnumber"

.PP
Definition at line 927 of file kinetic\&.pb-c\&.h\&.
.SS "protobuf_c_boolean Com__Seagate__Kinetic__Proto__Command__GetLog__Configuration::has_worldwidename"

.PP
Definition at line 931 of file kinetic\&.pb-c\&.h\&.
.SS "ProtobufCBinaryData Com__Seagate__Kinetic__Proto__Command__GetLog__Configuration::worldwidename"

.PP
Definition at line 932 of file kinetic\&.pb-c\&.h\&.
.SS "char* Com__Seagate__Kinetic__Proto__Command__GetLog__Configuration::version"

.PP
Definition at line 937 of file kinetic\&.pb-c\&.h\&.
.SS "char* Com__Seagate__Kinetic__Proto__Command__GetLog__Configuration::compilationdate"

.PP
Definition at line 938 of file kinetic\&.pb-c\&.h\&.
.SS "char* Com__Seagate__Kinetic__Proto__Command__GetLog__Configuration::sourcehash"

.PP
Definition at line 939 of file kinetic\&.pb-c\&.h\&.
.SS "char* Com__Seagate__Kinetic__Proto__Command__GetLog__Configuration::protocolversion"

.PP
Definition at line 945 of file kinetic\&.pb-c\&.h\&.
.SS "char* Com__Seagate__Kinetic__Proto__Command__GetLog__Configuration::protocolcompilationdate"

.PP
Definition at line 946 of file kinetic\&.pb-c\&.h\&.
.SS "char* Com__Seagate__Kinetic__Proto__Command__GetLog__Configuration::protocolsourcehash"

.PP
Definition at line 947 of file kinetic\&.pb-c\&.h\&.
.SS "size_t Com__Seagate__Kinetic__Proto__Command__GetLog__Configuration::n_interface"

.PP
Definition at line 951 of file kinetic\&.pb-c\&.h\&.
.SS "Com__Seagate__Kinetic__Proto__Command__GetLog__Configuration__Interface** Com__Seagate__Kinetic__Proto__Command__GetLog__Configuration::interface"

.PP
Definition at line 952 of file kinetic\&.pb-c\&.h\&.
.SS "protobuf_c_boolean Com__Seagate__Kinetic__Proto__Command__GetLog__Configuration::has_port"

.PP
Definition at line 956 of file kinetic\&.pb-c\&.h\&.
.SS "int32_t Com__Seagate__Kinetic__Proto__Command__GetLog__Configuration::port"

.PP
Definition at line 957 of file kinetic\&.pb-c\&.h\&.
.SS "protobuf_c_boolean Com__Seagate__Kinetic__Proto__Command__GetLog__Configuration::has_tlsport"

.PP
Definition at line 958 of file kinetic\&.pb-c\&.h\&.
.SS "int32_t Com__Seagate__Kinetic__Proto__Command__GetLog__Configuration::tlsport"

.PP
Definition at line 959 of file kinetic\&.pb-c\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
