.TH "Com__Seagate__Kinetic__Proto__Command__Body" 3 "Fri Mar 13 2015" "Version v0.12.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Com__Seagate__Kinetic__Proto__Command__Body \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic\&.pb-c\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "ProtobufCMessage \fBbase\fP"
.br
.ti -1c
.RI "Com__Seagate__Kinetic__Proto__Command__KeyValue * \fBkeyvalue\fP"
.br
.ti -1c
.RI "Com__Seagate__Kinetic__Proto__Command__Range * \fBrange\fP"
.br
.ti -1c
.RI "Com__Seagate__Kinetic__Proto__Command__Setup * \fBsetup\fP"
.br
.ti -1c
.RI "Com__Seagate__Kinetic__Proto__Command__P2POperation * \fBp2poperation\fP"
.br
.ti -1c
.RI "Com__Seagate__Kinetic__Proto__Command__GetLog * \fBgetlog\fP"
.br
.ti -1c
.RI "Com__Seagate__Kinetic__Proto__Command__Security * \fBsecurity\fP"
.br
.ti -1c
.RI "Com__Seagate__Kinetic__Proto__Command__PinOperation * \fBpinop\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 548 of file kinetic\&.pb-c\&.h\&.
.SH "Field Documentation"
.PP 
.SS "ProtobufCMessage Com__Seagate__Kinetic__Proto__Command__Body::base"

.PP
Definition at line 550 of file kinetic\&.pb-c\&.h\&.
.SS "Com__Seagate__Kinetic__Proto__Command__KeyValue* Com__Seagate__Kinetic__Proto__Command__Body::keyvalue"

.PP
Definition at line 554 of file kinetic\&.pb-c\&.h\&.
.SS "Com__Seagate__Kinetic__Proto__Command__Range* Com__Seagate__Kinetic__Proto__Command__Body::range"

.PP
Definition at line 558 of file kinetic\&.pb-c\&.h\&.
.SS "Com__Seagate__Kinetic__Proto__Command__Setup* Com__Seagate__Kinetic__Proto__Command__Body::setup"

.PP
Definition at line 562 of file kinetic\&.pb-c\&.h\&.
.SS "Com__Seagate__Kinetic__Proto__Command__P2POperation* Com__Seagate__Kinetic__Proto__Command__Body::p2poperation"

.PP
Definition at line 566 of file kinetic\&.pb-c\&.h\&.
.SS "Com__Seagate__Kinetic__Proto__Command__GetLog* Com__Seagate__Kinetic__Proto__Command__Body::getlog"

.PP
Definition at line 570 of file kinetic\&.pb-c\&.h\&.
.SS "Com__Seagate__Kinetic__Proto__Command__Security* Com__Seagate__Kinetic__Proto__Command__Body::security"

.PP
Definition at line 574 of file kinetic\&.pb-c\&.h\&.
.SS "Com__Seagate__Kinetic__Proto__Command__PinOperation* Com__Seagate__Kinetic__Proto__Command__Body::pinop"

.PP
Definition at line 578 of file kinetic\&.pb-c\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
