.TH "Com__Seagate__Kinetic__Proto__Command__GetLog__Statistics" 3 "Fri Mar 13 2015" "Version v0.12.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Com__Seagate__Kinetic__Proto__Command__GetLog__Statistics \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic\&.pb-c\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "ProtobufCMessage \fBbase\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_messagetype\fP"
.br
.ti -1c
.RI "\fBCom__Seagate__Kinetic__Proto__Command__MessageType\fP \fBmessagetype\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_count\fP"
.br
.ti -1c
.RI "uint64_t \fBcount\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_bytes\fP"
.br
.ti -1c
.RI "uint64_t \fBbytes\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 969 of file kinetic\&.pb-c\&.h\&.
.SH "Field Documentation"
.PP 
.SS "ProtobufCMessage Com__Seagate__Kinetic__Proto__Command__GetLog__Statistics::base"

.PP
Definition at line 971 of file kinetic\&.pb-c\&.h\&.
.SS "protobuf_c_boolean Com__Seagate__Kinetic__Proto__Command__GetLog__Statistics::has_messagetype"

.PP
Definition at line 972 of file kinetic\&.pb-c\&.h\&.
.SS "\fBCom__Seagate__Kinetic__Proto__Command__MessageType\fP Com__Seagate__Kinetic__Proto__Command__GetLog__Statistics::messagetype"

.PP
Definition at line 973 of file kinetic\&.pb-c\&.h\&.
.SS "protobuf_c_boolean Com__Seagate__Kinetic__Proto__Command__GetLog__Statistics::has_count"

.PP
Definition at line 977 of file kinetic\&.pb-c\&.h\&.
.SS "uint64_t Com__Seagate__Kinetic__Proto__Command__GetLog__Statistics::count"

.PP
Definition at line 978 of file kinetic\&.pb-c\&.h\&.
.SS "protobuf_c_boolean Com__Seagate__Kinetic__Proto__Command__GetLog__Statistics::has_bytes"

.PP
Definition at line 984 of file kinetic\&.pb-c\&.h\&.
.SS "uint64_t Com__Seagate__Kinetic__Proto__Command__GetLog__Statistics::bytes"

.PP
Definition at line 985 of file kinetic\&.pb-c\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
