.TH "Com__Seagate__Kinetic__Proto__Command__Header" 3 "Fri Mar 13 2015" "Version v0.12.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Com__Seagate__Kinetic__Proto__Command__Header \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic\&.pb-c\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "ProtobufCMessage \fBbase\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_clusterversion\fP"
.br
.ti -1c
.RI "int64_t \fBclusterversion\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_connectionid\fP"
.br
.ti -1c
.RI "int64_t \fBconnectionid\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_sequence\fP"
.br
.ti -1c
.RI "int64_t \fBsequence\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_acksequence\fP"
.br
.ti -1c
.RI "int64_t \fBacksequence\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_messagetype\fP"
.br
.ti -1c
.RI "\fBCom__Seagate__Kinetic__Proto__Command__MessageType\fP \fBmessagetype\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_timeout\fP"
.br
.ti -1c
.RI "int64_t \fBtimeout\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_earlyexit\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBearlyexit\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_priority\fP"
.br
.ti -1c
.RI "\fBCom__Seagate__Kinetic__Proto__Command__Priority\fP \fBpriority\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_timequanta\fP"
.br
.ti -1c
.RI "int64_t \fBtimequanta\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 468 of file kinetic\&.pb-c\&.h\&.
.SH "Field Documentation"
.PP 
.SS "ProtobufCMessage Com__Seagate__Kinetic__Proto__Command__Header::base"

.PP
Definition at line 470 of file kinetic\&.pb-c\&.h\&.
.SS "protobuf_c_boolean Com__Seagate__Kinetic__Proto__Command__Header::has_clusterversion"

.PP
Definition at line 476 of file kinetic\&.pb-c\&.h\&.
.SS "int64_t Com__Seagate__Kinetic__Proto__Command__Header::clusterversion"

.PP
Definition at line 477 of file kinetic\&.pb-c\&.h\&.
.SS "protobuf_c_boolean Com__Seagate__Kinetic__Proto__Command__Header::has_connectionid"

.PP
Definition at line 484 of file kinetic\&.pb-c\&.h\&.
.SS "int64_t Com__Seagate__Kinetic__Proto__Command__Header::connectionid"

.PP
Definition at line 485 of file kinetic\&.pb-c\&.h\&.
.SS "protobuf_c_boolean Com__Seagate__Kinetic__Proto__Command__Header::has_sequence"

.PP
Definition at line 491 of file kinetic\&.pb-c\&.h\&.
.SS "int64_t Com__Seagate__Kinetic__Proto__Command__Header::sequence"

.PP
Definition at line 492 of file kinetic\&.pb-c\&.h\&.
.SS "protobuf_c_boolean Com__Seagate__Kinetic__Proto__Command__Header::has_acksequence"

.PP
Definition at line 496 of file kinetic\&.pb-c\&.h\&.
.SS "int64_t Com__Seagate__Kinetic__Proto__Command__Header::acksequence"

.PP
Definition at line 497 of file kinetic\&.pb-c\&.h\&.
.SS "protobuf_c_boolean Com__Seagate__Kinetic__Proto__Command__Header::has_messagetype"

.PP
Definition at line 501 of file kinetic\&.pb-c\&.h\&.
.SS "\fBCom__Seagate__Kinetic__Proto__Command__MessageType\fP Com__Seagate__Kinetic__Proto__Command__Header::messagetype"

.PP
Definition at line 502 of file kinetic\&.pb-c\&.h\&.
.SS "protobuf_c_boolean Com__Seagate__Kinetic__Proto__Command__Header::has_timeout"

.PP
Definition at line 511 of file kinetic\&.pb-c\&.h\&.
.SS "int64_t Com__Seagate__Kinetic__Proto__Command__Header::timeout"

.PP
Definition at line 512 of file kinetic\&.pb-c\&.h\&.
.SS "protobuf_c_boolean Com__Seagate__Kinetic__Proto__Command__Header::has_earlyexit"

.PP
Definition at line 521 of file kinetic\&.pb-c\&.h\&.
.SS "protobuf_c_boolean Com__Seagate__Kinetic__Proto__Command__Header::earlyexit"

.PP
Definition at line 522 of file kinetic\&.pb-c\&.h\&.
.SS "protobuf_c_boolean Com__Seagate__Kinetic__Proto__Command__Header::has_priority"

.PP
Definition at line 528 of file kinetic\&.pb-c\&.h\&.
.SS "\fBCom__Seagate__Kinetic__Proto__Command__Priority\fP Com__Seagate__Kinetic__Proto__Command__Header::priority"

.PP
Definition at line 529 of file kinetic\&.pb-c\&.h\&.
.SS "protobuf_c_boolean Com__Seagate__Kinetic__Proto__Command__Header::has_timequanta"

.PP
Definition at line 537 of file kinetic\&.pb-c\&.h\&.
.SS "int64_t Com__Seagate__Kinetic__Proto__Command__Header::timequanta"

.PP
Definition at line 538 of file kinetic\&.pb-c\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
