.TH "Com__Seagate__Kinetic__Proto__Command__PinOperation" 3 "Fri Mar 13 2015" "Version v0.12.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Com__Seagate__Kinetic__Proto__Command__PinOperation \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic\&.pb-c\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "ProtobufCMessage \fBbase\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_pinoptype\fP"
.br
.ti -1c
.RI "\fBCom__Seagate__Kinetic__Proto__Command__PinOperation__PinOpType\fP \fBpinoptype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1162 of file kinetic\&.pb-c\&.h\&.
.SH "Field Documentation"
.PP 
.SS "ProtobufCMessage Com__Seagate__Kinetic__Proto__Command__PinOperation::base"

.PP
Definition at line 1164 of file kinetic\&.pb-c\&.h\&.
.SS "protobuf_c_boolean Com__Seagate__Kinetic__Proto__Command__PinOperation::has_pinoptype"

.PP
Definition at line 1165 of file kinetic\&.pb-c\&.h\&.
.SS "\fBCom__Seagate__Kinetic__Proto__Command__PinOperation__PinOpType\fP Com__Seagate__Kinetic__Proto__Command__PinOperation::pinoptype"

.PP
Definition at line 1166 of file kinetic\&.pb-c\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
