.TH "Com__Seagate__Kinetic__Proto__Command__Security" 3 "Fri Mar 13 2015" "Version v0.12.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Com__Seagate__Kinetic__Proto__Command__Security \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic\&.pb-c\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "ProtobufCMessage \fBbase\fP"
.br
.ti -1c
.RI "size_t \fBn_acl\fP"
.br
.ti -1c
.RI "Com__Seagate__Kinetic__Proto__Command__Security__ACL ** \fBacl\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_oldlockpin\fP"
.br
.ti -1c
.RI "ProtobufCBinaryData \fBoldlockpin\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_newlockpin\fP"
.br
.ti -1c
.RI "ProtobufCBinaryData \fBnewlockpin\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_olderasepin\fP"
.br
.ti -1c
.RI "ProtobufCBinaryData \fBolderasepin\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_newerasepin\fP"
.br
.ti -1c
.RI "ProtobufCBinaryData \fBnewerasepin\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1131 of file kinetic\&.pb-c\&.h\&.
.SH "Field Documentation"
.PP 
.SS "ProtobufCMessage Com__Seagate__Kinetic__Proto__Command__Security::base"

.PP
Definition at line 1133 of file kinetic\&.pb-c\&.h\&.
.SS "size_t Com__Seagate__Kinetic__Proto__Command__Security::n_acl"

.PP
Definition at line 1137 of file kinetic\&.pb-c\&.h\&.
.SS "Com__Seagate__Kinetic__Proto__Command__Security__ACL** Com__Seagate__Kinetic__Proto__Command__Security::acl"

.PP
Definition at line 1138 of file kinetic\&.pb-c\&.h\&.
.SS "protobuf_c_boolean Com__Seagate__Kinetic__Proto__Command__Security::has_oldlockpin"

.PP
Definition at line 1142 of file kinetic\&.pb-c\&.h\&.
.SS "ProtobufCBinaryData Com__Seagate__Kinetic__Proto__Command__Security::oldlockpin"

.PP
Definition at line 1143 of file kinetic\&.pb-c\&.h\&.
.SS "protobuf_c_boolean Com__Seagate__Kinetic__Proto__Command__Security::has_newlockpin"

.PP
Definition at line 1144 of file kinetic\&.pb-c\&.h\&.
.SS "ProtobufCBinaryData Com__Seagate__Kinetic__Proto__Command__Security::newlockpin"

.PP
Definition at line 1145 of file kinetic\&.pb-c\&.h\&.
.SS "protobuf_c_boolean Com__Seagate__Kinetic__Proto__Command__Security::has_olderasepin"

.PP
Definition at line 1146 of file kinetic\&.pb-c\&.h\&.
.SS "ProtobufCBinaryData Com__Seagate__Kinetic__Proto__Command__Security::olderasepin"

.PP
Definition at line 1147 of file kinetic\&.pb-c\&.h\&.
.SS "protobuf_c_boolean Com__Seagate__Kinetic__Proto__Command__Security::has_newerasepin"

.PP
Definition at line 1148 of file kinetic\&.pb-c\&.h\&.
.SS "ProtobufCBinaryData Com__Seagate__Kinetic__Proto__Command__Security::newerasepin"

.PP
Definition at line 1149 of file kinetic\&.pb-c\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
