.TH "Com__Seagate__Kinetic__Proto__Message" 3 "Fri Mar 13 2015" "Version v0.12.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Com__Seagate__Kinetic__Proto__Message \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic\&.pb-c\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "ProtobufCMessage \fBbase\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_authtype\fP"
.br
.ti -1c
.RI "\fBCom__Seagate__Kinetic__Proto__Message__AuthType\fP \fBauthtype\fP"
.br
.ti -1c
.RI "Com__Seagate__Kinetic__Proto__Message__HMACauth * \fBhmacauth\fP"
.br
.ti -1c
.RI "Com__Seagate__Kinetic__Proto__Message__PINauth * \fBpinauth\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_commandbytes\fP"
.br
.ti -1c
.RI "ProtobufCBinaryData \fBcommandbytes\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 436 of file kinetic\&.pb-c\&.h\&.
.SH "Field Documentation"
.PP 
.SS "ProtobufCMessage Com__Seagate__Kinetic__Proto__Message::base"

.PP
Definition at line 438 of file kinetic\&.pb-c\&.h\&.
.SS "protobuf_c_boolean Com__Seagate__Kinetic__Proto__Message::has_authtype"

.PP
Definition at line 442 of file kinetic\&.pb-c\&.h\&.
.SS "\fBCom__Seagate__Kinetic__Proto__Message__AuthType\fP Com__Seagate__Kinetic__Proto__Message::authtype"

.PP
Definition at line 443 of file kinetic\&.pb-c\&.h\&.
.SS "Com__Seagate__Kinetic__Proto__Message__HMACauth* Com__Seagate__Kinetic__Proto__Message::hmacauth"

.PP
Definition at line 447 of file kinetic\&.pb-c\&.h\&.
.SS "Com__Seagate__Kinetic__Proto__Message__PINauth* Com__Seagate__Kinetic__Proto__Message::pinauth"

.PP
Definition at line 452 of file kinetic\&.pb-c\&.h\&.
.SS "protobuf_c_boolean Com__Seagate__Kinetic__Proto__Message::has_commandbytes"

.PP
Definition at line 457 of file kinetic\&.pb-c\&.h\&.
.SS "ProtobufCBinaryData Com__Seagate__Kinetic__Proto__Message::commandbytes"

.PP
Definition at line 458 of file kinetic\&.pb-c\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
