.TH "Com__Seagate__Kinetic__Proto__Command__Status" 3 "Fri Mar 13 2015" "Version v0.12.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Com__Seagate__Kinetic__Proto__Command__Status \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic\&.pb-c\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "ProtobufCMessage \fBbase\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_code\fP"
.br
.ti -1c
.RI "\fBCom__Seagate__Kinetic__Proto__Command__Status__StatusCode\fP \fBcode\fP"
.br
.ti -1c
.RI "char * \fBstatusmessage\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_detailedmessage\fP"
.br
.ti -1c
.RI "ProtobufCBinaryData \fBdetailedmessage\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 588 of file kinetic\&.pb-c\&.h\&.
.SH "Field Documentation"
.PP 
.SS "ProtobufCMessage Com__Seagate__Kinetic__Proto__Command__Status::base"

.PP
Definition at line 590 of file kinetic\&.pb-c\&.h\&.
.SS "protobuf_c_boolean Com__Seagate__Kinetic__Proto__Command__Status::has_code"

.PP
Definition at line 594 of file kinetic\&.pb-c\&.h\&.
.SS "\fBCom__Seagate__Kinetic__Proto__Command__Status__StatusCode\fP Com__Seagate__Kinetic__Proto__Command__Status::code"

.PP
Definition at line 595 of file kinetic\&.pb-c\&.h\&.
.SS "char* Com__Seagate__Kinetic__Proto__Command__Status::statusmessage"

.PP
Definition at line 599 of file kinetic\&.pb-c\&.h\&.
.SS "protobuf_c_boolean Com__Seagate__Kinetic__Proto__Command__Status::has_detailedmessage"

.PP
Definition at line 603 of file kinetic\&.pb-c\&.h\&.
.SS "ProtobufCBinaryData Com__Seagate__Kinetic__Proto__Command__Status::detailedmessage"

.PP
Definition at line 604 of file kinetic\&.pb-c\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
