.TH "Com__Seagate__Kinetic__Proto__Command__GetLog__Limits" 3 "Fri Mar 13 2015" "Version v0.12.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Com__Seagate__Kinetic__Proto__Command__GetLog__Limits \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic\&.pb-c\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "ProtobufCMessage \fBbase\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_maxkeysize\fP"
.br
.ti -1c
.RI "uint32_t \fBmaxkeysize\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_maxvaluesize\fP"
.br
.ti -1c
.RI "uint32_t \fBmaxvaluesize\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_maxversionsize\fP"
.br
.ti -1c
.RI "uint32_t \fBmaxversionsize\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_maxtagsize\fP"
.br
.ti -1c
.RI "uint32_t \fBmaxtagsize\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_maxconnections\fP"
.br
.ti -1c
.RI "uint32_t \fBmaxconnections\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_maxoutstandingreadrequests\fP"
.br
.ti -1c
.RI "uint32_t \fBmaxoutstandingreadrequests\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_maxoutstandingwriterequests\fP"
.br
.ti -1c
.RI "uint32_t \fBmaxoutstandingwriterequests\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_maxmessagesize\fP"
.br
.ti -1c
.RI "uint32_t \fBmaxmessagesize\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_maxkeyrangecount\fP"
.br
.ti -1c
.RI "uint32_t \fBmaxkeyrangecount\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_maxidentitycount\fP"
.br
.ti -1c
.RI "uint32_t \fBmaxidentitycount\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_maxpinsize\fP"
.br
.ti -1c
.RI "uint32_t \fBmaxpinsize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 992 of file kinetic\&.pb-c\&.h\&.
.SH "Field Documentation"
.PP 
.SS "ProtobufCMessage Com__Seagate__Kinetic__Proto__Command__GetLog__Limits::base"

.PP
Definition at line 994 of file kinetic\&.pb-c\&.h\&.
.SS "protobuf_c_boolean Com__Seagate__Kinetic__Proto__Command__GetLog__Limits::has_maxkeysize"

.PP
Definition at line 995 of file kinetic\&.pb-c\&.h\&.
.SS "uint32_t Com__Seagate__Kinetic__Proto__Command__GetLog__Limits::maxkeysize"

.PP
Definition at line 996 of file kinetic\&.pb-c\&.h\&.
.SS "protobuf_c_boolean Com__Seagate__Kinetic__Proto__Command__GetLog__Limits::has_maxvaluesize"

.PP
Definition at line 997 of file kinetic\&.pb-c\&.h\&.
.SS "uint32_t Com__Seagate__Kinetic__Proto__Command__GetLog__Limits::maxvaluesize"

.PP
Definition at line 998 of file kinetic\&.pb-c\&.h\&.
.SS "protobuf_c_boolean Com__Seagate__Kinetic__Proto__Command__GetLog__Limits::has_maxversionsize"

.PP
Definition at line 999 of file kinetic\&.pb-c\&.h\&.
.SS "uint32_t Com__Seagate__Kinetic__Proto__Command__GetLog__Limits::maxversionsize"

.PP
Definition at line 1000 of file kinetic\&.pb-c\&.h\&.
.SS "protobuf_c_boolean Com__Seagate__Kinetic__Proto__Command__GetLog__Limits::has_maxtagsize"

.PP
Definition at line 1001 of file kinetic\&.pb-c\&.h\&.
.SS "uint32_t Com__Seagate__Kinetic__Proto__Command__GetLog__Limits::maxtagsize"

.PP
Definition at line 1002 of file kinetic\&.pb-c\&.h\&.
.SS "protobuf_c_boolean Com__Seagate__Kinetic__Proto__Command__GetLog__Limits::has_maxconnections"

.PP
Definition at line 1003 of file kinetic\&.pb-c\&.h\&.
.SS "uint32_t Com__Seagate__Kinetic__Proto__Command__GetLog__Limits::maxconnections"

.PP
Definition at line 1004 of file kinetic\&.pb-c\&.h\&.
.SS "protobuf_c_boolean Com__Seagate__Kinetic__Proto__Command__GetLog__Limits::has_maxoutstandingreadrequests"

.PP
Definition at line 1005 of file kinetic\&.pb-c\&.h\&.
.SS "uint32_t Com__Seagate__Kinetic__Proto__Command__GetLog__Limits::maxoutstandingreadrequests"

.PP
Definition at line 1006 of file kinetic\&.pb-c\&.h\&.
.SS "protobuf_c_boolean Com__Seagate__Kinetic__Proto__Command__GetLog__Limits::has_maxoutstandingwriterequests"

.PP
Definition at line 1007 of file kinetic\&.pb-c\&.h\&.
.SS "uint32_t Com__Seagate__Kinetic__Proto__Command__GetLog__Limits::maxoutstandingwriterequests"

.PP
Definition at line 1008 of file kinetic\&.pb-c\&.h\&.
.SS "protobuf_c_boolean Com__Seagate__Kinetic__Proto__Command__GetLog__Limits::has_maxmessagesize"

.PP
Definition at line 1009 of file kinetic\&.pb-c\&.h\&.
.SS "uint32_t Com__Seagate__Kinetic__Proto__Command__GetLog__Limits::maxmessagesize"

.PP
Definition at line 1010 of file kinetic\&.pb-c\&.h\&.
.SS "protobuf_c_boolean Com__Seagate__Kinetic__Proto__Command__GetLog__Limits::has_maxkeyrangecount"

.PP
Definition at line 1011 of file kinetic\&.pb-c\&.h\&.
.SS "uint32_t Com__Seagate__Kinetic__Proto__Command__GetLog__Limits::maxkeyrangecount"

.PP
Definition at line 1012 of file kinetic\&.pb-c\&.h\&.
.SS "protobuf_c_boolean Com__Seagate__Kinetic__Proto__Command__GetLog__Limits::has_maxidentitycount"

.PP
Definition at line 1013 of file kinetic\&.pb-c\&.h\&.
.SS "uint32_t Com__Seagate__Kinetic__Proto__Command__GetLog__Limits::maxidentitycount"

.PP
Definition at line 1014 of file kinetic\&.pb-c\&.h\&.
.SS "protobuf_c_boolean Com__Seagate__Kinetic__Proto__Command__GetLog__Limits::has_maxpinsize"

.PP
Definition at line 1015 of file kinetic\&.pb-c\&.h\&.
.SS "uint32_t Com__Seagate__Kinetic__Proto__Command__GetLog__Limits::maxpinsize"

.PP
Definition at line 1016 of file kinetic\&.pb-c\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
