.TH "Com__Seagate__Kinetic__Proto__Command__P2POperation__Operation" 3 "Fri Mar 13 2015" "Version v0.12.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Com__Seagate__Kinetic__Proto__Command__P2POperation__Operation \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic\&.pb-c\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "ProtobufCMessage \fBbase\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_key\fP"
.br
.ti -1c
.RI "ProtobufCBinaryData \fBkey\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_version\fP"
.br
.ti -1c
.RI "ProtobufCBinaryData \fBversion\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_newkey\fP"
.br
.ti -1c
.RI "ProtobufCBinaryData \fBnewkey\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_force\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBforce\fP"
.br
.ti -1c
.RI "Com__Seagate__Kinetic__Proto__Command__Status * \fBstatus\fP"
.br
.ti -1c
.RI "Com__Seagate__Kinetic__Proto__Command__P2POperation * \fBp2pop\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 742 of file kinetic\&.pb-c\&.h\&.
.SH "Field Documentation"
.PP 
.SS "ProtobufCMessage Com__Seagate__Kinetic__Proto__Command__P2POperation__Operation::base"

.PP
Definition at line 744 of file kinetic\&.pb-c\&.h\&.
.SS "protobuf_c_boolean Com__Seagate__Kinetic__Proto__Command__P2POperation__Operation::has_key"

.PP
Definition at line 748 of file kinetic\&.pb-c\&.h\&.
.SS "ProtobufCBinaryData Com__Seagate__Kinetic__Proto__Command__P2POperation__Operation::key"

.PP
Definition at line 749 of file kinetic\&.pb-c\&.h\&.
.SS "protobuf_c_boolean Com__Seagate__Kinetic__Proto__Command__P2POperation__Operation::has_version"

.PP
Definition at line 754 of file kinetic\&.pb-c\&.h\&.
.SS "ProtobufCBinaryData Com__Seagate__Kinetic__Proto__Command__P2POperation__Operation::version"

.PP
Definition at line 755 of file kinetic\&.pb-c\&.h\&.
.SS "protobuf_c_boolean Com__Seagate__Kinetic__Proto__Command__P2POperation__Operation::has_newkey"

.PP
Definition at line 759 of file kinetic\&.pb-c\&.h\&.
.SS "ProtobufCBinaryData Com__Seagate__Kinetic__Proto__Command__P2POperation__Operation::newkey"

.PP
Definition at line 760 of file kinetic\&.pb-c\&.h\&.
.SS "protobuf_c_boolean Com__Seagate__Kinetic__Proto__Command__P2POperation__Operation::has_force"

.PP
Definition at line 764 of file kinetic\&.pb-c\&.h\&.
.SS "protobuf_c_boolean Com__Seagate__Kinetic__Proto__Command__P2POperation__Operation::force"

.PP
Definition at line 765 of file kinetic\&.pb-c\&.h\&.
.SS "Com__Seagate__Kinetic__Proto__Command__Status* Com__Seagate__Kinetic__Proto__Command__P2POperation__Operation::status"

.PP
Definition at line 769 of file kinetic\&.pb-c\&.h\&.
.SS "Com__Seagate__Kinetic__Proto__Command__P2POperation* Com__Seagate__Kinetic__Proto__Command__P2POperation__Operation::p2pop"

.PP
Definition at line 775 of file kinetic\&.pb-c\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
