.TH "Com__Seagate__Kinetic__Proto__Command__Security__ACL" 3 "Fri Mar 13 2015" "Version v0.12.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Com__Seagate__Kinetic__Proto__Command__Security__ACL \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic\&.pb-c\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "ProtobufCMessage \fBbase\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_identity\fP"
.br
.ti -1c
.RI "int64_t \fBidentity\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_key\fP"
.br
.ti -1c
.RI "ProtobufCBinaryData \fBkey\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_hmacalgorithm\fP"
.br
.ti -1c
.RI "\fBCom__Seagate__Kinetic__Proto__Command__Security__ACL__HMACAlgorithm\fP \fBhmacalgorithm\fP"
.br
.ti -1c
.RI "size_t \fBn_scope\fP"
.br
.ti -1c
.RI "Com__Seagate__Kinetic__Proto__Command__Security__ACL__Scope ** \fBscope\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_maxpriority\fP"
.br
.ti -1c
.RI "\fBCom__Seagate__Kinetic__Proto__Command__Priority\fP \fBmaxpriority\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1095 of file kinetic\&.pb-c\&.h\&.
.SH "Field Documentation"
.PP 
.SS "ProtobufCMessage Com__Seagate__Kinetic__Proto__Command__Security__ACL::base"

.PP
Definition at line 1097 of file kinetic\&.pb-c\&.h\&.
.SS "protobuf_c_boolean Com__Seagate__Kinetic__Proto__Command__Security__ACL::has_identity"

.PP
Definition at line 1098 of file kinetic\&.pb-c\&.h\&.
.SS "int64_t Com__Seagate__Kinetic__Proto__Command__Security__ACL::identity"

.PP
Definition at line 1099 of file kinetic\&.pb-c\&.h\&.
.SS "protobuf_c_boolean Com__Seagate__Kinetic__Proto__Command__Security__ACL::has_key"

.PP
Definition at line 1103 of file kinetic\&.pb-c\&.h\&.
.SS "ProtobufCBinaryData Com__Seagate__Kinetic__Proto__Command__Security__ACL::key"

.PP
Definition at line 1104 of file kinetic\&.pb-c\&.h\&.
.SS "protobuf_c_boolean Com__Seagate__Kinetic__Proto__Command__Security__ACL::has_hmacalgorithm"

.PP
Definition at line 1105 of file kinetic\&.pb-c\&.h\&.
.SS "\fBCom__Seagate__Kinetic__Proto__Command__Security__ACL__HMACAlgorithm\fP Com__Seagate__Kinetic__Proto__Command__Security__ACL::hmacalgorithm"

.PP
Definition at line 1106 of file kinetic\&.pb-c\&.h\&.
.SS "size_t Com__Seagate__Kinetic__Proto__Command__Security__ACL::n_scope"

.PP
Definition at line 1112 of file kinetic\&.pb-c\&.h\&.
.SS "Com__Seagate__Kinetic__Proto__Command__Security__ACL__Scope** Com__Seagate__Kinetic__Proto__Command__Security__ACL::scope"

.PP
Definition at line 1113 of file kinetic\&.pb-c\&.h\&.
.SS "protobuf_c_boolean Com__Seagate__Kinetic__Proto__Command__Security__ACL::has_maxpriority"

.PP
Definition at line 1119 of file kinetic\&.pb-c\&.h\&.
.SS "\fBCom__Seagate__Kinetic__Proto__Command__Priority\fP Com__Seagate__Kinetic__Proto__Command__Security__ACL::maxpriority"

.PP
Definition at line 1120 of file kinetic\&.pb-c\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
