.TH "_Com__Seagate__Kinetic__Proto__Local" 3 "Fri Mar 13 2015" "Version v0.12.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_Com__Seagate__Kinetic__Proto__Local \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic\&.pb-c\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "ProtobufCMessage \fBbase\fP"
.br
.ti -1c
.RI "char * \fBprotocolversion\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 382 of file kinetic\&.pb-c\&.h\&.
.SH "Field Documentation"
.PP 
.SS "ProtobufCMessage _Com__Seagate__Kinetic__Proto__Local::base"

.PP
Definition at line 384 of file kinetic\&.pb-c\&.h\&.
.SS "char* _Com__Seagate__Kinetic__Proto__Local::protocolversion"

.PP
Definition at line 385 of file kinetic\&.pb-c\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
