.TH "Com__Seagate__Kinetic__Proto__Command__GetLog__Configuration__Interface" 3 "Fri Mar 13 2015" "Version v0.12.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Com__Seagate__Kinetic__Proto__Command__GetLog__Configuration__Interface \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic\&.pb-c\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "ProtobufCMessage \fBbase\fP"
.br
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_mac\fP"
.br
.ti -1c
.RI "ProtobufCBinaryData \fBmac\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_ipv4address\fP"
.br
.ti -1c
.RI "ProtobufCBinaryData \fBipv4address\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_ipv6address\fP"
.br
.ti -1c
.RI "ProtobufCBinaryData \fBipv6address\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 895 of file kinetic\&.pb-c\&.h\&.
.SH "Field Documentation"
.PP 
.SS "ProtobufCMessage Com__Seagate__Kinetic__Proto__Command__GetLog__Configuration__Interface::base"

.PP
Definition at line 897 of file kinetic\&.pb-c\&.h\&.
.SS "char* Com__Seagate__Kinetic__Proto__Command__GetLog__Configuration__Interface::name"

.PP
Definition at line 898 of file kinetic\&.pb-c\&.h\&.
.SS "protobuf_c_boolean Com__Seagate__Kinetic__Proto__Command__GetLog__Configuration__Interface::has_mac"

.PP
Definition at line 899 of file kinetic\&.pb-c\&.h\&.
.SS "ProtobufCBinaryData Com__Seagate__Kinetic__Proto__Command__GetLog__Configuration__Interface::mac"

.PP
Definition at line 900 of file kinetic\&.pb-c\&.h\&.
.SS "protobuf_c_boolean Com__Seagate__Kinetic__Proto__Command__GetLog__Configuration__Interface::has_ipv4address"

.PP
Definition at line 901 of file kinetic\&.pb-c\&.h\&.
.SS "ProtobufCBinaryData Com__Seagate__Kinetic__Proto__Command__GetLog__Configuration__Interface::ipv4address"

.PP
Definition at line 902 of file kinetic\&.pb-c\&.h\&.
.SS "protobuf_c_boolean Com__Seagate__Kinetic__Proto__Command__GetLog__Configuration__Interface::has_ipv6address"

.PP
Definition at line 903 of file kinetic\&.pb-c\&.h\&.
.SS "ProtobufCBinaryData Com__Seagate__Kinetic__Proto__Command__GetLog__Configuration__Interface::ipv6address"

.PP
Definition at line 904 of file kinetic\&.pb-c\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
