.TH "KineticProto_KeyValue" 3 "Fri Aug 8 2014" "Version v0.4.3" "protobuf-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticProto_KeyValue \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_proto\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "ProtobufCMessage \fBbase\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_newversion\fP"
.br
.ti -1c
.RI "ProtobufCBinaryData \fBnewversion\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_force\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBforce\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_key\fP"
.br
.ti -1c
.RI "ProtobufCBinaryData \fBkey\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_dbversion\fP"
.br
.ti -1c
.RI "ProtobufCBinaryData \fBdbversion\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_tag\fP"
.br
.ti -1c
.RI "ProtobufCBinaryData \fBtag\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_algorithm\fP"
.br
.ti -1c
.RI "\fBKineticProto_Algorithm\fP \fBalgorithm\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_metadataonly\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBmetadataonly\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_synchronization\fP"
.br
.ti -1c
.RI "\fBKineticProto_Synchronization\fP \fBsynchronization\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 235 of file kinetic_proto\&.h\&.
.SH "Field Documentation"
.PP 
.SS "ProtobufCMessage KineticProto_KeyValue::base"

.PP
Definition at line 237 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_KeyValue::has_newversion"

.PP
Definition at line 238 of file kinetic_proto\&.h\&.
.SS "ProtobufCBinaryData KineticProto_KeyValue::newversion"

.PP
Definition at line 239 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_KeyValue::has_force"

.PP
Definition at line 240 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_KeyValue::force"

.PP
Definition at line 241 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_KeyValue::has_key"

.PP
Definition at line 242 of file kinetic_proto\&.h\&.
.SS "ProtobufCBinaryData KineticProto_KeyValue::key"

.PP
Definition at line 243 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_KeyValue::has_dbversion"

.PP
Definition at line 244 of file kinetic_proto\&.h\&.
.SS "ProtobufCBinaryData KineticProto_KeyValue::dbversion"

.PP
Definition at line 245 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_KeyValue::has_tag"

.PP
Definition at line 246 of file kinetic_proto\&.h\&.
.SS "ProtobufCBinaryData KineticProto_KeyValue::tag"

.PP
Definition at line 247 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_KeyValue::has_algorithm"

.PP
Definition at line 248 of file kinetic_proto\&.h\&.
.SS "\fBKineticProto_Algorithm\fP KineticProto_KeyValue::algorithm"

.PP
Definition at line 249 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_KeyValue::has_metadataonly"

.PP
Definition at line 250 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_KeyValue::metadataonly"

.PP
Definition at line 251 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_KeyValue::has_synchronization"

.PP
Definition at line 252 of file kinetic_proto\&.h\&.
.SS "\fBKineticProto_Synchronization\fP KineticProto_KeyValue::synchronization"

.PP
Definition at line 253 of file kinetic_proto\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for protobuf-c from the source code\&.
