.TH "KineticProto_Command_GetLog_Utilization" 3 "Tue Nov 4 2014" "Version v0.8.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticProto_Command_GetLog_Utilization \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_proto\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "ProtobufCMessage \fBbase\fP"
.br
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_value\fP"
.br
.ti -1c
.RI "float \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 403 of file kinetic_proto\&.h\&.
.SH "Field Documentation"
.PP 
.SS "ProtobufCMessage KineticProto_Command_GetLog_Utilization::base"

.PP
Definition at line 404 of file kinetic_proto\&.h\&.
.SS "char* KineticProto_Command_GetLog_Utilization::name"

.PP
Definition at line 405 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_Command_GetLog_Utilization::has_value"

.PP
Definition at line 406 of file kinetic_proto\&.h\&.
.SS "float KineticProto_Command_GetLog_Utilization::value"

.PP
Definition at line 407 of file kinetic_proto\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
