.TH "KineticProto_Command" 3 "Tue Nov 4 2014" "Version v0.8.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticProto_Command \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_proto\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "ProtobufCMessage \fBbase\fP"
.br
.ti -1c
.RI "KineticProto_Command_Header * \fBheader\fP"
.br
.ti -1c
.RI "KineticProto_Command_Body * \fBbody\fP"
.br
.ti -1c
.RI "KineticProto_Command_Status * \fBstatus\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 622 of file kinetic_proto\&.h\&.
.SH "Field Documentation"
.PP 
.SS "ProtobufCMessage KineticProto_Command::base"

.PP
Definition at line 623 of file kinetic_proto\&.h\&.
.SS "KineticProto_Command_Header* KineticProto_Command::header"

.PP
Definition at line 624 of file kinetic_proto\&.h\&.
.SS "KineticProto_Command_Body* KineticProto_Command::body"

.PP
Definition at line 625 of file kinetic_proto\&.h\&.
.SS "KineticProto_Command_Status* KineticProto_Command::status"

.PP
Definition at line 626 of file kinetic_proto\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
