.TH "KineticProto_GetLog_Temperature" 3 "Thu Aug 7 2014" "Version v0.3.3" "protobuf-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticProto_GetLog_Temperature \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_proto\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "ProtobufCMessage \fBbase\fP"
.br
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_current\fP"
.br
.ti -1c
.RI "float \fBcurrent\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_minimum\fP"
.br
.ti -1c
.RI "float \fBminimum\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_maximum\fP"
.br
.ti -1c
.RI "float \fBmaximum\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_target\fP"
.br
.ti -1c
.RI "float \fBtarget\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 354 of file kinetic_proto\&.h\&.
.SH "Field Documentation"
.PP 
.SS "ProtobufCMessage KineticProto_GetLog_Temperature::base"

.PP
Definition at line 356 of file kinetic_proto\&.h\&.
.SS "char* KineticProto_GetLog_Temperature::name"

.PP
Definition at line 357 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_GetLog_Temperature::has_current"

.PP
Definition at line 358 of file kinetic_proto\&.h\&.
.SS "float KineticProto_GetLog_Temperature::current"

.PP
Definition at line 359 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_GetLog_Temperature::has_minimum"

.PP
Definition at line 360 of file kinetic_proto\&.h\&.
.SS "float KineticProto_GetLog_Temperature::minimum"

.PP
Definition at line 361 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_GetLog_Temperature::has_maximum"

.PP
Definition at line 362 of file kinetic_proto\&.h\&.
.SS "float KineticProto_GetLog_Temperature::maximum"

.PP
Definition at line 363 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_GetLog_Temperature::has_target"

.PP
Definition at line 364 of file kinetic_proto\&.h\&.
.SS "float KineticProto_GetLog_Temperature::target"

.PP
Definition at line 365 of file kinetic_proto\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for protobuf-c from the source code\&.
