.TH "KineticProto_GetLog_Capacity" 3 "Tue Jul 15 2014" "Version v0.3.1-beta" "protobuf-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticProto_GetLog_Capacity \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "ProtobufCMessage \fBbase\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_nominalcapacityinbytes\fP"
.br
.ti -1c
.RI "uint64_t \fBnominalcapacityinbytes\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_portionfull\fP"
.br
.ti -1c
.RI "float \fBportionfull\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 371 of file KineticProto\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for protobuf-c from the source code\&.
