.TH "KineticProto_Command_Security_ACL" 3 "Wed Nov 5 2014" "Version v0.8.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticProto_Command_Security_ACL \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_proto\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "ProtobufCMessage \fBbase\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_identity\fP"
.br
.ti -1c
.RI "int64_t \fBidentity\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_key\fP"
.br
.ti -1c
.RI "ProtobufCBinaryData \fBkey\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_hmacAlgorithm\fP"
.br
.ti -1c
.RI "\fBKineticProto_Command_Security_ACL_HMACAlgorithm\fP \fBhmacAlgorithm\fP"
.br
.ti -1c
.RI "size_t \fBn_scope\fP"
.br
.ti -1c
.RI "KineticProto_Command_Security_ACL_Scope ** \fBscope\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_maxPriority\fP"
.br
.ti -1c
.RI "\fBKineticProto_Command_Priority\fP \fBmaxPriority\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 576 of file kinetic_proto\&.h\&.
.SH "Field Documentation"
.PP 
.SS "ProtobufCMessage KineticProto_Command_Security_ACL::base"

.PP
Definition at line 577 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_Command_Security_ACL::has_identity"

.PP
Definition at line 578 of file kinetic_proto\&.h\&.
.SS "int64_t KineticProto_Command_Security_ACL::identity"

.PP
Definition at line 579 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_Command_Security_ACL::has_key"

.PP
Definition at line 580 of file kinetic_proto\&.h\&.
.SS "ProtobufCBinaryData KineticProto_Command_Security_ACL::key"

.PP
Definition at line 581 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_Command_Security_ACL::has_hmacAlgorithm"

.PP
Definition at line 582 of file kinetic_proto\&.h\&.
.SS "\fBKineticProto_Command_Security_ACL_HMACAlgorithm\fP KineticProto_Command_Security_ACL::hmacAlgorithm"

.PP
Definition at line 583 of file kinetic_proto\&.h\&.
.SS "size_t KineticProto_Command_Security_ACL::n_scope"

.PP
Definition at line 584 of file kinetic_proto\&.h\&.
.SS "KineticProto_Command_Security_ACL_Scope** KineticProto_Command_Security_ACL::scope"

.PP
Definition at line 585 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_Command_Security_ACL::has_maxPriority"

.PP
Definition at line 586 of file kinetic_proto\&.h\&.
.SS "\fBKineticProto_Command_Priority\fP KineticProto_Command_Security_ACL::maxPriority"

.PP
Definition at line 587 of file kinetic_proto\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
