.TH "KineticProto_Status" 3 "Fri Aug 8 2014" "Version v0.4.2" "protobuf-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticProto_Status \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_proto\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "ProtobufCMessage \fBbase\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_code\fP"
.br
.ti -1c
.RI "\fBKineticProto_Status_StatusCode\fP \fBcode\fP"
.br
.ti -1c
.RI "char * \fBstatusmessage\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_detailedmessage\fP"
.br
.ti -1c
.RI "ProtobufCBinaryData \fBdetailedmessage\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 222 of file kinetic_proto\&.h\&.
.SH "Field Documentation"
.PP 
.SS "ProtobufCMessage KineticProto_Status::base"

.PP
Definition at line 224 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_Status::has_code"

.PP
Definition at line 225 of file kinetic_proto\&.h\&.
.SS "\fBKineticProto_Status_StatusCode\fP KineticProto_Status::code"

.PP
Definition at line 226 of file kinetic_proto\&.h\&.
.SS "char* KineticProto_Status::statusmessage"

.PP
Definition at line 227 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_Status::has_detailedmessage"

.PP
Definition at line 228 of file kinetic_proto\&.h\&.
.SS "ProtobufCBinaryData KineticProto_Status::detailedmessage"

.PP
Definition at line 229 of file kinetic_proto\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for protobuf-c from the source code\&.
