.TH "KineticProto_Command" 3 "Wed Oct 15 2014" "Version v0.7.0" "protobuf-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticProto_Command \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_proto\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "ProtobufCMessage \fBbase\fP"
.br
.ti -1c
.RI "KineticProto_Header * \fBheader\fP"
.br
.ti -1c
.RI "KineticProto_Body * \fBbody\fP"
.br
.ti -1c
.RI "KineticProto_Status * \fBstatus\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 165 of file kinetic_proto\&.h\&.
.SH "Field Documentation"
.PP 
.SS "ProtobufCMessage KineticProto_Command::base"

.PP
Definition at line 166 of file kinetic_proto\&.h\&.
.SS "KineticProto_Header* KineticProto_Command::header"

.PP
Definition at line 167 of file kinetic_proto\&.h\&.
.SS "KineticProto_Body* KineticProto_Command::body"

.PP
Definition at line 168 of file kinetic_proto\&.h\&.
.SS "KineticProto_Status* KineticProto_Command::status"

.PP
Definition at line 169 of file kinetic_proto\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for protobuf-c from the source code\&.
