.TH "KineticProto_Message_HMACauth" 3 "Tue Dec 9 2014" "Version v0.9.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticProto_Message_HMACauth \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_proto\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "ProtobufCMessage \fBbase\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_identity\fP"
.br
.ti -1c
.RI "int64_t \fBidentity\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_hmac\fP"
.br
.ti -1c
.RI "ProtobufCBinaryData \fBhmac\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 211 of file kinetic_proto\&.h\&.
.SH "Field Documentation"
.PP 
.SS "ProtobufCMessage KineticProto_Message_HMACauth::base"

.PP
Definition at line 212 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_Message_HMACauth::has_identity"

.PP
Definition at line 213 of file kinetic_proto\&.h\&.
.SS "int64_t KineticProto_Message_HMACauth::identity"

.PP
Definition at line 214 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_Message_HMACauth::has_hmac"

.PP
Definition at line 215 of file kinetic_proto\&.h\&.
.SS "ProtobufCBinaryData KineticProto_Message_HMACauth::hmac"

.PP
Definition at line 216 of file kinetic_proto\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
