.TH "KineticProto_Header" 3 "Tue Jul 15 2014" "Version v0.3.1-beta" "protobuf-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticProto_Header \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "ProtobufCMessage \fBbase\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_clusterversion\fP"
.br
.ti -1c
.RI "int64_t \fBclusterversion\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_identity\fP"
.br
.ti -1c
.RI "int64_t \fBidentity\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_connectionid\fP"
.br
.ti -1c
.RI "int64_t \fBconnectionid\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_sequence\fP"
.br
.ti -1c
.RI "int64_t \fBsequence\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_acksequence\fP"
.br
.ti -1c
.RI "int64_t \fBacksequence\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_messagetype\fP"
.br
.ti -1c
.RI "KineticProto_MessageType \fBmessagetype\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_timeout\fP"
.br
.ti -1c
.RI "int64_t \fBtimeout\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_earlyexit\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBearlyexit\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_backgroundscan\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBbackgroundscan\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 182 of file KineticProto\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for protobuf-c from the source code\&.
