.TH "KineticProto_Command_Setup" 3 "Thu Dec 11 2014" "Version v0.9.1" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticProto_Command_Setup \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_proto\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "ProtobufCMessage \fBbase\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_newClusterVersion\fP"
.br
.ti -1c
.RI "int64_t \fBnewClusterVersion\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_firmwareDownload\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBfirmwareDownload\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 347 of file kinetic_proto\&.h\&.
.SH "Field Documentation"
.PP 
.SS "ProtobufCMessage KineticProto_Command_Setup::base"

.PP
Definition at line 348 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_Command_Setup::has_newClusterVersion"

.PP
Definition at line 349 of file kinetic_proto\&.h\&.
.SS "int64_t KineticProto_Command_Setup::newClusterVersion"

.PP
Definition at line 350 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_Command_Setup::has_firmwareDownload"

.PP
Definition at line 351 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_Command_Setup::firmwareDownload"

.PP
Definition at line 352 of file kinetic_proto\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
