.TH "KineticProto_GetLog_Limits" 3 "Wed Jul 30 2014" "Version v0.3.3" "protobuf-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticProto_GetLog_Limits \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_proto\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "ProtobufCMessage \fBbase\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_maxkeysize\fP"
.br
.ti -1c
.RI "uint32_t \fBmaxkeysize\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_maxvaluesize\fP"
.br
.ti -1c
.RI "uint32_t \fBmaxvaluesize\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_maxversionsize\fP"
.br
.ti -1c
.RI "uint32_t \fBmaxversionsize\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_maxtagsize\fP"
.br
.ti -1c
.RI "uint32_t \fBmaxtagsize\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_maxconnections\fP"
.br
.ti -1c
.RI "uint32_t \fBmaxconnections\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_maxoutstandingreadrequests\fP"
.br
.ti -1c
.RI "uint32_t \fBmaxoutstandingreadrequests\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_maxoutstandingwriterequests\fP"
.br
.ti -1c
.RI "uint32_t \fBmaxoutstandingwriterequests\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_maxmessagesize\fP"
.br
.ti -1c
.RI "uint32_t \fBmaxmessagesize\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_maxkeyrangecount\fP"
.br
.ti -1c
.RI "uint32_t \fBmaxkeyrangecount\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 438 of file kinetic_proto\&.h\&.
.SH "Field Documentation"
.PP 
.SS "ProtobufCMessage KineticProto_GetLog_Limits::base"

.PP
Definition at line 440 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_GetLog_Limits::has_maxkeysize"

.PP
Definition at line 441 of file kinetic_proto\&.h\&.
.SS "uint32_t KineticProto_GetLog_Limits::maxkeysize"

.PP
Definition at line 442 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_GetLog_Limits::has_maxvaluesize"

.PP
Definition at line 443 of file kinetic_proto\&.h\&.
.SS "uint32_t KineticProto_GetLog_Limits::maxvaluesize"

.PP
Definition at line 444 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_GetLog_Limits::has_maxversionsize"

.PP
Definition at line 445 of file kinetic_proto\&.h\&.
.SS "uint32_t KineticProto_GetLog_Limits::maxversionsize"

.PP
Definition at line 446 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_GetLog_Limits::has_maxtagsize"

.PP
Definition at line 447 of file kinetic_proto\&.h\&.
.SS "uint32_t KineticProto_GetLog_Limits::maxtagsize"

.PP
Definition at line 448 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_GetLog_Limits::has_maxconnections"

.PP
Definition at line 449 of file kinetic_proto\&.h\&.
.SS "uint32_t KineticProto_GetLog_Limits::maxconnections"

.PP
Definition at line 450 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_GetLog_Limits::has_maxoutstandingreadrequests"

.PP
Definition at line 451 of file kinetic_proto\&.h\&.
.SS "uint32_t KineticProto_GetLog_Limits::maxoutstandingreadrequests"

.PP
Definition at line 452 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_GetLog_Limits::has_maxoutstandingwriterequests"

.PP
Definition at line 453 of file kinetic_proto\&.h\&.
.SS "uint32_t KineticProto_GetLog_Limits::maxoutstandingwriterequests"

.PP
Definition at line 454 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_GetLog_Limits::has_maxmessagesize"

.PP
Definition at line 455 of file kinetic_proto\&.h\&.
.SS "uint32_t KineticProto_GetLog_Limits::maxmessagesize"

.PP
Definition at line 456 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_GetLog_Limits::has_maxkeyrangecount"

.PP
Definition at line 457 of file kinetic_proto\&.h\&.
.SS "uint32_t KineticProto_GetLog_Limits::maxkeyrangecount"

.PP
Definition at line 458 of file kinetic_proto\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for protobuf-c from the source code\&.
