.TH "KineticConnection" 3 "Thu Dec 11 2014" "Version v0.9.1" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticConnection \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_types_internal\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "bool \fBconnected\fP"
.br
.ti -1c
.RI "int \fBsocket\fP"
.br
.ti -1c
.RI "pthread_mutex_t \fBwriteMutex\fP"
.br
.ti -1c
.RI "int64_t \fBconnectionID\fP"
.br
.ti -1c
.RI "int64_t \fBsequence\fP"
.br
.ti -1c
.RI "\fBKineticList\fP \fBpdus\fP"
.br
.ti -1c
.RI "\fBKineticList\fP \fBoperations\fP"
.br
.ti -1c
.RI "\fBKineticSession\fP \fBsession\fP"
.br
.ti -1c
.RI "\fBKineticThread\fP \fBthread\fP"
.br
.ti -1c
.RI "pthread_t \fBthreadID\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 84 of file kinetic_types_internal\&.h\&.
.SH "Field Documentation"
.PP 
.SS "bool KineticConnection::connected"

.PP
Definition at line 85 of file kinetic_types_internal\&.h\&.
.SS "int KineticConnection::socket"

.PP
Definition at line 86 of file kinetic_types_internal\&.h\&.
.SS "pthread_mutex_t KineticConnection::writeMutex"

.PP
Definition at line 87 of file kinetic_types_internal\&.h\&.
.SS "int64_t KineticConnection::connectionID"

.PP
Definition at line 88 of file kinetic_types_internal\&.h\&.
.SS "int64_t KineticConnection::sequence"

.PP
Definition at line 89 of file kinetic_types_internal\&.h\&.
.SS "\fBKineticList\fP KineticConnection::pdus"

.PP
Definition at line 90 of file kinetic_types_internal\&.h\&.
.SS "\fBKineticList\fP KineticConnection::operations"

.PP
Definition at line 91 of file kinetic_types_internal\&.h\&.
.SS "\fBKineticSession\fP KineticConnection::session"

.PP
Definition at line 92 of file kinetic_types_internal\&.h\&.
.SS "\fBKineticThread\fP KineticConnection::thread"

.PP
Definition at line 93 of file kinetic_types_internal\&.h\&.
.SS "pthread_t KineticConnection::threadID"

.PP
Definition at line 94 of file kinetic_types_internal\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
