.TH "KineticProto_Command_GetLog_Capacity" 3 "Wed Nov 5 2014" "Version v0.8.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticProto_Command_GetLog_Capacity \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_proto\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "ProtobufCMessage \fBbase\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_nominalCapacityInBytes\fP"
.br
.ti -1c
.RI "uint64_t \fBnominalCapacityInBytes\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_portionFull\fP"
.br
.ti -1c
.RI "float \fBportionFull\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 431 of file kinetic_proto\&.h\&.
.SH "Field Documentation"
.PP 
.SS "ProtobufCMessage KineticProto_Command_GetLog_Capacity::base"

.PP
Definition at line 432 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_Command_GetLog_Capacity::has_nominalCapacityInBytes"

.PP
Definition at line 433 of file kinetic_proto\&.h\&.
.SS "uint64_t KineticProto_Command_GetLog_Capacity::nominalCapacityInBytes"

.PP
Definition at line 434 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_Command_GetLog_Capacity::has_portionFull"

.PP
Definition at line 435 of file kinetic_proto\&.h\&.
.SS "float KineticProto_Command_GetLog_Capacity::portionFull"

.PP
Definition at line 436 of file kinetic_proto\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
