.TH "KineticOperation" 3 "Fri Mar 13 2015" "Version v0.12.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticOperation \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_types_internal\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "KineticSession * \fBsession\fP"
.br
.ti -1c
.RI "KineticRequest * \fBrequest\fP"
.br
.ti -1c
.RI "\fBKineticResponse\fP * \fBresponse\fP"
.br
.ti -1c
.RI "uint16_t \fBtimeoutSeconds\fP"
.br
.ti -1c
.RI "int64_t \fBpendingClusterVersion\fP"
.br
.ti -1c
.RI "\fBByteArray\fP * \fBpin\fP"
.br
.ti -1c
.RI "\fBKineticEntry\fP * \fBentry\fP"
.br
.ti -1c
.RI "\fBByteBufferArray\fP * \fBbuffers\fP"
.br
.ti -1c
.RI "\fBKineticLogInfo\fP ** \fBdeviceInfo\fP"
.br
.ti -1c
.RI "KineticP2P_Operation * \fBp2pOp\fP"
.br
.ti -1c
.RI "\fBKineticOperationCallback\fP \fBopCallback\fP"
.br
.ti -1c
.RI "\fBKineticCompletionClosure\fP \fBclosure\fP"
.br
.ti -1c
.RI "\fBByteArray\fP \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 178 of file kinetic_types_internal\&.h\&.
.SH "Field Documentation"
.PP 
.SS "KineticSession* KineticOperation::session"

.PP
Definition at line 179 of file kinetic_types_internal\&.h\&.
.SS "KineticRequest* KineticOperation::request"

.PP
Definition at line 180 of file kinetic_types_internal\&.h\&.
.SS "\fBKineticResponse\fP* KineticOperation::response"

.PP
Definition at line 181 of file kinetic_types_internal\&.h\&.
.SS "uint16_t KineticOperation::timeoutSeconds"

.PP
Definition at line 182 of file kinetic_types_internal\&.h\&.
.SS "int64_t KineticOperation::pendingClusterVersion"

.PP
Definition at line 183 of file kinetic_types_internal\&.h\&.
.SS "\fBByteArray\fP* KineticOperation::pin"

.PP
Definition at line 184 of file kinetic_types_internal\&.h\&.
.SS "\fBKineticEntry\fP* KineticOperation::entry"

.PP
Definition at line 185 of file kinetic_types_internal\&.h\&.
.SS "\fBByteBufferArray\fP* KineticOperation::buffers"

.PP
Definition at line 186 of file kinetic_types_internal\&.h\&.
.SS "\fBKineticLogInfo\fP** KineticOperation::deviceInfo"

.PP
Definition at line 187 of file kinetic_types_internal\&.h\&.
.SS "KineticP2P_Operation* KineticOperation::p2pOp"

.PP
Definition at line 188 of file kinetic_types_internal\&.h\&.
.SS "\fBKineticOperationCallback\fP KineticOperation::opCallback"

.PP
Definition at line 189 of file kinetic_types_internal\&.h\&.
.SS "\fBKineticCompletionClosure\fP KineticOperation::closure"

.PP
Definition at line 190 of file kinetic_types_internal\&.h\&.
.SS "\fBByteArray\fP KineticOperation::value"

.PP
Definition at line 191 of file kinetic_types_internal\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
