.TH "KineticProto_P2POperation_Operation" 3 "Thu Aug 7 2014" "Version v0.3.3" "protobuf-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticProto_P2POperation_Operation \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_proto\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "ProtobufCMessage \fBbase\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_key\fP"
.br
.ti -1c
.RI "ProtobufCBinaryData \fBkey\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_version\fP"
.br
.ti -1c
.RI "ProtobufCBinaryData \fBversion\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_newkey\fP"
.br
.ti -1c
.RI "ProtobufCBinaryData \fBnewkey\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_force\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBforce\fP"
.br
.ti -1c
.RI "KineticProto_Status * \fBstatus\fP"
.br
.ti -1c
.RI "KineticProto_P2POperation * \fBp2pop\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 299 of file kinetic_proto\&.h\&.
.SH "Field Documentation"
.PP 
.SS "ProtobufCMessage KineticProto_P2POperation_Operation::base"

.PP
Definition at line 301 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_P2POperation_Operation::has_key"

.PP
Definition at line 302 of file kinetic_proto\&.h\&.
.SS "ProtobufCBinaryData KineticProto_P2POperation_Operation::key"

.PP
Definition at line 303 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_P2POperation_Operation::has_version"

.PP
Definition at line 304 of file kinetic_proto\&.h\&.
.SS "ProtobufCBinaryData KineticProto_P2POperation_Operation::version"

.PP
Definition at line 305 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_P2POperation_Operation::has_newkey"

.PP
Definition at line 306 of file kinetic_proto\&.h\&.
.SS "ProtobufCBinaryData KineticProto_P2POperation_Operation::newkey"

.PP
Definition at line 307 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_P2POperation_Operation::has_force"

.PP
Definition at line 308 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_P2POperation_Operation::force"

.PP
Definition at line 309 of file kinetic_proto\&.h\&.
.SS "KineticProto_Status* KineticProto_P2POperation_Operation::status"

.PP
Definition at line 310 of file kinetic_proto\&.h\&.
.SS "KineticProto_P2POperation* KineticProto_P2POperation_Operation::p2pop"

.PP
Definition at line 311 of file kinetic_proto\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for protobuf-c from the source code\&.
