.TH "KineticP2P_Operation" 3 "Fri Mar 13 2015" "Version v0.12.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticP2P_Operation \- 
.PP
Peer-to-peer opearation instance\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBKineticP2P_Peer\fP \fBpeer\fP"
.br
.ti -1c
.RI "size_t \fBnumOperations\fP"
.br
.RI "\fI
.PP
.RS 4
Peer to perform operations with 
.RE
.PP
\fP"
.ti -1c
.RI "\fBKineticP2P_OperationData\fP * \fBoperations\fP"
.br
.RI "\fI
.PP
.RS 4
Number of operations in operations array 
.RE
.PP
\fP"
.in -1c
.SH "Detailed Description"
.PP 
Peer-to-peer opearation instance\&. 
.PP
Definition at line 470 of file kinetic_types\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBKineticP2P_Peer\fP KineticP2P_Operation::peer"

.PP
Definition at line 471 of file kinetic_types\&.h\&.
.SS "size_t KineticP2P_Operation::numOperations"

.PP

.PP
.RS 4
Peer to perform operations with 
.RE
.PP

.PP
Definition at line 472 of file kinetic_types\&.h\&.
.SS "\fBKineticP2P_OperationData\fP* KineticP2P_Operation::operations"

.PP

.PP
.RS 4
Number of operations in operations array 
.RE
.PP

.PP
Definition at line 473 of file kinetic_types\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
