.TH "KineticProto_GetLog_Statistics" 3 "Fri Aug 8 2014" "Version v0.4.3" "protobuf-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticProto_GetLog_Statistics \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_proto\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "ProtobufCMessage \fBbase\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_messagetype\fP"
.br
.ti -1c
.RI "\fBKineticProto_MessageType\fP \fBmessagetype\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_count\fP"
.br
.ti -1c
.RI "uint64_t \fBcount\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_bytes\fP"
.br
.ti -1c
.RI "uint64_t \fBbytes\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 424 of file kinetic_proto\&.h\&.
.SH "Field Documentation"
.PP 
.SS "ProtobufCMessage KineticProto_GetLog_Statistics::base"

.PP
Definition at line 426 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_GetLog_Statistics::has_messagetype"

.PP
Definition at line 427 of file kinetic_proto\&.h\&.
.SS "\fBKineticProto_MessageType\fP KineticProto_GetLog_Statistics::messagetype"

.PP
Definition at line 428 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_GetLog_Statistics::has_count"

.PP
Definition at line 429 of file kinetic_proto\&.h\&.
.SS "uint64_t KineticProto_GetLog_Statistics::count"

.PP
Definition at line 430 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_GetLog_Statistics::has_bytes"

.PP
Definition at line 431 of file kinetic_proto\&.h\&.
.SS "uint64_t KineticProto_GetLog_Statistics::bytes"

.PP
Definition at line 432 of file kinetic_proto\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for protobuf-c from the source code\&.
