.TH "KineticProto_Security_ACL" 3 "Wed Sep 10 2014" "Version v0.6.0" "protobuf-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticProto_Security_ACL \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_proto\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "ProtobufCMessage \fBbase\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_identity\fP"
.br
.ti -1c
.RI "int64_t \fBidentity\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_key\fP"
.br
.ti -1c
.RI "ProtobufCBinaryData \fBkey\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_hmacAlgorithm\fP"
.br
.ti -1c
.RI "\fBKineticProto_Security_ACL_HMACAlgorithm\fP \fBhmacAlgorithm\fP"
.br
.ti -1c
.RI "size_t \fBn_scope\fP"
.br
.ti -1c
.RI "KineticProto_Security_ACL_Scope ** \fBscope\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 528 of file kinetic_proto\&.h\&.
.SH "Field Documentation"
.PP 
.SS "ProtobufCMessage KineticProto_Security_ACL::base"

.PP
Definition at line 530 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_Security_ACL::has_identity"

.PP
Definition at line 531 of file kinetic_proto\&.h\&.
.SS "int64_t KineticProto_Security_ACL::identity"

.PP
Definition at line 532 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_Security_ACL::has_key"

.PP
Definition at line 533 of file kinetic_proto\&.h\&.
.SS "ProtobufCBinaryData KineticProto_Security_ACL::key"

.PP
Definition at line 534 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_Security_ACL::has_hmacAlgorithm"

.PP
Definition at line 535 of file kinetic_proto\&.h\&.
.SS "\fBKineticProto_Security_ACL_HMACAlgorithm\fP KineticProto_Security_ACL::hmacAlgorithm"

.PP
Definition at line 536 of file kinetic_proto\&.h\&.
.SS "size_t KineticProto_Security_ACL::n_scope"

.PP
Definition at line 537 of file kinetic_proto\&.h\&.
.SS "KineticProto_Security_ACL_Scope** KineticProto_Security_ACL::scope"

.PP
Definition at line 538 of file kinetic_proto\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for protobuf-c from the source code\&.
