.TH "KineticProto_Command_Security_ACL_Scope" 3 "Tue Dec 9 2014" "Version v0.9.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticProto_Command_Security_ACL_Scope \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_proto\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "ProtobufCMessage \fBbase\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_offset\fP"
.br
.ti -1c
.RI "int64_t \fBoffset\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_value\fP"
.br
.ti -1c
.RI "ProtobufCBinaryData \fBvalue\fP"
.br
.ti -1c
.RI "size_t \fBn_permission\fP"
.br
.ti -1c
.RI "\fBKineticProto_Command_Security_ACL_Permission\fP * \fBpermission\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_TlsRequired\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBTlsRequired\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 560 of file kinetic_proto\&.h\&.
.SH "Field Documentation"
.PP 
.SS "ProtobufCMessage KineticProto_Command_Security_ACL_Scope::base"

.PP
Definition at line 561 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_Command_Security_ACL_Scope::has_offset"

.PP
Definition at line 562 of file kinetic_proto\&.h\&.
.SS "int64_t KineticProto_Command_Security_ACL_Scope::offset"

.PP
Definition at line 563 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_Command_Security_ACL_Scope::has_value"

.PP
Definition at line 564 of file kinetic_proto\&.h\&.
.SS "ProtobufCBinaryData KineticProto_Command_Security_ACL_Scope::value"

.PP
Definition at line 565 of file kinetic_proto\&.h\&.
.SS "size_t KineticProto_Command_Security_ACL_Scope::n_permission"

.PP
Definition at line 566 of file kinetic_proto\&.h\&.
.SS "\fBKineticProto_Command_Security_ACL_Permission\fP* KineticProto_Command_Security_ACL_Scope::permission"

.PP
Definition at line 567 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_Command_Security_ACL_Scope::has_TlsRequired"

.PP
Definition at line 568 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_Command_Security_ACL_Scope::TlsRequired"

.PP
Definition at line 569 of file kinetic_proto\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
