.TH "KineticListItem" 3 "Tue Nov 4 2014" "Version v0.8.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticListItem \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_types_internal\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "KineticListItem * \fBnext\fP"
.br
.ti -1c
.RI "KineticListItem * \fBprevious\fP"
.br
.ti -1c
.RI "void * \fBdata\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 59 of file kinetic_types_internal\&.h\&.
.SH "Field Documentation"
.PP 
.SS "KineticListItem* KineticListItem::next"

.PP
Definition at line 60 of file kinetic_types_internal\&.h\&.
.SS "KineticListItem* KineticListItem::previous"

.PP
Definition at line 61 of file kinetic_types_internal\&.h\&.
.SS "void* KineticListItem::data"

.PP
Definition at line 62 of file kinetic_types_internal\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
