.TH "KineticProto_GetLog_Configuration_Interface" 3 "Thu Sep 11 2014" "Version v0.6.0-beta-2" "protobuf-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticProto_GetLog_Configuration_Interface \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_proto\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "ProtobufCMessage \fBbase\fP"
.br
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_MAC\fP"
.br
.ti -1c
.RI "ProtobufCBinaryData \fBMAC\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_ipv4Address\fP"
.br
.ti -1c
.RI "ProtobufCBinaryData \fBipv4Address\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_ipv6Address\fP"
.br
.ti -1c
.RI "ProtobufCBinaryData \fBipv6Address\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 390 of file kinetic_proto\&.h\&.
.SH "Field Documentation"
.PP 
.SS "ProtobufCMessage KineticProto_GetLog_Configuration_Interface::base"

.PP
Definition at line 392 of file kinetic_proto\&.h\&.
.SS "char* KineticProto_GetLog_Configuration_Interface::name"

.PP
Definition at line 393 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_GetLog_Configuration_Interface::has_MAC"

.PP
Definition at line 394 of file kinetic_proto\&.h\&.
.SS "ProtobufCBinaryData KineticProto_GetLog_Configuration_Interface::MAC"

.PP
Definition at line 395 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_GetLog_Configuration_Interface::has_ipv4Address"

.PP
Definition at line 396 of file kinetic_proto\&.h\&.
.SS "ProtobufCBinaryData KineticProto_GetLog_Configuration_Interface::ipv4Address"

.PP
Definition at line 397 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_GetLog_Configuration_Interface::has_ipv6Address"

.PP
Definition at line 398 of file kinetic_proto\&.h\&.
.SS "ProtobufCBinaryData KineticProto_GetLog_Configuration_Interface::ipv6Address"

.PP
Definition at line 399 of file kinetic_proto\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for protobuf-c from the source code\&.
