.TH "KineticProto_Message_PINauth" 3 "Tue Mar 3 2015" "Version v0.12.0-beta" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticProto_Message_PINauth \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_proto\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "ProtobufCMessage \fBbase\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_pin\fP"
.br
.ti -1c
.RI "ProtobufCBinaryData \fBpin\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 223 of file kinetic_proto\&.h\&.
.SH "Field Documentation"
.PP 
.SS "ProtobufCMessage KineticProto_Message_PINauth::base"

.PP
Definition at line 224 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_Message_PINauth::has_pin"

.PP
Definition at line 225 of file kinetic_proto\&.h\&.
.SS "ProtobufCBinaryData KineticProto_Message_PINauth::pin"

.PP
Definition at line 226 of file kinetic_proto\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
