.TH "KineticProto_GetLog_Configuration" 3 "Wed Sep 10 2014" "Version v0.6.0" "protobuf-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticProto_GetLog_Configuration \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_proto\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "ProtobufCMessage \fBbase\fP"
.br
.ti -1c
.RI "char * \fBvendor\fP"
.br
.ti -1c
.RI "char * \fBmodel\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_serialNumber\fP"
.br
.ti -1c
.RI "ProtobufCBinaryData \fBserialNumber\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_worldWideName\fP"
.br
.ti -1c
.RI "ProtobufCBinaryData \fBworldWideName\fP"
.br
.ti -1c
.RI "char * \fBversion\fP"
.br
.ti -1c
.RI "char * \fBcompilationDate\fP"
.br
.ti -1c
.RI "char * \fBsourceHash\fP"
.br
.ti -1c
.RI "char * \fBprotocolVersion\fP"
.br
.ti -1c
.RI "char * \fBprotocolCompilationDate\fP"
.br
.ti -1c
.RI "char * \fBprotocolSourceHash\fP"
.br
.ti -1c
.RI "size_t \fBn_interface\fP"
.br
.ti -1c
.RI "KineticProto_GetLog_Configuration_Interface ** \fBinterface\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_port\fP"
.br
.ti -1c
.RI "int32_t \fBport\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_tlsPort\fP"
.br
.ti -1c
.RI "int32_t \fBtlsPort\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 406 of file kinetic_proto\&.h\&.
.SH "Field Documentation"
.PP 
.SS "ProtobufCMessage KineticProto_GetLog_Configuration::base"

.PP
Definition at line 408 of file kinetic_proto\&.h\&.
.SS "char* KineticProto_GetLog_Configuration::vendor"

.PP
Definition at line 409 of file kinetic_proto\&.h\&.
.SS "char* KineticProto_GetLog_Configuration::model"

.PP
Definition at line 410 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_GetLog_Configuration::has_serialNumber"

.PP
Definition at line 411 of file kinetic_proto\&.h\&.
.SS "ProtobufCBinaryData KineticProto_GetLog_Configuration::serialNumber"

.PP
Definition at line 412 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_GetLog_Configuration::has_worldWideName"

.PP
Definition at line 413 of file kinetic_proto\&.h\&.
.SS "ProtobufCBinaryData KineticProto_GetLog_Configuration::worldWideName"

.PP
Definition at line 414 of file kinetic_proto\&.h\&.
.SS "char* KineticProto_GetLog_Configuration::version"

.PP
Definition at line 415 of file kinetic_proto\&.h\&.
.SS "char* KineticProto_GetLog_Configuration::compilationDate"

.PP
Definition at line 416 of file kinetic_proto\&.h\&.
.SS "char* KineticProto_GetLog_Configuration::sourceHash"

.PP
Definition at line 417 of file kinetic_proto\&.h\&.
.SS "char* KineticProto_GetLog_Configuration::protocolVersion"

.PP
Definition at line 418 of file kinetic_proto\&.h\&.
.SS "char* KineticProto_GetLog_Configuration::protocolCompilationDate"

.PP
Definition at line 419 of file kinetic_proto\&.h\&.
.SS "char* KineticProto_GetLog_Configuration::protocolSourceHash"

.PP
Definition at line 420 of file kinetic_proto\&.h\&.
.SS "size_t KineticProto_GetLog_Configuration::n_interface"

.PP
Definition at line 421 of file kinetic_proto\&.h\&.
.SS "KineticProto_GetLog_Configuration_Interface** KineticProto_GetLog_Configuration::interface"

.PP
Definition at line 422 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_GetLog_Configuration::has_port"

.PP
Definition at line 423 of file kinetic_proto\&.h\&.
.SS "int32_t KineticProto_GetLog_Configuration::port"

.PP
Definition at line 424 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_GetLog_Configuration::has_tlsPort"

.PP
Definition at line 425 of file kinetic_proto\&.h\&.
.SS "int32_t KineticProto_GetLog_Configuration::tlsPort"

.PP
Definition at line 426 of file kinetic_proto\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for protobuf-c from the source code\&.
