.TH "KineticProto_Body" 3 "Fri Aug 8 2014" "Version v0.4.2" "protobuf-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticProto_Body \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_proto\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "ProtobufCMessage \fBbase\fP"
.br
.ti -1c
.RI "KineticProto_KeyValue * \fBkeyvalue\fP"
.br
.ti -1c
.RI "KineticProto_Range * \fBrange\fP"
.br
.ti -1c
.RI "KineticProto_Setup * \fBsetup\fP"
.br
.ti -1c
.RI "KineticProto_P2POperation * \fBp2poperation\fP"
.br
.ti -1c
.RI "KineticProto_GetLog * \fBgetlog\fP"
.br
.ti -1c
.RI "KineticProto_Security * \fBsecurity\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 208 of file kinetic_proto\&.h\&.
.SH "Field Documentation"
.PP 
.SS "ProtobufCMessage KineticProto_Body::base"

.PP
Definition at line 210 of file kinetic_proto\&.h\&.
.SS "KineticProto_KeyValue* KineticProto_Body::keyvalue"

.PP
Definition at line 211 of file kinetic_proto\&.h\&.
.SS "KineticProto_Range* KineticProto_Body::range"

.PP
Definition at line 212 of file kinetic_proto\&.h\&.
.SS "KineticProto_Setup* KineticProto_Body::setup"

.PP
Definition at line 213 of file kinetic_proto\&.h\&.
.SS "KineticProto_P2POperation* KineticProto_Body::p2poperation"

.PP
Definition at line 214 of file kinetic_proto\&.h\&.
.SS "KineticProto_GetLog* KineticProto_Body::getlog"

.PP
Definition at line 215 of file kinetic_proto\&.h\&.
.SS "KineticProto_Security* KineticProto_Body::security"

.PP
Definition at line 216 of file kinetic_proto\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for protobuf-c from the source code\&.
