.TH "KineticClient" 3 "Wed Feb 11 2015" "Version v0.11.1" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticClient \- 
.PP
Handle to the kinetic client, which is shared by all connections\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_types_internal\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBbus\fP * \fBbus\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Handle to the kinetic client, which is shared by all connections\&. 
.PP
Definition at line 59 of file kinetic_types_internal\&.h\&.
.SH "Field Documentation"
.PP 
.SS "struct \fBbus\fP* KineticClient::bus"

.PP
Definition at line 60 of file kinetic_types_internal\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
