.TH "KineticProto_Message" 3 "Tue Nov 4 2014" "Version v0.8.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticProto_Message \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_proto\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "ProtobufCMessage \fBbase\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_authType\fP"
.br
.ti -1c
.RI "\fBKineticProto_Message_AuthType\fP \fBauthType\fP"
.br
.ti -1c
.RI "KineticProto_Message_HMACauth * \fBhmacAuth\fP"
.br
.ti -1c
.RI "KineticProto_Message_PINauth * \fBpinAuth\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_commandBytes\fP"
.br
.ti -1c
.RI "ProtobufCBinaryData \fBcommandBytes\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 233 of file kinetic_proto\&.h\&.
.SH "Field Documentation"
.PP 
.SS "ProtobufCMessage KineticProto_Message::base"

.PP
Definition at line 234 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_Message::has_authType"

.PP
Definition at line 235 of file kinetic_proto\&.h\&.
.SS "\fBKineticProto_Message_AuthType\fP KineticProto_Message::authType"

.PP
Definition at line 236 of file kinetic_proto\&.h\&.
.SS "KineticProto_Message_HMACauth* KineticProto_Message::hmacAuth"

.PP
Definition at line 237 of file kinetic_proto\&.h\&.
.SS "KineticProto_Message_PINauth* KineticProto_Message::pinAuth"

.PP
Definition at line 238 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_Message::has_commandBytes"

.PP
Definition at line 239 of file kinetic_proto\&.h\&.
.SS "ProtobufCBinaryData KineticProto_Message::commandBytes"

.PP
Definition at line 240 of file kinetic_proto\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
