.TH "KineticProto_GetLog" 3 "Fri Aug 8 2014" "Version v0.4.2" "protobuf-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticProto_GetLog \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_proto\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "ProtobufCMessage \fBbase\fP"
.br
.ti -1c
.RI "size_t \fBn_type\fP"
.br
.ti -1c
.RI "\fBKineticProto_GetLog_Type\fP * \fBtype\fP"
.br
.ti -1c
.RI "size_t \fBn_utilization\fP"
.br
.ti -1c
.RI "KineticProto_GetLog_Utilization ** \fButilization\fP"
.br
.ti -1c
.RI "size_t \fBn_temperature\fP"
.br
.ti -1c
.RI "KineticProto_GetLog_Temperature ** \fBtemperature\fP"
.br
.ti -1c
.RI "KineticProto_GetLog_Capacity * \fBcapacity\fP"
.br
.ti -1c
.RI "KineticProto_GetLog_Configuration * \fBconfiguration\fP"
.br
.ti -1c
.RI "size_t \fBn_statistics\fP"
.br
.ti -1c
.RI "KineticProto_GetLog_Statistics ** \fBstatistics\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_messages\fP"
.br
.ti -1c
.RI "ProtobufCBinaryData \fBmessages\fP"
.br
.ti -1c
.RI "KineticProto_GetLog_Limits * \fBlimits\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 464 of file kinetic_proto\&.h\&.
.SH "Field Documentation"
.PP 
.SS "ProtobufCMessage KineticProto_GetLog::base"

.PP
Definition at line 466 of file kinetic_proto\&.h\&.
.SS "size_t KineticProto_GetLog::n_type"

.PP
Definition at line 467 of file kinetic_proto\&.h\&.
.SS "\fBKineticProto_GetLog_Type\fP* KineticProto_GetLog::type"

.PP
Definition at line 468 of file kinetic_proto\&.h\&.
.SS "size_t KineticProto_GetLog::n_utilization"

.PP
Definition at line 469 of file kinetic_proto\&.h\&.
.SS "KineticProto_GetLog_Utilization** KineticProto_GetLog::utilization"

.PP
Definition at line 470 of file kinetic_proto\&.h\&.
.SS "size_t KineticProto_GetLog::n_temperature"

.PP
Definition at line 471 of file kinetic_proto\&.h\&.
.SS "KineticProto_GetLog_Temperature** KineticProto_GetLog::temperature"

.PP
Definition at line 472 of file kinetic_proto\&.h\&.
.SS "KineticProto_GetLog_Capacity* KineticProto_GetLog::capacity"

.PP
Definition at line 473 of file kinetic_proto\&.h\&.
.SS "KineticProto_GetLog_Configuration* KineticProto_GetLog::configuration"

.PP
Definition at line 474 of file kinetic_proto\&.h\&.
.SS "size_t KineticProto_GetLog::n_statistics"

.PP
Definition at line 475 of file kinetic_proto\&.h\&.
.SS "KineticProto_GetLog_Statistics** KineticProto_GetLog::statistics"

.PP
Definition at line 476 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_GetLog::has_messages"

.PP
Definition at line 477 of file kinetic_proto\&.h\&.
.SS "ProtobufCBinaryData KineticProto_GetLog::messages"

.PP
Definition at line 478 of file kinetic_proto\&.h\&.
.SS "KineticProto_GetLog_Limits* KineticProto_GetLog::limits"

.PP
Definition at line 479 of file kinetic_proto\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for protobuf-c from the source code\&.
