.TH "KineticProto_Range" 3 "Tue Jul 15 2014" "Version v0.3.1-beta" "protobuf-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticProto_Range \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "ProtobufCMessage \fBbase\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_startkey\fP"
.br
.ti -1c
.RI "ProtobufCBinaryData \fBstartkey\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_endkey\fP"
.br
.ti -1c
.RI "ProtobufCBinaryData \fBendkey\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_startkeyinclusive\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBstartkeyinclusive\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_endkeyinclusive\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBendkeyinclusive\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_maxreturned\fP"
.br
.ti -1c
.RI "int32_t \fBmaxreturned\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_reverse\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBreverse\fP"
.br
.ti -1c
.RI "size_t \fBn_key\fP"
.br
.ti -1c
.RI "ProtobufCBinaryData * \fBkey\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 259 of file KineticProto\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for protobuf-c from the source code\&.
