.TH "KineticProto_Header" 3 "Wed Jul 30 2014" "Version v0.3.3" "protobuf-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticProto_Header \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_proto\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "ProtobufCMessage \fBbase\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_clusterversion\fP"
.br
.ti -1c
.RI "int64_t \fBclusterversion\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_identity\fP"
.br
.ti -1c
.RI "int64_t \fBidentity\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_connectionid\fP"
.br
.ti -1c
.RI "int64_t \fBconnectionid\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_sequence\fP"
.br
.ti -1c
.RI "int64_t \fBsequence\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_acksequence\fP"
.br
.ti -1c
.RI "int64_t \fBacksequence\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_messagetype\fP"
.br
.ti -1c
.RI "\fBKineticProto_MessageType\fP \fBmessagetype\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_timeout\fP"
.br
.ti -1c
.RI "int64_t \fBtimeout\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_earlyexit\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBearlyexit\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_backgroundscan\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBbackgroundscan\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 182 of file kinetic_proto\&.h\&.
.SH "Field Documentation"
.PP 
.SS "ProtobufCMessage KineticProto_Header::base"

.PP
Definition at line 184 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_Header::has_clusterversion"

.PP
Definition at line 185 of file kinetic_proto\&.h\&.
.SS "int64_t KineticProto_Header::clusterversion"

.PP
Definition at line 186 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_Header::has_identity"

.PP
Definition at line 187 of file kinetic_proto\&.h\&.
.SS "int64_t KineticProto_Header::identity"

.PP
Definition at line 188 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_Header::has_connectionid"

.PP
Definition at line 189 of file kinetic_proto\&.h\&.
.SS "int64_t KineticProto_Header::connectionid"

.PP
Definition at line 190 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_Header::has_sequence"

.PP
Definition at line 191 of file kinetic_proto\&.h\&.
.SS "int64_t KineticProto_Header::sequence"

.PP
Definition at line 192 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_Header::has_acksequence"

.PP
Definition at line 193 of file kinetic_proto\&.h\&.
.SS "int64_t KineticProto_Header::acksequence"

.PP
Definition at line 194 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_Header::has_messagetype"

.PP
Definition at line 195 of file kinetic_proto\&.h\&.
.SS "\fBKineticProto_MessageType\fP KineticProto_Header::messagetype"

.PP
Definition at line 196 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_Header::has_timeout"

.PP
Definition at line 197 of file kinetic_proto\&.h\&.
.SS "int64_t KineticProto_Header::timeout"

.PP
Definition at line 198 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_Header::has_earlyexit"

.PP
Definition at line 199 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_Header::earlyexit"

.PP
Definition at line 200 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_Header::has_backgroundscan"

.PP
Definition at line 201 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_Header::backgroundscan"

.PP
Definition at line 202 of file kinetic_proto\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for protobuf-c from the source code\&.
