.TH "KineticOperation" 3 "Mon Mar 2 2015" "Version v0.12.0-beta" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticOperation \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_types_internal\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "KineticConnection * \fBconnection\fP"
.br
.ti -1c
.RI "KineticRequest * \fBrequest\fP"
.br
.ti -1c
.RI "\fBKineticResponse\fP * \fBresponse\fP"
.br
.ti -1c
.RI "uint16_t \fBtimeoutSeconds\fP"
.br
.ti -1c
.RI "int64_t \fBpendingClusterVersion\fP"
.br
.ti -1c
.RI "\fBByteArray\fP * \fBpin\fP"
.br
.ti -1c
.RI "\fBKineticEntry\fP * \fBentry\fP"
.br
.ti -1c
.RI "\fBByteBufferArray\fP * \fBbuffers\fP"
.br
.ti -1c
.RI "\fBKineticLogInfo\fP ** \fBdeviceInfo\fP"
.br
.ti -1c
.RI "KineticP2P_Operation * \fBp2pOp\fP"
.br
.ti -1c
.RI "\fBKineticOperationCallback\fP \fBcallback\fP"
.br
.ti -1c
.RI "\fBKineticCompletionClosure\fP \fBclosure\fP"
.br
.ti -1c
.RI "\fBByteArray\fP \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 191 of file kinetic_types_internal\&.h\&.
.SH "Field Documentation"
.PP 
.SS "KineticConnection* KineticOperation::connection"

.PP
Definition at line 192 of file kinetic_types_internal\&.h\&.
.SS "KineticRequest* KineticOperation::request"

.PP
Definition at line 193 of file kinetic_types_internal\&.h\&.
.SS "\fBKineticResponse\fP* KineticOperation::response"

.PP
Definition at line 194 of file kinetic_types_internal\&.h\&.
.SS "uint16_t KineticOperation::timeoutSeconds"

.PP
Definition at line 195 of file kinetic_types_internal\&.h\&.
.SS "int64_t KineticOperation::pendingClusterVersion"

.PP
Definition at line 196 of file kinetic_types_internal\&.h\&.
.SS "\fBByteArray\fP* KineticOperation::pin"

.PP
Definition at line 197 of file kinetic_types_internal\&.h\&.
.SS "\fBKineticEntry\fP* KineticOperation::entry"

.PP
Definition at line 198 of file kinetic_types_internal\&.h\&.
.SS "\fBByteBufferArray\fP* KineticOperation::buffers"

.PP
Definition at line 199 of file kinetic_types_internal\&.h\&.
.SS "\fBKineticLogInfo\fP** KineticOperation::deviceInfo"

.PP
Definition at line 200 of file kinetic_types_internal\&.h\&.
.SS "KineticP2P_Operation* KineticOperation::p2pOp"

.PP
Definition at line 201 of file kinetic_types_internal\&.h\&.
.SS "\fBKineticOperationCallback\fP KineticOperation::callback"

.PP
Definition at line 202 of file kinetic_types_internal\&.h\&.
.SS "\fBKineticCompletionClosure\fP KineticOperation::closure"

.PP
Definition at line 203 of file kinetic_types_internal\&.h\&.
.SS "\fBByteArray\fP KineticOperation::value"

.PP
Definition at line 204 of file kinetic_types_internal\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
