.TH "KineticProto_P2POperation_Peer" 3 "Wed Oct 15 2014" "Version v0.7.0" "protobuf-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticProto_P2POperation_Peer \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_proto\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "ProtobufCMessage \fBbase\fP"
.br
.ti -1c
.RI "char * \fBhostname\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_port\fP"
.br
.ti -1c
.RI "int32_t \fBport\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_tls\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBtls\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 311 of file kinetic_proto\&.h\&.
.SH "Field Documentation"
.PP 
.SS "ProtobufCMessage KineticProto_P2POperation_Peer::base"

.PP
Definition at line 312 of file kinetic_proto\&.h\&.
.SS "char* KineticProto_P2POperation_Peer::hostname"

.PP
Definition at line 313 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_P2POperation_Peer::has_port"

.PP
Definition at line 314 of file kinetic_proto\&.h\&.
.SS "int32_t KineticProto_P2POperation_Peer::port"

.PP
Definition at line 315 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_P2POperation_Peer::has_tls"

.PP
Definition at line 316 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_P2POperation_Peer::tls"

.PP
Definition at line 317 of file kinetic_proto\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for protobuf-c from the source code\&.
