.TH "KineticProto_Command_PinOperation" 3 "Mon Mar 2 2015" "Version v0.12.0-beta" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticProto_Command_PinOperation \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_proto\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "ProtobufCMessage \fBbase\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_pinOpType\fP"
.br
.ti -1c
.RI "\fBKineticProto_Command_PinOperation_PinOpType\fP \fBpinOpType\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 612 of file kinetic_proto\&.h\&.
.SH "Field Documentation"
.PP 
.SS "ProtobufCMessage KineticProto_Command_PinOperation::base"

.PP
Definition at line 613 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_Command_PinOperation::has_pinOpType"

.PP
Definition at line 614 of file kinetic_proto\&.h\&.
.SS "\fBKineticProto_Command_PinOperation_PinOpType\fP KineticProto_Command_PinOperation::pinOpType"

.PP
Definition at line 615 of file kinetic_proto\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
