.TH "KineticProto_Status" 3 "Thu Sep 11 2014" "Version v0.6.0-beta-2" "protobuf-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticProto_Status \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_proto\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "ProtobufCMessage \fBbase\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_code\fP"
.br
.ti -1c
.RI "\fBKineticProto_Status_StatusCode\fP \fBcode\fP"
.br
.ti -1c
.RI "char * \fBstatusMessage\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_detailedMessage\fP"
.br
.ti -1c
.RI "ProtobufCBinaryData \fBdetailedMessage\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 219 of file kinetic_proto\&.h\&.
.SH "Field Documentation"
.PP 
.SS "ProtobufCMessage KineticProto_Status::base"

.PP
Definition at line 221 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_Status::has_code"

.PP
Definition at line 222 of file kinetic_proto\&.h\&.
.SS "\fBKineticProto_Status_StatusCode\fP KineticProto_Status::code"

.PP
Definition at line 223 of file kinetic_proto\&.h\&.
.SS "char* KineticProto_Status::statusMessage"

.PP
Definition at line 224 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_Status::has_detailedMessage"

.PP
Definition at line 225 of file kinetic_proto\&.h\&.
.SS "ProtobufCBinaryData KineticProto_Status::detailedMessage"

.PP
Definition at line 226 of file kinetic_proto\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for protobuf-c from the source code\&.
