.TH "KineticProto_Command_GetLog_Limits" 3 "Thu Dec 11 2014" "Version v0.9.1" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticProto_Command_GetLog_Limits \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_proto\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "ProtobufCMessage \fBbase\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_maxKeySize\fP"
.br
.ti -1c
.RI "uint32_t \fBmaxKeySize\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_maxValueSize\fP"
.br
.ti -1c
.RI "uint32_t \fBmaxValueSize\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_maxVersionSize\fP"
.br
.ti -1c
.RI "uint32_t \fBmaxVersionSize\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_maxTagSize\fP"
.br
.ti -1c
.RI "uint32_t \fBmaxTagSize\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_maxConnections\fP"
.br
.ti -1c
.RI "uint32_t \fBmaxConnections\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_maxOutstandingReadRequests\fP"
.br
.ti -1c
.RI "uint32_t \fBmaxOutstandingReadRequests\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_maxOutstandingWriteRequests\fP"
.br
.ti -1c
.RI "uint32_t \fBmaxOutstandingWriteRequests\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_maxMessageSize\fP"
.br
.ti -1c
.RI "uint32_t \fBmaxMessageSize\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_maxKeyRangeCount\fP"
.br
.ti -1c
.RI "uint32_t \fBmaxKeyRangeCount\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_maxIdentityCount\fP"
.br
.ti -1c
.RI "uint32_t \fBmaxIdentityCount\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_maxPinSize\fP"
.br
.ti -1c
.RI "uint32_t \fBmaxPinSize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 498 of file kinetic_proto\&.h\&.
.SH "Field Documentation"
.PP 
.SS "ProtobufCMessage KineticProto_Command_GetLog_Limits::base"

.PP
Definition at line 499 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_Command_GetLog_Limits::has_maxKeySize"

.PP
Definition at line 500 of file kinetic_proto\&.h\&.
.SS "uint32_t KineticProto_Command_GetLog_Limits::maxKeySize"

.PP
Definition at line 501 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_Command_GetLog_Limits::has_maxValueSize"

.PP
Definition at line 502 of file kinetic_proto\&.h\&.
.SS "uint32_t KineticProto_Command_GetLog_Limits::maxValueSize"

.PP
Definition at line 503 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_Command_GetLog_Limits::has_maxVersionSize"

.PP
Definition at line 504 of file kinetic_proto\&.h\&.
.SS "uint32_t KineticProto_Command_GetLog_Limits::maxVersionSize"

.PP
Definition at line 505 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_Command_GetLog_Limits::has_maxTagSize"

.PP
Definition at line 506 of file kinetic_proto\&.h\&.
.SS "uint32_t KineticProto_Command_GetLog_Limits::maxTagSize"

.PP
Definition at line 507 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_Command_GetLog_Limits::has_maxConnections"

.PP
Definition at line 508 of file kinetic_proto\&.h\&.
.SS "uint32_t KineticProto_Command_GetLog_Limits::maxConnections"

.PP
Definition at line 509 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_Command_GetLog_Limits::has_maxOutstandingReadRequests"

.PP
Definition at line 510 of file kinetic_proto\&.h\&.
.SS "uint32_t KineticProto_Command_GetLog_Limits::maxOutstandingReadRequests"

.PP
Definition at line 511 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_Command_GetLog_Limits::has_maxOutstandingWriteRequests"

.PP
Definition at line 512 of file kinetic_proto\&.h\&.
.SS "uint32_t KineticProto_Command_GetLog_Limits::maxOutstandingWriteRequests"

.PP
Definition at line 513 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_Command_GetLog_Limits::has_maxMessageSize"

.PP
Definition at line 514 of file kinetic_proto\&.h\&.
.SS "uint32_t KineticProto_Command_GetLog_Limits::maxMessageSize"

.PP
Definition at line 515 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_Command_GetLog_Limits::has_maxKeyRangeCount"

.PP
Definition at line 516 of file kinetic_proto\&.h\&.
.SS "uint32_t KineticProto_Command_GetLog_Limits::maxKeyRangeCount"

.PP
Definition at line 517 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_Command_GetLog_Limits::has_maxIdentityCount"

.PP
Definition at line 518 of file kinetic_proto\&.h\&.
.SS "uint32_t KineticProto_Command_GetLog_Limits::maxIdentityCount"

.PP
Definition at line 519 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_Command_GetLog_Limits::has_maxPinSize"

.PP
Definition at line 520 of file kinetic_proto\&.h\&.
.SS "uint32_t KineticProto_Command_GetLog_Limits::maxPinSize"

.PP
Definition at line 521 of file kinetic_proto\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
