.TH "KineticProto_KeyValue" 3 "Tue Jul 15 2014" "Version v0.3.1-beta" "protobuf-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticProto_KeyValue \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "ProtobufCMessage \fBbase\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_newversion\fP"
.br
.ti -1c
.RI "ProtobufCBinaryData \fBnewversion\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_force\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBforce\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_key\fP"
.br
.ti -1c
.RI "ProtobufCBinaryData \fBkey\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_dbversion\fP"
.br
.ti -1c
.RI "ProtobufCBinaryData \fBdbversion\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_tag\fP"
.br
.ti -1c
.RI "ProtobufCBinaryData \fBtag\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_algorithm\fP"
.br
.ti -1c
.RI "KineticProto_Algorithm \fBalgorithm\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_metadataonly\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBmetadataonly\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_synchronization\fP"
.br
.ti -1c
.RI "KineticProto_Synchronization \fBsynchronization\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 235 of file KineticProto\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for protobuf-c from the source code\&.
