.TH "KineticProto_Header" 3 "Wed Oct 15 2014" "Version v0.7.0" "protobuf-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticProto_Header \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_proto\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "ProtobufCMessage \fBbase\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_clusterVersion\fP"
.br
.ti -1c
.RI "int64_t \fBclusterVersion\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_identity\fP"
.br
.ti -1c
.RI "int64_t \fBidentity\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_connectionID\fP"
.br
.ti -1c
.RI "int64_t \fBconnectionID\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_sequence\fP"
.br
.ti -1c
.RI "int64_t \fBsequence\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_ackSequence\fP"
.br
.ti -1c
.RI "int64_t \fBackSequence\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_messageType\fP"
.br
.ti -1c
.RI "\fBKineticProto_MessageType\fP \fBmessageType\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_timeout\fP"
.br
.ti -1c
.RI "int64_t \fBtimeout\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_earlyExit\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBearlyExit\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_backgroundScan\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBbackgroundScan\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 176 of file kinetic_proto\&.h\&.
.SH "Field Documentation"
.PP 
.SS "ProtobufCMessage KineticProto_Header::base"

.PP
Definition at line 177 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_Header::has_clusterVersion"

.PP
Definition at line 178 of file kinetic_proto\&.h\&.
.SS "int64_t KineticProto_Header::clusterVersion"

.PP
Definition at line 179 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_Header::has_identity"

.PP
Definition at line 180 of file kinetic_proto\&.h\&.
.SS "int64_t KineticProto_Header::identity"

.PP
Definition at line 181 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_Header::has_connectionID"

.PP
Definition at line 182 of file kinetic_proto\&.h\&.
.SS "int64_t KineticProto_Header::connectionID"

.PP
Definition at line 183 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_Header::has_sequence"

.PP
Definition at line 184 of file kinetic_proto\&.h\&.
.SS "int64_t KineticProto_Header::sequence"

.PP
Definition at line 185 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_Header::has_ackSequence"

.PP
Definition at line 186 of file kinetic_proto\&.h\&.
.SS "int64_t KineticProto_Header::ackSequence"

.PP
Definition at line 187 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_Header::has_messageType"

.PP
Definition at line 188 of file kinetic_proto\&.h\&.
.SS "\fBKineticProto_MessageType\fP KineticProto_Header::messageType"

.PP
Definition at line 189 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_Header::has_timeout"

.PP
Definition at line 190 of file kinetic_proto\&.h\&.
.SS "int64_t KineticProto_Header::timeout"

.PP
Definition at line 191 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_Header::has_earlyExit"

.PP
Definition at line 192 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_Header::earlyExit"

.PP
Definition at line 193 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_Header::has_backgroundScan"

.PP
Definition at line 194 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_Header::backgroundScan"

.PP
Definition at line 195 of file kinetic_proto\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for protobuf-c from the source code\&.
