.TH "KineticProto_GetLog_Device" 3 "Wed Oct 15 2014" "Version v0.7.0" "protobuf-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticProto_GetLog_Device \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_proto\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "ProtobufCMessage \fBbase\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_name\fP"
.br
.ti -1c
.RI "ProtobufCBinaryData \fBname\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 460 of file kinetic_proto\&.h\&.
.SH "Field Documentation"
.PP 
.SS "ProtobufCMessage KineticProto_GetLog_Device::base"

.PP
Definition at line 461 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_GetLog_Device::has_name"

.PP
Definition at line 462 of file kinetic_proto\&.h\&.
.SS "ProtobufCBinaryData KineticProto_GetLog_Device::name"

.PP
Definition at line 463 of file kinetic_proto\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for protobuf-c from the source code\&.
