.TH "KineticConnection" 3 "Mon Mar 2 2015" "Version v0.12.0-beta" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticConnection \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_types_internal\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "bool \fBconnected\fP"
.br
.ti -1c
.RI "int \fBsocket\fP"
.br
.ti -1c
.RI "int64_t \fBconnectionID\fP"
.br
.ti -1c
.RI "int64_t \fBsequence\fP"
.br
.ti -1c
.RI "KineticSession * \fBpSession\fP"
.br
.ti -1c
.RI "struct \fBbus\fP * \fBmessageBus\fP"
.br
.ti -1c
.RI "socket_info * \fBsi\fP"
.br
.ti -1c
.RI "pthread_mutex_t \fBsendMutex\fP"
.br
.ti -1c
.RI "KineticResourceWaiter \fBconnectionReady\fP"
.br
.ti -1c
.RI "KineticCountingSemaphore * \fBoutstandingOperations\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 112 of file kinetic_types_internal\&.h\&.
.SH "Field Documentation"
.PP 
.SS "bool KineticConnection::connected"

.PP
Definition at line 113 of file kinetic_types_internal\&.h\&.
.SS "int KineticConnection::socket"

.PP
Definition at line 114 of file kinetic_types_internal\&.h\&.
.SS "int64_t KineticConnection::connectionID"

.PP
Definition at line 115 of file kinetic_types_internal\&.h\&.
.SS "int64_t KineticConnection::sequence"

.PP
Definition at line 116 of file kinetic_types_internal\&.h\&.
.SS "KineticSession* KineticConnection::pSession"

.PP
Definition at line 117 of file kinetic_types_internal\&.h\&.
.SS "struct \fBbus\fP* KineticConnection::messageBus"

.PP
Definition at line 118 of file kinetic_types_internal\&.h\&.
.SS "socket_info* KineticConnection::si"

.PP
Definition at line 119 of file kinetic_types_internal\&.h\&.
.SS "pthread_mutex_t KineticConnection::sendMutex"

.PP
Definition at line 120 of file kinetic_types_internal\&.h\&.
.SS "KineticResourceWaiter KineticConnection::connectionReady"

.PP
Definition at line 121 of file kinetic_types_internal\&.h\&.
.SS "KineticCountingSemaphore* KineticConnection::outstandingOperations"

.PP
Definition at line 122 of file kinetic_types_internal\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
