.TH "KineticProto_GetLog_Configuration" 3 "Thu Aug 7 2014" "Version v0.3.3" "protobuf-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticProto_GetLog_Configuration \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_proto\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "ProtobufCMessage \fBbase\fP"
.br
.ti -1c
.RI "char * \fBvendor\fP"
.br
.ti -1c
.RI "char * \fBmodel\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_serialnumber\fP"
.br
.ti -1c
.RI "ProtobufCBinaryData \fBserialnumber\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_worldwidename\fP"
.br
.ti -1c
.RI "ProtobufCBinaryData \fBworldwidename\fP"
.br
.ti -1c
.RI "char * \fBversion\fP"
.br
.ti -1c
.RI "char * \fBcompilationdate\fP"
.br
.ti -1c
.RI "char * \fBsourcehash\fP"
.br
.ti -1c
.RI "char * \fBprotocolversion\fP"
.br
.ti -1c
.RI "char * \fBprotocolcompilationdate\fP"
.br
.ti -1c
.RI "char * \fBprotocolsourcehash\fP"
.br
.ti -1c
.RI "size_t \fBn_interface\fP"
.br
.ti -1c
.RI "KineticProto_GetLog_Configuration_Interface ** \fBinterface\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_port\fP"
.br
.ti -1c
.RI "int32_t \fBport\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_tlsport\fP"
.br
.ti -1c
.RI "int32_t \fBtlsport\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 398 of file kinetic_proto\&.h\&.
.SH "Field Documentation"
.PP 
.SS "ProtobufCMessage KineticProto_GetLog_Configuration::base"

.PP
Definition at line 400 of file kinetic_proto\&.h\&.
.SS "char* KineticProto_GetLog_Configuration::vendor"

.PP
Definition at line 401 of file kinetic_proto\&.h\&.
.SS "char* KineticProto_GetLog_Configuration::model"

.PP
Definition at line 402 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_GetLog_Configuration::has_serialnumber"

.PP
Definition at line 403 of file kinetic_proto\&.h\&.
.SS "ProtobufCBinaryData KineticProto_GetLog_Configuration::serialnumber"

.PP
Definition at line 404 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_GetLog_Configuration::has_worldwidename"

.PP
Definition at line 405 of file kinetic_proto\&.h\&.
.SS "ProtobufCBinaryData KineticProto_GetLog_Configuration::worldwidename"

.PP
Definition at line 406 of file kinetic_proto\&.h\&.
.SS "char* KineticProto_GetLog_Configuration::version"

.PP
Definition at line 407 of file kinetic_proto\&.h\&.
.SS "char* KineticProto_GetLog_Configuration::compilationdate"

.PP
Definition at line 408 of file kinetic_proto\&.h\&.
.SS "char* KineticProto_GetLog_Configuration::sourcehash"

.PP
Definition at line 409 of file kinetic_proto\&.h\&.
.SS "char* KineticProto_GetLog_Configuration::protocolversion"

.PP
Definition at line 410 of file kinetic_proto\&.h\&.
.SS "char* KineticProto_GetLog_Configuration::protocolcompilationdate"

.PP
Definition at line 411 of file kinetic_proto\&.h\&.
.SS "char* KineticProto_GetLog_Configuration::protocolsourcehash"

.PP
Definition at line 412 of file kinetic_proto\&.h\&.
.SS "size_t KineticProto_GetLog_Configuration::n_interface"

.PP
Definition at line 413 of file kinetic_proto\&.h\&.
.SS "KineticProto_GetLog_Configuration_Interface** KineticProto_GetLog_Configuration::interface"

.PP
Definition at line 414 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_GetLog_Configuration::has_port"

.PP
Definition at line 415 of file kinetic_proto\&.h\&.
.SS "int32_t KineticProto_GetLog_Configuration::port"

.PP
Definition at line 416 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_GetLog_Configuration::has_tlsport"

.PP
Definition at line 417 of file kinetic_proto\&.h\&.
.SS "int32_t KineticProto_GetLog_Configuration::tlsport"

.PP
Definition at line 418 of file kinetic_proto\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for protobuf-c from the source code\&.
