.TH "KineticProto_Command_Body" 3 "Tue Dec 9 2014" "Version v0.9.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticProto_Command_Body \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_proto\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "ProtobufCMessage \fBbase\fP"
.br
.ti -1c
.RI "KineticProto_Command_KeyValue * \fBkeyValue\fP"
.br
.ti -1c
.RI "KineticProto_Command_Range * \fBrange\fP"
.br
.ti -1c
.RI "KineticProto_Command_Setup * \fBsetup\fP"
.br
.ti -1c
.RI "KineticProto_Command_P2POperation * \fBp2pOperation\fP"
.br
.ti -1c
.RI "KineticProto_Command_GetLog * \fBgetLog\fP"
.br
.ti -1c
.RI "KineticProto_Command_Security * \fBsecurity\fP"
.br
.ti -1c
.RI "KineticProto_Command_PinOperation * \fBpinOp\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 273 of file kinetic_proto\&.h\&.
.SH "Field Documentation"
.PP 
.SS "ProtobufCMessage KineticProto_Command_Body::base"

.PP
Definition at line 274 of file kinetic_proto\&.h\&.
.SS "KineticProto_Command_KeyValue* KineticProto_Command_Body::keyValue"

.PP
Definition at line 275 of file kinetic_proto\&.h\&.
.SS "KineticProto_Command_Range* KineticProto_Command_Body::range"

.PP
Definition at line 276 of file kinetic_proto\&.h\&.
.SS "KineticProto_Command_Setup* KineticProto_Command_Body::setup"

.PP
Definition at line 277 of file kinetic_proto\&.h\&.
.SS "KineticProto_Command_P2POperation* KineticProto_Command_Body::p2pOperation"

.PP
Definition at line 278 of file kinetic_proto\&.h\&.
.SS "KineticProto_Command_GetLog* KineticProto_Command_Body::getLog"

.PP
Definition at line 279 of file kinetic_proto\&.h\&.
.SS "KineticProto_Command_Security* KineticProto_Command_Body::security"

.PP
Definition at line 280 of file kinetic_proto\&.h\&.
.SS "KineticProto_Command_PinOperation* KineticProto_Command_Body::pinOp"

.PP
Definition at line 281 of file kinetic_proto\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
