.TH "KineticResourceWaiter" 3 "Wed Feb 11 2015" "Version v0.11.1" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticResourceWaiter \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_resourcewaiter_types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "pthread_mutex_t \fBmutex\fP"
.br
.ti -1c
.RI "pthread_cond_t \fBready_cond\fP"
.br
.ti -1c
.RI "bool \fBready\fP"
.br
.ti -1c
.RI "uint32_t \fBnum_waiting\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 27 of file kinetic_resourcewaiter_types\&.h\&.
.SH "Field Documentation"
.PP 
.SS "pthread_mutex_t KineticResourceWaiter::mutex"

.PP
Definition at line 28 of file kinetic_resourcewaiter_types\&.h\&.
.SS "pthread_cond_t KineticResourceWaiter::ready_cond"

.PP
Definition at line 29 of file kinetic_resourcewaiter_types\&.h\&.
.SS "bool KineticResourceWaiter::ready"

.PP
Definition at line 30 of file kinetic_resourcewaiter_types\&.h\&.
.SS "uint32_t KineticResourceWaiter::num_waiting"

.PP
Definition at line 31 of file kinetic_resourcewaiter_types\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
