.TH "KineticProto_P2POperation" 3 "Wed Jul 30 2014" "Version v0.3.3" "protobuf-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticProto_P2POperation \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_proto\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "ProtobufCMessage \fBbase\fP"
.br
.ti -1c
.RI "KineticProto_P2POperation_Peer * \fBpeer\fP"
.br
.ti -1c
.RI "size_t \fBn_operation\fP"
.br
.ti -1c
.RI "KineticProto_P2POperation_Operation ** \fBoperation\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBhas_allchildoperationssucceeded\fP"
.br
.ti -1c
.RI "protobuf_c_boolean \fBallchildoperationssucceeded\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 330 of file kinetic_proto\&.h\&.
.SH "Field Documentation"
.PP 
.SS "ProtobufCMessage KineticProto_P2POperation::base"

.PP
Definition at line 332 of file kinetic_proto\&.h\&.
.SS "KineticProto_P2POperation_Peer* KineticProto_P2POperation::peer"

.PP
Definition at line 333 of file kinetic_proto\&.h\&.
.SS "size_t KineticProto_P2POperation::n_operation"

.PP
Definition at line 334 of file kinetic_proto\&.h\&.
.SS "KineticProto_P2POperation_Operation** KineticProto_P2POperation::operation"

.PP
Definition at line 335 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_P2POperation::has_allchildoperationssucceeded"

.PP
Definition at line 336 of file kinetic_proto\&.h\&.
.SS "protobuf_c_boolean KineticProto_P2POperation::allchildoperationssucceeded"

.PP
Definition at line 337 of file kinetic_proto\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for protobuf-c from the source code\&.
