.TH "KineticOperation" 3 "Wed Nov 5 2014" "Version v0.8.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticOperation \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_types_internal\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "KineticConnection * \fBconnection\fP"
.br
.ti -1c
.RI "KineticPDU * \fBrequest\fP"
.br
.ti -1c
.RI "KineticPDU * \fBresponse\fP"
.br
.ti -1c
.RI "bool \fBvalueEnabled\fP"
.br
.ti -1c
.RI "bool \fBsendValue\fP"
.br
.ti -1c
.RI "bool \fBreceiveComplete\fP"
.br
.ti -1c
.RI "\fBKineticEntry\fP * \fBentry\fP"
.br
.ti -1c
.RI "\fBByteBufferArray\fP * \fBbuffers\fP"
.br
.ti -1c
.RI "\fBKineticOperationCallback\fP \fBcallback\fP"
.br
.ti -1c
.RI "\fBKineticCompletionClosure\fP \fBclosure\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 256 of file kinetic_types_internal\&.h\&.
.SH "Field Documentation"
.PP 
.SS "KineticConnection* KineticOperation::connection"

.PP
Definition at line 257 of file kinetic_types_internal\&.h\&.
.SS "KineticPDU* KineticOperation::request"

.PP
Definition at line 258 of file kinetic_types_internal\&.h\&.
.SS "KineticPDU* KineticOperation::response"

.PP
Definition at line 259 of file kinetic_types_internal\&.h\&.
.SS "bool KineticOperation::valueEnabled"

.PP
Definition at line 260 of file kinetic_types_internal\&.h\&.
.SS "bool KineticOperation::sendValue"

.PP
Definition at line 261 of file kinetic_types_internal\&.h\&.
.SS "bool KineticOperation::receiveComplete"

.PP
Definition at line 262 of file kinetic_types_internal\&.h\&.
.SS "\fBKineticEntry\fP* KineticOperation::entry"

.PP
Definition at line 263 of file kinetic_types_internal\&.h\&.
.SS "\fBByteBufferArray\fP* KineticOperation::buffers"

.PP
Definition at line 264 of file kinetic_types_internal\&.h\&.
.SS "\fBKineticOperationCallback\fP KineticOperation::callback"

.PP
Definition at line 265 of file kinetic_types_internal\&.h\&.
.SS "\fBKineticCompletionClosure\fP KineticOperation::closure"

.PP
Definition at line 266 of file kinetic_types_internal\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
