.TH "src Directory Reference" 3 "Thu Dec 11 2014" "Version v0.9.1" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBexamples\fP"
.br
.ti -1c
.RI "directory \fBlib\fP"
.br
.ti -1c
.RI "directory \fButility\fP"
.br
.in -1c
