.TH "examples Directory Reference" 3 "Thu Sep 11 2014" "Version v0.6.0" "protobuf-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
examples Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBdelete\&.c\fP"
.br
.ti -1c
.RI "file \fBdelete\&.h\fP"
.br
.ti -1c
.RI "file \fBget\&.c\fP"
.br
.ti -1c
.RI "file \fBget\&.h\fP"
.br
.ti -1c
.RI "file \fBnoop\&.c\fP"
.br
.ti -1c
.RI "file \fBnoop\&.h\fP"
.br
.ti -1c
.RI "file \fBput\&.c\fP"
.br
.ti -1c
.RI "file \fBput\&.h\fP"
.br
.in -1c
