.TH "include Directory Reference" 3 "Thu Dec 11 2014" "Version v0.9.1" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBbyte_array\&.h\fP"
.br
.ti -1c
.RI "file \fBkinetic_client\&.h\fP"
.br
.ti -1c
.RI "file \fBkinetic_types\&.h\fP"
.br
.in -1c
