.TH "utility Directory Reference" 3 "Fri Aug 8 2014" "Version v0.4.3" "protobuf-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
utility Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBexamples\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmain\&.c\fP"
.br
.in -1c
