.TH "ACL" 3 "Fri Mar 13 2015" "Version v0.12.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACL \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_acl_types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "size_t \fBACL_ceil\fP"
.br
.RI "\fICeiling of ACLs array: resize if count == ceil\&. \fP"
.ti -1c
.RI "size_t \fBACL_count\fP"
.br
.RI "\fIHow many \fBACL\fP * structs are in ACLs[]\&. \fP"
.ti -1c
.RI "Com__Seagate__Kinetic__Proto__Command__Security__ACL ** \fBACLs\fP"
.br
.RI "\fI\fBACL\fP struct array\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 40 of file kinetic_acl_types\&.h\&.
.SH "Field Documentation"
.PP 
.SS "size_t ACL::ACL_ceil"

.PP
Ceiling of ACLs array: resize if count == ceil\&. 
.PP
Definition at line 41 of file kinetic_acl_types\&.h\&.
.SS "size_t ACL::ACL_count"

.PP
How many \fBACL\fP * structs are in ACLs[]\&. 
.PP
Definition at line 42 of file kinetic_acl_types\&.h\&.
.SS "Com__Seagate__Kinetic__Proto__Command__Security__ACL** ACL::ACLs"

.PP
\fBACL\fP struct array\&. 
.PP
Definition at line 43 of file kinetic_acl_types\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
