acl.h
NAME
acl.h -
SYNOPSIS
#include 'acl_types.h'
#include 'kinetic_proto.h'
Functions
acl_of_file_res acl_of_file (const char *path, struct ACL **instance)
acl_of_file_res acl_of_string (const char *buf, size_t buf_size, struct ACL **instance)
void acl_fprintf (FILE *f, struct ACL *acl)
void acl_free (struct ACL *acl)
Function Documentation
acl_of_file_res acl_of_file (const char *path, struct ACL **instance)
Definition at line 71 of file acl.c.
References ACL_ERROR_BAD_JSON, ACL_ERROR_JSON_FILE, ACL_ERROR_MEMORY, ACL_ERROR_NULL, acl_of_string(), cleanup(), LOGF0, and LOGF2.
acl_of_file_res acl_of_string (const char *buf, size_tbuf_size, struct ACL **instance)
Definition at line 127 of file acl.c.
References ACL::ACL_ceil, ACL::ACL_count, ACL_END_OF_STREAM, ACL_ERROR_BAD_JSON, ACL_ERROR_MEMORY, ACL_OK, ACL::ACLs, cleanup(), LOG2, LOGF2, and read_next_ACL().
void acl_fprintf (FILE *f, struct ACL *acl)
Definition at line 382 of file acl.c.
References ACL::ACL_count, ACL::ACLs, and str_of_permission().
void acl_free (struct ACL *acl)
Definition at line 429 of file acl.c.
References ACL::ACL_count, and ACL::ACLs.
Author
Generated automatically by Doxygen for kinetic-c from the source code.