.TH "ACL" 3 "Mon Mar 2 2015" "Version v0.12.0-beta" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACL \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <acl_types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "size_t \fBACL_ceil\fP"
.br
.ti -1c
.RI "size_t \fBACL_count\fP"
.br
.ti -1c
.RI "KineticProto_Command_Security_ACL ** \fBACLs\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 21 of file acl_types\&.h\&.
.SH "Field Documentation"
.PP 
.SS "size_t ACL::ACL_ceil"

.PP
Definition at line 22 of file acl_types\&.h\&.
.SS "size_t ACL::ACL_count"

.PP
Definition at line 23 of file acl_types\&.h\&.
.SS "KineticProto_Command_Security_ACL** ACL::ACLs"

.PP
Definition at line 24 of file acl_types\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
