acl.c
NAME
acl.c -
SYNOPSIS
#include <string.h>
#include <stdio.h>
#include <fcntl.h>
#include <errno.h>
#include 'kinetic_logger.h'
#include 'acl.h'
#include 'json.h'
Macros
#define PERM_TABLE_ROWS sizeof(permission_table)/sizeof(permission_table)[0]
Functions
static acl_of_file_res read_next_ACL (const char *buf, size_t buf_size, size_t offset, size_t *new_offset, struct json_tokener *tokener, KineticProto_Command_Security_ACL **instance)
static acl_of_file_res unpack_scopes (KineticProto_Command_Security_ACL *acl, int scope_count, json_object *scopes)
static const char * str_of_permission (KineticProto_Command_Security_ACL_Permission perm)
static
KineticProto_Command_Security_ACL_Permission permission_of_str (const char *str)"
acl_of_file_res acl_of_file (const char *path, struct ACL **instance)
acl_of_file_res acl_of_string (const char *buf, size_t buf_size, struct ACL **instance)
void acl_fprintf (FILE *f, struct ACL *ACLs)
void acl_free (struct ACL *ACLs)
Variables
static permission_pair permission_table []
Macro Definition Documentation
#define PERM_TABLE_ROWS sizeof(permission_table)/sizeof(permission_table)[0]
Definition at line 46 of file acl.c.
Function Documentation
static acl_of_file_res read_next_ACL (const char *buf, size_tbuf_size, size_toffset, size_t *new_offset, struct json_tokener *tokener, KineticProto_Command_Security_ACL **instance) [static]
Definition at line 194 of file acl.c.
References ACL_END_OF_STREAM, ACL_ERROR_BAD_JSON, ACL_ERROR_INVALID_FIELD, ACL_ERROR_MEMORY, ACL_ERROR_MISSING_FIELD, ACL_OK, KINETIC_PROTO_COMMAND_SECURITY_ACL_HMACALGORITHM_HmacSHA1, KineticProto_command_security_acl__init(), LOGF2, and unpack_scopes().
static acl_of_file_res unpack_scopes (KineticProto_Command_Security_ACL *acl, intscope_count, json_object *scopes) [static]
Definition at line 281 of file acl.c.
References ACL_ERROR_INVALID_FIELD, ACL_ERROR_MEMORY, ACL_MAX_PERMISSIONS, ACL_OK, KINETIC_PROTO_COMMAND_SECURITY_ACL_PERMISSION_INVALID_PERMISSION, KineticProto_command_security_acl_scope__init(), and permission_of_str().
static const char* str_of_permission (KineticProto_Command_Security_ACL_Permissionperm) [static]
Definition at line 54 of file acl.c.
References PERM_TABLE_ROWS, and permission_table.
static KineticProto_Command_Security_ACL_Permission permission_of_str (const char *str) [static]
Definition at line 62 of file acl.c.
References KINETIC_PROTO_COMMAND_SECURITY_ACL_PERMISSION_INVALID_PERMISSION, PERM_TABLE_ROWS, and permission_table.
acl_of_file_res acl_of_file (const char *path, struct ACL **instance)
Definition at line 71 of file acl.c.
References ACL_ERROR_BAD_JSON, ACL_ERROR_JSON_FILE, ACL_ERROR_MEMORY, ACL_ERROR_NULL, acl_of_string(), LOGF0, and LOGF2.
acl_of_file_res acl_of_string (const char *buf, size_tbuf_size, struct ACL **instance)
Definition at line 127 of file acl.c.
References ACL::ACL_ceil, ACL::ACL_count, ACL_END_OF_STREAM, ACL_ERROR_BAD_JSON, ACL_ERROR_MEMORY, ACL_OK, ACL::ACLs, LOG2, LOGF2, and read_next_ACL().
void acl_fprintf (FILE *f, struct ACL *ACLs)
Definition at line 382 of file acl.c.
References ACL::ACL_count, ACL::ACLs, and str_of_permission().
void acl_free (struct ACL *ACLs)
Definition at line 429 of file acl.c.
References ACL::ACL_count, and ACL::ACLs.
Variable Documentation
permission_pair permission_table[] [static]
Initial value:
= {
    { KINETIC_PROTO_COMMAND_SECURITY_ACL_PERMISSION_INVALID_PERMISSION, "INVALID" },
    { KINETIC_PROTO_COMMAND_SECURITY_ACL_PERMISSION_READ, "READ" },
    { KINETIC_PROTO_COMMAND_SECURITY_ACL_PERMISSION_WRITE, "WRITE" },
    { KINETIC_PROTO_COMMAND_SECURITY_ACL_PERMISSION_DELETE, "DELETE" },
    { KINETIC_PROTO_COMMAND_SECURITY_ACL_PERMISSION_RANGE, "RANGE" },
    { KINETIC_PROTO_COMMAND_SECURITY_ACL_PERMISSION_SETUP, "SETUP" },
    { KINETIC_PROTO_COMMAND_SECURITY_ACL_PERMISSION_P2POP, "P2POP" },
    { KINETIC_PROTO_COMMAND_SECURITY_ACL_PERMISSION_GETLOG, "GETLOG" },
    { KINETIC_PROTO_COMMAND_SECURITY_ACL_PERMISSION_SECURITY, "SECURITY" },
}
Definition at line 34 of file acl.c.
Author
Generated automatically by Doxygen for kinetic-c from the source code.