blocking_put_get.c
NAME
blocking_put_get.c -
SYNOPSIS
#include 'kinetic_client.h'
#include 'kinetic_types.h'
#include 'byte_array.h'
#include <stdlib.h>
#include <getopt.h>
#include <stdio.h>
#include <sys/param.h>
#include <sys/stat.h>
#include <sys/file.h>
#include <ctype.h>
#include <openssl/sha.h>
Functions
static void do_put_and_get (KineticSession *session)
int main (int argc, char **argv)
Function Documentation
static void do_put_and_get (KineticSession *session) [static]
Definition at line 34 of file blocking_put_get.c.
References ByteBuffer::array, ByteBuffer_Append(), ByteBuffer_Free(), ByteBuffer_Malloc(), ByteBuffer_MallocAndAppend(), ByteBuffer::bytesUsed, ByteArray::data, KineticEntry::key, KINETIC_ALGORITHM_SHA1, Kinetic_GetStatusDescription(), KINETIC_SYNCHRONIZATION_WRITETHROUGH, KineticClient_Get(), KineticClient_Put(), and KineticEntry::value.
int main (intargc, char **argv)
Definition at line 96 of file blocking_put_get.c.
References ByteArray_CreateWithCString(), do_put_and_get(), KineticSessionConfig::host, Kinetic_GetStatusDescription(), KINETIC_PORT, KINETIC_STATUS_SUCCESS, KineticClient_CreateSession(), KineticClient_DestroySession(), KineticClient_Init(), KineticClient_Shutdown(), and KineticClientConfig::logFile.
Author
Generated automatically by Doxygen for kinetic-c from the source code.