.TH "blocking_flush.c" 3 "Mon Mar 2 2015" "Version v0.12.0-beta" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
blocking_flush.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'kinetic_client\&.h'\fP
.br
\fC#include 'kinetic_types\&.h'\fP
.br
\fC#include 'byte_array\&.h'\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <getopt\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <sys/param\&.h>\fP
.br
\fC#include <sys/stat\&.h>\fP
.br
\fC#include <sys/file\&.h>\fP
.br
\fC#include <ctype\&.h>\fP
.br
\fC#include <openssl/sha\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "static void \fBdo_flush\fP (KineticSession *session)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "static void do_flush (KineticSession *session)\fC [static]\fP"

.PP
Definition at line 34 of file blocking_flush\&.c\&.
.PP
References Kinetic_GetStatusDescription(), and KineticClient_Flush()\&.
.SS "int main (intargc, char **argv)"

.PP
Definition at line 43 of file blocking_flush\&.c\&.
.PP
References ByteArray_CreateWithCString(), do_flush(), KineticSessionConfig::host, Kinetic_GetStatusDescription(), KINETIC_PORT, KINETIC_STATUS_SUCCESS, KineticClient_CreateSession(), KineticClient_DestroySession(), KineticClient_Init(), KineticClient_Shutdown(), and KineticClientConfig::logFile\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
