blocking_flush.c
NAME
blocking_flush.c -
SYNOPSIS
#include 'kinetic_client.h'
#include 'kinetic_types.h'
#include 'byte_array.h'
#include <stdlib.h>
#include <getopt.h>
#include <stdio.h>
#include <sys/param.h>
#include <sys/stat.h>
#include <sys/file.h>
#include <ctype.h>
#include <openssl/sha.h>
Functions
static void do_flush (KineticSession *session)
int main (int argc, char **argv)
Function Documentation
static void do_flush (KineticSession *session) [static]
Definition at line 34 of file blocking_flush.c.
References Kinetic_GetStatusDescription(), and KineticClient_Flush().
int main (intargc, char **argv)
Definition at line 43 of file blocking_flush.c.
References ByteArray_CreateWithCString(), do_flush(), KineticSessionConfig::host, Kinetic_GetStatusDescription(), KINETIC_PORT, KINETIC_STATUS_SUCCESS, KineticClient_CreateSession(), KineticClient_DestroySession(), KineticClient_Init(), KineticClient_Shutdown(), and KineticClientConfig::logFile.
Author
Generated automatically by Doxygen for kinetic-c from the source code.