blocking_put_delete.c
NAME
blocking_put_delete.c -
SYNOPSIS
#include 'kinetic_client.h'
#include 'kinetic_types.h'
#include 'byte_array.h'
#include <stdlib.h>
#include <getopt.h>
#include <stdio.h>
#include <sys/param.h>
#include <sys/stat.h>
#include <sys/file.h>
#include <ctype.h>
#include <openssl/sha.h>
Functions
int main (int argc, char **argv)
Function Documentation
int main (intargc, char **argv)
Definition at line 82 of file blocking_put_delete.c.
References ByteArray_CreateWithCString(), KineticSession::config, KineticSessionConfig::host, Kinetic_GetStatusDescription(), KINETIC_PORT, KINETIC_STATUS_SUCCESS, KineticClient_CreateConnection(), KineticClient_DestroyConnection(), KineticClient_Init(), KineticClient_Shutdown(), and KineticClientConfig::logFile.
Author
Generated automatically by Doxygen for kinetic-c from the source code.