bus.h
NAME
bus.h -
SYNOPSIS
#include 'bus_types.h'
Functions
bool bus_init (bus_config *config, struct bus_result *res)
bool bus_send_request (struct bus *b, bus_user_msg *msg)
const char * bus_log_event_str (log_event_t event)
bool bus_register_socket (struct bus *b, bus_socket_t type, int fd, void *socket_udata)
bool bus_release_socket (struct bus *b, int fd, void **socket_udata_out)
bool bus_shutdown (struct bus *b)
struct listener * bus_get_listener_for_socket (struct bus *b, int fd)
bool bus_schedule_threadpool_task (struct bus *b, struct threadpool_task *task, size_t *backpressure)
void bus_lock_log (struct bus *b)
void bus_unlock_log (struct bus *b)
void bus_free (struct bus *b)
bool bus_process_boxed_message (struct bus *b, struct boxed_msg *box, size_t *backpressure)
void bus_backpressure_delay (struct bus *b, size_t backpressure, uint8_t shift)
Function Documentation
bool bus_init (bus_config *config, struct bus_result *res)
Definition at line 54 of file bus.c.
References attempt_to_increase_resource_limits(), bus_result::bus, BUS_INIT_ERROR_ALLOC_FAIL, BUS_INIT_ERROR_LISTENER_INIT_FAIL, BUS_INIT_ERROR_MISSING_SINK_CB, BUS_INIT_ERROR_MISSING_UNPACK_CB, BUS_INIT_ERROR_MUTEX_INIT_FAIL, BUS_INIT_ERROR_NULL, BUS_INIT_ERROR_PTHREAD_INIT_FAIL, BUS_INIT_ERROR_THREADPOOL_INIT_FAIL, BUS_LOG, BUS_LOG_SNPRINTF, bus_ssl_init(), bus_config::bus_udata, DEF_FD_SET_SIZE2, bus::error_cb, bus_config::error_cb, bus::fd_set, bus::fd_set_lock, bus::joined, bus::listener_count, bus_config::listener_count, listener_free(), listener_init(), bus::listeners, ListenerTask_MainLoop(), bus::log_cb, bus_config::log_cb, LOG_INITIALIZATION, bus::log_level, bus_config::log_level, bus::log_lock, noop_error_cb(), noop_log_cb(), set_defaults(), bus::sink_cb, bus_config::sink_cb, bus_result::status, bus::threadpool, bus_config::threadpool_cfg, threadpool_free(), threadpool_init(), threadpool::threads, bus::threads, bus::udata, bus::unexpected_msg_cb, bus_config::unexpected_msg_cb, bus::unpack_cb, bus_config::unpack_cb, yacht_free(), and yacht_init().
bool bus_send_request (struct bus *b, bus_user_msg *msg)
Definition at line 287 of file bus.c.
References box_msg(), BUS_LOG_SNPRINTF, bus_user_msg::fd, LOG_SENDING_REQUEST, send_do_blocking_send(), bus_user_msg::seq_id, and bus::udata.
const char* bus_log_event_str (log_event_tevent)
Definition at line 390 of file bus.c.
References LOG_INITIALIZATION, LOG_LISTENER, LOG_MEMORY, LOG_NEW_CLIENT, LOG_SENDER, LOG_SENDING_REQUEST, LOG_SHUTDOWN, and LOG_SOCKET_REGISTERED.
bool bus_register_socket (struct bus *b, bus_socket_ttype, intfd, void *socket_udata)
Definition at line 405 of file bus.c.
References BUS_LOG, BUS_LOG_SNPRINTF, BUS_NO_SEQ_ID, BUS_NO_SSL, BUS_SOCKET_SSL, bus_ssl_connect(), connection_info::fd, bus::fd_set, bus::fd_set_lock, connection_info::largest_rd_seq_id_seen, connection_info::largest_wr_seq_id_seen, listener_add_socket(), listener_id_of_socket(), bus::listeners, LOG_SOCKET_REGISTERED, poll_on_completion(), connection_info::ssl, connection_info::type, bus::udata, connection_info::udata, and yacht_set().
bool bus_release_socket (struct bus *b, intfd, void **socket_udata_out)
Definition at line 474 of file bus.c.
References BUS_LOG_SNPRINTF, BUS_NO_SSL, bus_ssl_disconnect(), bus::fd_set, bus::fd_set_lock, listener_id_of_socket(), listener_remove_socket(), bus::listeners, LOG_SOCKET_REGISTERED, poll_on_completion(), connection_info::ssl, bus::udata, connection_info::udata, and yacht_remove().
bool bus_shutdown (struct bus *b)
Definition at line 541 of file bus.c.
References ATOMIC_BOOL_COMPARE_AND_SWAP, BUS_LOG, BUS_LOG_SNPRINTF, bus::fd_set, free_connection_cb(), bus::joined, bus::listener_count, listener_shutdown(), bus::listeners, LOG_SHUTDOWN, poll_on_completion(), bus::shutdown_state, SHUTDOWN_STATE_HALTED, SHUTDOWN_STATE_RUNNING, SHUTDOWN_STATE_SHUTTING_DOWN, bus::threads, bus::udata, and yacht_free().
struct listener* bus_get_listener_for_socket (struct bus *b, intfd)
Definition at line 385 of file bus.c.
References listener_id_of_socket(), and bus::listeners.
bool bus_schedule_threadpool_task (struct bus *b, struct threadpool_task *task, size_t *backpressure)
Definition at line 516 of file bus.c.
References bus::threadpool, and threadpool_schedule().
void bus_lock_log (struct bus *b)
Definition at line 594 of file bus.c.
References bus::log_lock.
void bus_unlock_log (struct bus *b)
Definition at line 598 of file bus.c.
References bus::log_lock.
void bus_free (struct bus *b)
Definition at line 639 of file bus.c.
References BUS_LOG, BUS_LOG_SNPRINTF, bus_shutdown(), bus_ssl_ctx_free(), bus::fd_set_lock, bus::joined, limit, bus::listener_count, listener_free(), bus::listeners, bus::log_lock, LOG_SHUTDOWN, bus::shutdown_state, SHUTDOWN_STATE_HALTED, THREAD_SHUTDOWN_SECONDS, bus::threadpool, threadpool_free(), threadpool_shutdown(), bus::threads, and bus::udata.
bool bus_process_boxed_message (struct bus *b, struct boxed_msg *box, size_t *backpressure)
Definition at line 620 of file bus.c.
References box_cleanup_cb(), box_execute_cb(), BUS_LOG_SNPRINTF, bus_schedule_threadpool_task(), BUS_SEND_UNDEFINED, LOG_MEMORY, boxed_msg::result, bus_msg_result_t::status, threadpool_task::task, and bus::udata.
void bus_backpressure_delay (struct bus *b, size_tbackpressure, uint8_tshift)
Definition at line 583 of file bus.c.
References BUS_LOG_SNPRINTF, LOG_SENDER, and bus::udata.
Author
Generated automatically by Doxygen for kinetic-c from the source code.