.TH "bus" 3 "Wed Feb 11 2015" "Version v0.11.1" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bus \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <bus_internal_types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBbus_sink_cb\fP * \fBsink_cb\fP"
.br
.ti -1c
.RI "\fBbus_unpack_cb\fP * \fBunpack_cb\fP"
.br
.ti -1c
.RI "\fBbus_unexpected_msg_cb\fP * \fBunexpected_msg_cb\fP"
.br
.ti -1c
.RI "\fBbus_error_cb\fP * \fBerror_cb\fP"
.br
.ti -1c
.RI "void * \fBudata\fP"
.br
.ti -1c
.RI "int \fBlog_level\fP"
.br
.ti -1c
.RI "\fBbus_log_cb\fP * \fBlog_cb\fP"
.br
.ti -1c
.RI "pthread_mutex_t \fBlog_lock\fP"
.br
.ti -1c
.RI "uint8_t \fBsender_count\fP"
.br
.ti -1c
.RI "struct \fBsender\fP ** \fBsenders\fP"
.br
.ti -1c
.RI "uint8_t \fBlistener_count\fP"
.br
.ti -1c
.RI "struct \fBlistener\fP ** \fBlisteners\fP"
.br
.ti -1c
.RI "bool * \fBjoined\fP"
.br
.ti -1c
.RI "pthread_t * \fBthreads\fP"
.br
.ti -1c
.RI "struct \fBthreadpool\fP * \fBthreadpool\fP"
.br
.ti -1c
.RI "SSL_CTX * \fBssl_ctx\fP"
.br
.ti -1c
.RI "struct yacht * \fBfd_set\fP"
.br
.ti -1c
.RI "pthread_mutex_t \fBfd_set_lock\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 60 of file bus_internal_types\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBbus_sink_cb\fP* bus::sink_cb"

.PP
Definition at line 61 of file bus_internal_types\&.h\&.
.SS "\fBbus_unpack_cb\fP* bus::unpack_cb"

.PP
Definition at line 62 of file bus_internal_types\&.h\&.
.SS "\fBbus_unexpected_msg_cb\fP* bus::unexpected_msg_cb"

.PP
Definition at line 63 of file bus_internal_types\&.h\&.
.SS "\fBbus_error_cb\fP* bus::error_cb"

.PP
Definition at line 64 of file bus_internal_types\&.h\&.
.SS "void* bus::udata"

.PP
Definition at line 65 of file bus_internal_types\&.h\&.
.SS "int bus::log_level"

.PP
Definition at line 67 of file bus_internal_types\&.h\&.
.SS "\fBbus_log_cb\fP* bus::log_cb"

.PP
Definition at line 68 of file bus_internal_types\&.h\&.
.SS "pthread_mutex_t bus::log_lock"

.PP
Definition at line 69 of file bus_internal_types\&.h\&.
.SS "uint8_t bus::sender_count"

.PP
Definition at line 71 of file bus_internal_types\&.h\&.
.SS "struct \fBsender\fP** bus::senders"

.PP
Definition at line 72 of file bus_internal_types\&.h\&.
.SS "uint8_t bus::listener_count"

.PP
Definition at line 74 of file bus_internal_types\&.h\&.
.SS "struct \fBlistener\fP** bus::listeners"

.PP
Definition at line 75 of file bus_internal_types\&.h\&.
.SS "bool* bus::joined"

.PP
Definition at line 77 of file bus_internal_types\&.h\&.
.SS "pthread_t* bus::threads"

.PP
Definition at line 78 of file bus_internal_types\&.h\&.
.SS "struct \fBthreadpool\fP* bus::threadpool"

.PP
Definition at line 80 of file bus_internal_types\&.h\&.
.SS "SSL_CTX* bus::ssl_ctx"

.PP
Definition at line 81 of file bus_internal_types\&.h\&.
.SS "struct yacht* bus::fd_set"

.PP
Definition at line 84 of file bus_internal_types\&.h\&.
.SS "pthread_mutex_t bus::fd_set_lock"

.PP
Definition at line 85 of file bus_internal_types\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
