bus_example.c
NAME
bus_example.c -
SYNOPSIS
#include <stdlib.h>
#include <stdio.h>
#include <unistd.h>
#include <assert.h>
#include <string.h>
#include <err.h>
#include <signal.h>
#include <sys/time.h>
#include <poll.h>
#include 'bus.h'
#include 'atomic.h'
#include 'socket99.h'
Macros
#define MAGIC_NUMBER 3
#define MAX_SOCKETS 1000
#define DEFAULT_BUF_SIZE (1024 * 1024 + sizeof(prot_header_t))
#define PRINT_RESPONSES 0
#define LOG(VERBOSITY,...) do { if (state.verbosity >= VERBOSITY) { printf(__VA_ARGS__); } } while(0)
#define INCREMENT_COMPLETION_COUNTER 1
Enumerations
enum socket_state
Functions
static void run_bus (example_state *s, struct bus *b)
static void parse_args (int argc, char **argv, example_state *s)
static time_t get_cur_second (void)
static void log_cb (log_event_t event, int log_level, const char *msg, void *udata)
static bus_sink_cb_res_t reset_transfer (socket_info *si)
static bus_sink_cb_res_t sink_cb (uint8_t *read_buf, size_t read_size, void *socket_udata)
static bus_unpack_cb_res_t unpack_cb (void *msg, void *socket_udata)
static void unexpected_msg_cb (void *msg, int64_t seq_id, void *bus_udata, void *socket_udata)
int main (int argc, char **argv)
static void signal_handler (int arg)
static sig_t register_signal_handler (int sig)
static void register_signal_handlers (void)
static void usage (void)
static void open_sockets (example_state *s)
static size_t construct_msg (uint8_t *buf, size_t buf_size, size_t payload_size, int64_t seq_id)
static void completion_cb (bus_msg_result_t *res, void *udata)
static void tick_handler (example_state *s)
Variables
example_state state
static const char * executable_name = NULL
static bool loop_flag = true
static sig_t old_sigint_handler = NULL
Macro Definition Documentation
#define MAGIC_NUMBER 3
Definition at line 45 of file bus_example.c.
#define MAX_SOCKETS 1000
Definition at line 47 of file bus_example.c.
#define DEFAULT_BUF_SIZE (1024 * 1024 + sizeof(prot_header_t))
Definition at line 48 of file bus_example.c.
#define PRINT_RESPONSES 0
Definition at line 49 of file bus_example.c.
#define LOG(VERBOSITY, ...) do { if (state.verbosity >= VERBOSITY) { printf(__VA_ARGS__); } } while(0)
Definition at line 95 of file bus_example.c.
#define INCREMENT_COMPLETION_COUNTER 1
Definition at line 395 of file bus_example.c.
Enumeration Type Documentation
enum socket_state
Enumerator
STATE_UNINIT
STATE_AWAITING_HEADER
STATE_AWAITING_BODY
STATE_UNINIT
STATE_AWAITING_HEADER
STATE_AWAITING_BODY
Definition at line 51 of file bus_example.c.
Function Documentation
static void run_bus (example_state *s, struct bus *b) [static]
Definition at line 451 of file bus_example.c.
References bus_register_socket(), bus_send_request(), BUS_SOCKET_PLAIN, completion_cb(), construct_msg(), DEFAULT_BUF_SIZE, bus_user_msg::fd, get_cur_second(), LOG, open_sockets(), register_signal_handlers(), and tick_handler().
static void parse_args (intargc, char **argv, example_state *s) [static]
Definition at line 306 of file bus_example.c.
References DEFAULT_BUF_SIZE, and usage().
static time_t get_cur_second (void) [static]
Definition at line 445 of file bus_example.c.
static void log_cb (log_event_tevent, intlog_level, const char *msg, void *udata) [static]
Definition at line 88 of file bus_example.c.
References bus_log_event_str().
static bus_sink_cb_res_t reset_transfer (socket_info *si) [static]
Definition at line 100 of file bus_example.c.
References bus_sink_cb_res_t::next_read, and STATE_AWAITING_HEADER.
static bus_sink_cb_res_t sink_cb (uint8_t *read_buf, size_tread_size, void *socket_udata) [static]
Definition at line 111 of file bus_example.c.
References DEFAULT_BUF_SIZE, MAGIC_NUMBER, bus_sink_cb_res_t::next_read, reset_transfer(), STATE_AWAITING_BODY, STATE_AWAITING_HEADER, and STATE_UNINIT.
static bus_unpack_cb_res_t unpack_cb (void *msg, void *socket_udata) [static]
Definition at line 209 of file bus_example.c.
static void unexpected_msg_cb (void *msg, int64_tseq_id, void *bus_udata, void *socket_udata) [static]
Definition at line 232 of file bus_example.c.
int main (intargc, char **argv)
Definition at line 240 of file bus_example.c.
References bus_result::bus, bus_free(), bus_init(), bus_shutdown(), executable_name, get_cur_second(), LOG, log_cb(), bus_config::log_cb, parse_args(), run_bus(), sink_cb(), state, bus_result::status, unexpected_msg_cb(), and unpack_cb().
static void signal_handler (intarg) [static]
Definition at line 277 of file bus_example.c.
References LOG.
static sig_t register_signal_handler (intsig) [static]
Definition at line 286 of file bus_example.c.
References signal_handler().
static void register_signal_handlers (void) [static]
Definition at line 292 of file bus_example.c.
References register_signal_handler().
static void usage (void) [static]
Definition at line 297 of file bus_example.c.
References executable_name.
static void open_sockets (example_state *s) [static]
Definition at line 346 of file bus_example.c.
static size_t construct_msg (uint8_t *buf, size_tbuf_size, size_tpayload_size, int64_tseq_id) [static]
Definition at line 376 of file bus_example.c.
References MAGIC_NUMBER.
static void completion_cb (bus_msg_result_t *res, void *udata) [static]
Definition at line 397 of file bus_example.c.
References ATOMIC_BOOL_COMPARE_AND_SWAP, BUS_SEND_RX_FAILURE, BUS_SEND_RX_TIMEOUT, BUS_SEND_SUCCESS, BUS_SEND_TX_FAILURE, BUS_SEND_TX_TIMEOUT, LOG, bus_msg_result_t::response, state, bus_msg_result_t::status, and bus_msg_result_t::u.
static void tick_handler (example_state *s) [static]
Definition at line 438 of file bus_example.c.
References LOG.
Variable Documentation
example_state state
Definition at line 82 of file bus_example.c.
const char* executable_name = NULL [static]
Definition at line 98 of file bus_example.c.
bool loop_flag = true [static]
Definition at line 274 of file bus_example.c.
sig_t old_sigint_handler = NULL [static]
Definition at line 275 of file bus_example.c.
Author
Generated automatically by Doxygen for kinetic-c from the source code.