bus_ssl.c
NAME
bus_ssl.c -
SYNOPSIS
#include <poll.h>
#include <assert.h>
#include 'bus_ssl.h'
#include 'syscall.h'
#include 'util.h'
Macros
#define TIMEOUT_MSEC 100
#define MAX_TIMEOUT 10000
Functions
static bool init_client_SSL_CTX (SSL_CTX **ctx_out)
static void disable_SSL_compression (void)
static void disable_known_bad_ciphers (SSL_CTX *ctx)
static bool do_blocking_connection (struct bus *b, SSL *ssl, int fd)
bool BusSSL_Init (struct bus *b)
Initialize the SSL library internals for use by the messaging bus.
SSL * BusSSL_Connect (struct bus *b, int fd)
Do an SSL / TLS shake for a connection.
bool BusSSL_Disconnect (struct bus *b, SSL *ssl)
Disconnect and free an individual SSL handle.
void BusSSL_CtxFree (struct bus *b)
Free all internal data for using SSL (the SSL_CTX).
Macro Definition Documentation
#define TIMEOUT_MSEC 100
Definition at line 27 of file bus_ssl.c.
#define MAX_TIMEOUT 10000
Definition at line 28 of file bus_ssl.c.
Function Documentation
static bool init_client_SSL_CTX (SSL_CTX **ctx_out) [static]
Definition at line 87 of file bus_ssl.c.
References disable_known_bad_ciphers(), and disable_SSL_compression().
static void disable_SSL_compression (void) [static]
Definition at line 113 of file bus_ssl.c.
static void disable_known_bad_ciphers (SSL_CTX *ctx) [static]
Definition at line 122 of file bus_ssl.c.
static bool do_blocking_connection (struct bus *b, SSL *ssl, intfd) [static]
Definition at line 130 of file bus_ssl.c.
References BUS_LOG, BUS_LOG_SNPRINTF, LOG_SOCKET_REGISTERED, MAX_TIMEOUT, syscall_poll(), TIMEOUT_MSEC, bus::udata, and Util_IsResumableIOError().
bool BusSSL_Init (struct bus *b)
Initialize the SSL library internals for use by the messaging bus.
Definition at line 36 of file bus_ssl.c.
References init_client_SSL_CTX(), and bus::ssl_ctx.
SSL* BusSSL_Connect (struct bus *b, intfd)
Do an SSL / TLS shake for a connection. Blocking.
Definition at line 51 of file bus_ssl.c.
References do_blocking_connection(), and bus::ssl_ctx.
bool BusSSL_Disconnect (struct bus *b, SSL *ssl)
Disconnect and free an individual SSL handle.
Definition at line 73 of file bus_ssl.c.
void BusSSL_CtxFree (struct bus *b)
Free all internal data for using SSL (the SSL_CTX).
Definition at line 80 of file bus_ssl.c.
References bus::ssl_ctx.
Author
Generated automatically by Doxygen for kinetic-c from the source code.