bus_poll.c
NAME
bus_poll.c -
SYNOPSIS
#include 'bus_poll.h'
#include 'syscall.h'
#include 'listener.h'
#include 'util.h'
#include <assert.h>
#include <errno.h>
Functions
bool BusPoll_OnCompletion (struct bus *b, int fd)
Poll on fd until complete, return true on success or false on IO error.
Function Documentation
bool BusPoll_OnCompletion (struct bus *b, intfd)
Poll on fd until complete, return true on success or false on IO error. (This is mostly in a distinct module to add a testing seam.)
Definition at line 35 of file bus_poll.c.
References Bus_BackpressureDelay(), BUS_LOG, BUS_LOG_SNPRINTF, LISTENER_BACKPRESSURE_SHIFT, LISTENER_MSG_TAG, LOG_SENDING_REQUEST, read_buf, syscall_poll(), syscall_read(), bus::udata, and Util_IsResumableIOError().
Author
Generated automatically by Doxygen for kinetic-c from the source code.