.TH "bus_ssl.c" 3 "Wed Feb 11 2015" "Version v0.11.1" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bus_ssl.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <poll\&.h>\fP
.br
\fC#include <assert\&.h>\fP
.br
\fC#include 'bus_ssl\&.h'\fP
.br
\fC#include 'util\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTIMEOUT_MSEC\fP   100"
.br
.ti -1c
.RI "#define \fBMAX_TIMEOUT\fP   10000"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBbus_ssl_init\fP (struct \fBbus\fP *b)"
.br
.ti -1c
.RI "bool \fBbus_ssl_connect\fP (struct \fBbus\fP *b, \fBconnection_info\fP *ci)"
.br
.ti -1c
.RI "bool \fBbus_ssl_disconnect\fP (struct \fBbus\fP *b, SSL *ssl)"
.br
.ti -1c
.RI "void \fBbus_ssl_free\fP (struct \fBbus\fP *b)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define TIMEOUT_MSEC   100"

.PP
Definition at line 26 of file bus_ssl\&.c\&.
.SS "#define MAX_TIMEOUT   10000"

.PP
Definition at line 27 of file bus_ssl\&.c\&.
.SH "Function Documentation"
.PP 
.SS "bool bus_ssl_init (struct \fBbus\fP *b)"

.PP
Definition at line 35 of file bus_ssl\&.c\&.
.PP
References bus::ssl_ctx\&.
.SS "bool bus_ssl_connect (struct \fBbus\fP *b, \fBconnection_info\fP *ci)"

.PP
Definition at line 50 of file bus_ssl\&.c\&.
.PP
References connection_info::fd, connection_info::ssl, and bus::ssl_ctx\&.
.SS "bool bus_ssl_disconnect (struct \fBbus\fP *b, SSL *ssl)"

.PP
Definition at line 74 of file bus_ssl\&.c\&.
.SS "void bus_ssl_free (struct \fBbus\fP *b)"

.PP
Definition at line 81 of file bus_ssl\&.c\&.
.PP
References bus::ssl_ctx\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
