.TH "bus_ssl.c" 3 "Mon Mar 2 2015" "Version v0.12.0-beta" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bus_ssl.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <poll\&.h>\fP
.br
\fC#include <assert\&.h>\fP
.br
\fC#include 'bus_ssl\&.h'\fP
.br
\fC#include 'util\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTIMEOUT_MSEC\fP   100"
.br
.ti -1c
.RI "#define \fBMAX_TIMEOUT\fP   10000"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "static bool \fBinit_client_SSL_CTX\fP (SSL_CTX **ctx_out)"
.br
.ti -1c
.RI "static void \fBdisable_SSL_compression\fP (void)"
.br
.ti -1c
.RI "static void \fBdisable_known_bad_ciphers\fP (SSL_CTX *ctx)"
.br
.ti -1c
.RI "static bool \fBdo_blocking_connection\fP (struct \fBbus\fP *b, \fBconnection_info\fP *ci)"
.br
.ti -1c
.RI "bool \fBbus_ssl_init\fP (struct \fBbus\fP *b)"
.br
.ti -1c
.RI "bool \fBbus_ssl_connect\fP (struct \fBbus\fP *b, \fBconnection_info\fP *ci)"
.br
.ti -1c
.RI "bool \fBbus_ssl_disconnect\fP (struct \fBbus\fP *b, SSL *ssl)"
.br
.ti -1c
.RI "void \fBbus_ssl_ctx_free\fP (struct \fBbus\fP *b)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define TIMEOUT_MSEC   100"

.PP
Definition at line 26 of file bus_ssl\&.c\&.
.SS "#define MAX_TIMEOUT   10000"

.PP
Definition at line 27 of file bus_ssl\&.c\&.
.SH "Function Documentation"
.PP 
.SS "static bool init_client_SSL_CTX (SSL_CTX **ctx_out)\fC [static]\fP"

.PP
Definition at line 88 of file bus_ssl\&.c\&.
.PP
References disable_known_bad_ciphers(), and disable_SSL_compression()\&.
.SS "static void disable_SSL_compression (void)\fC [static]\fP"

.PP
Definition at line 114 of file bus_ssl\&.c\&.
.SS "static void disable_known_bad_ciphers (SSL_CTX *ctx)\fC [static]\fP"

.PP
Definition at line 123 of file bus_ssl\&.c\&.
.SS "static bool do_blocking_connection (struct \fBbus\fP *b, \fBconnection_info\fP *ci)\fC [static]\fP"

.PP
Definition at line 131 of file bus_ssl\&.c\&.
.PP
References BUS_LOG, BUS_LOG_SNPRINTF, connection_info::fd, LOG_SOCKET_REGISTERED, MAX_TIMEOUT, connection_info::ssl, TIMEOUT_MSEC, bus::udata, and util_is_resumable_io_error()\&.
.SS "bool bus_ssl_init (struct \fBbus\fP *b)"

.PP
Definition at line 35 of file bus_ssl\&.c\&.
.PP
References init_client_SSL_CTX(), and bus::ssl_ctx\&.
.SS "bool bus_ssl_connect (struct \fBbus\fP *b, \fBconnection_info\fP *ci)"

.PP
Definition at line 50 of file bus_ssl\&.c\&.
.PP
References do_blocking_connection(), connection_info::fd, connection_info::ssl, and bus::ssl_ctx\&.
.SS "bool bus_ssl_disconnect (struct \fBbus\fP *b, SSL *ssl)"

.PP
Definition at line 74 of file bus_ssl\&.c\&.
.SS "void bus_ssl_ctx_free (struct \fBbus\fP *b)"

.PP
Definition at line 81 of file bus_ssl\&.c\&.
.PP
References bus::ssl_ctx\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
