.TH "bus_internal_types.h" 3 "Fri Mar 13 2015" "Version v0.12.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bus_internal_types.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdint\&.h>\fP
.br
\fC#include <pthread\&.h>\fP
.br
\fC#include <openssl/ssl\&.h>\fP
.br
\fC#include <openssl/err\&.h>\fP
.br
\fC#include 'bus\&.h'\fP
.br
\fC#include 'yacht\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBboxed_msg\fP"
.br
.ti -1c
.RI "struct \fBbus\fP"
.br
.RI "\fIMessage bus\&. \fP"
.ti -1c
.RI "struct \fBconnection_info\fP"
.br
.RI "\fIPer-socket connection context\&. \fP"
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBBUS_NO_SSL\fP   ((SSL *)-2)"
.br
.RI "\fISpecial 'NO SSL' value, to distinguish from a NULL SSL handle\&. \fP"
.ti -1c
.RI "#define \fBTIMEOUT_NOT_YET_SET\fP   ((time_t)(-1))"
.br
.RI "\fISpecial timeout value indicating UNBOUND\&. \fP"
.ti -1c
.RI "#define \fBLISTENER_MSG_TAG\fP   0x15"
.br
.RI "\fIArbitrary byte used to tag writes from the listener\&. \fP"
.ti -1c
.RI "#define \fBDEF_FD_SET_SIZE2\fP   4"
.br
.RI "\fIStarting size^2 for file descriptor hash table\&. \fP"
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBshutdown_state_t\fP "
.br
.ti -1c
.RI "enum \fBrx_error_t\fP "
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BUS_NO_SSL   ((SSL *)-2)"

.PP
Special 'NO SSL' value, to distinguish from a NULL SSL handle\&. 
.PP
Definition at line 63 of file bus_internal_types\&.h\&.
.SS "#define TIMEOUT_NOT_YET_SET   ((time_t)(-1))"

.PP
Special timeout value indicating UNBOUND\&. 
.PP
Definition at line 98 of file bus_internal_types\&.h\&.
.SS "#define LISTENER_MSG_TAG   0x15"

.PP
Arbitrary byte used to tag writes from the listener\&. 
.PP
Definition at line 129 of file bus_internal_types\&.h\&.
.SS "#define DEF_FD_SET_SIZE2   4"

.PP
Starting size^2 for file descriptor hash table\&. 
.PP
Definition at line 132 of file bus_internal_types\&.h\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBshutdown_state_t\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fISHUTDOWN_STATE_RUNNING \fP\fP
.TP
\fB\fISHUTDOWN_STATE_SHUTTING_DOWN \fP\fP
.TP
\fB\fISHUTDOWN_STATE_HALTED \fP\fP
.PP
Definition at line 65 of file bus_internal_types\&.h\&.
.SS "enum \fBrx_error_t\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIRX_ERROR_NONE \fP\fP
.TP
\fB\fIRX_ERROR_READY_FOR_DELIVERY \fP\fP
.TP
\fB\fIRX_ERROR_DONE \fP\fP
.TP
\fB\fIRX_ERROR_POLLHUP \fP\fP
.TP
\fB\fIRX_ERROR_POLLERR \fP\fP
.TP
\fB\fIRX_ERROR_READ_FAILURE \fP\fP
.TP
\fB\fIRX_ERROR_TIMEOUT \fP\fP
.PP
Definition at line 100 of file bus_internal_types\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
