.TH "bus_sink_cb_res_t" 3 "Tue Mar 3 2015" "Version v0.12.0-beta" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bus_sink_cb_res_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <bus_types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "size_t \fBnext_read\fP"
.br
.ti -1c
.RI "void * \fBfull_msg_buffer\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 112 of file bus_types\&.h\&.
.SH "Field Documentation"
.PP 
.SS "size_t bus_sink_cb_res_t::next_read"

.PP
Definition at line 113 of file bus_types\&.h\&.
.SS "void* bus_sink_cb_res_t::full_msg_buffer"

.PP
Definition at line 114 of file bus_types\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
