.TH "bus_config" 3 "Fri Mar 13 2015" "Version v0.12.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bus_config \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <bus_types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBlistener_count\fP"
.br
.ti -1c
.RI "struct \fBthreadpool_config\fP \fBthreadpool_cfg\fP"
.br
.ti -1c
.RI "\fBbus_sink_cb\fP * \fBsink_cb\fP"
.br
.ti -1c
.RI "\fBbus_unpack_cb\fP * \fBunpack_cb\fP"
.br
.ti -1c
.RI "\fBbus_unexpected_msg_cb\fP * \fBunexpected_msg_cb\fP"
.br
.ti -1c
.RI "\fBbus_error_cb\fP * \fBerror_cb\fP"
.br
.ti -1c
.RI "int \fBlog_level\fP"
.br
.ti -1c
.RI "\fBbus_log_cb\fP * \fBlog_cb\fP"
.br
.ti -1c
.RI "void * \fBbus_udata\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 163 of file bus_types\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int bus_config::listener_count"

.PP
Definition at line 165 of file bus_types\&.h\&.
.SS "struct \fBthreadpool_config\fP bus_config::threadpool_cfg"

.PP
Definition at line 166 of file bus_types\&.h\&.
.SS "\fBbus_sink_cb\fP* bus_config::sink_cb"

.PP
Definition at line 169 of file bus_types\&.h\&.
.SS "\fBbus_unpack_cb\fP* bus_config::unpack_cb"

.PP
Definition at line 170 of file bus_types\&.h\&.
.SS "\fBbus_unexpected_msg_cb\fP* bus_config::unexpected_msg_cb"

.PP
Definition at line 171 of file bus_types\&.h\&.
.SS "\fBbus_error_cb\fP* bus_config::error_cb"

.PP
Definition at line 172 of file bus_types\&.h\&.
.SS "int bus_config::log_level"

.PP
Definition at line 174 of file bus_types\&.h\&.
.SS "\fBbus_log_cb\fP* bus_config::log_cb"

.PP
Definition at line 175 of file bus_types\&.h\&.
.SS "void* bus_config::bus_udata"

.PP
Definition at line 177 of file bus_types\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
