.TH "bus_ssl.h" 3 "Fri Mar 13 2015" "Version v0.12.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bus_ssl.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'bus\&.h'\fP
.br
\fC#include 'bus_internal_types\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBKINETIC_USE_TLS_1_2\fP   0"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBBusSSL_Init\fP (struct \fBbus\fP *b)"
.br
.RI "\fIInitialize the SSL library internals for use by the messaging bus\&. \fP"
.ti -1c
.RI "SSL * \fBBusSSL_Connect\fP (struct \fBbus\fP *b, int fd)"
.br
.RI "\fIDo an SSL / TLS shake for a connection\&. \fP"
.ti -1c
.RI "bool \fBBusSSL_Disconnect\fP (struct \fBbus\fP *b, SSL *ssl)"
.br
.RI "\fIDisconnect and free an individual SSL handle\&. \fP"
.ti -1c
.RI "void \fBBusSSL_CtxFree\fP (struct \fBbus\fP *b)"
.br
.RI "\fIFree all internal data for using SSL (the SSL_CTX)\&. \fP"
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define KINETIC_USE_TLS_1_2   0"

.PP
Definition at line 28 of file bus_ssl\&.h\&.
.SH "Function Documentation"
.PP 
.SS "bool BusSSL_Init (struct \fBbus\fP *b)"

.PP
Initialize the SSL library internals for use by the messaging bus\&. 
.PP
Definition at line 36 of file bus_ssl\&.c\&.
.PP
References init_client_SSL_CTX(), and bus::ssl_ctx\&.
.SS "SSL* BusSSL_Connect (struct \fBbus\fP *b, intfd)"

.PP
Do an SSL / TLS shake for a connection\&. Blocking\&. 
.PP
Definition at line 51 of file bus_ssl\&.c\&.
.PP
References do_blocking_connection(), and bus::ssl_ctx\&.
.SS "bool BusSSL_Disconnect (struct \fBbus\fP *b, SSL *ssl)"

.PP
Disconnect and free an individual SSL handle\&. 
.PP
Definition at line 73 of file bus_ssl\&.c\&.
.SS "void BusSSL_CtxFree (struct \fBbus\fP *b)"

.PP
Free all internal data for using SSL (the SSL_CTX)\&. 
.PP
Definition at line 80 of file bus_ssl\&.c\&.
.PP
References bus::ssl_ctx\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
