.TH "bus_ssl.c" 3 "Fri Mar 13 2015" "Version v0.12.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bus_ssl.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <poll\&.h>\fP
.br
\fC#include <assert\&.h>\fP
.br
\fC#include 'bus_ssl\&.h'\fP
.br
\fC#include 'syscall\&.h'\fP
.br
\fC#include 'util\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTIMEOUT_MSEC\fP   100"
.br
.ti -1c
.RI "#define \fBMAX_TIMEOUT\fP   10000"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "static bool \fBinit_client_SSL_CTX\fP (SSL_CTX **ctx_out)"
.br
.ti -1c
.RI "static void \fBdisable_SSL_compression\fP (void)"
.br
.ti -1c
.RI "static void \fBdisable_known_bad_ciphers\fP (SSL_CTX *ctx)"
.br
.ti -1c
.RI "static bool \fBdo_blocking_connection\fP (struct \fBbus\fP *b, SSL *ssl, int fd)"
.br
.ti -1c
.RI "bool \fBBusSSL_Init\fP (struct \fBbus\fP *b)"
.br
.RI "\fIInitialize the SSL library internals for use by the messaging bus\&. \fP"
.ti -1c
.RI "SSL * \fBBusSSL_Connect\fP (struct \fBbus\fP *b, int fd)"
.br
.RI "\fIDo an SSL / TLS shake for a connection\&. \fP"
.ti -1c
.RI "bool \fBBusSSL_Disconnect\fP (struct \fBbus\fP *b, SSL *ssl)"
.br
.RI "\fIDisconnect and free an individual SSL handle\&. \fP"
.ti -1c
.RI "void \fBBusSSL_CtxFree\fP (struct \fBbus\fP *b)"
.br
.RI "\fIFree all internal data for using SSL (the SSL_CTX)\&. \fP"
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define TIMEOUT_MSEC   100"

.PP
Definition at line 27 of file bus_ssl\&.c\&.
.SS "#define MAX_TIMEOUT   10000"

.PP
Definition at line 28 of file bus_ssl\&.c\&.
.SH "Function Documentation"
.PP 
.SS "static bool init_client_SSL_CTX (SSL_CTX **ctx_out)\fC [static]\fP"

.PP
Definition at line 87 of file bus_ssl\&.c\&.
.PP
References disable_known_bad_ciphers(), and disable_SSL_compression()\&.
.SS "static void disable_SSL_compression (void)\fC [static]\fP"

.PP
Definition at line 113 of file bus_ssl\&.c\&.
.SS "static void disable_known_bad_ciphers (SSL_CTX *ctx)\fC [static]\fP"

.PP
Definition at line 122 of file bus_ssl\&.c\&.
.SS "static bool do_blocking_connection (struct \fBbus\fP *b, SSL *ssl, intfd)\fC [static]\fP"

.PP
Definition at line 130 of file bus_ssl\&.c\&.
.PP
References BUS_LOG, BUS_LOG_SNPRINTF, LOG_SOCKET_REGISTERED, MAX_TIMEOUT, syscall_poll(), TIMEOUT_MSEC, bus::udata, and Util_IsResumableIOError()\&.
.SS "bool BusSSL_Init (struct \fBbus\fP *b)"

.PP
Initialize the SSL library internals for use by the messaging bus\&. 
.PP
Definition at line 36 of file bus_ssl\&.c\&.
.PP
References init_client_SSL_CTX(), and bus::ssl_ctx\&.
.SS "SSL* BusSSL_Connect (struct \fBbus\fP *b, intfd)"

.PP
Do an SSL / TLS shake for a connection\&. Blocking\&. 
.PP
Definition at line 51 of file bus_ssl\&.c\&.
.PP
References do_blocking_connection(), and bus::ssl_ctx\&.
.SS "bool BusSSL_Disconnect (struct \fBbus\fP *b, SSL *ssl)"

.PP
Disconnect and free an individual SSL handle\&. 
.PP
Definition at line 73 of file bus_ssl\&.c\&.
.SS "void BusSSL_CtxFree (struct \fBbus\fP *b)"

.PP
Free all internal data for using SSL (the SSL_CTX)\&. 
.PP
Definition at line 80 of file bus_ssl\&.c\&.
.PP
References bus::ssl_ctx\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
