.TH "ByteBufferArray" 3 "Wed Feb 11 2015" "Version v0.11.1" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ByteBufferArray \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <byte_array\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBByteBuffer\fP * \fBbuffers\fP"
.br
.ti -1c
.RI "size_t \fBcount\fP"
.br
.ti -1c
.RI "size_t \fBused\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 58 of file byte_array\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBByteBuffer\fP* ByteBufferArray::buffers"

.PP
Definition at line 59 of file byte_array\&.h\&.
.SS "size_t ByteBufferArray::count"

.PP
Definition at line 60 of file byte_array\&.h\&.
.SS "size_t ByteBufferArray::used"

.PP
Definition at line 61 of file byte_array\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
