byte_array.h
NAME
byte_array.h -
SYNOPSIS
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
Data Structures
struct ByteArray
Structure for handling generic arrays of bytes.
struct ByteBuffer
Structure for an embedded ByteArray as a buffer.
struct ByteBufferArray
Macros
#define BYTE_ARRAY_NONE (ByteArray){.len = 0, .data = NULL}
Convenience macro to represent an empty array with no data.
#define BYTE_BUFFER_NONE (ByteBuffer){.array = BYTE_ARRAY_NONE, .bytesUsed = 0}
Convenience macro to represent an empty buffer with no data.
Functions
ByteArray ByteArray_Create (void *data, size_t len)
ByteArray ByteArray_CreateWithCString (const char *str)
ByteArray ByteArray_GetSlice (const ByteArray array, size_t start, size_t len)
void ByteArray_FillWithDummyData (const ByteArray array)
ByteBuffer ByteBuffer_Create (void *data, size_t max_len, size_t used)
ByteBuffer ByteBuffer_CreateWithArray (ByteArray array)
ByteBuffer ByteBuffer_CreateAndAppend (void *data, size_t max_len, const void *value, size_t value_len)
ByteBuffer ByteBuffer_CreateAndAppendArray (void *data, size_t max_len, const ByteArray value)
ByteBuffer ByteBuffer_CreateAndAppendCString (void *data, size_t max_len, const char *value)
ByteBuffer ByteBuffer_CreateAndAppendFormattedCString (void *data, size_t max_len, const char *format,...)
ByteBuffer ByteBuffer_CreateAndAppendDummyData (void *data, size_t max_len, size_t len)
void ByteBuffer_Reset (ByteBuffer *buffer)
long ByteBuffer_BytesRemaining (const ByteBuffer buffer)
ByteArray ByteBuffer_Consume (ByteBuffer *buffer, size_t max_len)
ByteBuffer * ByteBuffer_Append (ByteBuffer *buffer, const void *data, size_t len)
ByteBuffer * ByteBuffer_AppendArray (ByteBuffer *buffer, const ByteArray array)
ByteBuffer * ByteBuffer_AppendBuffer (ByteBuffer *buffer, const ByteBuffer bufferToAppend)
ByteBuffer * ByteBuffer_AppendCString (ByteBuffer *buffer, const char *data)
ByteBuffer * ByteBuffer_AppendFormattedCString (ByteBuffer *buffer, const char *format,...)
ByteBuffer * ByteBuffer_AppendDummyData (ByteBuffer *buffer, size_t len)
bool ByteBuffer_IsNull (ByteBuffer const buffer)
ByteBuffer ByteBuffer_Malloc (size_t size)
ByteBuffer ByteBuffer_MallocAndAppend (const void *data, size_t len)
void ByteBuffer_Free (ByteBuffer buffer)
Macro Definition Documentation
#define BYTE_ARRAY_NONE (ByteArray){.len = 0, .data = NULL}
Convenience macro to represent an empty array with no data.
Definition at line 21 of file byte_array.h.
#define BYTE_BUFFER_NONE (ByteBuffer){.array = BYTE_ARRAY_NONE, .bytesUsed = 0}
Convenience macro to represent an empty buffer with no data.
Definition at line 46 of file byte_array.h.
Function Documentation
ByteArray ByteArray_Create (void *data, size_tlen)
Definition at line 12 of file byte_array.c.
References ByteArray::data.
ByteArray ByteArray_CreateWithCString (const char *str)
Definition at line 19 of file byte_array.c.
References ByteArray::data.
ByteArray ByteArray_GetSlice (const ByteArrayarray, size_tstart, size_tlen)
Definition at line 33 of file byte_array.c.
References ByteArray::data, and ByteArray::len.
void ByteArray_FillWithDummyData (const ByteArrayarray)
Definition at line 26 of file byte_array.c.
References ByteArray::data, and ByteArray::len.
ByteBuffer ByteBuffer_Create (void *data, size_tmax_len, size_tused)
Definition at line 49 of file byte_array.c.
ByteBuffer ByteBuffer_CreateWithArray (ByteArrayarray)
Definition at line 59 of file byte_array.c.
References ByteBuffer::array.
ByteBuffer ByteBuffer_CreateAndAppend (void *data, size_tmax_len, const void *value, size_tvalue_len)
Definition at line 64 of file byte_array.c.
References ByteBuffer_Append(), and ByteBuffer_Create().
ByteBuffer ByteBuffer_CreateAndAppendArray (void *data, size_tmax_len, const ByteArrayvalue)
Definition at line 71 of file byte_array.c.
References ByteBuffer_AppendArray(), and ByteBuffer_Create().
ByteBuffer ByteBuffer_CreateAndAppendCString (void *data, size_tmax_len, const char *value)
Definition at line 78 of file byte_array.c.
References ByteBuffer_AppendCString(), and ByteBuffer_Create().
ByteBuffer ByteBuffer_CreateAndAppendFormattedCString (void *data, size_tmax_len, const char *format, ...)
Definition at line 202 of file byte_array.c.
References ByteBuffer_Create().
ByteBuffer ByteBuffer_CreateAndAppendDummyData (void *data, size_tmax_len, size_tlen)
Definition at line 85 of file byte_array.c.
References ByteBuffer_AppendDummyData(), and ByteBuffer_Create().
void ByteBuffer_Reset (ByteBuffer *buffer)
Definition at line 43 of file byte_array.c.
References ByteBuffer::bytesUsed.
long ByteBuffer_BytesRemaining (const ByteBufferbuffer)
Definition at line 92 of file byte_array.c.
References ByteBuffer::array, ByteBuffer::bytesUsed, ByteArray::data, and ByteArray::len.
ByteArray ByteBuffer_Consume (ByteBuffer *buffer, size_tmax_len)
Definition at line 98 of file byte_array.c.
References ByteBuffer::array, BYTE_ARRAY_NONE, ByteBuffer_BytesRemaining(), ByteBuffer::bytesUsed, ByteArray::data, and ByteArray::len.
ByteBuffer* ByteBuffer_Append (ByteBuffer *buffer, const void *data, size_tlen)
Definition at line 116 of file byte_array.c.
References ByteBuffer::array, ByteBuffer::bytesUsed, ByteArray::data, and ByteArray::len.
ByteBuffer* ByteBuffer_AppendArray (ByteBuffer *buffer, const ByteArrayarray)
Definition at line 130 of file byte_array.c.
References ByteBuffer::array, ByteBuffer::bytesUsed, ByteArray::data, and ByteArray::len.
ByteBuffer* ByteBuffer_AppendBuffer (ByteBuffer *buffer, const ByteBufferbufferToAppend)
Definition at line 143 of file byte_array.c.
References ByteBuffer::array, ByteBuffer::bytesUsed, ByteArray::data, and ByteArray::len.
ByteBuffer* ByteBuffer_AppendCString (ByteBuffer *buffer, const char *data)
Definition at line 157 of file byte_array.c.
References ByteBuffer::array, ByteBuffer::bytesUsed, ByteArray::data, and ByteArray::len.
ByteBuffer* ByteBuffer_AppendFormattedCString (ByteBuffer *buffer, const char *format, ...)
Definition at line 186 of file byte_array.c.
References ByteBuffer::array, and ByteArray::data.
ByteBuffer* ByteBuffer_AppendDummyData (ByteBuffer *buffer, size_tlen)
Definition at line 216 of file byte_array.c.
References ByteBuffer::array, ByteBuffer::bytesUsed, ByteArray::data, and ByteArray::len.
bool ByteBuffer_IsNull (ByteBuffer constbuffer)
Definition at line 230 of file byte_array.c.
References ByteBuffer::array, and ByteArray::data.
ByteBuffer ByteBuffer_Malloc (size_tsize)
Definition at line 235 of file byte_array.c.
References ByteBuffer_Create().
ByteBuffer ByteBuffer_MallocAndAppend (const void *data, size_tlen)
Definition at line 243 of file byte_array.c.
References ByteBuffer_Append(), ByteBuffer_IsNull(), and ByteBuffer_Malloc().
void ByteBuffer_Free (ByteBufferbuffer)
Definition at line 253 of file byte_array.c.
References ByteBuffer::array, and ByteArray::data.
Author
Generated automatically by Doxygen for kinetic-c from the source code.