.TH "ByteBuffer" 3 "Wed Sep 10 2014" "Version v0.6.0" "protobuf-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ByteBuffer \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBByteArray\fP \fBbuffer\fP"
.br
.ti -1c
.RI "size_t \fBmaxLen\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 97 of file kinetic_types\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBByteArray\fP ByteBuffer::buffer"

.PP
Definition at line 99 of file kinetic_types\&.h\&.
.SS "size_t ByteBuffer::maxLen"

.PP
Definition at line 100 of file kinetic_types\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for protobuf-c from the source code\&.
