.TH "ByteBufferArray" 3 "Tue Nov 4 2014" "Version v0.8.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ByteBufferArray \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <byte_array\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBByteBuffer\fP * \fBbuffers\fP"
.br
.ti -1c
.RI "int \fBcount\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 39 of file byte_array\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBByteBuffer\fP* ByteBufferArray::buffers"

.PP
Definition at line 40 of file byte_array\&.h\&.
.SS "int ByteBufferArray::count"

.PP
Definition at line 41 of file byte_array\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
