.TH "ByteBuffer" 3 "Tue Mar 3 2015" "Version v0.12.0-beta" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ByteBuffer \- 
.PP
Structure for an embedded \fBByteArray\fP as a buffer\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <byte_array\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBByteArray\fP \fBarray\fP"
.br
.RI "\fI\fBByteArray\fP holding allocated array w/length = allocated size\&. \fP"
.ti -1c
.RI "size_t \fBbytesUsed\fP"
.br
.RI "\fIReflects the number of bytes used from the \fCarray\fP \fP"
.in -1c
.SH "Detailed Description"
.PP 
Structure for an embedded \fBByteArray\fP as a buffer\&. 

The \fCbytesUsed\fP field is initialized to zero, and is to incremented as each byte is consumed, but shall not exceed the \fCarray\fP length 
.PP
Definition at line 53 of file byte_array\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBByteArray\fP ByteBuffer::array"

.PP
\fBByteArray\fP holding allocated array w/length = allocated size\&. 
.PP
Definition at line 54 of file byte_array\&.h\&.
.SS "size_t ByteBuffer::bytesUsed"

.PP
Reflects the number of bytes used from the \fCarray\fP 
.PP
Definition at line 55 of file byte_array\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
