.TH "fd_info" 3 "Tue Jan 27 2015" "Version v0.11.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fd_info \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sender_internal\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBfd\fP"
.br
.ti -1c
.RI "SSL * \fBssl\fP"
.br
.ti -1c
.RI "int \fBrefcount\fP"
.br
.ti -1c
.RI "int64_t \fBlargest_seq_id_seen\fP"
.br
.ti -1c
.RI "bool \fBerrored\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 67 of file sender_internal\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int fd_info::fd"

.PP
Definition at line 68 of file sender_internal\&.h\&.
.SS "SSL* fd_info::ssl"

.PP
Definition at line 69 of file sender_internal\&.h\&.
.SS "int fd_info::refcount"

.PP
Definition at line 70 of file sender_internal\&.h\&.
.SS "int64_t fd_info::largest_seq_id_seen"

.PP
Definition at line 71 of file sender_internal\&.h\&.
.SS "bool fd_info::errored"

.PP
Definition at line 72 of file sender_internal\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
