get.c
NAME
get.c -
SYNOPSIS
#include 'get.h'
Functions
int Get (const char *host, int port, bool nonBlocking, int64_t clusterVersion, int64_t identity, ByteArray hmacKey, KineticKeyValue *metadata)
Connects to the specified Kinetic host/port and executes a Get to retrieve an object from the Device.
Variables
KineticPDU Request
KineticPDU Response
Function Documentation
int Get (const char *host, intport, boolnonBlocking, int64_tclusterVersion, int64_tidentity, ByteArrayhmacKey, KineticKeyValue *metadata)
Connects to the specified Kinetic host/port and executes a Get to retrieve an object from the Device.
Parameters:
host Host name or IP address to connect to
port Port to establish socket connection on
nonBlocking Set to true for non-blocking or false for blocking I/O
clusterVersion Cluster version to use for the operation
identity Identity to use for the operation (Must have ACL setup on Kinetic Device)
hmacKey Shared secret key used for the identity for HMAC calculation
metadata Key/value metadata for object to retrieve. 'value' will be populated unless 'metadataOnly' is set to 'true'
Returns:
Returns 0 upon succes, -1 or the Kinetic status code upon failure
Definition at line 25 of file get.c.
References KINETIC_STATUS_SUCCESS, KineticClient_Connect(), KineticClient_CreateOperation(), KineticClient_Disconnect(), KineticClient_Get(), and KineticClient_Init().
Variable Documentation
KineticPDU Request
Definition at line 23 of file get.c.
KineticPDU Response
Definition at line 23 of file get.c.
Author
Generated automatically by Doxygen for protobuf-c from the source code.