get_key_range.c
NAME
get_key_range.c -
SYNOPSIS
#include 'kinetic_client.h'
#include 'kinetic_types.h'
#include 'byte_array.h'
#include <stdlib.h>
#include <getopt.h>
#include <stdio.h>
#include <sys/param.h>
#include <sys/stat.h>
#include <sys/file.h>
Functions
static bool create_entries (KineticSession const *const session, const int count)
int main (int argc, char **argv)
Function Documentation
static bool create_entries (KineticSession const *constsession, const intcount) [static]
Definition at line 117 of file get_key_range.c.
References ByteBuffer_CreateAndAppendFormattedCString(), KineticEntry::key, KINETIC_ALGORITHM_SHA1, KINETIC_STATUS_SUCCESS, and KineticClient_Put().
int main (intargc, char **argv)
Definition at line 33 of file get_key_range.c.
References ByteBufferArray::buffers, ByteArray_CreateWithCString(), ByteBuffer_Create(), ByteBuffer_CreateAndAppendCString(), create_entries(), KineticSessionConfig::host, Kinetic_GetStatusDescription(), KINETIC_PORT, KINETIC_STATUS_SUCCESS, KineticClient_CreateSession(), KineticClient_DestroySession(), KineticClient_GetKeyRange(), KineticClient_Init(), KineticClient_Shutdown(), KineticClientConfig::logFile, KineticKeyRange::startKey, and ByteBufferArray::used.
Author
Generated automatically by Doxygen for kinetic-c from the source code.