get_nonblocking.c
NAME
get_nonblocking.c -
SYNOPSIS
#include 'kinetic_client.h'
#include 'kinetic_types.h'
#include 'kinetic_semaphore.h'
#include <stdlib.h>
#include <sys/param.h>
#include <openssl/sha.h>
#include <pthread.h>
Functions
int main (int argc, char **argv)
Function Documentation
int main (intargc, char **argv)
Definition at line 35 of file get_nonblocking.c.
References ByteBuffer::array, ByteArray_CreateWithCString(), ByteBuffer_Append(), ByteBuffer_Free(), ByteBuffer_Malloc(), ByteBuffer_MallocAndAppend(), ByteBuffer::bytesUsed, KineticSession::config, ByteArray::data, KineticSessionConfig::host, KineticEntry::key, KINETIC_ALGORITHM_SHA1, Kinetic_GetStatusDescription(), KINETIC_PORT, KINETIC_STATUS_INVALID, KINETIC_STATUS_SUCCESS, KINETIC_SYNCHRONIZATION_WRITETHROUGH, KineticClient_CreateConnection(), KineticClient_DestroyConnection(), KineticClient_Get(), KineticClient_Init(), KineticClient_Put(), KineticClient_Shutdown(), KineticSemaphore_Create(), KineticSemaphore_WaitForSignalAndDestroy(), and KineticClientConfig::logFile.
Author
Generated automatically by Doxygen for kinetic-c from the source code.