.TH "greatest_run_info" 3 "Tue Jan 27 2015" "Version v0.11.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
greatest_run_info \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <greatest\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned int \fBflags\fP"
.br
.ti -1c
.RI "unsigned int \fBtests_run\fP"
.br
.ti -1c
.RI "unsigned int \fBpassed\fP"
.br
.ti -1c
.RI "unsigned int \fBfailed\fP"
.br
.ti -1c
.RI "unsigned int \fBskipped\fP"
.br
.ti -1c
.RI "unsigned int \fBassertions\fP"
.br
.ti -1c
.RI "\fBgreatest_suite_info\fP \fBsuite\fP"
.br
.ti -1c
.RI "const char * \fBfail_file\fP"
.br
.ti -1c
.RI "unsigned int \fBfail_line\fP"
.br
.ti -1c
.RI "const char * \fBmsg\fP"
.br
.ti -1c
.RI "\fBgreatest_setup_cb\fP * \fBsetup\fP"
.br
.ti -1c
.RI "void * \fBsetup_udata\fP"
.br
.ti -1c
.RI "\fBgreatest_teardown_cb\fP * \fBteardown\fP"
.br
.ti -1c
.RI "void * \fBteardown_udata\fP"
.br
.ti -1c
.RI "unsigned int \fBcol\fP"
.br
.ti -1c
.RI "unsigned int \fBwidth\fP"
.br
.ti -1c
.RI "char * \fBsuite_filter\fP"
.br
.ti -1c
.RI "char * \fBtest_filter\fP"
.br
.ti -1c
.RI "clock_t \fBbegin\fP"
.br
.ti -1c
.RI "clock_t \fBend\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 150 of file bus/greatest\&.h\&.
.SH "Field Documentation"
.PP 
.SS "unsigned int greatest_run_info::flags"

.PP
Definition at line 151 of file bus/greatest\&.h\&.
.SS "unsigned int greatest_run_info::tests_run"

.PP
Definition at line 152 of file bus/greatest\&.h\&.
.SS "unsigned int greatest_run_info::passed"

.PP
Definition at line 155 of file bus/greatest\&.h\&.
.SS "unsigned int greatest_run_info::failed"

.PP
Definition at line 156 of file bus/greatest\&.h\&.
.SS "unsigned int greatest_run_info::skipped"

.PP
Definition at line 157 of file bus/greatest\&.h\&.
.SS "unsigned int greatest_run_info::assertions"

.PP
Definition at line 158 of file bus/greatest\&.h\&.
.SS "\fBgreatest_suite_info\fP greatest_run_info::suite"

.PP
Definition at line 161 of file bus/greatest\&.h\&.
.SS "const char * greatest_run_info::fail_file"

.PP
Definition at line 164 of file bus/greatest\&.h\&.
.SS "unsigned int greatest_run_info::fail_line"

.PP
Definition at line 165 of file bus/greatest\&.h\&.
.SS "const char * greatest_run_info::msg"

.PP
Definition at line 166 of file bus/greatest\&.h\&.
.SS "\fBgreatest_setup_cb\fP * greatest_run_info::setup"

.PP
Definition at line 169 of file bus/greatest\&.h\&.
.SS "void * greatest_run_info::setup_udata"

.PP
Definition at line 170 of file bus/greatest\&.h\&.
.SS "\fBgreatest_teardown_cb\fP * greatest_run_info::teardown"

.PP
Definition at line 171 of file bus/greatest\&.h\&.
.SS "void * greatest_run_info::teardown_udata"

.PP
Definition at line 172 of file bus/greatest\&.h\&.
.SS "unsigned int greatest_run_info::col"

.PP
Definition at line 175 of file bus/greatest\&.h\&.
.SS "unsigned int greatest_run_info::width"

.PP
Definition at line 176 of file bus/greatest\&.h\&.
.SS "char * greatest_run_info::suite_filter"

.PP
Definition at line 179 of file bus/greatest\&.h\&.
.SS "char * greatest_run_info::test_filter"

.PP
Definition at line 180 of file bus/greatest\&.h\&.
.SS "clock_t greatest_run_info::begin"

.PP
Definition at line 183 of file bus/greatest\&.h\&.
.SS "clock_t greatest_run_info::end"

.PP
Definition at line 184 of file bus/greatest\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
