.TH "greatest_suite_info" 3 "Wed Feb 11 2015" "Version v0.11.1" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
greatest_suite_info \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <greatest\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned int \fBtests_run\fP"
.br
.ti -1c
.RI "unsigned int \fBpassed\fP"
.br
.ti -1c
.RI "unsigned int \fBfailed\fP"
.br
.ti -1c
.RI "unsigned int \fBskipped\fP"
.br
.ti -1c
.RI "clock_t \fBpre_suite\fP"
.br
.ti -1c
.RI "clock_t \fBpost_suite\fP"
.br
.ti -1c
.RI "clock_t \fBpre_test\fP"
.br
.ti -1c
.RI "clock_t \fBpost_test\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 121 of file bus/greatest\&.h\&.
.SH "Field Documentation"
.PP 
.SS "unsigned int greatest_suite_info::tests_run"

.PP
Definition at line 122 of file bus/greatest\&.h\&.
.SS "unsigned int greatest_suite_info::passed"

.PP
Definition at line 123 of file bus/greatest\&.h\&.
.SS "unsigned int greatest_suite_info::failed"

.PP
Definition at line 124 of file bus/greatest\&.h\&.
.SS "unsigned int greatest_suite_info::skipped"

.PP
Definition at line 125 of file bus/greatest\&.h\&.
.SS "clock_t greatest_suite_info::pre_suite"

.PP
Definition at line 128 of file bus/greatest\&.h\&.
.SS "clock_t greatest_suite_info::post_suite"

.PP
Definition at line 129 of file bus/greatest\&.h\&.
.SS "clock_t greatest_suite_info::pre_test"

.PP
Definition at line 130 of file bus/greatest\&.h\&.
.SS "clock_t greatest_suite_info::post_test"

.PP
Definition at line 131 of file bus/greatest\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
