.TH "KineticOperation" 3 "Thu Jul 24 2014" "Version v0.3.3" "protobuf-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticOperation \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBKineticExchange\fP * \fBexchange\fP"
.br
.ti -1c
.RI "\fBKineticPDU\fP * \fBrequest\fP"
.br
.ti -1c
.RI "\fBKineticPDU\fP * \fBresponse\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 28 of file kinetic_operation\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for protobuf-c from the source code\&.
