kinetic_nbo.c
NAME
kinetic_nbo.c -
SYNOPSIS
#include 'kinetic_nbo.h'
Functions
static uint64_t KineticNBO_SwapByteOrder (uint8_t *pByte, size_t len)
uint32_t KineticNBO_FromHostU32 (uint32_t valueHost)
uint32_t KineticNBO_ToHostU32 (uint32_t valueNBO)
uint64_t KineticNBO_FromHostU64 (uint64_t valueHost)
uint64_t KineticNBO_ToHostU64 (uint64_t valueNBO)
Function Documentation
static uint64_t KineticNBO_SwapByteOrder (uint8_t *pByte, size_tlen) [static]
Definition at line 23 of file kinetic_nbo.c.
uint32_t KineticNBO_FromHostU32 (uint32_tvalueHost)
Definition at line 32 of file kinetic_nbo.c.
References KineticNBO_SwapByteOrder().
uint32_t KineticNBO_ToHostU32 (uint32_tvalueNBO)
Definition at line 38 of file kinetic_nbo.c.
References KineticNBO_SwapByteOrder().
uint64_t KineticNBO_FromHostU64 (uint64_tvalueHost)
Definition at line 44 of file kinetic_nbo.c.
References KineticNBO_SwapByteOrder().
uint64_t KineticNBO_ToHostU64 (uint64_tvalueNBO)
Definition at line 50 of file kinetic_nbo.c.
References KineticNBO_SwapByteOrder().
Author
Generated automatically by Doxygen for kinetic-c from the source code.