.TH "kinetic_message.h" 3 "Thu Sep 11 2014" "Version v0.6.0-beta-2" "protobuf-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kinetic_message.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'kinetic_types_internal\&.h'\fP
.br
\fC#include 'kinetic_hmac\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBKineticMessage_Init\fP (\fBKineticMessage\fP *const message)"
.br
.ti -1c
.RI "void \fBKineticMessage_ConfigureKeyValue\fP (\fBKineticMessage\fP *const message, const \fBKineticKeyValue\fP *metadata)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void KineticMessage_Init (\fBKineticMessage\fP *constmessage)"

.PP
Definition at line 23 of file kinetic_message\&.c\&.
.PP
References KINETIC_MESSAGE_INIT\&.
.SS "void KineticMessage_ConfigureKeyValue (\fBKineticMessage\fP *constmessage, const \fBKineticKeyValue\fP *metadata)"

.PP
Definition at line 42 of file kinetic_message\&.c\&.
.PP
References KineticKeyValue::algorithm, KineticMessage::body, KineticMessage::command, CONFIG_FIELD_BYTE_ARRAY, KineticMessage::keyValue, KineticKeyValue::metadataOnly, and KineticMessage::proto\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for protobuf-c from the source code\&.
