kinetic_controller.h
NAME
kinetic_controller.h -
SYNOPSIS
#include 'kinetic_types_internal.h'
Functions
KineticStatus KineticController_Init (KineticSession const *const session)
KineticOperation * KineticController_CreateOperation (KineticSession const *const session)
KineticStatus KineticController_ExecuteOperation (KineticOperation *operation, KineticCompletionClosure *closure)
void KineticController_Pause (KineticSession const *const session, bool pause)
void * KineticController_ReceiveThread (void *thread_arg)
void KineticController_HandleIncomingPDU (KineticConnection *const connection)
Function Documentation
KineticStatus KineticController_Init (KineticSession const *constsession)
Definition at line 30 of file kinetic_controller.c.
References KineticSession::connection, Kinetic_GetErrnoDescription(), KINETIC_STATUS_CONNECTION_ERROR, KINETIC_STATUS_SUCCESS, KineticController_ReceiveThread(), LOGF0, KineticConnection::thread, and KineticConnection::threadID.
KineticOperation* KineticController_CreateOperation (KineticSession const *constsession)
Definition at line 50 of file kinetic_controller.c.
References KineticSession::connection, KineticAllocator_NewOperation(), LOG0, and LOGF1.
KineticStatus KineticController_ExecuteOperation (KineticOperation *operation, KineticCompletionClosure *closure)
Definition at line 95 of file kinetic_controller.c.
References KINETIC_STATUS_INVALID, KINETIC_STATUS_SUCCESS, KineticOperation_SendRequest(), and LOGF1.
void KineticController_Pause (KineticSession const *constsession, boolpause)
Definition at line 143 of file kinetic_controller.c.
References KineticSession::connection, KineticThread::paused, and KineticConnection::thread.
void* KineticController_ReceiveThread (void *thread_arg)
Definition at line 251 of file kinetic_controller.c.
References KineticThread::abortRequested, KineticThread::connection, KineticThread::fatalError, KINETIC_STATUS_SUCCESS, LOG3, and KineticThread::paused.
void KineticController_HandleIncomingPDU (KineticConnection *constconnection)
Definition at line 150 of file kinetic_controller.c.
References Kinetic_GetStatusDescription(), KINETIC_PDU_TYPE_RESPONSE, KINETIC_PDU_TYPE_UNSOLICITED, KINETIC_PROTO_MESSAGE_AUTH_TYPE_UNSOLICITEDSTATUS, KINETIC_STATUS_SUCCESS, KineticAllocator_FreePDU(), KineticAllocator_NewPDU(), KineticOperation_AssociateResponseWithOperation(), KineticOperation_Complete(), KineticPDU_GetStatus(), KineticPDU_GetValueLength(), KineticPDU_ReceiveMain(), KineticPDU_ReceiveValue(), LOG0, LOG2, LOGF0, and LOGF2.
Author
Generated automatically by Doxygen for kinetic-c from the source code.