.TH "kinetic_client.h" 3 "Mon Mar 2 2015" "Version v0.12.0-beta" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kinetic_client.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'kinetic_types\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "KineticClient * \fBKineticClient_Init\fP (\fBKineticClientConfig\fP *config)"
.br
.RI "\fIInitializes the Kinetic API and configures logging\&. \fP"
.ti -1c
.RI "void \fBKineticClient_Shutdown\fP (KineticClient *const client)"
.br
.RI "\fIPerforms shutdown/cleanup of the kinetic-c client library\&. \fP"
.ti -1c
.RI "\fBKineticStatus\fP \fBKineticClient_CreateSession\fP (\fBKineticSessionConfig\fP *const config, KineticClient *const client, KineticSession **session)"
.br
.RI "\fICreates a session with the Kinetic Device per specified configuration\&. \fP"
.ti -1c
.RI "\fBKineticStatus\fP \fBKineticClient_DestroySession\fP (KineticSession *const session)"
.br
.RI "\fICloses the connection to a host\&. \fP"
.ti -1c
.RI "\fBKineticStatus\fP \fBKineticClient_NoOp\fP (KineticSession const *const session)"
.br
.RI "\fIExecutes a NOOP command to test whether the Kinetic Device is operational\&. \fP"
.ti -1c
.RI "\fBKineticStatus\fP \fBKineticClient_Put\fP (KineticSession const *const session, \fBKineticEntry\fP *const entry, \fBKineticCompletionClosure\fP *closure)"
.br
.RI "\fIExecutes a PUT command to store/update an entry on the Kinetic Device\&. \fP"
.ti -1c
.RI "\fBKineticStatus\fP \fBKineticClient_Flush\fP (KineticSession const *const session, \fBKineticCompletionClosure\fP *closure)"
.br
.RI "\fIExecutes a FLUSHALLDATA command to flush pending PUTs or DELETEs\&. \fP"
.ti -1c
.RI "\fBKineticStatus\fP \fBKineticClient_Get\fP (KineticSession const *const session, \fBKineticEntry\fP *const entry, \fBKineticCompletionClosure\fP *closure)"
.br
.RI "\fIExecutes a GET command to retrieve an entry from the Kinetic Device\&. \fP"
.ti -1c
.RI "\fBKineticStatus\fP \fBKineticClient_GetPrevious\fP (KineticSession const *const session, \fBKineticEntry\fP *const entry, \fBKineticCompletionClosure\fP *closure)"
.br
.RI "\fIExecutes a GETPREVIOUS command to retrieve the next entry from the Kinetic Device\&. \fP"
.ti -1c
.RI "\fBKineticStatus\fP \fBKineticClient_GetNext\fP (KineticSession const *const session, \fBKineticEntry\fP *const entry, \fBKineticCompletionClosure\fP *closure)"
.br
.RI "\fIExecutes a GETNEXT command to retrieve the next entry from the Kinetic Device\&. \fP"
.ti -1c
.RI "\fBKineticStatus\fP \fBKineticClient_Delete\fP (KineticSession const *const session, \fBKineticEntry\fP *const entry, \fBKineticCompletionClosure\fP *closure)"
.br
.RI "\fIExecutes a DELETE command to delete an entry from the Kinetic Device\&. \fP"
.ti -1c
.RI "\fBKineticStatus\fP \fBKineticClient_GetKeyRange\fP (KineticSession const *const session, \fBKineticKeyRange\fP *range, \fBByteBufferArray\fP *keys, \fBKineticCompletionClosure\fP *closure)"
.br
.RI "\fIExecutes a GETKEYRANGE command to retrieve a set of keys in the range specified range from the Kinetic Device\&. \fP"
.ti -1c
.RI "\fBKineticStatus\fP \fBKineticClient_P2POperation\fP (KineticSession const *const session, KineticP2P_Operation *const p2pOp, \fBKineticCompletionClosure\fP *closure)"
.br
.RI "\fIExecutes a PEER2PEERPUSH operation allows a client to instruct a Kinetic Device to copy a set of keys (and associated value and metadata) to another Kinetic Device\&. \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "KineticClient* KineticClient_Init (\fBKineticClientConfig\fP *config)"

.PP
Initializes the Kinetic API and configures logging\&. 
.PP
\fBParameters:\fP
.RS 4
\fIconfig\fP A configuration struct\&.
.RE
.PP
\fBReturns:\fP
.RS 4
Returns a pointer to a \fCKineticClient\fP\&. You need to pass this pointer to \fBKineticClient_CreateSession()\fP to create new connections\&. Once you are finished will the \fCKineticClient\fP, and there are no active connections\&. The pointer should be release with \fBKineticClient_Shutdown()\fP 
.RE
.PP

.PP
Definition at line 34 of file kinetic_client\&.c\&.
.PP
References KINETIC_CLIENT_DEFAULT_MAX_THREADPOOL_THREADS, KINETIC_CLIENT_DEFAULT_READER_THREADS, KINETIC_CLIENT_DEFAULT_WRITER_THREADS, KineticBus_Init(), KineticCalloc(), KineticFree(), KineticLogger_Init(), KineticClientConfig::logFile, KineticClientConfig::logLevel, KineticClientConfig::maxThreadpoolThreads, KineticClientConfig::readerThreads, and KineticClientConfig::writerThreads\&.
.SS "void KineticClient_Shutdown (KineticClient *constclient)"

.PP
Performs shutdown/cleanup of the kinetic-c client library\&. 
.PP
\fBParameters:\fP
.RS 4
\fIclient\fP The pointer returned from \fCKineticClient_Init\fP 
.RE
.PP

.PP
Definition at line 59 of file kinetic_client\&.c\&.
.PP
References KineticBus_Shutdown(), KineticFree(), and KineticLogger_Close()\&.
.SS "\fBKineticStatus\fP KineticClient_CreateSession (\fBKineticSessionConfig\fP *constconfig, KineticClient *constclient, KineticSession **session)"

.PP
Creates a session with the Kinetic Device per specified configuration\&. 
.PP
\fBParameters:\fP
.RS 4
\fIconfig\fP \fC\fBKineticSessionConfig\fP\fP structure which must be configured by the client prior to creating the device connection\&. \&.host Host name or IP address to connect to \&.port Port to establish socket connection on \&.clusterVersion Cluster version to use for the session \&.identity Identity to use for the session \&.hmacKey Key to use for HMAC calculations (NULL-terminated string) \&.pin PIN to use for PIN-based operations 
.br
\fIclient\fP The \fCKineticClient\fP pointer returned from \fBKineticClient_Init()\fP 
.br
\fIsession\fP Pointer to a KineticSession pointer that will be populated with the allocated/created session upon success\&.
.RE
.PP
\fBReturns:\fP
.RS 4
Returns the resulting \fCKineticStatus\fP, and \fCsession\fP will be populated with a pointer to the session instance upon success\&. The client should call \fBKineticClient_DestroySession()\fP in order to shutdown a connection and cleanup resources when done using a \fCKineticSession\fP\&. 
.RE
.PP

.PP
Definition at line 66 of file kinetic_client\&.c\&.
.PP
References ByteArray::data, KineticSessionConfig::hmacKey, KineticSessionConfig::host, KINETIC_STATUS_CONNECTION_ERROR, KINETIC_STATUS_HMAC_REQUIRED, KINETIC_STATUS_HOST_EMPTY, KINETIC_STATUS_MEMORY_ERROR, KINETIC_STATUS_SESSION_EMPTY, KINETIC_STATUS_SESSION_INVALID, KINETIC_STATUS_SUCCESS, KineticAllocator_FreeSession(), KineticAllocator_NewSession(), KineticSession_Connect(), KineticSession_Create(), KineticSession_Destroy(), ByteArray::len, LOG0, LOGF0, and KineticSessionConfig::port\&.
.SS "\fBKineticStatus\fP KineticClient_DestroySession (KineticSession *constsession)"

.PP
Closes the connection to a host\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsession\fP The connected \fCKineticSession\fP to close\&. The session instance will be freed by this call after closing the connection, so the pointer should not longer be used\&.
.RE
.PP
\fBReturns:\fP
.RS 4
Returns the resulting KineticStatus\&. 
.RE
.PP

.PP
Definition at line 118 of file kinetic_client\&.c\&.
.PP
References KINETIC_STATUS_CONNECTION_ERROR, KINETIC_STATUS_SESSION_INVALID, KINETIC_STATUS_SUCCESS, KineticSession_Destroy(), KineticSession_Disconnect(), and LOG0\&.
.SS "\fBKineticStatus\fP KineticClient_NoOp (KineticSession const *constsession)"

.PP
Executes a NOOP command to test whether the Kinetic Device is operational\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsession\fP The connected KineticSession to use for the operation\&.
.RE
.PP
\fBReturns:\fP
.RS 4
Returns the resulting KineticStatus\&. 
.RE
.PP

.PP
Definition at line 137 of file kinetic_client\&.c\&.
.PP
References KINETIC_ASSERT, KINETIC_STATUS_MEMORY_ERROR, KineticAllocator_NewOperation(), KineticController_ExecuteOperation(), and KineticOperation_BuildNoop()\&.
.SS "\fBKineticStatus\fP KineticClient_Put (KineticSession const *constsession, \fBKineticEntry\fP *constentry, \fBKineticCompletionClosure\fP *closure)"

.PP
Executes a PUT command to store/update an entry on the Kinetic Device\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsession\fP The connected KineticSession to use for the operation\&. 
.br
\fIentry\fP Key/value entry for object to store\&. 'value' must specify the data to be stored\&. If a closure is provided this pointer must remain valid until the closure callback is called\&.
.br
\fIclosure\fP Optional closure\&. If specified, operation will be executed in asynchronous mode, and closure callback will be called upon completion in another thread\&.
.RE
.PP
\fBReturns:\fP
.RS 4
Returns the resulting KineticStatus\&. 
.RE
.PP

.PP
Definition at line 149 of file kinetic_client\&.c\&.
.PP
References ByteBuffer::array, ByteArray::data, KINETIC_ASSERT, KINETIC_STATUS_MEMORY_ERROR, KINETIC_STATUS_SUCCESS, KineticAllocator_FreeOperation(), KineticAllocator_NewOperation(), KineticController_ExecuteOperation(), KineticOperation_BuildPut(), ByteArray::len, and KineticEntry::value\&.
.SS "\fBKineticStatus\fP KineticClient_Flush (KineticSession const *constsession, \fBKineticCompletionClosure\fP *closure)"

.PP
Executes a FLUSHALLDATA command to flush pending PUTs or DELETEs\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsession\fP The connected KineticSession to use for the operation\&. 
.br
\fIclosure\fP Optional closure\&. If specified, operation will be executed in asynchronous mode, and closure callback will be called upon completion in another thread\&.
.RE
.PP
\fBReturns:\fP
.RS 4
Returns the resulting KineticStatus\&. 
.RE
.PP

.PP
Definition at line 181 of file kinetic_client\&.c\&.
.PP
References KINETIC_ASSERT, KINETIC_STATUS_MEMORY_ERROR, KineticAllocator_NewOperation(), KineticController_ExecuteOperation(), and KineticOperation_BuildFlush()\&.
.SS "\fBKineticStatus\fP KineticClient_Get (KineticSession const *constsession, \fBKineticEntry\fP *constentry, \fBKineticCompletionClosure\fP *closure)"

.PP
Executes a GET command to retrieve an entry from the Kinetic Device\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsession\fP The connected KineticSession to use for the operation\&. 
.br
\fIentry\fP Key/value entry for object to retrieve\&. 'value' will be populated unless 'metadataOnly' is set to 'true'\&. If a closure is provided this pointer must remain valid until the closure callback is called\&. 
.br
\fIclosure\fP Optional closure\&. If specified, operation will be executed in asynchronous mode, and closure callback will be called upon completion in another thread\&.
.RE
.PP
\fBReturns:\fP
.RS 4
Returns the resulting KineticStatus\&. 
.RE
.PP

.PP
Definition at line 252 of file kinetic_client\&.c\&.
.PP
References CMD_GET, and handle_get_command()\&.
.SS "\fBKineticStatus\fP KineticClient_GetPrevious (KineticSession const *constsession, \fBKineticEntry\fP *constentry, \fBKineticCompletionClosure\fP *closure)"

.PP
Executes a GETPREVIOUS command to retrieve the next entry from the Kinetic Device\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsession\fP The connected KineticSession to use for the operation\&. 
.br
\fIentry\fP Key/value entry for object to retrieve\&. 'value' will be populated unless 'metadataOnly' is set to 'true'\&. The key and value fields will be populated with the previous key and its corresponding value, according to lexicographical byte order\&. If a closure is provided this pointer must remain valid until the closure callback is called\&.
.br
\fIclosure\fP Optional closure\&. If specified, operation will be executed in asynchronous mode, and closure callback will be called upon completion in another thread\&.
.RE
.PP
\fBReturns:\fP
.RS 4
Returns the resulting KineticStatus\&. 
.RE
.PP

.PP
Definition at line 259 of file kinetic_client\&.c\&.
.PP
References CMD_GET_PREVIOUS, and handle_get_command()\&.
.SS "\fBKineticStatus\fP KineticClient_GetNext (KineticSession const *constsession, \fBKineticEntry\fP *constentry, \fBKineticCompletionClosure\fP *closure)"

.PP
Executes a GETNEXT command to retrieve the next entry from the Kinetic Device\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsession\fP The connected KineticSession to use for the operation\&. 
.br
\fIentry\fP Key/value entry for object to retrieve\&. 'value' will be populated unless 'metadataOnly' is set to 'true'\&. The key and value fields will be populated with the next key and its corresponding value, according to lexicographical byte order\&. If a closure is provided this pointer must remain valid until the closure callback is called\&.
.br
\fIclosure\fP Optional closure\&. If specified, operation will be executed in asynchronous mode, and closure callback will be called upon completion in another thread\&.
.RE
.PP
\fBReturns:\fP
.RS 4
Returns the resulting KineticStatus\&. 
.RE
.PP

.PP
Definition at line 266 of file kinetic_client\&.c\&.
.PP
References CMD_GET_NEXT, and handle_get_command()\&.
.SS "\fBKineticStatus\fP KineticClient_Delete (KineticSession const *constsession, \fBKineticEntry\fP *constentry, \fBKineticCompletionClosure\fP *closure)"

.PP
Executes a DELETE command to delete an entry from the Kinetic Device\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsession\fP The connected KineticSession to use for the operation\&. 
.br
\fIentry\fP Key/value entry for object to delete\&. 'value' is not used for this operation\&. 
.br
\fIclosure\fP Optional closure\&. If specified, operation will be executed in asynchronous mode, and closure callback will be called upon completion in another thread\&.
.RE
.PP
\fBReturns:\fP
.RS 4
Returns the resulting KineticStatus\&. 
.RE
.PP

.PP
Definition at line 273 of file kinetic_client\&.c\&.
.PP
References KINETIC_ASSERT, KINETIC_STATUS_MEMORY_ERROR, KineticAllocator_NewOperation(), KineticController_ExecuteOperation(), and KineticOperation_BuildDelete()\&.
.SS "\fBKineticStatus\fP KineticClient_GetKeyRange (KineticSession const *constsession, \fBKineticKeyRange\fP *range, \fBByteBufferArray\fP *keys, \fBKineticCompletionClosure\fP *closure)"

.PP
Executes a GETKEYRANGE command to retrieve a set of keys in the range specified range from the Kinetic Device\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsession\fP The connected KineticSession to use for the operation 
.br
\fIrange\fP \fBKineticKeyRange\fP specifying keys to return 
.br
\fIkeys\fP \fBByteBufferArray\fP to store the retrieved keys\&. If a closure is provided, this must point to valid memory until the closure callback is called\&. 
.br
\fIclosure\fP Optional closure\&. If specified, operation will be executed in asynchronous mode, and closure callback will be called upon completion in another thread\&.
.RE
.PP
\fBReturns:\fP
.RS 4
Returns 0 upon success, -1 or the Kinetic status code upon failure 
.RE
.PP

.PP
Definition at line 291 of file kinetic_client\&.c\&.
.PP
References ByteBufferArray::buffers, ByteBufferArray::count, KINETIC_ASSERT, KINETIC_STATUS_MEMORY_ERROR, KineticAllocator_NewOperation(), KineticController_ExecuteOperation(), and KineticOperation_BuildGetKeyRange()\&.
.SS "\fBKineticStatus\fP KineticClient_P2POperation (KineticSession const *constsession, KineticP2P_Operation *constp2pOp, \fBKineticCompletionClosure\fP *closure)"

.PP
Executes a PEER2PEERPUSH operation allows a client to instruct a Kinetic Device to copy a set of keys (and associated value and metadata) to another Kinetic Device\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsession\fP The connected KineticSession to use for the operation 
.br
\fIp2pOp\fP KineticP2P_Operation pointer\&. This pointer needs to remain valid during the duration of the operation\&. The results of P2P operation(s) will be stored in the resultStatus field of this structure\&. 
.br
\fIclosure\fP Optional closure\&. If specified, operation will be executed in asynchronous mode, and closure callback will be called upon completion in another thread\&.
.RE
.PP
\fBReturns:\fP
.RS 4
Returns 0 upon success, -1 or the Kinetic status code upon failure\&. Note that P2P operations can be nested\&. This status code pertains to the initial top-level P2P operation\&. You'll need to check the resultStatus in the p2pOp structure to check the status of the individual P2P operations\&. 
.RE
.PP

.PP
Definition at line 313 of file kinetic_client\&.c\&.
.PP
References KINETIC_ASSERT, KINETIC_STATUS_MEMORY_ERROR, KINETIC_STATUS_SUCCESS, KineticAllocator_NewOperation(), KineticController_ExecuteOperation(), and KineticOperation_BuildP2POperation()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
