.TH "kinetic_exchange.c" 3 "Fri Aug 8 2014" "Version v0.4.2" "protobuf-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kinetic_exchange.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'kinetic_exchange\&.h'\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBKineticExchange_Init\fP (\fBKineticExchange\fP *const exchange, int64_t identity, const char *key, size_t keyLength, \fBKineticConnection\fP *const connection)"
.br
.ti -1c
.RI "void \fBKineticExchange_ConfigureConnectionID\fP (\fBKineticExchange\fP *const exchange)"
.br
.ti -1c
.RI "void \fBKineticExchange_SetClusterVersion\fP (\fBKineticExchange\fP *const exchange, int64_t clusterVersion)"
.br
.ti -1c
.RI "void \fBKineticExchange_IncrementSequence\fP (\fBKineticExchange\fP *const exchange)"
.br
.ti -1c
.RI "void \fBKineticExchange_ConfigureHeader\fP (const \fBKineticExchange\fP *const exchange, KineticProto_Header *const header)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void KineticExchange_Init (\fBKineticExchange\fP *constexchange, int64_tidentity, const char *key, size_tkeyLength, \fBKineticConnection\fP *constconnection)"

.PP
Definition at line 25 of file kinetic_exchange\&.c\&.
.PP
References KINETIC_EXCHANGE_INIT\&.
.SS "void KineticExchange_ConfigureConnectionID (\fBKineticExchange\fP *constexchange)"

.PP
Definition at line 35 of file kinetic_exchange\&.c\&.
.PP
References KineticExchange::connectionID\&.
.SS "void KineticExchange_SetClusterVersion (\fBKineticExchange\fP *constexchange, int64_tclusterVersion)"

.PP
Definition at line 43 of file kinetic_exchange\&.c\&.
.PP
References KineticExchange::clusterVersion, and KineticExchange::has_clusterVersion\&.
.SS "void KineticExchange_IncrementSequence (\fBKineticExchange\fP *constexchange)"

.PP
Definition at line 51 of file kinetic_exchange\&.c\&.
.PP
References KineticExchange::sequence\&.
.SS "void KineticExchange_ConfigureHeader (const \fBKineticExchange\fP *constexchange, KineticProto_Header *constheader)"

.PP
Definition at line 57 of file kinetic_exchange\&.c\&.
.PP
References KineticExchange::clusterVersion, KineticExchange::connectionID, KineticExchange::has_clusterVersion, KineticExchange::identity, and KineticExchange::sequence\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for protobuf-c from the source code\&.
