.TH "KineticMessage" 3 "Tue Nov 4 2014" "Version v0.8.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticMessage \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_types_internal\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "KineticProto_Message \fBmessage\fP"
.br
.ti -1c
.RI "KineticProto_Message_HMACauth \fBhmacAuth\fP"
.br
.ti -1c
.RI "KineticProto_Message_PINauth \fBpinAuth\fP"
.br
.ti -1c
.RI "uint8_t \fBhmacData\fP [\fBKINETIC_HMAC_MAX_LEN\fP]"
.br
.ti -1c
.RI "bool \fBhas_command\fP"
.br
.ti -1c
.RI "KineticProto_Command \fBcommand\fP"
.br
.ti -1c
.RI "KineticProto_Command_Header \fBheader\fP"
.br
.ti -1c
.RI "KineticProto_Command_Body \fBbody\fP"
.br
.ti -1c
.RI "KineticProto_Command_Status \fBstatus\fP"
.br
.ti -1c
.RI "KineticProto_Command_Security \fBsecurity\fP"
.br
.ti -1c
.RI "KineticProto_Command_Security_ACL \fBacl\fP"
.br
.ti -1c
.RI "KineticProto_Command_KeyValue \fBkeyValue\fP"
.br
.ti -1c
.RI "KineticProto_Command_Range \fBkeyRange\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 114 of file kinetic_types_internal\&.h\&.
.SH "Field Documentation"
.PP 
.SS "KineticProto_Message KineticMessage::message"

.PP
Definition at line 116 of file kinetic_types_internal\&.h\&.
.SS "KineticProto_Message_HMACauth KineticMessage::hmacAuth"

.PP
Definition at line 117 of file kinetic_types_internal\&.h\&.
.SS "KineticProto_Message_PINauth KineticMessage::pinAuth"

.PP
Definition at line 118 of file kinetic_types_internal\&.h\&.
.SS "uint8_t KineticMessage::hmacData[\fBKINETIC_HMAC_MAX_LEN\fP]"

.PP
Definition at line 119 of file kinetic_types_internal\&.h\&.
.SS "bool KineticMessage::has_command"

.PP
Definition at line 121 of file kinetic_types_internal\&.h\&.
.SS "KineticProto_Command KineticMessage::command"

.PP
Definition at line 122 of file kinetic_types_internal\&.h\&.
.SS "KineticProto_Command_Header KineticMessage::header"

.PP
Definition at line 123 of file kinetic_types_internal\&.h\&.
.SS "KineticProto_Command_Body KineticMessage::body"

.PP
Definition at line 124 of file kinetic_types_internal\&.h\&.
.SS "KineticProto_Command_Status KineticMessage::status"

.PP
Definition at line 125 of file kinetic_types_internal\&.h\&.
.SS "KineticProto_Command_Security KineticMessage::security"

.PP
Definition at line 126 of file kinetic_types_internal\&.h\&.
.SS "KineticProto_Command_Security_ACL KineticMessage::acl"

.PP
Definition at line 127 of file kinetic_types_internal\&.h\&.
.SS "KineticProto_Command_KeyValue KineticMessage::keyValue"

.PP
Definition at line 128 of file kinetic_types_internal\&.h\&.
.SS "KineticProto_Command_Range KineticMessage::keyRange"

.PP
Definition at line 129 of file kinetic_types_internal\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
