.TH "KineticOperation" 3 "Fri Aug 8 2014" "Version v0.5.0" "protobuf-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticOperation \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_operation\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBKineticExchange\fP * \fBexchange\fP"
.br
.ti -1c
.RI "\fBKineticPDU\fP * \fBrequest\fP"
.br
.ti -1c
.RI "\fBKineticPDU\fP * \fBresponse\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 28 of file kinetic_operation\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBKineticExchange\fP* KineticOperation::exchange"

.PP
Definition at line 30 of file kinetic_operation\&.h\&.
.SS "\fBKineticPDU\fP* KineticOperation::request"

.PP
Definition at line 31 of file kinetic_operation\&.h\&.
.SS "\fBKineticPDU\fP* KineticOperation::response"

.PP
Definition at line 32 of file kinetic_operation\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for protobuf-c from the source code\&.
