.TH "kinetic_socket.c" 3 "Wed Feb 11 2015" "Version v0.11.1" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kinetic_socket.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'kinetic_socket\&.h'\fP
.br
\fC#include 'kinetic_logger\&.h'\fP
.br
\fC#include 'kinetic_types_internal\&.h'\fP
.br
\fC#include 'kinetic_proto\&.h'\fP
.br
\fC#include 'protobuf-c/protobuf-c\&.h'\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <fcntl\&.h>\fP
.br
\fC#include <sys/socket\&.h>\fP
.br
\fC#include <netinet/in\&.h>\fP
.br
\fC#include <netinet/tcp\&.h>\fP
.br
\fC#include <sys/select\&.h>\fP
.br
\fC#include <sys/ioctl\&.h>\fP
.br
\fC#include <arpa/inet\&.h>\fP
.br
\fC#include <netdb\&.h>\fP
.br
\fC#include <signal\&.h>\fP
.br
\fC#include <poll\&.h>\fP
.br
\fC#include 'socket99\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBKineticSocket_Connect\fP (const char *host, int port)"
.br
.ti -1c
.RI "void \fBKineticSocket_Close\fP (int socket)"
.br
.ti -1c
.RI "void \fBKineticSocket_EnableTCPNoDelay\fP (int socket)"
.br
.ti -1c
.RI "void \fBKineticSocket_BeginPacket\fP (int socket)"
.br
.ti -1c
.RI "void \fBKineticSocket_FinishPacket\fP (int socket)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int KineticSocket_Connect (const char *host, intport)"

.PP
Definition at line 47 of file kinetic_socket\&.c\&.
.PP
References KINETIC_OBJ_SIZE, KINETIC_SOCKET_DESCRIPTOR_INVALID, KineticSocket_EnableTCPNoDelay(), LOG0, LOGF0, and LOGF1\&.
.SS "void KineticSocket_Close (intsocket)"

.PP
Definition at line 138 of file kinetic_socket\&.c\&.
.PP
References LOG1, LOG2, and LOGF0\&.
.SS "void KineticSocket_EnableTCPNoDelay (intsocket)"

.PP
Definition at line 156 of file kinetic_socket\&.c\&.
.SS "void KineticSocket_BeginPacket (intsocket)"

.PP
Definition at line 162 of file kinetic_socket\&.c\&.
.SS "void KineticSocket_FinishPacket (intsocket)"

.PP
Definition at line 172 of file kinetic_socket\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
