.TH "kinetic_socket.h" 3 "Wed Oct 15 2014" "Version v0.7.0" "protobuf-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kinetic_socket.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'kinetic_types_internal\&.h'\fP
.br
\fC#include 'kinetic_message\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBKineticSocket_Connect\fP (const char *host, int port, bool nonBlocking)"
.br
.ti -1c
.RI "void \fBKineticSocket_Close\fP (int socket)"
.br
.ti -1c
.RI "\fBKineticStatus\fP \fBKineticSocket_Read\fP (int socket, \fBByteBuffer\fP *dest, size_t len)"
.br
.ti -1c
.RI "\fBKineticStatus\fP \fBKineticSocket_ReadProtobuf\fP (int socket, KineticPDU *pdu)"
.br
.ti -1c
.RI "\fBKineticStatus\fP \fBKineticSocket_Write\fP (int socket, \fBByteBuffer\fP *src)"
.br
.ti -1c
.RI "\fBKineticStatus\fP \fBKineticSocket_WriteProtobuf\fP (int socket, KineticPDU *pdu)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int KineticSocket_Connect (const char *host, intport, boolnonBlocking)"

.PP
Definition at line 49 of file kinetic_socket\&.c\&.
.PP
References KINETIC_SOCKET_DESCRIPTOR_INVALID, LOG, LOGF, and PDU_VALUE_MAX_LEN\&.
.SS "void KineticSocket_Close (intsocket)"

.PP
Definition at line 138 of file kinetic_socket\&.c\&.
.PP
References LOG, and LOGF\&.
.SS "\fBKineticStatus\fP KineticSocket_Read (intsocket, \fBByteBuffer\fP *dest, size_tlen)"

.PP
Definition at line 156 of file kinetic_socket\&.c\&.
.PP
References ByteBuffer::array, ByteBuffer::bytesUsed, ByteArray::data, KINETIC_STATUS_BUFFER_OVERRUN, KINETIC_STATUS_INVALID, KINETIC_STATUS_MEMORY_ERROR, KINETIC_STATUS_SOCKET_ERROR, KINETIC_STATUS_SOCKET_TIMEOUT, KINETIC_STATUS_SUCCESS, ByteArray::len, LOG, and LOGF\&.
.SS "\fBKineticStatus\fP KineticSocket_ReadProtobuf (intsocket, KineticPDU *pdu)"

.PP
Definition at line 313 of file kinetic_socket\&.c\&.
.PP
References ByteBuffer::array, ByteBuffer_Create(), ByteBuffer::bytesUsed, ByteArray::data, KINETIC_STATUS_DATA_ERROR, KINETIC_STATUS_MEMORY_ERROR, KINETIC_STATUS_SUCCESS, KineticProto__unpack(), KineticSocket_Read(), LOG, and LOGF\&.
.SS "\fBKineticStatus\fP KineticSocket_Write (intsocket, \fBByteBuffer\fP *src)"

.PP
Definition at line 355 of file kinetic_socket\&.c\&.
.PP
References ByteBuffer::array, ByteBuffer::bytesUsed, ByteArray::data, KINETIC_STATUS_SOCKET_ERROR, KINETIC_STATUS_SUCCESS, LOG, and LOGF\&.
.SS "\fBKineticStatus\fP KineticSocket_WriteProtobuf (intsocket, KineticPDU *pdu)"

.PP
Definition at line 389 of file kinetic_socket\&.c\&.
.PP
References ByteBuffer_Create(), ByteBuffer::bytesUsed, KINETIC_STATUS_MEMORY_ERROR, KineticProto__pack(), KineticSocket_Write(), LOG, and LOGF\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for protobuf-c from the source code\&.
