.TH "kinetic_allocator.h" 3 "Tue Jan 27 2015" "Version v0.11.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kinetic_allocator.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'kinetic_types_internal\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBKineticAllocator_InitLists\fP (KineticConnection *connection)"
.br
.ti -1c
.RI "KineticConnection * \fBKineticAllocator_NewConnection\fP (struct \fBbus\fP *b, \fBKineticSession\fP *const session)"
.br
.ti -1c
.RI "void \fBKineticAllocator_FreeConnection\fP (KineticConnection *connection)"
.br
.ti -1c
.RI "KineticPDU * \fBKineticAllocator_NewPDU\fP (KineticConnection *connection)"
.br
.ti -1c
.RI "void \fBKineticAllocator_FreePDU\fP (KineticPDU *pdu)"
.br
.ti -1c
.RI "KineticOperation * \fBKineticAllocator_NewOperation\fP (KineticConnection *connection)"
.br
.ti -1c
.RI "void \fBKineticAllocator_FreeOperation\fP (KineticOperation *operation)"
.br
.ti -1c
.RI "\fBKineticResponse\fP * \fBKineticAllocator_NewKineticResponse\fP (size_t const valueLength)"
.br
.ti -1c
.RI "void \fBKineticAllocator_FreeKineticResponse\fP (\fBKineticResponse\fP *response)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void KineticAllocator_InitLists (KineticConnection *connection)"

.SS "KineticConnection* KineticAllocator_NewConnection (struct \fBbus\fP *b, \fBKineticSession\fP *constsession)"

.PP
Definition at line 29 of file kinetic_allocator\&.c\&.
.PP
References KineticCalloc(), KineticResourceWaiter_Init(), and LOG0\&.
.SS "void KineticAllocator_FreeConnection (KineticConnection *connection)"

.PP
Definition at line 43 of file kinetic_allocator\&.c\&.
.PP
References KineticFree(), and KineticResourceWaiter_Destroy()\&.
.SS "KineticPDU* KineticAllocator_NewPDU (KineticConnection *connection)"

.SS "void KineticAllocator_FreePDU (KineticPDU *pdu)"

.SS "KineticOperation* KineticAllocator_NewOperation (KineticConnection *connection)"

.PP
Definition at line 73 of file kinetic_allocator\&.c\&.
.PP
References KineticCalloc(), KineticFree(), KineticOperation_Init(), KineticPDU_InitWithCommand(), LOG0, LOGF0, and LOGF3\&.
.SS "void KineticAllocator_FreeOperation (KineticOperation *operation)"

.PP
Definition at line 96 of file kinetic_allocator\&.c\&.
.PP
References KineticAllocator_FreeKineticResponse(), KineticFree(), and LOGF3\&.
.SS "\fBKineticResponse\fP* KineticAllocator_NewKineticResponse (size_t constvalueLength)"

.PP
Definition at line 50 of file kinetic_allocator\&.c\&.
.PP
References KineticCalloc(), and LOG0\&.
.SS "void KineticAllocator_FreeKineticResponse (\fBKineticResponse\fP *response)"

.PP
Definition at line 60 of file kinetic_allocator\&.c\&.
.PP
References KineticResponse::command, KineticFree(), and KineticResponse::proto\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
