.TH "kinetic_types.c" 3 "Thu Sep 11 2014" "Version v0.6.0" "protobuf-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kinetic_types.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'kinetic_types\&.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "const char * \fBKineticStatusDescriptor\fP []"
.br
.ti -1c
.RI "const int \fBKineticStatusDescriptorCount\fP = sizeof(\fBKineticStatusDescriptor\fP)/sizeof(char*)"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const char* KineticStatusDescriptor[]"
\fBInitial value:\fP
.PP
.nf
= {
    "SUCCESS",
    "DEVICE_BUSY",
    "CONNECTION_ERROR",
    "INVALID_REQUEST",
    "OPERATION_FAILED",
    "VERSION_FAILURE",
    "DATA_ERROR",
}
.fi
.PP
Definition at line 4 of file kinetic_types\&.c\&.
.SS "const int KineticStatusDescriptorCount = sizeof(\fBKineticStatusDescriptor\fP)/sizeof(char*)"

.PP
Definition at line 14 of file kinetic_types\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for protobuf-c from the source code\&.
