kinetic_admin_client.h
NAME
kinetic_admin_client.h -
SYNOPSIS
#include 'kinetic_types.h'
#include 'kinetic_client.h'
Functions
KineticClient * KineticAdminClient_Init (KineticClientConfig *config)
Initializes the Kinetic Admin API and configures logging.
void KineticAdminClient_Shutdown (KineticClient *const client)
Performs shutdown/cleanup of the kinetic-c client library.
KineticStatus KineticAdminClient_CreateSession (KineticSessionConfig *const config, KineticClient *const client, KineticSession **session)
Creates a session with the Kinetic Device per specified configuration.
KineticStatus KineticAdminClient_DestroySession (KineticSession *const session)
Closes the connection to a host.
KineticStatus KineticAdminClient_SetErasePin (KineticSession *const session, ByteArray old_pin, ByteArray new_pin)
Sets the erase PIN of the Kinetic Device.
KineticStatus KineticAdminClient_SecureErase (KineticSession *const session, ByteArray pin)
Executes a SecureErase command to erase all data from the Kinetic device.
KineticStatus KineticAdminClient_InstantErase (KineticSession *const session, ByteArray pin)
Executes an InstantErase operation to erase all data from the Kinetic device.
KineticStatus KineticAdminClient_SetLockPin (KineticSession *const session, ByteArray old_pin, ByteArray new_pin)
Sets the lock PIN of the Kinetic Device.
KineticStatus KineticAdminClient_LockDevice (KineticSession *const session, ByteArray pin)
Executes a LOCK operation to lock the Kinetic device.
KineticStatus KineticAdminClient_UnlockDevice (KineticSession *const session, ByteArray pin)
Executes an UNLOCK operation to unlock the Kinetic device.
KineticStatus KineticAdminClient_GetLog (KineticSession *const session, KineticLogInfo_Type type, KineticLogInfo **info, KineticCompletionClosure *closure)
Executes a GETLOG operation to retrieve specific configuration and/or operational data from the Kinetic Device.
KineticStatus KineticAdminClient_GetDeviceSpecificLog (KineticSession *const session, ByteArray name, KineticLogInfo **info, KineticCompletionClosure *closure)
Executes a GETLOG operation to retrieve device-specific log info from the Kinetic Device via name/key.
void KineticAdminClient_FreeLogInfo (KineticSession *const session, KineticLogInfo *info)
Free the KineticLogInfo result from KineticClient_GetLog.
KineticStatus KineticAdminClient_SetClusterVersion (KineticSession *const session, int64_t version)
Updates the cluster version of the Kinetic Device.
KineticStatus KineticAdminClient_SetACL (KineticSession *const session, const char *ACLPath)
Executes a SECURITY operation, setting one or more ACLs.
KineticStatus KineticAdminClient_UpdateFirmware (KineticSession *const session, char const *const fw_path)
Executes a Firmware Download operation to update the firmware on the Kinetic device.
Function Documentation
KineticClient* KineticAdminClient_Init (KineticClientConfig *config)
Initializes the Kinetic Admin API and configures logging.
Parameters:
config A configuration struct.
Returns:
Returns a pointer to a KineticClient. You need to pass this pointer to KineticClient_CreateSession() to create new connections. Once you are finished will the KineticClient, and there are no active connections. The pointer should be released with KineticClient_Shutdown()
Definition at line 36 of file kinetic_admin_client.c.
References KineticClient_Init().
void KineticAdminClient_Shutdown (KineticClient *constclient)
Performs shutdown/cleanup of the kinetic-c client library.
Definition at line 41 of file kinetic_admin_client.c.
References KineticClient_Shutdown().
KineticStatus KineticAdminClient_CreateSession (KineticSessionConfig *constconfig, KineticClient *constclient, KineticSession **session)
Creates a session with the Kinetic Device per specified configuration.
Parameters:
config KineticSessionConfig structure which must be configured by the client prior to creating the device connection. .host Host name or IP address to connect to .port Port to establish socket connection on .clusterVersion Cluster version to use for the session .identity Identity to use for the session .hmacKey Key to use for HMAC calculations (NULL-terminated string) .pin PIN to use for PIN-based operations
client The KineticClient pointer returned from KineticClient_Init()
session Pointer to a KineticSession pointer that will be populated with the allocated/created session upon success.
Returns:
Returns the resulting KineticStatus, and session will be populated with a pointer to the session instance upon success. The client should call KineticClient_DestroySession() in order to shutdown a connection and cleanup resources when done using a KineticSession.
Definition at line 46 of file kinetic_admin_client.c.
References KineticClient_CreateSession().
KineticStatus KineticAdminClient_DestroySession (KineticSession *constsession)
Closes the connection to a host.
Parameters:
session The connected KineticSession to close. The session instance will be freed by this call after closing the connection, so the pointer should not longer be used.
Returns:
Returns the resulting KineticStatus.
Definition at line 52 of file kinetic_admin_client.c.
References KineticClient_DestroySession().
KineticStatus KineticAdminClient_SetErasePin (KineticSession *constsession, ByteArrayold_pin, ByteArraynew_pin)
Sets the erase PIN of the Kinetic Device.
Parameters:
session The connected KineticSession to close. The session instance will be freed by this call after closing the connection, so the pointer should not longer be used.
old_pin Old erase PIN to change.
new_pin New erase PIN to change to.
Returns:
Returns the resulting KineticStatus.
Definition at line 58 of file kinetic_admin_client.c.
References ByteArray::data, KINETIC_STATUS_MEMORY_ERROR, KINETIC_STATUS_MISSING_PIN, KINETIC_STATUS_SUCCESS, KineticAllocator_NewOperation(), KineticAuth_EnsureSslEnabled(), KineticBuilder_BuildSetPin(), KineticController_ExecuteOperation(), and ByteArray::len.
KineticStatus KineticAdminClient_SecureErase (KineticSession *constsession, ByteArraypin)
Executes a SecureErase command to erase all data from the Kinetic device.
Parameters:
session The connected KineticSession to use for the operation.
pin PIN to send with operation, which must match the configured erase PIN.
Returns:
Returns the resulting KineticStatus.
Definition at line 78 of file kinetic_admin_client.c.
References ByteArray::data, KINETIC_ASSERT, KINETIC_STATUS_MEMORY_ERROR, KINETIC_STATUS_MISSING_PIN, KINETIC_STATUS_SUCCESS, KineticAllocator_NewOperation(), KineticAuth_EnsureSslEnabled(), KineticBuilder_BuildErase(), KineticController_ExecuteOperation(), and ByteArray::len.
KineticStatus KineticAdminClient_InstantErase (KineticSession *constsession, ByteArraypin)
Executes an InstantErase operation to erase all data from the Kinetic device.
Parameters:
session The connected KineticSession to use for the operation.
pin PIN to send with operation, which must match the configured erase PIN.
Returns:
Returns the resulting KineticStatus.
Definition at line 99 of file kinetic_admin_client.c.
References ByteArray::data, KINETIC_ASSERT, KINETIC_STATUS_MEMORY_ERROR, KINETIC_STATUS_MISSING_PIN, KINETIC_STATUS_SUCCESS, KineticAllocator_NewOperation(), KineticAuth_EnsureSslEnabled(), KineticBuilder_BuildErase(), KineticController_ExecuteOperation(), and ByteArray::len.
KineticStatus KineticAdminClient_SetLockPin (KineticSession *constsession, ByteArrayold_pin, ByteArraynew_pin)
Sets the lock PIN of the Kinetic Device.
Parameters:
session The connected KineticSession to close. The session instance will be freed by this call after closing the connection, so the pointer should not longer be used.
old_pin Old erase PIN to change.
new_pin New erase PIN to change to.
Returns:
Returns the resulting KineticStatus.
Definition at line 121 of file kinetic_admin_client.c.
References ByteArray::data, KINETIC_STATUS_MEMORY_ERROR, KINETIC_STATUS_MISSING_PIN, KINETIC_STATUS_SUCCESS, KineticAllocator_NewOperation(), KineticAuth_EnsureSslEnabled(), KineticBuilder_BuildSetPin(), KineticController_ExecuteOperation(), and ByteArray::len.
KineticStatus KineticAdminClient_LockDevice (KineticSession *constsession, ByteArraypin)
Executes a LOCK operation to lock the Kinetic device.
Parameters:
session The connected KineticSession to use for the operation.
pin PIN to send with operation, which must match the configured lock PIN.
Returns:
Returns the resulting KineticStatus.
Definition at line 141 of file kinetic_admin_client.c.
References ByteArray::data, KINETIC_ASSERT, KINETIC_STATUS_MEMORY_ERROR, KINETIC_STATUS_MISSING_PIN, KINETIC_STATUS_SUCCESS, KineticAllocator_NewOperation(), KineticAuth_EnsureSslEnabled(), KineticBuilder_BuildLockUnlock(), KineticController_ExecuteOperation(), and ByteArray::len.
KineticStatus KineticAdminClient_UnlockDevice (KineticSession *constsession, ByteArraypin)
Executes an UNLOCK operation to unlock the Kinetic device.
Parameters:
session The connected KineticSession to use for the operation.
pin PIN to send with operation, which must match the configured lock PIN.
Returns:
Returns the resulting KineticStatus.
Definition at line 162 of file kinetic_admin_client.c.
References ByteArray::data, KINETIC_ASSERT, KINETIC_STATUS_MEMORY_ERROR, KINETIC_STATUS_MISSING_PIN, KINETIC_STATUS_SUCCESS, KineticAllocator_NewOperation(), KineticAuth_EnsureSslEnabled(), KineticBuilder_BuildLockUnlock(), KineticController_ExecuteOperation(), and ByteArray::len.
KineticStatus KineticAdminClient_GetLog (KineticSession *constsession, KineticLogInfo_Typetype, KineticLogInfo **info, KineticCompletionClosure *closure)
Executes a GETLOG operation to retrieve specific configuration and/or operational data from the Kinetic Device.
Parameters:
session The connected KineticSession to use for the operation
type KineticLogDataType specifying data type to retrieve.
info KineticLogInfo pointer, which will be assigned to a dynamically allocated structure populated with the requested data, if successful. The client should call KineticAdminClient_FreeLogInfo() with this pointer in order to free all allocated memory.
closure Optional closure. If specified, operation will be executed in asynchronous mode, and closure callback will be called upon completion in another thread.
Returns:
Returns the resulting KineticStatus
Definition at line 183 of file kinetic_admin_client.c.
References BYTE_ARRAY_NONE, COM__SEAGATE__KINETIC__PROTO__COMMAND__GET_LOG__TYPE__INVALID_TYPE, KINETIC_ASSERT, KINETIC_STATUS_INVALID_LOG_TYPE, KINETIC_STATUS_MEMORY_ERROR, KineticAllocator_NewOperation(), KineticBuilder_BuildGetLog(), KineticController_ExecuteOperation(), and KineticLogInfo_Type_to_Com__Seagate__Kinetic__Proto__Command__GetLog__Type().
KineticStatus KineticAdminClient_GetDeviceSpecificLog (KineticSession *constsession, ByteArrayname, KineticLogInfo **info, KineticCompletionClosure *closure)
Executes a GETLOG operation to retrieve device-specific log info from the Kinetic Device via name/key.
Parameters:
session The connected KineticSession to use for the operation
name Device specific name to retrieve info for.
info KineticLogInfo pointer, which will be assigned to a dynamically allocated structure populated with the requested data, if successful. The client should call KineticAdminClient_FreeLogInfo() with this pointer in order to free all allocated memory.
closure Optional closure. If specified, operation will be executed in asynchronous mode, and closure callback will be called upon completion in another thread.
Returns:
Returns the resulting KineticStatus
Definition at line 207 of file kinetic_admin_client.c.
References COM__SEAGATE__KINETIC__PROTO__COMMAND__GET_LOG__TYPE__DEVICE, KINETIC_ASSERT, KINETIC_STATUS_MEMORY_ERROR, KineticAllocator_NewOperation(), KineticBuilder_BuildGetLog(), and KineticController_ExecuteOperation().
void KineticAdminClient_FreeLogInfo (KineticSession *constsession, KineticLogInfo *info)
Free the KineticLogInfo result from KineticClient_GetLog.
Parameters:
session The connected KineticSession to use for the operation
info The KineticLogInfo result to free.
KineticStatus KineticAdminClient_SetClusterVersion (KineticSession *constsession, int64_tversion)
Updates the cluster version of the Kinetic Device.
Parameters:
session The connected KineticSession to use for the operation.
version New cluster version.
Returns:
Returns the resulting KineticStatus.
Definition at line 236 of file kinetic_admin_client.c.
References KINETIC_ASSERT, KINETIC_STATUS_MEMORY_ERROR, KineticAllocator_NewOperation(), KineticBuilder_BuildSetClusterVersion(), and KineticController_ExecuteOperation().
KineticStatus KineticAdminClient_SetACL (KineticSession *constsession, const char *ACLPath)
Executes a SECURITY operation, setting one or more ACLs.
Parameters:
session The connected KineticSession to use for the operation
ACLPath Path to a JSON file containing one or more ACLs.
Returns:
Returns the resulting KineticStatus.
Definition at line 248 of file kinetic_admin_client.c.
References ACL_OK, KINETIC_ASSERT, KINETIC_STATUS_ACL_ERROR, KINETIC_STATUS_INVALID_REQUEST, KINETIC_STATUS_MEMORY_ERROR, KineticACL_LoadFromFile(), KineticAllocator_NewOperation(), KineticBuilder_BuildSetACL(), and KineticController_ExecuteOperation().
KineticStatus KineticAdminClient_UpdateFirmware (KineticSession *constsession, char const *constfw_path)
Executes a Firmware Download operation to update the firmware on the Kinetic device.
Parameters:
session The connected KineticSession to use for the operation.
fw_path Path to firmware update image file.
Returns:
Returns the resulting KineticStatus.
Definition at line 276 of file kinetic_admin_client.c.
References KINETIC_ASSERT, KINETIC_STATUS_MEMORY_ERROR, KINETIC_STATUS_SUCCESS, KineticAllocator_NewOperation(), KineticBuilder_BuildUpdateFirmware(), and KineticController_ExecuteOperation().
Author
Generated automatically by Doxygen for kinetic-c from the source code.