.TH "KineticExchange" 3 "Mon Jul 28 2014" "Version v0.3.3" "protobuf-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticExchange \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "bool \fBhas_clusterVersion\fP"
.br
.ti -1c
.RI "int64_t \fBclusterVersion\fP"
.br
.ti -1c
.RI "int64_t \fBidentity\fP"
.br
.ti -1c
.RI "bool \fBhas_key\fP"
.br
.ti -1c
.RI "size_t \fBkeyLength\fP"
.br
.ti -1c
.RI "uint8_t \fBkey\fP [128]"
.br
.ti -1c
.RI "int64_t \fBconnectionID\fP"
.br
.ti -1c
.RI "int64_t \fBsequence\fP"
.br
.ti -1c
.RI "\fBKineticConnection\fP * \fBconnection\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 28 of file kinetic_exchange\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for protobuf-c from the source code\&.
