.TH "KineticPDU" 3 "Mon Jul 28 2014" "Version v0.3.3" "protobuf-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticPDU \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBKineticPDUHeader\fP \fBheader\fP"
.br
.ti -1c
.RI "\fBKineticMessage\fP * \fBprotobuf\fP"
.br
.ti -1c
.RI "uint32_t \fBprotobufLength\fP"
.br
.ti -1c
.RI "uint8_t \fBprotobufScratch\fP [1024 *1024]"
.br
.ti -1c
.RI "uint8_t * \fBvalue\fP"
.br
.ti -1c
.RI "uint32_t \fBvalueLength\fP"
.br
.ti -1c
.RI "\fBKineticHMAC\fP \fBhmac\fP"
.br
.ti -1c
.RI "\fBKineticExchange\fP * \fBexchange\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 41 of file kinetic_pdu\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for protobuf-c from the source code\&.
