.TH "KineticSession" 3 "Tue Dec 9 2014" "Version v0.9.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticSession \- 
.PP
An instance of a session with a Kinetic device\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBKineticSessionConfig\fP \fBconfig\fP"
.br
.ti -1c
.RI "struct \fB_KineticConnection\fP * \fBconnection\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
An instance of a session with a Kinetic device\&. 
.PP
Definition at line 124 of file kinetic_types\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBKineticSessionConfig\fP KineticSession::config"

.PP
Definition at line 126 of file kinetic_types\&.h\&.
.SS "struct \fB_KineticConnection\fP* KineticSession::connection"

.PP
Definition at line 131 of file kinetic_types\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
