.TH "kinetic_nbo.c" 3 "Thu Sep 11 2014" "Version v0.6.0" "protobuf-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kinetic_nbo.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'kinetic_nbo\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "uint32_t \fBKineticNBO_FromHostU32\fP (uint32_t valueHost)"
.br
.ti -1c
.RI "uint32_t \fBKineticNBO_ToHostU32\fP (uint32_t valueNBO)"
.br
.ti -1c
.RI "uint64_t \fBKineticNBO_FromHostU64\fP (uint64_t valueHost)"
.br
.ti -1c
.RI "uint64_t \fBKineticNBO_ToHostU64\fP (uint64_t valueNBO)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "uint32_t KineticNBO_FromHostU32 (uint32_tvalueHost)"

.PP
Definition at line 33 of file kinetic_nbo\&.c\&.
.SS "uint32_t KineticNBO_ToHostU32 (uint32_tvalueNBO)"

.PP
Definition at line 39 of file kinetic_nbo\&.c\&.
.SS "uint64_t KineticNBO_FromHostU64 (uint64_tvalueHost)"

.PP
Definition at line 45 of file kinetic_nbo\&.c\&.
.SS "uint64_t KineticNBO_ToHostU64 (uint64_tvalueNBO)"

.PP
Definition at line 51 of file kinetic_nbo\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for protobuf-c from the source code\&.
