kinetic_logger.h
NAME
kinetic_logger.h -
SYNOPSIS
#include 'kinetic_types_internal.h'
#include 'kinetic_proto.h'
#include <stdarg.h>
Macros
#define KINETIC_LOGGER_DISABLED false
#define KINETIC_LOGGER_FLUSH_THREAD_ENABLED false
#define KINETIC_LOG_FILE 'kinetic.log'
#define BYTES_TO_CSTRING(_buf_start, _array, _array_start, _count)
#define LOG0(message) KineticLogger_Log(0, message)
#define LOG1(message) KineticLogger_Log(1, message)
#define LOG2(message) KineticLogger_Log(2, message)
#define LOG3(message) KineticLogger_Log(3, message)
#define LOGF0(message,...) KineticLogger_LogPrintf(0, message, __VA_ARGS__)
#define LOGF1(message,...) KineticLogger_LogPrintf(1, message, __VA_ARGS__)
#define LOGF2(message,...) KineticLogger_LogPrintf(2, message, __VA_ARGS__)
#define LOGF3(message,...) KineticLogger_LogPrintf(3, message, __VA_ARGS__)
#define LOG_LOCATION KineticLogger_LogLocation(__FILE__, __LINE__, __func__);
Functions
void KineticLogger_Init (const char *logFile, int log_level)
void KineticLogger_Close (void)
void KineticLogger_Log (int log_level, const char *message)
void KineticLogger_LogPrintf (int log_level, const char *format,...)
void KineticLogger_LogLocation (const char *filename, int line, char const *message)
void KineticLogger_LogHeader (int log_level, const KineticPDUHeader *header)
void KineticLogger_LogProtobuf (int log_level, const KineticProto_Message *msg)
void KineticLogger_LogStatus (int log_level, KineticProto_Command_Status *status)
void KineticLogger_LogByteArray (int log_level, const char *title, ByteArray bytes)
void KineticLogger_LogByteBuffer (int log_level, const char *title, ByteBuffer buffer)
int KineticLogger_ByteArraySliceToCString (char *p_buf, const ByteArray bytes, const int start, const int count)
Macro Definition Documentation
#define KINETIC_LOGGER_DISABLED false
Definition at line 28 of file kinetic_logger.h.
#define KINETIC_LOGGER_FLUSH_THREAD_ENABLED false
Definition at line 29 of file kinetic_logger.h.
#define KINETIC_LOG_FILE 'kinetic.log'
Definition at line 30 of file kinetic_logger.h.
#define BYTES_TO_CSTRING(_buf_start, _array, _array_start, _count)
Value:
{ \
    ByteArray __array = {.data = _array.data, .len = (_array).len}; \
    KineticLogger_ByteArraySliceToCString((char*)(_buf_start), (__array), (_array_start), (_count)); \
}
Definition at line 44 of file kinetic_logger.h.
#define LOG0(message) KineticLogger_Log(0, message)
Definition at line 52 of file kinetic_logger.h.
#define LOG1(message) KineticLogger_Log(1, message)
Definition at line 53 of file kinetic_logger.h.
#define LOG2(message) KineticLogger_Log(2, message)
Definition at line 54 of file kinetic_logger.h.
#define LOG3(message) KineticLogger_Log(3, message)
Definition at line 55 of file kinetic_logger.h.
#define LOGF0(message, ...) KineticLogger_LogPrintf(0, message, __VA_ARGS__)
Definition at line 56 of file kinetic_logger.h.
#define LOGF1(message, ...) KineticLogger_LogPrintf(1, message, __VA_ARGS__)
Definition at line 57 of file kinetic_logger.h.
#define LOGF2(message, ...) KineticLogger_LogPrintf(2, message, __VA_ARGS__)
Definition at line 58 of file kinetic_logger.h.
#define LOGF3(message, ...) KineticLogger_LogPrintf(3, message, __VA_ARGS__)
Definition at line 59 of file kinetic_logger.h.
#define LOG_LOCATION KineticLogger_LogLocation(__FILE__, __LINE__, __func__);
Definition at line 60 of file kinetic_logger.h.
Function Documentation
void KineticLogger_Init (const char *logFile, intlog_level)
Definition at line 71 of file kinetic_logger.c.
void KineticLogger_Close (void)
Definition at line 101 of file kinetic_logger.c.
References Kinetic_GetErrnoDescription(), and LOGF0.
void KineticLogger_Log (intlog_level, const char *message)
Definition at line 121 of file kinetic_logger.c.
References KINETIC_LOGGER_BUFFER_STR_MAX_LEN.
void KineticLogger_LogPrintf (intlog_level, const char *format, ...)
Definition at line 133 of file kinetic_logger.c.
References KINETIC_LOGGER_BUFFER_STR_MAX_LEN.
void KineticLogger_LogLocation (const char *filename, intline, char const *message)
Definition at line 151 of file kinetic_logger.c.
References KineticLogger_LogPrintf().
void KineticLogger_LogHeader (intlog_level, const KineticPDUHeader *header)
Definition at line 167 of file kinetic_logger.c.
References KineticLogger_Log(), and KineticLogger_LogPrintf().
void KineticLogger_LogProtobuf (intlog_level, const KineticProto_Message *msg)
Definition at line 410 of file kinetic_logger.c.
References KineticLogger_Log(), and LOG_PROTO_INIT.
void KineticLogger_LogStatus (intlog_level, KineticProto_Command_Status *status)
Definition at line 422 of file kinetic_logger.c.
References KINETIC_PROTO_COMMAND_STATUS_STATUS_CODE_INVALID_STATUS_CODE, KINETIC_PROTO_COMMAND_STATUS_STATUS_CODE_SUCCESS, and KineticLogger_LogPrintf().
void KineticLogger_LogByteArray (intlog_level, const char *title, ByteArraybytes)
Definition at line 479 of file kinetic_logger.c.
References ByteArray::data, KineticLogger_LogPrintf(), and ByteArray::len.
void KineticLogger_LogByteBuffer (intlog_level, const char *title, ByteBufferbuffer)
Definition at line 523 of file kinetic_logger.c.
References ByteBuffer::array, ByteBuffer::bytesUsed, ByteArray::data, and KineticLogger_LogByteArray().
int KineticLogger_ByteArraySliceToCString (char *p_buf, const ByteArraybytes, const intstart, const intcount)
Definition at line 218 of file kinetic_logger.c.
References ByteArray::data.
Author
Generated automatically by Doxygen for kinetic-c from the source code.