.TH "KineticResponse" 3 "Fri Mar 13 2015" "Version v0.12.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticResponse \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_types_internal\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBKineticPDUHeader\fP \fBheader\fP"
.br
.ti -1c
.RI "Com__Seagate__Kinetic__Proto__Message * \fBproto\fP"
.br
.ti -1c
.RI "Com__Seagate__Kinetic__Proto__Command * \fBcommand\fP"
.br
.ti -1c
.RI "uint8_t \fBvalue\fP []"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 164 of file kinetic_types_internal\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBKineticPDUHeader\fP KineticResponse::header"

.PP
Definition at line 166 of file kinetic_types_internal\&.h\&.
.SS "Com__Seagate__Kinetic__Proto__Message* KineticResponse::proto"

.PP
Definition at line 167 of file kinetic_types_internal\&.h\&.
.SS "Com__Seagate__Kinetic__Proto__Command* KineticResponse::command"

.PP
Definition at line 168 of file kinetic_types_internal\&.h\&.
.SS "uint8_t KineticResponse::value[]"

.PP
Definition at line 169 of file kinetic_types_internal\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
