kinetic_bus.h
NAME
kinetic_bus.h -
SYNOPSIS
#include 'kinetic_types_internal.h'
Functions
bool KineticBus_Init (KineticClient *client, KineticClientConfig *config)
void KineticBus_Shutdown (KineticClient *const client)
Function Documentation
bool KineticBus_Init (KineticClient *client, KineticClientConfig *config)
Definition at line 250 of file kinetic_bus.c.
References KineticController_HandleUnexpectedResponse(), log_cb(), bus_config::log_cb, KineticClientConfig::logLevel, KineticClientConfig::maxThreadpoolThreads, KineticClientConfig::readerThreads, sink_cb(), unexpected_msg_cb(), unpack_cb(), and KineticClientConfig::writerThreads.
void KineticBus_Shutdown (KineticClient *constclient)
Definition at line 277 of file kinetic_bus.c.
References bus_free(), and bus_shutdown().
Author
Generated automatically by Doxygen for kinetic-c from the source code.