kinetic_types_internal.h
NAME
kinetic_types_internal.h -
SYNOPSIS
#include 'kinetic_types.h'
#include 'kinetic_proto.h'
#include <netinet/in.h>
#include <ifaddrs.h>
#include <openssl/sha.h>
#include <time.h>
#include <pthread.h>
Data Structures
struct KineticListItem
struct KineticList
struct KineticThread
struct KineticConnection
struct KineticHMAC
struct KineticMessage
struct KineticPDU
struct KineticOperation
struct KineticSerialAllocator
Macros
#define KINETIC_PDUS_PER_SESSION_DEFAULT (2)
#define KINETIC_PDUS_PER_SESSION_MAX (10)
#define KINETIC_SOCKET_DESCRIPTOR_INVALID (-1)
#define KINETIC_CONNECTION_INITIAL_STATUS_TIMEOUT_SECS (3)
#define KINETIC_OPERATION_TIMEOUT_SECS (20)
#define __func__ __FUNCTION__
#define STATIC static
#define NUM_ELEMENTS(ARRAY) (sizeof(ARRAY)/sizeof((ARRAY)[0]))
#define KINETIC_LIST_INITIALIZER
#define KINETIC_CONNECTION_INIT(_con)
#define KINETIC_MESSAGE_AUTH_HMAC_INIT(_msg, _identity, _hmac)
#define KINETIC_MESSAGE_HEADER_INIT(_hdr, _con)
#define KINETIC_MESSAGE_INIT(msg)
#define PDU_HEADER_LEN (1 + (2 * sizeof(int32_t)))
#define PDU_PROTO_MAX_LEN (1024 * 1024)
#define PDU_PROTO_MAX_UNPACKED_LEN (PDU_PROTO_MAX_LEN * 2)
#define PDU_MAX_LEN
#define KINETIC_PDU_HEADER_INIT (KineticPDUHeader) {.versionPrefix = 'F'}
#define KINETIC_PDU_INIT(_pdu, _con)
#define KINETIC_PDU_INIT_WITH_COMMAND(_pdu, _con)
#define KINETIC_OPERATION_INIT(_op, _con)
Typedefs
typedef KineticStatus(* KineticOperationCallback )(KineticOperation *const operation, KineticStatus const status)
Enumerations
enum KineticPDUType
Functions
struct __attribute__ ((__packed__)) _KineticPDUHeader
KineticProto_Command_Algorithm KineticProto_Command_Algorithm_from_KineticAlgorithm (KineticAlgorithm kinteicAlgorithm)
KineticAlgorithm KineticAlgorithm_from_KineticProto_Command_Algorithm (KineticProto_Command_Algorithm protoAlgorithm)
KineticProto_Command_Synchronization KineticProto_Command_Synchronization_from_KineticSynchronization (KineticSynchronization sync_mode)
KineticSynchronization KineticSynchronization_from_KineticProto_Command_Synchronization (KineticProto_Command_Synchronization sync_mode)
KineticStatus KineticProtoStatusCode_to_KineticStatus (KineticProto_Command_Status_StatusCode protoStatus)
ByteArray ProtobufCBinaryData_to_ByteArray (ProtobufCBinaryData protoData)
bool Copy_ProtobufCBinaryData_to_ByteBuffer (ByteBuffer dest, ProtobufCBinaryData src)
bool Copy_KineticProto_Command_KeyValue_to_KineticEntry (KineticProto_Command_KeyValue *keyValue, KineticEntry *entry)
bool Copy_KineticProto_Command_Range_to_ByteBufferArray (KineticProto_Command_Range *keyRange, ByteBufferArray *keys)
int Kinetic_GetErrnoDescription (int err_num, char *buf, size_t len)
struct timeval Kinetic_TimevalZero (void)
bool Kinetic_TimevalIsZero (struct timeval const tv)
struct timeval Kinetic_TimevalAdd (struct timeval const a, struct timeval const b)
int Kinetic_TimevalCmp (struct timeval const a, struct timeval const b)
KineticProto_Command_GetLog_Type KineticDeviceInfo_Type_to_KineticProto_Command_GetLog_Type (KineticDeviceInfo_Type type)
KineticMessageType KineticProto_Command_MessageType_to_KineticMessageType (KineticProto_Command_MessageType type)
Variables
KineticPDUHeader
Macro Definition Documentation
#define KINETIC_PDUS_PER_SESSION_DEFAULT (2)
Definition at line 32 of file kinetic_types_internal.h.
#define KINETIC_PDUS_PER_SESSION_MAX (10)
Definition at line 33 of file kinetic_types_internal.h.
#define KINETIC_SOCKET_DESCRIPTOR_INVALID (-1)
Definition at line 34 of file kinetic_types_internal.h.
#define KINETIC_CONNECTION_INITIAL_STATUS_TIMEOUT_SECS (3)
Definition at line 35 of file kinetic_types_internal.h.
#define KINETIC_OPERATION_TIMEOUT_SECS (20)
Definition at line 36 of file kinetic_types_internal.h.
#define __func__ __FUNCTION__
Definition at line 40 of file kinetic_types_internal.h.
#define STATIC static
Definition at line 47 of file kinetic_types_internal.h.
#define NUM_ELEMENTS(ARRAY) (sizeof(ARRAY)/sizeof((ARRAY)[0]))
Definition at line 51 of file kinetic_types_internal.h.
#define KINETIC_LIST_INITIALIZER
Value:
(KineticList) { \
    .mutex = PTHREAD_MUTEX_INITIALIZER, .locked = false, .start = NULL, }
Definition at line 71 of file kinetic_types_internal.h.
#define KINETIC_CONNECTION_INIT(_con)
Value:
{ (*_con) = (KineticConnection) { \
        .connected = false, \
        .socket = -1, \
        .writeMutex = PTHREAD_MUTEX_INITIALIZER, \
        .operations = KINETIC_LIST_INITIALIZER, \
        .pdus = KINETIC_LIST_INITIALIZER, \
    }; \
}
Definition at line 96 of file kinetic_types_internal.h.
#define KINETIC_MESSAGE_AUTH_HMAC_INIT(_msg, _identity, _hmac)
Value:
{ \
    assert((_msg) != NULL); \
    (_msg)->message.has_authType = true; \
    (_msg)->message.authType = KINETIC_PROTO_MESSAGE_AUTH_TYPE_HMACAUTH; \
    KineticProto_Message_hmacauth__init(&(_msg)->hmacAuth); \
    (_msg)->message.hmacAuth = &(_msg)->hmacAuth; \
    KineticProto_Message_pinauth__init(&(_msg)->pinAuth); \
    (_msg)->message.pinAuth = NULL; \
    (_msg)->command.header = &(_msg)->header; \
    memset((_msg)->hmacData, 0, KINETIC_HMAC_MAX_LEN); \
    if ((_hmac).len <= KINETIC_HMAC_MAX_LEN \
        && (_hmac).data != NULL && (_hmac).len > 0 \
        && (_msg)->hmacData != NULL) { \
        memcpy((_msg)->hmacData, (_hmac).data, (_hmac).len);} \
    (_msg)->message.hmacAuth->has_identity = true; \
    (_msg)->message.hmacAuth->identity = (_identity); \
    (_msg)->message.hmacAuth->has_hmac = true; \
    (_msg)->message.hmacAuth->hmac = (ProtobufCBinaryData) { \
        .data = (_msg)->hmacData, .len = SHA_DIGEST_LENGTH}; \
}
Definition at line 139 of file kinetic_types_internal.h.
#define KINETIC_MESSAGE_HEADER_INIT(_hdr, _con)
Value:
{ \
    assert((_hdr) != NULL); \
    assert((_con) != NULL); \
    *(_hdr) = (KineticProto_Command_Header) { \
        .base = PROTOBUF_C_MESSAGE_INIT(&KineticProto_command_header__descriptor), \
        .has_clusterVersion = true, \
        .clusterVersion = (_con)->session.config.clusterVersion, \
        .has_connectionID = true, \
        .connectionID = (_con)->connectionID, \
        .has_sequence = true, \
        .sequence = (_con)->sequence, \
    }; \
}
Definition at line 160 of file kinetic_types_internal.h.
#define KINETIC_MESSAGE_INIT(msg)
Value:
{ \
    KineticProto_Message__init(&(msg)->message); \
    KineticProto_command__init(&(msg)->command); \
    KineticProto_Message_hmacauth__init(&(msg)->hmacAuth); \
    KineticProto_Message_pinauth__init(&(msg)->pinAuth); \
    KineticProto_command_header__init(&(msg)->header); \
    KineticProto_command_status__init(&(msg)->status); \
    KineticProto_command_body__init(&(msg)->body); \
    KineticProto_command_key_value__init(&(msg)->keyValue); \
    KineticProto_command_range__init(&(msg)->keyRange); \
    KineticProto_command_get_log__init(&(msg)->getLog); \
    KineticProto_command_pin_operation__init(&(msg)->pinOp); \
    KineticProto_command_p2_poperation__init(&(msg)->p2pOp); \
    KineticProto_command_p2_poperation_operation__init(&(msg)->p2pOpOp); \
    KineticProto_command_p2_poperation_peer__init(&(msg)->p2pPeer); \
    KINETIC_MESSAGE_AUTH_HMAC_INIT(msg, 0, BYTE_ARRAY_NONE); \
    (msg)->has_command = false; \
}
Definition at line 174 of file kinetic_types_internal.h.
#define PDU_HEADER_LEN (1 + (2 * sizeof(int32_t)))
Definition at line 194 of file kinetic_types_internal.h.
#define PDU_PROTO_MAX_LEN (1024 * 1024)
Definition at line 195 of file kinetic_types_internal.h.
#define PDU_PROTO_MAX_UNPACKED_LEN (PDU_PROTO_MAX_LEN * 2)
Definition at line 196 of file kinetic_types_internal.h.
#define PDU_MAX_LEN
Value:
(PDU_HEADER_LEN + \
                                    PDU_PROTO_MAX_LEN + KINETIC_OBJ_SIZE)
Definition at line 197 of file kinetic_types_internal.h.
#define KINETIC_PDU_HEADER_INIT (KineticPDUHeader) {.versionPrefix = 'F'}
Definition at line 204 of file kinetic_types_internal.h.
#define KINETIC_PDU_INIT(_pdu, _con)
Value:
{ \
    assert((_pdu) != NULL); \
    assert((_con) != NULL); \
    memset((_pdu), 0, sizeof(KineticPDU)); \
    (_pdu)->connection = (_con); \
    (_pdu)->header = KINETIC_PDU_HEADER_INIT; \
    (_pdu)->headerNBO = KINETIC_PDU_HEADER_INIT; \
    KINETIC_MESSAGE_INIT(&((_pdu)->protoData.message)); \
    KINETIC_MESSAGE_AUTH_HMAC_INIT( \
            &((_pdu)->protoData.message), (_con)->session.config.identity, (_con)->session.config.hmacKey); \
    KINETIC_MESSAGE_HEADER_INIT(&((_pdu)->protoData.message.header), (_con)); \
}
Definition at line 243 of file kinetic_types_internal.h.
#define KINETIC_PDU_INIT_WITH_COMMAND(_pdu, _con)
Value:
{ \
    KINETIC_PDU_INIT((_pdu), (_con)) \
    (_pdu)->proto = &(_pdu)->protoData.message.message; \
    (_pdu)->protoData.message.has_command = true; \
    (_pdu)->command = &(_pdu)->protoData.message.command; \
    (_pdu)->command->header = &(_pdu)->protoData.message.header; \
    (_pdu)->type = KINETIC_PDU_TYPE_REQUEST; \
}
Definition at line 256 of file kinetic_types_internal.h.
#define KINETIC_OPERATION_INIT(_op, _con)
Value:
assert((_op) != NULL); \
    assert((_con) != NULL); \
    *(_op) = (KineticOperation) { \
        .connection = (_con), \
        .timeoutTimeMutex = PTHREAD_MUTEX_INITIALIZER, \
    }
Definition at line 283 of file kinetic_types_internal.h.
Typedef Documentation
typedef KineticStatus(* KineticOperationCallback)(KineticOperation *const operation, KineticStatus const status)
Definition at line 265 of file kinetic_types_internal.h.
Enumeration Type Documentation
enum KineticPDUType
Enumerator
KINETIC_PDU_TYPE_INVALID
KINETIC_PDU_TYPE_REQUEST
KINETIC_PDU_TYPE_RESPONSE
KINETIC_PDU_TYPE_UNSOLICITED
Definition at line 207 of file kinetic_types_internal.h.
Function Documentation
struct __attribute__ ((__packed__))
Definition at line 199 of file kinetic_types_internal.h.
KineticProto_Command_Algorithm KineticProto_Command_Algorithm_from_KineticAlgorithm (KineticAlgorithmkinteicAlgorithm)
Definition at line 134 of file kinetic_types_internal.c.
References KINETIC_ALGORITHM_CRC32, KINETIC_ALGORITHM_CRC64, KINETIC_ALGORITHM_INVALID, KINETIC_ALGORITHM_SHA1, KINETIC_ALGORITHM_SHA2, KINETIC_ALGORITHM_SHA3, KINETIC_PROTO_COMMAND_ALGORITHM_CRC32, KINETIC_PROTO_COMMAND_ALGORITHM_CRC64, KINETIC_PROTO_COMMAND_ALGORITHM_INVALID_ALGORITHM, KINETIC_PROTO_COMMAND_ALGORITHM_SHA1, KINETIC_PROTO_COMMAND_ALGORITHM_SHA2, and KINETIC_PROTO_COMMAND_ALGORITHM_SHA3.
KineticAlgorithm KineticAlgorithm_from_KineticProto_Command_Algorithm (KineticProto_Command_AlgorithmprotoAlgorithm)
Definition at line 165 of file kinetic_types_internal.c.
References KINETIC_ALGORITHM_CRC32, KINETIC_ALGORITHM_CRC64, KINETIC_ALGORITHM_INVALID, KINETIC_ALGORITHM_SHA1, KINETIC_ALGORITHM_SHA2, KINETIC_ALGORITHM_SHA3, KINETIC_PROTO_COMMAND_ALGORITHM_CRC32, KINETIC_PROTO_COMMAND_ALGORITHM_CRC64, KINETIC_PROTO_COMMAND_ALGORITHM_INVALID_ALGORITHM, KINETIC_PROTO_COMMAND_ALGORITHM_SHA1, KINETIC_PROTO_COMMAND_ALGORITHM_SHA2, and KINETIC_PROTO_COMMAND_ALGORITHM_SHA3.
KineticProto_Command_Synchronization KineticProto_Command_Synchronization_from_KineticSynchronization (KineticSynchronizationsync_mode)
Definition at line 89 of file kinetic_types_internal.c.
References KINETIC_PROTO_COMMAND_SYNCHRONIZATION_FLUSH, KINETIC_PROTO_COMMAND_SYNCHRONIZATION_INVALID_SYNCHRONIZATION, KINETIC_PROTO_COMMAND_SYNCHRONIZATION_WRITEBACK, KINETIC_PROTO_COMMAND_SYNCHRONIZATION_WRITETHROUGH, KINETIC_SYNCHRONIZATION_FLUSH, KINETIC_SYNCHRONIZATION_INVALID, KINETIC_SYNCHRONIZATION_WRITEBACK, and KINETIC_SYNCHRONIZATION_WRITETHROUGH.
KineticSynchronization KineticSynchronization_from_KineticProto_Command_Synchronization (KineticProto_Command_Synchronizationsync_mode)
Definition at line 111 of file kinetic_types_internal.c.
References KINETIC_PROTO_COMMAND_SYNCHRONIZATION_FLUSH, KINETIC_PROTO_COMMAND_SYNCHRONIZATION_INVALID_SYNCHRONIZATION, KINETIC_PROTO_COMMAND_SYNCHRONIZATION_WRITEBACK, KINETIC_PROTO_COMMAND_SYNCHRONIZATION_WRITETHROUGH, KINETIC_SYNCHRONIZATION_FLUSH, KINETIC_SYNCHRONIZATION_INVALID, KINETIC_SYNCHRONIZATION_WRITEBACK, and KINETIC_SYNCHRONIZATION_WRITETHROUGH.
KineticStatus KineticProtoStatusCode_to_KineticStatus (KineticProto_Command_Status_StatusCodeprotoStatus)
Definition at line 28 of file kinetic_types_internal.c.
References KINETIC_PROTO_COMMAND_STATUS_STATUS_CODE_DATA_ERROR, KINETIC_PROTO_COMMAND_STATUS_STATUS_CODE_EXPIRED, KINETIC_PROTO_COMMAND_STATUS_STATUS_CODE_HEADER_REQUIRED, KINETIC_PROTO_COMMAND_STATUS_STATUS_CODE_HMAC_FAILURE, KINETIC_PROTO_COMMAND_STATUS_STATUS_CODE_INTERNAL_ERROR, KINETIC_PROTO_COMMAND_STATUS_STATUS_CODE_INVALID_REQUEST, KINETIC_PROTO_COMMAND_STATUS_STATUS_CODE_INVALID_STATUS_CODE, KINETIC_PROTO_COMMAND_STATUS_STATUS_CODE_NESTED_OPERATION_ERRORS, KINETIC_PROTO_COMMAND_STATUS_STATUS_CODE_NO_SPACE, KINETIC_PROTO_COMMAND_STATUS_STATUS_CODE_NO_SUCH_HMAC_ALGORITHM, KINETIC_PROTO_COMMAND_STATUS_STATUS_CODE_NOT_ATTEMPTED, KINETIC_PROTO_COMMAND_STATUS_STATUS_CODE_NOT_AUTHORIZED, KINETIC_PROTO_COMMAND_STATUS_STATUS_CODE_NOT_FOUND, KINETIC_PROTO_COMMAND_STATUS_STATUS_CODE_PERM_DATA_ERROR, KINETIC_PROTO_COMMAND_STATUS_STATUS_CODE_REMOTE_CONNECTION_ERROR, KINETIC_PROTO_COMMAND_STATUS_STATUS_CODE_SERVICE_BUSY, KINETIC_PROTO_COMMAND_STATUS_STATUS_CODE_SUCCESS, KINETIC_PROTO_COMMAND_STATUS_STATUS_CODE_VERSION_FAILURE, KINETIC_PROTO_COMMAND_STATUS_STATUS_CODE_VERSION_MISMATCH, KINETIC_STATUS_CLUSTER_MISMATCH, KINETIC_STATUS_CONNECTION_ERROR, KINETIC_STATUS_DATA_ERROR, KINETIC_STATUS_DEVICE_BUSY, KINETIC_STATUS_INVALID, KINETIC_STATUS_INVALID_REQUEST, KINETIC_STATUS_NOT_FOUND, KINETIC_STATUS_OPERATION_FAILED, KINETIC_STATUS_SUCCESS, and KINETIC_STATUS_VERSION_MISMATCH.
ByteArray ProtobufCBinaryData_to_ByteArray (ProtobufCBinaryDataprotoData)
Definition at line 193 of file kinetic_types_internal.c.
References ByteArray::data.
bool Copy_ProtobufCBinaryData_to_ByteBuffer (ByteBufferdest, ProtobufCBinaryDatasrc)
Definition at line 202 of file kinetic_types_internal.c.
References ByteBuffer::array, ByteBuffer::bytesUsed, ByteArray::data, and ByteArray::len.
bool Copy_KineticProto_Command_KeyValue_to_KineticEntry (KineticProto_Command_KeyValue *keyValue, KineticEntry *entry)
Definition at line 220 of file kinetic_types_internal.c.
References KineticEntry::algorithm, ByteBuffer::array, ByteBuffer_Append(), ByteBuffer_Reset(), ByteBuffer::bytesUsed, ByteArray::data, KineticEntry::dbVersion, KineticEntry::force, KineticEntry::key, KineticAlgorithm_from_KineticProto_Command_Algorithm(), KineticSynchronization_from_KineticProto_Command_Synchronization(), ByteArray::len, LOG1, KineticEntry::metadataOnly, KineticEntry::newVersion, KineticEntry::synchronization, and KineticEntry::tag.
bool Copy_KineticProto_Command_Range_to_ByteBufferArray (KineticProto_Command_Range *keyRange, ByteBufferArray *keys)
Definition at line 294 of file kinetic_types_internal.c.
References ByteBufferArray::buffers, ByteBuffer_Append(), ByteBuffer_Reset(), ByteBufferArray::count, LOGF2, and ByteBufferArray::used.
int Kinetic_GetErrnoDescription (interr_num, char *buf, size_tlen)
Definition at line 311 of file kinetic_types_internal.c.
struct timeval Kinetic_TimevalZero (void)
Definition at line 326 of file kinetic_types_internal.c.
bool Kinetic_TimevalIsZero (struct timeval consttv)
Definition at line 334 of file kinetic_types_internal.c.
struct timeval Kinetic_TimevalAdd (struct timeval consta, struct timeval constb)
Definition at line 339 of file kinetic_types_internal.c.
int Kinetic_TimevalCmp (struct timeval consta, struct timeval constb)
Definition at line 366 of file kinetic_types_internal.c.
KineticProto_Command_GetLog_Type KineticDeviceInfo_Type_to_KineticProto_Command_GetLog_Type (KineticDeviceInfo_Typetype)
Definition at line 371 of file kinetic_types_internal.c.
References KINETIC_DEVICE_INFO_TYPE_CAPACITIES, KINETIC_DEVICE_INFO_TYPE_CONFIGURATION, KINETIC_DEVICE_INFO_TYPE_DEVICE, KINETIC_DEVICE_INFO_TYPE_LIMITS, KINETIC_DEVICE_INFO_TYPE_MESSAGES, KINETIC_DEVICE_INFO_TYPE_STATISTICS, KINETIC_DEVICE_INFO_TYPE_TEMPERATURES, KINETIC_DEVICE_INFO_TYPE_UTILIZATIONS, KINETIC_PROTO_COMMAND_GET_LOG__INIT_TYPE_CONFIGURATION, KINETIC_PROTO_COMMAND_GET_LOG_TYPE_CAPACITIES, KINETIC_PROTO_COMMAND_GET_LOG_TYPE_DEVICE, KINETIC_PROTO_COMMAND_GET_LOG_TYPE_INVALID_TYPE, KINETIC_PROTO_COMMAND_GET_LOG_TYPE_LIMITS, KINETIC_PROTO_COMMAND_GET_LOG_TYPE_MESSAGES, KINETIC_PROTO_COMMAND_GET_LOG_TYPE_STATISTICS, KINETIC_PROTO_COMMAND_GET_LOG_TYPE_TEMPERATURES, and KINETIC_PROTO_COMMAND_GET_LOG_TYPE_UTILIZATIONS.
KineticMessageType KineticProto_Command_MessageType_to_KineticMessageType (KineticProto_Command_MessageTypetype)
Definition at line 399 of file kinetic_types_internal.c.
Variable Documentation
KineticPDUHeader
Definition at line 203 of file kinetic_types_internal.h.
Author
Generated automatically by Doxygen for kinetic-c from the source code.