.TH "kinetic_pdu.c" 3 "Thu Nov 13 2014" "Version v0.8.1-beta" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kinetic_pdu.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'kinetic_pdu\&.h'\fP
.br
\fC#include 'kinetic_nbo\&.h'\fP
.br
\fC#include 'kinetic_connection\&.h'\fP
.br
\fC#include 'kinetic_socket\&.h'\fP
.br
\fC#include 'kinetic_hmac\&.h'\fP
.br
\fC#include 'kinetic_logger\&.h'\fP
.br
\fC#include 'kinetic_proto\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBKineticPDU_Init\fP (KineticPDU *const pdu, KineticConnection *const connection)"
.br
.ti -1c
.RI "\fBKineticStatus\fP \fBKineticPDU_ReceiveMain\fP (KineticPDU *const response)"
.br
.ti -1c
.RI "\fBKineticStatus\fP \fBKineticPDU_ReceiveValue\fP (int socket_desc, \fBByteBuffer\fP *value, size_t value_length)"
.br
.ti -1c
.RI "size_t \fBKineticPDU_GetValueLength\fP (KineticPDU *const pdu)"
.br
.ti -1c
.RI "\fBKineticStatus\fP \fBKineticPDU_GetStatus\fP (KineticPDU *pdu)"
.br
.ti -1c
.RI "KineticProto_Command_KeyValue * \fBKineticPDU_GetKeyValue\fP (KineticPDU *pdu)"
.br
.ti -1c
.RI "KineticProto_Command_Range * \fBKineticPDU_GetKeyRange\fP (KineticPDU *pdu)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void KineticPDU_Init (KineticPDU *constpdu, KineticConnection *constconnection)"

.PP
Definition at line 30 of file kinetic_pdu\&.c\&.
.PP
References KINETIC_PDU_INIT\&.
.SS "\fBKineticStatus\fP KineticPDU_ReceiveMain (KineticPDU *constresponse)"

.PP
Definition at line 36 of file kinetic_pdu\&.c\&.
.PP
References ByteBuffer::array, ByteBuffer_Create(), KineticMessage::command, KineticMessage::has_command, KINETIC_PROTO_COMMAND_STATUS_STATUS_CODE_DATA_ERROR, KINETIC_PROTO_MESSAGE_AUTH_TYPE_HMACAUTH, KINETIC_PROTO_MESSAGE_AUTH_TYPE_PINAUTH, KINETIC_PROTO_MESSAGE_AUTH_TYPE_UNSOLICITEDSTATUS, KINETIC_STATUS_DATA_ERROR, KINETIC_STATUS_SUCCESS, KineticHMAC_Validate(), KineticLogger_LogHeader(), KineticLogger_LogProtobuf(), KineticNBO_ToHostU32(), KineticPDU_GetStatus(), KineticPDUHeader, KineticProto_command__unpack(), KineticSocket_Read(), KineticSocket_ReadProtobuf(), ByteArray::len, LOG0, LOG2, LOG3, LOGF1, KineticMessage::message, and KineticMessage::status\&.
.SS "\fBKineticStatus\fP KineticPDU_ReceiveValue (intsocket_desc, \fBByteBuffer\fP *value, size_tvalue_length)"

.PP
Definition at line 119 of file kinetic_pdu\&.c\&.
.PP
References ByteBuffer::array, ByteBuffer_Reset(), ByteArray::data, KINETIC_STATUS_SUCCESS, KineticLogger_LogByteBuffer(), KineticSocket_Read(), LOG0, LOG1, and LOGF1\&.
.SS "size_t KineticPDU_GetValueLength (KineticPDU *constpdu)"

.PP
Definition at line 138 of file kinetic_pdu\&.c\&.
.SS "\fBKineticStatus\fP KineticPDU_GetStatus (KineticPDU *pdu)"

.PP
Definition at line 144 of file kinetic_pdu\&.c\&.
.PP
References KINETIC_STATUS_INVALID, and KineticProtoStatusCode_to_KineticStatus()\&.
.SS "KineticProto_Command_KeyValue* KineticPDU_GetKeyValue (KineticPDU *pdu)"

.PP
Definition at line 160 of file kinetic_pdu\&.c\&.
.SS "KineticProto_Command_Range* KineticPDU_GetKeyRange (KineticPDU *pdu)"

.PP
Definition at line 173 of file kinetic_pdu\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
