.TH "KineticKeyRange" 3 "Thu Nov 13 2014" "Version v0.8.1-beta" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticKeyRange \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBByteBuffer\fP \fBstartKey\fP"
.br
.ti -1c
.RI "\fBByteBuffer\fP \fBendKey\fP"
.br
.ti -1c
.RI "bool \fBstartKeyInclusive\fP"
.br
.ti -1c
.RI "bool \fBendKeyInclusive\fP"
.br
.ti -1c
.RI "int32_t \fBmaxReturned\fP"
.br
.ti -1c
.RI "bool \fBreverse\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 197 of file kinetic_types\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBByteBuffer\fP KineticKeyRange::startKey"

.PP
Definition at line 198 of file kinetic_types\&.h\&.
.SS "\fBByteBuffer\fP KineticKeyRange::endKey"

.PP
Definition at line 199 of file kinetic_types\&.h\&.
.SS "bool KineticKeyRange::startKeyInclusive"

.PP
Definition at line 200 of file kinetic_types\&.h\&.
.SS "bool KineticKeyRange::endKeyInclusive"

.PP
Definition at line 201 of file kinetic_types\&.h\&.
.SS "int32_t KineticKeyRange::maxReturned"

.PP
Definition at line 202 of file kinetic_types\&.h\&.
.SS "bool KineticKeyRange::reverse"

.PP
Definition at line 203 of file kinetic_types\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
