kinetic_types_internal.c
NAME
kinetic_types_internal.c -
SYNOPSIS
#include 'kinetic_types_internal.h'
#include 'kinetic_logger.h'
#include 'byte_array.h'
#include <sys/param.h>
#include <errno.h>
Functions
KineticStatus KineticProtoStatusCode_to_KineticStatus (Com__Seagate__Kinetic__Proto__Command__Status__StatusCode protoStatus)
Com__Seagate__Kinetic__Proto__Command__Synchronization Com__Seagate__Kinetic__Proto__Command__Synchronization_from_KineticSynchronization (KineticSynchronization sync_mode)
KineticSynchronization KineticSynchronization_from_Com__Seagate__Kinetic__Proto__Command__Synchronization (Com__Seagate__Kinetic__Proto__Command__Synchronization sync_mode)
Com__Seagate__Kinetic__Proto__Command__Algorithm Com__Seagate__Kinetic__Proto__Command__Algorithm_from_KineticAlgorithm (KineticAlgorithm kinteicAlgorithm)
KineticAlgorithm KineticAlgorithm_from_Com__Seagate__Kinetic__Proto__Command__Algorithm (Com__Seagate__Kinetic__Proto__Command__Algorithm protoAlgorithm)
ByteArray ProtobufCBinaryData_to_ByteArray (ProtobufCBinaryData protoData)
bool Copy_ProtobufCBinaryData_to_ByteBuffer (ByteBuffer dest, ProtobufCBinaryData src)
bool Copy_Com__Seagate__Kinetic__Proto__Command__KeyValue_to_KineticEntry (Com__Seagate__Kinetic__Proto__Command__KeyValue *key_value, KineticEntry *entry)
bool Copy_Com__Seagate__Kinetic__Proto__Command__Range_to_ByteBufferArray (Com__Seagate__Kinetic__Proto__Command__Range *keyRange, ByteBufferArray *keys)
int Kinetic_GetErrnoDescription (int err_num, char *buf, size_t len)
struct timeval Kinetic_TimevalZero (void)
bool Kinetic_TimevalIsZero (struct timeval const tv)
struct timeval Kinetic_TimevalAdd (struct timeval const a, struct timeval const b)
static int cmp_suseconds_t (suseconds_t const a, suseconds_t const b)
int Kinetic_TimevalCmp (struct timeval const a, struct timeval const b)
Com__Seagate__Kinetic__Proto__Command__GetLog__Type KineticLogInfo_Type_to_Com__Seagate__Kinetic__Proto__Command__GetLog__Type (KineticLogInfo_Type type)
KineticMessageType Com__Seagate__Kinetic__Proto__Command__MessageType_to_KineticMessageType (Com__Seagate__Kinetic__Proto__Command__MessageType type)
void KineticSessionConfig_Copy (KineticSessionConfig *dest, KineticSessionConfig *src)
void KineticMessage_Init (KineticMessage *const message)
static void KineticMessage_HeaderInit (Com__Seagate__Kinetic__Proto__Command__Header *hdr, KineticSession const *const session)
void KineticRequest_Init (KineticRequest *request, KineticSession const *const session)
Function Documentation
KineticStatus KineticProtoStatusCode_to_KineticStatus (Com__Seagate__Kinetic__Proto__Command__Status__StatusCodeprotoStatus)
Definition at line 28 of file kinetic_types_internal.c.
References COM__SEAGATE__KINETIC__PROTO__COMMAND__STATUS__STATUS_CODE__DATA_ERROR, COM__SEAGATE__KINETIC__PROTO__COMMAND__STATUS__STATUS_CODE__DEVICE_LOCKED, COM__SEAGATE__KINETIC__PROTO__COMMAND__STATUS__STATUS_CODE__EXPIRED, COM__SEAGATE__KINETIC__PROTO__COMMAND__STATUS__STATUS_CODE__HEADER_REQUIRED, COM__SEAGATE__KINETIC__PROTO__COMMAND__STATUS__STATUS_CODE__HMAC_FAILURE, COM__SEAGATE__KINETIC__PROTO__COMMAND__STATUS__STATUS_CODE__INTERNAL_ERROR, COM__SEAGATE__KINETIC__PROTO__COMMAND__STATUS__STATUS_CODE__INVALID_REQUEST, COM__SEAGATE__KINETIC__PROTO__COMMAND__STATUS__STATUS_CODE__INVALID_STATUS_CODE, COM__SEAGATE__KINETIC__PROTO__COMMAND__STATUS__STATUS_CODE__NESTED_OPERATION_ERRORS, COM__SEAGATE__KINETIC__PROTO__COMMAND__STATUS__STATUS_CODE__NO_SPACE, COM__SEAGATE__KINETIC__PROTO__COMMAND__STATUS__STATUS_CODE__NO_SUCH_HMAC_ALGORITHM, COM__SEAGATE__KINETIC__PROTO__COMMAND__STATUS__STATUS_CODE__NOT_ATTEMPTED, COM__SEAGATE__KINETIC__PROTO__COMMAND__STATUS__STATUS_CODE__NOT_AUTHORIZED, COM__SEAGATE__KINETIC__PROTO__COMMAND__STATUS__STATUS_CODE__NOT_FOUND, COM__SEAGATE__KINETIC__PROTO__COMMAND__STATUS__STATUS_CODE__PERM_DATA_ERROR, COM__SEAGATE__KINETIC__PROTO__COMMAND__STATUS__STATUS_CODE__REMOTE_CONNECTION_ERROR, COM__SEAGATE__KINETIC__PROTO__COMMAND__STATUS__STATUS_CODE__SERVICE_BUSY, COM__SEAGATE__KINETIC__PROTO__COMMAND__STATUS__STATUS_CODE__SUCCESS, COM__SEAGATE__KINETIC__PROTO__COMMAND__STATUS__STATUS_CODE__VERSION_FAILURE, COM__SEAGATE__KINETIC__PROTO__COMMAND__STATUS__STATUS_CODE__VERSION_MISMATCH, KINETIC_STATUS_CLUSTER_MISMATCH, KINETIC_STATUS_CONNECTION_ERROR, KINETIC_STATUS_DATA_ERROR, KINETIC_STATUS_DEVICE_BUSY, KINETIC_STATUS_DEVICE_LOCKED, KINETIC_STATUS_HMAC_FAILURE, KINETIC_STATUS_INVALID, KINETIC_STATUS_INVALID_REQUEST, KINETIC_STATUS_NOT_AUTHORIZED, KINETIC_STATUS_NOT_FOUND, KINETIC_STATUS_OPERATION_FAILED, KINETIC_STATUS_SUCCESS, and KINETIC_STATUS_VERSION_MISMATCH.
Com__Seagate__Kinetic__Proto__Command__Synchronization Com__Seagate__Kinetic__Proto__Command__Synchronization_from_KineticSynchronization (KineticSynchronizationsync_mode)
Definition at line 95 of file kinetic_types_internal.c.
References COM__SEAGATE__KINETIC__PROTO__COMMAND__SYNCHRONIZATION__FLUSH, COM__SEAGATE__KINETIC__PROTO__COMMAND__SYNCHRONIZATION__INVALID_SYNCHRONIZATION, COM__SEAGATE__KINETIC__PROTO__COMMAND__SYNCHRONIZATION__WRITEBACK, COM__SEAGATE__KINETIC__PROTO__COMMAND__SYNCHRONIZATION__WRITETHROUGH, KINETIC_SYNCHRONIZATION_FLUSH, KINETIC_SYNCHRONIZATION_INVALID, KINETIC_SYNCHRONIZATION_WRITEBACK, and KINETIC_SYNCHRONIZATION_WRITETHROUGH.
KineticSynchronization KineticSynchronization_from_Com__Seagate__Kinetic__Proto__Command__Synchronization (Com__Seagate__Kinetic__Proto__Command__Synchronizationsync_mode)
Definition at line 117 of file kinetic_types_internal.c.
References COM__SEAGATE__KINETIC__PROTO__COMMAND__SYNCHRONIZATION__FLUSH, COM__SEAGATE__KINETIC__PROTO__COMMAND__SYNCHRONIZATION__INVALID_SYNCHRONIZATION, COM__SEAGATE__KINETIC__PROTO__COMMAND__SYNCHRONIZATION__WRITEBACK, COM__SEAGATE__KINETIC__PROTO__COMMAND__SYNCHRONIZATION__WRITETHROUGH, KINETIC_SYNCHRONIZATION_FLUSH, KINETIC_SYNCHRONIZATION_INVALID, KINETIC_SYNCHRONIZATION_WRITEBACK, and KINETIC_SYNCHRONIZATION_WRITETHROUGH.
Com__Seagate__Kinetic__Proto__Command__Algorithm Com__Seagate__Kinetic__Proto__Command__Algorithm_from_KineticAlgorithm (KineticAlgorithmkinteicAlgorithm)
Definition at line 140 of file kinetic_types_internal.c.
References COM__SEAGATE__KINETIC__PROTO__COMMAND__ALGORITHM__CRC32, COM__SEAGATE__KINETIC__PROTO__COMMAND__ALGORITHM__CRC64, COM__SEAGATE__KINETIC__PROTO__COMMAND__ALGORITHM__INVALID_ALGORITHM, COM__SEAGATE__KINETIC__PROTO__COMMAND__ALGORITHM__SHA1, COM__SEAGATE__KINETIC__PROTO__COMMAND__ALGORITHM__SHA2, COM__SEAGATE__KINETIC__PROTO__COMMAND__ALGORITHM__SHA3, KINETIC_ALGORITHM_CRC32, KINETIC_ALGORITHM_CRC64, KINETIC_ALGORITHM_INVALID, KINETIC_ALGORITHM_SHA1, KINETIC_ALGORITHM_SHA2, and KINETIC_ALGORITHM_SHA3.
KineticAlgorithm KineticAlgorithm_from_Com__Seagate__Kinetic__Proto__Command__Algorithm (Com__Seagate__Kinetic__Proto__Command__AlgorithmprotoAlgorithm)
Definition at line 171 of file kinetic_types_internal.c.
References COM__SEAGATE__KINETIC__PROTO__COMMAND__ALGORITHM__CRC32, COM__SEAGATE__KINETIC__PROTO__COMMAND__ALGORITHM__CRC64, COM__SEAGATE__KINETIC__PROTO__COMMAND__ALGORITHM__INVALID_ALGORITHM, COM__SEAGATE__KINETIC__PROTO__COMMAND__ALGORITHM__SHA1, COM__SEAGATE__KINETIC__PROTO__COMMAND__ALGORITHM__SHA2, COM__SEAGATE__KINETIC__PROTO__COMMAND__ALGORITHM__SHA3, KINETIC_ALGORITHM_CRC32, KINETIC_ALGORITHM_CRC64, KINETIC_ALGORITHM_INVALID, KINETIC_ALGORITHM_SHA1, KINETIC_ALGORITHM_SHA2, and KINETIC_ALGORITHM_SHA3.
ByteArray ProtobufCBinaryData_to_ByteArray (ProtobufCBinaryDataprotoData)
Definition at line 199 of file kinetic_types_internal.c.
References ByteArray::data.
bool Copy_ProtobufCBinaryData_to_ByteBuffer (ByteBufferdest, ProtobufCBinaryDatasrc)
Definition at line 208 of file kinetic_types_internal.c.
References ByteBuffer::array, ByteBuffer::bytesUsed, ByteArray::data, and ByteArray::len.
bool Copy_Com__Seagate__Kinetic__Proto__Command__KeyValue_to_KineticEntry (Com__Seagate__Kinetic__Proto__Command__KeyValue *key_value, KineticEntry *entry)
Definition at line 226 of file kinetic_types_internal.c.
References KineticEntry::algorithm, ByteBuffer::array, ByteBuffer_Append(), ByteBuffer_Reset(), ByteBuffer::bytesUsed, ByteArray::data, KineticEntry::dbVersion, KineticEntry::key, KineticAlgorithm_from_Com__Seagate__Kinetic__Proto__Command__Algorithm(), ByteArray::len, LOG1, and KineticEntry::tag.
bool Copy_Com__Seagate__Kinetic__Proto__Command__Range_to_ByteBufferArray (Com__Seagate__Kinetic__Proto__Command__Range *keyRange, ByteBufferArray *keys)
Definition at line 277 of file kinetic_types_internal.c.
References ByteBufferArray::buffers, ByteBuffer_Append(), ByteBuffer_Reset(), ByteBufferArray::count, LOGF2, and ByteBufferArray::used.
int Kinetic_GetErrnoDescription (interr_num, char *buf, size_tlen)
Definition at line 294 of file kinetic_types_internal.c.
struct timeval Kinetic_TimevalZero (void)
Definition at line 308 of file kinetic_types_internal.c.
bool Kinetic_TimevalIsZero (struct timeval consttv)
Definition at line 316 of file kinetic_types_internal.c.
struct timeval Kinetic_TimevalAdd (struct timeval consta, struct timeval constb)
Definition at line 321 of file kinetic_types_internal.c.
static int cmp_suseconds_t (suseconds_t consta, suseconds_t constb) [static]
Definition at line 335 of file kinetic_types_internal.c.
int Kinetic_TimevalCmp (struct timeval consta, struct timeval constb)
Definition at line 348 of file kinetic_types_internal.c.
References cmp_suseconds_t().
Com__Seagate__Kinetic__Proto__Command__GetLog__Type KineticLogInfo_Type_to_Com__Seagate__Kinetic__Proto__Command__GetLog__Type (KineticLogInfo_Typetype)
Definition at line 353 of file kinetic_types_internal.c.
References COM__SEAGATE__KINETIC__PROTO__COMMAND__GET_LOG__TYPE__CAPACITIES, COM__SEAGATE__KINETIC__PROTO__COMMAND__GET_LOG__TYPE__CONFIGURATION, COM__SEAGATE__KINETIC__PROTO__COMMAND__GET_LOG__TYPE__INVALID_TYPE, COM__SEAGATE__KINETIC__PROTO__COMMAND__GET_LOG__TYPE__LIMITS, COM__SEAGATE__KINETIC__PROTO__COMMAND__GET_LOG__TYPE__MESSAGES, COM__SEAGATE__KINETIC__PROTO__COMMAND__GET_LOG__TYPE__STATISTICS, COM__SEAGATE__KINETIC__PROTO__COMMAND__GET_LOG__TYPE__TEMPERATURES, COM__SEAGATE__KINETIC__PROTO__COMMAND__GET_LOG__TYPE__UTILIZATIONS, KINETIC_DEVICE_INFO_TYPE_CAPACITIES, KINETIC_DEVICE_INFO_TYPE_CONFIGURATION, KINETIC_DEVICE_INFO_TYPE_LIMITS, KINETIC_DEVICE_INFO_TYPE_MESSAGES, KINETIC_DEVICE_INFO_TYPE_STATISTICS, KINETIC_DEVICE_INFO_TYPE_TEMPERATURES, and KINETIC_DEVICE_INFO_TYPE_UTILIZATIONS.
KineticMessageType Com__Seagate__Kinetic__Proto__Command__MessageType_to_KineticMessageType (Com__Seagate__Kinetic__Proto__Command__MessageTypetype)
Definition at line 379 of file kinetic_types_internal.c.
void KineticSessionConfig_Copy (KineticSessionConfig *dest, KineticSessionConfig *src)
Definition at line 384 of file kinetic_types_internal.c.
References ByteArray::data, KineticSessionConfig::hmacKey, KineticSessionConfig::keyData, KINETIC_ASSERT, and ByteArray::len.
void KineticMessage_Init (KineticMessage *constmessage)
Definition at line 395 of file kinetic_types_internal.c.
References KineticMessage::body, com__seagate__kinetic__proto__command__body__init(), com__seagate__kinetic__proto__command__get_log__device__init(), com__seagate__kinetic__proto__command__get_log__init(), com__seagate__kinetic__proto__command__header__init(), com__seagate__kinetic__proto__command__init(), com__seagate__kinetic__proto__command__key_value__init(), com__seagate__kinetic__proto__command__pin_operation__init(), com__seagate__kinetic__proto__command__range__init(), com__seagate__kinetic__proto__command__security__init(), com__seagate__kinetic__proto__command__setup__init(), com__seagate__kinetic__proto__command__status__init(), com__seagate__kinetic__proto__message__hmacauth__init(), com__seagate__kinetic__proto__message__init(), com__seagate__kinetic__proto__message__pinauth__init(), KineticMessage::command, KineticMessage::getLog, KineticMessage::getLogDevice, KineticMessage::header, KineticMessage::hmacAuth, KineticMessage::keyRange, KineticMessage::keyValue, KINETIC_ASSERT, KineticMessage::message, KineticMessage::pinAuth, KineticMessage::pinOp, KineticMessage::security, KineticMessage::setup, and KineticMessage::status.
static void KineticMessage_HeaderInit (Com__Seagate__Kinetic__Proto__Command__Header *hdr, KineticSession const *constsession) [static]
Definition at line 415 of file kinetic_types_internal.c.
References com__seagate__kinetic__proto__command__header__descriptor, KINETIC_ASSERT, and KINETIC_SEQUENCE_NOT_YET_BOUND.
void KineticRequest_Init (KineticRequest *request, KineticSession const *constsession)
Definition at line 430 of file kinetic_types_internal.c.
References KINETIC_ASSERT, KineticMessage_HeaderInit(), and KineticMessage_Init().
Author
Generated automatically by Doxygen for kinetic-c from the source code.