.TH "KineticMessage" 3 "Wed Oct 15 2014" "Version v0.7.0" "protobuf-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticMessage \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_types_internal\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBKineticProto\fP \fBproto\fP"
.br
.ti -1c
.RI "KineticProto_Command \fBcommand\fP"
.br
.ti -1c
.RI "KineticProto_Header \fBheader\fP"
.br
.ti -1c
.RI "KineticProto_Body \fBbody\fP"
.br
.ti -1c
.RI "KineticProto_Status \fBstatus\fP"
.br
.ti -1c
.RI "KineticProto_Security \fBsecurity\fP"
.br
.ti -1c
.RI "KineticProto_Security_ACL \fBacl\fP"
.br
.ti -1c
.RI "KineticProto_KeyValue \fBkeyValue\fP"
.br
.ti -1c
.RI "uint8_t \fBhmacData\fP [\fBKINETIC_HMAC_MAX_LEN\fP]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 91 of file kinetic_types_internal\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBKineticProto\fP KineticMessage::proto"

.PP
Definition at line 93 of file kinetic_types_internal\&.h\&.
.SS "KineticProto_Command KineticMessage::command"

.PP
Definition at line 94 of file kinetic_types_internal\&.h\&.
.SS "KineticProto_Header KineticMessage::header"

.PP
Definition at line 95 of file kinetic_types_internal\&.h\&.
.SS "KineticProto_Body KineticMessage::body"

.PP
Definition at line 96 of file kinetic_types_internal\&.h\&.
.SS "KineticProto_Status KineticMessage::status"

.PP
Definition at line 97 of file kinetic_types_internal\&.h\&.
.SS "KineticProto_Security KineticMessage::security"

.PP
Definition at line 98 of file kinetic_types_internal\&.h\&.
.SS "KineticProto_Security_ACL KineticMessage::acl"

.PP
Definition at line 99 of file kinetic_types_internal\&.h\&.
.SS "KineticProto_KeyValue KineticMessage::keyValue"

.PP
Definition at line 100 of file kinetic_types_internal\&.h\&.
.SS "uint8_t KineticMessage::hmacData[\fBKINETIC_HMAC_MAX_LEN\fP]"

.PP
Definition at line 101 of file kinetic_types_internal\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for protobuf-c from the source code\&.
