kinetic_pdu.h
NAME
kinetic_pdu.h -
SYNOPSIS
#include 'kinetic_types.h'
#include 'kinetic_exchange.h'
#include 'kinetic_message.h'
#include 'kinetic_hmac.h'
Data Structures
struct KineticPDUHeader
struct KineticPDU
Macros
#define PDU_HEADER_LEN (1 + (2 * sizeof(int32_t)))
#define PDU_PROTO_MAX_LEN (1024 * 1024)
#define PDU_VALUE_MAX_LEN (1024 * 1024)
#define PDU_MAX_LEN (PDU_HEADER_LEN + PDU_PROTO_MAX_LEN + PDU_VALUE_MAX_LEN)
Functions
void KineticPDU_Init (KineticPDU *const pdu, KineticExchange *const exchange, KineticMessage *const message, uint8_t *const value, int32_t valueLength)
bool KineticPDU_Send (KineticPDU *const request)
bool KineticPDU_Receive (KineticPDU *const response)
Macro Definition Documentation
#define PDU_HEADER_LEN (1 + (2 * sizeof(int32_t)))
Definition at line 29 of file kinetic_pdu.h.
#define PDU_PROTO_MAX_LEN (1024 * 1024)
Definition at line 30 of file kinetic_pdu.h.
#define PDU_VALUE_MAX_LEN (1024 * 1024)
Definition at line 31 of file kinetic_pdu.h.
#define PDU_MAX_LEN (PDU_HEADER_LEN + PDU_PROTO_MAX_LEN + PDU_VALUE_MAX_LEN)
Definition at line 32 of file kinetic_pdu.h.
Function Documentation
void KineticPDU_Init (KineticPDU *constpdu, KineticExchange *constexchange, KineticMessage *constmessage, uint8_t *constvalue, int32_tvalueLength)
Definition at line 33 of file kinetic_pdu.c.
References KineticPDU::exchange, KineticMessage::header, KineticExchange_ConfigureHeader(), and KineticMessage::proto.
bool KineticPDU_Send (KineticPDU *constrequest)
Definition at line 63 of file kinetic_pdu.c.
References KineticExchange::connection, KineticPDU::exchange, KineticPDU::header, KineticPDU::hmac, KineticExchange::key, KineticExchange::keyLength, KINETIC_PROTO_SECURITY_ACL_HMACALGORITHM_HmacSHA1, KineticHMAC_Init(), KineticHMAC_Populate(), KineticProto_get_packed_size(), KineticSocket_Write(), KineticSocket_WriteProtobuf(), LOG, LOGF, KineticPDU::message, KineticMessage::proto, KineticPDUHeader::protobufLength, KineticPDU::protobufLength, KineticConnection::socketDescriptor, KineticPDU::value, KineticPDUHeader::valueLength, and KineticPDU::valueLength.
bool KineticPDU_Receive (KineticPDU *constresponse)
Definition at line 110 of file kinetic_pdu.c.
References KineticExchange::connection, KineticPDU::exchange, KineticPDU::header, KineticExchange::key, KineticExchange::keyLength, KineticHMAC_Validate(), KineticSocket_Read(), KineticSocket_ReadProtobuf(), LOG, LOGF, KineticPDU::proto, KineticPDUHeader::protobufLength, KineticPDU::protobufScratch, KineticPDU::rawHeader, KineticConnection::socketDescriptor, KineticPDU::value, KineticPDUHeader::valueLength, KineticPDU::valueLength, and KineticPDUHeader::versionPrefix.
Author
Generated automatically by Doxygen for protobuf-c from the source code.