.TH "kinetic_countingsemaphore.c" 3 "Fri Mar 13 2015" "Version v0.12.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kinetic_countingsemaphore.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'kinetic_countingsemaphore\&.h'\fP
.br
\fC#include 'kinetic_countingsemaphore_types\&.h'\fP
.br
\fC#include 'kinetic_logger\&.h'\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <assert\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "KineticCountingSemaphore * \fBKineticCountingSemaphore_Create\fP (uint32_t counts)"
.br
.ti -1c
.RI "void \fBKineticCountingSemaphore_Take\fP (KineticCountingSemaphore *const sem)"
.br
.ti -1c
.RI "void \fBKineticCountingSemaphore_Give\fP (KineticCountingSemaphore *const sem)"
.br
.ti -1c
.RI "void \fBKineticCountingSemaphore_Destroy\fP (KineticCountingSemaphore *const sem)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "KineticCountingSemaphore* KineticCountingSemaphore_Create (uint32_tcounts)"

.PP
Definition at line 26 of file kinetic_countingsemaphore\&.c\&.
.SS "void KineticCountingSemaphore_Take (KineticCountingSemaphore *constsem)"

.PP
Definition at line 38 of file kinetic_countingsemaphore\&.c\&.
.PP
References KINETIC_ASSERT, and LOGF3\&.
.SS "void KineticCountingSemaphore_Give (KineticCountingSemaphore *constsem)"

.PP
Definition at line 60 of file kinetic_countingsemaphore\&.c\&.
.PP
References KINETIC_ASSERT, and LOGF3\&.
.SS "void KineticCountingSemaphore_Destroy (KineticCountingSemaphore *constsem)"

.PP
Definition at line 79 of file kinetic_countingsemaphore\&.c\&.
.PP
References KINETIC_ASSERT\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
