.TH "KineticOperation" 3 "Wed Oct 15 2014" "Version v0.7.0" "protobuf-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticOperation \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_types_internal\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBKineticConnection\fP * \fBconnection\fP"
.br
.ti -1c
.RI "KineticPDU * \fBrequest\fP"
.br
.ti -1c
.RI "KineticPDU * \fBresponse\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 192 of file kinetic_types_internal\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBKineticConnection\fP* KineticOperation::connection"

.PP
Definition at line 193 of file kinetic_types_internal\&.h\&.
.SS "KineticPDU* KineticOperation::request"

.PP
Definition at line 194 of file kinetic_types_internal\&.h\&.
.SS "KineticPDU* KineticOperation::response"

.PP
Definition at line 195 of file kinetic_types_internal\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for protobuf-c from the source code\&.
