.TH "KineticDeviceInfo_Configuration" 3 "Thu Nov 13 2014" "Version v0.8.1-beta" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticDeviceInfo_Configuration \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBvendor\fP"
.br
.ti -1c
.RI "char * \fBmodel\fP"
.br
.ti -1c
.RI "\fBByteArray\fP \fBserialNumber\fP"
.br
.ti -1c
.RI "\fBByteArray\fP \fBworldWideName\fP"
.br
.ti -1c
.RI "char * \fBversion\fP"
.br
.ti -1c
.RI "char * \fBcompilationDate\fP"
.br
.ti -1c
.RI "char * \fBsourceHash\fP"
.br
.ti -1c
.RI "char * \fBprotocolVersion\fP"
.br
.ti -1c
.RI "char * \fBprotocolCompilationDate\fP"
.br
.ti -1c
.RI "char * \fBprotocolSourceHash\fP"
.br
.ti -1c
.RI "\fBKineticDeviceInfo_Interface\fP * \fBinterfaces\fP"
.br
.ti -1c
.RI "size_t \fBnumInterfaces\fP"
.br
.ti -1c
.RI "int32_t \fBport\fP"
.br
.ti -1c
.RI "int32_t \fBtlsPort\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 238 of file kinetic_types\&.h\&.
.SH "Field Documentation"
.PP 
.SS "char* KineticDeviceInfo_Configuration::vendor"

.PP
Definition at line 239 of file kinetic_types\&.h\&.
.SS "char* KineticDeviceInfo_Configuration::model"

.PP
Definition at line 240 of file kinetic_types\&.h\&.
.SS "\fBByteArray\fP KineticDeviceInfo_Configuration::serialNumber"

.PP
Definition at line 241 of file kinetic_types\&.h\&.
.SS "\fBByteArray\fP KineticDeviceInfo_Configuration::worldWideName"

.PP
Definition at line 242 of file kinetic_types\&.h\&.
.SS "char* KineticDeviceInfo_Configuration::version"

.PP
Definition at line 243 of file kinetic_types\&.h\&.
.SS "char* KineticDeviceInfo_Configuration::compilationDate"

.PP
Definition at line 244 of file kinetic_types\&.h\&.
.SS "char* KineticDeviceInfo_Configuration::sourceHash"

.PP
Definition at line 245 of file kinetic_types\&.h\&.
.SS "char* KineticDeviceInfo_Configuration::protocolVersion"

.PP
Definition at line 246 of file kinetic_types\&.h\&.
.SS "char* KineticDeviceInfo_Configuration::protocolCompilationDate"

.PP
Definition at line 247 of file kinetic_types\&.h\&.
.SS "char* KineticDeviceInfo_Configuration::protocolSourceHash"

.PP
Definition at line 248 of file kinetic_types\&.h\&.
.SS "\fBKineticDeviceInfo_Interface\fP* KineticDeviceInfo_Configuration::interfaces"

.PP
Definition at line 249 of file kinetic_types\&.h\&.
.SS "size_t KineticDeviceInfo_Configuration::numInterfaces"

.PP
Definition at line 250 of file kinetic_types\&.h\&.
.SS "int32_t KineticDeviceInfo_Configuration::port"

.PP
Definition at line 251 of file kinetic_types\&.h\&.
.SS "int32_t KineticDeviceInfo_Configuration::tlsPort"

.PP
Definition at line 252 of file kinetic_types\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
