kinetic_session.c
NAME
kinetic_session.c -
SYNOPSIS
#include 'kinetic_session.h'
#include 'kinetic_types_internal.h'
#include 'kinetic_controller.h'
#include 'kinetic_socket.h'
#include 'kinetic_response.h'
#include 'kinetic_operation.h'
#include 'kinetic_allocator.h'
#include 'kinetic_resourcewaiter.h'
#include 'kinetic_logger.h'
#include <stdlib.h>
#include <string.h>
#include <pthread.h>
#include <errno.h>
#include <sys/time.h>
Macros
#define ATOMIC_FETCH_AND_INCREMENT(P) __sync_fetch_and_add(P, 1)
Functions
KineticStatus KineticSession_Create (KineticSession *const session, KineticClient *const client)
KineticStatus KineticSession_Destroy (KineticSession *const session)
KineticStatus KineticSession_Connect (KineticSession *const session)
KineticStatus KineticSession_Disconnect (KineticSession *const session)
KineticStatus KineticSession_GetTerminationStatus (KineticSession const *const session)
void KineticSession_SetTerminationStatus (KineticSession *const session, KineticStatus status)
int64_t KineticSession_GetNextSequenceCount (KineticSession *const session)
int64_t KineticSession_GetClusterVersion (KineticSession const *const session)
void KineticSession_SetClusterVersion (KineticSession *const session, int64_t cluster_version)
int64_t KineticSession_GetConnectionID (KineticSession const *const session)
void KineticSession_SetConnectionID (KineticSession *const session, int64_t id)
Macro Definition Documentation
#define ATOMIC_FETCH_AND_INCREMENT(P) __sync_fetch_and_add(P, 1)
Definition at line 165 of file kinetic_session.c.
Function Documentation
KineticStatus KineticSession_Create (KineticSession *constsession, KineticClient *constclient)
Definition at line 37 of file kinetic_session.c.
References KINETIC_MAX_OUTSTANDING_OPERATIONS_PER_SESSION, KINETIC_SOCKET_INVALID, KINETIC_STATUS_MEMORY_ERROR, KINETIC_STATUS_SESSION_EMPTY, KINETIC_STATUS_SUCCESS, KineticCountingSemaphore_Create(), and LOG0.
KineticStatus KineticSession_Destroy (KineticSession *constsession)
Definition at line 68 of file kinetic_session.c.
References KINETIC_STATUS_SESSION_EMPTY, KINETIC_STATUS_SUCCESS, KineticAllocator_FreeSession(), and KineticCountingSemaphore_Destroy().
KineticStatus KineticSession_Connect (KineticSession *constsession)
Definition at line 79 of file kinetic_session.c.
References Bus_RegisterSocket(), BUS_SOCKET_PLAIN, BUS_SOCKET_SSL, KINETIC_ASSERT, KINETIC_CONNECTION_TIMEOUT_SECS, KINETIC_SOCKET_DESCRIPTOR_INVALID, KINETIC_STATUS_CONNECTION_ERROR, KINETIC_STATUS_MEMORY_ERROR, KINETIC_STATUS_SESSION_EMPTY, KINETIC_STATUS_SUCCESS, KineticResourceWaiter_WaitTilAvailable(), KineticSession_GetConnectionID(), KineticSocket_Close(), KineticSocket_Connect(), LOG0, LOGF1, and PDU_PROTO_MAX_LEN.
KineticStatus KineticSession_Disconnect (KineticSession *constsession)
Definition at line 131 of file kinetic_session.c.
References Bus_ReleaseSocket(), KINETIC_SOCKET_INVALID, KINETIC_STATUS_CONNECTION_ERROR, KINETIC_STATUS_SESSION_EMPTY, and KINETIC_STATUS_SUCCESS.
KineticStatus KineticSession_GetTerminationStatus (KineticSession const *constsession)
Definition at line 151 of file kinetic_session.c.
References KINETIC_STATUS_SESSION_INVALID.
void KineticSession_SetTerminationStatus (KineticSession *constsession, KineticStatusstatus)
Definition at line 159 of file kinetic_session.c.
References KINETIC_ASSERT.
int64_t KineticSession_GetNextSequenceCount (KineticSession *constsession)
Definition at line 167 of file kinetic_session.c.
References ATOMIC_FETCH_AND_INCREMENT, and KINETIC_ASSERT.
int64_t KineticSession_GetClusterVersion (KineticSession const *constsession)
Definition at line 174 of file kinetic_session.c.
References KINETIC_ASSERT.
void KineticSession_SetClusterVersion (KineticSession *constsession, int64_tcluster_version)
Definition at line 180 of file kinetic_session.c.
References KINETIC_ASSERT.
int64_t KineticSession_GetConnectionID (KineticSession const *constsession)
Definition at line 186 of file kinetic_session.c.
References KINETIC_ASSERT.
void KineticSession_SetConnectionID (KineticSession *constsession, int64_tid)
Definition at line 192 of file kinetic_session.c.
References KINETIC_ASSERT.
Author
Generated automatically by Doxygen for kinetic-c from the source code.