.TH "KineticList" 3 "Tue Dec 9 2014" "Version v0.9.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticList \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_types_internal\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "KineticListItem * \fBstart\fP"
.br
.ti -1c
.RI "pthread_mutex_t \fBmutex\fP"
.br
.ti -1c
.RI "bool \fBlocked\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 66 of file kinetic_types_internal\&.h\&.
.SH "Field Documentation"
.PP 
.SS "KineticListItem* KineticList::start"

.PP
Definition at line 67 of file kinetic_types_internal\&.h\&.
.SS "pthread_mutex_t KineticList::mutex"

.PP
Definition at line 68 of file kinetic_types_internal\&.h\&.
.SS "bool KineticList::locked"

.PP
Definition at line 69 of file kinetic_types_internal\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
