.TH "kinetic_socket.h" 3 "Tue Mar 3 2015" "Version v0.12.0-beta" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kinetic_socket.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'kinetic_types_internal\&.h'\fP
.br
\fC#include 'kinetic_message\&.h'\fP
.br

.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBKineticWaitStatus\fP "
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBKineticSocket_Connect\fP (const char *host, int port)"
.br
.ti -1c
.RI "void \fBKineticSocket_Close\fP (int socket)"
.br
.ti -1c
.RI "void \fBKineticSocket_BeginPacket\fP (int socket)"
.br
.ti -1c
.RI "void \fBKineticSocket_FinishPacket\fP (int socket)"
.br
.ti -1c
.RI "void \fBKineticSocket_EnableTCPNoDelay\fP (int socket)"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBKineticWaitStatus\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIKINETIC_WAIT_STATUS_DATA_AVAILABLE \fP\fP
.TP
\fB\fIKINETIC_WAIT_STATUS_TIMED_OUT \fP\fP
.TP
\fB\fIKINETIC_WAIT_STATUS_RETRYABLE_ERROR \fP\fP
.TP
\fB\fIKINETIC_WAIT_STATUS_FATAL_ERROR \fP\fP
.PP
Definition at line 27 of file kinetic_socket\&.h\&.
.SH "Function Documentation"
.PP 
.SS "int KineticSocket_Connect (const char *host, intport)"

.PP
Definition at line 47 of file kinetic_socket\&.c\&.
.PP
References KINETIC_OBJ_SIZE, KINETIC_SOCKET_DESCRIPTOR_INVALID, KineticSocket_EnableTCPNoDelay(), LOG0, LOGF0, and LOGF1\&.
.SS "void KineticSocket_Close (intsocket)"

.PP
Definition at line 138 of file kinetic_socket\&.c\&.
.PP
References LOG1, LOG2, and LOGF0\&.
.SS "void KineticSocket_BeginPacket (intsocket)"

.PP
Definition at line 162 of file kinetic_socket\&.c\&.
.SS "void KineticSocket_FinishPacket (intsocket)"

.PP
Definition at line 172 of file kinetic_socket\&.c\&.
.SS "void KineticSocket_EnableTCPNoDelay (intsocket)"

.PP
Definition at line 156 of file kinetic_socket\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
