.TH "kinetic_allocator.h" 3 "Thu Nov 13 2014" "Version v0.8.1-beta" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kinetic_allocator.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'kinetic_types_internal\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBKineticAllocator_InitLists\fP (KineticConnection *connection)"
.br
.ti -1c
.RI "KineticPDU * \fBKineticAllocator_NewPDU\fP (KineticConnection *connection)"
.br
.ti -1c
.RI "void \fBKineticAllocator_FreePDU\fP (KineticConnection *connection, KineticPDU *pdu)"
.br
.ti -1c
.RI "KineticPDU * \fBKineticAllocator_GetFirstPDU\fP (KineticConnection *connection)"
.br
.ti -1c
.RI "KineticPDU * \fBKineticAllocator_GetNextPDU\fP (KineticConnection *connection, KineticPDU *pdu)"
.br
.ti -1c
.RI "void \fBKineticAllocator_FreeAllPDUs\fP (KineticConnection *connection)"
.br
.ti -1c
.RI "KineticOperation * \fBKineticAllocator_NewOperation\fP (KineticConnection *connection)"
.br
.ti -1c
.RI "void \fBKineticAllocator_FreeOperation\fP (KineticConnection *connection, KineticOperation *operation)"
.br
.ti -1c
.RI "KineticOperation * \fBKineticAllocator_GetFirstOperation\fP (KineticConnection *connection)"
.br
.ti -1c
.RI "KineticOperation * \fBKineticAllocator_GetNextOperation\fP (KineticConnection *connection, KineticOperation *operation)"
.br
.ti -1c
.RI "void \fBKineticAllocator_FreeAllOperations\fP (KineticConnection *connection)"
.br
.ti -1c
.RI "bool \fBKineticAllocator_ValidateAllMemoryFreed\fP (KineticConnection *connection)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void KineticAllocator_InitLists (KineticConnection *connection)"

.PP
Definition at line 44 of file kinetic_allocator\&.c\&.
.PP
References KINETIC_LIST_INITIALIZER\&.
.SS "KineticPDU* KineticAllocator_NewPDU (KineticConnection *connection)"

.PP
Definition at line 221 of file kinetic_allocator\&.c\&.
.PP
References KINETIC_PDU_INIT, LOG0, and LOGF3\&.
.SS "void KineticAllocator_FreePDU (KineticConnection *connection, KineticPDU *pdu)"

.PP
Definition at line 237 of file kinetic_allocator\&.c\&.
.PP
References KINETIC_LIST_LOCK, KINETIC_LIST_UNLOCK, KineticProto_Message__free_unpacked(), LOG3, and LOGF3\&.
.SS "KineticPDU* KineticAllocator_GetFirstPDU (KineticConnection *connection)"

.PP
Definition at line 250 of file kinetic_allocator\&.c\&.
.SS "KineticPDU* KineticAllocator_GetNextPDU (KineticConnection *connection, KineticPDU *pdu)"

.PP
Definition at line 256 of file kinetic_allocator\&.c\&.
.SS "void KineticAllocator_FreeAllPDUs (KineticConnection *connection)"

.PP
Definition at line 262 of file kinetic_allocator\&.c\&.
.PP
References KINETIC_LIST_LOCK, KINETIC_LIST_UNLOCK, KineticProto_Message__free_unpacked(), LOG1, and LOG3\&.
.SS "KineticOperation* KineticAllocator_NewOperation (KineticConnection *connection)"

.PP
Definition at line 290 of file kinetic_allocator\&.c\&.
.PP
References KINETIC_OPERATION_INIT, KINETIC_PDU_INIT_WITH_COMMAND, KineticAllocator_NewPDU(), LOGF0, and LOGF3\&.
.SS "void KineticAllocator_FreeOperation (KineticConnection *connection, KineticOperation *operation)"

.PP
Definition at line 307 of file kinetic_allocator\&.c\&.
.PP
References KineticAllocator_FreePDU(), and LOGF3\&.
.SS "KineticOperation* KineticAllocator_GetFirstOperation (KineticConnection *connection)"

.PP
Definition at line 327 of file kinetic_allocator\&.c\&.
.SS "KineticOperation* KineticAllocator_GetNextOperation (KineticConnection *connection, KineticOperation *operation)"

.PP
Definition at line 333 of file kinetic_allocator\&.c\&.
.SS "void KineticAllocator_FreeAllOperations (KineticConnection *connection)"

.PP
Definition at line 339 of file kinetic_allocator\&.c\&.
.PP
References KineticAllocator_FreePDU(), LOG1, and LOGF3\&.
.SS "bool KineticAllocator_ValidateAllMemoryFreed (KineticConnection *connection)"

.PP
Definition at line 372 of file kinetic_allocator\&.c\&.
.PP
References BOOL_TO_STRING, and LOGF3\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
