.TH "KineticDeviceInfo" 3 "Thu Nov 13 2014" "Version v0.8.1-beta" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticDeviceInfo \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "size_t \fBtotalLength\fP"
.br
.ti -1c
.RI "\fBKineticDeviceInfo_Utilization\fP * \fButilizations\fP"
.br
.ti -1c
.RI "size_t \fBnumUtilizations\fP"
.br
.ti -1c
.RI "\fBKineticDeviceInfo_Temperature\fP * \fBtemperatures\fP"
.br
.ti -1c
.RI "size_t \fBnumTemperatures\fP"
.br
.ti -1c
.RI "\fBKineticDeviceInfo_Capacity\fP * \fBcapacity\fP"
.br
.ti -1c
.RI "\fBKineticDeviceInfo_Configuration\fP * \fBconfiguration\fP"
.br
.ti -1c
.RI "\fBKineticDeviceInfo_Statistics\fP * \fBstatistics\fP"
.br
.ti -1c
.RI "size_t \fBnumStatistics\fP"
.br
.ti -1c
.RI "\fBByteArray\fP \fBmessages\fP"
.br
.ti -1c
.RI "\fBKineticDeviceInfo_Limits\fP * \fBlimits\fP"
.br
.ti -1c
.RI "\fBKineticDeviceInfo_Device\fP * \fBdevice\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 310 of file kinetic_types\&.h\&.
.SH "Field Documentation"
.PP 
.SS "size_t KineticDeviceInfo::totalLength"

.PP
Definition at line 311 of file kinetic_types\&.h\&.
.SS "\fBKineticDeviceInfo_Utilization\fP* KineticDeviceInfo::utilizations"

.PP
Definition at line 312 of file kinetic_types\&.h\&.
.SS "size_t KineticDeviceInfo::numUtilizations"

.PP
Definition at line 313 of file kinetic_types\&.h\&.
.SS "\fBKineticDeviceInfo_Temperature\fP* KineticDeviceInfo::temperatures"

.PP
Definition at line 314 of file kinetic_types\&.h\&.
.SS "size_t KineticDeviceInfo::numTemperatures"

.PP
Definition at line 315 of file kinetic_types\&.h\&.
.SS "\fBKineticDeviceInfo_Capacity\fP* KineticDeviceInfo::capacity"

.PP
Definition at line 316 of file kinetic_types\&.h\&.
.SS "\fBKineticDeviceInfo_Configuration\fP* KineticDeviceInfo::configuration"

.PP
Definition at line 317 of file kinetic_types\&.h\&.
.SS "\fBKineticDeviceInfo_Statistics\fP* KineticDeviceInfo::statistics"

.PP
Definition at line 318 of file kinetic_types\&.h\&.
.SS "size_t KineticDeviceInfo::numStatistics"

.PP
Definition at line 319 of file kinetic_types\&.h\&.
.SS "\fBByteArray\fP KineticDeviceInfo::messages"

.PP
Definition at line 320 of file kinetic_types\&.h\&.
.SS "\fBKineticDeviceInfo_Limits\fP* KineticDeviceInfo::limits"

.PP
Definition at line 321 of file kinetic_types\&.h\&.
.SS "\fBKineticDeviceInfo_Device\fP* KineticDeviceInfo::device"

.PP
Definition at line 322 of file kinetic_types\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
