.TH "kinetic_connection.h" 3 "Wed Sep 10 2014" "Version v0.6.0-beta" "protobuf-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kinetic_connection.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'kinetic_types_internal\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBKineticConnection_Connect\fP (\fBKineticConnection\fP *connection, const char *host, int port, bool nonBlocking, int64_t clusterVersion, int64_t identity, const \fBByteArray\fP key)"
.br
.ti -1c
.RI "void \fBKineticConnection_Disconnect\fP (\fBKineticConnection\fP *const connection)"
.br
.ti -1c
.RI "void \fBKineticConnection_IncrementSequence\fP (\fBKineticConnection\fP *const connection)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool KineticConnection_Connect (\fBKineticConnection\fP *connection, const char *host, intport, boolnonBlocking, int64_tclusterVersion, int64_tidentity, const \fBByteArray\fPkey)"

.PP
Definition at line 25 of file kinetic_connection\&.c\&.
.PP
References KineticConnection::clusterVersion, KineticConnection::connected, KineticConnection::host, KineticConnection::identity, KineticConnection::key, KineticConnection::keyData, KineticSocket_Connect(), KineticConnection::nonBlocking, KineticConnection::port, and KineticConnection::socketDescriptor\&.
.SS "void KineticConnection_Disconnect (\fBKineticConnection\fP *constconnection)"

.PP
Definition at line 48 of file kinetic_connection\&.c\&.
.PP
References KineticConnection::socketDescriptor\&.
.SS "void KineticConnection_IncrementSequence (\fBKineticConnection\fP *constconnection)"

.PP
Definition at line 57 of file kinetic_connection\&.c\&.
.PP
References KineticConnection::sequence\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for protobuf-c from the source code\&.
