.TH "kinetic_controller.h" 3 "Thu Dec 11 2014" "Version v0.9.1" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kinetic_controller.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'kinetic_types_internal\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBKineticStatus\fP \fBKineticController_Init\fP (\fBKineticSession\fP const *const session)"
.br
.ti -1c
.RI "KineticOperation * \fBKineticController_CreateOperation\fP (\fBKineticSession\fP const *const session)"
.br
.ti -1c
.RI "\fBKineticStatus\fP \fBKineticController_ExecuteOperation\fP (KineticOperation *operation, \fBKineticCompletionClosure\fP *closure)"
.br
.ti -1c
.RI "void \fBKineticController_Pause\fP (\fBKineticSession\fP const *const session, bool pause)"
.br
.ti -1c
.RI "void * \fBKineticController_ReceiveThread\fP (void *thread_arg)"
.br
.ti -1c
.RI "void \fBKineticController_HandleIncomingPDU\fP (KineticConnection *const connection)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBKineticStatus\fP KineticController_Init (\fBKineticSession\fP const *constsession)"

.PP
Definition at line 30 of file kinetic_controller\&.c\&.
.PP
References KineticSession::connection, Kinetic_GetErrnoDescription(), KINETIC_STATUS_CONNECTION_ERROR, KINETIC_STATUS_SUCCESS, KineticController_ReceiveThread(), LOGF0, KineticConnection::thread, and KineticConnection::threadID\&.
.SS "KineticOperation* KineticController_CreateOperation (\fBKineticSession\fP const *constsession)"

.PP
Definition at line 50 of file kinetic_controller\&.c\&.
.PP
References KineticSession::connection, KineticAllocator_NewOperation(), LOG0, and LOGF1\&.
.SS "\fBKineticStatus\fP KineticController_ExecuteOperation (KineticOperation *operation, \fBKineticCompletionClosure\fP *closure)"

.PP
Definition at line 95 of file kinetic_controller\&.c\&.
.PP
References KINETIC_STATUS_INVALID, KINETIC_STATUS_SUCCESS, KineticOperation_SendRequest(), and LOGF1\&.
.SS "void KineticController_Pause (\fBKineticSession\fP const *constsession, boolpause)"

.PP
Definition at line 143 of file kinetic_controller\&.c\&.
.PP
References KineticSession::connection, KineticThread::paused, and KineticConnection::thread\&.
.SS "void* KineticController_ReceiveThread (void *thread_arg)"

.PP
Definition at line 251 of file kinetic_controller\&.c\&.
.PP
References KineticThread::abortRequested, KineticThread::connection, KineticThread::fatalError, KINETIC_STATUS_SUCCESS, LOG3, and KineticThread::paused\&.
.SS "void KineticController_HandleIncomingPDU (KineticConnection *constconnection)"

.PP
Definition at line 150 of file kinetic_controller\&.c\&.
.PP
References Kinetic_GetStatusDescription(), KINETIC_PDU_TYPE_RESPONSE, KINETIC_PDU_TYPE_UNSOLICITED, KINETIC_PROTO_MESSAGE_AUTH_TYPE_UNSOLICITEDSTATUS, KINETIC_STATUS_SUCCESS, KineticAllocator_FreePDU(), KineticAllocator_NewPDU(), KineticOperation_AssociateResponseWithOperation(), KineticOperation_Complete(), KineticPDU_GetStatus(), KineticPDU_GetValueLength(), KineticPDU_ReceiveMain(), KineticPDU_ReceiveValue(), LOG0, LOG2, LOGF0, and LOGF2\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
