.TH "KineticPDU" 3 "Wed Sep 10 2014" "Version v0.6.0-beta" "protobuf-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticPDU \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBKineticPDUHeader\fP \fBheader\fP"
.br
.ti -1c
.RI "\fBKineticPDUHeader\fP \fBheaderNBO\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fBKineticProto\fP \fBprotoBase\fP"
.br
.ti -1c
.RI "   \fBKineticMessage\fP \fBmessage\fP"
.br
.ti -1c
.RI "   uint8_t \fBbuffer\fP [((1024 *1024)*2)]"
.br
.ti -1c
.RI "} \fBprotoData\fP"
.br
.ti -1c
.RI "\fBKineticProto\fP * \fBproto\fP"
.br
.ti -1c
.RI "uint8_t \fBprotobufRaw\fP [(1024 *1024)]"
.br
.ti -1c
.RI "\fBKineticKeyValue\fP * \fBmetadata\fP"
.br
.ti -1c
.RI "uint8_t \fBvalueBuffer\fP [(1024 *1024)]"
.br
.ti -1c
.RI "\fBByteArray\fP \fBvalue\fP"
.br
.ti -1c
.RI "\fBKineticHMAC\fP \fBhmac\fP"
.br
.ti -1c
.RI "\fBKineticConnection\fP * \fBconnection\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 255 of file kinetic_types\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBKineticPDUHeader\fP KineticPDU::header"

.PP
Definition at line 258 of file kinetic_types\&.h\&.
.SS "\fBKineticPDUHeader\fP KineticPDU::headerNBO"

.PP
Definition at line 259 of file kinetic_types\&.h\&.
.SS "\fBKineticProto\fP KineticPDU::protoBase"

.PP
Definition at line 263 of file kinetic_types\&.h\&.
.SS "\fBKineticMessage\fP KineticPDU::message"

.PP
Definition at line 266 of file kinetic_types\&.h\&.
.SS "uint8_t KineticPDU::buffer[((1024 *1024)*2)]"

.PP
Definition at line 269 of file kinetic_types\&.h\&.
.SS "union { \&.\&.\&. }   KineticPDU::protoData"

.SS "\fBKineticProto\fP* KineticPDU::proto"

.PP
Definition at line 271 of file kinetic_types\&.h\&.
.SS "uint8_t KineticPDU::protobufRaw[(1024 *1024)]"

.PP
Definition at line 273 of file kinetic_types\&.h\&.
.SS "\fBKineticKeyValue\fP* KineticPDU::metadata"

.PP
Definition at line 276 of file kinetic_types\&.h\&.
.SS "uint8_t KineticPDU::valueBuffer[(1024 *1024)]"

.PP
Definition at line 279 of file kinetic_types\&.h\&.
.SS "\fBByteArray\fP KineticPDU::value"

.PP
Definition at line 280 of file kinetic_types\&.h\&.
.SS "\fBKineticHMAC\fP KineticPDU::hmac"

.PP
Definition at line 283 of file kinetic_types\&.h\&.
.SS "\fBKineticConnection\fP* KineticPDU::connection"

.PP
Definition at line 286 of file kinetic_types\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for protobuf-c from the source code\&.
