kinetic_pdu.c
NAME
kinetic_pdu.c -
SYNOPSIS
#include 'kinetic_pdu.h'
#include 'kinetic_nbo.h'
#include 'kinetic_connection.h'
#include 'kinetic_socket.h'
#include 'kinetic_hmac.h'
#include 'kinetic_logger.h'
#include 'kinetic_proto.h'
Functions
void KineticPDU_Init (KineticPDU *const pdu, KineticConnection *const connection)
void KineticPDU_AttachValuePayload (KineticPDU *const pdu, ByteArray payload)
void KineticPDU_EnableValueBuffer (KineticPDU *const pdu)
void KineticPDU_EnableValueBufferWithLength (KineticPDU *const pdu, size_t length)
KineticProto_Status_StatusCode KineticPDU_Status (KineticPDU *const pdu)
bool KineticPDU_Send (KineticPDU *request)
bool KineticPDU_Receive (KineticPDU *const response)
Function Documentation
void KineticPDU_Init (KineticPDU *constpdu, KineticConnection *constconnection)
Definition at line 29 of file kinetic_pdu.c.
References KINETIC_PDU_INIT.
void KineticPDU_AttachValuePayload (KineticPDU *constpdu, ByteArraypayload)
Definition at line 35 of file kinetic_pdu.c.
References KineticPDU::header, KineticPDU::headerNBO, KineticNBO_FromHostU32(), and KineticPDU::value.
void KineticPDU_EnableValueBuffer (KineticPDU *constpdu)
Definition at line 44 of file kinetic_pdu.c.
References KineticPDU::value, and KineticPDU::valueBuffer.
void KineticPDU_EnableValueBufferWithLength (KineticPDU *constpdu, size_tlength)
Definition at line 50 of file kinetic_pdu.c.
References KineticPDU::header, KineticPDU::headerNBO, KineticNBO_FromHostU32(), KineticPDU::value, and KineticPDU::valueBuffer.
KineticProto_Status_StatusCode KineticPDU_Status (KineticPDU *constpdu)
Definition at line 60 of file kinetic_pdu.c.
References KINETIC_PROTO_STATUS_STATUS_CODE_INVALID_STATUS_CODE, and KineticPDU::proto.
bool KineticPDU_Send (KineticPDU *request)
Definition at line 75 of file kinetic_pdu.c.
References KineticPDU::connection, KineticPDU::header, KineticPDU::headerNBO, KineticPDU::hmac, KineticConnection::key, KINETIC_PROTO_SECURITY_ACL_HMACALGORITHM_HmacSHA1, KineticHMAC_Init(), KineticHMAC_Populate(), KineticLogger_LogHeader(), KineticLogger_LogProtobuf(), KineticNBO_FromHostU32(), KineticPDUHeader, KineticProto__get_packed_size(), KineticSocket_Write(), KineticSocket_WriteProtobuf(), LOG, LOGF, KineticPDU::message, KineticMessage::proto, KineticPDU::protoData, KineticConnection::socketDescriptor, and KineticPDU::value.
bool KineticPDU_Receive (KineticPDU *constresponse)
Definition at line 138 of file kinetic_pdu.c.
References KineticMessage::command, KineticPDU::connection, KineticPDU::header, KineticPDU::headerNBO, KineticConnection::key, KINETIC_PROTO_STATUS_STATUS_CODE_DATA_ERROR, KineticHMAC_Validate(), KineticLogger_LogByteArray(), KineticLogger_LogHeader(), KineticLogger_LogProtobuf(), KineticNBO_ToHostU32(), KineticPDUHeader, KineticSocket_Read(), KineticSocket_ReadProtobuf(), LOG, LOGF, KineticPDU::message, KineticMessage::proto, KineticPDU::proto, KineticPDU::protoData, KineticConnection::socketDescriptor, KineticMessage::status, and KineticPDU::value.
Author
Generated automatically by Doxygen for protobuf-c from the source code.