.TH "kinetic_connection.c" 3 "Thu Dec 11 2014" "Version v0.9.1" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kinetic_connection.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'kinetic_connection\&.h'\fP
.br
\fC#include 'kinetic_types_internal\&.h'\fP
.br
\fC#include 'kinetic_controller\&.h'\fP
.br
\fC#include 'kinetic_socket\&.h'\fP
.br
\fC#include 'kinetic_pdu\&.h'\fP
.br
\fC#include 'kinetic_operation\&.h'\fP
.br
\fC#include 'kinetic_allocator\&.h'\fP
.br
\fC#include 'kinetic_logger\&.h'\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <pthread\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include <sys/time\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBKineticStatus\fP \fBKineticSession_Create\fP (\fBKineticSession\fP *const session)"
.br
.ti -1c
.RI "\fBKineticStatus\fP \fBKineticSession_Destroy\fP (\fBKineticSession\fP *const session)"
.br
.ti -1c
.RI "\fBKineticStatus\fP \fBKineticSession_Connect\fP (\fBKineticSession\fP const *const session)"
.br
.ti -1c
.RI "\fBKineticStatus\fP \fBKineticSession_Disconnect\fP (\fBKineticSession\fP const *const session)"
.br
.ti -1c
.RI "void \fBKineticSession_IncrementSequence\fP (\fBKineticSession\fP const *const session)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBKineticStatus\fP KineticSession_Create (\fBKineticSession\fP *constsession)"

.PP
Definition at line 36 of file kinetic_connection\&.c\&.
.PP
References KineticSession::connection, KINETIC_CONNECTION_INIT, KINETIC_STATUS_MEMORY_ERROR, KINETIC_STATUS_SESSION_EMPTY, KINETIC_STATUS_SUCCESS, KineticAllocator_NewConnection(), and KineticConnection::session\&.
.SS "\fBKineticStatus\fP KineticSession_Destroy (\fBKineticSession\fP *constsession)"

.PP
Definition at line 52 of file kinetic_connection\&.c\&.
.PP
References KineticSession::connection, KINETIC_STATUS_SESSION_EMPTY, KINETIC_STATUS_SESSION_INVALID, KINETIC_STATUS_SUCCESS, KineticAllocator_FreeConnection(), and KineticConnection::writeMutex\&.
.SS "\fBKineticStatus\fP KineticSession_Connect (\fBKineticSession\fP const *constsession)"

.PP
Definition at line 66 of file kinetic_connection\&.c\&.
.PP
References KineticSession::config, KineticThread::connection, KineticSession::connection, KineticSessionConfig::host, KINETIC_SOCKET_DESCRIPTOR_INVALID, KINETIC_STATUS_CONNECTION_ERROR, KINETIC_STATUS_SESSION_EMPTY, KINETIC_STATUS_SOCKET_TIMEOUT, KINETIC_STATUS_SUCCESS, KineticController_Init(), KineticSocket_Connect(), LOG0, KineticSessionConfig::port, and KineticConnection::thread\&.
.SS "\fBKineticStatus\fP KineticSession_Disconnect (\fBKineticSession\fP const *constsession)"

.PP
Definition at line 112 of file kinetic_connection\&.c\&.
.PP
References KineticConnection::connected, KineticSession::connection, Kinetic_GetErrnoDescription(), KINETIC_HANDLE_INVALID, KINETIC_STATUS_CONNECTION_ERROR, KINETIC_STATUS_SESSION_EMPTY, KINETIC_STATUS_SUCCESS, LOG3, and LOGF0\&.
.SS "void KineticSession_IncrementSequence (\fBKineticSession\fP const *constsession)"

.PP
Definition at line 142 of file kinetic_connection\&.c\&.
.PP
References KineticSession::connection, and KineticConnection::sequence\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
