.TH "KineticP2P_OperationData" 3 "Thu Dec 11 2014" "Version v0.9.1" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticP2P_OperationData \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBByteBuffer\fP \fBkey\fP"
.br
.ti -1c
.RI "\fBByteBuffer\fP \fBversion\fP"
.br
.ti -1c
.RI "\fBByteBuffer\fP \fBnewKey\fP"
.br
.ti -1c
.RI "\fBKineticStatus\fP \fBresultStatus\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 342 of file kinetic_types\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBByteBuffer\fP KineticP2P_OperationData::key"

.PP
Definition at line 343 of file kinetic_types\&.h\&.
.SS "\fBByteBuffer\fP KineticP2P_OperationData::version"

.PP
Definition at line 344 of file kinetic_types\&.h\&.
.SS "\fBByteBuffer\fP KineticP2P_OperationData::newKey"

.PP
Definition at line 345 of file kinetic_types\&.h\&.
.SS "\fBKineticStatus\fP KineticP2P_OperationData::resultStatus"

.PP
Definition at line 346 of file kinetic_types\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
