kinetic_operation.h
NAME
kinetic_operation.h -
SYNOPSIS
#include 'kinetic_types_internal.h'
Enumerations
enum KineticOperation_NonstandardTimeout
Functions
KineticStatus KineticOperation_SendRequest (KineticOperation *const operation)
KineticStatus KineticOperation_GetStatus (const KineticOperation *const operation)
void KineticOperation_Complete (KineticOperation *operation, KineticStatus status)
KineticStatus KineticOperation_NoopCallback (KineticOperation *const operation, KineticStatus const status)
void KineticOperation_BuildNoop (KineticOperation *operation)
KineticStatus KineticOperation_PutCallback (KineticOperation *const operation, KineticStatus const status)
KineticStatus KineticOperation_BuildPut (KineticOperation *const operation, KineticEntry *const entry)
KineticStatus KineticOperation_GetCallback (KineticOperation *const operation, KineticStatus const status)
void KineticOperation_BuildGet (KineticOperation *const operation, KineticEntry *const entry)
void KineticOperation_BuildGetNext (KineticOperation *const operation, KineticEntry *const entry)
void KineticOperation_BuildGetPrevious (KineticOperation *const operation, KineticEntry *const entry)
KineticStatus KineticOperation_FlushCallback (KineticOperation *const operation, KineticStatus const status)
void KineticOperation_BuildFlush (KineticOperation *const operation)
KineticStatus KineticOperation_DeleteCallback (KineticOperation *const operation, KineticStatus const status)
void KineticOperation_BuildDelete (KineticOperation *const operation, KineticEntry *const entry)
KineticStatus KineticOperation_GetKeyRangeCallback (KineticOperation *const operation, KineticStatus const status)
void KineticOperation_BuildGetKeyRange (KineticOperation *const operation, KineticKeyRange *range, ByteBufferArray *buffers)
KineticStatus KineticOperation_P2POperationCallback (KineticOperation *const operation, KineticStatus const status)
KineticStatus KineticOperation_BuildP2POperation (KineticOperation *const operation, KineticP2P_Operation *const p2pOp)
KineticStatus KineticOperation_SetPinCallback (KineticOperation *const operation, KineticStatus const status)
void KineticOperation_BuildSetPin (KineticOperation *const operation, ByteArray old_pin, ByteArray new_pin, bool lock)
KineticStatus KineticOperation_EraseCallback (KineticOperation *const operation, KineticStatus const status)
void KineticOperation_BuildErase (KineticOperation *const operation, bool secure_erase, ByteArray *pin)
KineticStatus KineticOperation_LockUnlockCallback (KineticOperation *const operation, KineticStatus const status)
void KineticOperation_BuildLockUnlock (KineticOperation *const operation, bool lock, ByteArray *pin)
KineticStatus KineticOperation_GetLogCallback (KineticOperation *const operation, KineticStatus const status)
void KineticOperation_BuildGetLog (KineticOperation *const operation, KineticLogInfo_Type type, KineticLogInfo **info)
KineticStatus KineticOperation_SetACLCallback (KineticOperation *const operation, KineticStatus const status)
void KineticOperation_BuildSetACL (KineticOperation *const operation, struct ACL *ACLs)
KineticStatus KineticOperation_SetClusterVersionCallback (KineticOperation *const operation, KineticStatus const status)
void KineticOperation_BuildSetClusterVersion (KineticOperation *const operation, int64_t new_cluster_version)
KineticStatus KineticOperation_UpdateFirmwareCallback (KineticOperation *const operation, KineticStatus const status)
KineticStatus KineticOperation_BuildUpdateFirmware (KineticOperation *const operation, const char *fw_path)
Enumeration Type Documentation
enum KineticOperation_NonstandardTimeout
Enumerator
KineticOperation_TimeoutSetACL
KineticOperation_TimeoutSetPin
KineticOperation_TimeoutLockUnlock
KineticOperation_TimeoutErase
Definition at line 32 of file kinetic_operation.h.
Function Documentation
KineticStatus KineticOperation_SendRequest (KineticOperation *constoperation)
Definition at line 48 of file kinetic_operation.c.
References KINETIC_ASSERT, KINETIC_STATUS_CONNECTION_ERROR, KineticOperation_SendRequestInLock(), KineticRequest_LockOperation(), and KineticRequest_UnlockOperation().
KineticStatus KineticOperation_GetStatus (const KineticOperation *constoperation)
Definition at line 143 of file kinetic_operation.c.
References KINETIC_STATUS_INVALID, and KineticResponse_GetStatus().
void KineticOperation_Complete (KineticOperation *operation, KineticStatusstatus)
Definition at line 162 of file kinetic_operation.c.
References KINETIC_ASSERT, KineticAllocator_FreeOperation(), KineticCountingSemaphore_Give(), and KineticCompletionData::status.
KineticStatus KineticOperation_NoopCallback (KineticOperation *constoperation, KineticStatus conststatus)
Definition at line 184 of file kinetic_operation.c.
References KINETIC_ASSERT, and LOGF3.
void KineticOperation_BuildNoop (KineticOperation *operation)
Definition at line 193 of file kinetic_operation.c.
References KINETIC_PROTO_COMMAND_MESSAGE_TYPE_NOOP, KineticOperation_NoopCallback(), and KineticOperation_ValidateOperation().
KineticStatus KineticOperation_PutCallback (KineticOperation *constoperation, KineticStatus conststatus)
Definition at line 201 of file kinetic_operation.c.
References ByteBuffer::array, BYTE_BUFFER_NONE, ByteBuffer_Append(), ByteBuffer_Reset(), ByteBuffer::bytesUsed, ByteArray::data, KineticEntry::dbVersion, KINETIC_ASSERT, KINETIC_STATUS_SUCCESS, ByteArray::len, LOGF3, and KineticEntry::newVersion.
KineticStatus KineticOperation_BuildPut (KineticOperation *constoperation, KineticEntry *constentry)
Definition at line 233 of file kinetic_operation.c.
References ByteBuffer::bytesUsed, KINETIC_OBJ_SIZE, KINETIC_PROTO_COMMAND_MESSAGE_TYPE_PUT, KINETIC_STATUS_BUFFER_OVERRUN, KINETIC_STATUS_SUCCESS, KineticMessage_ConfigureKeyValue(), KineticOperation_PutCallback(), KineticOperation_ValidateOperation(), LOGF2, and KineticEntry::value.
KineticStatus KineticOperation_GetCallback (KineticOperation *constoperation, KineticStatus conststatus)
void KineticOperation_BuildGet (KineticOperation *constoperation, KineticEntry *constentry)
Definition at line 315 of file kinetic_operation.c.
References build_get_command(), get_cmd_cb(), and KINETIC_PROTO_COMMAND_MESSAGE_TYPE_GET.
void KineticOperation_BuildGetNext (KineticOperation *constoperation, KineticEntry *constentry)
Definition at line 339 of file kinetic_operation.c.
References build_get_command(), getnext_cmd_cb(), and KINETIC_PROTO_COMMAND_MESSAGE_TYPE_GETNEXT.
void KineticOperation_BuildGetPrevious (KineticOperation *constoperation, KineticEntry *constentry)
Definition at line 327 of file kinetic_operation.c.
References build_get_command(), getprevious_cmd_cb(), and KINETIC_PROTO_COMMAND_MESSAGE_TYPE_GETPREVIOUS.
KineticStatus KineticOperation_FlushCallback (KineticOperation *constoperation, KineticStatus conststatus)
Definition at line 346 of file kinetic_operation.c.
References KINETIC_ASSERT, and LOGF3.
void KineticOperation_BuildFlush (KineticOperation *constoperation)
Definition at line 356 of file kinetic_operation.c.
References KINETIC_PROTO_COMMAND_MESSAGE_TYPE_FLUSHALLDATA, KineticOperation_FlushCallback(), and KineticOperation_ValidateOperation().
KineticStatus KineticOperation_DeleteCallback (KineticOperation *constoperation, KineticStatus conststatus)
Definition at line 366 of file kinetic_operation.c.
References KINETIC_ASSERT, and LOGF3.
void KineticOperation_BuildDelete (KineticOperation *constoperation, KineticEntry *constentry)
Definition at line 376 of file kinetic_operation.c.
References ByteBuffer_Reset(), KINETIC_PROTO_COMMAND_MESSAGE_TYPE_DELETE, KineticMessage_ConfigureKeyValue(), KineticOperation_DeleteCallback(), and KineticOperation_ValidateOperation().
KineticStatus KineticOperation_GetKeyRangeCallback (KineticOperation *constoperation, KineticStatus conststatus)
Definition at line 396 of file kinetic_operation.c.
References Copy_KineticProto_Command_Range_to_ByteBufferArray(), KINETIC_ASSERT, KINETIC_STATUS_BUFFER_OVERRUN, KINETIC_STATUS_SUCCESS, KineticResponse_GetKeyRange(), and LOGF3.
void KineticOperation_BuildGetKeyRange (KineticOperation *constoperation, KineticKeyRange *range, ByteBufferArray *buffers)
Definition at line 419 of file kinetic_operation.c.
References KINETIC_ASSERT, KINETIC_PROTO_COMMAND_MESSAGE_TYPE_GETKEYRANGE, KineticMessage_ConfigureKeyRange(), KineticOperation_GetKeyRangeCallback(), and KineticOperation_ValidateOperation().
KineticStatus KineticOperation_P2POperationCallback (KineticOperation *constoperation, KineticStatus conststatus)
Definition at line 605 of file kinetic_operation.c.
References destroy_p2pOp(), KINETIC_STATUS_SUCCESS, and populateP2PStatusCodes().
KineticStatus KineticOperation_BuildP2POperation (KineticOperation *constoperation, KineticP2P_Operation *constp2pOp)
Definition at line 624 of file kinetic_operation.c.
References build_p2pOp(), KINETIC_P2P_OPERATION_LIMIT, KINETIC_PROTO_COMMAND_MESSAGE_TYPE_PEER2PEERPUSH, KINETIC_STATUS_BUFFER_OVERRUN, KINETIC_STATUS_OPERATION_INVALID, KINETIC_STATUS_SUCCESS, KineticOperation_P2POperationCallback(), and KineticOperation_ValidateOperation().
KineticStatus KineticOperation_SetPinCallback (KineticOperation *constoperation, KineticStatus conststatus)
Definition at line 654 of file kinetic_operation.c.
References KINETIC_ASSERT, and LOGF3.
void KineticOperation_BuildSetPin (KineticOperation *constoperation, ByteArrayold_pin, ByteArraynew_pin, boollock)
Definition at line 663 of file kinetic_operation.c.
References ByteArray::data, KINETIC_PROTO_COMMAND_MESSAGE_TYPE_SECURITY, KineticOperation_SetPinCallback(), KineticOperation_TimeoutSetPin, KineticOperation_ValidateOperation(), and ByteArray::len.
KineticStatus KineticOperation_EraseCallback (KineticOperation *constoperation, KineticStatus conststatus)
Definition at line 694 of file kinetic_operation.c.
References KINETIC_ASSERT, and LOGF3.
void KineticOperation_BuildErase (KineticOperation *constoperation, boolsecure_erase, ByteArray *pin)
Definition at line 703 of file kinetic_operation.c.
References KINETIC_PROTO_COMMAND_MESSAGE_TYPE_PINOP, KINETIC_PROTO_COMMAND_PIN_OPERATION_PIN_OP_TYPE_ERASE_PINOP, KINETIC_PROTO_COMMAND_PIN_OPERATION_PIN_OP_TYPE_SECURE_ERASE_PINOP, KineticOperation_EraseCallback(), KineticOperation_TimeoutErase, and KineticOperation_ValidateOperation().
KineticStatus KineticOperation_LockUnlockCallback (KineticOperation *constoperation, KineticStatus conststatus)
Definition at line 722 of file kinetic_operation.c.
References KINETIC_ASSERT, and LOGF3.
void KineticOperation_BuildLockUnlock (KineticOperation *constoperation, boollock, ByteArray *pin)
Definition at line 731 of file kinetic_operation.c.
References KINETIC_PROTO_COMMAND_MESSAGE_TYPE_PINOP, KINETIC_PROTO_COMMAND_PIN_OPERATION_PIN_OP_TYPE_LOCK_PINOP, KINETIC_PROTO_COMMAND_PIN_OPERATION_PIN_OP_TYPE_UNLOCK_PINOP, KineticOperation_LockUnlockCallback(), KineticOperation_TimeoutLockUnlock, and KineticOperation_ValidateOperation().
KineticStatus KineticOperation_GetLogCallback (KineticOperation *constoperation, KineticStatus conststatus)
Definition at line 435 of file kinetic_operation.c.
References KINETIC_ASSERT, KINETIC_STATUS_OPERATION_FAILED, KINETIC_STATUS_SUCCESS, KineticLogInfo_Create(), and LOGF3.
void KineticOperation_BuildGetLog (KineticOperation *constoperation, KineticLogInfo_Typetype, KineticLogInfo **info)
Definition at line 458 of file kinetic_operation.c.
References KINETIC_PROTO_COMMAND_MESSAGE_TYPE_GETLOG, KineticLogInfo_Type_to_KineticProto_Command_GetLog_Type(), KineticOperation_GetLogCallback(), and KineticOperation_ValidateOperation().
KineticStatus KineticOperation_SetACLCallback (KineticOperation *constoperation, KineticStatus conststatus)
Definition at line 780 of file kinetic_operation.c.
References KINETIC_ASSERT, and LOGF3.
void KineticOperation_BuildSetACL (KineticOperation *constoperation, struct ACL *ACLs)
Definition at line 790 of file kinetic_operation.c.
References ACL::ACL_count, ACL::ACLs, KINETIC_PROTO_COMMAND_MESSAGE_TYPE_SECURITY, KineticOperation_SetACLCallback(), KineticOperation_TimeoutSetACL, and KineticOperation_ValidateOperation().
KineticStatus KineticOperation_SetClusterVersionCallback (KineticOperation *constoperation, KineticStatus conststatus)
Definition at line 751 of file kinetic_operation.c.
References KINETIC_ASSERT, KINETIC_STATUS_SUCCESS, KineticSession_SetClusterVersion(), and LOGF3.
void KineticOperation_BuildSetClusterVersion (KineticOperation *constoperation, int64_tnew_cluster_version)
Definition at line 764 of file kinetic_operation.c.
References KINETIC_PROTO_COMMAND_MESSAGE_TYPE_SETUP, KineticOperation_SetClusterVersionCallback(), and KineticOperation_ValidateOperation().
KineticStatus KineticOperation_UpdateFirmwareCallback (KineticOperation *constoperation, KineticStatus conststatus)
Definition at line 807 of file kinetic_operation.c.
References KINETIC_ASSERT, and LOGF3.
KineticStatus KineticOperation_BuildUpdateFirmware (KineticOperation *constoperation, const char *fw_path)
Definition at line 822 of file kinetic_operation.c.
References KINETIC_PROTO_COMMAND_MESSAGE_TYPE_SETUP, KINETIC_STATUS_INVALID, KINETIC_STATUS_INVALID_FILE, KINETIC_STATUS_MEMORY_ERROR, KINETIC_STATUS_SUCCESS, KineticOperation_UpdateFirmwareCallback(), KineticOperation_ValidateOperation(), LOG0, and LOGF0.
Author
Generated automatically by Doxygen for kinetic-c from the source code.