.TH "KineticDeviceInfo_Temperature" 3 "Thu Dec 11 2014" "Version v0.9.1" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticDeviceInfo_Temperature \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "float \fBcurrent\fP"
.br
.ti -1c
.RI "float \fBminimum\fP"
.br
.ti -1c
.RI "float \fBmaximum\fP"
.br
.ti -1c
.RI "float \fBtarget\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 232 of file kinetic_types\&.h\&.
.SH "Field Documentation"
.PP 
.SS "char* KineticDeviceInfo_Temperature::name"

.PP
Definition at line 233 of file kinetic_types\&.h\&.
.SS "float KineticDeviceInfo_Temperature::current"

.PP
Definition at line 234 of file kinetic_types\&.h\&.
.SS "float KineticDeviceInfo_Temperature::minimum"

.PP
Definition at line 235 of file kinetic_types\&.h\&.
.SS "float KineticDeviceInfo_Temperature::maximum"

.PP
Definition at line 236 of file kinetic_types\&.h\&.
.SS "float KineticDeviceInfo_Temperature::target"

.PP
Definition at line 237 of file kinetic_types\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
