.TH "KineticDeviceInfo_Statistics" 3 "Thu Nov 13 2014" "Version v0.8.1-beta" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticDeviceInfo_Statistics \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBKineticMessageType\fP \fBmessageType\fP"
.br
.ti -1c
.RI "uint64_t \fBcount\fP"
.br
.ti -1c
.RI "uint64_t \fBbytes\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 289 of file kinetic_types\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBKineticMessageType\fP KineticDeviceInfo_Statistics::messageType"

.PP
Definition at line 290 of file kinetic_types\&.h\&.
.SS "uint64_t KineticDeviceInfo_Statistics::count"

.PP
Definition at line 291 of file kinetic_types\&.h\&.
.SS "uint64_t KineticDeviceInfo_Statistics::bytes"

.PP
Definition at line 292 of file kinetic_types\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
