kinetic_connection.h
NAME
kinetic_connection.h -
SYNOPSIS
#include 'kinetic_types_internal.h'
Functions
KineticSessionHandle KineticConnection_NewConnection (const KineticSession *const config)
void KineticConnection_FreeConnection (KineticSessionHandle *const handle)
KineticConnection * KineticConnection_FromHandle (KineticSessionHandle handle)
KineticStatus KineticConnection_Connect (KineticConnection *const connection)
void KineticConnection_Pause (KineticConnection *const connection, bool pause)
KineticStatus KineticConnection_Disconnect (KineticConnection *const connection)
void KineticConnection_IncrementSequence (KineticConnection *const connection)
Function Documentation
KineticSessionHandle KineticConnection_NewConnection (const KineticSession *constconfig)
Definition at line 150 of file kinetic_connection.c.
References KINETIC_CONNECTION_INIT, KINETIC_HANDLE_INVALID, and KINETIC_SESSIONS_MAX.
void KineticConnection_FreeConnection (KineticSessionHandle *consthandle)
Definition at line 170 of file kinetic_connection.c.
References KINETIC_HANDLE_INVALID, and KineticConnection_FromHandle().
KineticConnection* KineticConnection_FromHandle (KineticSessionHandlehandle)
Definition at line 182 of file kinetic_connection.c.
References KINETIC_HANDLE_INVALID, and KINETIC_SESSIONS_MAX.
KineticStatus KineticConnection_Connect (KineticConnection *constconnection)
Definition at line 189 of file kinetic_connection.c.
References Kinetic_GetErrnoDescription(), KINETIC_SOCKET_DESCRIPTOR_INVALID, KINETIC_STATUS_CONNECTION_ERROR, KINETIC_STATUS_SESSION_EMPTY, KINETIC_STATUS_SUCCESS, KineticSocket_Connect(), LOG0, and LOGF0.
void KineticConnection_Pause (KineticConnection *constconnection, boolpause)
Definition at line 38 of file kinetic_connection.c.
KineticStatus KineticConnection_Disconnect (KineticConnection *constconnection)
Definition at line 220 of file kinetic_connection.c.
References Kinetic_GetErrnoDescription(), KINETIC_HANDLE_INVALID, KINETIC_STATUS_CONNECTION_ERROR, KINETIC_STATUS_SESSION_INVALID, KINETIC_STATUS_SUCCESS, LOG2, and LOGF0.
void KineticConnection_IncrementSequence (KineticConnection *constconnection)
Definition at line 246 of file kinetic_connection.c.
Author
Generated automatically by Doxygen for kinetic-c from the source code.