.TH "kinetic_countingsemaphore.h" 3 "Mon Mar 2 2015" "Version v0.12.0-beta" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kinetic_countingsemaphore.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "KineticCountingSemaphore * \fBKineticCountingSemaphore_Create\fP (uint32_t max)"
.br
.ti -1c
.RI "void \fBKineticCountingSemaphore_Take\fP (KineticCountingSemaphore *const sem)"
.br
.ti -1c
.RI "void \fBKineticCountingSemaphore_Give\fP (KineticCountingSemaphore *const sem)"
.br
.ti -1c
.RI "void \fBKineticCountingSemaphore_Destroy\fP (KineticCountingSemaphore *const sem)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "KineticCountingSemaphore* KineticCountingSemaphore_Create (uint32_tmax)"

.PP
Definition at line 26 of file kinetic_countingsemaphore\&.c\&.
.SS "void KineticCountingSemaphore_Take (KineticCountingSemaphore *constsem)"

.PP
Definition at line 38 of file kinetic_countingsemaphore\&.c\&.
.PP
References LOGF3\&.
.SS "void KineticCountingSemaphore_Give (KineticCountingSemaphore *constsem)"

.PP
Definition at line 60 of file kinetic_countingsemaphore\&.c\&.
.PP
References LOGF3\&.
.SS "void KineticCountingSemaphore_Destroy (KineticCountingSemaphore *constsem)"

.PP
Definition at line 79 of file kinetic_countingsemaphore\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
