.TH "KineticConnection" 3 "Fri Aug 8 2014" "Version v0.4.3" "protobuf-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticConnection \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "bool \fBconnected\fP"
.br
.ti -1c
.RI "bool \fBblocking\fP"
.br
.ti -1c
.RI "int \fBport\fP"
.br
.ti -1c
.RI "int \fBsocketDescriptor\fP"
.br
.ti -1c
.RI "char \fBhost\fP [256]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 74 of file kinetic_types\&.h\&.
.SH "Field Documentation"
.PP 
.SS "bool KineticConnection::connected"

.PP
Definition at line 76 of file kinetic_types\&.h\&.
.SS "bool KineticConnection::blocking"

.PP
Definition at line 77 of file kinetic_types\&.h\&.
.SS "int KineticConnection::port"

.PP
Definition at line 78 of file kinetic_types\&.h\&.
.SS "int KineticConnection::socketDescriptor"

.PP
Definition at line 79 of file kinetic_types\&.h\&.
.SS "char KineticConnection::host[256]"

.PP
Definition at line 80 of file kinetic_types\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for protobuf-c from the source code\&.
