.TH "kinetic_countingsemaphore_types.h" 3 "Wed Feb 11 2015" "Version v0.11.1" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kinetic_countingsemaphore_types.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <pthread\&.h>\fP
.br
\fC#include <stdint\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBKineticCountingSemaphore\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
