.TH "kinetic_operation.h" 3 "Wed Oct 15 2014" "Version v0.7.0" "protobuf-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kinetic_operation.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'kinetic_types_internal\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBKineticOperation\fP \fBKineticOperation_Create\fP (\fBKineticConnection\fP *const connection)"
.br
.ti -1c
.RI "\fBKineticStatus\fP \fBKineticOperation_Free\fP (\fBKineticOperation\fP *const operation)"
.br
.ti -1c
.RI "\fBKineticStatus\fP \fBKineticOperation_GetStatus\fP (const \fBKineticOperation\fP *const operation)"
.br
.ti -1c
.RI "void \fBKineticOperation_BuildNoop\fP (\fBKineticOperation\fP *operation)"
.br
.ti -1c
.RI "void \fBKineticOperation_BuildPut\fP (\fBKineticOperation\fP *const operation, \fBKineticEntry\fP *const entry)"
.br
.ti -1c
.RI "void \fBKineticOperation_BuildGet\fP (\fBKineticOperation\fP *const operation, \fBKineticEntry\fP *const entry)"
.br
.ti -1c
.RI "void \fBKineticOperation_BuildDelete\fP (\fBKineticOperation\fP *const operation, \fBKineticEntry\fP *const entry)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBKineticOperation\fP KineticOperation_Create (\fBKineticConnection\fP *constconnection)"

.PP
Definition at line 40 of file kinetic_operation\&.c\&.
.PP
References KineticOperation::connection, KINETIC_PDU_INIT_WITH_MESSAGE, KineticAllocator_NewPDU(), KineticPDU_Init(), LOG, LOGF, KineticConnection::pdus, KineticOperation::request, and KineticOperation::response\&.
.SS "\fBKineticStatus\fP KineticOperation_Free (\fBKineticOperation\fP *constoperation)"

.PP
Definition at line 76 of file kinetic_operation\&.c\&.
.PP
References KineticOperation::connection, KINETIC_STATUS_SESSION_INVALID, KINETIC_STATUS_SUCCESS, KineticAllocator_FreePDU(), LOG, KineticConnection::pdus, KineticOperation::request, and KineticOperation::response\&.
.SS "\fBKineticStatus\fP KineticOperation_GetStatus (const \fBKineticOperation\fP *constoperation)"

.PP
Definition at line 96 of file kinetic_operation\&.c\&.
.PP
References KINETIC_STATUS_INVALID, KineticPDU_GetStatus(), and KineticOperation::response\&.
.SS "void KineticOperation_BuildNoop (\fBKineticOperation\fP *operation)"

.PP
Definition at line 107 of file kinetic_operation\&.c\&.
.PP
References BYTE_BUFFER_NONE, KineticOperation::connection, KINETIC_PROTO_MESSAGE_TYPE_NOOP, KineticConnection_IncrementSequence(), KineticOperation::request, and KineticOperation::response\&.
.SS "void KineticOperation_BuildPut (\fBKineticOperation\fP *constoperation, \fBKineticEntry\fP *constentry)"

.PP
Definition at line 119 of file kinetic_operation\&.c\&.
.PP
References BYTE_BUFFER_NONE, KineticOperation::connection, KINETIC_PROTO_MESSAGE_TYPE_PUT, KineticConnection_IncrementSequence(), KineticMessage_ConfigureKeyValue(), KineticOperation::request, KineticOperation::response, and KineticEntry::value\&.
.SS "void KineticOperation_BuildGet (\fBKineticOperation\fP *constoperation, \fBKineticEntry\fP *constentry)"

.PP
Definition at line 136 of file kinetic_operation\&.c\&.
.PP
References BYTE_BUFFER_NONE, KineticOperation::connection, KINETIC_PROTO_MESSAGE_TYPE_GET, KineticConnection_IncrementSequence(), KineticMessage_ConfigureKeyValue(), KineticEntry::metadataOnly, KineticOperation::request, KineticOperation::response, and KineticEntry::value\&.
.SS "void KineticOperation_BuildDelete (\fBKineticOperation\fP *constoperation, \fBKineticEntry\fP *constentry)"

.PP
Definition at line 156 of file kinetic_operation\&.c\&.
.PP
References BYTE_BUFFER_NONE, KineticOperation::connection, KINETIC_PROTO_MESSAGE_TYPE_DELETE, KineticConnection_IncrementSequence(), KineticMessage_ConfigureKeyValue(), KineticOperation::request, and KineticOperation::response\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for protobuf-c from the source code\&.
