kinetic_device_info.c
NAME
kinetic_device_info.c -
SYNOPSIS
#include 'kinetic_device_info.h'
#include 'kinetic_logger.h'
#include <stdlib.h>
#include <string.h>
Functions
static char * copy_str (const char *s)
static ByteArray copy_to_byte_array (uint8_t *data, size_t length)
static void free_byte_array (ByteArray ba)
static KineticLogInfo_Utilization * KineticLogInfo_GetUtilizations (const Com__Seagate__Kinetic__Proto__Command__GetLog *getLog, size_t *numUtilizations)
static KineticLogInfo_Temperature * KineticLogInfo_GetTemperatures (const Com__Seagate__Kinetic__Proto__Command__GetLog *getLog, size_t *numTemperatures)
static KineticLogInfo_Capacity * KineticLogInfo_GetCapacity (const Com__Seagate__Kinetic__Proto__Command__GetLog *getLog)
static
KineticLogInfo_Configuration * KineticLogInfo_GetConfiguration (const Com__Seagate__Kinetic__Proto__Command__GetLog *getLog)"
static KineticLogInfo_Statistics * KineticLogInfo_GetStatistics (const Com__Seagate__Kinetic__Proto__Command__GetLog *getLog, size_t *numStatistics)
static ByteArray KineticLogInfo_GetMessages (const Com__Seagate__Kinetic__Proto__Command__GetLog *getLog)
static KineticLogInfo_Limits * KineticLogInfo_GetLimits (const Com__Seagate__Kinetic__Proto__Command__GetLog *getLog)
static KineticLogInfo_Device * KineticLogInfo_GetDevice (const Com__Seagate__Kinetic__Proto__Command__GetLog *getLog)
KineticLogInfo * KineticLogInfo_Create (const Com__Seagate__Kinetic__Proto__Command__GetLog *getLog)
void KineticLogInfo_Free (KineticLogInfo *kdi)
Function Documentation
static char* copy_str (const char *s) [static]
Definition at line 27 of file kinetic_device_info.c.
static ByteArray copy_to_byte_array (uint8_t *data, size_tlength) [static]
Definition at line 41 of file kinetic_device_info.c.
References ByteArray::data, and ByteArray::len.
static void free_byte_array (ByteArrayba) [static]
Definition at line 50 of file kinetic_device_info.c.
References ByteArray::data.
static KineticLogInfo_Utilization* KineticLogInfo_GetUtilizations (const Com__Seagate__Kinetic__Proto__Command__GetLog *getLog, size_t *numUtilizations) [static]
Definition at line 54 of file kinetic_device_info.c.
References copy_str(), KineticLogInfo_Utilization::name, and KineticLogInfo_Utilization::value.
static KineticLogInfo_Temperature* KineticLogInfo_GetTemperatures (const Com__Seagate__Kinetic__Proto__Command__GetLog *getLog, size_t *numTemperatures) [static]
Definition at line 80 of file kinetic_device_info.c.
References copy_str(), KineticLogInfo_Temperature::current, KineticLogInfo_Temperature::maximum, KineticLogInfo_Temperature::minimum, KineticLogInfo_Temperature::name, and KineticLogInfo_Temperature::target.
static KineticLogInfo_Capacity* KineticLogInfo_GetCapacity (const Com__Seagate__Kinetic__Proto__Command__GetLog *getLog) [static]
Definition at line 101 of file kinetic_device_info.c.
References KineticLogInfo_Capacity::nominalCapacityInBytes, and KineticLogInfo_Capacity::portionFull.
static KineticLogInfo_Configuration* KineticLogInfo_GetConfiguration (const Com__Seagate__Kinetic__Proto__Command__GetLog *getLog) [static]
Definition at line 112 of file kinetic_device_info.c.
References KineticLogInfo_Configuration::compilationDate, copy_str(), copy_to_byte_array(), ByteArray::data, free_byte_array(), KineticLogInfo_Configuration::interfaces, KineticLogInfo_Interface::ipv4Address, KineticLogInfo_Interface::ipv6Address, KineticLogInfo_Interface::MAC, KineticLogInfo_Configuration::model, KineticLogInfo_Interface::name, KineticLogInfo_Configuration::numInterfaces, KineticLogInfo_Configuration::protocolCompilationDate, KineticLogInfo_Configuration::protocolSourceHash, KineticLogInfo_Configuration::protocolVersion, KineticLogInfo_Configuration::serialNumber, KineticLogInfo_Configuration::sourceHash, KineticLogInfo_Configuration::vendor, KineticLogInfo_Configuration::version, and KineticLogInfo_Configuration::worldWideName.
static KineticLogInfo_Statistics* KineticLogInfo_GetStatistics (const Com__Seagate__Kinetic__Proto__Command__GetLog *getLog, size_t *numStatistics) [static]
Definition at line 195 of file kinetic_device_info.c.
References KineticLogInfo_Statistics::bytes, KineticLogInfo_Statistics::count, and KineticLogInfo_Statistics::messageType.
static ByteArray KineticLogInfo_GetMessages (const Com__Seagate__Kinetic__Proto__Command__GetLog *getLog) [static]
Definition at line 217 of file kinetic_device_info.c.
References copy_to_byte_array().
static KineticLogInfo_Limits* KineticLogInfo_GetLimits (const Com__Seagate__Kinetic__Proto__Command__GetLog *getLog) [static]
Definition at line 224 of file kinetic_device_info.c.
References KineticLogInfo_Limits::maxConnections, KineticLogInfo_Limits::maxIdentityCount, KineticLogInfo_Limits::maxKeyRangeCount, KineticLogInfo_Limits::maxKeySize, KineticLogInfo_Limits::maxMessageSize, KineticLogInfo_Limits::maxOutstandingReadRequests, KineticLogInfo_Limits::maxOutstandingWriteRequests, KineticLogInfo_Limits::maxPinSize, KineticLogInfo_Limits::maxTagSize, KineticLogInfo_Limits::maxValueSize, and KineticLogInfo_Limits::maxVersionSize.
static KineticLogInfo_Device* KineticLogInfo_GetDevice (const Com__Seagate__Kinetic__Proto__Command__GetLog *getLog) [static]
Definition at line 244 of file kinetic_device_info.c.
References copy_to_byte_array(), and KineticLogInfo_Device::name.
KineticLogInfo* KineticLogInfo_Create (const Com__Seagate__Kinetic__Proto__Command__GetLog *getLog)
Definition at line 257 of file kinetic_device_info.c.
References KineticLogInfo::capacity, KineticLogInfo::configuration, ByteArray::data, KineticLogInfo::device, KINETIC_ASSERT, KineticLogInfo_GetCapacity(), KineticLogInfo_GetConfiguration(), KineticLogInfo_GetDevice(), KineticLogInfo_GetLimits(), KineticLogInfo_GetMessages(), KineticLogInfo_GetStatistics(), KineticLogInfo_GetTemperatures(), KineticLogInfo_GetUtilizations(), KineticLogInfo::limits, LOGF2, KineticLogInfo::messages, KineticLogInfo::numStatistics, KineticLogInfo::numTemperatures, KineticLogInfo::numUtilizations, KineticLogInfo::statistics, KineticLogInfo::temperatures, and KineticLogInfo::utilizations.
void KineticLogInfo_Free (KineticLogInfo *kdi)
Definition at line 323 of file kinetic_device_info.c.
References KineticLogInfo::capacity, KineticLogInfo_Configuration::compilationDate, KineticLogInfo::configuration, ByteArray::data, KineticLogInfo::device, KineticLogInfo_Configuration::interfaces, KineticLogInfo_Interface::ipv4Address, KineticLogInfo_Interface::ipv6Address, KineticLogInfo::limits, KineticLogInfo_Interface::MAC, KineticLogInfo::messages, KineticLogInfo_Configuration::model, KineticLogInfo_Utilization::name, KineticLogInfo_Temperature::name, KineticLogInfo_Interface::name, KineticLogInfo_Device::name, KineticLogInfo_Configuration::numInterfaces, KineticLogInfo::numTemperatures, KineticLogInfo::numUtilizations, KineticLogInfo_Configuration::protocolCompilationDate, KineticLogInfo_Configuration::protocolSourceHash, KineticLogInfo_Configuration::protocolVersion, KineticLogInfo_Configuration::serialNumber, KineticLogInfo_Configuration::sourceHash, KineticLogInfo::statistics, KineticLogInfo::temperatures, KineticLogInfo::utilizations, KineticLogInfo_Configuration::vendor, KineticLogInfo_Configuration::version, and KineticLogInfo_Configuration::worldWideName.
Author
Generated automatically by Doxygen for kinetic-c from the source code.