.TH "KineticCompletionData" 3 "Tue Nov 4 2014" "Version v0.8.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticCompletionData \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int64_t \fBconnectionID\fP"
.br
.ti -1c
.RI "int64_t \fBsequence\fP"
.br
.ti -1c
.RI "struct timeval \fBrequestTime\fP"
.br
.ti -1c
.RI "\fBKineticStatus\fP \fBstatus\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 164 of file kinetic_types\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int64_t KineticCompletionData::connectionID"

.PP
Definition at line 165 of file kinetic_types\&.h\&.
.SS "int64_t KineticCompletionData::sequence"

.PP
Definition at line 166 of file kinetic_types\&.h\&.
.SS "struct timeval KineticCompletionData::requestTime"

.PP
Definition at line 167 of file kinetic_types\&.h\&.
.SS "\fBKineticStatus\fP KineticCompletionData::status"

.PP
Definition at line 168 of file kinetic_types\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
