.TH "KineticLogInfo_Device" 3 "Tue Mar 3 2015" "Version v0.12.0-beta" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticLogInfo_Device \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBByteArray\fP \fBname\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 392 of file kinetic_types\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBByteArray\fP KineticLogInfo_Device::name"

.PP
Definition at line 393 of file kinetic_types\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
