kinetic_allocator.c
NAME
kinetic_allocator.c -
SYNOPSIS
#include 'kinetic_allocator.h'
#include 'kinetic_logger.h'
#include <stdlib.h>
#include <pthread.h>
Macros
#define KINETIC_LIST_LOCK(_list)
#define KINETIC_LIST_UNLOCK(_list)
Functions
void KineticAllocator_InitLists (KineticConnection *connection)
KineticConnection * KineticAllocator_NewConnection (void)
void KineticAllocator_FreeConnection (KineticConnection *connection)
KineticPDU * KineticAllocator_NewPDU (KineticConnection *connection)
void KineticAllocator_FreePDU (KineticConnection *connection, KineticPDU *pdu)
KineticPDU * KineticAllocator_GetFirstPDU (KineticConnection *connection)
KineticPDU * KineticAllocator_GetNextPDU (KineticConnection *connection, KineticPDU *pdu)
void KineticAllocator_FreeAllPDUs (KineticConnection *connection)
KineticOperation * KineticAllocator_NewOperation (KineticConnection *const connection)
void KineticAllocator_FreeOperation (KineticConnection *const connection, KineticOperation *operation)
KineticOperation * KineticAllocator_GetFirstOperation (KineticConnection *const connection)
KineticOperation * KineticAllocator_GetNextOperation (KineticConnection *const connection, KineticOperation *operation)
void KineticAllocator_FreeAllOperations (KineticConnection *const connection)
bool KineticAllocator_ValidateAllMemoryFreed (KineticConnection *const connection)
Macro Definition Documentation
#define KINETIC_LIST_LOCK(_list)
Value:
{ \
    /*LOG_LOCATION; LOGF3("Locking list! (list_addr=0x%llX)", (_list));*/ \
    pthread_mutex_lock(&((_list)->mutex)); \
    ((_list)->locked) = true; \
}
Definition at line 31 of file kinetic_allocator.c.
#define KINETIC_LIST_UNLOCK(_list)
Value:
{ \
    /*LOG_LOCATION; LOGF3("Unlocking list! (list_addr=0x%llX)", (_list));*/ \
    assert(((_list)->locked)); \
    pthread_mutex_unlock(&((_list)->mutex)); \
    ((_list)->locked) = false; \
}
Definition at line 37 of file kinetic_allocator.c.
Function Documentation
void KineticAllocator_InitLists (KineticConnection *connection)
Definition at line 44 of file kinetic_allocator.c.
References KINETIC_LIST_INITIALIZER.
KineticConnection* KineticAllocator_NewConnection (void)
Definition at line 51 of file kinetic_allocator.c.
References KINETIC_CONNECTION_INIT.
void KineticAllocator_FreeConnection (KineticConnection *connection)
Definition at line 58 of file kinetic_allocator.c.
KineticPDU* KineticAllocator_NewPDU (KineticConnection *connection)
Definition at line 200 of file kinetic_allocator.c.
References KINETIC_PDU_INIT, LOG0, and LOGF3.
void KineticAllocator_FreePDU (KineticConnection *connection, KineticPDU *pdu)
Definition at line 216 of file kinetic_allocator.c.
References KINETIC_LIST_LOCK, KINETIC_LIST_UNLOCK, KineticProto_Message__free_unpacked(), LOG3, and LOGF3.
KineticPDU* KineticAllocator_GetFirstPDU (KineticConnection *connection)
Definition at line 236 of file kinetic_allocator.c.
KineticPDU* KineticAllocator_GetNextPDU (KineticConnection *connection, KineticPDU *pdu)
Definition at line 242 of file kinetic_allocator.c.
void KineticAllocator_FreeAllPDUs (KineticConnection *connection)
Definition at line 248 of file kinetic_allocator.c.
References KINETIC_LIST_LOCK, KINETIC_LIST_UNLOCK, KineticProto_Message__free_unpacked(), LOG1, and LOG3.
KineticOperation* KineticAllocator_NewOperation (KineticConnection *constconnection)
Definition at line 276 of file kinetic_allocator.c.
References KINETIC_OPERATION_INIT, KINETIC_PDU_INIT_WITH_COMMAND, KineticAllocator_NewPDU(), LOGF0, and LOGF3.
void KineticAllocator_FreeOperation (KineticConnection *constconnection, KineticOperation *operation)
Definition at line 293 of file kinetic_allocator.c.
References KineticAllocator_FreePDU(), and LOGF3.
KineticOperation* KineticAllocator_GetFirstOperation (KineticConnection *constconnection)
Definition at line 315 of file kinetic_allocator.c.
KineticOperation* KineticAllocator_GetNextOperation (KineticConnection *constconnection, KineticOperation *operation)
Definition at line 321 of file kinetic_allocator.c.
void KineticAllocator_FreeAllOperations (KineticConnection *constconnection)
Definition at line 327 of file kinetic_allocator.c.
References KineticAllocator_FreeOperation(), and KineticAllocator_GetFirstOperation().
bool KineticAllocator_ValidateAllMemoryFreed (KineticConnection *constconnection)
Definition at line 336 of file kinetic_allocator.c.
References BOOL_TO_STRING, and LOGF3.
Author
Generated automatically by Doxygen for kinetic-c from the source code.