.TH "kinetic_engine.h" 3 "Mon Mar 2 2015" "Version v0.12.0-beta" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kinetic_engine.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'kinetic_types_internal\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBKineticEngine\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBKineticStatus\fP \fBKineticEngine_Startup\fP (\fBKineticEngine\fP *const engine)"
.br
.ti -1c
.RI "\fBKineticStatus\fP \fBKineticEngine_CreateConnection\fP (KineticSession *const session)"
.br
.ti -1c
.RI "\fBKineticStatus\fP \fBKineticEngine_DestroyConnection\fP (KineticSession *const session)"
.br
.ti -1c
.RI "\fBKineticStatus\fP \fBKineticEngine_EnqueueOperation\fP (KineticSession *const session, KineticOperation *const operation, \fBKineticOperationCallback\fP const *const callback)"
.br
.ti -1c
.RI "\fBKineticStatus\fP \fBKineticEngine_Shutdown\fP (\fBKineticEngine\fP *const engine)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBKineticStatus\fP KineticEngine_Startup (\fBKineticEngine\fP *constengine)"

.PP
Definition at line 21 of file kinetic_engine\&.c\&.
.PP
References KINETIC_STATUS_INVALID\&.
.SS "\fBKineticStatus\fP KineticEngine_CreateConnection (KineticSession *constsession)"

.PP
Definition at line 26 of file kinetic_engine\&.c\&.
.PP
References KINETIC_STATUS_INVALID\&.
.SS "\fBKineticStatus\fP KineticEngine_DestroyConnection (KineticSession *constsession)"

.PP
Definition at line 31 of file kinetic_engine\&.c\&.
.PP
References KINETIC_STATUS_INVALID\&.
.SS "\fBKineticStatus\fP KineticEngine_EnqueueOperation (KineticSession *constsession, KineticOperation *constoperation, \fBKineticOperationCallback\fP const *constcallback)"

.PP
Definition at line 36 of file kinetic_engine\&.c\&.
.PP
References KINETIC_STATUS_INVALID\&.
.SS "\fBKineticStatus\fP KineticEngine_Shutdown (\fBKineticEngine\fP *constengine)"

.PP
Definition at line 42 of file kinetic_engine\&.c\&.
.PP
References KINETIC_STATUS_INVALID\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
