.TH "kinetic_connection.c" 3 "Thu Nov 13 2014" "Version v0.8.1-beta" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kinetic_connection.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'kinetic_connection\&.h'\fP
.br
\fC#include 'kinetic_types_internal\&.h'\fP
.br
\fC#include 'kinetic_controller\&.h'\fP
.br
\fC#include 'kinetic_socket\&.h'\fP
.br
\fC#include 'kinetic_pdu\&.h'\fP
.br
\fC#include 'kinetic_operation\&.h'\fP
.br
\fC#include 'kinetic_allocator\&.h'\fP
.br
\fC#include 'kinetic_logger\&.h'\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <pthread\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include <sys/time\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBKineticSessionHandle\fP \fBKineticConnection_NewConnection\fP (const \fBKineticSession\fP *const config)"
.br
.ti -1c
.RI "void \fBKineticConnection_FreeConnection\fP (\fBKineticSessionHandle\fP *const handle)"
.br
.ti -1c
.RI "KineticConnection * \fBKineticConnection_FromHandle\fP (\fBKineticSessionHandle\fP handle)"
.br
.ti -1c
.RI "\fBKineticStatus\fP \fBKineticConnection_Connect\fP (KineticConnection *const connection)"
.br
.ti -1c
.RI "\fBKineticStatus\fP \fBKineticConnection_Disconnect\fP (KineticConnection *const connection)"
.br
.ti -1c
.RI "void \fBKineticConnection_IncrementSequence\fP (KineticConnection *const connection)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBKineticSessionHandle\fP KineticConnection_NewConnection (const \fBKineticSession\fP *constconfig)"

.PP
Definition at line 39 of file kinetic_connection\&.c\&.
.PP
References KINETIC_CONNECTION_INIT, KINETIC_HANDLE_INVALID, and KINETIC_SESSIONS_MAX\&.
.SS "void KineticConnection_FreeConnection (\fBKineticSessionHandle\fP *consthandle)"

.PP
Definition at line 59 of file kinetic_connection\&.c\&.
.PP
References KINETIC_HANDLE_INVALID, and KineticConnection_FromHandle()\&.
.SS "KineticConnection* KineticConnection_FromHandle (\fBKineticSessionHandle\fPhandle)"

.PP
Definition at line 72 of file kinetic_connection\&.c\&.
.PP
References KINETIC_HANDLE_INVALID, and KINETIC_SESSIONS_MAX\&.
.SS "\fBKineticStatus\fP KineticConnection_Connect (KineticConnection *constconnection)"

.PP
Definition at line 79 of file kinetic_connection\&.c\&.
.PP
References KINETIC_SOCKET_DESCRIPTOR_INVALID, KINETIC_STATUS_CONNECTION_ERROR, KINETIC_STATUS_SESSION_EMPTY, KINETIC_STATUS_SUCCESS, KineticController_CreateWorkerThreads(), KineticSocket_Connect(), and LOG0\&.
.SS "\fBKineticStatus\fP KineticConnection_Disconnect (KineticConnection *constconnection)"

.PP
Definition at line 105 of file kinetic_connection\&.c\&.
.PP
References Kinetic_GetErrnoDescription(), KINETIC_HANDLE_INVALID, KINETIC_STATUS_CONNECTION_ERROR, KINETIC_STATUS_SESSION_INVALID, KINETIC_STATUS_SUCCESS, LOG2, and LOGF0\&.
.SS "void KineticConnection_IncrementSequence (KineticConnection *constconnection)"

.PP
Definition at line 131 of file kinetic_connection\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
