.TH "KineticLogInfo_Utilization" 3 "Fri Mar 13 2015" "Version v0.12.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticLogInfo_Utilization \- 
.PP
Log info untilization entry\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "float \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Log info untilization entry\&. 
.PP
Definition at line 302 of file kinetic_types\&.h\&.
.SH "Field Documentation"
.PP 
.SS "char* KineticLogInfo_Utilization::name"

.PP
Definition at line 303 of file kinetic_types\&.h\&.
.SS "float KineticLogInfo_Utilization::value"

.PP
Definition at line 304 of file kinetic_types\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
