.TH "KineticLogInfo_Statistics" 3 "Tue Mar 3 2015" "Version v0.12.0-beta" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticLogInfo_Statistics \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBKineticMessageType\fP \fBmessageType\fP"
.br
.ti -1c
.RI "uint64_t \fBcount\fP"
.br
.ti -1c
.RI "uint64_t \fBbytes\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 374 of file kinetic_types\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBKineticMessageType\fP KineticLogInfo_Statistics::messageType"

.PP
Definition at line 375 of file kinetic_types\&.h\&.
.SS "uint64_t KineticLogInfo_Statistics::count"

.PP
Definition at line 376 of file kinetic_types\&.h\&.
.SS "uint64_t KineticLogInfo_Statistics::bytes"

.PP
Definition at line 377 of file kinetic_types\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
