kinetic_hmac.c
NAME
kinetic_hmac.c -
SYNOPSIS
#include 'kinetic_hmac.h'
#include 'kinetic_nbo.h'
#include 'kinetic_logger.h'
#include <string.h>
#include <openssl/hmac.h>
Macros
#define LOG_HMAC 0
Functions
static void KineticHMAC_Compute (KineticHMAC *hmac, const Com__Seagate__Kinetic__Proto__Message *proto, const ByteArray key)
void KineticHMAC_Init (KineticHMAC *hmac, Com__Seagate__Kinetic__Proto__Command__Security__ACL__HMACAlgorithm algorithm)
void KineticHMAC_Populate (KineticHMAC *hmac, Com__Seagate__Kinetic__Proto__Message *msg, const ByteArray key)
bool KineticHMAC_Validate (const Com__Seagate__Kinetic__Proto__Message *msg, const ByteArray key)
Macro Definition Documentation
#define LOG_HMAC 0
Definition at line 110 of file kinetic_hmac.c.
Function Documentation
static void KineticHMAC_Compute (KineticHMAC *hmac, const Com__Seagate__Kinetic__Proto__Message *proto, const ByteArraykey) [static]
Definition at line 112 of file kinetic_hmac.c.
References ByteArray::data, KineticHMAC::data, KINETIC_ASSERT, KineticNBO_FromHostU32(), ByteArray::len, and KineticHMAC::len.
void KineticHMAC_Init (KineticHMAC *hmac, Com__Seagate__Kinetic__Proto__Command__Security__ACL__HMACAlgorithmalgorithm)
Definition at line 31 of file kinetic_hmac.c.
References KineticHMAC::algorithm, COM__SEAGATE__KINETIC__PROTO__COMMAND__SECURITY__ACL__HMACALGORITHM__HmacSHA1, COM__SEAGATE__KINETIC__PROTO__COMMAND__SECURITY__ACL__HMACALGORITHM__INVALID_HMAC_ALGORITHM, and KINETIC_HMAC_MAX_LEN.
void KineticHMAC_Populate (KineticHMAC *hmac, Com__Seagate__Kinetic__Proto__Message *msg, const ByteArraykey)
Definition at line 47 of file kinetic_hmac.c.
References COM__SEAGATE__KINETIC__PROTO__COMMAND__SECURITY__ACL__HMACALGORITHM__HmacSHA1, ByteArray::data, KineticHMAC::data, KINETIC_ASSERT, KineticHMAC_Compute(), KineticHMAC_Init(), ByteArray::len, and KineticHMAC::len.
bool KineticHMAC_Validate (const Com__Seagate__Kinetic__Proto__Message *msg, const ByteArraykey)
Definition at line 67 of file kinetic_hmac.c.
References COM__SEAGATE__KINETIC__PROTO__COMMAND__SECURITY__ACL__HMACALGORITHM__HmacSHA1, COM__SEAGATE__KINETIC__PROTO__MESSAGE__AUTH_TYPE__HMACAUTH, ByteArray::data, KineticHMAC::data, KINETIC_ASSERT, KineticHMAC_Compute(), KineticHMAC_Init(), KineticLogger_LogByteArray(), ByteArray::len, KineticHMAC::len, and LOG0.
Author
Generated automatically by Doxygen for kinetic-c from the source code.