kinetic_request.c
NAME
kinetic_request.c -
SYNOPSIS
#include 'kinetic_request.h'
#include <pthread.h>
#include 'kinetic_logger.h'
#include 'kinetic_session.h'
#include 'kinetic_auth.h'
#include 'kinetic_nbo.h'
#include 'kinetic_controller.h'
#include 'byte_array.h'
#include 'bus.h'
Functions
size_t KineticRequest_PackCommand (KineticRequest *request)
KineticStatus KineticRequest_PopulateAuthentication (KineticSessionConfig *config, KineticRequest *request, ByteArray *pin)
KineticStatus KineticRequest_PackMessage (KineticOperation *operation, uint8_t **out_msg, size_t *msgSize)
bool KineticRequest_SendRequest (KineticOperation *operation, uint8_t *msg, size_t msgSize)
bool KineticRequest_LockSend (KineticSession *session)
bool KineticRequest_UnlockSend (KineticSession *session)
Function Documentation
size_t KineticRequest_PackCommand (KineticRequest *request)
Definition at line 36 of file kinetic_request.c.
References com__seagate__kinetic__proto__command__get_packed_size(), com__seagate__kinetic__proto__command__pack(), KINETIC_ASSERT, KINETIC_REQUEST_PACK_FAILURE, KineticLogger_LogByteArray(), and LOGF0.
KineticStatus KineticRequest_PopulateAuthentication (KineticSessionConfig *config, KineticRequest *request, ByteArray *pin)
Definition at line 62 of file kinetic_request.c.
References KineticAuth_PopulateHmac(), and KineticAuth_PopulatePin().
KineticStatus KineticRequest_PackMessage (KineticOperation *operation, uint8_t **out_msg, size_t *msgSize)
Definition at line 72 of file kinetic_request.c.
References com__seagate__kinetic__proto__message__get_packed_size(), com__seagate__kinetic__proto__message__pack(), KINETIC_ASSERT, KINETIC_STATUS_MEMORY_ERROR, KINETIC_STATUS_SUCCESS, KineticLogger_LogHeader(), KineticLogger_LogProtobuf(), KineticNBO_FromHostU32(), KineticPDUHeader, LOG0, LOGF2, and PDU_HEADER_LEN.
bool KineticRequest_SendRequest (KineticOperation *operation, uint8_t *msg, size_tmsgSize)
Definition at line 132 of file kinetic_request.c.
References Bus_SendRequest(), BUS_SOCKET_PLAIN, bus_user_msg::fd, KINETIC_ASSERT, and KineticController_HandleResult().
bool KineticRequest_LockSend (KineticSession *session)
Definition at line 150 of file kinetic_request.c.
References KINETIC_ASSERT.
bool KineticRequest_UnlockSend (KineticSession *session)
Definition at line 156 of file kinetic_request.c.
References KINETIC_ASSERT.
Author
Generated automatically by Doxygen for kinetic-c from the source code.