.TH "KineticHMAC" 3 "Wed Jul 30 2014" "Version v0.3.3" "protobuf-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticHMAC \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_hmac\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBKineticProto_Security_ACL_HMACAlgorithm\fP \fBalgorithm\fP"
.br
.ti -1c
.RI "unsigned int \fBvalueLength\fP"
.br
.ti -1c
.RI "uint8_t \fBvalue\fP [((SHA_DIGEST_LENGTH))]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 27 of file kinetic_hmac\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBKineticProto_Security_ACL_HMACAlgorithm\fP KineticHMAC::algorithm"

.PP
Definition at line 29 of file kinetic_hmac\&.h\&.
.SS "unsigned int KineticHMAC::valueLength"

.PP
Definition at line 30 of file kinetic_hmac\&.h\&.
.SS "uint8_t KineticHMAC::value[((SHA_DIGEST_LENGTH))]"

.PP
Definition at line 31 of file kinetic_hmac\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for protobuf-c from the source code\&.
