kinetic_auth.c
NAME
kinetic_auth.c -
SYNOPSIS
#include 'kinetic_auth.h'
#include 'kinetic_hmac.h'
#include 'kinetic.pb-c.h'
#include 'kinetic_logger.h'
Functions
KineticStatus KineticAuth_EnsureSslEnabled (KineticSessionConfig const *const config)
KineticStatus KineticAuth_PopulateHmac (KineticSessionConfig const *const config, KineticRequest *const pdu)
KineticStatus KineticAuth_PopulatePin (KineticSessionConfig const *const config, KineticRequest *const pdu, ByteArray pin)
KineticStatus KineticAuth_PopulateTag (ByteBuffer *const tag, KineticAlgorithm algorithm, ByteArray const *const key)
Function Documentation
KineticStatus KineticAuth_EnsureSslEnabled (KineticSessionConfig const *constconfig)
Definition at line 26 of file kinetic_auth.c.
References KINETIC_ASSERT, KINETIC_STATUS_SSL_REQUIRED, KINETIC_STATUS_SUCCESS, and KineticSessionConfig::useSsl.
KineticStatus KineticAuth_PopulateHmac (KineticSessionConfig const *constconfig, KineticRequest *constpdu)
Definition at line 33 of file kinetic_auth.c.
References COM__SEAGATE__KINETIC__PROTO__COMMAND__SECURITY__ACL__HMACALGORITHM__HmacSHA1, COM__SEAGATE__KINETIC__PROTO__MESSAGE__AUTH_TYPE__HMACAUTH, com__seagate__kinetic__proto__message__hmacauth__init(), ByteArray::data, KineticSessionConfig::hmacKey, KineticSessionConfig::identity, KINETIC_ASSERT, KINETIC_HMAC_MAX_LEN, KINETIC_HMAC_SHA1_LEN, KINETIC_STATUS_HMAC_REQUIRED, KINETIC_STATUS_SUCCESS, KineticHMAC_Init(), KineticHMAC_Populate(), ByteArray::len, and LOG3.
KineticStatus KineticAuth_PopulatePin (KineticSessionConfig const *constconfig, KineticRequest *constpdu, ByteArraypin)
Definition at line 76 of file kinetic_auth.c.
References COM__SEAGATE__KINETIC__PROTO__MESSAGE__AUTH_TYPE__PINAUTH, com__seagate__kinetic__proto__message__pinauth__init(), KineticMessage::command, ByteArray::data, KineticMessage::header, KINETIC_ASSERT, KINETIC_PIN_MAX_LEN, KINETIC_STATUS_SSL_REQUIRED, KINETIC_STATUS_SUCCESS, ByteArray::len, LOG3, KineticMessage::message, KineticMessage::pinAuth, and KineticSessionConfig::useSsl.
KineticStatus KineticAuth_PopulateTag (ByteBuffer *consttag, KineticAlgorithmalgorithm, ByteArray const *constkey)
Definition at line 107 of file kinetic_auth.c.
References KINETIC_STATUS_INVALID.
Author
Generated automatically by Doxygen for kinetic-c from the source code.