.TH "KineticExchange" 3 "Fri Aug 8 2014" "Version v0.4.2" "protobuf-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticExchange \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "bool \fBhas_clusterVersion\fP"
.br
.ti -1c
.RI "int64_t \fBclusterVersion\fP"
.br
.ti -1c
.RI "int64_t \fBidentity\fP"
.br
.ti -1c
.RI "bool \fBhas_key\fP"
.br
.ti -1c
.RI "size_t \fBkeyLength\fP"
.br
.ti -1c
.RI "char \fBkey\fP [128+1]"
.br
.ti -1c
.RI "int64_t \fBconnectionID\fP"
.br
.ti -1c
.RI "int64_t \fBsequence\fP"
.br
.ti -1c
.RI "\fBKineticConnection\fP * \fBconnection\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 138 of file kinetic_types\&.h\&.
.SH "Field Documentation"
.PP 
.SS "bool KineticExchange::has_clusterVersion"

.PP
Definition at line 142 of file kinetic_types\&.h\&.
.SS "int64_t KineticExchange::clusterVersion"

.PP
Definition at line 148 of file kinetic_types\&.h\&.
.SS "int64_t KineticExchange::identity"

.PP
Definition at line 154 of file kinetic_types\&.h\&.
.SS "bool KineticExchange::has_key"

.PP
Definition at line 159 of file kinetic_types\&.h\&.
.SS "size_t KineticExchange::keyLength"

.PP
Definition at line 160 of file kinetic_types\&.h\&.
.SS "char KineticExchange::key[128+1]"

.PP
Definition at line 161 of file kinetic_types\&.h\&.
.SS "int64_t KineticExchange::connectionID"

.PP
Definition at line 169 of file kinetic_types\&.h\&.
.SS "int64_t KineticExchange::sequence"

.PP
Definition at line 173 of file kinetic_types\&.h\&.
.SS "\fBKineticConnection\fP* KineticExchange::connection"

.PP
Definition at line 176 of file kinetic_types\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for protobuf-c from the source code\&.
