kinetic_socket.h
NAME
kinetic_socket.h -
SYNOPSIS
#include 'kinetic_types_internal.h'
#include 'kinetic_message.h'
Functions
int KineticSocket_Connect (const char *host, int port, bool nonBlocking)
void KineticSocket_Close (int socket)
KineticStatus KineticSocket_Read (int socket, ByteBuffer *dest, size_t len)
KineticStatus KineticSocket_ReadProtobuf (int socket, KineticPDU *pdu)
KineticStatus KineticSocket_Write (int socket, ByteBuffer *src)
KineticStatus KineticSocket_WriteProtobuf (int socket, KineticPDU *pdu)
Function Documentation
int KineticSocket_Connect (const char *host, intport, boolnonBlocking)
Definition at line 49 of file kinetic_socket.c.
References KINETIC_SOCKET_DESCRIPTOR_INVALID, LOG, LOGF, and PDU_VALUE_MAX_LEN.
void KineticSocket_Close (intsocket)
Definition at line 138 of file kinetic_socket.c.
References LOG, and LOGF.
KineticStatus KineticSocket_Read (intsocket, ByteBuffer *dest, size_tlen)
Definition at line 156 of file kinetic_socket.c.
References ByteBuffer::array, ByteBuffer::bytesUsed, ByteArray::data, KINETIC_STATUS_BUFFER_OVERRUN, KINETIC_STATUS_INVALID, KINETIC_STATUS_MEMORY_ERROR, KINETIC_STATUS_SOCKET_ERROR, KINETIC_STATUS_SOCKET_TIMEOUT, KINETIC_STATUS_SUCCESS, ByteArray::len, LOG, and LOGF.
KineticStatus KineticSocket_ReadProtobuf (intsocket, KineticPDU *pdu)
Definition at line 313 of file kinetic_socket.c.
References ByteBuffer::array, ByteBuffer_Create(), ByteBuffer::bytesUsed, ByteArray::data, KINETIC_STATUS_DATA_ERROR, KINETIC_STATUS_MEMORY_ERROR, KINETIC_STATUS_SUCCESS, KineticProto__unpack(), KineticSocket_Read(), LOG, and LOGF.
KineticStatus KineticSocket_Write (intsocket, ByteBuffer *src)
Definition at line 355 of file kinetic_socket.c.
References ByteBuffer::array, ByteBuffer::bytesUsed, ByteArray::data, KINETIC_STATUS_SOCKET_ERROR, KINETIC_STATUS_SUCCESS, LOG, and LOGF.
KineticStatus KineticSocket_WriteProtobuf (intsocket, KineticPDU *pdu)
Definition at line 389 of file kinetic_socket.c.
References ByteBuffer_Create(), ByteBuffer::bytesUsed, KINETIC_STATUS_MEMORY_ERROR, KineticProto__pack(), KineticSocket_Write(), LOG, and LOGF.
Author
Generated automatically by Doxygen for protobuf-c from the source code.