.TH "kinetic_hmac.h" 3 "Thu Sep 11 2014" "Version v0.6.0-beta-2" "protobuf-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kinetic_hmac.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'kinetic_types_internal\&.h'\fP
.br
\fC#include 'kinetic_proto\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBKineticHMAC_Init\fP (\fBKineticHMAC\fP *hmac, \fBKineticProto_Security_ACL_HMACAlgorithm\fP algorithm)"
.br
.ti -1c
.RI "void \fBKineticHMAC_Populate\fP (\fBKineticHMAC\fP *hmac, \fBKineticProto\fP *proto, const \fBByteArray\fP key)"
.br
.ti -1c
.RI "bool \fBKineticHMAC_Validate\fP (const \fBKineticProto\fP *proto, const \fBByteArray\fP key)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void KineticHMAC_Init (\fBKineticHMAC\fP *hmac, \fBKineticProto_Security_ACL_HMACAlgorithm\fPalgorithm)"

.PP
Definition at line 31 of file kinetic_hmac\&.c\&.
.PP
References KineticHMAC::algorithm, KINETIC_HMAC_MAX_LEN, KINETIC_PROTO_SECURITY_ACL_HMACALGORITHM_HmacSHA1, and KINETIC_PROTO_SECURITY_ACL_HMACALGORITHM_INVALID_HMAC_ALGORITHM\&.
.SS "void KineticHMAC_Populate (\fBKineticHMAC\fP *hmac, \fBKineticProto\fP *proto, const \fBByteArray\fPkey)"

.PP
Definition at line 49 of file kinetic_hmac\&.c\&.
.PP
References KineticHMAC::data, KINETIC_PROTO_SECURITY_ACL_HMACALGORITHM_HmacSHA1, KineticHMAC_Init(), and KineticHMAC::len\&.
.SS "bool KineticHMAC_Validate (const \fBKineticProto\fP *proto, const \fBByteArray\fPkey)"

.PP
Definition at line 62 of file kinetic_hmac\&.c\&.
.PP
References KineticHMAC::data, KINETIC_PROTO_SECURITY_ACL_HMACALGORITHM_HmacSHA1, KineticHMAC_Init(), KineticLogger_LogByteArray(), KineticHMAC::len, and LOG\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for protobuf-c from the source code\&.
