.TH "kinetic_pdu_unpack.h" 3 "Fri Mar 13 2015" "Version v0.12.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kinetic_pdu_unpack.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'kinetic\&.pb-c\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "Com__Seagate__Kinetic__Proto__Command * \fBKineticPDU_unpack_command\fP (ProtobufCAllocator *allocator, size_t len, const uint8_t *data)"
.br
.ti -1c
.RI "Com__Seagate__Kinetic__Proto__Message * \fBKineticPDU_unpack_message\fP (ProtobufCAllocator *allocator, size_t len, const uint8_t *data)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "Com__Seagate__Kinetic__Proto__Command* KineticPDU_unpack_command (ProtobufCAllocator *allocator, size_tlen, const uint8_t *data)"

.PP
Definition at line 23 of file kinetic_pdu_unpack\&.c\&.
.PP
References com__seagate__kinetic__proto__command__unpack()\&.
.SS "Com__Seagate__Kinetic__Proto__Message* KineticPDU_unpack_message (ProtobufCAllocator *allocator, size_tlen, const uint8_t *data)"

.PP
Definition at line 28 of file kinetic_pdu_unpack\&.c\&.
.PP
References com__seagate__kinetic__proto__message__unpack()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
