.TH "KineticList" 3 "Wed Oct 15 2014" "Version v0.7.0" "protobuf-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticList \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_types_internal\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "KineticListItem * \fBstart\fP"
.br
.ti -1c
.RI "KineticListItem * \fBlast\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 56 of file kinetic_types_internal\&.h\&.
.SH "Field Documentation"
.PP 
.SS "KineticListItem* KineticList::start"

.PP
Definition at line 57 of file kinetic_types_internal\&.h\&.
.SS "KineticListItem* KineticList::last"

.PP
Definition at line 58 of file kinetic_types_internal\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for protobuf-c from the source code\&.
