.TH "kinetic_message.h" 3 "Fri Aug 8 2014" "Version v0.4.3" "protobuf-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kinetic_message.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'kinetic_types\&.h'\fP
.br
\fC#include 'kinetic_hmac\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBKineticMessage_Init\fP (\fBKineticMessage\fP *const message)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void KineticMessage_Init (\fBKineticMessage\fP *constmessage)"

.PP
Definition at line 23 of file kinetic_message\&.c\&.
.PP
References KINETIC_MESSAGE_INIT\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for protobuf-c from the source code\&.
