.TH "KineticConnection" 3 "Tue Jul 15 2014" "Version v0.3.1-beta" "protobuf-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticConnection \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "bool \fBConnected\fP"
.br
.ti -1c
.RI "bool \fBBlocking\fP"
.br
.ti -1c
.RI "int \fBPort\fP"
.br
.ti -1c
.RI "int \fBFileDescriptor\fP"
.br
.ti -1c
.RI "char \fBHost\fP [256]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 61 of file KineticTypes\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for protobuf-c from the source code\&.
