.TH "KineticMessage" 3 "Fri Mar 13 2015" "Version v0.12.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticMessage \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_types_internal\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "Com__Seagate__Kinetic__Proto__Message \fBmessage\fP"
.br
.ti -1c
.RI "Com__Seagate__Kinetic__Proto__Message__HMACauth \fBhmacAuth\fP"
.br
.ti -1c
.RI "Com__Seagate__Kinetic__Proto__Message__PINauth \fBpinAuth\fP"
.br
.ti -1c
.RI "uint8_t \fBhmacData\fP [\fBKINETIC_HMAC_MAX_LEN\fP]"
.br
.ti -1c
.RI "Com__Seagate__Kinetic__Proto__Command \fBcommand\fP"
.br
.ti -1c
.RI "Com__Seagate__Kinetic__Proto__Command__Header \fBheader\fP"
.br
.ti -1c
.RI "Com__Seagate__Kinetic__Proto__Command__Body \fBbody\fP"
.br
.ti -1c
.RI "Com__Seagate__Kinetic__Proto__Command__Status \fBstatus\fP"
.br
.ti -1c
.RI "Com__Seagate__Kinetic__Proto__Command__Security \fBsecurity\fP"
.br
.ti -1c
.RI "Com__Seagate__Kinetic__Proto__Command__Security__ACL \fBacl\fP"
.br
.ti -1c
.RI "Com__Seagate__Kinetic__Proto__Command__KeyValue \fBkeyValue\fP"
.br
.ti -1c
.RI "Com__Seagate__Kinetic__Proto__Command__Range \fBkeyRange\fP"
.br
.ti -1c
.RI "Com__Seagate__Kinetic__Proto__Command__Setup \fBsetup\fP"
.br
.ti -1c
.RI "Com__Seagate__Kinetic__Proto__Command__GetLog \fBgetLog\fP"
.br
.ti -1c
.RI "\fBCom__Seagate__Kinetic__Proto__Command__GetLog__Type\fP \fBgetLogType\fP"
.br
.ti -1c
.RI "Com__Seagate__Kinetic__Proto__Command__GetLog__Device \fBgetLogDevice\fP"
.br
.ti -1c
.RI "Com__Seagate__Kinetic__Proto__Command__PinOperation \fBpinOp\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 118 of file kinetic_types_internal\&.h\&.
.SH "Field Documentation"
.PP 
.SS "Com__Seagate__Kinetic__Proto__Message KineticMessage::message"

.PP
Definition at line 122 of file kinetic_types_internal\&.h\&.
.SS "Com__Seagate__Kinetic__Proto__Message__HMACauth KineticMessage::hmacAuth"

.PP
Definition at line 123 of file kinetic_types_internal\&.h\&.
.SS "Com__Seagate__Kinetic__Proto__Message__PINauth KineticMessage::pinAuth"

.PP
Definition at line 124 of file kinetic_types_internal\&.h\&.
.SS "uint8_t KineticMessage::hmacData[\fBKINETIC_HMAC_MAX_LEN\fP]"

.PP
Definition at line 125 of file kinetic_types_internal\&.h\&.
.SS "Com__Seagate__Kinetic__Proto__Command KineticMessage::command"

.PP
Definition at line 128 of file kinetic_types_internal\&.h\&.
.SS "Com__Seagate__Kinetic__Proto__Command__Header KineticMessage::header"

.PP
Definition at line 129 of file kinetic_types_internal\&.h\&.
.SS "Com__Seagate__Kinetic__Proto__Command__Body KineticMessage::body"

.PP
Definition at line 130 of file kinetic_types_internal\&.h\&.
.SS "Com__Seagate__Kinetic__Proto__Command__Status KineticMessage::status"

.PP
Definition at line 131 of file kinetic_types_internal\&.h\&.
.SS "Com__Seagate__Kinetic__Proto__Command__Security KineticMessage::security"

.PP
Definition at line 132 of file kinetic_types_internal\&.h\&.
.SS "Com__Seagate__Kinetic__Proto__Command__Security__ACL KineticMessage::acl"

.PP
Definition at line 133 of file kinetic_types_internal\&.h\&.
.SS "Com__Seagate__Kinetic__Proto__Command__KeyValue KineticMessage::keyValue"

.PP
Definition at line 134 of file kinetic_types_internal\&.h\&.
.SS "Com__Seagate__Kinetic__Proto__Command__Range KineticMessage::keyRange"

.PP
Definition at line 135 of file kinetic_types_internal\&.h\&.
.SS "Com__Seagate__Kinetic__Proto__Command__Setup KineticMessage::setup"

.PP
Definition at line 136 of file kinetic_types_internal\&.h\&.
.SS "Com__Seagate__Kinetic__Proto__Command__GetLog KineticMessage::getLog"

.PP
Definition at line 137 of file kinetic_types_internal\&.h\&.
.SS "\fBCom__Seagate__Kinetic__Proto__Command__GetLog__Type\fP KineticMessage::getLogType"

.PP
Definition at line 138 of file kinetic_types_internal\&.h\&.
.SS "Com__Seagate__Kinetic__Proto__Command__GetLog__Device KineticMessage::getLogDevice"

.PP
Definition at line 139 of file kinetic_types_internal\&.h\&.
.SS "Com__Seagate__Kinetic__Proto__Command__PinOperation KineticMessage::pinOp"

.PP
Definition at line 140 of file kinetic_types_internal\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
