.TH "KineticConnection" 3 "Thu Sep 11 2014" "Version v0.6.0" "protobuf-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticConnection \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "bool \fBconnected\fP"
.br
.ti -1c
.RI "bool \fBnonBlocking\fP"
.br
.ti -1c
.RI "int \fBport\fP"
.br
.ti -1c
.RI "int \fBsocketDescriptor\fP"
.br
.ti -1c
.RI "int64_t \fBconnectionID\fP"
.br
.ti -1c
.RI "char \fBhost\fP [256]"
.br
.ti -1c
.RI "int64_t \fBclusterVersion\fP"
.br
.ti -1c
.RI "int64_t \fBidentity\fP"
.br
.ti -1c
.RI "uint8_t \fBkeyData\fP [128]"
.br
.ti -1c
.RI "\fBByteArray\fP \fBkey\fP"
.br
.ti -1c
.RI "int64_t \fBsequence\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 108 of file kinetic_types\&.h\&.
.SH "Field Documentation"
.PP 
.SS "bool KineticConnection::connected"

.PP
Definition at line 110 of file kinetic_types\&.h\&.
.SS "bool KineticConnection::nonBlocking"

.PP
Definition at line 111 of file kinetic_types\&.h\&.
.SS "int KineticConnection::port"

.PP
Definition at line 112 of file kinetic_types\&.h\&.
.SS "int KineticConnection::socketDescriptor"

.PP
Definition at line 113 of file kinetic_types\&.h\&.
.SS "int64_t KineticConnection::connectionID"

.PP
Definition at line 114 of file kinetic_types\&.h\&.
.SS "char KineticConnection::host[256]"

.PP
Definition at line 115 of file kinetic_types\&.h\&.
.SS "int64_t KineticConnection::clusterVersion"

.PP
Definition at line 121 of file kinetic_types\&.h\&.
.SS "int64_t KineticConnection::identity"

.PP
Definition at line 127 of file kinetic_types\&.h\&.
.SS "uint8_t KineticConnection::keyData[128]"

.PP
Definition at line 132 of file kinetic_types\&.h\&.
.SS "\fBByteArray\fP KineticConnection::key"

.PP
Definition at line 133 of file kinetic_types\&.h\&.
.SS "int64_t KineticConnection::sequence"

.PP
Definition at line 137 of file kinetic_types\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for protobuf-c from the source code\&.
