kinetic_client.h
NAME
kinetic_client.h -
SYNOPSIS
#include 'kinetic_types.h'
Functions
KineticClient * KineticClient_Init (KineticClientConfig *config)
Initializes the Kinetic API and configures logging destination.
void KineticClient_Shutdown (KineticClient *const client)
Performs shutdown/cleanup of the kinetic-c client lib.
KineticStatus KineticClient_CreateConnection (KineticSession *const session, KineticClient *const client)
Initializes the Kinetic API, configures logging destination, establishes a connection to the specified Kinetic Device, and establishes a session.
KineticStatus KineticClient_DestroyConnection (KineticSession *const session)
Closes the connection to a host.
KineticStatus KineticClient_NoOp (KineticSession const *const session)
Executes a NOOP command to test whether the Kinetic Device is operational.
KineticStatus KineticClient_Put (KineticSession const *const session, KineticEntry *const entry, KineticCompletionClosure *closure)
Executes a PUT command to store/update an entry on the Kinetic Device.
KineticStatus KineticClient_Flush (KineticSession const *const session, KineticCompletionClosure *closure)
Executes a FLUSHALLDATA command to flush pending PUTs or DELETEs.
KineticStatus KineticClient_Get (KineticSession const *const session, KineticEntry *const entry, KineticCompletionClosure *closure)
Executes a GET command to retrieve an entry from the Kinetic Device.
KineticStatus KineticClient_GetPrevious (KineticSession const *const session, KineticEntry *const entry, KineticCompletionClosure *closure)
Executes a GETPREVIOUS command to retrieve the next entry from the Kinetic Device.
KineticStatus KineticClient_GetNext (KineticSession const *const session, KineticEntry *const entry, KineticCompletionClosure *closure)
Executes a GETNEXT command to retrieve the next entry from the Kinetic Device.
KineticStatus KineticClient_Delete (KineticSession const *const session, KineticEntry *const entry, KineticCompletionClosure *closure)
Executes a DELETE command to delete an entry from the Kinetic Device.
KineticStatus KineticClient_GetKeyRange (KineticSession const *const session, KineticKeyRange *range, ByteBufferArray *keys, KineticCompletionClosure *closure)
Executes a GETKEYRANGE command to retrieve a set of keys in the range specified range from the Kinetic Device.
KineticStatus KineticClient_GetLog (KineticSession const *const session, KineticDeviceInfo_Type type, KineticDeviceInfo **info, KineticCompletionClosure *closure)
Executes a GETLOG command to retrieve specific configuration and/or operational data from the Kinetic Device.
void KineticClient_FreeDeviceInfo (KineticSession const *const session, KineticDeviceInfo *info)
Free the KineticDeviceInfo result from KineticClient_GetLog.
KineticStatus KineticClient_P2POperation (KineticSession const *const session, KineticP2P_Operation *const p2pOp, KineticCompletionClosure *closure)
Executes a PEER2PEERPUSH operation allows a client to instruct a Kinetic Device to copy a set of keys (and associated value and metadata) to another Kinetic Device.
KineticStatus KineticClient_InstantSecureErase (KineticSession const *const session)
Executes an InstantSecureErase command to erase all data from the Kinetic device.
Function Documentation
KineticClient* KineticClient_Init (KineticClientConfig *config)
Initializes the Kinetic API and configures logging destination.
Parameters:
config A configuration struct.
Returns:
Returns a pointer to a KineticClient. You need to pass this pointer to KineticClient_CreateConnection() to create new connections. Once you are finished will the KineticClient, and there are no active connections. The pointer should be release with KineticClient_Shutdown()
Definition at line 33 of file kinetic_client.c.
References KINETIC_CLIENT_DEFAULT_MAX_THREADPOOL_THREADS, KINETIC_CLIENT_DEFAULT_READER_THREADS, KINETIC_CLIENT_DEFAULT_WRITER_THREADS, KineticCalloc(), KineticFree(), KineticLogger_Init(), KineticPDU_InitBus(), KineticClientConfig::logFile, KineticClientConfig::logLevel, KineticClientConfig::maxThreadpoolThreads, KineticClientConfig::readerThreads, and KineticClientConfig::writerThreads.
void KineticClient_Shutdown (KineticClient *constclient)
Performs shutdown/cleanup of the kinetic-c client lib.
Parameters:
client The pointer returned from KineticClient_Init
Definition at line 59 of file kinetic_client.c.
References KineticFree(), KineticLogger_Close(), and KineticPDU_DeinitBus().
KineticStatus KineticClient_CreateConnection (KineticSession *constsession, KineticClient *constclient)
Initializes the Kinetic API, configures logging destination, establishes a connection to the specified Kinetic Device, and establishes a session.
Parameters:
session Configured KineticSession to connect .config KineticSessionConfig structure which must be configured by the client prior to creating the device connection. .host Host name or IP address to connect to .port Port to establish socket connection on .clusterVersion Cluster version to use for the session .identity Identity to use for the session .hmacKey Key to use for HMAC calculations (NULL-terminated string) .connection Pointer to dynamically allocated connection which will be populated upon establishment of a connection.
client The KineticClient pointer returned from KineticClient_Init()
Returns:
Returns the resulting KineticStatus, and session->connection will be populated with a session instance pointer upon success. The client should call KineticClient_DestroyConnection() in order to shutdown a connection and cleanup resources when done using a KineticSession.
Definition at line 66 of file kinetic_client.c.
References KineticSession::config, KineticSession::connection, ByteArray::data, KineticSessionConfig::hmacKey, KineticSessionConfig::host, Kinetic_GetStatusDescription(), KINETIC_STATUS_CONNECTION_ERROR, KINETIC_STATUS_HMAC_EMPTY, KINETIC_STATUS_HOST_EMPTY, KINETIC_STATUS_SESSION_EMPTY, KINETIC_STATUS_SUCCESS, KineticSession_Connect(), KineticSession_Create(), KineticSession_Destroy(), ByteArray::len, LOG0, LOGF0, and KineticSessionConfig::port.
KineticStatus KineticClient_DestroyConnection (KineticSession *constsession)
Closes the connection to a host.
Parameters:
session The connected KineticSession to close. The connection instance will be freed by this call after closing the connection.
Returns:
Returns the resulting KineticStatus.
Definition at line 107 of file kinetic_client.c.
References KineticSession::connection, KINETIC_STATUS_CONNECTION_ERROR, KINETIC_STATUS_SESSION_INVALID, KINETIC_STATUS_SUCCESS, KineticSession_Destroy(), KineticSession_Disconnect(), and LOG0.
KineticStatus KineticClient_NoOp (KineticSession const *constsession)
Executes a NOOP command to test whether the Kinetic Device is operational.
Parameters:
session The connected KineticSession to use for the operation.
Returns:
Returns the resulting KineticStatus.
Definition at line 127 of file kinetic_client.c.
References KineticSession::connection, KINETIC_STATUS_MEMORY_ERROR, KineticController_CreateOperation(), KineticController_ExecuteOperation(), and KineticOperation_BuildNoop().
KineticStatus KineticClient_Put (KineticSession const *constsession, KineticEntry *constentry, KineticCompletionClosure *closure)
Executes a PUT command to store/update an entry on the Kinetic Device.
Parameters:
session The connected KineticSession to use for the operation.
entry Key/value entry for object to store. 'value' must specify the data to be stored. If a closure is provided this pointer must remain valid until the closure callback is called.
closure Optional closure. If specified, operation will be executed in asynchronous mode, and closure callback will be called upon completion in another thread.
Returns:
Returns the resulting KineticStatus.
Definition at line 139 of file kinetic_client.c.
References ByteBuffer::array, KineticSession::connection, ByteArray::data, KINETIC_STATUS_MEMORY_ERROR, KineticController_CreateOperation(), KineticController_ExecuteOperation(), KineticOperation_BuildPut(), KineticConnection::pSession, and KineticEntry::value.
KineticStatus KineticClient_Flush (KineticSession const *constsession, KineticCompletionClosure *closure)
Executes a FLUSHALLDATA command to flush pending PUTs or DELETEs.
Parameters:
session The connected KineticSession to use for the operation.
closure Optional closure. If specified, operation will be executed in asynchronous mode, and closure callback will be called upon completion in another thread.
Returns:
Returns the resulting KineticStatus.
Definition at line 163 of file kinetic_client.c.
References KineticSession::connection, KINETIC_STATUS_MEMORY_ERROR, KineticController_CreateOperation(), KineticController_ExecuteOperation(), and KineticOperation_BuildFlush().
KineticStatus KineticClient_Get (KineticSession const *constsession, KineticEntry *constentry, KineticCompletionClosure *closure)
Executes a GET command to retrieve an entry from the Kinetic Device.
Parameters:
session The connected KineticSession to use for the operation.
entry Key/value entry for object to retrieve. 'value' will be populated unless 'metadataOnly' is set to 'true'. If a closure is provided this pointer must remain valid until the closure callback is called.
closure Optional closure. If specified, operation will be executed in asynchronous mode, and closure callback will be called upon completion in another thread.
Returns:
Returns the resulting KineticStatus.
Definition at line 234 of file kinetic_client.c.
References CMD_GET.
KineticStatus KineticClient_GetPrevious (KineticSession const *constsession, KineticEntry *constentry, KineticCompletionClosure *closure)
Executes a GETPREVIOUS command to retrieve the next entry from the Kinetic Device.
Parameters:
session The connected KineticSession to use for the operation.
entry Key/value entry for object to retrieve. 'value' will be populated unless 'metadataOnly' is set to 'true'. The key and value fields will be populated with the previous key and its corresponding value, according to lexicographical byte order. If a closure is provided this pointer must remain valid until the closure callback is called.
closure Optional closure. If specified, operation will be executed in asynchronous mode, and closure callback will be called upon completion in another thread.
Returns:
Returns the resulting KineticStatus.
Definition at line 241 of file kinetic_client.c.
References CMD_GET_PREVIOUS.
KineticStatus KineticClient_GetNext (KineticSession const *constsession, KineticEntry *constentry, KineticCompletionClosure *closure)
Executes a GETNEXT command to retrieve the next entry from the Kinetic Device.
Parameters:
session The connected KineticSession to use for the operation.
entry Key/value entry for object to retrieve. 'value' will be populated unless 'metadataOnly' is set to 'true'. The key and value fields will be populated with the next key and its corresponding value, according to lexicographical byte order. If a closure is provided this pointer must remain valid until the closure callback is called.
closure Optional closure. If specified, operation will be executed in asynchronous mode, and closure callback will be called upon completion in another thread.
Returns:
Returns the resulting KineticStatus.
Definition at line 248 of file kinetic_client.c.
References CMD_GET_NEXT.
KineticStatus KineticClient_Delete (KineticSession const *constsession, KineticEntry *constentry, KineticCompletionClosure *closure)
Executes a DELETE command to delete an entry from the Kinetic Device.
Parameters:
session The connected KineticSession to use for the operation.
entry Key/value entry for object to delete. 'value' is not used for this operation.
closure Optional closure. If specified, operation will be executed in asynchronous mode, and closure callback will be called upon completion in another thread.
Returns:
Returns the resulting KineticStatus.
Definition at line 255 of file kinetic_client.c.
References KineticSession::connection, KINETIC_STATUS_MEMORY_ERROR, KineticController_CreateOperation(), KineticController_ExecuteOperation(), and KineticOperation_BuildDelete().
KineticStatus KineticClient_GetKeyRange (KineticSession const *constsession, KineticKeyRange *range, ByteBufferArray *keys, KineticCompletionClosure *closure)
Executes a GETKEYRANGE command to retrieve a set of keys in the range specified range from the Kinetic Device.
Parameters:
session The connected KineticSession to use for the operation
range KineticKeyRange specifying keys to return
keys ByteBufferArray to store the retrieved keys. If a closure is provided, this must point to valid memory until the closure callback is called.
closure Optional closure. If specified, operation will be executed in asynchronous mode, and closure callback will be called upon completion in another thread.
Returns:
Returns 0 upon success, -1 or the Kinetic status code upon failure
Definition at line 273 of file kinetic_client.c.
References ByteBufferArray::buffers, KineticSession::connection, ByteBufferArray::count, KINETIC_STATUS_MEMORY_ERROR, KineticController_CreateOperation(), KineticController_ExecuteOperation(), and KineticOperation_BuildGetKeyRange().
KineticStatus KineticClient_GetLog (KineticSession const *constsession, KineticDeviceInfo_Typetype, KineticDeviceInfo **info, KineticCompletionClosure *closure)
Executes a GETLOG command to retrieve specific configuration and/or operational data from the Kinetic Device.
Parameters:
session The connected KineticSession to use for the operation
type KineticLogDataType specifying data type to retrieve.
info KineticDeviceInfo pointer, which will be assigned to a dynamically allocated structure populated with the requested data, if successful. The client should call free() on this pointer in order to free the root and any nested structures.
closure Optional closure. If specified, operation will be executed in asynchronous mode, and closure callback will be called upon completion in another thread.
Returns:
Returns 0 upon success, -1 or the Kinetic status code upon failure
Definition at line 295 of file kinetic_client.c.
References KineticSession::connection, KINETIC_STATUS_MEMORY_ERROR, KineticController_CreateOperation(), KineticController_ExecuteOperation(), and KineticOperation_BuildGetLog().
void KineticClient_FreeDeviceInfo (KineticSession const *constsession, KineticDeviceInfo *info)
Free the KineticDeviceInfo result from KineticClient_GetLog.
Parameters:
session The connected KineticSession to use for the operation
info The KineticDeviceInfo result to free.
Definition at line 314 of file kinetic_client.c.
References KineticDeviceInfo_Free().
KineticStatus KineticClient_P2POperation (KineticSession const *constsession, KineticP2P_Operation *constp2pOp, KineticCompletionClosure *closure)
Executes a PEER2PEERPUSH operation allows a client to instruct a Kinetic Device to copy a set of keys (and associated value and metadata) to another Kinetic Device.
Parameters:
session The connected KineticSession to use for the operation
p2pOp KineticP2P_Operation pointer. This pointer needs to remain valid during the duration of the operation. The results of P2P operation(s) will be stored in the resultStatus field of this structure.
closure Optional closure. If specified, operation will be executed in asynchronous mode, and closure callback will be called upon completion in another thread.
Returns:
Returns 0 upon success, -1 or the Kinetic status code upon failure. Note that P2P operations can be nested. This status code pertains to the initial top-level P2P operation. You'll need to check the resultStatus in the p2pOp structure to check the status of the individual P2P operations.
Definition at line 326 of file kinetic_client.c.
References KineticSession::connection, KINETIC_STATUS_MEMORY_ERROR, KINETIC_STATUS_SUCCESS, KineticController_CreateOperation(), KineticController_ExecuteOperation(), KineticOperation_BuildP2POperation(), and KineticOperation_Complete().
KineticStatus KineticClient_InstantSecureErase (KineticSession const *constsession)
Executes an InstantSecureErase command to erase all data from the Kinetic device.
Parameters:
session The connected KineticSession to use for the operation.
Returns:
Returns the resulting KineticStatus.
Definition at line 352 of file kinetic_client.c.
References KineticSession::connection, KINETIC_STATUS_MEMORY_ERROR, KineticController_CreateOperation(), KineticController_ExecuteOperation(), and KineticOperation_BuildInstantSecureErase().
Author
Generated automatically by Doxygen for kinetic-c from the source code.