.TH "kinetic_socket.c" 3 "Thu Aug 7 2014" "Version v0.4.0" "protobuf-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kinetic_socket.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'kinetic_socket\&.h'\fP
.br
\fC#include 'kinetic_logger\&.h'\fP
.br
\fC#include 'protobuf-c/protobuf-c\&.h'\fP
.br
\fC#include 'socket99\&.h'\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include <fcntl\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include <sys/socket\&.h>\fP
.br
\fC#include <netinet/in\&.h>\fP
.br
\fC#include <arpa/inet\&.h>\fP
.br
\fC#include <netdb\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBKineticSocket_GetSocketError\fP (int fd)"
.br
.ti -1c
.RI "bool \fBKineticSocket_HaveInput\fP (int fd, double timeout)"
.br
.ti -1c
.RI "bool \fBKineticSocket_FlushSocketBeforeClose\fP (int fd)"
.br
.ti -1c
.RI "bool \fBKineticSocket_CloseSocket\fP (int fd)"
.br
.ti -1c
.RI "int \fBKineticSocket_Connect\fP (char *host, int port, bool blocking)"
.br
.ti -1c
.RI "void \fBKineticSocket_Close\fP (int socketDescriptor)"
.br
.ti -1c
.RI "bool \fBKineticSocket_Read\fP (int socketDescriptor, void *buffer, size_t length)"
.br
.ti -1c
.RI "bool \fBKineticSocket_ReadProtobuf\fP (int socketDescriptor, \fBKineticProto\fP **message, void *buffer, size_t length)"
.br
.ti -1c
.RI "bool \fBKineticSocket_Write\fP (int socketDescriptor, const void *buffer, size_t length)"
.br
.ti -1c
.RI "bool \fBKineticSocket_WriteProtobuf\fP (int socketDescriptor, const \fBKineticProto\fP *proto)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int KineticSocket_GetSocketError (intfd)"

.PP
Definition at line 39 of file kinetic_socket\&.c\&.
.PP
References LOG\&.
.SS "bool KineticSocket_HaveInput (intfd, doubletimeout)"

.PP
Definition at line 57 of file kinetic_socket\&.c\&.
.PP
References LOG\&.
.SS "bool KineticSocket_FlushSocketBeforeClose (intfd)"

.PP
Definition at line 88 of file kinetic_socket\&.c\&.
.PP
References KineticSocket_HaveInput()\&.
.SS "bool KineticSocket_CloseSocket (intfd)"

.PP
Definition at line 113 of file kinetic_socket\&.c\&.
.PP
References KineticSocket_FlushSocketBeforeClose(), KineticSocket_GetSocketError(), and LOG\&.
.SS "int KineticSocket_Connect (char *host, intport, boolblocking)"

.PP
Definition at line 170 of file kinetic_socket\&.c\&.
.PP
References LOG, and LOGF\&.
.SS "void KineticSocket_Close (intsocketDescriptor)"

.PP
Definition at line 253 of file kinetic_socket\&.c\&.
.PP
References LOG\&.
.SS "bool KineticSocket_Read (intsocketDescriptor, void *buffer, size_tlength)"

.PP
Definition at line 276 of file kinetic_socket\&.c\&.
.PP
References LOG\&.
.SS "bool KineticSocket_ReadProtobuf (intsocketDescriptor, \fBKineticProto\fP **message, void *buffer, size_tlength)"

.PP
Definition at line 332 of file kinetic_socket\&.c\&.
.PP
References KineticProto_unpack(), KineticSocket_Read(), and LOG\&.
.SS "bool KineticSocket_Write (intsocketDescriptor, const void *buffer, size_tlength)"

.PP
Definition at line 368 of file kinetic_socket\&.c\&.
.PP
References LOG\&.
.SS "bool KineticSocket_WriteProtobuf (intsocketDescriptor, const \fBKineticProto\fP *proto)"

.PP
Definition at line 405 of file kinetic_socket\&.c\&.
.PP
References KineticProto_get_packed_size(), KineticProto_pack(), KineticSocket_Write(), and LOG\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for protobuf-c from the source code\&.
