.TH "KineticSerialAllocator" 3 "Wed Feb 11 2015" "Version v0.11.1" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticSerialAllocator \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_types_internal\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t * \fBbuffer\fP"
.br
.ti -1c
.RI "size_t \fBused\fP"
.br
.ti -1c
.RI "size_t \fBtotal\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 186 of file kinetic_types_internal\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint8_t* KineticSerialAllocator::buffer"

.PP
Definition at line 187 of file kinetic_types_internal\&.h\&.
.SS "size_t KineticSerialAllocator::used"

.PP
Definition at line 188 of file kinetic_types_internal\&.h\&.
.SS "size_t KineticSerialAllocator::total"

.PP
Definition at line 189 of file kinetic_types_internal\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
