.TH "kinetic_types.c" 3 "Tue Nov 4 2014" "Version v0.8.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kinetic_types.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'kinetic_types_internal\&.h'\fP
.br
\fC#include 'kinetic_types\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "const char * \fBKinetic_GetStatusDescription\fP (\fBKineticStatus\fP status)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "const char* Kinetic_GetStatusDescription (\fBKineticStatus\fPstatus)"

.PP
Definition at line 53 of file kinetic_types\&.c\&.
.PP
References KINETIC_STATUS_COUNT\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
