.TH "KineticDeviceInfo_Statistics" 3 "Tue Jan 27 2015" "Version v0.11.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticDeviceInfo_Statistics \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBKineticMessageType\fP \fBmessageType\fP"
.br
.ti -1c
.RI "uint64_t \fBcount\fP"
.br
.ti -1c
.RI "uint64_t \fBbytes\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 367 of file kinetic_types\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBKineticMessageType\fP KineticDeviceInfo_Statistics::messageType"

.PP
Definition at line 368 of file kinetic_types\&.h\&.
.SS "uint64_t KineticDeviceInfo_Statistics::count"

.PP
Definition at line 369 of file kinetic_types\&.h\&.
.SS "uint64_t KineticDeviceInfo_Statistics::bytes"

.PP
Definition at line 370 of file kinetic_types\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
