kinetic_callbacks.h
NAME
kinetic_callbacks.h -
SYNOPSIS
#include 'kinetic_types_internal.h'
Functions
KineticStatus KineticCallbacks_Basic (KineticOperation *const operation, KineticStatus const status)
KineticStatus KineticCallbacks_Put (KineticOperation *const operation, KineticStatus const status)
KineticStatus KineticCallbacks_Get (KineticOperation *const operation, KineticStatus const status)
KineticStatus KineticCallbacks_Delete (KineticOperation *const operation, KineticStatus const status)
KineticStatus KineticCallbacks_GetKeyRange (KineticOperation *const operation, KineticStatus const status)
KineticStatus KineticCallbacks_P2POperation (KineticOperation *const operation, KineticStatus const status)
KineticStatus KineticCallbacks_GetLog (KineticOperation *const operation, KineticStatus const status)
KineticStatus KineticCallbacks_SetClusterVersion (KineticOperation *const operation, KineticStatus const status)
KineticStatus KineticCallbacks_SetACL (KineticOperation *const operation, KineticStatus const status)
KineticStatus KineticCallbacks_UpdateFirmware (KineticOperation *const operation, KineticStatus const status)
Function Documentation
KineticStatus KineticCallbacks_Basic (KineticOperation *constoperation, KineticStatus conststatus)
Definition at line 43 of file kinetic_callbacks.c.
References KINETIC_ASSERT.
KineticStatus KineticCallbacks_Put (KineticOperation *constoperation, KineticStatus conststatus)
Definition at line 50 of file kinetic_callbacks.c.
References ByteBuffer::array, BYTE_BUFFER_NONE, ByteBuffer_Append(), ByteBuffer_Reset(), ByteBuffer::bytesUsed, ByteArray::data, KineticEntry::dbVersion, KINETIC_ASSERT, KINETIC_STATUS_SUCCESS, ByteArray::len, and KineticEntry::newVersion.
KineticStatus KineticCallbacks_Get (KineticOperation *constoperation, KineticStatus conststatus)
Definition at line 80 of file kinetic_callbacks.c.
References ByteBuffer_AppendArray(), ByteBuffer_IsNull(), Copy_Com__Seagate__Kinetic__Proto__Command__KeyValue_to_KineticEntry(), KINETIC_ASSERT, KINETIC_STATUS_BUFFER_OVERRUN, KINETIC_STATUS_SUCCESS, and KineticResponse_GetKeyValue().
KineticStatus KineticCallbacks_Delete (KineticOperation *constoperation, KineticStatus conststatus)
Definition at line 110 of file kinetic_callbacks.c.
References KINETIC_ASSERT.
KineticStatus KineticCallbacks_GetKeyRange (KineticOperation *constoperation, KineticStatus conststatus)
Definition at line 118 of file kinetic_callbacks.c.
References Copy_Com__Seagate__Kinetic__Proto__Command__Range_to_ByteBufferArray(), KINETIC_ASSERT, KINETIC_STATUS_BUFFER_OVERRUN, KINETIC_STATUS_SUCCESS, and KineticResponse_GetKeyRange().
KineticStatus KineticCallbacks_P2POperation (KineticOperation *constoperation, KineticStatus conststatus)
Definition at line 168 of file kinetic_callbacks.c.
References KINETIC_ASSERT, KINETIC_STATUS_SUCCESS, KineticAllocator_FreeP2PProtobuf(), and populateP2PStatusCodes().
KineticStatus KineticCallbacks_GetLog (KineticOperation *constoperation, KineticStatus conststatus)
Definition at line 194 of file kinetic_callbacks.c.
References KINETIC_ASSERT, KINETIC_STATUS_OPERATION_FAILED, KINETIC_STATUS_SUCCESS, and KineticLogInfo_Create().
KineticStatus KineticCallbacks_SetClusterVersion (KineticOperation *constoperation, KineticStatus conststatus)
Definition at line 215 of file kinetic_callbacks.c.
References KINETIC_ASSERT, KINETIC_STATUS_SUCCESS, and KineticSession_SetClusterVersion().
KineticStatus KineticCallbacks_SetACL (KineticOperation *constoperation, KineticStatus conststatus)
Definition at line 226 of file kinetic_callbacks.c.
References ACL::ACL_count, ACL::ACLs, KINETIC_ASSERT, and KineticACL_Free().
KineticStatus KineticCallbacks_UpdateFirmware (KineticOperation *constoperation, KineticStatus conststatus)
Definition at line 244 of file kinetic_callbacks.c.
References KINETIC_ASSERT.
Author
Generated automatically by Doxygen for kinetic-c from the source code.