.TH "kinetic_connection.h" 3 "Wed Oct 15 2014" "Version v0.7.0" "protobuf-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kinetic_connection.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'kinetic_types_internal\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBKineticSessionHandle\fP \fBKineticConnection_NewConnection\fP (const \fBKineticSession\fP *const config)"
.br
.ti -1c
.RI "void \fBKineticConnection_FreeConnection\fP (\fBKineticSessionHandle\fP *const handle)"
.br
.ti -1c
.RI "\fBKineticConnection\fP * \fBKineticConnection_FromHandle\fP (\fBKineticSessionHandle\fP handle)"
.br
.ti -1c
.RI "\fBKineticStatus\fP \fBKineticConnection_Connect\fP (\fBKineticConnection\fP *const connection)"
.br
.ti -1c
.RI "\fBKineticStatus\fP \fBKineticConnection_Disconnect\fP (\fBKineticConnection\fP *const connection)"
.br
.ti -1c
.RI "void \fBKineticConnection_IncrementSequence\fP (\fBKineticConnection\fP *const connection)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBKineticSessionHandle\fP KineticConnection_NewConnection (const \fBKineticSession\fP *constconfig)"

.PP
Definition at line 31 of file kinetic_connection\&.c\&.
.PP
References KINETIC_CONNECTION_INIT, KINETIC_HANDLE_INVALID, KINETIC_SESSIONS_MAX, and KineticConnection::session\&.
.SS "void KineticConnection_FreeConnection (\fBKineticSessionHandle\fP *consthandle)"

.PP
Definition at line 51 of file kinetic_connection\&.c\&.
.PP
References KineticConnection::connected, KINETIC_HANDLE_INVALID, and KineticConnection_FromHandle()\&.
.SS "\fBKineticConnection\fP* KineticConnection_FromHandle (\fBKineticSessionHandle\fPhandle)"

.PP
Definition at line 63 of file kinetic_connection\&.c\&.
.PP
References KINETIC_HANDLE_INVALID, and KINETIC_SESSIONS_MAX\&.
.SS "\fBKineticStatus\fP KineticConnection_Connect (\fBKineticConnection\fP *constconnection)"

.PP
Definition at line 70 of file kinetic_connection\&.c\&.
.PP
References KineticConnection::connected, KineticSession::host, KINETIC_SOCKET_DESCRIPTOR_INVALID, KINETIC_STATUS_CONNECTION_ERROR, KINETIC_STATUS_SESSION_EMPTY, KINETIC_STATUS_SUCCESS, KineticSocket_Connect(), LOG, KineticSession::nonBlocking, KineticSession::port, KineticConnection::session, and KineticConnection::socket\&.
.SS "\fBKineticStatus\fP KineticConnection_Disconnect (\fBKineticConnection\fP *constconnection)"

.PP
Definition at line 92 of file kinetic_connection\&.c\&.
.PP
References KINETIC_HANDLE_INVALID, KINETIC_STATUS_SESSION_INVALID, KINETIC_STATUS_SUCCESS, and KineticConnection::socket\&.
.SS "void KineticConnection_IncrementSequence (\fBKineticConnection\fP *constconnection)"

.PP
Definition at line 103 of file kinetic_connection\&.c\&.
.PP
References KineticConnection::sequence\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for protobuf-c from the source code\&.
