kinetic_api.h
NAME
kinetic_api.h -
SYNOPSIS
#include 'kinetic_types.h'
#include 'kinetic_exchange.h'
#include 'kinetic_pdu.h'
#include 'kinetic_operation.h'
Functions
void KineticApi_Init (const char *logFile)
Initializes the Kinetic API andcsonfigures logging destination.
bool KineticApi_Connect (KineticConnection *connection, const char *host, int port, bool blocking)
Establishes a Kinetic protocol socket connection to a host.
bool KineticApi_ConfigureExchange (KineticExchange *exchange, KineticConnection *connection, int64_t clusterVersion, int64_t identity, const char *key, size_t keyLength)
Initializes and configures a Kinetic exchange.
KineticOperation KineticApi_CreateOperation (KineticExchange *exchange, KineticPDU *request, KineticMessage *requestMsg, KineticPDU *response)
Creates and initializes a Kinetic operation.
KineticProto_Status_StatusCode KineticApi_NoOp (KineticOperation *operation)
Executes a NOOP command to test whether the Kinetic Device is operational.
Function Documentation
void KineticApi_Init (const char *logFile)
Initializes the Kinetic API andcsonfigures logging destination.
Parameters:
logFile Path to log file. Specify NULL to log to STDOUT.
Definition at line 27 of file kinetic_api.c.
References KineticLogger_Init().
bool KineticApi_Connect (KineticConnection *connection, const char *host, intport, boolblocking)
Establishes a Kinetic protocol socket connection to a host.
Parameters:
connection KineticConnection instance to configure with connection info
host Host name or IP address to connect to
port Port to establish socket connection on
blocking Set to true for blocking or false for non-bloocking I/O
Returns:
Returns true if connection succeeded
Definition at line 32 of file kinetic_api.c.
References KineticConnection::connected, KineticConnection_Connect(), KineticConnection_Init(), LOG, and KineticConnection::socketDescriptor.
bool KineticApi_ConfigureExchange (KineticExchange *exchange, KineticConnection *connection, int64_tclusterVersion, int64_tidentity, const char *key, size_tkeyLength)
Initializes and configures a Kinetic exchange.
Parameters:
exchange KineticExchange instance to configure with exchange info
connection KineticConnection to associate with exchange
clusterVersion Cluster version for the exchange
identity Identity to use for the exchange
key Key to use for HMAC calculations
keyLength Length of HMAC key
Returns:
Returns true if configuration succeeded
Definition at line 55 of file kinetic_api.c.
References KineticExchange_ConfigureConnectionID(), KineticExchange_Init(), KineticExchange_SetClusterVersion(), and LOG.
KineticOperation KineticApi_CreateOperation (KineticExchange *exchange, KineticPDU *request, KineticMessage *requestMsg, KineticPDU *response)
Creates and initializes a Kinetic operation.
Parameters:
exchange KineticExchange instance to populate with exchange info
request KineticPDU instance to use for request
requestMsg KineticMessage instance to use for request
response KineticPDU instance to use for reponse
Returns:
Returns a configured operation instance
Definition at line 88 of file kinetic_api.c.
References KineticOperation::exchange, KineticMessage_Init(), KineticPDU_Init(), LOG, KineticPDU::message, KineticPDU::proto, KineticOperation::request, and KineticOperation::response.
KineticProto_Status_StatusCode KineticApi_NoOp (KineticOperation *operation)
Executes a NOOP command to test whether the Kinetic Device is operational.
Parameters:
operation KineticOperation instance to use for the operation
Returns:
Returns the resultant status code
Definition at line 136 of file kinetic_api.c.
References KineticExchange::connection, KineticOperation::exchange, KineticPDU::exchange, KINETIC_PROTO_STATUS_STATUS_CODE_INVALID_STATUS_CODE, KineticExchange_IncrementSequence(), KineticOperation_BuildNoop(), KineticPDU_Receive(), KineticPDU_Send(), KineticPDU::message, KineticPDU::proto, KineticOperation::request, and KineticOperation::response.
Author
Generated automatically by Doxygen for protobuf-c from the source code.