.TH "kinetic_controller.h" 3 "Fri Mar 13 2015" "Version v0.12.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kinetic_controller.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'kinetic_types_internal\&.h'\fP
.br
\fC#include 'bus\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBKineticStatus\fP \fBKineticController_Init\fP (KineticSession *const session)"
.br
.ti -1c
.RI "\fBKineticStatus\fP \fBKineticController_ExecuteOperation\fP (KineticOperation *operation, \fBKineticCompletionClosure\fP *closure)"
.br
.ti -1c
.RI "void \fBKineticController_HandleUnexpectedResponse\fP (void *msg, int64_t seq_id, void *bus_udata, void *socket_udata)"
.br
.ti -1c
.RI "void \fBKineticController_HandleResult\fP (\fBbus_msg_result_t\fP *res, void *udata)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBKineticStatus\fP KineticController_Init (KineticSession *constsession)"

.SS "\fBKineticStatus\fP KineticController_ExecuteOperation (KineticOperation *operation, \fBKineticCompletionClosure\fP *closure)"

.PP
Definition at line 59 of file kinetic_controller\&.c\&.
.PP
References DefaultClosure(), KINETIC_ASSERT, KINETIC_STATUS_INVALID, KINETIC_STATUS_SESSION_TERMINATED, KINETIC_STATUS_SOCKET_ERROR, KINETIC_STATUS_SUCCESS, KineticOperation_SendRequest(), KineticSession_Disconnect(), and KineticSession_GetTerminationStatus()\&.
.SS "void KineticController_HandleUnexpectedResponse (void *msg, int64_tseq_id, void *bus_udata, void *socket_udata)"

.PP
Definition at line 179 of file kinetic_controller\&.c\&.
.PP
References COM__SEAGATE__KINETIC__PROTO__MESSAGE__AUTH_TYPE__UNSOLICITEDSTATUS, KineticAllocator_FreeKineticResponse(), KineticLogger_LogPrintf(), KineticLogger_LogProtobuf(), KineticResourceWaiter_SetAvailable(), KineticResponse_GetConnectionID(), KineticResponse_GetProtobufLength(), KineticResponse_GetStatus(), KineticResponse_GetValueLength(), KineticSession_SetConnectionID(), KineticSession_SetTerminationStatus(), LOG0, LOGF2, and KineticResponse::proto\&.
.SS "void KineticController_HandleResult (\fBbus_msg_result_t\fP *res, void *udata)"

.PP
Definition at line 240 of file kinetic_controller\&.c\&.
.PP
References bus_error_string(), BUS_SEND_RX_TIMEOUT, bus_to_kinetic_status(), KineticResponse::command, KineticResponse::header, KINETIC_ASSERT, Kinetic_GetStatusDescription(), KINETIC_STATUS_SUCCESS, KineticLogger_LogHeader(), KineticLogger_LogProtobuf(), KineticOperation_Complete(), KineticResponse_GetProtobufLength(), KineticResponse_GetStatus(), KineticResponse_GetValueLength(), LOG0, LOGF0, LOGF2, KineticResponse::proto, bus_msg_result_t::response, bus_msg_result_t::status, and bus_msg_result_t::u\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
