.TH "KineticExchange" 3 "Thu Aug 7 2014" "Version v0.4.0" "protobuf-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticExchange \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_exchange\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "bool \fBhas_clusterVersion\fP"
.br
.ti -1c
.RI "int64_t \fBclusterVersion\fP"
.br
.ti -1c
.RI "int64_t \fBidentity\fP"
.br
.ti -1c
.RI "bool \fBhas_key\fP"
.br
.ti -1c
.RI "size_t \fBkeyLength\fP"
.br
.ti -1c
.RI "char \fBkey\fP [128+1]"
.br
.ti -1c
.RI "int64_t \fBconnectionID\fP"
.br
.ti -1c
.RI "int64_t \fBsequence\fP"
.br
.ti -1c
.RI "\fBKineticConnection\fP * \fBconnection\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 28 of file kinetic_exchange\&.h\&.
.SH "Field Documentation"
.PP 
.SS "bool KineticExchange::has_clusterVersion"

.PP
Definition at line 32 of file kinetic_exchange\&.h\&.
.SS "int64_t KineticExchange::clusterVersion"

.PP
Definition at line 38 of file kinetic_exchange\&.h\&.
.SS "int64_t KineticExchange::identity"

.PP
Definition at line 44 of file kinetic_exchange\&.h\&.
.SS "bool KineticExchange::has_key"

.PP
Definition at line 49 of file kinetic_exchange\&.h\&.
.SS "size_t KineticExchange::keyLength"

.PP
Definition at line 50 of file kinetic_exchange\&.h\&.
.SS "char KineticExchange::key[128+1]"

.PP
Definition at line 51 of file kinetic_exchange\&.h\&.
.SS "int64_t KineticExchange::connectionID"

.PP
Definition at line 59 of file kinetic_exchange\&.h\&.
.SS "int64_t KineticExchange::sequence"

.PP
Definition at line 63 of file kinetic_exchange\&.h\&.
.SS "\fBKineticConnection\fP* KineticExchange::connection"

.PP
Definition at line 66 of file kinetic_exchange\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for protobuf-c from the source code\&.
