.TH "kinetic_proto.h" 3 "Wed Sep 10 2014" "Version v0.6.0" "protobuf-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kinetic_proto.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'protobuf-c/protobuf-c\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBKineticProto_Command\fP"
.br
.ti -1c
.RI "struct \fBKineticProto_Header\fP"
.br
.ti -1c
.RI "struct \fBKineticProto_Body\fP"
.br
.ti -1c
.RI "struct \fBKineticProto_Status\fP"
.br
.ti -1c
.RI "struct \fBKineticProto_KeyValue\fP"
.br
.ti -1c
.RI "struct \fBKineticProto_Range\fP"
.br
.ti -1c
.RI "struct \fBKineticProto_Setup\fP"
.br
.ti -1c
.RI "struct \fBKineticProto_P2POperation_Operation\fP"
.br
.ti -1c
.RI "struct \fBKineticProto_P2POperation_Peer\fP"
.br
.ti -1c
.RI "struct \fBKineticProto_P2POperation\fP"
.br
.ti -1c
.RI "struct \fBKineticProto_GetLog_Utilization\fP"
.br
.ti -1c
.RI "struct \fBKineticProto_GetLog_Temperature\fP"
.br
.ti -1c
.RI "struct \fBKineticProto_GetLog_Capacity\fP"
.br
.ti -1c
.RI "struct \fBKineticProto_GetLog_Configuration_Interface\fP"
.br
.ti -1c
.RI "struct \fBKineticProto_GetLog_Configuration\fP"
.br
.ti -1c
.RI "struct \fBKineticProto_GetLog_Statistics\fP"
.br
.ti -1c
.RI "struct \fBKineticProto_GetLog_Limits\fP"
.br
.ti -1c
.RI "struct \fBKineticProto_GetLog_Device\fP"
.br
.ti -1c
.RI "struct \fBKineticProto_GetLog\fP"
.br
.ti -1c
.RI "struct \fBKineticProto_Security_ACL_Scope\fP"
.br
.ti -1c
.RI "struct \fBKineticProto_Security_ACL\fP"
.br
.ti -1c
.RI "struct \fBKineticProto_Security\fP"
.br
.ti -1c
.RI "struct \fB_KineticProto\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBKINETIC_PROTO_COMMAND__INIT\fP"
.br
.ti -1c
.RI "#define \fBKINETIC_PROTO_HEADER__INIT\fP"
.br
.ti -1c
.RI "#define \fBKINETIC_PROTO_BODY__INIT\fP"
.br
.ti -1c
.RI "#define \fBKINETIC_PROTO_STATUS__INIT\fP"
.br
.ti -1c
.RI "#define \fBKINETIC_PROTO_KEY_VALUE__INIT\fP"
.br
.ti -1c
.RI "#define \fBKINETIC_PROTO_RANGE__INIT\fP"
.br
.ti -1c
.RI "#define \fBKINETIC_PROTO_SETUP__INIT\fP"
.br
.ti -1c
.RI "#define \fBKINETIC_PROTO_P2_POPERATION_OPERATION__INIT\fP"
.br
.ti -1c
.RI "#define \fBKINETIC_PROTO_P2_POPERATION_PEER__INIT\fP"
.br
.ti -1c
.RI "#define \fBKINETIC_PROTO_P2_POPERATION__INIT\fP"
.br
.ti -1c
.RI "#define \fBKINETIC_PROTO_GET_LOG_UTILIZATION__INIT\fP"
.br
.ti -1c
.RI "#define \fBKINETIC_PROTO_GET_LOG_TEMPERATURE__INIT\fP"
.br
.ti -1c
.RI "#define \fBKINETIC_PROTO_GET_LOG_CAPACITY__INIT\fP"
.br
.ti -1c
.RI "#define \fBKINETIC_PROTO_GET_LOG_CONFIGURATION_INTERFACE__INIT\fP"
.br
.ti -1c
.RI "#define \fBKINETIC_PROTO_GET_LOG_CONFIGURATION__INIT\fP"
.br
.ti -1c
.RI "#define \fBKINETIC_PROTO_GET_LOG_STATISTICS__INIT\fP"
.br
.ti -1c
.RI "#define \fBKINETIC_PROTO_GET_LOG_LIMITS__INIT\fP"
.br
.ti -1c
.RI "#define \fBKINETIC_PROTO_GET_LOG_DEVICE__INIT\fP"
.br
.ti -1c
.RI "#define \fBKINETIC_PROTO_GET_LOG__INIT\fP"
.br
.ti -1c
.RI "#define \fBKINETIC_PROTO_SECURITY_ACL_SCOPE__INIT\fP"
.br
.ti -1c
.RI "#define \fBKINETIC_PROTO_SECURITY_ACL__INIT\fP"
.br
.ti -1c
.RI "#define \fBKINETIC_PROTO_SECURITY__INIT\fP"
.br
.ti -1c
.RI "#define \fBKINETIC_PROTO__INIT\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef 
.br
typedefPROTOBUF_C__BEGIN_DECLS 
.br
struct \fB_KineticProto\fP \fBKineticProto\fP"
.br
.ti -1c
.RI "typedef void(* \fBKineticProto_Command_Closure\fP )(const KineticProto_Command *message, void *closure_data)"
.br
.ti -1c
.RI "typedef void(* \fBKineticProto_Header_Closure\fP )(const KineticProto_Header *message, void *closure_data)"
.br
.ti -1c
.RI "typedef void(* \fBKineticProto_Body_Closure\fP )(const KineticProto_Body *message, void *closure_data)"
.br
.ti -1c
.RI "typedef void(* \fBKineticProto_Status_Closure\fP )(const KineticProto_Status *message, void *closure_data)"
.br
.ti -1c
.RI "typedef void(* \fBKineticProto_KeyValue_Closure\fP )(const KineticProto_KeyValue *message, void *closure_data)"
.br
.ti -1c
.RI "typedef void(* \fBKineticProto_Range_Closure\fP )(const KineticProto_Range *message, void *closure_data)"
.br
.ti -1c
.RI "typedef void(* \fBKineticProto_Setup_Closure\fP )(const KineticProto_Setup *message, void *closure_data)"
.br
.ti -1c
.RI "typedef void(* \fBKineticProto_P2POperation_Operation_Closure\fP )(const KineticProto_P2POperation_Operation *message, void *closure_data)"
.br
.ti -1c
.RI "typedef void(* \fBKineticProto_P2POperation_Peer_Closure\fP )(const KineticProto_P2POperation_Peer *message, void *closure_data)"
.br
.ti -1c
.RI "typedef void(* \fBKineticProto_P2POperation_Closure\fP )(const KineticProto_P2POperation *message, void *closure_data)"
.br
.ti -1c
.RI "typedef void(* \fBKineticProto_GetLog_Utilization_Closure\fP )(const KineticProto_GetLog_Utilization *message, void *closure_data)"
.br
.ti -1c
.RI "typedef void(* \fBKineticProto_GetLog_Temperature_Closure\fP )(const KineticProto_GetLog_Temperature *message, void *closure_data)"
.br
.ti -1c
.RI "typedef void(* \fBKineticProto_GetLog_Capacity_Closure\fP )(const KineticProto_GetLog_Capacity *message, void *closure_data)"
.br
.ti -1c
.RI "typedef void(* \fBKineticProto_GetLog_Configuration_Interface_Closure\fP )(const KineticProto_GetLog_Configuration_Interface *message, void *closure_data)"
.br
.ti -1c
.RI "typedef void(* \fBKineticProto_GetLog_Configuration_Closure\fP )(const KineticProto_GetLog_Configuration *message, void *closure_data)"
.br
.ti -1c
.RI "typedef void(* \fBKineticProto_GetLog_Statistics_Closure\fP )(const KineticProto_GetLog_Statistics *message, void *closure_data)"
.br
.ti -1c
.RI "typedef void(* \fBKineticProto_GetLog_Limits_Closure\fP )(const KineticProto_GetLog_Limits *message, void *closure_data)"
.br
.ti -1c
.RI "typedef void(* \fBKineticProto_GetLog_Device_Closure\fP )(const KineticProto_GetLog_Device *message, void *closure_data)"
.br
.ti -1c
.RI "typedef void(* \fBKineticProto_GetLog_Closure\fP )(const KineticProto_GetLog *message, void *closure_data)"
.br
.ti -1c
.RI "typedef void(* \fBKineticProto_Security_ACL_Scope_Closure\fP )(const KineticProto_Security_ACL_Scope *message, void *closure_data)"
.br
.ti -1c
.RI "typedef void(* \fBKineticProto_Security_ACL_Closure\fP )(const KineticProto_Security_ACL *message, void *closure_data)"
.br
.ti -1c
.RI "typedef void(* \fBKineticProto_Security_Closure\fP )(const KineticProto_Security *message, void *closure_data)"
.br
.ti -1c
.RI "typedef void(* \fBKineticProto_Closure\fP )(const \fBKineticProto\fP *message, void *closure_data)"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBKineticProto_Status_StatusCode\fP "
.br
.ti -1c
.RI "enum \fBKineticProto_GetLog_Type\fP "
.br
.ti -1c
.RI "enum \fBKineticProto_Security_ACL_HMACAlgorithm\fP "
.br
.ti -1c
.RI "enum \fBKineticProto_Security_ACL_Permission\fP "
.br
.ti -1c
.RI "enum \fBKineticProto_Synchronization\fP "
.br
.ti -1c
.RI "enum \fBKineticProto_Algorithm\fP "
.br
.ti -1c
.RI "enum \fBKineticProto_MessageType\fP "
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBKineticProto_command__init\fP (KineticProto_Command *message)"
.br
.ti -1c
.RI "void \fBKineticProto_header__init\fP (KineticProto_Header *message)"
.br
.ti -1c
.RI "void \fBKineticProto_body__init\fP (KineticProto_Body *message)"
.br
.ti -1c
.RI "void \fBKineticProto_status__init\fP (KineticProto_Status *message)"
.br
.ti -1c
.RI "void \fBKineticProto_key_value__init\fP (KineticProto_KeyValue *message)"
.br
.ti -1c
.RI "void \fBKineticProto_range__init\fP (KineticProto_Range *message)"
.br
.ti -1c
.RI "void \fBKineticProto_setup__init\fP (KineticProto_Setup *message)"
.br
.ti -1c
.RI "void \fBKineticProto_p2_poperation_operation__init\fP (KineticProto_P2POperation_Operation *message)"
.br
.ti -1c
.RI "void \fBKineticProto_p2_poperation_peer__init\fP (KineticProto_P2POperation_Peer *message)"
.br
.ti -1c
.RI "void \fBKineticProto_p2_poperation__init\fP (KineticProto_P2POperation *message)"
.br
.ti -1c
.RI "void \fBKineticProto_get_log_utilization__init\fP (KineticProto_GetLog_Utilization *message)"
.br
.ti -1c
.RI "void \fBKineticProto_get_log_temperature__init\fP (KineticProto_GetLog_Temperature *message)"
.br
.ti -1c
.RI "void \fBKineticProto_get_log_capacity__init\fP (KineticProto_GetLog_Capacity *message)"
.br
.ti -1c
.RI "void \fBKineticProto_get_log_configuration_interface__init\fP (KineticProto_GetLog_Configuration_Interface *message)"
.br
.ti -1c
.RI "void \fBKineticProto_get_log_configuration__init\fP (KineticProto_GetLog_Configuration *message)"
.br
.ti -1c
.RI "void \fBKineticProto_get_log_statistics__init\fP (KineticProto_GetLog_Statistics *message)"
.br
.ti -1c
.RI "void \fBKineticProto_get_log_limits__init\fP (KineticProto_GetLog_Limits *message)"
.br
.ti -1c
.RI "void \fBKineticProto_get_log_device__init\fP (KineticProto_GetLog_Device *message)"
.br
.ti -1c
.RI "void \fBKineticProto_get_log__init\fP (KineticProto_GetLog *message)"
.br
.ti -1c
.RI "void \fBKineticProto_security_acl_scope__init\fP (KineticProto_Security_ACL_Scope *message)"
.br
.ti -1c
.RI "void \fBKineticProto_security_acl__init\fP (KineticProto_Security_ACL *message)"
.br
.ti -1c
.RI "void \fBKineticProto_security__init\fP (KineticProto_Security *message)"
.br
.ti -1c
.RI "void \fBKineticProto__init\fP (\fBKineticProto\fP *message)"
.br
.ti -1c
.RI "size_t \fBKineticProto__get_packed_size\fP (const \fBKineticProto\fP *message)"
.br
.ti -1c
.RI "size_t \fBKineticProto__pack\fP (const \fBKineticProto\fP *message, uint8_t *out)"
.br
.ti -1c
.RI "size_t \fBKineticProto__pack_to_buffer\fP (const \fBKineticProto\fP *message, ProtobufCBuffer *buffer)"
.br
.ti -1c
.RI "\fBKineticProto\fP * \fBKineticProto__unpack\fP (ProtobufCAllocator *allocator, size_t len, const uint8_t *data)"
.br
.ti -1c
.RI "void \fBKineticProto__free_unpacked\fP (\fBKineticProto\fP *message, ProtobufCAllocator *allocator)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const ProtobufCMessageDescriptor \fBKineticProto__descriptor\fP"
.br
.ti -1c
.RI "const ProtobufCMessageDescriptor \fBKineticProto_command__descriptor\fP"
.br
.ti -1c
.RI "const ProtobufCMessageDescriptor \fBKineticProto_header__descriptor\fP"
.br
.ti -1c
.RI "const ProtobufCMessageDescriptor \fBKineticProto_body__descriptor\fP"
.br
.ti -1c
.RI "const ProtobufCMessageDescriptor \fBKineticProto_status__descriptor\fP"
.br
.ti -1c
.RI "const ProtobufCEnumDescriptor \fBKineticProto_status_status_code__descriptor\fP"
.br
.ti -1c
.RI "const ProtobufCMessageDescriptor \fBKineticProto_key_value__descriptor\fP"
.br
.ti -1c
.RI "const ProtobufCMessageDescriptor \fBKineticProto_range__descriptor\fP"
.br
.ti -1c
.RI "const ProtobufCMessageDescriptor \fBKineticProto_setup__descriptor\fP"
.br
.ti -1c
.RI "const ProtobufCMessageDescriptor \fBKineticProto_p2_poperation__descriptor\fP"
.br
.ti -1c
.RI "const ProtobufCMessageDescriptor \fBKineticProto_p2_poperation_operation__descriptor\fP"
.br
.ti -1c
.RI "const ProtobufCMessageDescriptor \fBKineticProto_p2_poperation_peer__descriptor\fP"
.br
.ti -1c
.RI "const ProtobufCMessageDescriptor \fBKineticProto_get_log__descriptor\fP"
.br
.ti -1c
.RI "const ProtobufCMessageDescriptor \fBKineticProto_get_log_utilization__descriptor\fP"
.br
.ti -1c
.RI "const ProtobufCMessageDescriptor \fBKineticProto_get_log_temperature__descriptor\fP"
.br
.ti -1c
.RI "const ProtobufCMessageDescriptor \fBKineticProto_get_log_capacity__descriptor\fP"
.br
.ti -1c
.RI "const ProtobufCMessageDescriptor \fBKineticProto_get_log_configuration__descriptor\fP"
.br
.ti -1c
.RI "const ProtobufCMessageDescriptor \fBKineticProto_get_log_configuration_interface__descriptor\fP"
.br
.ti -1c
.RI "const ProtobufCMessageDescriptor \fBKineticProto_get_log_statistics__descriptor\fP"
.br
.ti -1c
.RI "const ProtobufCMessageDescriptor \fBKineticProto_get_log_limits__descriptor\fP"
.br
.ti -1c
.RI "const ProtobufCMessageDescriptor \fBKineticProto_get_log_device__descriptor\fP"
.br
.ti -1c
.RI "const ProtobufCEnumDescriptor \fBKineticProto_get_log_type__descriptor\fP"
.br
.ti -1c
.RI "const ProtobufCMessageDescriptor \fBKineticProto_security__descriptor\fP"
.br
.ti -1c
.RI "const ProtobufCMessageDescriptor \fBKineticProto_security_acl__descriptor\fP"
.br
.ti -1c
.RI "const ProtobufCMessageDescriptor \fBKineticProto_security_acl_scope__descriptor\fP"
.br
.ti -1c
.RI "const ProtobufCEnumDescriptor \fBKineticProto_security_acl_hmacalgorithm__descriptor\fP"
.br
.ti -1c
.RI "const ProtobufCEnumDescriptor \fBKineticProto_security_acl_permission__descriptor\fP"
.br
.ti -1c
.RI "const ProtobufCEnumDescriptor \fBKineticProto_synchronization__descriptor\fP"
.br
.ti -1c
.RI "const ProtobufCEnumDescriptor \fBKineticProto_algorithm__descriptor\fP"
.br
.ti -1c
.RI "const ProtobufCEnumDescriptor \fBKineticProto_message_type__descriptor\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define KINETIC_PROTO_COMMAND__INIT"
\fBValue:\fP
.PP
.nf
{ PROTOBUF_C_MESSAGE_INIT (&KineticProto_command__descriptor) \
    , NULL, NULL, NULL }
.fi
.PP
Definition at line 172 of file kinetic_proto\&.h\&.
.SS "#define KINETIC_PROTO_HEADER__INIT"
\fBValue:\fP
.PP
.nf
{ PROTOBUF_C_MESSAGE_INIT (&KineticProto_header__descriptor) \
    , 0,0, 0,0, 0,0, 0,0, 0,0, 0,0, 0,0, 0,0, 0,0 }
.fi
.PP
Definition at line 199 of file kinetic_proto\&.h\&.
.SS "#define KINETIC_PROTO_BODY__INIT"
\fBValue:\fP
.PP
.nf
{ PROTOBUF_C_MESSAGE_INIT (&KineticProto_body__descriptor) \
    , NULL, NULL, NULL, NULL, NULL, NULL }
.fi
.PP
Definition at line 214 of file kinetic_proto\&.h\&.
.SS "#define KINETIC_PROTO_STATUS__INIT"
\fBValue:\fP
.PP
.nf
{ PROTOBUF_C_MESSAGE_INIT (&KineticProto_status__descriptor) \
    , 0,0, NULL, 0,{0,NULL} }
.fi
.PP
Definition at line 228 of file kinetic_proto\&.h\&.
.SS "#define KINETIC_PROTO_KEY_VALUE__INIT"
\fBValue:\fP
.PP
.nf
{ PROTOBUF_C_MESSAGE_INIT (&KineticProto_key_value__descriptor) \
    , 0,{0,NULL}, 0,0, 0,{0,NULL}, 0,{0,NULL}, 0,{0,NULL}, 0,0, 0,0, 0,0 }
.fi
.PP
Definition at line 253 of file kinetic_proto\&.h\&.
.SS "#define KINETIC_PROTO_RANGE__INIT"
\fBValue:\fP
.PP
.nf
{ PROTOBUF_C_MESSAGE_INIT (&KineticProto_range__descriptor) \
    , 0,{0,NULL}, 0,{0,NULL}, 0,0, 0,0, 0,0, 0,0, 0,NULL }
.fi
.PP
Definition at line 276 of file kinetic_proto\&.h\&.
.SS "#define KINETIC_PROTO_SETUP__INIT"
\fBValue:\fP
.PP
.nf
{ PROTOBUF_C_MESSAGE_INIT (&KineticProto_setup__descriptor) \
    , 0,0, 0,0, 0,{0,NULL}, 0,{0,NULL}, 0,0 }
.fi
.PP
Definition at line 295 of file kinetic_proto\&.h\&.
.SS "#define KINETIC_PROTO_P2_POPERATION_OPERATION__INIT"
\fBValue:\fP
.PP
.nf
{ PROTOBUF_C_MESSAGE_INIT (&KineticProto_p2_poperation_operation__descriptor) \
    , 0,{0,NULL}, 0,{0,NULL}, 0,{0,NULL}, 0,0, NULL, NULL }
.fi
.PP
Definition at line 314 of file kinetic_proto\&.h\&.
.SS "#define KINETIC_PROTO_P2_POPERATION_PEER__INIT"
\fBValue:\fP
.PP
.nf
{ PROTOBUF_C_MESSAGE_INIT (&KineticProto_p2_poperation_peer__descriptor) \
    , NULL, 0,0, 0,0 }
.fi
.PP
Definition at line 328 of file kinetic_proto\&.h\&.
.SS "#define KINETIC_PROTO_P2_POPERATION__INIT"
\fBValue:\fP
.PP
.nf
{ PROTOBUF_C_MESSAGE_INIT (&KineticProto_p2_poperation__descriptor) \
    , NULL, 0,NULL, 0,0 }
.fi
.PP
Definition at line 342 of file kinetic_proto\&.h\&.
.SS "#define KINETIC_PROTO_GET_LOG_UTILIZATION__INIT"
\fBValue:\fP
.PP
.nf
{ PROTOBUF_C_MESSAGE_INIT (&KineticProto_get_log_utilization__descriptor) \
    , NULL, 0,0 }
.fi
.PP
Definition at line 354 of file kinetic_proto\&.h\&.
.SS "#define KINETIC_PROTO_GET_LOG_TEMPERATURE__INIT"
\fBValue:\fP
.PP
.nf
{ PROTOBUF_C_MESSAGE_INIT (&KineticProto_get_log_temperature__descriptor) \
    , NULL, 0,0, 0,0, 0,0, 0,0 }
.fi
.PP
Definition at line 372 of file kinetic_proto\&.h\&.
.SS "#define KINETIC_PROTO_GET_LOG_CAPACITY__INIT"
\fBValue:\fP
.PP
.nf
{ PROTOBUF_C_MESSAGE_INIT (&KineticProto_get_log_capacity__descriptor) \
    , 0,0, 0,0 }
.fi
.PP
Definition at line 385 of file kinetic_proto\&.h\&.
.SS "#define KINETIC_PROTO_GET_LOG_CONFIGURATION_INTERFACE__INIT"
\fBValue:\fP
.PP
.nf
{ PROTOBUF_C_MESSAGE_INIT (&KineticProto_get_log_configuration_interface__descriptor) \
    , NULL, 0,{0,NULL}, 0,{0,NULL}, 0,{0,NULL} }
.fi
.PP
Definition at line 401 of file kinetic_proto\&.h\&.
.SS "#define KINETIC_PROTO_GET_LOG_CONFIGURATION__INIT"
\fBValue:\fP
.PP
.nf
{ PROTOBUF_C_MESSAGE_INIT (&KineticProto_get_log_configuration__descriptor) \
    , NULL, NULL, 0,{0,NULL}, 0,{0,NULL}, NULL, NULL, NULL, NULL, NULL, NULL, 0,NULL, 0,0, 0,0 }
.fi
.PP
Definition at line 428 of file kinetic_proto\&.h\&.
.SS "#define KINETIC_PROTO_GET_LOG_STATISTICS__INIT"
\fBValue:\fP
.PP
.nf
{ PROTOBUF_C_MESSAGE_INIT (&KineticProto_get_log_statistics__descriptor) \
    , 0,0, 0,0, 0,0 }
.fi
.PP
Definition at line 443 of file kinetic_proto\&.h\&.
.SS "#define KINETIC_PROTO_GET_LOG_LIMITS__INIT"
\fBValue:\fP
.PP
.nf
{ PROTOBUF_C_MESSAGE_INIT (&KineticProto_get_log_limits__descriptor) \
    , 0,0, 0,0, 0,0, 0,0, 0,0, 0,0, 0,0, 0,0, 0,0, 0,0 }
.fi
.PP
Definition at line 472 of file kinetic_proto\&.h\&.
.SS "#define KINETIC_PROTO_GET_LOG_DEVICE__INIT"
\fBValue:\fP
.PP
.nf
{ PROTOBUF_C_MESSAGE_INIT (&KineticProto_get_log_device__descriptor) \
    , 0,{0,NULL} }
.fi
.PP
Definition at line 483 of file kinetic_proto\&.h\&.
.SS "#define KINETIC_PROTO_GET_LOG__INIT"
\fBValue:\fP
.PP
.nf
{ PROTOBUF_C_MESSAGE_INIT (&KineticProto_get_log__descriptor) \
    , 0,NULL, 0,NULL, 0,NULL, NULL, NULL, 0,NULL, 0,{0,NULL}, NULL, NULL }
.fi
.PP
Definition at line 506 of file kinetic_proto\&.h\&.
.SS "#define KINETIC_PROTO_SECURITY_ACL_SCOPE__INIT"
\fBValue:\fP
.PP
.nf
{ PROTOBUF_C_MESSAGE_INIT (&KineticProto_security_acl_scope__descriptor) \
    , 0,0, 0,{0,NULL}, 0,NULL, 0,0 }
.fi
.PP
Definition at line 523 of file kinetic_proto\&.h\&.
.SS "#define KINETIC_PROTO_SECURITY_ACL__INIT"
\fBValue:\fP
.PP
.nf
{ PROTOBUF_C_MESSAGE_INIT (&KineticProto_security_acl__descriptor) \
    , 0,0, 0,{0,NULL}, 0,0, 0,NULL }
.fi
.PP
Definition at line 540 of file kinetic_proto\&.h\&.
.SS "#define KINETIC_PROTO_SECURITY__INIT"
\fBValue:\fP
.PP
.nf
{ PROTOBUF_C_MESSAGE_INIT (&KineticProto_security__descriptor) \
    , 0,NULL }
.fi
.PP
Definition at line 551 of file kinetic_proto\&.h\&.
.SS "#define KINETIC_PROTO__INIT"
\fBValue:\fP
.PP
.nf
{ PROTOBUF_C_MESSAGE_INIT (&KineticProto__descriptor) \
    , NULL, 0,{0,NULL} }
.fi
.PP
Definition at line 563 of file kinetic_proto\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef typedefPROTOBUF_C__BEGIN_DECLS struct \fB_KineticProto\fP \fBKineticProto\fP"

.PP
Definition at line 38 of file kinetic_proto\&.h\&.
.SS "typedef void(* KineticProto_Command_Closure)(const KineticProto_Command *message, void *closure_data)"

.PP
Definition at line 654 of file kinetic_proto\&.h\&.
.SS "typedef void(* KineticProto_Header_Closure)(const KineticProto_Header *message, void *closure_data)"

.PP
Definition at line 657 of file kinetic_proto\&.h\&.
.SS "typedef void(* KineticProto_Body_Closure)(const KineticProto_Body *message, void *closure_data)"

.PP
Definition at line 660 of file kinetic_proto\&.h\&.
.SS "typedef void(* KineticProto_Status_Closure)(const KineticProto_Status *message, void *closure_data)"

.PP
Definition at line 663 of file kinetic_proto\&.h\&.
.SS "typedef void(* KineticProto_KeyValue_Closure)(const KineticProto_KeyValue *message, void *closure_data)"

.PP
Definition at line 666 of file kinetic_proto\&.h\&.
.SS "typedef void(* KineticProto_Range_Closure)(const KineticProto_Range *message, void *closure_data)"

.PP
Definition at line 669 of file kinetic_proto\&.h\&.
.SS "typedef void(* KineticProto_Setup_Closure)(const KineticProto_Setup *message, void *closure_data)"

.PP
Definition at line 672 of file kinetic_proto\&.h\&.
.SS "typedef void(* KineticProto_P2POperation_Operation_Closure)(const KineticProto_P2POperation_Operation *message, void *closure_data)"

.PP
Definition at line 675 of file kinetic_proto\&.h\&.
.SS "typedef void(* KineticProto_P2POperation_Peer_Closure)(const KineticProto_P2POperation_Peer *message, void *closure_data)"

.PP
Definition at line 678 of file kinetic_proto\&.h\&.
.SS "typedef void(* KineticProto_P2POperation_Closure)(const KineticProto_P2POperation *message, void *closure_data)"

.PP
Definition at line 681 of file kinetic_proto\&.h\&.
.SS "typedef void(* KineticProto_GetLog_Utilization_Closure)(const KineticProto_GetLog_Utilization *message, void *closure_data)"

.PP
Definition at line 684 of file kinetic_proto\&.h\&.
.SS "typedef void(* KineticProto_GetLog_Temperature_Closure)(const KineticProto_GetLog_Temperature *message, void *closure_data)"

.PP
Definition at line 687 of file kinetic_proto\&.h\&.
.SS "typedef void(* KineticProto_GetLog_Capacity_Closure)(const KineticProto_GetLog_Capacity *message, void *closure_data)"

.PP
Definition at line 690 of file kinetic_proto\&.h\&.
.SS "typedef void(* KineticProto_GetLog_Configuration_Interface_Closure)(const KineticProto_GetLog_Configuration_Interface *message, void *closure_data)"

.PP
Definition at line 693 of file kinetic_proto\&.h\&.
.SS "typedef void(* KineticProto_GetLog_Configuration_Closure)(const KineticProto_GetLog_Configuration *message, void *closure_data)"

.PP
Definition at line 696 of file kinetic_proto\&.h\&.
.SS "typedef void(* KineticProto_GetLog_Statistics_Closure)(const KineticProto_GetLog_Statistics *message, void *closure_data)"

.PP
Definition at line 699 of file kinetic_proto\&.h\&.
.SS "typedef void(* KineticProto_GetLog_Limits_Closure)(const KineticProto_GetLog_Limits *message, void *closure_data)"

.PP
Definition at line 702 of file kinetic_proto\&.h\&.
.SS "typedef void(* KineticProto_GetLog_Device_Closure)(const KineticProto_GetLog_Device *message, void *closure_data)"

.PP
Definition at line 705 of file kinetic_proto\&.h\&.
.SS "typedef void(* KineticProto_GetLog_Closure)(const KineticProto_GetLog *message, void *closure_data)"

.PP
Definition at line 708 of file kinetic_proto\&.h\&.
.SS "typedef void(* KineticProto_Security_ACL_Scope_Closure)(const KineticProto_Security_ACL_Scope *message, void *closure_data)"

.PP
Definition at line 711 of file kinetic_proto\&.h\&.
.SS "typedef void(* KineticProto_Security_ACL_Closure)(const KineticProto_Security_ACL *message, void *closure_data)"

.PP
Definition at line 714 of file kinetic_proto\&.h\&.
.SS "typedef void(* KineticProto_Security_Closure)(const KineticProto_Security *message, void *closure_data)"

.PP
Definition at line 717 of file kinetic_proto\&.h\&.
.SS "typedef void(* KineticProto_Closure)(const \fBKineticProto\fP *message, void *closure_data)"

.PP
Definition at line 720 of file kinetic_proto\&.h\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBKineticProto_Status_StatusCode\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIKINETIC_PROTO_STATUS_STATUS_CODE_INVALID_STATUS_CODE \fP\fP
.TP
\fB\fIKINETIC_PROTO_STATUS_STATUS_CODE_NOT_ATTEMPTED \fP\fP
.TP
\fB\fIKINETIC_PROTO_STATUS_STATUS_CODE_SUCCESS \fP\fP
.TP
\fB\fIKINETIC_PROTO_STATUS_STATUS_CODE_HMAC_FAILURE \fP\fP
.TP
\fB\fIKINETIC_PROTO_STATUS_STATUS_CODE_NOT_AUTHORIZED \fP\fP
.TP
\fB\fIKINETIC_PROTO_STATUS_STATUS_CODE_VERSION_FAILURE \fP\fP
.TP
\fB\fIKINETIC_PROTO_STATUS_STATUS_CODE_INTERNAL_ERROR \fP\fP
.TP
\fB\fIKINETIC_PROTO_STATUS_STATUS_CODE_HEADER_REQUIRED \fP\fP
.TP
\fB\fIKINETIC_PROTO_STATUS_STATUS_CODE_NOT_FOUND \fP\fP
.TP
\fB\fIKINETIC_PROTO_STATUS_STATUS_CODE_VERSION_MISMATCH \fP\fP
.TP
\fB\fIKINETIC_PROTO_STATUS_STATUS_CODE_SERVICE_BUSY \fP\fP
.TP
\fB\fIKINETIC_PROTO_STATUS_STATUS_CODE_EXPIRED \fP\fP
.TP
\fB\fIKINETIC_PROTO_STATUS_STATUS_CODE_DATA_ERROR \fP\fP
.TP
\fB\fIKINETIC_PROTO_STATUS_STATUS_CODE_PERM_DATA_ERROR \fP\fP
.TP
\fB\fIKINETIC_PROTO_STATUS_STATUS_CODE_REMOTE_CONNECTION_ERROR \fP\fP
.TP
\fB\fIKINETIC_PROTO_STATUS_STATUS_CODE_NO_SPACE \fP\fP
.TP
\fB\fIKINETIC_PROTO_STATUS_STATUS_CODE_NO_SUCH_HMAC_ALGORITHM \fP\fP
.TP
\fB\fIKINETIC_PROTO_STATUS_STATUS_CODE_INVALID_REQUEST \fP\fP
.TP
\fB\fIKINETIC_PROTO_STATUS_STATUS_CODE_NESTED_OPERATION_ERRORS \fP\fP
.PP
Definition at line 65 of file kinetic_proto\&.h\&.
.SS "enum \fBKineticProto_GetLog_Type\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIKINETIC_PROTO_GET_LOG_TYPE_INVALID_TYPE \fP\fP
.TP
\fB\fIKINETIC_PROTO_GET_LOG_TYPE_UTILIZATIONS \fP\fP
.TP
\fB\fIKINETIC_PROTO_GET_LOG_TYPE_TEMPERATURES \fP\fP
.TP
\fB\fIKINETIC_PROTO_GET_LOG_TYPE_CAPACITIES \fP\fP
.TP
\fB\fIKINETIC_PROTO_GET_LOG_TYPE_CONFIGURATION \fP\fP
.TP
\fB\fIKINETIC_PROTO_GET_LOG_TYPE_STATISTICS \fP\fP
.TP
\fB\fIKINETIC_PROTO_GET_LOG_TYPE_MESSAGES \fP\fP
.TP
\fB\fIKINETIC_PROTO_GET_LOG_TYPE_LIMITS \fP\fP
.TP
\fB\fIKINETIC_PROTO_GET_LOG_TYPE_DEVICE \fP\fP
.PP
Definition at line 87 of file kinetic_proto\&.h\&.
.SS "enum \fBKineticProto_Security_ACL_HMACAlgorithm\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIKINETIC_PROTO_SECURITY_ACL_HMACALGORITHM_INVALID_HMAC_ALGORITHM \fP\fP
.TP
\fB\fIKINETIC_PROTO_SECURITY_ACL_HMACALGORITHM_HmacSHA1 \fP\fP
.PP
Definition at line 99 of file kinetic_proto\&.h\&.
.SS "enum \fBKineticProto_Security_ACL_Permission\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIKINETIC_PROTO_SECURITY_ACL_PERMISSION_INVALID_PERMISSION \fP\fP
.TP
\fB\fIKINETIC_PROTO_SECURITY_ACL_PERMISSION_READ \fP\fP
.TP
\fB\fIKINETIC_PROTO_SECURITY_ACL_PERMISSION_WRITE \fP\fP
.TP
\fB\fIKINETIC_PROTO_SECURITY_ACL_PERMISSION_DELETE \fP\fP
.TP
\fB\fIKINETIC_PROTO_SECURITY_ACL_PERMISSION_RANGE \fP\fP
.TP
\fB\fIKINETIC_PROTO_SECURITY_ACL_PERMISSION_SETUP \fP\fP
.TP
\fB\fIKINETIC_PROTO_SECURITY_ACL_PERMISSION_P2POP \fP\fP
.TP
\fB\fIKINETIC_PROTO_SECURITY_ACL_PERMISSION_GETLOG \fP\fP
.TP
\fB\fIKINETIC_PROTO_SECURITY_ACL_PERMISSION_SECURITY \fP\fP
.PP
Definition at line 104 of file kinetic_proto\&.h\&.
.SS "enum \fBKineticProto_Synchronization\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIKINETIC_PROTO_SYNCHRONIZATION_INVALID_SYNCHRONIZATION \fP\fP
.TP
\fB\fIKINETIC_PROTO_SYNCHRONIZATION_WRITETHROUGH \fP\fP
.TP
\fB\fIKINETIC_PROTO_SYNCHRONIZATION_WRITEBACK \fP\fP
.TP
\fB\fIKINETIC_PROTO_SYNCHRONIZATION_FLUSH \fP\fP
.PP
Definition at line 116 of file kinetic_proto\&.h\&.
.SS "enum \fBKineticProto_Algorithm\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIKINETIC_PROTO_ALGORITHM_INVALID_ALGORITHM \fP\fP
.TP
\fB\fIKINETIC_PROTO_ALGORITHM_SHA1 \fP\fP
.TP
\fB\fIKINETIC_PROTO_ALGORITHM_SHA2 \fP\fP
.TP
\fB\fIKINETIC_PROTO_ALGORITHM_SHA3 \fP\fP
.TP
\fB\fIKINETIC_PROTO_ALGORITHM_CRC32 \fP\fP
.TP
\fB\fIKINETIC_PROTO_ALGORITHM_CRC64 \fP\fP
.PP
Definition at line 123 of file kinetic_proto\&.h\&.
.SS "enum \fBKineticProto_MessageType\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIKINETIC_PROTO_MESSAGE_TYPE_INVALID_MESSAGE_TYPE \fP\fP
.TP
\fB\fIKINETIC_PROTO_MESSAGE_TYPE_GET \fP\fP
.TP
\fB\fIKINETIC_PROTO_MESSAGE_TYPE_GET_RESPONSE \fP\fP
.TP
\fB\fIKINETIC_PROTO_MESSAGE_TYPE_PUT \fP\fP
.TP
\fB\fIKINETIC_PROTO_MESSAGE_TYPE_PUT_RESPONSE \fP\fP
.TP
\fB\fIKINETIC_PROTO_MESSAGE_TYPE_DELETE \fP\fP
.TP
\fB\fIKINETIC_PROTO_MESSAGE_TYPE_DELETE_RESPONSE \fP\fP
.TP
\fB\fIKINETIC_PROTO_MESSAGE_TYPE_GETNEXT \fP\fP
.TP
\fB\fIKINETIC_PROTO_MESSAGE_TYPE_GETNEXT_RESPONSE \fP\fP
.TP
\fB\fIKINETIC_PROTO_MESSAGE_TYPE_GETPREVIOUS \fP\fP
.TP
\fB\fIKINETIC_PROTO_MESSAGE_TYPE_GETPREVIOUS_RESPONSE \fP\fP
.TP
\fB\fIKINETIC_PROTO_MESSAGE_TYPE_GETKEYRANGE \fP\fP
.TP
\fB\fIKINETIC_PROTO_MESSAGE_TYPE_GETKEYRANGE_RESPONSE \fP\fP
.TP
\fB\fIKINETIC_PROTO_MESSAGE_TYPE_GETVERSION \fP\fP
.TP
\fB\fIKINETIC_PROTO_MESSAGE_TYPE_GETVERSION_RESPONSE \fP\fP
.TP
\fB\fIKINETIC_PROTO_MESSAGE_TYPE_SETUP \fP\fP
.TP
\fB\fIKINETIC_PROTO_MESSAGE_TYPE_SETUP_RESPONSE \fP\fP
.TP
\fB\fIKINETIC_PROTO_MESSAGE_TYPE_GETLOG \fP\fP
.TP
\fB\fIKINETIC_PROTO_MESSAGE_TYPE_GETLOG_RESPONSE \fP\fP
.TP
\fB\fIKINETIC_PROTO_MESSAGE_TYPE_SECURITY \fP\fP
.TP
\fB\fIKINETIC_PROTO_MESSAGE_TYPE_SECURITY_RESPONSE \fP\fP
.TP
\fB\fIKINETIC_PROTO_MESSAGE_TYPE_PEER2PEERPUSH \fP\fP
.TP
\fB\fIKINETIC_PROTO_MESSAGE_TYPE_PEER2PEERPUSH_RESPONSE \fP\fP
.TP
\fB\fIKINETIC_PROTO_MESSAGE_TYPE_NOOP \fP\fP
.TP
\fB\fIKINETIC_PROTO_MESSAGE_TYPE_NOOP_RESPONSE \fP\fP
.TP
\fB\fIKINETIC_PROTO_MESSAGE_TYPE_FLUSHALLDATA \fP\fP
.TP
\fB\fIKINETIC_PROTO_MESSAGE_TYPE_FLUSHALLDATA_RESPONSE \fP\fP
.PP
Definition at line 132 of file kinetic_proto\&.h\&.
.SH "Function Documentation"
.PP 
.SS "void KineticProto_command__init (KineticProto_Command *message)"

.PP
Definition at line 32 of file kinetic_proto\&.c\&.
.PP
References KINETIC_PROTO_COMMAND__INIT\&.
.SS "void KineticProto_header__init (KineticProto_Header *message)"

.PP
Definition at line 37 of file kinetic_proto\&.c\&.
.PP
References KINETIC_PROTO_HEADER__INIT\&.
.SS "void KineticProto_body__init (KineticProto_Body *message)"

.PP
Definition at line 42 of file kinetic_proto\&.c\&.
.PP
References KINETIC_PROTO_BODY__INIT\&.
.SS "void KineticProto_status__init (KineticProto_Status *message)"

.PP
Definition at line 47 of file kinetic_proto\&.c\&.
.PP
References KINETIC_PROTO_STATUS__INIT\&.
.SS "void KineticProto_key_value__init (KineticProto_KeyValue *message)"

.PP
Definition at line 52 of file kinetic_proto\&.c\&.
.PP
References KINETIC_PROTO_KEY_VALUE__INIT\&.
.SS "void KineticProto_range__init (KineticProto_Range *message)"

.PP
Definition at line 57 of file kinetic_proto\&.c\&.
.PP
References KINETIC_PROTO_RANGE__INIT\&.
.SS "void KineticProto_setup__init (KineticProto_Setup *message)"

.PP
Definition at line 62 of file kinetic_proto\&.c\&.
.PP
References KINETIC_PROTO_SETUP__INIT\&.
.SS "void KineticProto_p2_poperation_operation__init (KineticProto_P2POperation_Operation *message)"

.PP
Definition at line 67 of file kinetic_proto\&.c\&.
.PP
References KINETIC_PROTO_P2_POPERATION_OPERATION__INIT\&.
.SS "void KineticProto_p2_poperation_peer__init (KineticProto_P2POperation_Peer *message)"

.PP
Definition at line 72 of file kinetic_proto\&.c\&.
.PP
References KINETIC_PROTO_P2_POPERATION_PEER__INIT\&.
.SS "void KineticProto_p2_poperation__init (KineticProto_P2POperation *message)"

.PP
Definition at line 77 of file kinetic_proto\&.c\&.
.PP
References KINETIC_PROTO_P2_POPERATION__INIT\&.
.SS "void KineticProto_get_log_utilization__init (KineticProto_GetLog_Utilization *message)"

.PP
Definition at line 82 of file kinetic_proto\&.c\&.
.PP
References KINETIC_PROTO_GET_LOG_UTILIZATION__INIT\&.
.SS "void KineticProto_get_log_temperature__init (KineticProto_GetLog_Temperature *message)"

.PP
Definition at line 87 of file kinetic_proto\&.c\&.
.PP
References KINETIC_PROTO_GET_LOG_TEMPERATURE__INIT\&.
.SS "void KineticProto_get_log_capacity__init (KineticProto_GetLog_Capacity *message)"

.PP
Definition at line 92 of file kinetic_proto\&.c\&.
.PP
References KINETIC_PROTO_GET_LOG_CAPACITY__INIT\&.
.SS "void KineticProto_get_log_configuration_interface__init (KineticProto_GetLog_Configuration_Interface *message)"

.PP
Definition at line 97 of file kinetic_proto\&.c\&.
.PP
References KINETIC_PROTO_GET_LOG_CONFIGURATION_INTERFACE__INIT\&.
.SS "void KineticProto_get_log_configuration__init (KineticProto_GetLog_Configuration *message)"

.PP
Definition at line 102 of file kinetic_proto\&.c\&.
.PP
References KINETIC_PROTO_GET_LOG_CONFIGURATION__INIT\&.
.SS "void KineticProto_get_log_statistics__init (KineticProto_GetLog_Statistics *message)"

.PP
Definition at line 107 of file kinetic_proto\&.c\&.
.PP
References KINETIC_PROTO_GET_LOG_STATISTICS__INIT\&.
.SS "void KineticProto_get_log_limits__init (KineticProto_GetLog_Limits *message)"

.PP
Definition at line 112 of file kinetic_proto\&.c\&.
.PP
References KINETIC_PROTO_GET_LOG_LIMITS__INIT\&.
.SS "void KineticProto_get_log_device__init (KineticProto_GetLog_Device *message)"

.PP
Definition at line 117 of file kinetic_proto\&.c\&.
.PP
References KINETIC_PROTO_GET_LOG_DEVICE__INIT\&.
.SS "void KineticProto_get_log__init (KineticProto_GetLog *message)"

.PP
Definition at line 122 of file kinetic_proto\&.c\&.
.PP
References KINETIC_PROTO_GET_LOG__INIT\&.
.SS "void KineticProto_security_acl_scope__init (KineticProto_Security_ACL_Scope *message)"

.PP
Definition at line 127 of file kinetic_proto\&.c\&.
.PP
References KINETIC_PROTO_SECURITY_ACL_SCOPE__INIT\&.
.SS "void KineticProto_security_acl__init (KineticProto_Security_ACL *message)"

.PP
Definition at line 132 of file kinetic_proto\&.c\&.
.PP
References KINETIC_PROTO_SECURITY_ACL__INIT\&.
.SS "void KineticProto_security__init (KineticProto_Security *message)"

.PP
Definition at line 137 of file kinetic_proto\&.c\&.
.PP
References KINETIC_PROTO_SECURITY__INIT\&.
.SS "void KineticProto__init (\fBKineticProto\fP *message)"

.PP
Definition at line 142 of file kinetic_proto\&.c\&.
.PP
References KINETIC_PROTO__INIT\&.
.SS "size_t KineticProto__get_packed_size (const \fBKineticProto\fP *message)"

.PP
Definition at line 147 of file kinetic_proto\&.c\&.
.PP
References KineticProto__descriptor\&.
.SS "size_t KineticProto__pack (const \fBKineticProto\fP *message, uint8_t *out)"

.PP
Definition at line 152 of file kinetic_proto\&.c\&.
.PP
References KineticProto__descriptor\&.
.SS "size_t KineticProto__pack_to_buffer (const \fBKineticProto\fP *message, ProtobufCBuffer *buffer)"

.PP
Definition at line 158 of file kinetic_proto\&.c\&.
.PP
References KineticProto__descriptor\&.
.SS "\fBKineticProto\fP* KineticProto__unpack (ProtobufCAllocator *allocator, size_tlen, const uint8_t *data)"

.PP
Definition at line 164 of file kinetic_proto\&.c\&.
.PP
References KineticProto__descriptor\&.
.SS "void KineticProto__free_unpacked (\fBKineticProto\fP *message, ProtobufCAllocator *allocator)"

.PP
Definition at line 171 of file kinetic_proto\&.c\&.
.PP
References KineticProto__descriptor\&.
.SH "Variable Documentation"
.PP 
.SS "const ProtobufCMessageDescriptor KineticProto__descriptor"

.PP
Definition at line 2532 of file kinetic_proto\&.c\&.
.SS "const ProtobufCMessageDescriptor KineticProto_command__descriptor"

.PP
Definition at line 226 of file kinetic_proto\&.c\&.
.SS "const ProtobufCMessageDescriptor KineticProto_header__descriptor"

.PP
Definition at line 370 of file kinetic_proto\&.c\&.
.SS "const ProtobufCMessageDescriptor KineticProto_body__descriptor"

.PP
Definition at line 474 of file kinetic_proto\&.c\&.
.SS "const ProtobufCMessageDescriptor KineticProto_status__descriptor"

.PP
Definition at line 600 of file kinetic_proto\&.c\&.
.SS "const ProtobufCEnumDescriptor KineticProto_status_status_code__descriptor"

.PP
Definition at line 536 of file kinetic_proto\&.c\&.
.SS "const ProtobufCMessageDescriptor KineticProto_key_value__descriptor"

.PP
Definition at line 729 of file kinetic_proto\&.c\&.
.SS "const ProtobufCMessageDescriptor KineticProto_range__descriptor"

.PP
Definition at line 846 of file kinetic_proto\&.c\&.
.SS "const ProtobufCMessageDescriptor KineticProto_setup__descriptor"

.PP
Definition at line 936 of file kinetic_proto\&.c\&.
.SS "const ProtobufCMessageDescriptor KineticProto_p2_poperation__descriptor"

.PP
Definition at line 1167 of file kinetic_proto\&.c\&.
.SS "const ProtobufCMessageDescriptor KineticProto_p2_poperation_operation__descriptor"

.PP
Definition at line 1039 of file kinetic_proto\&.c\&.
.SS "const ProtobufCMessageDescriptor KineticProto_p2_poperation_peer__descriptor"

.PP
Definition at line 1103 of file kinetic_proto\&.c\&.
.SS "const ProtobufCMessageDescriptor KineticProto_get_log__descriptor"

.PP
Definition at line 2072 of file kinetic_proto\&.c\&.
.SS "const ProtobufCMessageDescriptor KineticProto_get_log_utilization__descriptor"

.PP
Definition at line 1218 of file kinetic_proto\&.c\&.
.SS "const ProtobufCMessageDescriptor KineticProto_get_log_temperature__descriptor"

.PP
Definition at line 1308 of file kinetic_proto\&.c\&.
.SS "const ProtobufCMessageDescriptor KineticProto_get_log_capacity__descriptor"

.PP
Definition at line 1359 of file kinetic_proto\&.c\&.
.SS "const ProtobufCMessageDescriptor KineticProto_get_log_configuration__descriptor"

.PP
Definition at line 1630 of file kinetic_proto\&.c\&.
.SS "const ProtobufCMessageDescriptor KineticProto_get_log_configuration_interface__descriptor"

.PP
Definition at line 1436 of file kinetic_proto\&.c\&.
.SS "const ProtobufCMessageDescriptor KineticProto_get_log_statistics__descriptor"

.PP
Definition at line 1695 of file kinetic_proto\&.c\&.
.SS "const ProtobufCMessageDescriptor KineticProto_get_log_limits__descriptor"

.PP
Definition at line 1850 of file kinetic_proto\&.c\&.
.SS "const ProtobufCMessageDescriptor KineticProto_get_log_device__descriptor"

.PP
Definition at line 1888 of file kinetic_proto\&.c\&.
.SS "const ProtobufCEnumDescriptor KineticProto_get_log_type__descriptor"

.PP
Definition at line 1930 of file kinetic_proto\&.c\&.
.SS "const ProtobufCMessageDescriptor KineticProto_security__descriptor"

.PP
Definition at line 2334 of file kinetic_proto\&.c\&.
.SS "const ProtobufCMessageDescriptor KineticProto_security_acl__descriptor"

.PP
Definition at line 2296 of file kinetic_proto\&.c\&.
.SS "const ProtobufCMessageDescriptor KineticProto_security_acl_scope__descriptor"

.PP
Definition at line 2149 of file kinetic_proto\&.c\&.
.SS "const ProtobufCEnumDescriptor KineticProto_security_acl_hmacalgorithm__descriptor"

.PP
Definition at line 2177 of file kinetic_proto\&.c\&.
.SS "const ProtobufCEnumDescriptor KineticProto_security_acl_permission__descriptor"

.PP
Definition at line 2219 of file kinetic_proto\&.c\&.
.SS "const ProtobufCEnumDescriptor KineticProto_synchronization__descriptor"

.PP
Definition at line 2366 of file kinetic_proto\&.c\&.
.SS "const ProtobufCEnumDescriptor KineticProto_algorithm__descriptor"

.PP
Definition at line 2402 of file kinetic_proto\&.c\&.
.SS "const ProtobufCEnumDescriptor KineticProto_message_type__descriptor"

.PP
Definition at line 2480 of file kinetic_proto\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for protobuf-c from the source code\&.
