.TH "KineticLogInfo_Configuration" 3 "Fri Mar 13 2015" "Version v0.12.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticLogInfo_Configuration \- 
.PP
Log info device configuration\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBvendor\fP"
.br
.ti -1c
.RI "char * \fBmodel\fP"
.br
.ti -1c
.RI "\fBByteArray\fP \fBserialNumber\fP"
.br
.ti -1c
.RI "\fBByteArray\fP \fBworldWideName\fP"
.br
.ti -1c
.RI "char * \fBversion\fP"
.br
.ti -1c
.RI "char * \fBcompilationDate\fP"
.br
.ti -1c
.RI "char * \fBsourceHash\fP"
.br
.ti -1c
.RI "char * \fBprotocolVersion\fP"
.br
.ti -1c
.RI "char * \fBprotocolCompilationDate\fP"
.br
.ti -1c
.RI "char * \fBprotocolSourceHash\fP"
.br
.ti -1c
.RI "\fBKineticLogInfo_Interface\fP * \fBinterfaces\fP"
.br
.ti -1c
.RI "size_t \fBnumInterfaces\fP"
.br
.ti -1c
.RI "int32_t \fBport\fP"
.br
.ti -1c
.RI "int32_t \fBtlsPort\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Log info device configuration\&. 
.PP
Definition at line 339 of file kinetic_types\&.h\&.
.SH "Field Documentation"
.PP 
.SS "char* KineticLogInfo_Configuration::vendor"

.PP
Definition at line 340 of file kinetic_types\&.h\&.
.SS "char* KineticLogInfo_Configuration::model"

.PP
Definition at line 341 of file kinetic_types\&.h\&.
.SS "\fBByteArray\fP KineticLogInfo_Configuration::serialNumber"

.PP
Definition at line 342 of file kinetic_types\&.h\&.
.SS "\fBByteArray\fP KineticLogInfo_Configuration::worldWideName"

.PP
Definition at line 343 of file kinetic_types\&.h\&.
.SS "char* KineticLogInfo_Configuration::version"

.PP
Definition at line 344 of file kinetic_types\&.h\&.
.SS "char* KineticLogInfo_Configuration::compilationDate"

.PP
Definition at line 345 of file kinetic_types\&.h\&.
.SS "char* KineticLogInfo_Configuration::sourceHash"

.PP
Definition at line 346 of file kinetic_types\&.h\&.
.SS "char* KineticLogInfo_Configuration::protocolVersion"

.PP
Definition at line 347 of file kinetic_types\&.h\&.
.SS "char* KineticLogInfo_Configuration::protocolCompilationDate"

.PP
Definition at line 348 of file kinetic_types\&.h\&.
.SS "char* KineticLogInfo_Configuration::protocolSourceHash"

.PP
Definition at line 349 of file kinetic_types\&.h\&.
.SS "\fBKineticLogInfo_Interface\fP* KineticLogInfo_Configuration::interfaces"

.PP
Definition at line 350 of file kinetic_types\&.h\&.
.SS "size_t KineticLogInfo_Configuration::numInterfaces"

.PP
Definition at line 351 of file kinetic_types\&.h\&.
.SS "int32_t KineticLogInfo_Configuration::port"

.PP
Definition at line 352 of file kinetic_types\&.h\&.
.SS "int32_t KineticLogInfo_Configuration::tlsPort"

.PP
Definition at line 353 of file kinetic_types\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
