.TH "kinetic_version_info.h" 3 "Fri Mar 13 2015" "Version v0.12.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kinetic_version_info.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBKINETIC_C_VERSION\fP   '0\&.12\&.0-beta'"
.br
.ti -1c
.RI "#define \fBKINETIC_C_PROTOCOL_VERSION\fP   '3\&.0\&.5'"
.br
.ti -1c
.RI "#define \fBKINETIC_C_REPO_HASH\fP   'de7e564866dee5cdd75ac204c84b356188bfcb56'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define KINETIC_C_VERSION   '0\&.12\&.0-beta'"

.PP
Definition at line 3 of file kinetic_version_info\&.h\&.
.SS "#define KINETIC_C_PROTOCOL_VERSION   '3\&.0\&.5'"

.PP
Definition at line 4 of file kinetic_version_info\&.h\&.
.SS "#define KINETIC_C_REPO_HASH   'de7e564866dee5cdd75ac204c84b356188bfcb56'"

.PP
Definition at line 5 of file kinetic_version_info\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
