.TH "KineticResponse" 3 "Tue Jan 27 2015" "Version v0.11.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticResponse \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_types_internal\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBKineticPDUHeader\fP \fBheader\fP"
.br
.ti -1c
.RI "KineticProto_Message * \fBproto\fP"
.br
.ti -1c
.RI "KineticProto_Command * \fBcommand\fP"
.br
.ti -1c
.RI "uint8_t \fBvalue\fP []"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 158 of file kinetic_types_internal\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBKineticPDUHeader\fP KineticResponse::header"

.PP
Definition at line 160 of file kinetic_types_internal\&.h\&.
.SS "KineticProto_Message* KineticResponse::proto"

.PP
Definition at line 161 of file kinetic_types_internal\&.h\&.
.SS "KineticProto_Command* KineticResponse::command"

.PP
Definition at line 162 of file kinetic_types_internal\&.h\&.
.SS "uint8_t KineticResponse::value[]"

.PP
Definition at line 163 of file kinetic_types_internal\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
