.TH "kinetic_logger.c" 3 "Mon Mar 2 2015" "Version v0.12.0-beta" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kinetic_logger.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'kinetic_logger\&.h'\fP
.br
\fC#include <stdarg\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <sys/time\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include <pthread\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBBUFFER_SIZE\fP   1024"
.br
.ti -1c
.RI "#define \fBBUFFER_MAX_STRLEN\fP   (\fBBUFFER_SIZE\fP-2)"
.br
.ti -1c
.RI "#define \fBLOG_INDENT\fP   '  '"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "static bool \fBis_level_enabled\fP (int log_level)"
.br
.ti -1c
.RI "static void \fBlock_buffer\fP (void)"
.br
.ti -1c
.RI "static void \fBunlock_buffer\fP (void)"
.br
.ti -1c
.RI "static void \fBflush_buffer\fP (void)"
.br
.ti -1c
.RI "static char * \fBget_buffer\fP (void)"
.br
.ti -1c
.RI "static void \fBfinish_buffer\fP (void)"
.br
.ti -1c
.RI "static void \fBlog_protobuf_message\fP (int log_level, const ProtobufCMessage *msg, char *\fBindent\fP)"
.br
.ti -1c
.RI "void \fBKineticLogger_Init\fP (const char *log_file, int log_level)"
.br
.ti -1c
.RI "void \fBKineticLogger_Close\fP (void)"
.br
.ti -1c
.RI "void \fBKineticLogger_Log\fP (int log_level, const char *message)"
.br
.ti -1c
.RI "void \fBKineticLogger_LogPrintf\fP (int log_level, const char *format,\&.\&.\&.)"
.br
.ti -1c
.RI "void \fBKineticLogger_LogLocation\fP (const char *filename, int line, const char *message)"
.br
.ti -1c
.RI "void \fBKineticLogger_LogHeader\fP (int log_level, const \fBKineticPDUHeader\fP *header)"
.br
.ti -1c
.RI "static void \fBlog_proto_level_start\fP (const char *name)"
.br
.ti -1c
.RI "static void \fBlog_proto_level_end\fP (void)"
.br
.ti -1c
.RI "static void \fBlog_proto_level_start_array\fP (const char *name, unsigned quantity)"
.br
.ti -1c
.RI "static void \fBlog_proto_level_end_array\fP (void)"
.br
.ti -1c
.RI "static int \fBbytetoa\fP (char *p_buf, uint8_t val)"
.br
.ti -1c
.RI "int \fBKineticLogger_ByteArraySliceToCString\fP (char *p_buf, const \fBByteArray\fP bytes, const int start, const int count)"
.br
.ti -1c
.RI "static void \fBLogUnboxed\fP (int log_level, void const *const fieldData, ProtobufCFieldDescriptor const *const fieldDesc, size_t const i, char *\fBindent\fP)"
.br
.ti -1c
.RI "void \fBKineticLogger_LogProtobuf\fP (int log_level, const KineticProto_Message *msg)"
.br
.ti -1c
.RI "void \fBKineticLogger_LogStatus\fP (int log_level, KineticProto_Command_Status *status)"
.br
.ti -1c
.RI "void \fBKineticLogger_LogByteArray\fP (int log_level, const char *title, \fBByteArray\fP bytes)"
.br
.ti -1c
.RI "void \fBKineticLogger_LogByteBuffer\fP (int log_level, const char *title, \fBByteBuffer\fP buffer)"
.br
.ti -1c
.RI "void \fBKineticLogger_LogTimestamp\fP (int log_level, const char *title)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static int \fBKineticLogLevel\fP = -1"
.br
.ti -1c
.RI "static FILE * \fBKineticLoggerHandle\fP = NULL"
.br
.ti -1c
.RI "static pthread_mutex_t \fBBufferMutex\fP = PTHREAD_MUTEX_INITIALIZER"
.br
.ti -1c
.RI "static char \fBBuffer\fP [1024]"
.br
.ti -1c
.RI "static char \fBindent\fP [64] = ' '"
.br
.ti -1c
.RI "static const size_t \fBmax_indent\fP = sizeof(\fBindent\fP)-3"
.br
.ti -1c
.RI "static int \fBindent_overflow\fP = 0"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BUFFER_SIZE   1024"

.PP
Definition at line 32 of file kinetic_logger\&.c\&.
.SS "#define BUFFER_MAX_STRLEN   (\fBBUFFER_SIZE\fP-2)"

.PP
Definition at line 33 of file kinetic_logger\&.c\&.
.SS "#define LOG_INDENT   '  '"

.PP
Definition at line 150 of file kinetic_logger\&.c\&.
.SH "Function Documentation"
.PP 
.SS "static bool is_level_enabled (intlog_level)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 541 of file kinetic_logger\&.c\&.
.SS "static void lock_buffer (void)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 546 of file kinetic_logger\&.c\&.
.PP
References BufferMutex\&.
.SS "static void unlock_buffer (void)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 551 of file kinetic_logger\&.c\&.
.PP
References BufferMutex\&.
.SS "static void flush_buffer (void)\fC [static]\fP"

.PP
Definition at line 556 of file kinetic_logger\&.c\&.
.PP
References Buffer, and KineticLoggerHandle\&.
.SS "static char * get_buffer (void)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 565 of file kinetic_logger\&.c\&.
.PP
References Buffer, and lock_buffer()\&.
.SS "static void finish_buffer (void)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 571 of file kinetic_logger\&.c\&.
.PP
References flush_buffer(), and unlock_buffer()\&.
.SS "static void log_protobuf_message (intlog_level, const ProtobufCMessage *msg, char *indent)\fC [static]\fP"

.PP
Definition at line 340 of file kinetic_logger\&.c\&.
.PP
References is_level_enabled(), KineticProto_command__free_unpacked(), KineticProto_command__unpack(), log_proto_level_end(), log_proto_level_end_array(), log_proto_level_start(), log_proto_level_start_array(), and LogUnboxed()\&.
.SS "void KineticLogger_Init (const char *log_file, intlog_level)"

.PP
Definition at line 55 of file kinetic_logger\&.c\&.
.PP
References BufferMutex, KINETIC_ASSERT, KineticLoggerHandle, and KineticLogLevel\&.
.SS "void KineticLogger_Close (void)"

.PP
Definition at line 84 of file kinetic_logger\&.c\&.
.PP
References KineticLoggerHandle, and KineticLogLevel\&.
.SS "void KineticLogger_Log (intlog_level, const char *message)"

.PP
Definition at line 94 of file kinetic_logger\&.c\&.
.PP
References KineticLogger_LogPrintf()\&.
.SS "void KineticLogger_LogPrintf (intlog_level, const char *format, \&.\&.\&.)"

.PP
Definition at line 99 of file kinetic_logger\&.c\&.
.PP
References Buffer, BUFFER_MAX_STRLEN, finish_buffer(), get_buffer(), and is_level_enabled()\&.
.SS "void KineticLogger_LogLocation (const char *filename, intline, const char *message)"

.PP
Definition at line 121 of file kinetic_logger\&.c\&.
.PP
References KineticLogger_LogPrintf(), and KineticLogLevel\&.
.SS "void KineticLogger_LogHeader (intlog_level, const \fBKineticPDUHeader\fP *header)"

.PP
Definition at line 136 of file kinetic_logger\&.c\&.
.PP
References is_level_enabled(), KineticLogger_Log(), and KineticLogger_LogPrintf()\&.
.SS "static void log_proto_level_start (const char *name)\fC [static]\fP"

.PP
Definition at line 156 of file kinetic_logger\&.c\&.
.PP
References indent, indent_overflow, KineticLogger_LogPrintf(), LOG_INDENT, and max_indent\&.
.SS "static void log_proto_level_end (void)\fC [static]\fP"

.PP
Definition at line 167 of file kinetic_logger\&.c\&.
.PP
References indent, indent_overflow, and KineticLogger_LogPrintf()\&.
.SS "static void log_proto_level_start_array (const char *name, unsignedquantity)\fC [static]\fP"

.PP
Definition at line 178 of file kinetic_logger\&.c\&.
.PP
References indent, indent_overflow, KineticLogger_LogPrintf(), LOG_INDENT, and max_indent\&.
.SS "static void log_proto_level_end_array (void)\fC [static]\fP"

.PP
Definition at line 190 of file kinetic_logger\&.c\&.
.PP
References indent, indent_overflow, and KineticLogger_LogPrintf()\&.
.SS "static int bytetoa (char *p_buf, uint8_tval)\fC [static]\fP"

.PP
Definition at line 201 of file kinetic_logger\&.c\&.
.SS "int KineticLogger_ByteArraySliceToCString (char *p_buf, const \fBByteArray\fPbytes, const intstart, const intcount)"

.PP
Definition at line 221 of file kinetic_logger\&.c\&.
.PP
References bytetoa(), and ByteArray::data\&.
.SS "static void LogUnboxed (intlog_level, void const *constfieldData, ProtobufCFieldDescriptor const *constfieldDesc, size_t consti, char *indent)\fC [static]\fP"

.PP
Definition at line 233 of file kinetic_logger\&.c\&.
.PP
References BOOL_TO_STRING, KINETIC_ASSERT, KineticLogger_LogByteArray(), KineticLogger_LogPrintf(), log_proto_level_end(), log_proto_level_start(), and log_protobuf_message()\&.
.SS "void KineticLogger_LogProtobuf (intlog_level, const KineticProto_Message *msg)"

.PP
Definition at line 403 of file kinetic_logger\&.c\&.
.PP
References indent, indent_overflow, is_level_enabled(), KineticLogger_Log(), and log_protobuf_message()\&.
.SS "void KineticLogger_LogStatus (intlog_level, KineticProto_Command_Status *status)"

.PP
Definition at line 415 of file kinetic_logger\&.c\&.
.PP
References is_level_enabled(), KINETIC_PROTO_COMMAND_STATUS_STATUS_CODE_INVALID_STATUS_CODE, KINETIC_PROTO_COMMAND_STATUS_STATUS_CODE_SUCCESS, and KineticLogger_LogPrintf()\&.
.SS "void KineticLogger_LogByteArray (intlog_level, const char *title, \fBByteArray\fPbytes)"

.PP
Definition at line 472 of file kinetic_logger\&.c\&.
.PP
References ByteArray::data, is_level_enabled(), KineticLogger_LogPrintf(), and ByteArray::len\&.
.SS "void KineticLogger_LogByteBuffer (intlog_level, const char *title, \fBByteBuffer\fPbuffer)"

.PP
Definition at line 516 of file kinetic_logger\&.c\&.
.PP
References ByteBuffer::array, ByteBuffer::bytesUsed, ByteArray::data, is_level_enabled(), and KineticLogger_LogByteArray()\&.
.SS "void KineticLogger_LogTimestamp (intlog_level, const char *title)"

.PP
Definition at line 525 of file kinetic_logger\&.c\&.
.PP
References KineticLogger_LogPrintf()\&.
.SH "Variable Documentation"
.PP 
.SS "int KineticLogLevel = -1\fC [static]\fP"

.PP
Definition at line 35 of file kinetic_logger\&.c\&.
.SS "FILE* KineticLoggerHandle = NULL\fC [static]\fP"

.PP
Definition at line 36 of file kinetic_logger\&.c\&.
.SS "pthread_mutex_t BufferMutex = PTHREAD_MUTEX_INITIALIZER\fC [static]\fP"

.PP
Definition at line 37 of file kinetic_logger\&.c\&.
.SS "char Buffer[1024]\fC [static]\fP"

.PP
Definition at line 38 of file kinetic_logger\&.c\&.
.SS "char indent[64] = ' '\fC [static]\fP"

.PP
Definition at line 151 of file kinetic_logger\&.c\&.
.SS "const size_t max_indent = sizeof(\fBindent\fP)-3\fC [static]\fP"

.PP
Definition at line 152 of file kinetic_logger\&.c\&.
.SS "int indent_overflow = 0\fC [static]\fP"

.PP
Definition at line 153 of file kinetic_logger\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
