kinetic_session.h
NAME
kinetic_session.h -
SYNOPSIS
#include 'kinetic_types_internal.h'
Functions
KineticStatus KineticSession_Create (KineticSession *const session, KineticClient *const client)
KineticStatus KineticSession_Destroy (KineticSession *const session)
KineticStatus KineticSession_Connect (KineticSession const *const session)
KineticStatus KineticSession_Disconnect (KineticSession const *const session)
void KineticSession_IncrementSequence (KineticSession const *const session)
Function Documentation
KineticStatus KineticSession_Create (KineticSession *constsession, KineticClient *constclient)
Definition at line 37 of file kinetic_session.c.
References KineticSession::connection, KINETIC_MAX_OUTSTANDING_OPERATIONS_PER_SESSION, KINETIC_STATUS_MEMORY_ERROR, KINETIC_STATUS_SESSION_EMPTY, KINETIC_STATUS_SUCCESS, KineticAllocator_FreeConnection(), KineticAllocator_NewConnection(), KineticCountingSemaphore_Create(), LOG0, KineticConnection::outstandingOperations, and KineticConnection::sendMutex.
KineticStatus KineticSession_Destroy (KineticSession *constsession)
Definition at line 71 of file kinetic_session.c.
References KineticSession::connection, KINETIC_STATUS_SESSION_EMPTY, KINETIC_STATUS_SESSION_INVALID, KINETIC_STATUS_SUCCESS, KineticAllocator_FreeConnection(), KineticCountingSemaphore_Destroy(), and KineticConnection::outstandingOperations.
KineticStatus KineticSession_Connect (KineticSession const *constsession)
Definition at line 85 of file kinetic_session.c.
References bus_register_socket(), BUS_SOCKET_PLAIN, KineticSession::config, KineticSession::connection, KineticSessionConfig::host, KINETIC_CONNECTION_TIMEOUT_SECS, KINETIC_SOCKET_DESCRIPTOR_INVALID, KINETIC_STATUS_CONNECTION_ERROR, KINETIC_STATUS_MEMORY_ERROR, KINETIC_STATUS_SESSION_EMPTY, KINETIC_STATUS_SUCCESS, KineticResourceWaiter_WaitTilAvailable(), KineticSocket_Close(), KineticSocket_Connect(), LOG0, LOG_LOCATION, LOGF1, PDU_PROTO_MAX_LEN, and KineticSessionConfig::port.
KineticStatus KineticSession_Disconnect (KineticSession const *constsession)
Definition at line 147 of file kinetic_session.c.
References bus_release_socket(), KineticConnection::connected, KineticSession::connection, KINETIC_HANDLE_INVALID, KINETIC_STATUS_CONNECTION_ERROR, KINETIC_STATUS_SESSION_EMPTY, and KINETIC_STATUS_SUCCESS.
void KineticSession_IncrementSequence (KineticSession const *constsession)
Author
Generated automatically by Doxygen for kinetic-c from the source code.