.TH "kinetic_resourcewaiter.h" 3 "Wed Feb 11 2015" "Version v0.11.1" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kinetic_resourcewaiter.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br
\fC#include <stdbool\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBKineticResourceWaiter_Init\fP (KineticResourceWaiter *const waiter)"
.br
.ti -1c
.RI "void \fBKineticResourceWaiter_SetAvailable\fP (KineticResourceWaiter *const waiter)"
.br
.ti -1c
.RI "bool \fBKineticResourceWaiter_WaitTilAvailable\fP (KineticResourceWaiter *const waiter, uint32_t max_wait_sec)"
.br
.ti -1c
.RI "void \fBKineticResourceWaiter_Destroy\fP (KineticResourceWaiter *const waiter)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void KineticResourceWaiter_Init (KineticResourceWaiter *constwaiter)"

.PP
Definition at line 27 of file kinetic_resourcewaiter\&.c\&.
.SS "void KineticResourceWaiter_SetAvailable (KineticResourceWaiter *constwaiter)"

.PP
Definition at line 34 of file kinetic_resourcewaiter\&.c\&.
.SS "bool KineticResourceWaiter_WaitTilAvailable (KineticResourceWaiter *constwaiter, uint32_tmax_wait_sec)"

.PP
Definition at line 47 of file kinetic_resourcewaiter\&.c\&.
.SS "void KineticResourceWaiter_Destroy (KineticResourceWaiter *constwaiter)"

.PP
Definition at line 72 of file kinetic_resourcewaiter\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
