.TH "kinetic_hmac.h" 3 "Fri Aug 8 2014" "Version v0.5.0" "protobuf-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kinetic_hmac.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'kinetic_types\&.h'\fP
.br
\fC#include 'kinetic_message\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBKineticHMAC_Init\fP (\fBKineticHMAC\fP *hmac, \fBKineticProto_Security_ACL_HMACAlgorithm\fP algorithm)"
.br
.ti -1c
.RI "void \fBKineticHMAC_Populate\fP (\fBKineticHMAC\fP *hmac, \fBKineticProto\fP *proto, const char *const key, size_t keyLen)"
.br
.ti -1c
.RI "bool \fBKineticHMAC_Validate\fP (const \fBKineticProto\fP *proto, const char *const key, size_t keyLen)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void KineticHMAC_Init (\fBKineticHMAC\fP *hmac, \fBKineticProto_Security_ACL_HMACAlgorithm\fPalgorithm)"

.PP
Definition at line 29 of file kinetic_hmac\&.c\&.
.PP
References KineticHMAC::algorithm, KINETIC_HMAC_MAX_LEN, KINETIC_PROTO_SECURITY_ACL_HMACALGORITHM_HmacSHA1, KINETIC_PROTO_SECURITY_ACL_HMACALGORITHM_INVALID_HMAC_ALGORITHM, KineticHMAC::value, and KineticHMAC::valueLength\&.
.SS "void KineticHMAC_Populate (\fBKineticHMAC\fP *hmac, \fBKineticProto\fP *proto, const char *constkey, size_tkeyLen)"

.PP
Definition at line 43 of file kinetic_hmac\&.c\&.
.PP
References KINETIC_PROTO_SECURITY_ACL_HMACALGORITHM_HmacSHA1, KineticHMAC_Init(), KineticHMAC::value, and KineticHMAC::valueLength\&.
.SS "bool KineticHMAC_Validate (const \fBKineticProto\fP *proto, const char *constkey, size_tkeyLen)"

.PP
Definition at line 54 of file kinetic_hmac\&.c\&.
.PP
References KINETIC_PROTO_SECURITY_ACL_HMACALGORITHM_HmacSHA1, KineticHMAC_Init(), KineticHMAC::value, and KineticHMAC::valueLength\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for protobuf-c from the source code\&.
