.TH "KineticEntry" 3 "Tue Nov 4 2014" "Version v0.8.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticEntry \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBByteBuffer\fP \fBkey\fP"
.br
.ti -1c
.RI "\fBByteBuffer\fP \fBvalue\fP"
.br
.ti -1c
.RI "\fBByteBuffer\fP \fBdbVersion\fP"
.br
.ti -1c
.RI "\fBByteBuffer\fP \fBtag\fP"
.br
.ti -1c
.RI "\fBKineticAlgorithm\fP \fBalgorithm\fP"
.br
.ti -1c
.RI "\fBByteBuffer\fP \fBnewVersion\fP"
.br
.ti -1c
.RI "bool \fBmetadataOnly\fP"
.br
.ti -1c
.RI "bool \fBforce\fP"
.br
.ti -1c
.RI "\fBKineticSynchronization\fP \fBsynchronization\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 179 of file kinetic_types\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBByteBuffer\fP KineticEntry::key"

.PP
Definition at line 180 of file kinetic_types\&.h\&.
.SS "\fBByteBuffer\fP KineticEntry::value"

.PP
Definition at line 181 of file kinetic_types\&.h\&.
.SS "\fBByteBuffer\fP KineticEntry::dbVersion"

.PP
Definition at line 184 of file kinetic_types\&.h\&.
.SS "\fBByteBuffer\fP KineticEntry::tag"

.PP
Definition at line 185 of file kinetic_types\&.h\&.
.SS "\fBKineticAlgorithm\fP KineticEntry::algorithm"

.PP
Definition at line 186 of file kinetic_types\&.h\&.
.SS "\fBByteBuffer\fP KineticEntry::newVersion"

.PP
Definition at line 189 of file kinetic_types\&.h\&.
.SS "bool KineticEntry::metadataOnly"

.PP
Definition at line 190 of file kinetic_types\&.h\&.
.SS "bool KineticEntry::force"

.PP
Definition at line 191 of file kinetic_types\&.h\&.
.SS "\fBKineticSynchronization\fP KineticEntry::synchronization"

.PP
Definition at line 192 of file kinetic_types\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
