.TH "KineticLogInfo_Limits" 3 "Tue Mar 3 2015" "Version v0.12.0-beta" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticLogInfo_Limits \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBmaxKeySize\fP"
.br
.ti -1c
.RI "uint32_t \fBmaxValueSize\fP"
.br
.ti -1c
.RI "uint32_t \fBmaxVersionSize\fP"
.br
.ti -1c
.RI "uint32_t \fBmaxTagSize\fP"
.br
.ti -1c
.RI "uint32_t \fBmaxConnections\fP"
.br
.ti -1c
.RI "uint32_t \fBmaxOutstandingReadRequests\fP"
.br
.ti -1c
.RI "uint32_t \fBmaxOutstandingWriteRequests\fP"
.br
.ti -1c
.RI "uint32_t \fBmaxMessageSize\fP"
.br
.ti -1c
.RI "uint32_t \fBmaxKeyRangeCount\fP"
.br
.ti -1c
.RI "uint32_t \fBmaxIdentityCount\fP"
.br
.ti -1c
.RI "uint32_t \fBmaxPinSize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 379 of file kinetic_types\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint32_t KineticLogInfo_Limits::maxKeySize"

.PP
Definition at line 380 of file kinetic_types\&.h\&.
.SS "uint32_t KineticLogInfo_Limits::maxValueSize"

.PP
Definition at line 381 of file kinetic_types\&.h\&.
.SS "uint32_t KineticLogInfo_Limits::maxVersionSize"

.PP
Definition at line 382 of file kinetic_types\&.h\&.
.SS "uint32_t KineticLogInfo_Limits::maxTagSize"

.PP
Definition at line 383 of file kinetic_types\&.h\&.
.SS "uint32_t KineticLogInfo_Limits::maxConnections"

.PP
Definition at line 384 of file kinetic_types\&.h\&.
.SS "uint32_t KineticLogInfo_Limits::maxOutstandingReadRequests"

.PP
Definition at line 385 of file kinetic_types\&.h\&.
.SS "uint32_t KineticLogInfo_Limits::maxOutstandingWriteRequests"

.PP
Definition at line 386 of file kinetic_types\&.h\&.
.SS "uint32_t KineticLogInfo_Limits::maxMessageSize"

.PP
Definition at line 387 of file kinetic_types\&.h\&.
.SS "uint32_t KineticLogInfo_Limits::maxKeyRangeCount"

.PP
Definition at line 388 of file kinetic_types\&.h\&.
.SS "uint32_t KineticLogInfo_Limits::maxIdentityCount"

.PP
Definition at line 389 of file kinetic_types\&.h\&.
.SS "uint32_t KineticLogInfo_Limits::maxPinSize"

.PP
Definition at line 390 of file kinetic_types\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
