kinetic_operation.c
NAME
kinetic_operation.c -
SYNOPSIS
#include 'kinetic_operation.h'
#include 'kinetic_controller.h'
#include 'kinetic_session.h'
#include 'kinetic_message.h'
#include 'kinetic_bus.h'
#include 'kinetic_response.h'
#include 'kinetic_nbo.h'
#include 'kinetic_auth.h'
#include 'kinetic_socket.h'
#include 'kinetic_device_info.h'
#include 'kinetic_allocator.h'
#include 'kinetic_logger.h'
#include <pthread.h>
#include <stdlib.h>
#include <errno.h>
#include <sys/time.h>
#include <stdio.h>
#include 'bus.h'
#include 'acl.h'
Macros
#define ATOMIC_FETCH_AND_INCREMENT(P) __sync_fetch_and_add(P, 1)
Functions
static void KineticOperation_ValidateOperation (KineticOperation *operation)
static KineticStatus KineticOperation_SendRequestInner (KineticOperation *const operation)
KineticStatus KineticOperation_SendRequest (KineticOperation *const operation)
static void log_request_seq_id (int fd, int64_t seq_id, KineticMessageType mt)
KineticStatus KineticOperation_GetStatus (const KineticOperation *const operation)
void KineticOperation_Complete (KineticOperation *operation, KineticStatus status)
KineticStatus KineticOperation_NoopCallback (KineticOperation *const operation, KineticStatus const status)
void KineticOperation_BuildNoop (KineticOperation *const operation)
KineticStatus KineticOperation_PutCallback (KineticOperation *const operation, KineticStatus const status)
KineticStatus KineticOperation_BuildPut (KineticOperation *const operation, KineticEntry *const entry)
static KineticStatus get_cb (const char *cmd_name, KineticOperation *const operation, KineticStatus const status)
static void build_get_command (KineticOperation *const operation, KineticEntry *const entry, KineticOperationCallback cb, KineticProto_Command_MessageType command_id)
static KineticStatus get_cmd_cb (KineticOperation *const operation, KineticStatus const status)
void KineticOperation_BuildGet (KineticOperation *const operation, KineticEntry *const entry)
static KineticStatus getprevious_cmd_cb (KineticOperation *const operation, KineticStatus const status)
void KineticOperation_BuildGetPrevious (KineticOperation *const operation, KineticEntry *const entry)
static KineticStatus getnext_cmd_cb (KineticOperation *const operation, KineticStatus const status)
void KineticOperation_BuildGetNext (KineticOperation *const operation, KineticEntry *const entry)
KineticStatus KineticOperation_FlushCallback (KineticOperation *const operation, KineticStatus const status)
void KineticOperation_BuildFlush (KineticOperation *const operation)
KineticStatus KineticOperation_DeleteCallback (KineticOperation *const operation, KineticStatus const status)
void KineticOperation_BuildDelete (KineticOperation *const operation, KineticEntry *const entry)
KineticStatus KineticOperation_GetKeyRangeCallback (KineticOperation *const operation, KineticStatus const status)
void KineticOperation_BuildGetKeyRange (KineticOperation *const operation, KineticKeyRange *range, ByteBufferArray *buffers)
KineticStatus KineticOperation_GetLogCallback (KineticOperation *const operation, KineticStatus const status)
void KineticOperation_BuildGetLog (KineticOperation *const operation, KineticLogInfo_Type type, KineticLogInfo **info)
void destroy_p2pOp (KineticProto_Command_P2POperation *proto_p2pOp)
KineticProto_Command_P2POperation * build_p2pOp (uint32_t nestingLevel, KineticP2P_Operation const *const p2pOp)
static void populateP2PStatusCodes (KineticP2P_Operation *const p2pOp, KineticProto_Command_P2POperation const *const p2pOperation)
KineticStatus KineticOperation_P2POperationCallback (KineticOperation *const operation, KineticStatus const status)
KineticStatus KineticOperation_BuildP2POperation (KineticOperation *const operation, KineticP2P_Operation *const p2pOp)
KineticStatus KineticOperation_SetPinCallback (KineticOperation *const operation, KineticStatus const status)
void KineticOperation_BuildSetPin (KineticOperation *const operation, ByteArray old_pin, ByteArray new_pin, bool lock)
KineticStatus KineticOperation_EraseCallback (KineticOperation *const operation, KineticStatus const status)
void KineticOperation_BuildErase (KineticOperation *const operation, bool secure_erase, ByteArray *pin)
KineticStatus KineticOperation_LockUnlockCallback (KineticOperation *const operation, KineticStatus const status)
void KineticOperation_BuildLockUnlock (KineticOperation *const operation, bool lock, ByteArray *pin)
KineticStatus KineticOperation_SetClusterVersionCallback (KineticOperation *const operation, KineticStatus const status)
void KineticOperation_BuildSetClusterVersion (KineticOperation *operation, int64_t new_cluster_version)
KineticStatus KineticOperation_SetACLCallback (KineticOperation *const operation, KineticStatus const status)
void KineticOperation_BuildSetACL (KineticOperation *const operation, struct ACL *ACLs)
KineticStatus KineticOperation_UpdateFirmwareCallback (KineticOperation *const operation, KineticStatus const status)
KineticStatus KineticOperation_BuildUpdateFirmware (KineticOperation *const operation, const char *fw_path)
Macro Definition Documentation
#define ATOMIC_FETCH_AND_INCREMENT(P) __sync_fetch_and_add(P, 1)
Definition at line 41 of file kinetic_operation.c.
Function Documentation
static void KineticOperation_ValidateOperation (KineticOperation *operation) [static]
Definition at line 235 of file kinetic_operation.c.
References KINETIC_ASSERT.
static KineticStatus KineticOperation_SendRequestInner (KineticOperation *constoperation) [static]
Definition at line 85 of file kinetic_operation.c.
References bus_send_request(), cleanup(), KINETIC_ASSERT, KINETIC_SEQUENCE_NOT_YET_BOUND, KINETIC_STATUS_INVALID, KINETIC_STATUS_MEMORY_ERROR, KINETIC_STATUS_SOCKET_ERROR, KINETIC_STATUS_SUCCESS, KineticAuth_PopulateHmac(), KineticAuth_PopulatePin(), KineticCountingSemaphore_Give(), KineticCountingSemaphore_Take(), KineticLogger_LogByteArray(), KineticLogger_LogHeader(), KineticLogger_LogProtobuf(), KineticNBO_FromHostU32(), KineticPDUHeader, KineticProto_command__get_packed_size(), KineticProto_command__pack(), KineticProto_Message__get_packed_size(), KineticProto_Message__pack(), KineticSession_GetNextSequenceCount(), LOG0, log_request_seq_id(), LOGF0, LOGF2, LOGF3, and PDU_HEADER_LEN.
KineticStatus KineticOperation_SendRequest (KineticOperation *constoperation)
Definition at line 46 of file kinetic_operation.c.
References KINETIC_ASSERT, KINETIC_STATUS_SUCCESS, and KineticOperation_SendRequestInner().
static void log_request_seq_id (intfd, int64_tseq_id, KineticMessageTypemt) [static]
Definition at line 70 of file kinetic_operation.c.
References LOGF2.
KineticStatus KineticOperation_GetStatus (const KineticOperation *constoperation)
Definition at line 226 of file kinetic_operation.c.
References KINETIC_STATUS_INVALID, and KineticResponse_GetStatus().
void KineticOperation_Complete (KineticOperation *operation, KineticStatusstatus)
Definition at line 245 of file kinetic_operation.c.
References KINETIC_ASSERT, KineticAllocator_FreeOperation(), KineticCountingSemaphore_Give(), and KineticCompletionData::status.
KineticStatus KineticOperation_NoopCallback (KineticOperation *constoperation, KineticStatus conststatus)
Definition at line 267 of file kinetic_operation.c.
References KINETIC_ASSERT, and LOGF3.
void KineticOperation_BuildNoop (KineticOperation *constoperation)
Definition at line 276 of file kinetic_operation.c.
References KINETIC_PROTO_COMMAND_MESSAGE_TYPE_NOOP, KineticOperation_NoopCallback(), and KineticOperation_ValidateOperation().
KineticStatus KineticOperation_PutCallback (KineticOperation *constoperation, KineticStatus conststatus)
Definition at line 284 of file kinetic_operation.c.
References ByteBuffer::array, BYTE_BUFFER_NONE, ByteBuffer_Append(), ByteBuffer_Reset(), ByteBuffer::bytesUsed, ByteArray::data, KineticEntry::dbVersion, KINETIC_ASSERT, KINETIC_STATUS_SUCCESS, ByteArray::len, LOGF3, and KineticEntry::newVersion.
KineticStatus KineticOperation_BuildPut (KineticOperation *constoperation, KineticEntry *constentry)
Definition at line 316 of file kinetic_operation.c.
References ByteBuffer::bytesUsed, KINETIC_OBJ_SIZE, KINETIC_PROTO_COMMAND_MESSAGE_TYPE_PUT, KINETIC_STATUS_BUFFER_OVERRUN, KINETIC_STATUS_SUCCESS, KineticMessage_ConfigureKeyValue(), KineticOperation_PutCallback(), KineticOperation_ValidateOperation(), LOGF2, and KineticEntry::value.
static KineticStatus get_cb (const char *cmd_name, KineticOperation *constoperation, KineticStatus conststatus) [static]
Definition at line 339 of file kinetic_operation.c.
References ByteBuffer_AppendArray(), ByteBuffer_IsNull(), Copy_KineticProto_Command_KeyValue_to_KineticEntry(), KINETIC_ASSERT, KINETIC_STATUS_BUFFER_OVERRUN, KINETIC_STATUS_SUCCESS, KineticResponse_GetKeyValue(), and LOGF3.
static void build_get_command (KineticOperation *constoperation, KineticEntry *constentry, KineticOperationCallbackcb, KineticProto_Command_MessageTypecommand_id) [static]
Definition at line 371 of file kinetic_operation.c.
References ByteBuffer_Reset(), KineticMessage_ConfigureKeyValue(), and KineticOperation_ValidateOperation().
static KineticStatus get_cmd_cb (KineticOperation *constoperation, KineticStatus conststatus) [static]
Definition at line 393 of file kinetic_operation.c.
References get_cb().
void KineticOperation_BuildGet (KineticOperation *constoperation, KineticEntry *constentry)
Definition at line 398 of file kinetic_operation.c.
References build_get_command(), get_cmd_cb(), and KINETIC_PROTO_COMMAND_MESSAGE_TYPE_GET.
static KineticStatus getprevious_cmd_cb (KineticOperation *constoperation, KineticStatus conststatus) [static]
Definition at line 405 of file kinetic_operation.c.
References get_cb().
void KineticOperation_BuildGetPrevious (KineticOperation *constoperation, KineticEntry *constentry)
Definition at line 410 of file kinetic_operation.c.
References build_get_command(), getprevious_cmd_cb(), and KINETIC_PROTO_COMMAND_MESSAGE_TYPE_GETPREVIOUS.
static KineticStatus getnext_cmd_cb (KineticOperation *constoperation, KineticStatus conststatus) [static]
Definition at line 417 of file kinetic_operation.c.
References get_cb().
void KineticOperation_BuildGetNext (KineticOperation *constoperation, KineticEntry *constentry)
Definition at line 422 of file kinetic_operation.c.
References build_get_command(), getnext_cmd_cb(), and KINETIC_PROTO_COMMAND_MESSAGE_TYPE_GETNEXT.
KineticStatus KineticOperation_FlushCallback (KineticOperation *constoperation, KineticStatus conststatus)
Definition at line 429 of file kinetic_operation.c.
References KINETIC_ASSERT, and LOGF3.
void KineticOperation_BuildFlush (KineticOperation *constoperation)
Definition at line 439 of file kinetic_operation.c.
References KINETIC_PROTO_COMMAND_MESSAGE_TYPE_FLUSHALLDATA, KineticOperation_FlushCallback(), and KineticOperation_ValidateOperation().
KineticStatus KineticOperation_DeleteCallback (KineticOperation *constoperation, KineticStatus conststatus)
Definition at line 449 of file kinetic_operation.c.
References KINETIC_ASSERT, and LOGF3.
void KineticOperation_BuildDelete (KineticOperation *constoperation, KineticEntry *constentry)
Definition at line 459 of file kinetic_operation.c.
References ByteBuffer_Reset(), KINETIC_PROTO_COMMAND_MESSAGE_TYPE_DELETE, KineticMessage_ConfigureKeyValue(), KineticOperation_DeleteCallback(), and KineticOperation_ValidateOperation().
KineticStatus KineticOperation_GetKeyRangeCallback (KineticOperation *constoperation, KineticStatus conststatus)
Definition at line 479 of file kinetic_operation.c.
References Copy_KineticProto_Command_Range_to_ByteBufferArray(), KINETIC_ASSERT, KINETIC_STATUS_BUFFER_OVERRUN, KINETIC_STATUS_SUCCESS, KineticResponse_GetKeyRange(), and LOGF3.
void KineticOperation_BuildGetKeyRange (KineticOperation *constoperation, KineticKeyRange *range, ByteBufferArray *buffers)
Definition at line 502 of file kinetic_operation.c.
References KINETIC_ASSERT, KINETIC_PROTO_COMMAND_MESSAGE_TYPE_GETKEYRANGE, KineticMessage_ConfigureKeyRange(), KineticOperation_GetKeyRangeCallback(), and KineticOperation_ValidateOperation().
KineticStatus KineticOperation_GetLogCallback (KineticOperation *constoperation, KineticStatus conststatus)
Definition at line 518 of file kinetic_operation.c.
References KINETIC_ASSERT, KINETIC_STATUS_OPERATION_FAILED, KINETIC_STATUS_SUCCESS, KineticLogInfo_Create(), and LOGF3.
void KineticOperation_BuildGetLog (KineticOperation *constoperation, KineticLogInfo_Typetype, KineticLogInfo **info)
Definition at line 541 of file kinetic_operation.c.
References KINETIC_PROTO_COMMAND_MESSAGE_TYPE_GETLOG, KineticLogInfo_Type_to_KineticProto_Command_GetLog_Type(), KineticOperation_GetLogCallback(), and KineticOperation_ValidateOperation().
void destroy_p2pOp (KineticProto_Command_P2POperation *proto_p2pOp)
Definition at line 560 of file kinetic_operation.c.
KineticProto_Command_P2POperation* build_p2pOp (uint32_tnestingLevel, KineticP2P_Operation const *constp2pOp)
Definition at line 589 of file kinetic_operation.c.
References ByteBuffer_IsNull(), destroy_p2pOp(), KINETIC_ASSERT, KINETIC_P2P_MAX_NESTING, KineticProto_command_p2_poperation__init(), KineticProto_command_p2_poperation_operation__init(), KineticProto_command_p2_poperation_peer__init(), and LOGF0.
static void populateP2PStatusCodes (KineticP2P_Operation *constp2pOp, KineticProto_Command_P2POperation const *constp2pOperation) [static]
Definition at line 659 of file kinetic_operation.c.
References KINETIC_STATUS_INVALID, and KineticProtoStatusCode_to_KineticStatus().
KineticStatus KineticOperation_P2POperationCallback (KineticOperation *constoperation, KineticStatus conststatus)
Definition at line 688 of file kinetic_operation.c.
References destroy_p2pOp(), KINETIC_STATUS_SUCCESS, and populateP2PStatusCodes().
KineticStatus KineticOperation_BuildP2POperation (KineticOperation *constoperation, KineticP2P_Operation *constp2pOp)
Definition at line 707 of file kinetic_operation.c.
References build_p2pOp(), KINETIC_P2P_OPERATION_LIMIT, KINETIC_PROTO_COMMAND_MESSAGE_TYPE_PEER2PEERPUSH, KINETIC_STATUS_BUFFER_OVERRUN, KINETIC_STATUS_OPERATION_INVALID, KINETIC_STATUS_SUCCESS, KineticOperation_P2POperationCallback(), and KineticOperation_ValidateOperation().
KineticStatus KineticOperation_SetPinCallback (KineticOperation *constoperation, KineticStatus conststatus)
Definition at line 737 of file kinetic_operation.c.
References KINETIC_ASSERT, and LOGF3.
void KineticOperation_BuildSetPin (KineticOperation *constoperation, ByteArrayold_pin, ByteArraynew_pin, boollock)
Definition at line 746 of file kinetic_operation.c.
References ByteArray::data, KINETIC_PROTO_COMMAND_MESSAGE_TYPE_SECURITY, KineticOperation_SetPinCallback(), KineticOperation_ValidateOperation(), and ByteArray::len.
KineticStatus KineticOperation_EraseCallback (KineticOperation *constoperation, KineticStatus conststatus)
Definition at line 776 of file kinetic_operation.c.
References KINETIC_ASSERT, and LOGF3.
void KineticOperation_BuildErase (KineticOperation *constoperation, boolsecure_erase, ByteArray *pin)
Definition at line 785 of file kinetic_operation.c.
References KINETIC_PROTO_COMMAND_MESSAGE_TYPE_PINOP, KINETIC_PROTO_COMMAND_PIN_OPERATION_PIN_OP_TYPE_ERASE_PINOP, KINETIC_PROTO_COMMAND_PIN_OPERATION_PIN_OP_TYPE_SECURE_ERASE_PINOP, KineticOperation_EraseCallback(), and KineticOperation_ValidateOperation().
KineticStatus KineticOperation_LockUnlockCallback (KineticOperation *constoperation, KineticStatus conststatus)
Definition at line 804 of file kinetic_operation.c.
References KINETIC_ASSERT, and LOGF3.
void KineticOperation_BuildLockUnlock (KineticOperation *constoperation, boollock, ByteArray *pin)
Definition at line 813 of file kinetic_operation.c.
References KINETIC_PROTO_COMMAND_MESSAGE_TYPE_PINOP, KINETIC_PROTO_COMMAND_PIN_OPERATION_PIN_OP_TYPE_LOCK_PINOP, KINETIC_PROTO_COMMAND_PIN_OPERATION_PIN_OP_TYPE_UNLOCK_PINOP, KineticOperation_LockUnlockCallback(), and KineticOperation_ValidateOperation().
KineticStatus KineticOperation_SetClusterVersionCallback (KineticOperation *constoperation, KineticStatus conststatus)
Definition at line 832 of file kinetic_operation.c.
References KINETIC_ASSERT, KINETIC_STATUS_SUCCESS, KineticSession_SetClusterVersion(), and LOGF3.
void KineticOperation_BuildSetClusterVersion (KineticOperation *operation, int64_tnew_cluster_version)
Definition at line 845 of file kinetic_operation.c.
References KINETIC_PROTO_COMMAND_MESSAGE_TYPE_SETUP, KineticOperation_SetClusterVersionCallback(), and KineticOperation_ValidateOperation().
KineticStatus KineticOperation_SetACLCallback (KineticOperation *constoperation, KineticStatus conststatus)
Definition at line 861 of file kinetic_operation.c.
References KINETIC_ASSERT, and LOGF3.
void KineticOperation_BuildSetACL (KineticOperation *constoperation, struct ACL *ACLs)
Definition at line 871 of file kinetic_operation.c.
References ACL::ACL_count, ACL::ACLs, KINETIC_PROTO_COMMAND_MESSAGE_TYPE_SECURITY, KineticOperation_SetACLCallback(), and KineticOperation_ValidateOperation().
KineticStatus KineticOperation_UpdateFirmwareCallback (KineticOperation *constoperation, KineticStatus conststatus)
Definition at line 887 of file kinetic_operation.c.
References KINETIC_ASSERT, and LOGF3.
KineticStatus KineticOperation_BuildUpdateFirmware (KineticOperation *constoperation, const char *fw_path)
Definition at line 902 of file kinetic_operation.c.
References cleanup(), KINETIC_PROTO_COMMAND_MESSAGE_TYPE_SETUP, KINETIC_STATUS_INVALID, KINETIC_STATUS_INVALID_FILE, KINETIC_STATUS_MEMORY_ERROR, KINETIC_STATUS_SUCCESS, KineticOperation_UpdateFirmwareCallback(), KineticOperation_ValidateOperation(), LOG0, and LOGF0.
Author
Generated automatically by Doxygen for kinetic-c from the source code.