.TH "KineticCompletionClosure" 3 "Fri Mar 13 2015" "Version v0.12.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticCompletionClosure \- 
.PP
Closure which can be specified for operations which support asynchronous mode\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBKineticCompletionCallback\fP \fBcallback\fP"
.br
.RI "\fIFunction to be called upon completion\&. \fP"
.ti -1c
.RI "void * \fBclientData\fP"
.br
.RI "\fIOptional client-supplied data which will be supplied to callback\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Closure which can be specified for operations which support asynchronous mode\&. 
.PP
Definition at line 225 of file kinetic_types\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBKineticCompletionCallback\fP KineticCompletionClosure::callback"

.PP
Function to be called upon completion\&. 
.PP
Definition at line 226 of file kinetic_types\&.h\&.
.SS "void* KineticCompletionClosure::clientData"

.PP
Optional client-supplied data which will be supplied to callback\&. 
.PP
Definition at line 227 of file kinetic_types\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
