.TH "KineticHMAC" 3 "Tue Nov 4 2014" "Version v0.8.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticHMAC \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_types_internal\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBKineticProto_Command_Security_ACL_HMACAlgorithm\fP \fBalgorithm\fP"
.br
.ti -1c
.RI "uint32_t \fBlen\fP"
.br
.ti -1c
.RI "uint8_t \fBdata\fP [\fBKINETIC_HMAC_MAX_LEN\fP]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 106 of file kinetic_types_internal\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBKineticProto_Command_Security_ACL_HMACAlgorithm\fP KineticHMAC::algorithm"

.PP
Definition at line 107 of file kinetic_types_internal\&.h\&.
.SS "uint32_t KineticHMAC::len"

.PP
Definition at line 108 of file kinetic_types_internal\&.h\&.
.SS "uint8_t KineticHMAC::data[\fBKINETIC_HMAC_MAX_LEN\fP]"

.PP
Definition at line 109 of file kinetic_types_internal\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
