.TH "KineticDeviceInfo_Utilization" 3 "Thu Nov 13 2014" "Version v0.8.1-beta" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticDeviceInfo_Utilization \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "float \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 217 of file kinetic_types\&.h\&.
.SH "Field Documentation"
.PP 
.SS "char* KineticDeviceInfo_Utilization::name"

.PP
Definition at line 218 of file kinetic_types\&.h\&.
.SS "float KineticDeviceInfo_Utilization::value"

.PP
Definition at line 219 of file kinetic_types\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
