.TH "KineticCompletionData" 3 "Wed Feb 11 2015" "Version v0.11.1" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticCompletionData \- 
.PP
Completion data which will be provided to \fBKineticCompletionClosure\fP for asynchronous operations\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int64_t \fBconnectionID\fP"
.br
.RI "\fIConnection ID for the session\&. \fP"
.ti -1c
.RI "int64_t \fBsequence\fP"
.br
.RI "\fISequence count for the operation\&. \fP"
.ti -1c
.RI "struct timeval \fBrequestTime\fP"
.br
.RI "\fITime at which the operation request was queued up\&. \fP"
.ti -1c
.RI "\fBKineticStatus\fP \fBstatus\fP"
.br
.RI "\fIResultant status of the operation\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Completion data which will be provided to \fBKineticCompletionClosure\fP for asynchronous operations\&. 
.PP
Definition at line 207 of file kinetic_types\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int64_t KineticCompletionData::connectionID"

.PP
Connection ID for the session\&. 
.PP
Definition at line 208 of file kinetic_types\&.h\&.
.SS "int64_t KineticCompletionData::sequence"

.PP
Sequence count for the operation\&. 
.PP
Definition at line 209 of file kinetic_types\&.h\&.
.SS "struct timeval KineticCompletionData::requestTime"

.PP
Time at which the operation request was queued up\&. 
.PP
Definition at line 210 of file kinetic_types\&.h\&.
.SS "\fBKineticStatus\fP KineticCompletionData::status"

.PP
Resultant status of the operation\&. 
.PP
Definition at line 211 of file kinetic_types\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
