kinetic_auth.h
NAME
kinetic_auth.h -
SYNOPSIS
#include 'kinetic_types_internal.h'
Functions
KineticStatus KineticAuth_EnsureSslEnabled (KineticSessionConfig const *const config)
KineticStatus KineticAuth_PopulateHmac (KineticSessionConfig const *const config, KineticRequest *const request)
KineticStatus KineticAuth_PopulatePin (KineticSessionConfig const *const config, KineticRequest *const request, ByteArray pin)
KineticStatus KineticAuth_PopulateTag (ByteBuffer *const tag, KineticAlgorithm algorithm, ByteArray const *const key)
Function Documentation
KineticStatus KineticAuth_EnsureSslEnabled (KineticSessionConfig const *constconfig)
Definition at line 26 of file kinetic_auth.c.
References KINETIC_STATUS_SSL_REQUIRED, KINETIC_STATUS_SUCCESS, and KineticSessionConfig::useSsl.
KineticStatus KineticAuth_PopulateHmac (KineticSessionConfig const *constconfig, KineticRequest *constrequest)
Definition at line 33 of file kinetic_auth.c.
References ByteArray::data, KineticSessionConfig::hmacKey, KineticSessionConfig::identity, KINETIC_HMAC_MAX_LEN, KINETIC_HMAC_SHA1_LEN, KINETIC_PROTO_COMMAND_SECURITY_ACL_HMACALGORITHM_HmacSHA1, KINETIC_PROTO_MESSAGE_AUTH_TYPE_HMACAUTH, KINETIC_STATUS_HMAC_REQUIRED, KINETIC_STATUS_SUCCESS, KineticHMAC_Init(), KineticHMAC_Populate(), KineticProto_Message_hmacauth__init(), ByteArray::len, and LOG3.
KineticStatus KineticAuth_PopulatePin (KineticSessionConfig const *constconfig, KineticRequest *constrequest, ByteArraypin)
Definition at line 76 of file kinetic_auth.c.
References KineticMessage::command, ByteArray::data, KineticMessage::header, KINETIC_PIN_MAX_LEN, KINETIC_PROTO_MESSAGE_AUTH_TYPE_PINAUTH, KINETIC_STATUS_SSL_REQUIRED, KINETIC_STATUS_SUCCESS, KineticProto_Message_pinauth__init(), ByteArray::len, LOG3, KineticMessage::message, KineticMessage::pinAuth, and KineticSessionConfig::useSsl.
KineticStatus KineticAuth_PopulateTag (ByteBuffer *consttag, KineticAlgorithmalgorithm, ByteArray const *constkey)
Definition at line 107 of file kinetic_auth.c.
References KINETIC_STATUS_INVALID.
Author
Generated automatically by Doxygen for kinetic-c from the source code.