kinetic_device_info.h
NAME
kinetic_device_info.h -
SYNOPSIS
#include 'kinetic_device_info.h'
#include 'kinetic_types_internal.h'
Functions
KineticLogInfo * KineticLogInfo_Create (const KineticProto_Command_GetLog *getLog)
void KineticLogInfo_Free (KineticLogInfo *kdi)
Function Documentation
KineticLogInfo* KineticLogInfo_Create (const KineticProto_Command_GetLog *getLog)
Definition at line 257 of file kinetic_device_info.c.
References KineticLogInfo::capacity, KineticLogInfo::configuration, ByteArray::data, KineticLogInfo::device, KINETIC_ASSERT, KineticLogInfo_GetCapacity(), KineticLogInfo_GetConfiguration(), KineticLogInfo_GetDevice(), KineticLogInfo_GetLimits(), KineticLogInfo_GetMessages(), KineticLogInfo_GetStatistics(), KineticLogInfo_GetTemperatures(), KineticLogInfo_GetUtilizations(), KineticLogInfo::limits, LOGF2, KineticLogInfo::messages, KineticLogInfo::numStatistics, KineticLogInfo::numTemperatures, KineticLogInfo::numUtilizations, KineticLogInfo::statistics, KineticLogInfo::temperatures, and KineticLogInfo::utilizations.
void KineticLogInfo_Free (KineticLogInfo *kdi)
Definition at line 323 of file kinetic_device_info.c.
References KineticLogInfo::capacity, KineticLogInfo_Configuration::compilationDate, KineticLogInfo::configuration, ByteArray::data, KineticLogInfo::device, KineticLogInfo_Configuration::interfaces, KineticLogInfo_Interface::ipv4Address, KineticLogInfo_Interface::ipv6Address, KineticLogInfo::limits, KineticLogInfo_Interface::MAC, KineticLogInfo::messages, KineticLogInfo_Configuration::model, KineticLogInfo_Utilization::name, KineticLogInfo_Temperature::name, KineticLogInfo_Interface::name, KineticLogInfo_Device::name, KineticLogInfo_Configuration::numInterfaces, KineticLogInfo::numTemperatures, KineticLogInfo::numUtilizations, KineticLogInfo_Configuration::protocolCompilationDate, KineticLogInfo_Configuration::protocolSourceHash, KineticLogInfo_Configuration::protocolVersion, KineticLogInfo_Configuration::serialNumber, KineticLogInfo_Configuration::sourceHash, KineticLogInfo::statistics, KineticLogInfo::temperatures, KineticLogInfo::utilizations, KineticLogInfo_Configuration::vendor, KineticLogInfo_Configuration::version, and KineticLogInfo_Configuration::worldWideName.
Author
Generated automatically by Doxygen for kinetic-c from the source code.