.TH "KineticLogInfo_Temperature" 3 "Mon Mar 2 2015" "Version v0.12.0-beta" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticLogInfo_Temperature \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "float \fBcurrent\fP"
.br
.ti -1c
.RI "float \fBminimum\fP"
.br
.ti -1c
.RI "float \fBmaximum\fP"
.br
.ti -1c
.RI "float \fBtarget\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 305 of file kinetic_types\&.h\&.
.SH "Field Documentation"
.PP 
.SS "char* KineticLogInfo_Temperature::name"

.PP
Definition at line 306 of file kinetic_types\&.h\&.
.SS "float KineticLogInfo_Temperature::current"

.PP
Definition at line 307 of file kinetic_types\&.h\&.
.SS "float KineticLogInfo_Temperature::minimum"

.PP
Definition at line 308 of file kinetic_types\&.h\&.
.SS "float KineticLogInfo_Temperature::maximum"

.PP
Definition at line 309 of file kinetic_types\&.h\&.
.SS "float KineticLogInfo_Temperature::target"

.PP
Definition at line 310 of file kinetic_types\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
