.TH "KineticP2P_OperationData" 3 "Tue Mar 3 2015" "Version v0.12.0-beta" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticP2P_OperationData \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBByteBuffer\fP \fBkey\fP"
.br
.ti -1c
.RI "\fBByteBuffer\fP \fBversion\fP"
.br
.ti -1c
.RI "\fBByteBuffer\fP \fBnewKey\fP"
.br
.ti -1c
.RI "KineticP2P_Operation * \fBchainedOperation\fP"
.br
.ti -1c
.RI "\fBKineticStatus\fP \fBresultStatus\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 420 of file kinetic_types\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBByteBuffer\fP KineticP2P_OperationData::key"

.PP
Definition at line 421 of file kinetic_types\&.h\&.
.SS "\fBByteBuffer\fP KineticP2P_OperationData::version"

.PP
Definition at line 422 of file kinetic_types\&.h\&.
.SS "\fBByteBuffer\fP KineticP2P_OperationData::newKey"

.PP
Definition at line 423 of file kinetic_types\&.h\&.
.SS "KineticP2P_Operation* KineticP2P_OperationData::chainedOperation"

.PP
Definition at line 424 of file kinetic_types\&.h\&.
.SS "\fBKineticStatus\fP KineticP2P_OperationData::resultStatus"

.PP
Definition at line 425 of file kinetic_types\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
