.TH "KineticP2P_Peer" 3 "Tue Dec 9 2014" "Version v0.9.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticP2P_Peer \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBhostname\fP"
.br
.ti -1c
.RI "int32_t \fBport\fP"
.br
.ti -1c
.RI "bool \fBtls\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 336 of file kinetic_types\&.h\&.
.SH "Field Documentation"
.PP 
.SS "char* KineticP2P_Peer::hostname"

.PP
Definition at line 337 of file kinetic_types\&.h\&.
.SS "int32_t KineticP2P_Peer::port"

.PP
Definition at line 338 of file kinetic_types\&.h\&.
.SS "bool KineticP2P_Peer::tls"

.PP
Definition at line 339 of file kinetic_types\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
