.TH "KineticKeyRange" 3 "Wed Oct 15 2014" "Version v0.7.0" "protobuf-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticKeyRange \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBByteBuffer\fP \fBstartKey\fP"
.br
.ti -1c
.RI "\fBByteBuffer\fP \fBendKey\fP"
.br
.ti -1c
.RI "bool \fBstartKeyInclusive\fP"
.br
.ti -1c
.RI "bool \fBendKeyInclusive\fP"
.br
.ti -1c
.RI "int32_t \fBmaxReturned\fP"
.br
.ti -1c
.RI "bool \fBreverse\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 171 of file kinetic_types\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBByteBuffer\fP KineticKeyRange::startKey"

.PP
Definition at line 172 of file kinetic_types\&.h\&.
.SS "\fBByteBuffer\fP KineticKeyRange::endKey"

.PP
Definition at line 173 of file kinetic_types\&.h\&.
.SS "bool KineticKeyRange::startKeyInclusive"

.PP
Definition at line 174 of file kinetic_types\&.h\&.
.SS "bool KineticKeyRange::endKeyInclusive"

.PP
Definition at line 175 of file kinetic_types\&.h\&.
.SS "int32_t KineticKeyRange::maxReturned"

.PP
Definition at line 176 of file kinetic_types\&.h\&.
.SS "bool KineticKeyRange::reverse"

.PP
Definition at line 177 of file kinetic_types\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for protobuf-c from the source code\&.
