.TH "KineticVersionInfo" 3 "Fri Mar 13 2015" "Version v0.12.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticVersionInfo \- 
.PP
kinetic-c library version info (returned from \fBKineticClient_Version()\fP)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const char * \fBversion\fP"
.br
.RI "\fIkinetic-c library version \fP"
.ti -1c
.RI "const char * \fBprotocolVersion\fP"
.br
.RI "\fIkinetic-protocol version library is built with \fP"
.ti -1c
.RI "const char * \fBrepoCommitHash\fP"
.br
.RI "\fIrepository commit hash which library is built from \fP"
.in -1c
.SH "Detailed Description"
.PP 
kinetic-c library version info (returned from \fBKineticClient_Version()\fP) 
.PP
Definition at line 64 of file kinetic_types\&.h\&.
.SH "Field Documentation"
.PP 
.SS "const char* KineticVersionInfo::version"

.PP
kinetic-c library version 
.PP
Definition at line 65 of file kinetic_types\&.h\&.
.SS "const char* KineticVersionInfo::protocolVersion"

.PP
kinetic-protocol version library is built with 
.PP
Definition at line 66 of file kinetic_types\&.h\&.
.SS "const char* KineticVersionInfo::repoCommitHash"

.PP
repository commit hash which library is built from 
.PP
Definition at line 67 of file kinetic_types\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
