kinetic_connection.c
NAME
kinetic_connection.c -
SYNOPSIS
#include 'kinetic_connection.h'
#include 'kinetic_types_internal.h'
#include 'kinetic_controller.h'
#include 'kinetic_socket.h'
#include 'kinetic_pdu.h'
#include 'kinetic_operation.h'
#include 'kinetic_allocator.h'
#include 'kinetic_logger.h'
#include <stdlib.h>
#include <string.h>
#include <pthread.h>
#include <errno.h>
#include <sys/time.h>
Functions
KineticStatus KineticSession_Create (KineticSession *const session)
KineticStatus KineticSession_Destroy (KineticSession *const session)
KineticStatus KineticSession_Connect (KineticSession const *const session)
KineticStatus KineticSession_Disconnect (KineticSession const *const session)
void KineticSession_IncrementSequence (KineticSession const *const session)
Function Documentation
KineticStatus KineticSession_Create (KineticSession *constsession)
Definition at line 36 of file kinetic_connection.c.
References KineticSession::connection, KINETIC_CONNECTION_INIT, KINETIC_STATUS_MEMORY_ERROR, KINETIC_STATUS_SESSION_EMPTY, KINETIC_STATUS_SUCCESS, KineticAllocator_NewConnection(), and KineticConnection::session.
KineticStatus KineticSession_Destroy (KineticSession *constsession)
Definition at line 52 of file kinetic_connection.c.
References KineticSession::connection, KINETIC_STATUS_SESSION_EMPTY, KINETIC_STATUS_SESSION_INVALID, KINETIC_STATUS_SUCCESS, KineticAllocator_FreeConnection(), and KineticConnection::writeMutex.
KineticStatus KineticSession_Connect (KineticSession const *constsession)
Definition at line 66 of file kinetic_connection.c.
References KineticSession::config, KineticThread::connection, KineticSession::connection, KineticSessionConfig::host, KINETIC_SOCKET_DESCRIPTOR_INVALID, KINETIC_STATUS_CONNECTION_ERROR, KINETIC_STATUS_SESSION_EMPTY, KINETIC_STATUS_SOCKET_TIMEOUT, KINETIC_STATUS_SUCCESS, KineticController_Init(), KineticSocket_Connect(), LOG0, KineticSessionConfig::port, and KineticConnection::thread.
KineticStatus KineticSession_Disconnect (KineticSession const *constsession)
Definition at line 112 of file kinetic_connection.c.
References KineticConnection::connected, KineticSession::connection, Kinetic_GetErrnoDescription(), KINETIC_HANDLE_INVALID, KINETIC_STATUS_CONNECTION_ERROR, KINETIC_STATUS_SESSION_EMPTY, KINETIC_STATUS_SUCCESS, LOG3, and LOGF0.
void KineticSession_IncrementSequence (KineticSession const *constsession)
Definition at line 142 of file kinetic_connection.c.
References KineticSession::connection, and KineticConnection::sequence.
Author
Generated automatically by Doxygen for kinetic-c from the source code.