kinetic_controller.c
NAME
kinetic_controller.c -
SYNOPSIS
#include 'kinetic_controller.h'
#include 'kinetic_session.h'
#include 'kinetic_operation.h'
#include 'kinetic_bus.h'
#include 'kinetic_response.h'
#include 'kinetic_auth.h'
#include 'kinetic_socket.h'
#include 'kinetic_allocator.h'
#include 'kinetic_resourcewaiter.h'
#include 'kinetic_logger.h'
#include <pthread.h>
#include 'bus.h'
Functions
KineticOperation * KineticController_CreateOperation (KineticSession const *const session)
static void DefaultCallback (KineticCompletionData *kinetic_data, void *client_data)
static KineticCompletionClosure DefaultClosure (DefaultCallbackData *const data)
KineticStatus KineticController_ExecuteOperation (KineticOperation *operation, KineticCompletionClosure *const closure)
KineticStatus bus_to_kinetic_status (bus_send_status_t const status)
static const char * bus_error_string (bus_send_status_t t)
void KineticController_HandleUnexpectedResponse (void *msg, int64_t seq_id, void *bus_udata, void *socket_udata)
void KineticController_HandleResult (bus_msg_result_t *res, void *udata)
Function Documentation
KineticOperation* KineticController_CreateOperation (KineticSession const *constsession)
Definition at line 34 of file kinetic_controller.c.
References KineticAllocator_NewOperation(), LOG0, and LOGF3.
static void DefaultCallback (KineticCompletionData *kinetic_data, void *client_data) [static]
Definition at line 64 of file kinetic_controller.c.
References KineticCompletionData::status.
static KineticCompletionClosure DefaultClosure (DefaultCallbackData *constdata) [static]
Definition at line 74 of file kinetic_controller.c.
References KineticCompletionClosure::callback, and DefaultCallback().
KineticStatus KineticController_ExecuteOperation (KineticOperation *operation, KineticCompletionClosure *constclosure)
Definition at line 82 of file kinetic_controller.c.
References DefaultClosure(), KINETIC_ASSERT, KINETIC_STATUS_INVALID, KINETIC_STATUS_SUCCESS, and KineticOperation_SendRequest().
KineticStatus bus_to_kinetic_status (bus_send_status_t conststatus)
Definition at line 122 of file kinetic_controller.c.
References BUS_SEND_BAD_RESPONSE, BUS_SEND_RX_FAILURE, BUS_SEND_RX_TIMEOUT, BUS_SEND_RX_TIMEOUT_EXPECT, BUS_SEND_SUCCESS, BUS_SEND_TX_FAILURE, BUS_SEND_TX_TIMEOUT, BUS_SEND_UNDEFINED, BUS_SEND_UNREGISTERED_SOCKET, KINETIC_ASSERT, KINETIC_STATUS_INVALID, KINETIC_STATUS_OPERATION_TIMEDOUT, KINETIC_STATUS_SOCKET_ERROR, KINETIC_STATUS_SOCKET_TIMEOUT, KINETIC_STATUS_SUCCESS, LOGF0, and LOGF3.
static const char* bus_error_string (bus_send_status_tt) [static]
Definition at line 167 of file kinetic_controller.c.
References BUS_SEND_BAD_RESPONSE, BUS_SEND_RX_FAILURE, BUS_SEND_RX_TIMEOUT, BUS_SEND_RX_TIMEOUT_EXPECT, BUS_SEND_SUCCESS, BUS_SEND_TX_FAILURE, BUS_SEND_TX_TIMEOUT, BUS_SEND_UNDEFINED, and BUS_SEND_UNREGISTERED_SOCKET.
void KineticController_HandleUnexpectedResponse (void *msg, int64_tseq_id, void *bus_udata, void *socket_udata)
Definition at line 191 of file kinetic_controller.c.
References KineticResponse::command, KineticResponse::header, KINETIC_PROTO_MESSAGE_AUTH_TYPE_UNSOLICITEDSTATUS, KineticAllocator_FreeKineticResponse(), KineticLogger_LogPrintf(), KineticLogger_LogProtobuf(), KineticLogger_LogTimestamp(), KineticResourceWaiter_SetAvailable(), LOG0, LOGF2, and KineticResponse::proto.
void KineticController_HandleResult (bus_msg_result_t *res, void *udata)
Definition at line 252 of file kinetic_controller.c.
References bus_error_string(), BUS_SEND_RX_TIMEOUT, bus_to_kinetic_status(), KineticResponse::command, KineticResponse::header, KINETIC_ASSERT, Kinetic_GetStatusDescription(), KINETIC_STATUS_INVALID, KINETIC_STATUS_SUCCESS, KineticLogger_LogHeader(), KineticLogger_LogProtobuf(), KineticLogger_LogTimestamp(), KineticOperation_Complete(), KineticProtoStatusCode_to_KineticStatus(), LOGF0, LOGF2, KineticResponse::proto, bus_msg_result_t::response, bus_msg_result_t::status, and bus_msg_result_t::u.
Author
Generated automatically by Doxygen for kinetic-c from the source code.