.TH "kinetic_message.c" 3 "Fri Mar 13 2015" "Version v0.12.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kinetic_message.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'kinetic_message\&.h'\fP
.br
\fC#include 'kinetic_logger\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCONFIG_FIELD_BYTE_BUFFER\fP(_name, _proto_name, _field, _entry)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBKineticMessage_ConfigureKeyValue\fP (\fBKineticMessage\fP *const message, const \fBKineticEntry\fP *entry)"
.br
.ti -1c
.RI "void \fBKineticMessage_ConfigureKeyRange\fP (\fBKineticMessage\fP *const message, const \fBKineticKeyRange\fP *range)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CONFIG_FIELD_BYTE_BUFFER(_name, _proto_name, _field, _entry)"
\fBValue:\fP
.PP
.nf
{ \
    if ((_entry)->_name\&.array\&.data != NULL \
        && (_entry)->_name\&.array\&.len > 0 \
        && (_entry)->_name\&.bytesUsed > 0 \
        && (_entry)->_name\&.bytesUsed <= (_entry)->_name\&.array\&.len) \
    { \
        (_field)\&._proto_name\&.data = (_entry)->_name\&.array\&.data; \
        (_field)\&._proto_name\&.len = (_entry)->_name\&.bytesUsed; \
        (_field)\&.has_ ## _proto_name = true; \
    } \
    else { \
        (_field)\&.has_ ## _proto_name = false; \
    } \
}
.fi
.PP
Definition at line 24 of file kinetic_message\&.c\&.
.SH "Function Documentation"
.PP 
.SS "void KineticMessage_ConfigureKeyValue (\fBKineticMessage\fP *constmessage, const \fBKineticEntry\fP *entry)"

.PP
Definition at line 39 of file kinetic_message\&.c\&.
.PP
References KineticEntry::algorithm, KineticMessage::body, Com__Seagate__Kinetic__Proto__Command__Algorithm_from_KineticAlgorithm(), Com__Seagate__Kinetic__Proto__Command__Synchronization_from_KineticSynchronization(), KineticMessage::command, CONFIG_FIELD_BYTE_BUFFER, KineticEntry::force, KineticMessage::keyValue, KINETIC_ASSERT, KineticEntry::metadataOnly, and KineticEntry::synchronization\&.
.SS "void KineticMessage_ConfigureKeyRange (\fBKineticMessage\fP *constmessage, const \fBKineticKeyRange\fP *range)"

.PP
Definition at line 80 of file kinetic_message\&.c\&.
.PP
References ByteBuffer::array, KineticMessage::body, ByteBuffer::bytesUsed, KineticMessage::command, ByteArray::data, KineticKeyRange::endKey, KineticKeyRange::endKeyInclusive, KineticMessage::keyRange, KINETIC_ASSERT, ByteArray::len, KineticKeyRange::maxReturned, KineticKeyRange::reverse, KineticKeyRange::startKey, and KineticKeyRange::startKeyInclusive\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
