.TH "KineticPDU" 3 "Tue Jul 15 2014" "Version v0.3.1-beta" "protobuf-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticPDU \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t * \fBprefix\fP"
.br
.ti -1c
.RI "uint8_t * \fBprotoLength\fP"
.br
.ti -1c
.RI "uint8_t * \fBvalueLength\fP"
.br
.ti -1c
.RI "uint8_t * \fBproto\fP"
.br
.ti -1c
.RI "uint8_t * \fBvalue\fP"
.br
.ti -1c
.RI "uint8_t * \fBdata\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 31 of file KineticPDU\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for protobuf-c from the source code\&.
