kinetic_admin_client.c
NAME
kinetic_admin_client.c -
SYNOPSIS
#include 'kinetic_admin_client.h'
#include 'kinetic_types_internal.h'
#include 'kinetic_controller.h'
#include 'kinetic_operation.h'
#include 'kinetic_allocator.h'
#include 'kinetic_auth.h'
#include 'kinetic_device_info.h'
#include 'acl.h'
Functions
KineticClient * KineticAdminClient_Init (KineticClientConfig *config)
Initializes the Kinetic Admin API and configures logging.
void KineticAdminClient_Shutdown (KineticClient *const client)
Performs shutdown/cleanup of the kinetic-c client library.
KineticStatus KineticAdminClient_CreateSession (KineticSessionConfig *const config, KineticClient *const client, KineticSession **session)
Creates a session with the Kinetic Device per specified configuration.
KineticStatus KineticAdminClient_DestroySession (KineticSession *const session)
Closes the connection to a host.
KineticStatus KineticAdminClient_SetErasePin (KineticSession const *const session, ByteArray old_pin, ByteArray new_pin)
Sets the erase PIN of the Kinetic Device.
KineticStatus KineticAdminClient_SecureErase (KineticSession const *const session, ByteArray pin)
Executes a SecureErase command to erase all data from the Kinetic device.
KineticStatus KineticAdminClient_InstantErase (KineticSession const *const session, ByteArray pin)
Executes an InstantErase command to erase all data from the Kinetic device.
KineticStatus KineticAdminClient_SetLockPin (KineticSession const *const session, ByteArray old_pin, ByteArray new_pin)
Sets the lock PIN of the Kinetic Device.
KineticStatus KineticAdminClient_LockDevice (KineticSession const *const session, ByteArray pin)
Executes a LOCK command to lock the Kinetic device.
KineticStatus KineticAdminClient_UnlockDevice (KineticSession const *const session, ByteArray pin)
Executes an UNLOCK command to unlock the Kinetic device.
KineticStatus KineticAdminClient_GetLog (KineticSession const *const session, KineticLogInfo_Type type, KineticLogInfo **info, KineticCompletionClosure *closure)
Executes a GETLOG command to retrieve specific configuration and/or operational data from the Kinetic Device.
void KineticClient_FreeLogInfo (KineticSession const *const session, KineticLogInfo *info)
KineticStatus KineticAdminClient_SetClusterVersion (KineticSession const *const session, int64_t version)
Updates the cluster version of the Kinetic Device.
KineticStatus KineticAdminClient_SetACL (KineticSession const *const session, const char *ACLPath)
Executes a SECURITY operation, setting one or more ACLs.
KineticStatus KineticAdminClient_UpdateFirmware (KineticSession const *const session, char const *const fw_path)
Executes a Firmware Download operation to update the firmware on the Kinetic device.
Function Documentation
KineticClient* KineticAdminClient_Init (KineticClientConfig *config)
Initializes the Kinetic Admin API and configures logging.
Parameters:
config A configuration struct.
Returns:
Returns a pointer to a KineticClient. You need to pass this pointer to KineticClient_CreateSession() to create new connections. Once you are finished will the KineticClient, and there are no active connections. The pointer should be released with KineticClient_Shutdown()
Definition at line 34 of file kinetic_admin_client.c.
References KineticClient_Init().
void KineticAdminClient_Shutdown (KineticClient *constclient)
Performs shutdown/cleanup of the kinetic-c client library.
Definition at line 39 of file kinetic_admin_client.c.
References KineticClient_Shutdown().
KineticStatus KineticAdminClient_CreateSession (KineticSessionConfig *constconfig, KineticClient *constclient, KineticSession **session)
Creates a session with the Kinetic Device per specified configuration.
Parameters:
config KineticSessionConfig structure which must be configured by the client prior to creating the device connection. .host Host name or IP address to connect to .port Port to establish socket connection on .clusterVersion Cluster version to use for the session .identity Identity to use for the session .hmacKey Key to use for HMAC calculations (NULL-terminated string) .pin PIN to use for PIN-based operations
client The KineticClient pointer returned from KineticClient_Init()
session Pointer to a KineticSession pointer that will be populated with the allocated/created session upon success.
Returns:
Returns the resulting KineticStatus, and session will be populated with a pointer to the session instance upon success. The client should call KineticClient_DestroySession() in order to shutdown a connection and cleanup resources when done using a KineticSession.
Definition at line 44 of file kinetic_admin_client.c.
References KineticClient_CreateSession().
KineticStatus KineticAdminClient_DestroySession (KineticSession *constsession)
Closes the connection to a host.
Parameters:
session The connected KineticSession to close. The session instance will be freed by this call after closing the connection, so the pointer should not longer be used.
Returns:
Returns the resulting KineticStatus.
Definition at line 50 of file kinetic_admin_client.c.
References KineticClient_DestroySession().
KineticStatus KineticAdminClient_SetErasePin (KineticSession const *constsession, ByteArrayold_pin, ByteArraynew_pin)
Sets the erase PIN of the Kinetic Device.
Parameters:
session The connected KineticSession to close. The session instance will be freed by this call after closing the connection, so the pointer should not longer be used.
old_pin Old erase PIN to change.
new_pin New erase PIN to change to.
Returns:
Returns the resulting KineticStatus.
Definition at line 56 of file kinetic_admin_client.c.
References ByteArray::data, KINETIC_STATUS_MEMORY_ERROR, KINETIC_STATUS_MISSING_PIN, KINETIC_STATUS_SUCCESS, KineticAllocator_NewOperation(), KineticAuth_EnsureSslEnabled(), KineticController_ExecuteOperation(), KineticOperation_BuildSetPin(), and ByteArray::len.
KineticStatus KineticAdminClient_SecureErase (KineticSession const *constsession, ByteArraypin)
Executes a SecureErase command to erase all data from the Kinetic device.
Parameters:
session The connected KineticSession to use for the operation.
pin PIN to send with operation, which must match the configured erase PIN.
Returns:
Returns the resulting KineticStatus.
Definition at line 76 of file kinetic_admin_client.c.
References ByteArray::data, KINETIC_STATUS_MEMORY_ERROR, KINETIC_STATUS_MISSING_PIN, KINETIC_STATUS_SUCCESS, KineticAllocator_NewOperation(), KineticAuth_EnsureSslEnabled(), KineticController_ExecuteOperation(), KineticOperation_BuildErase(), and ByteArray::len.
KineticStatus KineticAdminClient_InstantErase (KineticSession const *constsession, ByteArraypin)
Executes an InstantErase command to erase all data from the Kinetic device.
Parameters:
session The connected KineticSession to use for the operation.
pin PIN to send with operation, which must match the configured erase PIN.
Returns:
Returns the resulting KineticStatus.
Definition at line 98 of file kinetic_admin_client.c.
References ByteArray::data, KINETIC_STATUS_MEMORY_ERROR, KINETIC_STATUS_MISSING_PIN, KINETIC_STATUS_SUCCESS, KineticAllocator_NewOperation(), KineticAuth_EnsureSslEnabled(), KineticController_ExecuteOperation(), KineticOperation_BuildErase(), and ByteArray::len.
KineticStatus KineticAdminClient_SetLockPin (KineticSession const *constsession, ByteArrayold_pin, ByteArraynew_pin)
Sets the lock PIN of the Kinetic Device.
Parameters:
session The connected KineticSession to close. The session instance will be freed by this call after closing the connection, so the pointer should not longer be used.
old_pin Old erase PIN to change.
new_pin New erase PIN to change to.
Returns:
Returns the resulting KineticStatus.
Definition at line 121 of file kinetic_admin_client.c.
References ByteArray::data, KINETIC_STATUS_MEMORY_ERROR, KINETIC_STATUS_MISSING_PIN, KINETIC_STATUS_SUCCESS, KineticAllocator_NewOperation(), KineticAuth_EnsureSslEnabled(), KineticController_ExecuteOperation(), KineticOperation_BuildSetPin(), and ByteArray::len.
KineticStatus KineticAdminClient_LockDevice (KineticSession const *constsession, ByteArraypin)
Executes a LOCK command to lock the Kinetic device.
Parameters:
session The connected KineticSession to use for the operation.
pin PIN to send with operation, which must match the configured lock PIN.
Returns:
Returns the resulting KineticStatus.
Definition at line 141 of file kinetic_admin_client.c.
References ByteArray::data, KINETIC_STATUS_MEMORY_ERROR, KINETIC_STATUS_MISSING_PIN, KINETIC_STATUS_SUCCESS, KineticAllocator_NewOperation(), KineticAuth_EnsureSslEnabled(), KineticController_ExecuteOperation(), KineticOperation_BuildLockUnlock(), and ByteArray::len.
KineticStatus KineticAdminClient_UnlockDevice (KineticSession const *constsession, ByteArraypin)
Executes an UNLOCK command to unlock the Kinetic device.
Parameters:
session The connected KineticSession to use for the operation.
pin PIN to send with operation, which must match the configured lock PIN.
Returns:
Returns the resulting KineticStatus.
Definition at line 163 of file kinetic_admin_client.c.
References ByteArray::data, KINETIC_STATUS_MEMORY_ERROR, KINETIC_STATUS_MISSING_PIN, KINETIC_STATUS_SUCCESS, KineticAllocator_NewOperation(), KineticAuth_EnsureSslEnabled(), KineticController_ExecuteOperation(), KineticOperation_BuildLockUnlock(), and ByteArray::len.
KineticStatus KineticAdminClient_GetLog (KineticSession const *constsession, KineticLogInfo_Typetype, KineticLogInfo **info, KineticCompletionClosure *closure)
Executes a GETLOG command to retrieve specific configuration and/or operational data from the Kinetic Device.
Parameters:
session The connected KineticSession to use for the operation
type KineticLogDataType specifying data type to retrieve.
info KineticLogInfo pointer, which will be assigned to a dynamically allocated structure populated with the requested data, if successful. The client should call free() on this pointer in order to free the root and any nested structures.
closure Optional closure. If specified, operation will be executed in asynchronous mode, and closure callback will be called upon completion in another thread.
Returns:
Returns 0 upon success, -1 or the Kinetic status code upon failure
Definition at line 185 of file kinetic_admin_client.c.
References KINETIC_STATUS_MEMORY_ERROR, KineticAllocator_NewOperation(), KineticController_ExecuteOperation(), and KineticOperation_BuildGetLog().
void KineticClient_FreeLogInfo (KineticSession const *constsession, KineticLogInfo *info)
Definition at line 204 of file kinetic_admin_client.c.
References KineticLogInfo_Free().
KineticStatus KineticAdminClient_SetClusterVersion (KineticSession const *constsession, int64_tversion)
Updates the cluster version of the Kinetic Device.
Parameters:
session The connected KineticSession to use for the operation.
version New cluster version.
Returns:
Returns the resulting KineticStatus.
Definition at line 215 of file kinetic_admin_client.c.
References KINETIC_STATUS_MEMORY_ERROR, KineticAllocator_NewOperation(), KineticController_ExecuteOperation(), and KineticOperation_BuildSetClusterVersion().
KineticStatus KineticAdminClient_SetACL (KineticSession const *constsession, const char *ACLPath)
Executes a SECURITY operation, setting one or more ACLs.
Parameters:
session The connected KineticSession to use for the operation
ACLPath Path to a JSON file containing one or more ACLs.
Returns:
Returns 0 upon success, -1 or the Kinetic status code upon failure.
Definition at line 228 of file kinetic_admin_client.c.
References acl_of_file(), ACL_OK, KINETIC_STATUS_ACL_ERROR, KINETIC_STATUS_INVALID_REQUEST, KINETIC_STATUS_MEMORY_ERROR, KineticAllocator_NewOperation(), KineticController_ExecuteOperation(), and KineticOperation_BuildSetACL().
KineticStatus KineticAdminClient_UpdateFirmware (KineticSession const *constsession, char const *constfw_path)
Executes a Firmware Download operation to update the firmware on the Kinetic device.
Parameters:
session The connected KineticSession to use for the operation.
fw_path Path to firmware update image file.
Returns:
Returns the resulting KineticStatus.
Definition at line 259 of file kinetic_admin_client.c.
References KINETIC_STATUS_MEMORY_ERROR, KINETIC_STATUS_SUCCESS, KineticAllocator_NewOperation(), KineticController_ExecuteOperation(), and KineticOperation_BuildUpdateFirmware().
Author
Generated automatically by Doxygen for kinetic-c from the source code.