.TH "KineticThread" 3 "Tue Dec 9 2014" "Version v0.9.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticThread \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_types_internal\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "bool \fBabortRequested\fP"
.br
.ti -1c
.RI "bool \fBfatalError\fP"
.br
.ti -1c
.RI "bool \fBpaused\fP"
.br
.ti -1c
.RI "KineticConnection * \fBconnection\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 75 of file kinetic_types_internal\&.h\&.
.SH "Field Documentation"
.PP 
.SS "bool KineticThread::abortRequested"

.PP
Definition at line 76 of file kinetic_types_internal\&.h\&.
.SS "bool KineticThread::fatalError"

.PP
Definition at line 77 of file kinetic_types_internal\&.h\&.
.SS "bool KineticThread::paused"

.PP
Definition at line 78 of file kinetic_types_internal\&.h\&.
.SS "KineticConnection* KineticThread::connection"

.PP
Definition at line 79 of file kinetic_types_internal\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
