.TH "KineticLogInfo_Capacity" 3 "Fri Mar 13 2015" "Version v0.12.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticLogInfo_Capacity \- 
.PP
Log info capacity entry\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint64_t \fBnominalCapacityInBytes\fP"
.br
.ti -1c
.RI "float \fBportionFull\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Log info capacity entry\&. 
.PP
Definition at line 321 of file kinetic_types\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint64_t KineticLogInfo_Capacity::nominalCapacityInBytes"

.PP
Definition at line 322 of file kinetic_types\&.h\&.
.SS "float KineticLogInfo_Capacity::portionFull"

.PP
Definition at line 323 of file kinetic_types\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
