.TH "KineticDeviceInfo_Interface" 3 "Tue Dec 9 2014" "Version v0.9.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticDeviceInfo_Interface \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "\fBByteArray\fP \fBMAC\fP"
.br
.ti -1c
.RI "\fBByteArray\fP \fBipv4Address\fP"
.br
.ti -1c
.RI "\fBByteArray\fP \fBipv6Address\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 243 of file kinetic_types\&.h\&.
.SH "Field Documentation"
.PP 
.SS "char* KineticDeviceInfo_Interface::name"

.PP
Definition at line 244 of file kinetic_types\&.h\&.
.SS "\fBByteArray\fP KineticDeviceInfo_Interface::MAC"

.PP
Definition at line 245 of file kinetic_types\&.h\&.
.SS "\fBByteArray\fP KineticDeviceInfo_Interface::ipv4Address"

.PP
Definition at line 246 of file kinetic_types\&.h\&.
.SS "\fBByteArray\fP KineticDeviceInfo_Interface::ipv6Address"

.PP
Definition at line 247 of file kinetic_types\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
