kinetic_socket.c
NAME
kinetic_socket.c -
SYNOPSIS
#include 'kinetic_socket.h'
#include 'kinetic_logger.h'
#include 'kinetic_types_internal.h'
#include 'kinetic_proto.h'
#include 'protobuf-c/protobuf-c.h'
#include <stdlib.h>
#include <errno.h>
#include <string.h>
#include <stdio.h>
#include <sys/types.h>
#include <unistd.h>
#include <fcntl.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <netinet/tcp.h>
#include <sys/select.h>
#include <sys/ioctl.h>
#include <arpa/inet.h>
#include <netdb.h>
#include <signal.h>
#include <poll.h>
#include 'socket99.h'
Functions
int KineticSocket_Connect (const char *host, int port)
void KineticSocket_Close (int socket)
KineticWaitStatus KineticSocket_WaitUntilDataAvailable (int socket, int timeout)
int KineticSocket_DataBytesAvailable (int socket)
KineticStatus KineticSocket_Read (int socket, ByteBuffer *dest, size_t len)
KineticStatus KineticSocket_ReadProtobuf (int socket, KineticPDU *pdu)
KineticStatus KineticSocket_Write (int socket, ByteBuffer *src)
KineticStatus KineticSocket_WriteProtobuf (int socket, KineticPDU *pdu)
void KineticSocket_BeginPacket (int socket)
void KineticSocket_FinishPacket (int socket)
Function Documentation
int KineticSocket_Connect (const char *host, intport)
Definition at line 47 of file kinetic_socket.c.
References KINETIC_OBJ_SIZE, KINETIC_SOCKET_DESCRIPTOR_INVALID, LOG0, LOGF0, and LOGF1.
void KineticSocket_Close (intsocket)
Definition at line 135 of file kinetic_socket.c.
References LOG1, LOG2, and LOGF0.
KineticWaitStatus KineticSocket_WaitUntilDataAvailable (intsocket, inttimeout)
Definition at line 153 of file kinetic_socket.c.
References KINETIC_WAIT_STATUS_DATA_AVAILABLE, KINETIC_WAIT_STATUS_FATAL_ERROR, KINETIC_WAIT_STATUS_RETRYABLE_ERROR, and KINETIC_WAIT_STATUS_TIMED_OUT.
int KineticSocket_DataBytesAvailable (intsocket)
Definition at line 189 of file kinetic_socket.c.
KineticStatus KineticSocket_Read (intsocket, ByteBuffer *dest, size_tlen)
Definition at line 197 of file kinetic_socket.c.
References ByteBuffer::array, ByteBuffer::bytesUsed, ByteArray::data, KINETIC_STATUS_BUFFER_OVERRUN, KINETIC_STATUS_INVALID, KINETIC_STATUS_MEMORY_ERROR, KINETIC_STATUS_SOCKET_ERROR, KINETIC_STATUS_SOCKET_TIMEOUT, KINETIC_STATUS_SUCCESS, ByteArray::len, LOG0, LOGF0, LOGF1, LOGF2, and LOGF3.
KineticStatus KineticSocket_ReadProtobuf (intsocket, KineticPDU *pdu)
Definition at line 346 of file kinetic_socket.c.
References ByteBuffer::array, ByteBuffer_Create(), ByteBuffer::bytesUsed, ByteArray::data, KINETIC_STATUS_DATA_ERROR, KINETIC_STATUS_MEMORY_ERROR, KINETIC_STATUS_SUCCESS, KineticProto_Message__unpack(), KineticSocket_Read(), LOG0, LOG3, and LOGF3.
KineticStatus KineticSocket_Write (intsocket, ByteBuffer *src)
Definition at line 384 of file kinetic_socket.c.
References ByteBuffer::array, ByteBuffer::bytesUsed, ByteArray::data, KINETIC_STATUS_SOCKET_ERROR, KINETIC_STATUS_SUCCESS, LOG3, LOGF0, LOGF2, and LOGF3.
KineticStatus KineticSocket_WriteProtobuf (intsocket, KineticPDU *pdu)
Definition at line 407 of file kinetic_socket.c.
References ByteBuffer_Create(), KINETIC_STATUS_MEMORY_ERROR, KineticProto_Message__pack(), KineticSocket_Write(), LOG0, and LOGF3.
void KineticSocket_BeginPacket (intsocket)
Definition at line 429 of file kinetic_socket.c.
void KineticSocket_FinishPacket (intsocket)
Definition at line 439 of file kinetic_socket.c.
Author
Generated automatically by Doxygen for kinetic-c from the source code.