.TH "KineticDeviceInfo_Capacity" 3 "Thu Dec 11 2014" "Version v0.9.1" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticDeviceInfo_Capacity \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint64_t \fBnominalCapacityInBytes\fP"
.br
.ti -1c
.RI "float \fBportionFull\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 239 of file kinetic_types\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint64_t KineticDeviceInfo_Capacity::nominalCapacityInBytes"

.PP
Definition at line 240 of file kinetic_types\&.h\&.
.SS "float KineticDeviceInfo_Capacity::portionFull"

.PP
Definition at line 241 of file kinetic_types\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
