.TH "KineticLogInfo_Limits" 3 "Fri Mar 13 2015" "Version v0.12.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticLogInfo_Limits \- 
.PP
Log info device limits\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBmaxKeySize\fP"
.br
.ti -1c
.RI "uint32_t \fBmaxValueSize\fP"
.br
.ti -1c
.RI "uint32_t \fBmaxVersionSize\fP"
.br
.ti -1c
.RI "uint32_t \fBmaxTagSize\fP"
.br
.ti -1c
.RI "uint32_t \fBmaxConnections\fP"
.br
.ti -1c
.RI "uint32_t \fBmaxOutstandingReadRequests\fP"
.br
.ti -1c
.RI "uint32_t \fBmaxOutstandingWriteRequests\fP"
.br
.ti -1c
.RI "uint32_t \fBmaxMessageSize\fP"
.br
.ti -1c
.RI "uint32_t \fBmaxKeyRangeCount\fP"
.br
.ti -1c
.RI "uint32_t \fBmaxIdentityCount\fP"
.br
.ti -1c
.RI "uint32_t \fBmaxPinSize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Log info device limits\&. 
.PP
Definition at line 407 of file kinetic_types\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint32_t KineticLogInfo_Limits::maxKeySize"

.PP
Definition at line 408 of file kinetic_types\&.h\&.
.SS "uint32_t KineticLogInfo_Limits::maxValueSize"

.PP
Definition at line 409 of file kinetic_types\&.h\&.
.SS "uint32_t KineticLogInfo_Limits::maxVersionSize"

.PP
Definition at line 410 of file kinetic_types\&.h\&.
.SS "uint32_t KineticLogInfo_Limits::maxTagSize"

.PP
Definition at line 411 of file kinetic_types\&.h\&.
.SS "uint32_t KineticLogInfo_Limits::maxConnections"

.PP
Definition at line 412 of file kinetic_types\&.h\&.
.SS "uint32_t KineticLogInfo_Limits::maxOutstandingReadRequests"

.PP
Definition at line 413 of file kinetic_types\&.h\&.
.SS "uint32_t KineticLogInfo_Limits::maxOutstandingWriteRequests"

.PP
Definition at line 414 of file kinetic_types\&.h\&.
.SS "uint32_t KineticLogInfo_Limits::maxMessageSize"

.PP
Definition at line 415 of file kinetic_types\&.h\&.
.SS "uint32_t KineticLogInfo_Limits::maxKeyRangeCount"

.PP
Definition at line 416 of file kinetic_types\&.h\&.
.SS "uint32_t KineticLogInfo_Limits::maxIdentityCount"

.PP
Definition at line 417 of file kinetic_types\&.h\&.
.SS "uint32_t KineticLogInfo_Limits::maxPinSize"

.PP
Definition at line 418 of file kinetic_types\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
