kinetic_bus.c
NAME
kinetic_bus.c -
SYNOPSIS
#include 'kinetic_bus.h'
#include 'kinetic_nbo.h'
#include 'kinetic_session.h'
#include 'kinetic_socket.h'
#include 'kinetic_hmac.h'
#include 'kinetic_logger.h'
#include 'kinetic.pb-c.h'
#include 'kinetic_allocator.h'
#include 'kinetic_controller.h'
#include 'bus.h'
#include 'kinetic_pdu_unpack.h'
#include <time.h>
Functions
static void log_cb (log_event_t event, int log_level, const char *msg, void *udata)
static bus_sink_cb_res_t reset_transfer (socket_info *si)
static bool unpack_header (uint8_t const *const read_buf, size_t const read_size, KineticPDUHeader *const header)
static bus_sink_cb_res_t sink_cb (uint8_t *read_buf, size_t read_size, void *socket_udata)
static void log_response_seq_id (int fd, int64_t seq_id)
static bus_unpack_cb_res_t unpack_cb (void *msg, void *socket_udata)
bool KineticBus_Init (KineticClient *client, KineticClientConfig *config)
void KineticBus_Shutdown (KineticClient *const client)
Function Documentation
static void log_cb (log_event_tevent, intlog_level, const char *msg, void *udata) [static]
Definition at line 36 of file kinetic_bus.c.
References Bus_LogEventStr(), and KineticLogger_LogPrintf().
static bus_sink_cb_res_t reset_transfer (socket_info *si) [static]
Definition at line 42 of file kinetic_bus.c.
References KineticPDUHeader, bus_sink_cb_res_t::next_read, STATE_AWAITING_HEADER, and UNPACK_ERROR_UNDEFINED.
static bool unpack_header (uint8_t const *constread_buf, size_t constread_size, KineticPDUHeader *constheader) [static]
Definition at line 54 of file kinetic_bus.c.
References KineticNBO_ToHostU32(), KineticPDUHeader, and PDU_PROTO_MAX_LEN.
static bus_sink_cb_res_t sink_cb (uint8_t *read_buf, size_tread_size, void *socket_udata) [static]
Definition at line 80 of file kinetic_bus.c.
References KINETIC_ASSERT, KineticPDUHeader, bus_sink_cb_res_t::next_read, PDU_HEADER_LEN, reset_transfer(), STATE_AWAITING_BODY, STATE_AWAITING_HEADER, STATE_UNINIT, UNPACK_ERROR_INVALID_HEADER, UNPACK_ERROR_SUCCESS, and unpack_header().
static void log_response_seq_id (intfd, int64_tseq_id) [static]
Definition at line 161 of file kinetic_bus.c.
References LOGF2.
static bus_unpack_cb_res_t unpack_cb (void *msg, void *socket_udata) [static]
Definition at line 173 of file kinetic_bus.c.
References BUS_NO_SEQ_ID, COM__SEAGATE__KINETIC__PROTO__MESSAGE__AUTH_TYPE__UNSOLICITEDSTATUS, KineticResponse::command, KineticResponse::header, KINETIC_ASSERT, KineticAllocator_NewKineticResponse(), KineticPDU_unpack_command(), KineticPDU_unpack_message(), KineticSession_GetConnectionID(), log_response_seq_id(), KineticResponse::proto, UNPACK_ERROR_PAYLOAD_MALLOC_FAIL, UNPACK_ERROR_SUCCESS, and KineticResponse::value.
bool KineticBus_Init (KineticClient *client, KineticClientConfig *config)
Definition at line 242 of file kinetic_bus.c.
References KineticController_HandleUnexpectedResponse(), log_cb(), bus_config::log_cb, KineticClientConfig::logLevel, KineticClientConfig::maxThreadpoolThreads, KineticClientConfig::readerThreads, sink_cb(), unexpected_msg_cb(), and unpack_cb().
void KineticBus_Shutdown (KineticClient *constclient)
Definition at line 268 of file kinetic_bus.c.
References Bus_Free(), and Bus_Shutdown().
Author
Generated automatically by Doxygen for kinetic-c from the source code.