.TH "KineticSession" 3 "Tue Jan 27 2015" "Version v0.11.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticSession \- 
.PP
An instance of a session with a Kinetic device\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBKineticSessionConfig\fP \fBconfig\fP"
.br
.RI "\fISession configuration structure which must be configured\&. \fP"
.ti -1c
.RI "struct \fB_KineticConnection\fP * \fBconnection\fP"
.br
.RI "\fIConnection instance which is dynamically allocated upon call to \fCKineticClient_CreateConnection\fP\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
An instance of a session with a Kinetic device\&. 
.PP
Definition at line 143 of file kinetic_types\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBKineticSessionConfig\fP KineticSession::config"

.PP
Session configuration structure which must be configured\&. 
.PP
Definition at line 145 of file kinetic_types\&.h\&.
.SS "struct \fB_KineticConnection\fP* KineticSession::connection"

.PP
Connection instance which is dynamically allocated upon call to \fCKineticClient_CreateConnection\fP\&. Client must call \fCKineticClient_DestroyConnection\fP when finished with a session to shutdown a session cleanly and free the \fCconnection\fP\&. 
.PP
Definition at line 150 of file kinetic_types\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
