.TH "kinetic_nbo.h" 3 "Mon Mar 2 2015" "Version v0.12.0-beta" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kinetic_nbo.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'kinetic_types_internal\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "uint32_t \fBKineticNBO_FromHostU32\fP (uint32_t valueHost)"
.br
.ti -1c
.RI "uint32_t \fBKineticNBO_ToHostU32\fP (uint32_t valueNBO)"
.br
.ti -1c
.RI "uint64_t \fBKineticNBO_FromHostU64\fP (uint64_t valueHost)"
.br
.ti -1c
.RI "uint64_t \fBKineticNBO_ToHostU64\fP (uint64_t valueNBO)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "uint32_t KineticNBO_FromHostU32 (uint32_tvalueHost)"

.PP
Definition at line 32 of file kinetic_nbo\&.c\&.
.PP
References KineticNBO_SwapByteOrder()\&.
.SS "uint32_t KineticNBO_ToHostU32 (uint32_tvalueNBO)"

.PP
Definition at line 38 of file kinetic_nbo\&.c\&.
.PP
References KineticNBO_SwapByteOrder()\&.
.SS "uint64_t KineticNBO_FromHostU64 (uint64_tvalueHost)"

.PP
Definition at line 44 of file kinetic_nbo\&.c\&.
.PP
References KineticNBO_SwapByteOrder()\&.
.SS "uint64_t KineticNBO_ToHostU64 (uint64_tvalueNBO)"

.PP
Definition at line 50 of file kinetic_nbo\&.c\&.
.PP
References KineticNBO_SwapByteOrder()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
