.TH "kinetic_hmac.h" 3 "Fri Mar 13 2015" "Version v0.12.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kinetic_hmac.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'kinetic_types_internal\&.h'\fP
.br
\fC#include 'kinetic\&.pb-c\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBKineticHMAC_Init\fP (\fBKineticHMAC\fP *hmac, \fBCom__Seagate__Kinetic__Proto__Command__Security__ACL__HMACAlgorithm\fP algorithm)"
.br
.ti -1c
.RI "void \fBKineticHMAC_Populate\fP (\fBKineticHMAC\fP *hmac, Com__Seagate__Kinetic__Proto__Message *msg, const \fBByteArray\fP key)"
.br
.ti -1c
.RI "bool \fBKineticHMAC_Validate\fP (const Com__Seagate__Kinetic__Proto__Message *msg, const \fBByteArray\fP key)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void KineticHMAC_Init (\fBKineticHMAC\fP *hmac, \fBCom__Seagate__Kinetic__Proto__Command__Security__ACL__HMACAlgorithm\fPalgorithm)"

.PP
Definition at line 31 of file kinetic_hmac\&.c\&.
.PP
References KineticHMAC::algorithm, COM__SEAGATE__KINETIC__PROTO__COMMAND__SECURITY__ACL__HMACALGORITHM__HmacSHA1, COM__SEAGATE__KINETIC__PROTO__COMMAND__SECURITY__ACL__HMACALGORITHM__INVALID_HMAC_ALGORITHM, and KINETIC_HMAC_MAX_LEN\&.
.SS "void KineticHMAC_Populate (\fBKineticHMAC\fP *hmac, Com__Seagate__Kinetic__Proto__Message *msg, const \fBByteArray\fPkey)"

.PP
Definition at line 47 of file kinetic_hmac\&.c\&.
.PP
References COM__SEAGATE__KINETIC__PROTO__COMMAND__SECURITY__ACL__HMACALGORITHM__HmacSHA1, ByteArray::data, KineticHMAC::data, KINETIC_ASSERT, KineticHMAC_Compute(), KineticHMAC_Init(), ByteArray::len, and KineticHMAC::len\&.
.SS "bool KineticHMAC_Validate (const Com__Seagate__Kinetic__Proto__Message *msg, const \fBByteArray\fPkey)"

.PP
Definition at line 67 of file kinetic_hmac\&.c\&.
.PP
References COM__SEAGATE__KINETIC__PROTO__COMMAND__SECURITY__ACL__HMACALGORITHM__HmacSHA1, COM__SEAGATE__KINETIC__PROTO__MESSAGE__AUTH_TYPE__HMACAUTH, ByteArray::data, KineticHMAC::data, KINETIC_ASSERT, KineticHMAC_Compute(), KineticHMAC_Init(), KineticLogger_LogByteArray(), ByteArray::len, KineticHMAC::len, and LOG0\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
