.TH "kinetic_memory.h" 3 "Fri Mar 13 2015" "Version v0.12.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kinetic_memory.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stddef\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void * \fBKineticCalloc\fP (size_t count, size_t size)"
.br
.ti -1c
.RI "void \fBKineticFree\fP (void *pointer)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void* KineticCalloc (size_tcount, size_tsize)"

.PP
Definition at line 24 of file kinetic_memory\&.c\&.
.SS "void KineticFree (void *pointer)"

.PP
Definition at line 29 of file kinetic_memory\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
