.TH "KineticLogInfo" 3 "Fri Mar 13 2015" "Version v0.12.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticLogInfo \- 
.PP
Base log info structure which is allocated by client and passed to KineticAdminClient_GetLog\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBKineticLogInfo_Utilization\fP * \fButilizations\fP"
.br
.ti -1c
.RI "size_t \fBnumUtilizations\fP"
.br
.ti -1c
.RI "\fBKineticLogInfo_Temperature\fP * \fBtemperatures\fP"
.br
.ti -1c
.RI "size_t \fBnumTemperatures\fP"
.br
.ti -1c
.RI "\fBKineticLogInfo_Capacity\fP * \fBcapacity\fP"
.br
.ti -1c
.RI "\fBKineticLogInfo_Configuration\fP * \fBconfiguration\fP"
.br
.ti -1c
.RI "\fBKineticLogInfo_Statistics\fP * \fBstatistics\fP"
.br
.ti -1c
.RI "size_t \fBnumStatistics\fP"
.br
.ti -1c
.RI "\fBByteArray\fP \fBmessages\fP"
.br
.ti -1c
.RI "\fBKineticLogInfo_Limits\fP * \fBlimits\fP"
.br
.ti -1c
.RI "\fBKineticLogInfo_Device\fP * \fBdevice\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Base log info structure which is allocated by client and passed to KineticAdminClient_GetLog\&. 
.PP
Definition at line 431 of file kinetic_types\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBKineticLogInfo_Utilization\fP* KineticLogInfo::utilizations"

.PP
Definition at line 432 of file kinetic_types\&.h\&.
.SS "size_t KineticLogInfo::numUtilizations"

.PP
Definition at line 433 of file kinetic_types\&.h\&.
.SS "\fBKineticLogInfo_Temperature\fP* KineticLogInfo::temperatures"

.PP
Definition at line 434 of file kinetic_types\&.h\&.
.SS "size_t KineticLogInfo::numTemperatures"

.PP
Definition at line 435 of file kinetic_types\&.h\&.
.SS "\fBKineticLogInfo_Capacity\fP* KineticLogInfo::capacity"

.PP
Definition at line 436 of file kinetic_types\&.h\&.
.SS "\fBKineticLogInfo_Configuration\fP* KineticLogInfo::configuration"

.PP
Definition at line 437 of file kinetic_types\&.h\&.
.SS "\fBKineticLogInfo_Statistics\fP* KineticLogInfo::statistics"

.PP
Definition at line 438 of file kinetic_types\&.h\&.
.SS "size_t KineticLogInfo::numStatistics"

.PP
Definition at line 439 of file kinetic_types\&.h\&.
.SS "\fBByteArray\fP KineticLogInfo::messages"

.PP
Definition at line 440 of file kinetic_types\&.h\&.
.SS "\fBKineticLogInfo_Limits\fP* KineticLogInfo::limits"

.PP
Definition at line 441 of file kinetic_types\&.h\&.
.SS "\fBKineticLogInfo_Device\fP* KineticLogInfo::device"

.PP
Definition at line 442 of file kinetic_types\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
