.TH "kinetic_pdu.c" 3 "Fri Aug 8 2014" "Version v0.4.3" "protobuf-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kinetic_pdu.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'kinetic_types\&.h'\fP
.br
\fC#include 'kinetic_pdu\&.h'\fP
.br
\fC#include 'kinetic_socket\&.h'\fP
.br
\fC#include 'kinetic_hmac\&.h'\fP
.br
\fC#include 'kinetic_logger\&.h'\fP
.br
\fC#include 'kinetic_proto\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBKineticPDU_Init\fP (\fBKineticPDU\fP *const pdu, \fBKineticExchange\fP *const exchange, \fBKineticMessage\fP *const message, uint8_t *const value, int32_t valueLength)"
.br
.ti -1c
.RI "bool \fBKineticPDU_Send\fP (\fBKineticPDU\fP *const request)"
.br
.ti -1c
.RI "bool \fBKineticPDU_Receive\fP (\fBKineticPDU\fP *const response)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void KineticPDU_Init (\fBKineticPDU\fP *constpdu, \fBKineticExchange\fP *constexchange, \fBKineticMessage\fP *constmessage, uint8_t *constvalue, int32_tvalueLength)"

.PP
Definition at line 31 of file kinetic_pdu\&.c\&.
.PP
References KineticPDU::exchange, KineticMessage::header, KineticExchange_ConfigureHeader(), and KineticMessage::proto\&.
.SS "bool KineticPDU_Send (\fBKineticPDU\fP *constrequest)"

.PP
Definition at line 60 of file kinetic_pdu\&.c\&.
.PP
References KineticExchange::connection, KineticPDU::exchange, KineticPDU::header, KineticPDU::hmac, KineticExchange::key, KineticExchange::keyLength, KINETIC_PROTO_SECURITY_ACL_HMACALGORITHM_HmacSHA1, KineticHMAC_Init(), KineticHMAC_Populate(), KineticLogger_LogProtobuf(), KineticPDUHeader, KineticProto_get_packed_size(), KineticSocket_Write(), KineticSocket_WriteProtobuf(), LOG, LOGF, KineticPDU::message, KineticMessage::proto, KineticPDU::protobufLength, KineticConnection::socketDescriptor, KineticPDU::value, and KineticPDU::valueLength\&.
.SS "bool KineticPDU_Receive (\fBKineticPDU\fP *constresponse)"

.PP
Definition at line 107 of file kinetic_pdu\&.c\&.
.PP
References KineticExchange::connection, KineticPDU::exchange, KineticPDU::header, KineticExchange::key, KineticExchange::keyLength, KineticHMAC_Validate(), KineticLogger_LogHeader(), KineticLogger_LogProtobuf(), KineticPDUHeader, KineticSocket_Read(), KineticSocket_ReadProtobuf(), LOG, LOGF, KineticPDU::proto, KineticPDU::protobufScratch, KineticPDU::rawHeader, KineticConnection::socketDescriptor, KineticPDU::value, and KineticPDU::valueLength\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for protobuf-c from the source code\&.
