.TH "kinetic_entry.h" 3 "Fri Mar 13 2015" "Version v0.12.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kinetic_entry.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'kinetic_types_internal\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBKineticEntry_Init\fP (\fBKineticEntry\fP *entry)"
.br
.ti -1c
.RI "\fBByteBuffer\fP * \fBKineticEntry_GetVersion\fP (\fBKineticEntry\fP *entry)"
.br
.ti -1c
.RI "void \fBKineticEntry_SetVersion\fP (\fBKineticEntry\fP *entry, \fBByteBuffer\fP version)"
.br
.ti -1c
.RI "\fBByteBuffer\fP * \fBKineticEntry_GetTag\fP (\fBKineticEntry\fP *entry)"
.br
.ti -1c
.RI "void \fBKineticEntry_SetTag\fP (\fBKineticEntry\fP *entry, \fBByteBuffer\fP tag)"
.br
.ti -1c
.RI "\fBKineticAlgorithm\fP \fBKineticEntry_GetAlgorithm\fP (\fBKineticEntry\fP *entry)"
.br
.ti -1c
.RI "void \fBKineticEntry_SetAlgorithm\fP (\fBKineticEntry\fP *entry, \fBKineticAlgorithm\fP algorithm)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void KineticEntry_Init (\fBKineticEntry\fP *entry)"

.PP
Definition at line 24 of file kinetic_entry\&.c\&.
.PP
References BYTE_BUFFER_NONE, KineticEntry::key, and KINETIC_ASSERT\&.
.SS "\fBByteBuffer\fP* KineticEntry_GetVersion (\fBKineticEntry\fP *entry)"

.PP
Definition at line 33 of file kinetic_entry\&.c\&.
.PP
References KineticEntry::dbVersion, and KINETIC_ASSERT\&.
.SS "void KineticEntry_SetVersion (\fBKineticEntry\fP *entry, \fBByteBuffer\fPversion)"

.PP
Definition at line 39 of file kinetic_entry\&.c\&.
.PP
References KineticEntry::dbVersion, and KINETIC_ASSERT\&.
.SS "\fBByteBuffer\fP* KineticEntry_GetTag (\fBKineticEntry\fP *entry)"

.PP
Definition at line 45 of file kinetic_entry\&.c\&.
.PP
References KINETIC_ASSERT, and KineticEntry::tag\&.
.SS "void KineticEntry_SetTag (\fBKineticEntry\fP *entry, \fBByteBuffer\fPtag)"

.PP
Definition at line 51 of file kinetic_entry\&.c\&.
.PP
References KINETIC_ASSERT, and KineticEntry::tag\&.
.SS "\fBKineticAlgorithm\fP KineticEntry_GetAlgorithm (\fBKineticEntry\fP *entry)"

.PP
Definition at line 57 of file kinetic_entry\&.c\&.
.PP
References KineticEntry::algorithm, and KINETIC_ASSERT\&.
.SS "void KineticEntry_SetAlgorithm (\fBKineticEntry\fP *entry, \fBKineticAlgorithm\fPalgorithm)"

.PP
Definition at line 63 of file kinetic_entry\&.c\&.
.PP
References KineticEntry::algorithm, and KINETIC_ASSERT\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
