.TH "KineticLogInfo_Statistics" 3 "Fri Mar 13 2015" "Version v0.12.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticLogInfo_Statistics \- 
.PP
Log info statistics entry\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBKineticMessageType\fP \fBmessageType\fP"
.br
.ti -1c
.RI "uint64_t \fBcount\fP"
.br
.ti -1c
.RI "uint64_t \fBbytes\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Log info statistics entry\&. 
.PP
Definition at line 398 of file kinetic_types\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBKineticMessageType\fP KineticLogInfo_Statistics::messageType"

.PP
Definition at line 399 of file kinetic_types\&.h\&.
.SS "uint64_t KineticLogInfo_Statistics::count"

.PP
Definition at line 400 of file kinetic_types\&.h\&.
.SS "uint64_t KineticLogInfo_Statistics::bytes"

.PP
Definition at line 401 of file kinetic_types\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
