.TH "KineticP2P_Operation" 3 "Tue Dec 9 2014" "Version v0.9.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticP2P_Operation \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBKineticP2P_Peer\fP \fBpeer\fP"
.br
.ti -1c
.RI "size_t \fBnumOperations\fP"
.br
.ti -1c
.RI "\fBKineticP2P_OperationData\fP * \fBoperations\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 349 of file kinetic_types\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBKineticP2P_Peer\fP KineticP2P_Operation::peer"

.PP
Definition at line 350 of file kinetic_types\&.h\&.
.SS "size_t KineticP2P_Operation::numOperations"

.PP
Definition at line 351 of file kinetic_types\&.h\&.
.SS "\fBKineticP2P_OperationData\fP* KineticP2P_Operation::operations"

.PP
Definition at line 352 of file kinetic_types\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
