.TH "KineticPDUHeader" 3 "Wed Jul 30 2014" "Version v0.3.3" "protobuf-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticPDUHeader \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_pdu\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBversionPrefix\fP"
.br
.ti -1c
.RI "uint32_t \fBprotobufLength\fP"
.br
.ti -1c
.RI "uint32_t \fBvalueLength\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 34 of file kinetic_pdu\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint8_t KineticPDUHeader::versionPrefix"

.PP
Definition at line 36 of file kinetic_pdu\&.h\&.
.SS "uint32_t KineticPDUHeader::protobufLength"

.PP
Definition at line 37 of file kinetic_pdu\&.h\&.
.SS "uint32_t KineticPDUHeader::valueLength"

.PP
Definition at line 38 of file kinetic_pdu\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for protobuf-c from the source code\&.
