.TH "KineticKeyValue" 3 "Thu Sep 11 2014" "Version v0.6.0-beta-2" "protobuf-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KineticKeyValue \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinetic_types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBByteArray\fP \fBkey\fP"
.br
.ti -1c
.RI "\fBByteArray\fP \fBnewVersion\fP"
.br
.ti -1c
.RI "\fBByteArray\fP \fBdbVersion\fP"
.br
.ti -1c
.RI "\fBByteArray\fP \fBtag\fP"
.br
.ti -1c
.RI "bool \fBforce\fP"
.br
.ti -1c
.RI "\fBKineticProto_Algorithm\fP \fBalgorithm\fP"
.br
.ti -1c
.RI "bool \fBmetadataOnly\fP"
.br
.ti -1c
.RI "\fBKineticProto_Synchronization\fP \fBsynchronization\fP"
.br
.ti -1c
.RI "\fBByteArray\fP \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 223 of file kinetic_types\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBByteArray\fP KineticKeyValue::key"

.PP
Definition at line 225 of file kinetic_types\&.h\&.
.SS "\fBByteArray\fP KineticKeyValue::newVersion"

.PP
Definition at line 226 of file kinetic_types\&.h\&.
.SS "\fBByteArray\fP KineticKeyValue::dbVersion"

.PP
Definition at line 227 of file kinetic_types\&.h\&.
.SS "\fBByteArray\fP KineticKeyValue::tag"

.PP
Definition at line 228 of file kinetic_types\&.h\&.
.SS "bool KineticKeyValue::force"

.PP
Definition at line 229 of file kinetic_types\&.h\&.
.SS "\fBKineticProto_Algorithm\fP KineticKeyValue::algorithm"

.PP
Definition at line 230 of file kinetic_types\&.h\&.
.SS "bool KineticKeyValue::metadataOnly"

.PP
Definition at line 231 of file kinetic_types\&.h\&.
.SS "\fBKineticProto_Synchronization\fP KineticKeyValue::synchronization"

.PP
Definition at line 232 of file kinetic_types\&.h\&.
.SS "\fBByteArray\fP KineticKeyValue::value"

.PP
Definition at line 233 of file kinetic_types\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for protobuf-c from the source code\&.
