listener.c
NAME
listener.c -
SYNOPSIS
#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
#include <sys/time.h>
#include <assert.h>
#include <poll.h>
#include <err.h>
#include <time.h>
#include 'bus_internal_types.h'
#include 'listener.h'
#include 'listener_internal.h'
#include 'util.h'
#include 'atomic.h'
Macros
#define DEFAULT_READ_BUF_SIZE (1024L * 1024L)
#define INCOMING_MSG_PIPE 1
#define INCOMING_MSG_PIPE_ID 0
#define MSG_BP_1QTR (0.25)
#define MSG_BP_HALF (0.5)
#define MSG_BP_3QTR (2.0)
#define RX_INFO_BP_1QTR (0.5)
#define RX_INFO_BP_HALF (0.5)
#define RX_INFO_BP_3QTR (2.0)
#define THREADPOOL_BP (1.0)
#define TIMEOUT_DELAY 100
#define DUMP_READ 0
Functions
static void retry_delivery (listener *l, rx_info_t *info)
struct listener * listener_init (struct bus *b, struct bus_config *cfg)
bool listener_add_socket (struct listener *l, connection_info *ci, int notify_fd)
bool listener_remove_socket (struct listener *l, int fd)
static uint16_t get_backpressure (struct listener *l)
static void observe_backpressure (listener *l, size_t backpressure)
bool listener_hold_response (struct listener *l, int fd, int64_t seq_id, int16_t timeout_sec)
bool listener_expect_response (struct listener *l, boxed_msg *box, uint16_t *backpressure)
bool listener_shutdown (struct listener *l)
void listener_free (struct listener *l)
void * listener_mainloop (void *arg)
static void check_and_flush_incoming_msg_pipe (listener *l, int *res)
static void set_error_for_socket (listener *l, int id, int fd, rx_error_t err)
static void print_SSL_error (struct bus *b, connection_info *ci, int lvl, const char *prefix)
static bool socket_read_plain (struct bus *b, listener *l, int pfd_i, connection_info *ci)
static bool socket_read_ssl (struct bus *b, listener *l, int pfd_i, connection_info *ci)
static bool sink_socket_read (struct bus *b, listener *l, connection_info *ci, ssize_t size)
static void attempt_recv (listener *l, int available)
static rx_info_t * find_info_by_sequence_id (listener *l, int fd, int64_t seq_id)
static void process_unpacked_message (listener *l, connection_info *ci, bus_unpack_cb_res_t result)
static void tick_handler (listener *l)
static void dump_rx_info_table (listener *l)
static void clean_up_completed_info (listener *l, rx_info_t *info)
static void notify_message_failure (listener *l, rx_info_t *info, bus_send_status_t status)
static rx_info_t * get_free_rx_info (struct listener *l)
static connection_info * get_connection_info (struct listener *l, int fd)
static void release_rx_info (struct listener *l, rx_info_t *info)
static listener_msg * get_free_msg (listener *l)
static void release_msg (struct listener *l, listener_msg *msg)
static bool push_message (struct listener *l, listener_msg *msg)
static void msg_handler (listener *l, listener_msg *pmsg)
static void notify_caller (int fd)
static bool grow_read_buf (listener *l, size_t nsize)
static void add_socket (listener *l, connection_info *ci, int notify_fd)
static void free_ci (connection_info *ci)
static void remove_socket (listener *l, int fd)
static void hold_response (listener *l, int fd, int64_t seq_id, int16_t timeout_sec)
static rx_info_t * get_hold_rx_info (listener *l, int fd, int64_t seq_id)
static void attempt_delivery (listener *l, struct rx_info_t *info)
static void expect_response (listener *l, struct boxed_msg *box)
static void shutdown (listener *l)
Macro Definition Documentation
#define DEFAULT_READ_BUF_SIZE (1024L * 1024L)
Definition at line 37 of file listener.c.
#define INCOMING_MSG_PIPE 1
Definition at line 38 of file listener.c.
#define INCOMING_MSG_PIPE_ID 0
Definition at line 39 of file listener.c.
#define MSG_BP_1QTR (0.25)
Definition at line 111 of file listener.c.
#define MSG_BP_HALF (0.5)
Definition at line 112 of file listener.c.
#define MSG_BP_3QTR (2.0)
Definition at line 113 of file listener.c.
#define RX_INFO_BP_1QTR (0.5)
Definition at line 114 of file listener.c.
#define RX_INFO_BP_HALF (0.5)
Definition at line 115 of file listener.c.
#define RX_INFO_BP_3QTR (2.0)
Definition at line 116 of file listener.c.
#define THREADPOOL_BP (1.0)
Definition at line 117 of file listener.c.
#define TIMEOUT_DELAY 100
Definition at line 278 of file listener.c.
#define DUMP_READ 0
Definition at line 530 of file listener.c.
Function Documentation
static void retry_delivery (listener *l, rx_info_t *info) [static]
Definition at line 810 of file listener.c.
References listener::bus, BUS_ASSERT, BUS_LOG_SNPRINTF, bus_process_boxed_message(), BUS_SEND_SUCCESS, rx_info_t::expect, rx_info_t::id, LOG_MEMORY, observe_backpressure(), boxed_msg::out_seq_id, release_rx_info(), boxed_msg::result, RIS_EXPECT, RX_ERROR_DONE, RX_ERROR_READY_FOR_DELIVERY, rx_info_t::state, bus_msg_result_t::status, rx_info_t::u, and bus::udata.
struct listener* listener_init (struct bus *b, struct bus_config *cfg)
Definition at line 43 of file listener.c.
References listener::bus, BUS_LOG, listener::commit_pipe, listener::fds, listener_msg::id, rx_info_t::id, listener::incoming_msg_pipe, INCOMING_MSG_PIPE_ID, LOG_LISTENER, MAX_PENDING_MESSAGES, MAX_QUEUE_MESSAGES, listener::msg_freelist, listener::msgs, listener_msg::next, rx_info_t::next, RIS_INACTIVE, listener::rx_info, listener::rx_info_freelist, listener::rx_info_max_used, rx_info_t::state, and bus::udata.
bool listener_add_socket (struct listener *l, connection_info *ci, intnotify_fd)
Definition at line 88 of file listener.c.
References listener_msg::add_socket, get_free_msg(), MSG_ADD_SOCKET, push_message(), listener_msg::type, and listener_msg::u.
bool listener_remove_socket (struct listener *l, intfd)
Definition at line 100 of file listener.c.
References get_free_msg(), MSG_REMOVE_SOCKET, push_message(), listener_msg::remove_socket, listener_msg::type, and listener_msg::u.
static uint16_t get_backpressure (struct listener *l) [static]
Definition at line 119 of file listener.c.
References listener::bus, BUS_LOG_SNPRINTF, LOG_SENDER, MAX_PENDING_MESSAGES, MAX_QUEUE_MESSAGES, MSG_BP_1QTR, MSG_BP_3QTR, MSG_BP_HALF, listener::msgs_in_use, RX_INFO_BP_1QTR, RX_INFO_BP_3QTR, RX_INFO_BP_HALF, listener::rx_info_in_use, THREADPOOL_BP, bus::udata, and listener::upstream_backpressure.
static void observe_backpressure (listener *l, size_tbackpressure) [static]
Definition at line 154 of file listener.c.
References listener::upstream_backpressure.
bool listener_hold_response (struct listener *l, intfd, int64_tseq_id, int16_ttimeout_sec)
Definition at line 159 of file listener.c.
References listener::bus, BUS_LOG, BUS_LOG_SNPRINTF, get_free_msg(), listener_msg::hold, LOG_LISTENER, LOG_MEMORY, MSG_HOLD_RESPONSE, push_message(), listener_msg::type, listener_msg::u, and bus::udata.
bool listener_expect_response (struct listener *l, boxed_msg *box, uint16_t *backpressure)
Definition at line 186 of file listener.c.
References listener::bus, BUS_LOG_SNPRINTF, listener_msg::expect, get_backpressure(), get_free_msg(), LOG_MEMORY, MSG_EXPECT_RESPONSE, boxed_msg::out_seq_id, push_message(), listener_msg::type, listener_msg::u, and bus::udata.
bool listener_shutdown (struct listener *l)
Definition at line 212 of file listener.c.
References get_free_msg(), MSG_SHUTDOWN, push_message(), and listener_msg::type.
void listener_free (struct listener *l)
Definition at line 220 of file listener.c.
References listener_msg::add_socket, listener::bus, BUS_ASSERT, BUS_LOG_SNPRINTF, listener::commit_pipe, listener_msg::expect, rx_info_t::expect, listener::fds, free_ci(), INCOMING_MSG_PIPE, listener::incoming_msg_pipe, LOG_LISTENER, MAX_PENDING_MESSAGES, MAX_QUEUE_MESSAGES, MSG_ADD_SOCKET, MSG_EXPECT_RESPONSE, listener::msgs, listener::read_buf, remove_socket(), RIS_EXPECT, RIS_HOLD, RIS_INACTIVE, listener::rx_info, rx_info_t::state, listener::tracked_fds, listener_msg::type, listener_msg::u, rx_info_t::u, and bus::udata.
void* listener_mainloop (void *arg)
Definition at line 280 of file listener.c.
References attempt_recv(), BUS_ASSERT, BUS_LOG, BUS_LOG_SNPRINTF, check_and_flush_incoming_msg_pipe(), INCOMING_MSG_PIPE, LOG_LISTENER, tick_handler(), TIMEOUT_DELAY, bus::udata, and util_is_resumable_io_error().
static void check_and_flush_incoming_msg_pipe (listener *l, int *res) [static]
Definition at line 329 of file listener.c.
References listener::bus, BUS_LOG_SNPRINTF, listener::fds, INCOMING_MSG_PIPE_ID, LOG_LISTENER, msg_handler(), listener::msgs, and bus::udata.
static void set_error_for_socket (listener *l, intid, intfd, rx_error_terr) [static]
Definition at line 363 of file listener.c.
References listener::bus, BUS_ASSERT, BUS_LOG_SNPRINTF, rx_info_t::expect, boxed_msg::fd, listener::fds, INCOMING_MSG_PIPE, LOG_LISTENER, release_rx_info(), RIS_EXPECT, RIS_HOLD, RIS_INACTIVE, listener::rx_info, listener::rx_info_max_used, rx_info_t::state, rx_info_t::u, and bus::udata.
static void print_SSL_error (struct bus *b, connection_info *ci, intlvl, const char *prefix) [static]
Definition at line 396 of file listener.c.
References BUS_LOG_SNPRINTF, connection_info::fd, LOG_LISTENER, and bus::udata.
static bool socket_read_plain (struct bus *b, listener *l, intpfd_i, connection_info *ci) [static]
Definition at line 454 of file listener.c.
References BUS_LOG_SNPRINTF, connection_info::fd, LOG_LISTENER, listener::read_buf, RX_ERROR_READ_FAILURE, set_error_for_socket(), sink_socket_read(), connection_info::to_read_size, bus::udata, and util_is_resumable_io_error().
static bool socket_read_ssl (struct bus *b, listener *l, intpfd_i, connection_info *ci) [static]
Definition at line 477 of file listener.c.
References BUS_ASSERT, BUS_LOG_SNPRINTF, connection_info::fd, LOG_LISTENER, print_SSL_error(), listener::read_buf, RX_ERROR_POLLHUP, RX_ERROR_READ_FAILURE, set_error_for_socket(), sink_socket_read(), connection_info::ssl, connection_info::to_read_size, bus::udata, and util_is_resumable_io_error().
static bool sink_socket_read (struct bus *b, listener *l, connection_info *ci, ssize_tsize) [static]
Definition at line 532 of file listener.c.
References BUS_ASSERT, bus_lock_log(), BUS_LOG, BUS_LOG_SNPRINTF, bus_unlock_log(), bus_sink_cb_res_t::full_msg_buffer, grow_read_buf(), LOG_LISTENER, LOG_MEMORY, bus_sink_cb_res_t::next_read, bus_unpack_cb_res_t::ok, process_unpacked_message(), listener::read_buf, listener::read_buf_size, bus::sink_cb, bus_unpack_cb_res_t::success, connection_info::to_read_size, bus_unpack_cb_res_t::u, bus::udata, connection_info::udata, and bus::unpack_cb.
static void attempt_recv (listener *l, intavailable) [static]
Definition at line 411 of file listener.c.
References listener::bus, BUS_ASSERT, BUS_LOG, BUS_LOG_SNPRINTF, BUS_SOCKET_PLAIN, BUS_SOCKET_SSL, connection_info::fd, listener::fd_info, listener::fds, INCOMING_MSG_PIPE, LOG_LISTENER, listener::read_buf_size, RX_ERROR_POLLERR, RX_ERROR_POLLHUP, set_error_for_socket(), socket_read_plain(), socket_read_ssl(), connection_info::to_read_size, listener::tracked_fds, connection_info::type, and bus::udata.
static rx_info_t* find_info_by_sequence_id (listener *l, intfd, int64_tseq_id) [static]
Definition at line 575 of file listener.c.
References listener::bus, BUS_ASSERT, BUS_LOG_SNPRINTF, dump_rx_info_table(), rx_info_t::expect, boxed_msg::fd, rx_info_t::hold, rx_info_t::id, bus::log_level, LOG_LISTENER, LOG_MEMORY, boxed_msg::out_seq_id, RIS_EXPECT, RIS_HOLD, RIS_INACTIVE, listener::rx_info, listener::rx_info_max_used, rx_info_t::state, rx_info_t::u, and bus::udata.
static void process_unpacked_message (listener *l, connection_info *ci, bus_unpack_cb_res_tresult) [static]
Definition at line 620 of file listener.c.
References attempt_delivery(), listener::bus, BUS_ASSERT, BUS_LOG_SNPRINTF, BUS_NO_SEQ_ID, bus_unpack_cb_res_t::error, bus::error_cb, rx_info_t::expect, connection_info::fd, find_info_by_sequence_id(), rx_info_t::hold, rx_info_t::id, connection_info::largest_seq_id_seen, LOG_LISTENER, bus_unpack_cb_res_t::ok, RIS_EXPECT, RIS_HOLD, RIS_INACTIVE, RX_ERROR_READY_FOR_DELIVERY, rx_info_t::state, bus_unpack_cb_res_t::success, rx_info_t::u, bus_unpack_cb_res_t::u, bus::udata, connection_info::udata, and bus::unexpected_msg_cb.
static void tick_handler (listener *l) [static]
Definition at line 687 of file listener.c.
References listener::bus, BUS_ASSERT, BUS_LOG, BUS_LOG_SNPRINTF, BUS_SEND_RX_FAILURE, BUS_SEND_RX_TIMEOUT, clean_up_completed_info(), dump_rx_info_table(), rx_info_t::expect, boxed_msg::fd, rx_info_t::hold, rx_info_t::id, listener::is_idle, bus::log_level, LOG_LISTENER, MAX_PENDING_MESSAGES, MAX_QUEUE_MESSAGES, listener::msgs, listener::msgs_in_use, notify_message_failure(), boxed_msg::out_seq_id, release_rx_info(), retry_delivery(), RIS_EXPECT, RIS_HOLD, RIS_INACTIVE, RX_ERROR_DONE, RX_ERROR_NONE, RX_ERROR_READY_FOR_DELIVERY, listener::rx_info, listener::rx_info_in_use, listener::rx_info_max_used, rx_info_t::state, rx_info_t::timeout_sec, listener::tracked_fds, boxed_msg::tv_send_done, boxed_msg::tv_send_start, listener_msg::type, rx_info_t::u, and bus::udata.
static void dump_rx_info_table (listener *l) [static]
Definition at line 784 of file listener.c.
References rx_info_t::expect, boxed_msg::fd, rx_info_t::hold, rx_info_t::id, rx_info_t::next, boxed_msg::out_seq_id, RIS_EXPECT, RIS_HOLD, RIS_INACTIVE, listener::rx_info, listener::rx_info_max_used, rx_info_t::state, rx_info_t::timeout_sec, and rx_info_t::u.
static void clean_up_completed_info (listener *l, rx_info_t *info) [static]
Definition at line 838 of file listener.c.
References listener::bus, BUS_ASSERT, BUS_LOG_SNPRINTF, bus_process_boxed_message(), BUS_SEND_SUCCESS, rx_info_t::expect, boxed_msg::fd, rx_info_t::id, LOG_MEMORY, observe_backpressure(), boxed_msg::out_msg, boxed_msg::out_seq_id, release_rx_info(), boxed_msg::result, RIS_EXPECT, RX_ERROR_DONE, rx_info_t::state, bus_msg_result_t::status, rx_info_t::timeout_sec, rx_info_t::u, and bus::udata.
static void notify_message_failure (listener *l, rx_info_t *info, bus_send_status_tstatus) [static]
Definition at line 877 of file listener.c.
References listener::bus, BUS_ASSERT, BUS_LOG_SNPRINTF, bus_process_boxed_message(), rx_info_t::expect, LOG_MEMORY, observe_backpressure(), release_rx_info(), RIS_EXPECT, RX_ERROR_DONE, rx_info_t::state, rx_info_t::u, and bus::udata.
static rx_info_t* get_free_rx_info (struct listener *l) [static]
Definition at line 904 of file listener.c.
References listener::bus, BUS_ASSERT, BUS_LOG, BUS_LOG_SNPRINTF, rx_info_t::id, LOG_LISTENER, LOG_SENDER, MAX_PENDING_MESSAGES, rx_info_t::next, RIS_INACTIVE, listener::rx_info, listener::rx_info_freelist, listener::rx_info_in_use, listener::rx_info_max_used, rx_info_t::state, and bus::udata.
static connection_info* get_connection_info (struct listener *l, intfd) [static]
Definition at line 931 of file listener.c.
References listener::bus, BUS_ASSERT, connection_info::fd, listener::fd_info, listener::tracked_fds, and bus::udata.
static void release_rx_info (struct listener *l, rx_info_t *info) [static]
Definition at line 941 of file listener.c.
References listener::bus, BUS_ASSERT, BUS_LOG_SNPRINTF, rx_info_t::expect, get_connection_info(), rx_info_t::hold, rx_info_t::id, LOG_LISTENER, MAX_PENDING_MESSAGES, rx_info_t::next, RIS_EXPECT, RIS_HOLD, RIS_INACTIVE, RX_ERROR_DONE, listener::rx_info, listener::rx_info_freelist, listener::rx_info_in_use, listener::rx_info_max_used, rx_info_t::state, rx_info_t::u, bus::udata, connection_info::udata, and bus::unexpected_msg_cb.
static listener_msg* get_free_msg (listener *l) [static]
Definition at line 1008 of file listener.c.
References ATOMIC_BOOL_COMPARE_AND_SWAP, listener::bus, BUS_ASSERT, BUS_LOG, BUS_LOG_SNPRINTF, LOG_LISTENER, listener::msg_freelist, MSG_NONE, listener::msgs_in_use, listener_msg::next, listener_msg::type, and bus::udata.
static void release_msg (struct listener *l, listener_msg *msg) [static]
Definition at line 1044 of file listener.c.
References ATOMIC_BOOL_COMPARE_AND_SWAP, listener::bus, BUS_ASSERT, BUS_LOG, listener_msg::id, LOG_LISTENER, MAX_QUEUE_MESSAGES, listener::msg_freelist, MSG_NONE, listener::msgs_in_use, listener_msg::next, listener_msg::type, and bus::udata.
static bool push_message (struct listener *l, listener_msg *msg) [static]
Definition at line 1065 of file listener.c.
References listener::bus, BUS_ASSERT, BUS_LOG_SNPRINTF, listener::commit_pipe, listener_msg::id, LOG_LISTENER, release_msg(), and bus::udata.
static void msg_handler (listener *l, listener_msg *pmsg) [static]
Definition at line 1090 of file listener.c.
References listener_msg::add_socket, add_socket(), listener::bus, BUS_ASSERT, BUS_LOG_SNPRINTF, listener_msg::expect, expect_response(), listener_msg::hold, hold_response(), listener::is_idle, LOG_LISTENER, MSG_ADD_SOCKET, MSG_EXPECT_RESPONSE, MSG_HOLD_RESPONSE, MSG_NONE, MSG_REMOVE_SOCKET, MSG_SHUTDOWN, release_msg(), listener_msg::remove_socket, remove_socket(), shutdown(), listener_msg::type, listener_msg::u, and bus::udata.
static void notify_caller (intfd) [static]
Definition at line 1125 of file listener.c.
static bool grow_read_buf (listener *l, size_tnsize) [static]
Definition at line 1141 of file listener.c.
References listener::bus, BUS_LOG_SNPRINTF, LOG_MEMORY, listener::read_buf, listener::read_buf_size, and bus::udata.
static void add_socket (listener *l, connection_info *ci, intnotify_fd) [static]
Definition at line 1159 of file listener.c.
References listener::bus, BUS_ASSERT, BUS_LOG, connection_info::fd, listener::fd_info, listener::fds, bus_sink_cb_res_t::full_msg_buffer, grow_read_buf(), INCOMING_MSG_PIPE, LOG_LISTENER, MAX_FDS, bus_sink_cb_res_t::next_read, notify_caller(), listener::read_buf, bus::sink_cb, connection_info::to_read_size, listener::tracked_fds, bus::udata, and connection_info::udata.
static void free_ci (connection_info *ci) [static]
Definition at line 1197 of file listener.c.
References connection_info::ssl.
static void remove_socket (listener *l, intfd) [static]
Definition at line 1205 of file listener.c.
References listener::bus, BUS_LOG_SNPRINTF, listener::fd_info, listener::fds, free_ci(), INCOMING_MSG_PIPE, LOG_LISTENER, listener::tracked_fds, and bus::udata.
static void hold_response (listener *l, intfd, int64_tseq_id, int16_ttimeout_sec) [static]
Definition at line 1230 of file listener.c.
References listener::bus, BUS_ASSERT, BUS_LOG_SNPRINTF, get_free_rx_info(), rx_info_t::hold, rx_info_t::id, LOG_LISTENER, RIS_HOLD, RIS_INACTIVE, rx_info_t::state, rx_info_t::timeout_sec, rx_info_t::u, and bus::udata.
static rx_info_t* get_hold_rx_info (listener *l, intfd, int64_tseq_id) [static]
Definition at line 1254 of file listener.c.
References rx_info_t::hold, RIS_HOLD, listener::rx_info, listener::rx_info_max_used, rx_info_t::state, and rx_info_t::u.
static void attempt_delivery (listener *l, struct rx_info_t *info) [static]
Definition at line 1266 of file listener.c.
References listener::bus, BUS_ASSERT, BUS_LOG_SNPRINTF, bus_process_boxed_message(), BUS_SEND_SUCCESS, clean_up_completed_info(), rx_info_t::expect, rx_info_t::id, LOG_LISTENER, LOG_MEMORY, observe_backpressure(), bus_unpack_cb_res_t::ok, bus_msg_result_t::response, boxed_msg::result, RIS_EXPECT, RIS_HOLD, RIS_INACTIVE, RX_ERROR_DONE, rx_info_t::state, bus_msg_result_t::status, bus_unpack_cb_res_t::success, rx_info_t::u, bus_unpack_cb_res_t::u, bus_msg_result_t::u, and bus::udata.
static void expect_response (listener *l, struct boxed_msg *box) [static]
Definition at line 1316 of file listener.c.
References attempt_delivery(), listener::bus, BUS_ASSERT, BUS_LOG_SNPRINTF, BUS_SEND_RX_TIMEOUT_EXPECT, rx_info_t::expect, boxed_msg::fd, get_free_rx_info(), get_hold_rx_info(), rx_info_t::hold, rx_info_t::id, LOG_LISTENER, LOG_MEMORY, notify_message_failure(), boxed_msg::out_seq_id, RIS_EXPECT, RIS_HOLD, RIS_INACTIVE, RX_ERROR_NONE, RX_ERROR_READY_FOR_DELIVERY, rx_info_t::state, boxed_msg::timeout_sec, rx_info_t::timeout_sec, rx_info_t::u, and bus::udata.
static void shutdown (listener *l) [static]
Definition at line 1383 of file listener.c.
References listener::shutdown.
Author
Generated automatically by Doxygen for kinetic-c from the source code.