.TH "listener_msg" 3 "Fri Mar 13 2015" "Version v0.12.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
listener_msg \- 
.PP
A queue message, with a command in the tagged union\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <listener_internal_types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const uint8_t \fBid\fP"
.br
.ti -1c
.RI "\fBMSG_TYPE\fP \fBtype\fP"
.br
.ti -1c
.RI "struct \fBlistener_msg\fP * \fBnext\fP"
.br
.ti -1c
.RI "int \fBpipes\fP [2]"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   struct {"
.br
.ti -1c
.RI "      \fBconnection_info\fP * \fBinfo\fP"
.br
.ti -1c
.RI "      int \fBnotify_fd\fP"
.br
.ti -1c
.RI "   } \fBadd_socket\fP"
.br
.ti -1c
.RI "   struct {"
.br
.ti -1c
.RI "      int \fBfd\fP"
.br
.ti -1c
.RI "      int \fBnotify_fd\fP"
.br
.ti -1c
.RI "   } \fBremove_socket\fP"
.br
.ti -1c
.RI "   struct {"
.br
.ti -1c
.RI "      int \fBfd\fP"
.br
.ti -1c
.RI "      int64_t \fBseq_id\fP"
.br
.ti -1c
.RI "      int16_t \fBtimeout_sec\fP"
.br
.ti -1c
.RI "      int \fBnotify_fd\fP"
.br
.ti -1c
.RI "   } \fBhold\fP"
.br
.ti -1c
.RI "   struct {"
.br
.ti -1c
.RI "      \fBboxed_msg\fP * \fBbox\fP"
.br
.ti -1c
.RI "   } \fBexpect\fP"
.br
.ti -1c
.RI "   struct {"
.br
.ti -1c
.RI "      int \fBnotify_fd\fP"
.br
.ti -1c
.RI "   } \fBshutdown\fP"
.br
.ti -1c
.RI "} \fBu\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A queue message, with a command in the tagged union\&. 


.PP
Definition at line 51 of file listener_internal_types\&.h\&.
.SH "Field Documentation"
.PP 
.SS "const uint8_t listener_msg::id"

.PP
Definition at line 52 of file listener_internal_types\&.h\&.
.SS "\fBMSG_TYPE\fP listener_msg::type"

.PP
Definition at line 53 of file listener_internal_types\&.h\&.
.SS "struct \fBlistener_msg\fP* listener_msg::next"

.PP
Definition at line 54 of file listener_internal_types\&.h\&.
.SS "int listener_msg::pipes[2]"

.PP
Definition at line 55 of file listener_internal_types\&.h\&.
.SS "\fBconnection_info\fP* listener_msg::info"

.PP
Definition at line 59 of file listener_internal_types\&.h\&.
.SS "int listener_msg::notify_fd"

.PP
Definition at line 60 of file listener_internal_types\&.h\&.
.SS "struct { \&.\&.\&. }   listener_msg::add_socket"

.SS "int listener_msg::fd"

.PP
Definition at line 63 of file listener_internal_types\&.h\&.
.SS "struct { \&.\&.\&. }   listener_msg::remove_socket"

.SS "int64_t listener_msg::seq_id"

.PP
Definition at line 68 of file listener_internal_types\&.h\&.
.SS "int16_t listener_msg::timeout_sec"

.PP
Definition at line 69 of file listener_internal_types\&.h\&.
.SS "struct { \&.\&.\&. }   listener_msg::hold"

.SS "\fBboxed_msg\fP* listener_msg::box"

.PP
Definition at line 73 of file listener_internal_types\&.h\&.
.SS "struct { \&.\&.\&. }   listener_msg::expect"

.SS "struct { \&.\&.\&. }   listener_msg::shutdown"

.SS "union { \&.\&.\&. }   listener_msg::u"


.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
