.TH "listener_cmd.c" 3 "Fri Mar 13 2015" "Version v0.12.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
listener_cmd.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <unistd\&.h>\fP
.br
\fC#include <err\&.h>\fP
.br
\fC#include <assert\&.h>\fP
.br
\fC#include 'syscall\&.h'\fP
.br
\fC#include 'listener_cmd\&.h'\fP
.br
\fC#include 'listener_cmd_internal\&.h'\fP
.br
\fC#include 'listener_task\&.h'\fP
.br
\fC#include 'listener_helper\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "static void \fBmsg_handler\fP (\fBlistener\fP *l, \fBlistener_msg\fP *pmsg)"
.br
.ti -1c
.RI "static void \fBadd_socket\fP (\fBlistener\fP *l, \fBconnection_info\fP *ci, int notify_fd)"
.br
.ti -1c
.RI "static void \fBremove_socket\fP (\fBlistener\fP *l, int fd, int notify_fd)"
.br
.ti -1c
.RI "static void \fBhold_response\fP (\fBlistener\fP *l, int fd, int64_t seq_id, int16_t timeout_sec, int notify_fd)"
.br
.ti -1c
.RI "static void \fBexpect_response\fP (\fBlistener\fP *l, \fBboxed_msg\fP *box)"
.br
.ti -1c
.RI "static void \fBshutdown\fP (\fBlistener\fP *l, int notify_fd)"
.br
.ti -1c
.RI "void \fBListenerCmd_NotifyCaller\fP (\fBlistener\fP *l, int fd)"
.br
.RI "\fINotify the listener's caller that a command has completed\&. \fP"
.ti -1c
.RI "void \fBListenerCmd_CheckIncomingMessages\fP (\fBlistener\fP *l, int *res)"
.br
.RI "\fIProcess incoming commands, if any\&. \fP"
.ti -1c
.RI "static void \fBswap\fP (\fBlistener\fP *l, int a, int b)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "static void msg_handler (\fBlistener\fP *l, \fBlistener_msg\fP *pmsg)\fC [static]\fP"

.PP
Definition at line 112 of file listener_cmd\&.c\&.
.PP
References add_socket(), listener_msg::add_socket, listener::bus, BUS_ASSERT, BUS_LOG_SNPRINTF, listener_msg::expect, expect_response(), listener_msg::hold, hold_response(), listener::is_idle, ListenerTask_ReleaseMsg(), LOG_LISTENER, MSG_ADD_SOCKET, MSG_EXPECT_RESPONSE, MSG_HOLD_RESPONSE, MSG_NONE, MSG_REMOVE_SOCKET, MSG_SHUTDOWN, remove_socket(), listener_msg::remove_socket, shutdown(), listener_msg::shutdown, listener_msg::type, listener_msg::u, and bus::udata\&.
.SS "static void add_socket (\fBlistener\fP *l, \fBconnection_info\fP *ci, intnotify_fd)\fC [static]\fP"

.PP
Definition at line 161 of file listener_cmd\&.c\&.
.PP
References listener::bus, BUS_ASSERT, BUS_LOG, connection_info::fd, listener::fd_info, listener::fds, bus_sink_cb_res_t::full_msg_buffer, listener::inactive_fds, INCOMING_MSG_PIPE, ListenerCmd_NotifyCaller(), ListenerTask_GrowReadBuf(), LOG_LISTENER, MAX_FDS, bus_sink_cb_res_t::next_read, listener::read_buf, bus::sink_cb, swap(), connection_info::to_read_size, listener::tracked_fds, bus::udata, and connection_info::udata\&.
.SS "static void remove_socket (\fBlistener\fP *l, intfd, intnotify_fd)\fC [static]\fP"

.PP
Definition at line 218 of file listener_cmd\&.c\&.
.PP
References listener::bus, BUS_LOG_SNPRINTF, listener::fds, listener::inactive_fds, INCOMING_MSG_PIPE, ListenerCmd_NotifyCaller(), LOG_LISTENER, swap(), listener::tracked_fds, and bus::udata\&.
.SS "static void hold_response (\fBlistener\fP *l, intfd, int64_tseq_id, int16_ttimeout_sec, intnotify_fd)\fC [static]\fP"

.PP
Definition at line 258 of file listener_cmd\&.c\&.
.PP
References listener::bus, BUS_ASSERT, BUS_LOG_SNPRINTF, rx_info_t::hold, rx_info_t::id, ListenerCmd_NotifyCaller(), ListenerHelper_GetFreeRXInfo(), LOG_LISTENER, RIS_HOLD, RIS_INACTIVE, rx_info_t::state, rx_info_t::timeout_sec, rx_info_t::u, and bus::udata\&.
.SS "static void expect_response (\fBlistener\fP *l, \fBboxed_msg\fP *box)\fC [static]\fP"

.PP
Definition at line 288 of file listener_cmd\&.c\&.
.PP
References listener::bus, BUS_ASSERT, BUS_LOG_SNPRINTF, BUS_SEND_RX_FAILURE, BUS_SEND_UNDEFINED, rx_info_t::expect, boxed_msg::fd, rx_info_t::hold, rx_info_t::id, ListenerHelper_FindInfoBySequenceID(), ListenerTask_AttemptDelivery(), ListenerTask_NotifyMessageFailure(), LOG_LISTENER, boxed_msg::out_seq_id, boxed_msg::result, RIS_EXPECT, RIS_HOLD, RX_ERROR_NONE, RX_ERROR_READY_FOR_DELIVERY, rx_info_t::state, bus_msg_result_t::status, boxed_msg::timeout_sec, rx_info_t::timeout_sec, rx_info_t::u, and bus::udata\&.
.SS "static void shutdown (\fBlistener\fP *l, intnotify_fd)\fC [static]\fP"

.PP
Definition at line 349 of file listener_cmd\&.c\&.
.PP
References listener::shutdown_notify_fd\&.
.SS "void ListenerCmd_NotifyCaller (\fBlistener\fP *l, intfd)"

.PP
Notify the listener's caller that a command has completed\&. 
.PP
Definition at line 42 of file listener_cmd\&.c\&.
.PP
References listener::bus, BUS_LOG_SNPRINTF, LISTENER_MSG_TAG, ListenerTask_GetBackpressure(), LOG_LISTENER, syscall_write(), and bus::udata\&.
.SS "void ListenerCmd_CheckIncomingMessages (\fBlistener\fP *l, int *res)"

.PP
Process incoming commands, if any\&. 
.PP
Definition at line 73 of file listener_cmd\&.c\&.
.PP
References listener::bus, BUS_LOG_SNPRINTF, listener::fds, INCOMING_MSG_PIPE_ID, LISTENER_CMD_BUF_SIZE, LOG_LISTENER, msg_handler(), listener::msgs, syscall_read(), and bus::udata\&.
.SS "static void swap (\fBlistener\fP *l, inta, intb)\fC [static]\fP"

.PP
Definition at line 148 of file listener_cmd\&.c\&.
.PP
References listener::fd_info, listener::fds, and INCOMING_MSG_PIPE\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
