.TH "listener_cmd_internal.h" 3 "Tue Mar 3 2015" "Version v0.12.0-beta" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
listener_cmd_internal.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'bus_types\&.h'\fP
.br
\fC#include 'bus_internal_types\&.h'\fP
.br
\fC#include 'listener_cmd\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "static void \fBmsg_handler\fP (\fBlistener\fP *l, \fBlistener_msg\fP *pmsg)"
.br
.ti -1c
.RI "static void \fBadd_socket\fP (\fBlistener\fP *l, \fBconnection_info\fP *ci, int notify_fd)"
.br
.ti -1c
.RI "static void \fBremove_socket\fP (\fBlistener\fP *l, int fd, int notify_fd)"
.br
.ti -1c
.RI "static void \fBhold_response\fP (\fBlistener\fP *l, int fd, int64_t seq_id, int16_t timeout_sec)"
.br
.ti -1c
.RI "static void \fBexpect_response\fP (\fBlistener\fP *l, \fBboxed_msg\fP *box)"
.br
.ti -1c
.RI "static void \fBshutdown\fP (\fBlistener\fP *l, int notify_fd)"
.br
.ti -1c
.RI "static \fBrx_info_t\fP * \fBget_free_rx_info\fP (struct \fBlistener\fP *l)"
.br
.ti -1c
.RI "static \fBrx_info_t\fP * \fBget_hold_rx_info\fP (\fBlistener\fP *l, int fd, int64_t seq_id)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "static void msg_handler (\fBlistener\fP *l, \fBlistener_msg\fP *pmsg)\fC [static]\fP"

.SS "static void add_socket (\fBlistener\fP *l, \fBconnection_info\fP *ci, intnotify_fd)\fC [static]\fP"

.SS "static void remove_socket (\fBlistener\fP *l, intfd, intnotify_fd)\fC [static]\fP"

.SS "static void hold_response (\fBlistener\fP *l, intfd, int64_tseq_id, int16_ttimeout_sec)\fC [static]\fP"

.SS "static void expect_response (\fBlistener\fP *l, \fBboxed_msg\fP *box)\fC [static]\fP"

.SS "static void shutdown (\fBlistener\fP *l, intnotify_fd)\fC [static]\fP"

.SS "static \fBrx_info_t\fP* get_free_rx_info (struct \fBlistener\fP *l)\fC [static]\fP"

.SS "static \fBrx_info_t\fP* get_hold_rx_info (\fBlistener\fP *l, intfd, int64_tseq_id)\fC [static]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
