.TH "listener_io.c" 3 "Fri Mar 13 2015" "Version v0.12.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
listener_io.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'listener_io\&.h'\fP
.br
\fC#include 'listener_helper\&.h'\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <assert\&.h>\fP
.br
\fC#include 'listener_task\&.h'\fP
.br
\fC#include 'syscall\&.h'\fP
.br
\fC#include 'util\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDUMP_READ\fP   0"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "static ssize_t \fBsocket_read_plain\fP (struct \fBbus\fP *b, \fBlistener\fP *l, int pfd_i, \fBconnection_info\fP *ci)"
.br
.ti -1c
.RI "static ssize_t \fBsocket_read_ssl\fP (struct \fBbus\fP *b, \fBlistener\fP *l, int pfd_i, \fBconnection_info\fP *ci)"
.br
.ti -1c
.RI "static bool \fBsink_socket_read\fP (struct \fBbus\fP *b, \fBlistener\fP *l, \fBconnection_info\fP *ci, ssize_t size)"
.br
.ti -1c
.RI "static void \fBprint_SSL_error\fP (struct \fBbus\fP *b, \fBconnection_info\fP *ci, int lvl, const char *prefix)"
.br
.ti -1c
.RI "static void \fBset_error_for_socket\fP (\fBlistener\fP *l, int id, int fd, \fBrx_error_t\fP err)"
.br
.ti -1c
.RI "static void \fBprocess_unpacked_message\fP (\fBlistener\fP *l, \fBconnection_info\fP *ci, \fBbus_unpack_cb_res_t\fP result)"
.br
.ti -1c
.RI "static void \fBmove_errored_active_sockets_to_end\fP (\fBlistener\fP *l)"
.br
.ti -1c
.RI "void \fBListenerIO_AttemptRecv\fP (\fBlistener\fP *l, int available)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DUMP_READ   0"

.PP
Definition at line 222 of file listener_io\&.c\&.
.SH "Function Documentation"
.PP 
.SS "static ssize_t socket_read_plain (struct \fBbus\fP *b, \fBlistener\fP *l, intpfd_i, \fBconnection_info\fP *ci)\fC [static]\fP"

.PP
Definition at line 116 of file listener_io\&.c\&.
.PP
References BUS_LOG_SNPRINTF, connection_info::fd, LOG_LISTENER, listener::read_buf, RX_ERROR_READ_FAILURE, set_error_for_socket(), sink_socket_read(), syscall_read(), connection_info::to_read_size, bus::udata, and Util_IsResumableIOError()\&.
.SS "static ssize_t socket_read_ssl (struct \fBbus\fP *b, \fBlistener\fP *l, intpfd_i, \fBconnection_info\fP *ci)\fC [static]\fP"

.PP
Definition at line 163 of file listener_io\&.c\&.
.PP
References BUS_ASSERT, BUS_LOG_SNPRINTF, connection_info::fd, LOG_LISTENER, print_SSL_error(), listener::read_buf, RX_ERROR_POLLHUP, RX_ERROR_READ_FAILURE, set_error_for_socket(), sink_socket_read(), connection_info::ssl, syscall_SSL_get_error(), syscall_SSL_read(), connection_info::to_read_size, bus::udata, and Util_IsResumableIOError()\&.
.SS "static bool sink_socket_read (struct \fBbus\fP *b, \fBlistener\fP *l, \fBconnection_info\fP *ci, ssize_tsize)\fC [static]\fP"

.PP
Definition at line 224 of file listener_io\&.c\&.
.PP
References BUS_ASSERT, BUS_LOG, BUS_LOG_SNPRINTF, bus_sink_cb_res_t::full_msg_buffer, ListenerTask_GrowReadBuf(), LOG_LISTENER, LOG_MEMORY, bus_sink_cb_res_t::next_read, bus_unpack_cb_res_t::ok, process_unpacked_message(), listener::read_buf, listener::read_buf_size, bus::sink_cb, bus_unpack_cb_res_t::success, connection_info::to_read_size, bus_unpack_cb_res_t::u, bus::udata, connection_info::udata, and bus::unpack_cb\&.
.SS "static void print_SSL_error (struct \fBbus\fP *b, \fBconnection_info\fP *ci, intlvl, const char *prefix)\fC [static]\fP"

.PP
Definition at line 150 of file listener_io\&.c\&.
.PP
References BUS_LOG_SNPRINTF, connection_info::fd, LOG_LISTENER, and bus::udata\&.
.SS "static void set_error_for_socket (\fBlistener\fP *l, intid, intfd, \fBrx_error_t\fPerr)\fC [static]\fP"

.PP
Definition at line 265 of file listener_io\&.c\&.
.PP
References listener::bus, BUS_ASSERT, BUS_LOG_SNPRINTF, connection_info::error, listener::error_occured, rx_info_t::expect, boxed_msg::fd, listener::fd_info, rx_info_t::hold, LOG_LISTENER, RIS_EXPECT, RIS_HOLD, RIS_INACTIVE, listener::rx_info, listener::rx_info_max_used, rx_info_t::state, rx_info_t::u, and bus::udata\&.
.SS "static void process_unpacked_message (\fBlistener\fP *l, \fBconnection_info\fP *ci, \fBbus_unpack_cb_res_t\fPresult)\fC [static]\fP"

.PP
Definition at line 334 of file listener_io\&.c\&.
.PP
References listener::bus, BUS_ASSERT, BUS_LOG_SNPRINTF, BUS_NO_SEQ_ID, bus_unpack_cb_res_t::error, bus::error_cb, rx_info_t::expect, connection_info::fd, rx_info_t::hold, rx_info_t::id, ListenerHelper_FindInfoBySequenceID(), ListenerTask_AttemptDelivery(), LOG_LISTENER, bus_unpack_cb_res_t::ok, RIS_EXPECT, RIS_HOLD, RIS_INACTIVE, RX_ERROR_READY_FOR_DELIVERY, rx_info_t::state, bus_unpack_cb_res_t::success, rx_info_t::u, bus_unpack_cb_res_t::u, bus::udata, connection_info::udata, and bus::unexpected_msg_cb\&.
.SS "static void move_errored_active_sockets_to_end (\fBlistener\fP *l)\fC [static]\fP"

.PP
Definition at line 306 of file listener_io\&.c\&.
.PP
References connection_info::error, listener::fd_info, listener::fds, listener::inactive_fds, INCOMING_MSG_PIPE, and listener::tracked_fds\&.
.SS "void ListenerIO_AttemptRecv (\fBlistener\fP *l, intavailable)"

.PP
Definition at line 44 of file listener_io\&.c\&.
.PP
References listener::bus, BUS_ASSERT, BUS_LOG, BUS_LOG_SNPRINTF, BUS_SOCKET_PLAIN, BUS_SOCKET_SSL, listener::error_occured, connection_info::fd, listener::fd_info, listener::fds, INCOMING_MSG_PIPE, LOG_LISTENER, move_errored_active_sockets_to_end(), listener::read_buf_size, RX_ERROR_POLLERR, RX_ERROR_POLLHUP, set_error_for_socket(), socket_read_plain(), socket_read_ssl(), connection_info::to_read_size, listener::tracked_fds, connection_info::type, and bus::udata\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
