.TH "listener" 3 "Fri Mar 13 2015" "Version v0.12.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
listener \- 
.PP
Receiver of responses\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <listener_internal_types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBbus\fP * \fBbus\fP"
.br
.ti -1c
.RI "int \fBshutdown_notify_fd\fP"
.br
.ti -1c
.RI "int \fBcommit_pipe\fP"
.br
.ti -1c
.RI "int \fBincoming_msg_pipe\fP"
.br
.ti -1c
.RI "bool \fBis_idle\fP"
.br
.ti -1c
.RI "\fBrx_info_t\fP \fBrx_info\fP [(1024)]"
.br
.ti -1c
.RI "\fBrx_info_t\fP * \fBrx_info_freelist\fP"
.br
.ti -1c
.RI "uint16_t \fBrx_info_in_use\fP"
.br
.ti -1c
.RI "uint16_t \fBrx_info_max_used\fP"
.br
.ti -1c
.RI "\fBlistener_msg\fP \fBmsgs\fP [(32)]"
.br
.ti -1c
.RI "\fBlistener_msg\fP * \fBmsg_freelist\fP"
.br
.ti -1c
.RI "int16_t \fBmsgs_in_use\fP"
.br
.ti -1c
.RI "int64_t \fBlargest_seq_id_seen\fP"
.br
.ti -1c
.RI "size_t \fBupstream_backpressure\fP"
.br
.ti -1c
.RI "uint16_t \fBtracked_fds\fP"
.br
.RI "\fIFDs currently tracked by listener\&. \fP"
.ti -1c
.RI "uint16_t \fBinactive_fds\fP"
.br
.RI "\fIFile descriptors that are inactive due to errors, but have not yet been explicitly removed/closed by the client\&. \fP"
.ti -1c
.RI "struct pollfd \fBfds\fP [1000+1]"
.br
.RI "\fITracked file descriptors, for polling\&. \fP"
.ti -1c
.RI "\fBconnection_info\fP * \fBfd_info\fP [1000]"
.br
.RI "\fIThe connection info, corresponding to the the file descriptors tracked in l->fds\&. \fP"
.ti -1c
.RI "bool \fBerror_occured\fP"
.br
.RI "\fIFlag indicating post-poll handling is necessary\&. \fP"
.ti -1c
.RI "size_t \fBread_buf_size\fP"
.br
.ti -1c
.RI "uint8_t * \fBread_buf\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Receiver of responses\&. 
.PP
Definition at line 136 of file listener_internal_types\&.h\&.
.SH "Field Documentation"
.PP 
.SS "struct \fBbus\fP* listener::bus"

.PP
Definition at line 137 of file listener_internal_types\&.h\&.
.SS "int listener::shutdown_notify_fd"

.PP
Definition at line 144 of file listener_internal_types\&.h\&.
.SS "int listener::commit_pipe"

.PP
Definition at line 147 of file listener_internal_types\&.h\&.
.SS "int listener::incoming_msg_pipe"

.PP
Definition at line 148 of file listener_internal_types\&.h\&.
.SS "bool listener::is_idle"

.PP
Definition at line 149 of file listener_internal_types\&.h\&.
.SS "\fBrx_info_t\fP listener::rx_info[(1024)]"

.PP
Definition at line 151 of file listener_internal_types\&.h\&.
.SS "\fBrx_info_t\fP* listener::rx_info_freelist"

.PP
Definition at line 152 of file listener_internal_types\&.h\&.
.SS "uint16_t listener::rx_info_in_use"

.PP
Definition at line 153 of file listener_internal_types\&.h\&.
.SS "uint16_t listener::rx_info_max_used"

.PP
Definition at line 154 of file listener_internal_types\&.h\&.
.SS "\fBlistener_msg\fP listener::msgs[(32)]"

.PP
Definition at line 156 of file listener_internal_types\&.h\&.
.SS "\fBlistener_msg\fP* listener::msg_freelist"

.PP
Definition at line 157 of file listener_internal_types\&.h\&.
.SS "int16_t listener::msgs_in_use"

.PP
Definition at line 158 of file listener_internal_types\&.h\&.
.SS "int64_t listener::largest_seq_id_seen"

.PP
Definition at line 159 of file listener_internal_types\&.h\&.
.SS "size_t listener::upstream_backpressure"

.PP
Definition at line 161 of file listener_internal_types\&.h\&.
.SS "uint16_t listener::tracked_fds"

.PP
FDs currently tracked by listener\&. 
.PP
Definition at line 163 of file listener_internal_types\&.h\&.
.SS "uint16_t listener::inactive_fds"

.PP
File descriptors that are inactive due to errors, but have not yet been explicitly removed/closed by the client\&. 
.PP
Definition at line 166 of file listener_internal_types\&.h\&.
.SS "struct pollfd listener::fds[1000+1]"

.PP
Tracked file descriptors, for polling\&. fds[INCOMING_MSG_PIPE_ID (0)] is the incoming_msg_pipe, so the listener's poll is awakened by incoming commands\&. fds[1] through fds[l->tracked_fds - l->inactive_fds] are the file descriptors which should be polled, and the remaining ones (if any) have been moved to the end so poll() will not touch them\&. 
.PP
Definition at line 175 of file listener_internal_types\&.h\&.
.SS "\fBconnection_info\fP* listener::fd_info[1000]"

.PP
The connection info, corresponding to the the file descriptors tracked in l->fds\&. Unlike l->fds, these are not offset by one for the incoming message pipe, i\&.e\&. l->fd_info[3] correspons to l->fds[3 + INCOMING_MSG_PIPE]\&. 
.PP
Definition at line 180 of file listener_internal_types\&.h\&.
.SS "bool listener::error_occured"

.PP
Flag indicating post-poll handling is necessary\&. 
.PP
Definition at line 182 of file listener_internal_types\&.h\&.
.SS "size_t listener::read_buf_size"

.PP
Definition at line 185 of file listener_internal_types\&.h\&.
.SS "uint8_t* listener::read_buf"

.PP
Definition at line 186 of file listener_internal_types\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
