.TH "listener_internal_types.h" 3 "Fri Mar 13 2015" "Version v0.12.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
listener_internal_types.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'bus_types\&.h'\fP
.br
\fC#include 'bus_internal_types\&.h'\fP
.br
\fC#include <poll\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBlistener_msg\fP"
.br
.RI "\fIA queue message, with a command in the tagged union\&. \fP"
.ti -1c
.RI "struct \fBrx_info_t\fP"
.br
.RI "\fIRecord in table for partially processed messages\&. \fP"
.ti -1c
.RI "struct \fBlistener\fP"
.br
.RI "\fIReceiver of responses\&. \fP"
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDEFAULT_READ_BUF_SIZE\fP   (1024L * 1024L)"
.br
.RI "\fIDefault size for the read buffer, which will grow on demand\&. \fP"
.ti -1c
.RI "#define \fBINCOMING_MSG_PIPE_ID\fP   0"
.br
.RI "\fIID of the \fCstruct pollfd\fP for the listener's incoming command pipe\&. \fP"
.ti -1c
.RI "#define \fBINCOMING_MSG_PIPE\fP   1"
.br
.RI "\fIOffset to account for the first file descriptor being the incoming message pipe\&. \fP"
.ti -1c
.RI "#define \fBLISTENER_TASK_TIMEOUT_DELAY\fP   100"
.br
.RI "\fIHow long the listener should wait for responses before becoming idle and blocking\&. \fP"
.ti -1c
.RI "#define \fBMAX_FDS\fP   1000"
.br
.RI "\fIMax number of sockets to monitor\&. \fP"
.ti -1c
.RI "#define \fBMAX_PENDING_MESSAGES\fP   (1024)"
.br
.ti -1c
.RI "#define \fBMAX_QUEUE_MESSAGES\fP   (32)"
.br
.RI "\fIMax number of unprocessed queue messages\&. \fP"
.ti -1c
.RI "#define \fBINFINITE_DELAY\fP   (-1)"
.br
.RI "\fISpecial value meaning poll should block indefinitely\&. \fP"
.ti -1c
.RI "#define \fBLISTENER_NO_FD\fP   (-1)"
.br
.RI "\fISentinel values used for \fBlistener\&.shutdown_notify_fd\fP\&. \fP"
.ti -1c
.RI "#define \fBLISTENER_SHUTDOWN_COMPLETE_FD\fP   (-2)"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef uint32_t \fBmsg_flag_t\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBMSG_TYPE\fP "
.br
.ti -1c
.RI "enum \fBrx_info_state\fP "
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DEFAULT_READ_BUF_SIZE   (1024L * 1024L)"

.PP
Default size for the read buffer, which will grow on demand\&. 
.PP
Definition at line 29 of file listener_internal_types\&.h\&.
.SS "#define INCOMING_MSG_PIPE_ID   0"

.PP
ID of the \fCstruct pollfd\fP for the listener's incoming command pipe\&. This is in the same pollfd array as the sockets being watched so that an incoming command will wake it from its blocking poll\&. 
.PP
Definition at line 35 of file listener_internal_types\&.h\&.
.SS "#define INCOMING_MSG_PIPE   1"

.PP
Offset to account for the first file descriptor being the incoming message pipe\&. 
.PP
Definition at line 39 of file listener_internal_types\&.h\&.
.SS "#define LISTENER_TASK_TIMEOUT_DELAY   100"

.PP
How long the listener should wait for responses before becoming idle and blocking\&. 
.PP
Definition at line 83 of file listener_internal_types\&.h\&.
.SS "#define MAX_FDS   1000"

.PP
Max number of sockets to monitor\&. If listening to more sockets than this, use multiple listener threads\&. 
.PP
Definition at line 118 of file listener_internal_types\&.h\&.
.SS "#define MAX_PENDING_MESSAGES   (1024)"

.PP
Definition at line 122 of file listener_internal_types\&.h\&.
.SS "#define MAX_QUEUE_MESSAGES   (32)"

.PP
Max number of unprocessed queue messages\&. 
.PP
Definition at line 125 of file listener_internal_types\&.h\&.
.SS "#define INFINITE_DELAY   (-1)"

.PP
Special value meaning poll should block indefinitely\&. 
.PP
Definition at line 129 of file listener_internal_types\&.h\&.
.SS "#define LISTENER_NO_FD   (-1)"

.PP
Sentinel values used for \fBlistener\&.shutdown_notify_fd\fP\&. 
.PP
Definition at line 132 of file listener_internal_types\&.h\&.
.SS "#define LISTENER_SHUTDOWN_COMPLETE_FD   (-2)"

.PP
Definition at line 133 of file listener_internal_types\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef uint32_t \fBmsg_flag_t\fP"

.PP
Definition at line 126 of file listener_internal_types\&.h\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBMSG_TYPE\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIMSG_NONE \fP\fP
.TP
\fB\fIMSG_ADD_SOCKET \fP\fP
.TP
\fB\fIMSG_REMOVE_SOCKET \fP\fP
.TP
\fB\fIMSG_HOLD_RESPONSE \fP\fP
.TP
\fB\fIMSG_EXPECT_RESPONSE \fP\fP
.TP
\fB\fIMSG_SHUTDOWN \fP\fP
.PP
Definition at line 41 of file listener_internal_types\&.h\&.
.SS "enum \fBrx_info_state\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIRIS_HOLD \fP\fP
.TP
\fB\fIRIS_EXPECT \fP\fP
.TP
\fB\fIRIS_INACTIVE \fP\fP
.PP
Definition at line 85 of file listener_internal_types\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
