listener_cmd.c
NAME
listener_cmd.c -
SYNOPSIS
#include <unistd.h>
#include <err.h>
#include <assert.h>
#include <poll.h>
#include 'listener_cmd.h'
#include 'listener_cmd_internal.h'
#include 'listener_task.h'
Functions
void ListenerCmd_NotifyCaller (int fd)
void ListenerCmd_CheckIncomingMessages (listener *l, int *res)
static void msg_handler (listener *l, listener_msg *pmsg)
static void add_socket (listener *l, connection_info *ci, int notify_fd)
static void remove_socket (listener *l, int fd, int notify_fd)
static void hold_response (listener *l, int fd, int64_t seq_id, int16_t timeout_sec)
static rx_info_t * get_hold_rx_info (listener *l, int fd, int64_t seq_id)
static void expect_response (listener *l, struct boxed_msg *box)
static void shutdown (listener *l, int notify_fd)
static rx_info_t * get_free_rx_info (struct listener *l)
Function Documentation
void ListenerCmd_NotifyCaller (intfd)
Definition at line 29 of file listener_cmd.c.
References LISTENER_MSG_TAG.
void ListenerCmd_CheckIncomingMessages (listener *l, int *res)
Definition at line 48 of file listener_cmd.c.
References listener::bus, BUS_LOG_SNPRINTF, listener::fds, INCOMING_MSG_PIPE_ID, LOG_LISTENER, msg_handler(), listener::msgs, and bus::udata.
static void msg_handler (listener *l, listener_msg *pmsg) [static]
Definition at line 82 of file listener_cmd.c.
References listener_msg::add_socket, add_socket(), listener::bus, BUS_ASSERT, BUS_LOG_SNPRINTF, listener_msg::expect, expect_response(), listener_msg::hold, hold_response(), listener::is_idle, ListenerTask_ReleaseMsg(), LOG_LISTENER, MSG_ADD_SOCKET, MSG_EXPECT_RESPONSE, MSG_HOLD_RESPONSE, MSG_NONE, MSG_REMOVE_SOCKET, MSG_SHUTDOWN, listener_msg::remove_socket, remove_socket(), listener_msg::shutdown, shutdown(), listener_msg::type, listener_msg::u, and bus::udata.
static void add_socket (listener *l, connection_info *ci, intnotify_fd) [static]
Definition at line 117 of file listener_cmd.c.
References listener::bus, BUS_ASSERT, BUS_LOG, connection_info::fd, listener::fd_info, listener::fds, bus_sink_cb_res_t::full_msg_buffer, INCOMING_MSG_PIPE, ListenerCmd_NotifyCaller(), ListenerTask_GrowReadBuf(), LOG_LISTENER, MAX_FDS, bus_sink_cb_res_t::next_read, listener::read_buf, bus::sink_cb, connection_info::to_read_size, listener::tracked_fds, bus::udata, and connection_info::udata.
static void remove_socket (listener *l, intfd, intnotify_fd) [static]
Definition at line 156 of file listener_cmd.c.
References listener::bus, BUS_LOG_SNPRINTF, listener::fd_info, listener::fds, INCOMING_MSG_PIPE, ListenerCmd_NotifyCaller(), LOG_LISTENER, listener::tracked_fds, and bus::udata.
static void hold_response (listener *l, intfd, int64_tseq_id, int16_ttimeout_sec) [static]
Definition at line 181 of file listener_cmd.c.
References listener::bus, BUS_ASSERT, BUS_LOG_SNPRINTF, get_free_rx_info(), rx_info_t::hold, rx_info_t::id, LOG_LISTENER, RIS_HOLD, RIS_INACTIVE, rx_info_t::state, rx_info_t::timeout_sec, rx_info_t::u, and bus::udata.
static rx_info_t* get_hold_rx_info (listener *l, intfd, int64_tseq_id) [static]
Definition at line 205 of file listener_cmd.c.
References rx_info_t::hold, RIS_HOLD, listener::rx_info, listener::rx_info_max_used, rx_info_t::state, and rx_info_t::u.
static void expect_response (listener *l, struct boxed_msg *box) [static]
Definition at line 217 of file listener_cmd.c.
References listener::bus, BUS_ASSERT, BUS_LOG_SNPRINTF, BUS_SEND_RX_TIMEOUT_EXPECT, rx_info_t::expect, boxed_msg::fd, get_free_rx_info(), get_hold_rx_info(), rx_info_t::hold, rx_info_t::id, ListenerTask_AttemptDelivery(), ListenerTask_NotifyMessageFailure(), LOG_LISTENER, LOG_MEMORY, boxed_msg::out_seq_id, RIS_EXPECT, RIS_HOLD, RIS_INACTIVE, RX_ERROR_NONE, RX_ERROR_READY_FOR_DELIVERY, rx_info_t::state, boxed_msg::timeout_sec, rx_info_t::timeout_sec, rx_info_t::u, and bus::udata.
static void shutdown (listener *l, intnotify_fd) [static]
Definition at line 283 of file listener_cmd.c.
References listener::shutdown_notify_fd.
static rx_info_t* get_free_rx_info (struct listener *l) [static]
Definition at line 287 of file listener_cmd.c.
References listener::bus, BUS_ASSERT, BUS_LOG, BUS_LOG_SNPRINTF, rx_info_t::id, LOG_LISTENER, LOG_SENDER, MAX_PENDING_MESSAGES, rx_info_t::next, RIS_INACTIVE, listener::rx_info, listener::rx_info_freelist, listener::rx_info_in_use, listener::rx_info_max_used, rx_info_t::state, and bus::udata.
Author
Generated automatically by Doxygen for kinetic-c from the source code.