.TH "listener_cmd_internal.h" 3 "Fri Mar 13 2015" "Version v0.12.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
listener_cmd_internal.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'bus_types\&.h'\fP
.br
\fC#include 'bus_internal_types\&.h'\fP
.br
\fC#include 'listener_cmd\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBLISTENER_CMD_BUF_SIZE\fP   64"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define LISTENER_CMD_BUF_SIZE   64"

.PP
Definition at line 27 of file listener_cmd_internal\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
