.TH "listener_task_internal.h" 3 "Fri Mar 13 2015" "Version v0.12.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
listener_task_internal.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'bus_types\&.h'\fP
.br
\fC#include 'bus_internal_types\&.h'\fP
.br
\fC#include 'listener_internal_types\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMSG_BP_1QTR\fP   (0\&.25)"
.br
.RI "\fICoefficients for backpressure based on certain conditions\&. \fP"
.ti -1c
.RI "#define \fBMSG_BP_HALF\fP   (0\&.5)"
.br
.ti -1c
.RI "#define \fBMSG_BP_3QTR\fP   (2\&.0)"
.br
.ti -1c
.RI "#define \fBRX_INFO_BP_1QTR\fP   (0\&.5)"
.br
.ti -1c
.RI "#define \fBRX_INFO_BP_HALF\fP   (0\&.5)"
.br
.ti -1c
.RI "#define \fBRX_INFO_BP_3QTR\fP   (2\&.0)"
.br
.ti -1c
.RI "#define \fBTHREADPOOL_BP\fP   (1\&.0)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define MSG_BP_1QTR   (0\&.25)"

.PP
Coefficients for backpressure based on certain conditions\&. 
.PP
Definition at line 28 of file listener_task_internal\&.h\&.
.SS "#define MSG_BP_HALF   (0\&.5)"

.PP
Definition at line 29 of file listener_task_internal\&.h\&.
.SS "#define MSG_BP_3QTR   (2\&.0)"

.PP
Definition at line 30 of file listener_task_internal\&.h\&.
.SS "#define RX_INFO_BP_1QTR   (0\&.5)"

.PP
Definition at line 31 of file listener_task_internal\&.h\&.
.SS "#define RX_INFO_BP_HALF   (0\&.5)"

.PP
Definition at line 32 of file listener_task_internal\&.h\&.
.SS "#define RX_INFO_BP_3QTR   (2\&.0)"

.PP
Definition at line 33 of file listener_task_internal\&.h\&.
.SS "#define THREADPOOL_BP   (1\&.0)"

.PP
Definition at line 34 of file listener_task_internal\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
