.TH "listener_task_internal.h" 3 "Tue Mar 3 2015" "Version v0.12.0-beta" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
listener_task_internal.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'bus_types\&.h'\fP
.br
\fC#include 'bus_internal_types\&.h'\fP
.br
\fC#include 'listener_internal_types\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "static void \fBtick_handler\fP (\fBlistener\fP *l)"
.br
.ti -1c
.RI "static void \fBclean_up_completed_info\fP (\fBlistener\fP *l, \fBrx_info_t\fP *info)"
.br
.ti -1c
.RI "static void \fBretry_delivery\fP (\fBlistener\fP *l, \fBrx_info_t\fP *info)"
.br
.ti -1c
.RI "static void \fBobserve_backpressure\fP (\fBlistener\fP *l, size_t backpressure)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "static void tick_handler (\fBlistener\fP *l)\fC [static]\fP"

.SS "static void clean_up_completed_info (\fBlistener\fP *l, \fBrx_info_t\fP *info)\fC [static]\fP"

.SS "static void retry_delivery (\fBlistener\fP *l, \fBrx_info_t\fP *info)\fC [static]\fP"

.SS "static void observe_backpressure (\fBlistener\fP *l, size_tbackpressure)\fC [static]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
