listener_io.h
NAME
listener_io.h -
SYNOPSIS
#include 'bus_types.h'
#include 'bus_internal_types.h'
#include 'listener_internal_types.h'
Functions
void ListenerIO_AttemptRecv (listener *l, int available)
Function Documentation
void ListenerIO_AttemptRecv (listener *l, intavailable)
Definition at line 29 of file listener_io.c.
References listener::bus, BUS_ASSERT, BUS_LOG, BUS_LOG_SNPRINTF, BUS_SOCKET_PLAIN, BUS_SOCKET_SSL, connection_info::fd, listener::fd_info, listener::fds, INCOMING_MSG_PIPE, LOG_LISTENER, listener::read_buf_size, RX_ERROR_POLLERR, RX_ERROR_POLLHUP, set_error_for_socket(), socket_read_plain(), socket_read_ssl(), connection_info::to_read_size, listener::tracked_fds, connection_info::type, and bus::udata.
Author
Generated automatically by Doxygen for kinetic-c from the source code.