listener_cmd.h
NAME
listener_cmd.h -
SYNOPSIS
#include 'listener_internal_types.h'
Functions
void ListenerCmd_NotifyCaller (listener *l, int fd)
Notify the listener's caller that a command has completed.
void ListenerCmd_CheckIncomingMessages (listener *l, int *res)
Process incoming commands, if any.
Function Documentation
void ListenerCmd_NotifyCaller (listener *l, intfd)
Notify the listener's caller that a command has completed.
Definition at line 42 of file listener_cmd.c.
References listener::bus, BUS_LOG_SNPRINTF, LISTENER_MSG_TAG, ListenerTask_GetBackpressure(), LOG_LISTENER, syscall_write(), and bus::udata.
void ListenerCmd_CheckIncomingMessages (listener *l, int *res)
Process incoming commands, if any.
Definition at line 73 of file listener_cmd.c.
References listener::bus, BUS_LOG_SNPRINTF, listener::fds, INCOMING_MSG_PIPE_ID, LISTENER_CMD_BUF_SIZE, LOG_LISTENER, msg_handler(), listener::msgs, syscall_read(), and bus::udata.
Author
Generated automatically by Doxygen for kinetic-c from the source code.