listener_io.c
NAME
listener_io.c -
SYNOPSIS
#include 'listener_io.h'
#include 'listener_io_internal.h'
#include <unistd.h>
#include <assert.h>
#include 'listener_task.h'
#include 'util.h'
Macros
#define DUMP_READ 0
Functions
void ListenerIO_AttemptRecv (listener *l, int available)
static bool socket_read_plain (struct bus *b, listener *l, int pfd_i, connection_info *ci)
static void print_SSL_error (struct bus *b, connection_info *ci, int lvl, const char *prefix)
static bool socket_read_ssl (struct bus *b, listener *l, int pfd_i, connection_info *ci)
static bool sink_socket_read (struct bus *b, listener *l, connection_info *ci, ssize_t size)
static void set_error_for_socket (listener *l, int id, int fd, rx_error_t err)
static rx_info_t * find_info_by_sequence_id (listener *l, int fd, int64_t seq_id)
static void process_unpacked_message (listener *l, connection_info *ci, bus_unpack_cb_res_t result)
Macro Definition Documentation
#define DUMP_READ 0
Definition at line 156 of file listener_io.c.
Function Documentation
void ListenerIO_AttemptRecv (listener *l, intavailable)
Definition at line 29 of file listener_io.c.
References listener::bus, BUS_ASSERT, BUS_LOG, BUS_LOG_SNPRINTF, BUS_SOCKET_PLAIN, BUS_SOCKET_SSL, connection_info::fd, listener::fd_info, listener::fds, INCOMING_MSG_PIPE, LOG_LISTENER, listener::read_buf_size, RX_ERROR_POLLERR, RX_ERROR_POLLHUP, set_error_for_socket(), socket_read_plain(), socket_read_ssl(), connection_info::to_read_size, listener::tracked_fds, connection_info::type, and bus::udata.
static bool socket_read_plain (struct bus *b, listener *l, intpfd_i, connection_info *ci) [static]
Definition at line 72 of file listener_io.c.
References BUS_LOG_SNPRINTF, connection_info::fd, LOG_LISTENER, listener::read_buf, RX_ERROR_READ_FAILURE, set_error_for_socket(), sink_socket_read(), connection_info::to_read_size, bus::udata, and util_is_resumable_io_error().
static void print_SSL_error (struct bus *b, connection_info *ci, intlvl, const char *prefix) [static]
Definition at line 95 of file listener_io.c.
References BUS_LOG_SNPRINTF, connection_info::fd, LOG_LISTENER, and bus::udata.
static bool socket_read_ssl (struct bus *b, listener *l, intpfd_i, connection_info *ci) [static]
Definition at line 103 of file listener_io.c.
References BUS_ASSERT, BUS_LOG_SNPRINTF, connection_info::fd, LOG_LISTENER, print_SSL_error(), listener::read_buf, RX_ERROR_POLLHUP, RX_ERROR_READ_FAILURE, set_error_for_socket(), sink_socket_read(), connection_info::ssl, connection_info::to_read_size, bus::udata, and util_is_resumable_io_error().
static bool sink_socket_read (struct bus *b, listener *l, connection_info *ci, ssize_tsize) [static]
Definition at line 158 of file listener_io.c.
References BUS_ASSERT, bus_lock_log(), BUS_LOG, BUS_LOG_SNPRINTF, bus_unlock_log(), bus_sink_cb_res_t::full_msg_buffer, ListenerTask_GrowReadBuf(), LOG_LISTENER, LOG_MEMORY, bus_sink_cb_res_t::next_read, bus_unpack_cb_res_t::ok, process_unpacked_message(), listener::read_buf, listener::read_buf_size, bus::sink_cb, bus_unpack_cb_res_t::success, connection_info::to_read_size, bus_unpack_cb_res_t::u, bus::udata, connection_info::udata, and bus::unpack_cb.
static void set_error_for_socket (listener *l, intid, intfd, rx_error_terr) [static]
Definition at line 201 of file listener_io.c.
References listener::bus, BUS_ASSERT, BUS_LOG_SNPRINTF, rx_info_t::expect, boxed_msg::fd, listener::fds, INCOMING_MSG_PIPE, ListenerTask_ReleaseRXInfo(), LOG_LISTENER, RIS_EXPECT, RIS_HOLD, RIS_INACTIVE, listener::rx_info, listener::rx_info_max_used, rx_info_t::state, rx_info_t::u, and bus::udata.
static rx_info_t* find_info_by_sequence_id (listener *l, intfd, int64_tseq_id) [static]
Definition at line 235 of file listener_io.c.
References listener::bus, BUS_ASSERT, BUS_LOG_SNPRINTF, rx_info_t::expect, boxed_msg::fd, rx_info_t::hold, rx_info_t::id, ListenerTask_DumpRXInfoTable(), bus::log_level, LOG_LISTENER, LOG_MEMORY, boxed_msg::out_seq_id, RIS_EXPECT, RIS_HOLD, RIS_INACTIVE, listener::rx_info, listener::rx_info_max_used, rx_info_t::state, rx_info_t::u, and bus::udata.
static void process_unpacked_message (listener *l, connection_info *ci, bus_unpack_cb_res_tresult) [static]
Definition at line 280 of file listener_io.c.
References listener::bus, BUS_ASSERT, BUS_LOG_SNPRINTF, BUS_NO_SEQ_ID, bus_unpack_cb_res_t::error, bus::error_cb, rx_info_t::expect, connection_info::fd, find_info_by_sequence_id(), rx_info_t::hold, rx_info_t::id, connection_info::largest_rd_seq_id_seen, ListenerTask_AttemptDelivery(), LOG_LISTENER, bus_unpack_cb_res_t::ok, RIS_EXPECT, RIS_HOLD, RIS_INACTIVE, RX_ERROR_READY_FOR_DELIVERY, rx_info_t::state, bus_unpack_cb_res_t::success, rx_info_t::u, bus_unpack_cb_res_t::u, bus::udata, connection_info::udata, and bus::unexpected_msg_cb.
Author
Generated automatically by Doxygen for kinetic-c from the source code.