listener.h
NAME
listener.h -
SYNOPSIS
#include 'bus_types.h'
#include 'bus_internal_types.h'
Macros
#define LISTENER_BACKPRESSURE_SHIFT 0 /* TODO */
#define LISTENER_EXPECT_BACKPRESSURE_SHIFT 7
Functions
struct listener * listener_init (struct bus *b, struct bus_config *cfg)
bool listener_add_socket (struct listener *l, connection_info *ci, int *notify_fd)
bool listener_remove_socket (struct listener *l, int fd, int *notify_fd)
bool listener_hold_response (struct listener *l, int fd, int64_t seq_id, int16_t timeout_sec)
bool listener_expect_response (struct listener *l, boxed_msg *box, uint16_t *backpressure)
bool listener_shutdown (struct listener *l, int *notify_fd)
void listener_free (struct listener *l)
Macro Definition Documentation
#define LISTENER_BACKPRESSURE_SHIFT 0 /* TODO */
Definition at line 28 of file listener.h.
#define LISTENER_EXPECT_BACKPRESSURE_SHIFT 7
Definition at line 32 of file listener.h.
Function Documentation
struct listener* listener_init (struct bus *b, struct bus_config *cfg)
Definition at line 39 of file listener.c.
References listener::bus, BUS_LOG, listener::commit_pipe, listener::fds, listener_msg::id, rx_info_t::id, listener::incoming_msg_pipe, INCOMING_MSG_PIPE_ID, LISTENER_NO_FD, LOG_LISTENER, MAX_PENDING_MESSAGES, MAX_QUEUE_MESSAGES, listener::msg_freelist, listener::msgs, listener_msg::next, rx_info_t::next, listener_msg::pipes, RIS_INACTIVE, listener::rx_info, listener::rx_info_freelist, listener::rx_info_max_used, listener::shutdown_notify_fd, rx_info_t::state, and bus::udata.
bool listener_add_socket (struct listener *l, connection_info *ci, int *notify_fd)
Definition at line 99 of file listener.c.
References listener_msg::add_socket, get_free_msg(), MSG_ADD_SOCKET, listener_msg::pipes, push_message(), listener_msg::type, and listener_msg::u.
bool listener_remove_socket (struct listener *l, intfd, int *notify_fd)
Definition at line 110 of file listener.c.
References get_free_msg(), MSG_REMOVE_SOCKET, listener_msg::pipes, push_message(), listener_msg::remove_socket, listener_msg::type, and listener_msg::u.
bool listener_hold_response (struct listener *l, intfd, int64_tseq_id, int16_ttimeout_sec)
Definition at line 120 of file listener.c.
References listener::bus, BUS_LOG, BUS_LOG_SNPRINTF, get_free_msg(), listener_msg::hold, LOG_LISTENER, LOG_MEMORY, MSG_HOLD_RESPONSE, push_message(), listener_msg::type, listener_msg::u, and bus::udata.
bool listener_expect_response (struct listener *l, boxed_msg *box, uint16_t *backpressure)
Definition at line 147 of file listener.c.
References listener::bus, BUS_LOG_SNPRINTF, listener_msg::expect, get_free_msg(), ListenerTask_GetBackpressure(), LOG_MEMORY, MSG_EXPECT_RESPONSE, boxed_msg::out_seq_id, push_message(), listener_msg::type, listener_msg::u, and bus::udata.
bool listener_shutdown (struct listener *l, int *notify_fd)
Definition at line 173 of file listener.c.
References get_free_msg(), MSG_SHUTDOWN, listener_msg::pipes, push_message(), listener_msg::shutdown, listener_msg::type, and listener_msg::u.
void listener_free (struct listener *l)
Definition at line 182 of file listener.c.
References listener_msg::add_socket, listener::bus, BUS_ASSERT, BUS_LOG_SNPRINTF, listener::commit_pipe, listener_msg::expect, rx_info_t::expect, listener::incoming_msg_pipe, LISTENER_SHUTDOWN_COMPLETE_FD, ListenerCmd_NotifyCaller(), LOG_LISTENER, MAX_PENDING_MESSAGES, MAX_QUEUE_MESSAGES, MSG_ADD_SOCKET, MSG_EXPECT_RESPONSE, MSG_REMOVE_SOCKET, listener::msgs, listener_msg::pipes, listener::read_buf, listener_msg::remove_socket, RIS_EXPECT, RIS_HOLD, RIS_INACTIVE, listener::rx_info, listener::shutdown_notify_fd, rx_info_t::state, listener_msg::type, listener_msg::u, rx_info_t::u, and bus::udata.
Author
Generated automatically by Doxygen for kinetic-c from the source code.