.TH "main.c" 3 "Fri Aug 8 2014" "Version v0.4.3" "protobuf-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'kinetic\&.h'\fP
.br
\fC#include 'noop\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (intargc, char **argv)"

.PP
Definition at line 27 of file main\&.c\&.
.PP
References HOST_NAME_MAX, KINETIC_PORT, and NoOp()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for protobuf-c from the source code\&.
