main.c
NAME
main.c -
SYNOPSIS
#include 'kinetic_client.h'
#include 'kinetic_admin_client.h'
#include <stdlib.h>
#include <stdio.h>
#include <getopt.h>
Macros
#define OPT_MIN OPT_NOOP
Enumerations
enum OptionID
Functions
static int ParseOptions (const int argc, char **const argv, struct UtilConfig *cfg)
static KineticStatus ExecuteOperation (struct UtilConfig *cfg)
static void ConfigureEntry (struct UtilConfig *cfg, const char *key, const char *tag, const char *version, KineticAlgorithm algorithm, bool force, const char *value)
static void PrintLogInfo (KineticLogInfo_Type type, KineticLogInfo *info)
static const char * GetOptString (OptionID opt_id)
void PrintUsage (const char *exec)
int main (int argc, char **argv)
static void PrintEntry (KineticEntry *entry)
Macro Definition Documentation
#define OPT_MIN OPT_NOOP
Definition at line 98 of file main.c.
Enumeration Type Documentation
enum OptionID
Enumerator
OPT_NONE
OPT_HELP
OPT_LOGLEVEL
OPT_HOST
OPT_PORT
OPT_TLSPORT
OPT_IDENTITY
OPT_KEY
OPT_VALUE
OPT_CLUSTERVERSION
OPT_FILE
OPT_HMACKEY
OPT_NEWCLUSTERVERSION
OPT_PIN
OPT_NEWPIN
OPT_LOGTYPE
OPT_DEVICELOGNAME
OPT_NOOP
OPT_PUT
OPT_GET
OPT_DELETE
OPT_GETNEXT
OPT_GETPREVIOUS
OPT_GETLOG
OPT_GETDEVICESPECIFICLOG
OPT_SETERASEPIN
OPT_INSTANTERASE
OPT_SECUREERASE
OPT_SETLOCKPIN
OPT_LOCKDEVICE
OPT_UNLOCKDEVICE
OPT_SETCLUSTERVERSION
OPT_SETACL
OPT_UPDATEFIRMWARE
OPT_MAX
Definition at line 27 of file main.c.
Function Documentation
int ParseOptions (const intargc, char **constargv, struct UtilConfig *cfg) [static]
Definition at line 605 of file main.c.
References ByteArray_Create(), ConfigureEntry(), HOST_NAME_MAX, KINETIC_ALGORITHM_SHA1, KINETIC_DEVICE_INFO_TYPE_CAPACITIES, KINETIC_DEVICE_INFO_TYPE_CONFIGURATION, KINETIC_DEVICE_INFO_TYPE_LIMITS, KINETIC_DEVICE_INFO_TYPE_MESSAGES, KINETIC_DEVICE_INFO_TYPE_STATISTICS, KINETIC_DEVICE_INFO_TYPE_TEMPERATURES, KINETIC_DEVICE_INFO_TYPE_UTILIZATIONS, KINETIC_MAX_KEY_LEN, KINETIC_PORT, KINETIC_TLS_PORT, OPT_CLUSTERVERSION, OPT_DELETE, OPT_DEVICELOGNAME, OPT_FILE, OPT_GET, OPT_GETDEVICESPECIFICLOG, OPT_GETLOG, OPT_GETNEXT, OPT_GETPREVIOUS, OPT_HELP, OPT_HMACKEY, OPT_HOST, OPT_IDENTITY, OPT_INSTANTERASE, OPT_KEY, OPT_LOCKDEVICE, OPT_LOGLEVEL, OPT_LOGTYPE, OPT_NEWCLUSTERVERSION, OPT_NEWPIN, OPT_NOOP, OPT_PIN, OPT_PORT, OPT_PUT, OPT_SECUREERASE, OPT_SETACL, OPT_SETCLUSTERVERSION, OPT_SETERASEPIN, OPT_SETLOCKPIN, OPT_TLSPORT, OPT_UNLOCKDEVICE, OPT_UPDATEFIRMWARE, OPT_VALUE, and PrintUsage().
KineticStatus ExecuteOperation (struct UtilConfig *cfg) [static]
Definition at line 413 of file main.c.
References ByteArray_Create(), ByteArray::data, KineticLogInfo::device, GetOptString(), Kinetic_GetStatusDescription(), KINETIC_STATUS_INVALID, KINETIC_STATUS_NOT_FOUND, KINETIC_STATUS_SUCCESS, KineticAdminClient_GetDeviceSpecificLog(), KineticAdminClient_GetLog(), KineticAdminClient_InstantErase(), KineticAdminClient_LockDevice(), KineticAdminClient_SecureErase(), KineticAdminClient_SetACL(), KineticAdminClient_SetClusterVersion(), KineticAdminClient_SetErasePin(), KineticAdminClient_SetLockPin(), KineticAdminClient_UnlockDevice(), KineticAdminClient_UpdateFirmware(), KineticClient_Delete(), KineticClient_Get(), KineticClient_GetNext(), KineticClient_GetPrevious(), KineticClient_NoOp(), KineticClient_Put(), ByteArray::len, KineticLogInfo_Device::name, OPT_DELETE, OPT_GET, OPT_GETDEVICESPECIFICLOG, OPT_GETLOG, OPT_GETNEXT, OPT_GETPREVIOUS, OPT_INSTANTERASE, OPT_LOCKDEVICE, OPT_NOOP, OPT_PUT, OPT_SECUREERASE, OPT_SETACL, OPT_SETCLUSTERVERSION, OPT_SETERASEPIN, OPT_SETLOCKPIN, OPT_UNLOCKDEVICE, OPT_UPDATEFIRMWARE, PrintEntry(), and PrintLogInfo().
void ConfigureEntry (struct UtilConfig *cfg, const char *key, const char *tag, const char *version, KineticAlgorithmalgorithm, boolforce, const char *value) [static]
Definition at line 588 of file main.c.
References ByteBuffer_Create(), and ByteBuffer_CreateAndAppendCString().
static void PrintLogInfo (KineticLogInfo_Typetype, KineticLogInfo *info) [static]
Definition at line 234 of file main.c.
References KineticLogInfo_Statistics::bytes, KineticLogInfo::capacity, KineticLogInfo_Configuration::compilationDate, KineticLogInfo::configuration, KineticLogInfo_Statistics::count, KineticLogInfo_Temperature::current, ByteArray::data, KineticLogInfo_Configuration::interfaces, KineticLogInfo_Interface::ipv4Address, KineticLogInfo_Interface::ipv6Address, KINETIC_DEVICE_INFO_TYPE_CAPACITIES, KINETIC_DEVICE_INFO_TYPE_CONFIGURATION, KINETIC_DEVICE_INFO_TYPE_LIMITS, KINETIC_DEVICE_INFO_TYPE_MESSAGES, KINETIC_DEVICE_INFO_TYPE_STATISTICS, KINETIC_DEVICE_INFO_TYPE_TEMPERATURES, KINETIC_DEVICE_INFO_TYPE_UTILIZATIONS, KineticMessageType_GetName(), ByteArray::len, KineticLogInfo::limits, KineticLogInfo_Interface::MAC, KineticLogInfo_Limits::maxConnections, KineticLogInfo_Limits::maxIdentityCount, KineticLogInfo_Temperature::maximum, KineticLogInfo_Limits::maxKeyRangeCount, KineticLogInfo_Limits::maxKeySize, KineticLogInfo_Limits::maxMessageSize, KineticLogInfo_Limits::maxOutstandingReadRequests, KineticLogInfo_Limits::maxOutstandingWriteRequests, KineticLogInfo_Limits::maxPinSize, KineticLogInfo_Limits::maxTagSize, KineticLogInfo_Limits::maxValueSize, KineticLogInfo_Limits::maxVersionSize, KineticLogInfo::messages, KineticLogInfo_Statistics::messageType, KineticLogInfo_Temperature::minimum, KineticLogInfo_Configuration::model, KineticLogInfo_Utilization::name, KineticLogInfo_Temperature::name, KineticLogInfo_Interface::name, KineticLogInfo_Capacity::nominalCapacityInBytes, KineticLogInfo_Configuration::numInterfaces, KineticLogInfo::numStatistics, KineticLogInfo::numTemperatures, KineticLogInfo::numUtilizations, KineticLogInfo_Configuration::port, KineticLogInfo_Capacity::portionFull, KineticLogInfo_Configuration::protocolCompilationDate, KineticLogInfo_Configuration::protocolSourceHash, KineticLogInfo_Configuration::protocolVersion, KineticLogInfo_Configuration::serialNumber, KineticLogInfo_Configuration::sourceHash, KineticLogInfo::statistics, KineticLogInfo_Temperature::target, KineticLogInfo::temperatures, KineticLogInfo_Configuration::tlsPort, KineticLogInfo::utilizations, KineticLogInfo_Utilization::value, KineticLogInfo_Configuration::vendor, KineticLogInfo_Configuration::version, and KineticLogInfo_Configuration::worldWideName.
static const char * GetOptString (OptionIDopt_id) [static]
Definition at line 334 of file main.c.
References OPT_CLUSTERVERSION, OPT_DELETE, OPT_FILE, OPT_GET, OPT_GETDEVICESPECIFICLOG, OPT_GETLOG, OPT_GETNEXT, OPT_GETPREVIOUS, OPT_HELP, OPT_HMACKEY, OPT_HOST, OPT_IDENTITY, OPT_INSTANTERASE, OPT_KEY, OPT_LOCKDEVICE, OPT_LOGLEVEL, OPT_LOGTYPE, OPT_NEWCLUSTERVERSION, OPT_NEWPIN, OPT_NOOP, OPT_PIN, OPT_PORT, OPT_PUT, OPT_SECUREERASE, OPT_SETACL, OPT_SETCLUSTERVERSION, OPT_SETERASEPIN, OPT_SETLOCKPIN, OPT_TLSPORT, OPT_UNLOCKDEVICE, OPT_UPDATEFIRMWARE, and OPT_VALUE.
void PrintUsage (const char *exec)
Definition at line 120 of file main.c.
int main (intargc, char **argv)
Definition at line 167 of file main.c.
References ExecuteOperation(), Kinetic_GetStatusDescription(), KINETIC_STATUS_SUCCESS, KineticClient_CreateSession(), KineticClient_Init(), KineticClientConfig::logFile, OPT_NONE, ParseOptions(), and PrintUsage().
static void PrintEntry (KineticEntry *entry) [static]
Definition at line 221 of file main.c.
References ByteBuffer::array, ByteBuffer::bytesUsed, ByteArray::data, KineticEntry::key, and KineticEntry::value.
Author
Generated automatically by Doxygen for kinetic-c from the source code.