.TH "main.c" 3 "Thu Aug 7 2014" "Version v0.4.0" "protobuf-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'kinetic\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (intargc, char **argv)"

.PP
Definition at line 26 of file main\&.c\&.
.PP
References KINETIC_PROTO_COMMAND_INIT, KINETIC_PROTO_HEADER_INIT, KINETIC_PROTO_INIT, KineticProto_command_init(), KineticProto_free_unpacked(), KineticProto_get_packed_size(), KineticProto_header_init(), KineticProto_init(), KineticProto_pack(), KineticProto_pack_to_buffer(), and KineticProto_unpack()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for protobuf-c from the source code\&.
