.TH "noop.h" 3 "Fri Aug 8 2014" "Version v0.4.3" "protobuf-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
noop.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'kinetic\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBNoOp\fP (const char *host, int port, int64_t clusterVersion, int64_t identity, const char *key)"
.br
.RI "\fIConnects to the specified Kinetic host/port and executes a NoOp (ping) operation\&. \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "int NoOp (const char *host, intport, int64_tclusterVersion, int64_tidentity, const char *key)"

.PP
Connects to the specified Kinetic host/port and executes a NoOp (ping) operation\&. 
.PP
\fBParameters:\fP
.RS 4
\fIhost\fP Host name or IP address to connect to 
.br
\fIport\fP Port to establish socket connection on 
.br
\fIclusterVersion\fP Cluster version to use for the operation 
.br
\fIidentity\fP Identity to use for the operation (Must have ACL setup on Kinetic Device) 
.br
\fIkey\fP Shared secret key used for the identity for HMAC calculation
.RE
.PP
\fBReturns:\fP
.RS 4
Returns true if operation succeeded, false otherwise 
.RE
.PP

.PP
Definition at line 23 of file noop\&.c\&.
.PP
References KINETIC_PROTO_STATUS_STATUS_CODE_SUCCESS, KineticApi_ConfigureExchange(), KineticApi_Connect(), KineticApi_CreateOperation(), KineticApi_Init(), KineticApi_NoOp(), KineticPDU::proto, and KineticConnection::socketDescriptor\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for protobuf-c from the source code\&.
