noop.h
NAME
noop.h -
SYNOPSIS
#include 'kinetic.h'
Functions
int NoOp (const char *host, int port, int64_t clusterVersion, int64_t identity, const char *key)
Connects to the specified Kinetic host/port and executes a NoOp (ping) operation.
Function Documentation
int NoOp (const char *host, intport, int64_tclusterVersion, int64_tidentity, const char *key)
Connects to the specified Kinetic host/port and executes a NoOp (ping) operation.
Parameters:
host Host name or IP address to connect to
port Port to establish socket connection on
clusterVersion Cluster version to use for the operation
identity Identity to use for the operation (Must have ACL setup on Kinetic Device)
key Shared secret key used for the identity for HMAC calculation
Returns:
Returns true if operation succeeded, false otherwise
Definition at line 23 of file noop.c.
References KINETIC_PROTO_STATUS_STATUS_CODE_SUCCESS, KineticApi_ConfigureExchange(), KineticApi_Connect(), KineticApi_CreateOperation(), KineticApi_Init(), KineticApi_NoOp(), KineticPDU::proto, and KineticConnection::socketDescriptor.
Author
Generated automatically by Doxygen for protobuf-c from the source code.