put_nonblocking.c
NAME
put_nonblocking.c -
SYNOPSIS
#include 'kinetic_client.h'
#include 'kinetic_types.h'
#include 'kinetic_semaphore.h'
#include <stdlib.h>
#include <openssl/sha.h>
#include <pthread.h>
Functions
static void put_finished (KineticCompletionData *kinetic_data, void *clientData)
int main (int argc, char **argv)
Function Documentation
static void put_finished (KineticCompletionData *kinetic_data, void *clientData) [static]
Definition at line 129 of file put_nonblocking.c.
References KineticSemaphore_Signal(), and KineticCompletionData::status.
int main (intargc, char **argv)
Definition at line 34 of file put_nonblocking.c.
References ByteBuffer::array, ByteArray_CreateWithCString(), ByteBuffer_Append(), ByteBuffer_Free(), ByteBuffer_Malloc(), ByteBuffer_MallocAndAppend(), ByteBuffer::bytesUsed, ByteArray::data, KineticSessionConfig::host, KineticEntry::key, KINETIC_ALGORITHM_SHA1, Kinetic_GetStatusDescription(), KINETIC_PORT, KINETIC_STATUS_INVALID, KINETIC_STATUS_SUCCESS, KINETIC_SYNCHRONIZATION_WRITETHROUGH, KineticClient_CreateSession(), KineticClient_DestroySession(), KineticClient_Init(), KineticClient_Put(), KineticClient_Shutdown(), KineticSemaphore_Create(), KineticSemaphore_WaitForSignalAndDestroy(), KineticClientConfig::logFile, and put_finished().
Author
Generated automatically by Doxygen for kinetic-c from the source code.