.TH "rx_info_t" 3 "Fri Mar 13 2015" "Version v0.12.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rx_info_t \- 
.PP
Record in table for partially processed messages\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <listener_internal_types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const uint16_t \fBid\fP"
.br
.ti -1c
.RI "struct \fBrx_info_t\fP * \fBnext\fP"
.br
.ti -1c
.RI "\fBrx_info_state\fP \fBstate\fP"
.br
.ti -1c
.RI "time_t \fBtimeout_sec\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   struct {"
.br
.ti -1c
.RI "      int \fBfd\fP"
.br
.ti -1c
.RI "      int64_t \fBseq_id\fP"
.br
.ti -1c
.RI "      bool \fBhas_result\fP"
.br
.ti -1c
.RI "      \fBbus_unpack_cb_res_t\fP \fBresult\fP"
.br
.ti -1c
.RI "      \fBrx_error_t\fP \fBerror\fP"
.br
.ti -1c
.RI "   } \fBhold\fP"
.br
.ti -1c
.RI "   struct {"
.br
.ti -1c
.RI "      \fBboxed_msg\fP * \fBbox\fP"
.br
.ti -1c
.RI "      \fBrx_error_t\fP \fBerror\fP"
.br
.ti -1c
.RI "      bool \fBhas_result\fP"
.br
.ti -1c
.RI "      \fBbus_unpack_cb_res_t\fP \fBresult\fP"
.br
.ti -1c
.RI "   } \fBexpect\fP"
.br
.ti -1c
.RI "} \fBu\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Record in table for partially processed messages\&. 


.PP
Definition at line 92 of file listener_internal_types\&.h\&.
.SH "Field Documentation"
.PP 
.SS "const uint16_t rx_info_t::id"

.PP
Definition at line 93 of file listener_internal_types\&.h\&.
.SS "struct \fBrx_info_t\fP* rx_info_t::next"

.PP
Definition at line 94 of file listener_internal_types\&.h\&.
.SS "\fBrx_info_state\fP rx_info_t::state"

.PP
Definition at line 96 of file listener_internal_types\&.h\&.
.SS "time_t rx_info_t::timeout_sec"

.PP
Definition at line 97 of file listener_internal_types\&.h\&.
.SS "int rx_info_t::fd"

.PP
Definition at line 101 of file listener_internal_types\&.h\&.
.SS "int64_t rx_info_t::seq_id"

.PP
Definition at line 102 of file listener_internal_types\&.h\&.
.SS "bool rx_info_t::has_result"

.PP
Definition at line 103 of file listener_internal_types\&.h\&.
.SS "\fBbus_unpack_cb_res_t\fP rx_info_t::result"

.PP
Definition at line 104 of file listener_internal_types\&.h\&.
.SS "\fBrx_error_t\fP rx_info_t::error"

.PP
Definition at line 105 of file listener_internal_types\&.h\&.
.SS "struct { \&.\&.\&. }   rx_info_t::hold"

.SS "\fBboxed_msg\fP* rx_info_t::box"

.PP
Definition at line 108 of file listener_internal_types\&.h\&.
.SS "struct { \&.\&.\&. }   rx_info_t::expect"

.SS "union { \&.\&.\&. }   rx_info_t::u"


.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
