.TH "send_internal.h" 3 "Fri Mar 13 2015" "Version v0.12.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
send_internal.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'send\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSEND_NOTIFY_LISTENER_RETRIES\fP   10"
.br
.ti -1c
.RI "#define \fBSEND_NOTIFY_LISTENER_RETRY_DELAY\fP   5"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define SEND_NOTIFY_LISTENER_RETRIES   10"

.PP
Definition at line 25 of file send_internal\&.h\&.
.SS "#define SEND_NOTIFY_LISTENER_RETRY_DELAY   5"

.PP
Definition at line 26 of file send_internal\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
