sender.h
NAME
sender.h -
SYNOPSIS
#include 'bus_types.h'
#include 'bus_internal_types.h'
Functions
struct sender * sender_init (struct bus *b, struct bus_config *cfg)
bool sender_register_socket (struct sender *s, int fd, SSL *ssl)
bool sender_remove_socket (struct sender *s, int fd)
bool sender_send_request (struct sender *s, boxed_msg *box)
bool sender_shutdown (struct sender *s)
void sender_free (struct sender *s)
Function Documentation
struct sender* sender_init (struct bus *b, struct bus_config *cfg)
Definition at line 41 of file sender.c.
References sender::bus, BUS_LOG, BUS_LOG_SNPRINTF, sender::commit_pipe, sender::fd_hash_table, sender::fds, HASH_TABLE_SIZE2, tx_info_t::id, sender::incoming_command_pipe, LOG_SENDER, MAX_CONCURRENT_SENDS, sender::pipes, SENDER_FD_NOT_IN_USE, tx_info_t::state, TIS_UNDEF, sender::tx_info, bus::udata, and yacht_init().
bool sender_register_socket (struct sender *s, intfd, SSL *ssl)
Definition at line 105 of file sender.c.
References tx_info_t::add_socket, sender::bus, BUS_LOG_SNPRINTF, commit_event_and_block(), get_free_tx_info(), LOG_SENDER, release_tx_info(), tx_info_t::state, TIS_ADD_SOCKET, TX_ERROR_NONE, tx_info_t::u, and bus::udata.
bool sender_remove_socket (struct sender *s, intfd)
Definition at line 122 of file sender.c.
References commit_event_and_block(), get_free_tx_info(), release_tx_info(), tx_info_t::rm_socket, tx_info_t::state, TIS_RM_SOCKET, TX_ERROR_NONE, and tx_info_t::u.
bool sender_send_request (struct sender *s, boxed_msg *box)
Definition at line 133 of file sender.c.
References sender::bus, BUS_LOG, BUS_LOG_SNPRINTF, commit_event_and_block(), tx_info_t::enqueue, boxed_msg::fd, get_free_tx_info(), LOG_SENDER, release_tx_info(), tx_info_t::state, boxed_msg::timeout_sec, TIS_REQUEST_ENQUEUE, boxed_msg::tv_send_start, TX_ERROR_NONE, tx_info_t::u, and bus::udata.
bool sender_shutdown (struct sender *s)
Definition at line 158 of file sender.c.
References sender::bus, BUS_LOG_SNPRINTF, commit_event_and_block(), sender::fd_hash_table, get_free_tx_info(), tx_info_t::id, LOG_SENDER, release_tx_info(), tx_info_t::state, TIS_SHUTDOWN, TX_ERROR_NONE, and bus::udata.
void sender_free (struct sender *s)
Definition at line 174 of file sender.c.
References cleanup().
Author
Generated automatically by Doxygen for kinetic-c from the source code.