send_helper.h
NAME
send_helper.h -
SYNOPSIS
#include 'bus_types.h'
#include 'bus_internal_types.h'
Enumerations
enum SendHelper_HandleWrite_res
Functions
SendHelper_HandleWrite_res SendHelper_HandleWrite (bus *b, boxed_msg *box)
Enumeration Type Documentation
enum SendHelper_HandleWrite_res
Enumerator
SHHW_OK
SHHW_DONE
SHHW_ERROR
Definition at line 26 of file send_helper.h.
Function Documentation
SendHelper_HandleWrite_res SendHelper_HandleWrite (bus *b, boxed_msg *box)
Definition at line 39 of file send_helper.c.
References BUS_LOG_SNPRINTF, BUS_NO_SSL, BUS_SEND_TIMESTAMP_ERROR, BUS_SEND_TX_FAILURE, BUS_SEND_TX_TIMEOUT_NOTIFYING_LISTENER, enqueue_EXPECT_message_to_listener(), boxed_msg::fd, LOG_SENDER, boxed_msg::out_msg_size, boxed_msg::out_sent_size, boxed_msg::out_seq_id, Send_HandleFailure(), SHHW_DONE, SHHW_ERROR, SHHW_OK, boxed_msg::ssl, boxed_msg::tv_send_done, bus::udata, Util_Timestamp(), write_plain(), and write_ssl().
Author
Generated automatically by Doxygen for kinetic-c from the source code.