sender.c
NAME
sender.c -
SYNOPSIS
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
#include <sys/time.h>
#include <assert.h>
#include <poll.h>
#include 'bus.h'
#include 'bus_types.h'
#include 'bus_internal_types.h'
#include 'listener.h'
#include 'util.h'
#include 'atomic.h'
#include 'yacht.h'
#include 'sender_internal.h'
Macros
#define CMD_FD (1)
#define TIMEOUT_DELAY 100
Functions
struct sender * sender_init (struct bus *b, struct bus_config *cfg)
bool sender_register_socket (struct sender *s, int fd, SSL *ssl)
bool sender_remove_socket (struct sender *s, int fd)
bool sender_send_request (struct sender *s, boxed_msg *box)
bool sender_shutdown (struct sender *s)
void sender_free (struct sender *s)
static tx_info_t * get_free_tx_info (struct sender *s)
static void release_tx_info (struct sender *s, tx_info_t *info)
static int get_notify_pipe (struct sender *s, int id)
static bool write_commit (struct sender *s, tx_info_t *info)
static tx_error_t commit_event_and_block (struct sender *s, tx_info_t *info)
void * sender_mainloop (void *arg)
static void free_fd_info_cb (void *value, void *udata)
static void cleanup (sender *s)
static bool register_socket_info (sender *s, int fd, SSL *ssl)
static void increment_fd_refcount (sender *s, fd_info *fdi)
static void decrement_fd_refcount (sender *s, fd_info *fdi)
static bool release_socket_info (sender *s, int fd)
static void handle_command (sender *s, int id)
static void enqueue_write (struct sender *s, tx_info_t *info)
static bool check_incoming_commands (struct sender *s)
static tx_info_t * get_info_to_write_for_socket (sender *s, int fd)
static void set_error_for_socket (sender *s, int fd, tx_error_t error)
static void attempt_write (sender *s, int available)
static ssize_t socket_write_plain (sender *s, tx_info_t *info)
static ssize_t socket_write_ssl (sender *s, tx_info_t *info, SSL *ssl)
static void update_sent (struct bus *b, sender *s, tx_info_t *info, ssize_t sent)
static void notify_caller (sender *s, tx_info_t *info, bool success)
static void tick_handler (sender *s)
static void tick_timeout (sender *s, tx_info_t *info)
static void attempt_to_enqueue_sending_request_message_to_listener (sender *s, int fd, int64_t seq_id, int16_t timeout_sec)
static void attempt_to_enqueue_request_sent_message_to_listener (sender *s, tx_info_t *info)
static void notify_message_failure (sender *s, tx_info_t *info, bus_send_status_t status)
Macro Definition Documentation
#define CMD_FD (1)
Definition at line 39 of file sender.c.
#define TIMEOUT_DELAY 100
Definition at line 330 of file sender.c.
Function Documentation
struct sender* sender_init (struct bus *b, struct bus_config *cfg)
Definition at line 41 of file sender.c.
References sender::bus, BUS_LOG, BUS_LOG_SNPRINTF, sender::commit_pipe, sender::fd_hash_table, sender::fds, HASH_TABLE_SIZE2, tx_info_t::id, sender::incoming_command_pipe, LOG_SENDER, MAX_CONCURRENT_SENDS, sender::pipes, SENDER_FD_NOT_IN_USE, tx_info_t::state, TIS_UNDEF, sender::tx_info, bus::udata, and yacht_init().
bool sender_register_socket (struct sender *s, intfd, SSL *ssl)
Definition at line 105 of file sender.c.
References tx_info_t::add_socket, sender::bus, BUS_LOG_SNPRINTF, commit_event_and_block(), get_free_tx_info(), LOG_SENDER, release_tx_info(), tx_info_t::state, TIS_ADD_SOCKET, TX_ERROR_NONE, tx_info_t::u, and bus::udata.
bool sender_remove_socket (struct sender *s, intfd)
Definition at line 122 of file sender.c.
References commit_event_and_block(), get_free_tx_info(), release_tx_info(), tx_info_t::rm_socket, tx_info_t::state, TIS_RM_SOCKET, TX_ERROR_NONE, and tx_info_t::u.
bool sender_send_request (struct sender *s, boxed_msg *box)
Definition at line 133 of file sender.c.
References sender::bus, BUS_LOG, BUS_LOG_SNPRINTF, commit_event_and_block(), tx_info_t::enqueue, boxed_msg::fd, get_free_tx_info(), LOG_SENDER, release_tx_info(), tx_info_t::state, boxed_msg::timeout_sec, TIS_REQUEST_ENQUEUE, boxed_msg::tv_send_start, TX_ERROR_NONE, tx_info_t::u, and bus::udata.
bool sender_shutdown (struct sender *s)
Definition at line 158 of file sender.c.
References sender::bus, BUS_LOG_SNPRINTF, commit_event_and_block(), sender::fd_hash_table, get_free_tx_info(), tx_info_t::id, LOG_SENDER, release_tx_info(), tx_info_t::state, TIS_SHUTDOWN, TX_ERROR_NONE, and bus::udata.
void sender_free (struct sender *s)
Definition at line 174 of file sender.c.
References cleanup().
static tx_info_t* get_free_tx_info (struct sender *s) [static]
Definition at line 181 of file sender.c.
References ATOMIC_BOOL_COMPARE_AND_SWAP, sender::bus, BUS_LOG, BUS_LOG_SNPRINTF, tx_info_t::done_pipe, get_notify_pipe(), tx_info_t::id, LOG_SENDER, MAX_CONCURRENT_SENDS, tx_info_t::state, TIS_UNDEF, sender::tx_flags, sender::tx_info, and bus::udata.
static void release_tx_info (struct sender *s, tx_info_t *info) [static]
Definition at line 207 of file sender.c.
References ATOMIC_BOOL_COMPARE_AND_SWAP, sender::bus, BUS_LOG_SNPRINTF, tx_info_t::id, LOG_SENDER, MAX_CONCURRENT_SENDS, tx_info_t::state, TIS_UNDEF, sender::tx_flags, and bus::udata.
static int get_notify_pipe (struct sender *s, intid) [static]
Definition at line 227 of file sender.c.
References sender::pipes.
static bool write_commit (struct sender *s, tx_info_t *info) [static]
Definition at line 231 of file sender.c.
References sender::bus, BUS_LOG_SNPRINTF, sender::commit_pipe, tx_info_t::id, LOG_SENDER, and bus::udata.
static tx_error_t commit_event_and_block (struct sender *s, tx_info_t *info) [static]
Definition at line 255 of file sender.c.
References sender::bus, BUS_LOG_SNPRINTF, tx_info_t::done_pipe, LOG_SENDER, SENDER_FD_NOT_IN_USE, TX_ERROR_CLOSED, TX_ERROR_NONE, TX_ERROR_WRITE_FAILURE, bus::udata, and write_commit().
void* sender_mainloop (void *arg)
Definition at line 332 of file sender.c.
References attempt_write(), BUS_LOG, BUS_LOG_SNPRINTF, check_incoming_commands(), cleanup(), CMD_FD, LOG_SENDER, tick_handler(), TIMEOUT_DELAY, bus::udata, and util_is_resumable_io_error().
static void free_fd_info_cb (void *value, void *udata) [static]
Definition at line 395 of file sender.c.
References fd_info::ssl.
static void cleanup (sender *s) [static]
Definition at line 405 of file sender.c.
References sender::bus, BUS_LOG, BUS_LOG_SNPRINTF, sender::commit_pipe, sender::fd_hash_table, free_fd_info_cb(), sender::incoming_command_pipe, LOG_SENDER, LOG_SHUTDOWN, MAX_CONCURRENT_SENDS, sender::pipes, tx_info_t::state, TIS_SHUTDOWN, sender::tx_info, bus::udata, and yacht_free().
static bool register_socket_info (sender *s, intfd, SSL *ssl) [static]
Definition at line 437 of file sender.c.
References fd_info::fd, sender::fd_hash_table, fd_info::largest_seq_id_seen, fd_info::refcount, sender::shutdown, fd_info::ssl, and yacht_set().
static void increment_fd_refcount (sender *s, fd_info *fdi) [static]
Definition at line 457 of file sender.c.
References sender::active_fds, fd_info::fd, sender::fds, fd_info::refcount, and SENDER_FD_NOT_IN_USE.
static void decrement_fd_refcount (sender *s, fd_info *fdi) [static]
Definition at line 472 of file sender.c.
References sender::active_fds, CMD_FD, fd_info::fd, sender::fds, MAX_CONCURRENT_SENDS, fd_info::refcount, and SENDER_FD_NOT_IN_USE.
static bool release_socket_info (sender *s, intfd) [static]
Definition at line 498 of file sender.c.
References fd_info::errored, fd_info::fd, sender::fd_hash_table, fd_info::refcount, set_error_for_socket(), sender::shutdown, TX_ERROR_CLOSED, and yacht_remove().
static void handle_command (sender *s, intid) [static]
Definition at line 520 of file sender.c.
References tx_info_t::add_socket, sender::bus, BUS_LOG_SNPRINTF, enqueue_write(), sender::is_idle, LOG_SENDER, MAX_CONCURRENT_SENDS, notify_caller(), register_socket_info(), release_socket_info(), tx_info_t::rm_socket, sender::shutdown, tx_info_t::state, TIS_ADD_SOCKET, TIS_REQUEST_ENQUEUE, TIS_RM_SOCKET, TIS_SHUTDOWN, sender::tx_info, tx_info_t::u, and bus::udata.
static void enqueue_write (struct sender *s, tx_info_t *info) [static]
Definition at line 572 of file sender.c.
References attempt_to_enqueue_sending_request_message_to_listener(), sender::bus, BUS_LOG_SNPRINTF, BUS_NO_SEQ_ID, tx_info_t::enqueue, fd_info::errored, sender::fd_hash_table, increment_fd_refcount(), fd_info::largest_seq_id_seen, LOG_SENDER, set_error_for_socket(), tx_info_t::state, TIS_REQUEST_ENQUEUE, TIS_REQUEST_WRITE, TX_ERROR_BAD_SEQUENCE_ID, TX_ERROR_CLOSED, TX_ERROR_UNREGISTERED_SOCKET, tx_info_t::u, bus::udata, tx_info_t::write, and yacht_get().
static bool check_incoming_commands (struct sender *s) [static]
Definition at line 631 of file sender.c.
References sender::bus, BUS_LOG_SNPRINTF, handle_command(), sender::incoming_command_pipe, LOG_SENDER, and bus::udata.
static tx_info_t* get_info_to_write_for_socket (sender *s, intfd) [static]
Definition at line 659 of file sender.c.
References MAX_CONCURRENT_SENDS, tx_info_t::state, TIS_REQUEST_WRITE, sender::tx_flags, sender::tx_info, tx_info_t::u, and tx_info_t::write.
static void set_error_for_socket (sender *s, intfd, tx_error_terror) [static]
Definition at line 688 of file sender.c.
References sender::bus, BUS_LOG_SNPRINTF, BUS_SEND_TX_FAILURE, BUS_SEND_UNDEFINED, BUS_SEND_UNREGISTERED_SOCKET, decrement_fd_refcount(), tx_info_t::enqueue, tx_info_t::error, fd_info::errored, sender::fd_hash_table, LOG_SENDER, MAX_CONCURRENT_SENDS, tx_info_t::notify, notify_message_failure(), tx_info_t::state, TIS_ERROR, TIS_REQUEST_ENQUEUE, TIS_REQUEST_WRITE, TIS_RESPONSE_NOTIFY, TX_ERROR_UNREGISTERED_SOCKET, sender::tx_flags, sender::tx_info, tx_info_t::u, bus::udata, tx_info_t::write, and yacht_get().
static void attempt_write (sender *s, intavailable) [static]
Definition at line 759 of file sender.c.
References sender::active_fds, sender::bus, BUS_LOG_SNPRINTF, BUS_NO_SSL, CMD_FD, sender::fds, get_info_to_write_for_socket(), LOG_SENDER, SENDER_FD_NOT_IN_USE, set_error_for_socket(), socket_write_plain(), socket_write_ssl(), tx_info_t::state, TIS_REQUEST_WRITE, TX_ERROR_POLLERR, TX_ERROR_POLLHUP, tx_info_t::u, bus::udata, and tx_info_t::write.
static ssize_t socket_write_plain (sender *s, tx_info_t *info) [static]
Definition at line 803 of file sender.c.
References sender::bus, BUS_LOG_SNPRINTF, tx_info_t::id, LOG_SENDER, boxed_msg::out_msg, boxed_msg::out_msg_size, set_error_for_socket(), tx_info_t::state, TIS_REQUEST_WRITE, TX_ERROR_WRITE_FAILURE, tx_info_t::u, bus::udata, update_sent(), util_is_resumable_io_error(), and tx_info_t::write.
static ssize_t socket_write_ssl (sender *s, tx_info_t *info, SSL *ssl) [static]
Definition at line 842 of file sender.c.
References sender::bus, BUS_LOG_SNPRINTF, LOG_SENDER, boxed_msg::out_msg, boxed_msg::out_msg_size, set_error_for_socket(), tx_info_t::state, TIS_REQUEST_WRITE, TX_ERROR_WRITE_FAILURE, tx_info_t::u, bus::udata, update_sent(), util_is_resumable_io_error(), and tx_info_t::write.
static void update_sent (struct bus *b, sender *s, tx_info_t *info, ssize_tsent) [static]
Definition at line 898 of file sender.c.
References attempt_to_enqueue_request_sent_message_to_listener(), BUS_LOG, BUS_LOG_SNPRINTF, decrement_fd_refcount(), LOG_SENDER, tx_info_t::notify, boxed_msg::out_msg, boxed_msg::out_msg_size, tx_info_t::state, TIS_REQUEST_WRITE, TIS_RESPONSE_NOTIFY, tx_info_t::u, bus::udata, and tx_info_t::write.
static void notify_caller (sender *s, tx_info_t *info, boolsuccess) [static]
Definition at line 936 of file sender.c.
References sender::bus, BUS_LOG_SNPRINTF, tx_info_t::error, tx_info_t::id, LOG_SENDER, sender::pipes, tx_info_t::release, tx_info_t::state, TIS_ERROR, TIS_REQUEST_RELEASE, tx_info_t::u, and bus::udata.
static void tick_handler (sender *s) [static]
Definition at line 987 of file sender.c.
References sender::active_fds, attempt_to_enqueue_request_sent_message_to_listener(), sender::bus, BUS_LOG_SNPRINTF, sender::is_idle, LOG_SENDER, MAX_CONCURRENT_SENDS, tx_info_t::state, tick_timeout(), TIS_REQUEST_WRITE, TIS_RESPONSE_NOTIFY, TIS_UNDEF, sender::tx_flags, sender::tx_info, and bus::udata.
static void tick_timeout (sender *s, tx_info_t *info) [static]
Definition at line 1033 of file sender.c.
References sender::bus, BUS_LOG, BUS_LOG_SNPRINTF, BUS_SEND_TX_TIMEOUT, tx_info_t::error, LOG_SENDER, tx_info_t::notify, notify_message_failure(), tx_info_t::state, TIS_ERROR, TIS_REQUEST_WRITE, TIS_RESPONSE_NOTIFY, TX_ERROR_NOTIFY_TIMEOUT, TX_ERROR_WRITE_TIMEOUT, tx_info_t::u, bus::udata, and tx_info_t::write.
static void attempt_to_enqueue_sending_request_message_to_listener (sender *s, intfd, int64_tseq_id, int16_ttimeout_sec) [static]
Definition at line 1096 of file sender.c.
References sender::bus, bus_get_listener_for_socket(), BUS_LOG_SNPRINTF, listener_hold_response(), LOG_SENDER, and bus::udata.
static void attempt_to_enqueue_request_sent_message_to_listener (sender *s, tx_info_t *info) [static]
Definition at line 1120 of file sender.c.
References sender::bus, bus_get_listener_for_socket(), BUS_LOG, BUS_LOG_SNPRINTF, tx_info_t::id, listener_expect_response(), LOG_SENDER, tx_info_t::notify, notify_caller(), tx_info_t::release, tx_info_t::state, TIS_REQUEST_RELEASE, TIS_RESPONSE_NOTIFY, tx_info_t::u, and bus::udata.
static void notify_message_failure (sender *s, tx_info_t *info, bus_send_status_tstatus) [static]
Definition at line 1154 of file sender.c.
References sender::bus, BUS_LOG_SNPRINTF, bus_process_boxed_message(), tx_info_t::error, tx_info_t::id, LOG_SENDER, notify_caller(), boxed_msg::result, tx_info_t::state, bus_msg_result_t::status, TIS_ERROR, tx_info_t::u, and bus::udata.
Author
Generated automatically by Doxygen for kinetic-c from the source code.