send_helper.c
NAME
send_helper.c -
SYNOPSIS
#include 'send_helper.h'
#include 'send_internal.h'
#include 'listener.h'
#include 'send.h'
#include 'syscall.h'
#include 'util.h'
#include <assert.h>
Functions
static ssize_t write_plain (struct bus *b, boxed_msg *box)
static ssize_t write_ssl (struct bus *b, boxed_msg *box, SSL *ssl)
static bool enqueue_EXPECT_message_to_listener (bus *b, boxed_msg *box)
SendHelper_HandleWrite_res SendHelper_HandleWrite (bus *b, boxed_msg *box)
Function Documentation
static ssize_t write_plain (struct bus *b, boxed_msg *box) [static]
Definition at line 97 of file send_helper.c.
References BUS_LOG_SNPRINTF, boxed_msg::fd, LOG_SENDER, boxed_msg::out_msg, boxed_msg::out_msg_size, boxed_msg::out_sent_size, syscall_write(), bus::udata, and Util_IsResumableIOError().
static ssize_t write_ssl (struct bus *b, boxed_msg *box, SSL *ssl) [static]
Definition at line 132 of file send_helper.c.
References BUS_LOG_SNPRINTF, boxed_msg::fd, LOG_SENDER, boxed_msg::out_msg, boxed_msg::out_msg_size, boxed_msg::out_sent_size, syscall_SSL_get_error(), syscall_SSL_write(), bus::udata, and Util_IsResumableIOError().
static bool enqueue_EXPECT_message_to_listener (bus *b, boxed_msg *box) [static]
Definition at line 215 of file send_helper.c.
References Bus_BackpressureDelay(), Bus_GetListenerForSocket(), BUS_LOG_SNPRINTF, BUS_SEND_REQUEST_COMPLETE, BUS_SEND_UNDEFINED, boxed_msg::fd, LISTENER_EXPECT_BACKPRESSURE_SHIFT, Listener_ExpectResponse(), LOG_SENDER, boxed_msg::out_seq_id, boxed_msg::result, SEND_NOTIFY_LISTENER_RETRIES, SEND_NOTIFY_LISTENER_RETRY_DELAY, bus_msg_result_t::status, syscall_poll(), and bus::udata.
SendHelper_HandleWrite_res SendHelper_HandleWrite (bus *b, boxed_msg *box)
Definition at line 39 of file send_helper.c.
References BUS_LOG_SNPRINTF, BUS_NO_SSL, BUS_SEND_TIMESTAMP_ERROR, BUS_SEND_TX_FAILURE, BUS_SEND_TX_TIMEOUT_NOTIFYING_LISTENER, enqueue_EXPECT_message_to_listener(), boxed_msg::fd, LOG_SENDER, boxed_msg::out_msg_size, boxed_msg::out_sent_size, boxed_msg::out_seq_id, Send_HandleFailure(), SHHW_DONE, SHHW_ERROR, SHHW_OK, boxed_msg::ssl, boxed_msg::tv_send_done, bus::udata, Util_Timestamp(), write_plain(), and write_ssl().
Author
Generated automatically by Doxygen for kinetic-c from the source code.