send.c
NAME
send.c -
SYNOPSIS
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
#include <sys/time.h>
#include <assert.h>
#include <poll.h>
#include 'bus.h'
#include 'bus_types.h'
#include 'bus_internal_types.h'
#include 'listener.h'
#include 'util.h'
#include 'atomic.h'
#include 'yacht.h'
#include 'send_internal.h'
Functions
bool send_do_blocking_send (bus *b, boxed_msg *box)
static bool attempt_to_enqueue_sending_request_message_to_listener (struct bus *b, int fd, int64_t seq_id, int16_t timeout_sec)
static void handle_failure (struct bus *b, boxed_msg *box, bus_send_status_t status)
static ssize_t write_plain (bus *b, boxed_msg *box)
static ssize_t write_ssl (bus *b, boxed_msg *box, SSL *ssl)
static bool enqueue_request_sent_message_to_listener (bus *b, boxed_msg *box)
static handle_write_res handle_write (bus *b, boxed_msg *box)
Function Documentation
bool send_do_blocking_send (bus *b, boxed_msg *box)
Definition at line 45 of file send.c.
References attempt_to_enqueue_sending_request_message_to_listener(), BUS_LOG_SNPRINTF, BUS_SEND_TX_FAILURE, BUS_SEND_TX_TIMEOUT, BUS_SEND_UNREGISTERED_SOCKET, boxed_msg::fd, handle_failure(), handle_write(), HW_DONE, HW_ERROR, HW_OK, LOG_SENDER, boxed_msg::out_msg, boxed_msg::out_msg_size, boxed_msg::out_sent_size, boxed_msg::out_seq_id, boxed_msg::timeout_sec, boxed_msg::tv_send_start, bus::udata, and util_timestamp().
static bool attempt_to_enqueue_sending_request_message_to_listener (struct bus *b, intfd, int64_tseq_id, int16_ttimeout_sec) [static]
Definition at line 165 of file send.c.
References bus_get_listener_for_socket(), BUS_LOG_SNPRINTF, listener_hold_response(), LOG_SENDER, and bus::udata.
static void handle_failure (struct bus *b, boxed_msg *box, bus_send_status_tstatus) [static]
Definition at line 188 of file send.c.
References bus_backpressure_delay(), BUS_LOG_SNPRINTF, bus_process_boxed_message(), boxed_msg::fd, LISTENER_EXPECT_BACKPRESSURE_SHIFT, LOG_SENDER, boxed_msg::out_seq_id, boxed_msg::result, bus_msg_result_t::status, and bus::udata.
static ssize_t write_plain (bus *b, boxed_msg *box) [static]
Definition at line 277 of file send.c.
References BUS_LOG_SNPRINTF, boxed_msg::fd, LOG_SENDER, boxed_msg::out_msg, boxed_msg::out_msg_size, boxed_msg::out_sent_size, bus::udata, and util_is_resumable_io_error().
static ssize_t write_ssl (bus *b, boxed_msg *box, SSL *ssl) [static]
Definition at line 312 of file send.c.
References BUS_LOG_SNPRINTF, boxed_msg::fd, LOG_SENDER, boxed_msg::out_msg, boxed_msg::out_msg_size, boxed_msg::out_sent_size, bus::udata, and util_is_resumable_io_error().
static bool enqueue_request_sent_message_to_listener (bus *b, boxed_msg *box) [static]
Definition at line 392 of file send.c.
References bus_backpressure_delay(), bus_get_listener_for_socket(), BUS_LOG_SNPRINTF, boxed_msg::fd, LISTENER_EXPECT_BACKPRESSURE_SHIFT, listener_expect_response(), LOG_SENDER, boxed_msg::out_seq_id, and bus::udata.
static handle_write_res handle_write (bus *b, boxed_msg *box) [static]
Definition at line 224 of file send.c.
References BUS_LOG_SNPRINTF, BUS_NO_SSL, BUS_SEND_TX_FAILURE, BUS_SEND_TX_TIMEOUT_NOTIFYING_LISTENER, enqueue_request_sent_message_to_listener(), boxed_msg::fd, handle_failure(), HW_DONE, HW_ERROR, HW_OK, LOG_SENDER, boxed_msg::out_msg_size, boxed_msg::out_sent_size, boxed_msg::out_seq_id, boxed_msg::ssl, boxed_msg::tv_send_done, bus::udata, util_timestamp(), write_plain(), and write_ssl().
Author
Generated automatically by Doxygen for kinetic-c from the source code.