send.h
NAME
send.h -
SYNOPSIS
#include 'bus_types.h'
#include 'bus_internal_types.h'
Functions
bool send_do_blocking_send (struct bus *b, boxed_msg *box)
Function Documentation
bool send_do_blocking_send (struct bus *b, boxed_msg *box)
Definition at line 45 of file send.c.
References attempt_to_enqueue_sending_request_message_to_listener(), BUS_LOG_SNPRINTF, BUS_SEND_TX_FAILURE, BUS_SEND_TX_TIMEOUT, BUS_SEND_UNREGISTERED_SOCKET, boxed_msg::fd, handle_failure(), handle_write(), HW_DONE, HW_ERROR, HW_OK, LOG_SENDER, boxed_msg::out_msg, boxed_msg::out_msg_size, boxed_msg::out_sent_size, boxed_msg::out_seq_id, boxed_msg::timeout_sec, boxed_msg::tv_send_start, bus::udata, and util_timestamp().
Author
Generated automatically by Doxygen for kinetic-c from the source code.