setup_teardown.c
NAME
setup_teardown.c -
SYNOPSIS
#include 'kinetic_client.h'
#include 'kinetic_types.h'
#include 'byte_array.h'
#include <stdlib.h>
#include <getopt.h>
#include <stdio.h>
#include <sys/param.h>
#include <sys/stat.h>
#include <sys/file.h>
Functions
static void usage (void)
static void handle_args (int argc, char **argv)
int main (int argc, char **argv)
Variables
static char * kinetic_host = 'localhost'
static long idle_seconds = 0
Function Documentation
static void usage (void) [static]
Definition at line 35 of file setup_teardown.c.
static void handle_args (intargc, char **argv) [static]
Definition at line 40 of file setup_teardown.c.
References idle_seconds, kinetic_host, and usage().
int main (intargc, char **argv)
Definition at line 57 of file setup_teardown.c.
References ByteArray_CreateWithCString(), handle_args(), KineticSessionConfig::host, idle_seconds, Kinetic_GetStatusDescription(), KINETIC_PORT, KINETIC_STATUS_SUCCESS, KineticClient_CreateSession(), KineticClient_DestroySession(), KineticClient_Init(), KineticClient_Shutdown(), and KineticClientConfig::logFile.
Variable Documentation
char* kinetic_host = 'localhost' [static]
Definition at line 32 of file setup_teardown.c.
long idle_seconds = 0 [static]
Definition at line 33 of file setup_teardown.c.
Author
Generated automatically by Doxygen for kinetic-c from the source code.