test_threadpool.c
NAME
test_threadpool.c -
SYNOPSIS
#include <stdlib.h>
#include <stdio.h>
#include <unistd.h>
#include <assert.h>
#include <err.h>
#include <poll.h>
#include 'threadpool.h'
Macros
#define ATOMIC_BOOL_COMPARE_AND_SWAP(PTR, OLD, NEW) (__sync_bool_compare_and_swap(PTR, OLD, NEW))
Functions
static size_t fibs (size_t arg)
static void dump_stats (const char *prefix, struct threadpool_info *stats)
static void task_cb (void *udata)
static void inf_loop_cb (void *env)
int main (int argc, char **argv)
Variables
static size_t task_count = 0
Macro Definition Documentation
#define ATOMIC_BOOL_COMPARE_AND_SWAP(PTR, OLD, NEW) (__sync_bool_compare_and_swap(PTR, OLD, NEW))
Definition at line 42 of file test_threadpool.c.
Function Documentation
static size_t fibs (size_targ) [static]
Definition at line 31 of file test_threadpool.c.
static void dump_stats (const char *prefix, struct threadpool_info *stats) [static]
Definition at line 36 of file test_threadpool.c.
References threadpool_info::active_threads, threadpool_info::backlog_size, and threadpool_info::dormant_threads.
static void task_cb (void *udata) [static]
Definition at line 45 of file test_threadpool.c.
References ATOMIC_BOOL_COMPARE_AND_SWAP, dump_stats(), fibs(), task_count, and threadpool_stats().
static void inf_loop_cb (void *env) [static]
Definition at line 68 of file test_threadpool.c.
int main (intargc, char **argv)
Definition at line 75 of file test_threadpool.c.
References dump_stats(), inf_loop_cb(), limit, threadpool_config::max_threads, threadpool_task::task, task_cb(), task_count, threadpool_config::task_ringbuf_size2, THREAD_SHUTDOWN_SECONDS, threadpool_free(), threadpool_init(), threadpool_schedule(), threadpool_shutdown(), and threadpool_stats().
Variable Documentation
size_t task_count = 0 [static]
Definition at line 29 of file test_threadpool.c.
Author
Generated automatically by Doxygen for kinetic-c from the source code.