test_threadpool_stress.c
NAME
test_threadpool_stress.c -
SYNOPSIS
#include <stdlib.h>
#include <stdio.h>
#include <unistd.h>
#include <assert.h>
#include <err.h>
#include <poll.h>
#include <sys/time.h>
#include 'threadpool.h'
Macros
#define ATOMIC_BOOL_COMPARE_AND_SWAP(PTR, OLD, NEW) (__sync_bool_compare_and_swap(PTR, OLD, NEW))
#define SPIN_ADJ(F, ADJ)
Functions
static void dump_stats (const char *prefix, struct threadpool_info *stats, size_t ticks)
static size_t fibs (size_t arg)
static void task_cb (void *udata)
int main (int argc, char **argv)
Variables
static size_t task_count = 0
static size_t last_count = 0
Macro Definition Documentation
#define ATOMIC_BOOL_COMPARE_AND_SWAP(PTR, OLD, NEW) (__sync_bool_compare_and_swap(PTR, OLD, NEW))
Definition at line 44 of file test_threadpool_stress.c.
#define SPIN_ADJ(F, ADJ)
Value:
do { \
        for (;;) { \
            size_t v = F; \
            if (ATOMIC_BOOL_COMPARE_AND_SWAP(&F, v, v + ADJ)) { \
                break; \
            } \
        } \
    } while (0)
Definition at line 48 of file test_threadpool_stress.c.
Function Documentation
static void dump_stats (const char *prefix, struct threadpool_info *stats, size_tticks) [static]
Definition at line 35 of file test_threadpool_stress.c.
References threadpool_info::active_threads, threadpool_info::backlog_size, threadpool_info::dormant_threads, last_count, and task_count.
static size_t fibs (size_targ) [static]
Definition at line 58 of file test_threadpool_stress.c.
static void task_cb (void *udata) [static]
Definition at line 63 of file test_threadpool_stress.c.
References fibs(), SPIN_ADJ, and task_count.
int main (intargc, char **argv)
Definition at line 70 of file test_threadpool_stress.c.
References dump_stats(), threadpool_config::max_threads, threadpool_task::task, task_cb(), threadpool_config::task_ringbuf_size2, Threadpool_Init(), Threadpool_Schedule(), and Threadpool_Stats().
Variable Documentation
size_t task_count = 0 [static]
Definition at line 32 of file test_threadpool_stress.c.
size_t last_count = 0 [static]
Definition at line 33 of file test_threadpool_stress.c.
Author
Generated automatically by Doxygen for kinetic-c from the source code.