test_yacht.c
NAME
test_yacht.c -
SYNOPSIS
#include 'greatest.h'
#include 'yacht.h'
Functions
static int yacht_should_cleanly_init_and_free (void)
static int yacht_should_add_and_have_accurate_membership (void)
static int yacht_should_add_and_remove_accurately (uint8_t sz2)
static int yacht_should_add_and_remove_accurately_out_of_order (uint8_t sz2)
static int yacht_set_should_return_old_keys (uint8_t sz2)
static int yacht_should_grow_and_add_and_remove_accurately_out_of_order (uint8_t sz2)
void suite (void)
static int greatest_name_match (const char *name, const char *filter)
int greatest_pre_test (const char *name)
void greatest_post_test (const char *name, int res)
static void greatest_run_suite (greatest_suite_cb *suite_cb, const char *suite_name)
void greatest_do_pass (const char *name)
void greatest_do_fail (const char *name)
void greatest_do_skip (const char *name)
int greatest_do_assert_equal_t (const void *exp, const void *got, greatest_type_info *type_info, void *udata)
void greatest_usage (const char *name)
void GREATEST_SET_SETUP_CB (greatest_setup_cb *cb, void *udata)
void GREATEST_SET_TEARDOWN_CB (greatest_teardown_cb *cb, void *udata)
static int greatest_string_equal_cb (const void *exp, const void *got, void *udata)
static int greatest_string_printf_cb (const void *t, void *udata)
int main (int argc, char **argv)
Variables
greatest_type_info greatest_type_info_string = { greatest_string_equal_cb, greatest_string_printf_cb, }
greatest_run_info greatest_info
Function Documentation
static int yacht_should_cleanly_init_and_free (void) [static]
Definition at line 25 of file test_yacht.c.
References ASSERT, PASS, yacht_free(), and yacht_init().
static int yacht_should_add_and_have_accurate_membership (void) [static]
Definition at line 32 of file test_yacht.c.
References ASSERT, PASS, yacht_free(), yacht_init(), yacht_member(), and yacht_set().
static int yacht_should_add_and_remove_accurately (uint8_tsz2) [static]
Definition at line 46 of file test_yacht.c.
References ASSERT, ASSERT_EQ, PASS, yacht_free(), yacht_init(), yacht_member(), yacht_remove(), and yacht_set().
static int yacht_should_add_and_remove_accurately_out_of_order (uint8_tsz2) [static]
Definition at line 73 of file test_yacht.c.
References ASSERT, PASS, yacht_free(), yacht_init(), yacht_member(), yacht_remove(), and yacht_set().
static int yacht_set_should_return_old_keys (uint8_tsz2) [static]
Definition at line 99 of file test_yacht.c.
References ASSERT, ASSERT_EQ, PASS, yacht_free(), yacht_get(), yacht_init(), yacht_member(), and yacht_set().
static int yacht_should_grow_and_add_and_remove_accurately_out_of_order (uint8_tsz2) [static]
Definition at line 126 of file test_yacht.c.
References ASSERT, ASSERT_EQ, PASS, yacht_free(), yacht_init(), yacht_member(), yacht_remove(), and yacht_set().
void suite (void)
Definition at line 160 of file test_yacht.c.
References RUN_TEST, RUN_TESTp, yacht_set_should_return_old_keys(), yacht_should_add_and_have_accurate_membership(), yacht_should_add_and_remove_accurately(), yacht_should_add_and_remove_accurately_out_of_order(), yacht_should_cleanly_init_and_free(), and yacht_should_grow_and_add_and_remove_accurately_out_of_order().
static int greatest_name_match (const char *name, const char *filter) [static]
Definition at line 179 of file test_yacht.c.
int greatest_pre_test (const char *name)
Definition at line 179 of file test_yacht.c.
void greatest_post_test (const char *name, intres)
Definition at line 179 of file test_yacht.c.
static void greatest_run_suite (greatest_suite_cb *suite_cb, const char *suite_name) [static]
Definition at line 179 of file test_yacht.c.
void greatest_do_pass (const char *name)
Definition at line 179 of file test_yacht.c.
void greatest_do_fail (const char *name)
Definition at line 179 of file test_yacht.c.
void greatest_do_skip (const char *name)
Definition at line 179 of file test_yacht.c.
int greatest_do_assert_equal_t (const void *exp, const void *got, greatest_type_info *type_info, void *udata)
Definition at line 179 of file test_yacht.c.
void greatest_usage (const char *name)
Definition at line 179 of file test_yacht.c.
void GREATEST_SET_SETUP_CB (greatest_setup_cb *cb, void *udata)
Definition at line 179 of file test_yacht.c.
void GREATEST_SET_TEARDOWN_CB (greatest_teardown_cb *cb, void *udata)
Definition at line 179 of file test_yacht.c.
static int greatest_string_equal_cb (const void *exp, const void *got, void *udata) [static]
Definition at line 179 of file test_yacht.c.
static int greatest_string_printf_cb (const void *t, void *udata) [static]
Definition at line 179 of file test_yacht.c.
int main (intargc, char **argv)
Definition at line 181 of file test_yacht.c.
References GREATEST_MAIN_BEGIN, GREATEST_MAIN_END, RUN_SUITE, and suite().
Variable Documentation
greatest_type_info greatest_type_info_string = { greatest_string_equal_cb, greatest_string_printf_cb, }
Definition at line 179 of file test_yacht.c.
greatest_run_info greatest_info
Definition at line 179 of file test_yacht.c.
Author
Generated automatically by Doxygen for kinetic-c from the source code.