test_threadpool_sequencing.c
NAME
test_threadpool_sequencing.c -
SYNOPSIS
#include <stdlib.h>
#include <stdio.h>
#include <unistd.h>
#include <assert.h>
#include <err.h>
#include <poll.h>
#include <sys/time.h>
#include <string.h>
#include <pthread.h>
#include 'threadpool.h'
Macros
#define MAX_TASKS 32
#define ATOMIC_BOOL_COMPARE_AND_SWAP(PTR, OLD, NEW) (__sync_bool_compare_and_swap(PTR, OLD, NEW))
#define SPIN_ADJ(F, ADJ)
Functions
static void dump_stats (const char *prefix, struct threadpool_info *stats, size_t ticks)
static void task_cb (void *udata)
int main (int argc, char **argv)
Variables
static size_t completed_count = 0
static size_t limit = 1000000
Macro Definition Documentation
#define MAX_TASKS 32
Definition at line 35 of file test_threadpool_sequencing.c.
#define ATOMIC_BOOL_COMPARE_AND_SWAP(PTR, OLD, NEW) (__sync_bool_compare_and_swap(PTR, OLD, NEW))
Definition at line 44 of file test_threadpool_sequencing.c.
#define SPIN_ADJ(F, ADJ)
Value:
do { \
        for (;;) { \
            size_t v = F; \
            if (ATOMIC_BOOL_COMPARE_AND_SWAP(&F, v, v + ADJ)) { \
                break; \
            } \
        } \
    } while (0)
Definition at line 48 of file test_threadpool_sequencing.c.
Function Documentation
static void dump_stats (const char *prefix, struct threadpool_info *stats, size_tticks) [static]
Definition at line 37 of file test_threadpool_sequencing.c.
References threadpool_info::active_threads, threadpool_info::backlog_size, completed_count, and threadpool_info::dormant_threads.
static void task_cb (void *udata) [static]
Definition at line 66 of file test_threadpool_sequencing.c.
References completed_count, limit, SPIN_ADJ, and Threadpool_Schedule().
int main (intargc, char **argv)
Definition at line 84 of file test_threadpool_sequencing.c.
References completed_count, dump_stats(), limit, MAX_TASKS, threadpool_config::max_threads, threadpool_task::task, task_cb(), threadpool_config::task_ringbuf_size2, Threadpool_Init(), Threadpool_Schedule(), and Threadpool_Stats().
Variable Documentation
size_t completed_count = 0 [static]
Definition at line 34 of file test_threadpool_sequencing.c.
size_t limit = 1000000 [static]
Definition at line 64 of file test_threadpool_sequencing.c.
Author
Generated automatically by Doxygen for kinetic-c from the source code.