.TH "thread_info" 3 "Tue Jan 27 2015" "Version v0.11.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
thread_info \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <threadpool_internals\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "pthread_t \fBt\fP"
.br
.ti -1c
.RI "int \fBparent_fd\fP"
.br
.ti -1c
.RI "int \fBchild_fd\fP"
.br
.ti -1c
.RI "\fBthread_status_t\fP \fBstatus\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file threadpool_internals\&.h\&.
.SH "Field Documentation"
.PP 
.SS "pthread_t thread_info::t"

.PP
Definition at line 16 of file threadpool_internals\&.h\&.
.SS "int thread_info::parent_fd"

.PP
Definition at line 17 of file threadpool_internals\&.h\&.
.SS "int thread_info::child_fd"

.PP
Definition at line 18 of file threadpool_internals\&.h\&.
.SS "\fBthread_status_t\fP thread_info::status"

.PP
Definition at line 19 of file threadpool_internals\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
