.TH "thread_context" 3 "Tue Jan 27 2015" "Version v0.11.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
thread_context \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <threadpool_internals\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBthreadpool\fP * \fBt\fP"
.br
.ti -1c
.RI "struct \fBthread_info\fP * \fBti\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 23 of file threadpool_internals\&.h\&.
.SH "Field Documentation"
.PP 
.SS "struct \fBthreadpool\fP* thread_context::t"

.PP
Definition at line 24 of file threadpool_internals\&.h\&.
.SS "struct \fBthread_info\fP* thread_context::ti"

.PP
Definition at line 25 of file threadpool_internals\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
