.TH "threadpool_task" 3 "Tue Jan 27 2015" "Version v0.11.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
threadpool_task \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <threadpool\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBthreadpool_task_cb\fP * \fBtask\fP"
.br
.ti -1c
.RI "\fBthreadpool_task_cleanup_cb\fP * \fBcleanup\fP"
.br
.ti -1c
.RI "void * \fBudata\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 48 of file threadpool\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBthreadpool_task_cb\fP* threadpool_task::task"

.PP
Definition at line 49 of file threadpool\&.h\&.
.SS "\fBthreadpool_task_cleanup_cb\fP* threadpool_task::cleanup"

.PP
Definition at line 50 of file threadpool\&.h\&.
.SS "void* threadpool_task::udata"

.PP
Definition at line 51 of file threadpool\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
