.TH "threadpool_info" 3 "Tue Jan 27 2015" "Version v0.11.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
threadpool_info \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <threadpool\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBactive_threads\fP"
.br
.ti -1c
.RI "uint8_t \fBdormant_threads\fP"
.br
.ti -1c
.RI "size_t \fBbacklog_size\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 55 of file threadpool\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint8_t threadpool_info::active_threads"

.PP
Definition at line 56 of file threadpool\&.h\&.
.SS "uint8_t threadpool_info::dormant_threads"

.PP
Definition at line 57 of file threadpool\&.h\&.
.SS "size_t threadpool_info::backlog_size"

.PP
Definition at line 58 of file threadpool\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
