.TH "threadpool_config" 3 "Tue Jan 27 2015" "Version v0.11.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
threadpool_config \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <threadpool\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBtask_ringbuf_size2\fP"
.br
.ti -1c
.RI "size_t \fBmax_delay\fP"
.br
.ti -1c
.RI "uint8_t \fBmax_threads\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 34 of file threadpool\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint8_t threadpool_config::task_ringbuf_size2"

.PP
Definition at line 35 of file threadpool\&.h\&.
.SS "size_t threadpool_config::max_delay"

.PP
Definition at line 36 of file threadpool\&.h\&.
.SS "uint8_t threadpool_config::max_threads"

.PP
Definition at line 37 of file threadpool\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
