.TH "tx_info_t" 3 "Mon Mar 2 2015" "Version v0.12.0-beta" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tx_info_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sender_internal\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const int \fBid\fP"
.br
.ti -1c
.RI "int \fBdone_pipe\fP"
.br
.ti -1c
.RI "\fBtx_info_state\fP \fBstate\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   struct {"
.br
.ti -1c
.RI "      int \fBfd\fP"
.br
.ti -1c
.RI "      SSL * \fBssl\fP"
.br
.ti -1c
.RI "   } \fBadd_socket\fP"
.br
.ti -1c
.RI "   struct {"
.br
.ti -1c
.RI "      int \fBfd\fP"
.br
.ti -1c
.RI "   } \fBrm_socket\fP"
.br
.ti -1c
.RI "   struct \fBu_enqueue\fP {"
.br
.ti -1c
.RI "      int \fBfd\fP"
.br
.ti -1c
.RI "      time_t \fBtimeout_sec\fP"
.br
.ti -1c
.RI "      \fBboxed_msg\fP * \fBbox\fP"
.br
.ti -1c
.RI "   } \fBenqueue\fP"
.br
.ti -1c
.RI "   struct \fBu_write\fP {"
.br
.ti -1c
.RI "      int \fBfd\fP"
.br
.ti -1c
.RI "      time_t \fBtimeout_sec\fP"
.br
.ti -1c
.RI "      time_t \fBorig_timeout_sec\fP"
.br
.ti -1c
.RI "      \fBboxed_msg\fP * \fBbox\fP"
.br
.ti -1c
.RI "      size_t \fBsent_size\fP"
.br
.ti -1c
.RI "      \fBfd_info\fP * \fBfdi\fP"
.br
.ti -1c
.RI "   } \fBwrite\fP"
.br
.ti -1c
.RI "   struct \fBu_notify\fP {"
.br
.ti -1c
.RI "      int \fBfd\fP"
.br
.ti -1c
.RI "      time_t \fBtimeout_sec\fP"
.br
.ti -1c
.RI "      \fBboxed_msg\fP * \fBbox\fP"
.br
.ti -1c
.RI "   } \fBnotify\fP"
.br
.ti -1c
.RI "   struct {"
.br
.ti -1c
.RI "      uint16_t \fBbackpressure\fP"
.br
.ti -1c
.RI "   } \fBrelease\fP"
.br
.ti -1c
.RI "   struct \fBu_error\fP {"
.br
.ti -1c
.RI "      \fBtx_error_t\fP \fBerror\fP"
.br
.ti -1c
.RI "      \fBboxed_msg\fP * \fBbox\fP"
.br
.ti -1c
.RI "      uint16_t \fBbackpressure\fP"
.br
.ti -1c
.RI "   } \fBerror\fP"
.br
.ti -1c
.RI "} \fBu\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 78 of file sender_internal\&.h\&.
.SH "Field Documentation"
.PP 
.SS "const int tx_info_t::id"

.PP
Definition at line 80 of file sender_internal\&.h\&.
.SS "int tx_info_t::done_pipe"

.PP
Definition at line 83 of file sender_internal\&.h\&.
.SS "\fBtx_info_state\fP tx_info_t::state"

.PP
Definition at line 86 of file sender_internal\&.h\&.
.SS "int tx_info_t::fd"

.PP
Definition at line 89 of file sender_internal\&.h\&.
.SS "SSL* tx_info_t::ssl"

.PP
Definition at line 90 of file sender_internal\&.h\&.
.SS "struct { \&.\&.\&. }   tx_info_t::add_socket"

.SS "struct { \&.\&.\&. }   tx_info_t::rm_socket"

.SS "time_t tx_info_t::timeout_sec"

.PP
Definition at line 99 of file sender_internal\&.h\&.
.SS "\fBboxed_msg\fP* tx_info_t::box"

.PP
Definition at line 100 of file sender_internal\&.h\&.
.SS "struct { \&.\&.\&. } ::u_enqueue  tx_info_t::enqueue"

.SS "time_t tx_info_t::orig_timeout_sec"

.PP
Definition at line 106 of file sender_internal\&.h\&.
.SS "size_t tx_info_t::sent_size"

.PP
Definition at line 108 of file sender_internal\&.h\&.
.SS "\fBfd_info\fP* tx_info_t::fdi"

.PP
Definition at line 109 of file sender_internal\&.h\&.
.SS "struct { \&.\&.\&. } ::u_write  tx_info_t::write"

.SS "struct { \&.\&.\&. } ::u_notify  tx_info_t::notify"

.SS "uint16_t tx_info_t::backpressure"

.PP
Definition at line 119 of file sender_internal\&.h\&.
.SS "struct { \&.\&.\&. }   tx_info_t::release"

.SS "\fBtx_error_t\fP tx_info_t::error"

.PP
Definition at line 123 of file sender_internal\&.h\&.
.SS "struct { \&.\&.\&. } ::u_error  tx_info_t::error"

.SS "union { \&.\&.\&. }   tx_info_t::u"


.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
