.TH "util.c" 3 "Tue Jan 27 2015" "Version v0.11.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
util.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdbool\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include 'util\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fButil_is_resumable_io_error\fP (int errno_)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool util_is_resumable_io_error (interrno_)"

.PP
Definition at line 25 of file util\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
