.TH "util.h" 3 "Tue Mar 3 2015" "Version v0.12.0-beta" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
util.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdbool\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include <sys/time\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fButil_is_resumable_io_error\fP (int errno_)"
.br
.ti -1c
.RI "bool \fButil_timestamp\fP (struct timeval *tv, bool relative)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool util_is_resumable_io_error (interrno_)"

.PP
Definition at line 26 of file util\&.c\&.
.SS "bool util_timestamp (struct timeval *tv, boolrelative)"

.PP
Definition at line 30 of file util\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
