.TH "util.h" 3 "Fri Mar 13 2015" "Version v0.12.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
util.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdbool\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include <sys/time\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBUtil_IsResumableIOError\fP (int errno_)"
.br
.ti -1c
.RI "bool \fBUtil_Timestamp\fP (struct timeval *tv, bool relative)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool Util_IsResumableIOError (interrno_)"

.PP
Definition at line 26 of file util\&.c\&.
.SS "bool Util_Timestamp (struct timeval *tv, boolrelative)"

.PP
Definition at line 30 of file util\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
