write_file_nonblocking_threads.c
NAME
write_file_nonblocking_threads.c -
SYNOPSIS
#include 'kinetic_client.h'
#include 'kinetic_types.h'
#include 'byte_array.h'
#include <stdlib.h>
#include <getopt.h>
#include <stdio.h>
#include <sys/param.h>
#include <sys/stat.h>
#include <sys/file.h>
#include <pthread.h>
#include <errno.h>
Macros
#define REPORT_ERRNO(en, msg) if(en != 0){errno = en; perror(msg);}
Functions
void * store_file_thread (void *storeArgs)
FileTransferProgress * start_file_transfer (KineticSession *session, char const *const filename, uint64_t prefix, uint32_t maxOverlappedChunks)
KineticStatus wait_for_transfer_complete (FileTransferProgress *const transfer)
int main (int argc, char **argv)
Macro Definition Documentation
#define REPORT_ERRNO(en, msg) if(en != 0){errno = en; perror(msg);}
Definition at line 32 of file write_file_nonblocking_threads.c.
Function Documentation
void * store_file_thread (void *storeArgs)
Definition at line 163 of file write_file_nonblocking_threads.c.
References Kinetic_GetStatusDescription(), KINETIC_STATUS_SUCCESS, start_file_transfer(), and wait_for_transfer_complete().
FileTransferProgress* start_file_transfer (KineticSession *session, char const *constfilename, uint64_tprefix, uint32_tmaxOverlappedChunks)
Definition at line 176 of file write_file_nonblocking_threads.c.
References ByteBuffer_CreateAndAppend().
KineticStatus wait_for_transfer_complete (FileTransferProgress *consttransfer)
Definition at line 198 of file write_file_nonblocking_threads.c.
int main (intargc, char **argv)
Definition at line 79 of file write_file_nonblocking_threads.c.
References ByteArray_CreateWithCString(), KineticSession::config, KineticSessionConfig::host, Kinetic_GetStatusDescription(), KINETIC_PORT, KINETIC_STATUS_SUCCESS, KineticClient_CreateConnection(), KineticClient_DestroyConnection(), KineticClient_Init(), KineticClient_Shutdown(), REPORT_ERRNO, and store_file_thread().
Author
Generated automatically by Doxygen for kinetic-c from the source code.