write_file_nonblocking.c
NAME
write_file_nonblocking.c -
SYNOPSIS
#include 'kinetic_client.h'
#include 'kinetic_types.h'
#include 'byte_array.h'
#include <stdlib.h>
#include <getopt.h>
#include <stdio.h>
#include <sys/param.h>
#include <sys/stat.h>
#include <sys/file.h>
#include <pthread.h>
#include <errno.h>
Macros
#define REPORT_ERRNO(en, msg) if(en != 0){errno = en; perror(msg);}
Functions
FileTransferProgress * start_file_transfer (KineticSession *session, char const *const filename, uint64_t keyPrefix, uint32_t maxOverlappedChunks)
KineticStatus wait_for_put_finish (FileTransferProgress *const transfer)
static int put_chunk_of_file (FileTransferProgress *transfer)
static void put_chunk_of_file_finished (KineticCompletionData *kinetic_data, void *client_data)
int main (int argc, char **argv)
Macro Definition Documentation
#define REPORT_ERRNO(en, msg) if(en != 0){errno = en; perror(msg);}
Definition at line 32 of file write_file_nonblocking.c.
Function Documentation
FileTransferProgress * start_file_transfer (KineticSession *session, char const *constfilename, uint64_tkeyPrefix, uint32_tmaxOverlappedChunks)
Definition at line 194 of file write_file_nonblocking.c.
References put_chunk_of_file().
KineticStatus wait_for_put_finish (FileTransferProgress *consttransfer)
Definition at line 215 of file write_file_nonblocking.c.
static int put_chunk_of_file (FileTransferProgress *transfer) [static]
Definition at line 121 of file write_file_nonblocking.c.
References ByteBuffer_Create(), ByteBuffer_CreateAndAppend(), ByteBuffer_CreateAndAppendFormattedCString(), KINETIC_ALGORITHM_SHA1, Kinetic_GetStatusDescription(), KINETIC_STATUS_SUCCESS, KINETIC_SYNCHRONIZATION_WRITETHROUGH, KineticClient_Put(), and REPORT_ERRNO.
static void put_chunk_of_file_finished (KineticCompletionData *kinetic_data, void *client_data) [static]
Definition at line 166 of file write_file_nonblocking.c.
References Kinetic_GetStatusDescription(), KINETIC_STATUS_NOT_ATTEMPTED, KINETIC_STATUS_SUCCESS, put_chunk_of_file(), and KineticCompletionData::status.
int main (intargc, char **argv)
Definition at line 69 of file write_file_nonblocking.c.
References ByteArray_CreateWithCString(), KineticSessionConfig::host, Kinetic_GetStatusDescription(), KINETIC_PORT, KINETIC_STATUS_SUCCESS, KineticClient_CreateSession(), KineticClient_DestroySession(), KineticClient_Init(), KineticClient_Shutdown(), KineticClientConfig::logFile, start_file_transfer(), and wait_for_put_finish().
Author
Generated automatically by Doxygen for kinetic-c from the source code.