write_file_blocking.c
NAME
write_file_blocking.c -
SYNOPSIS
#include 'kinetic_client.h'
#include 'kinetic_types.h'
#include 'byte_array.h'
#include <stdlib.h>
#include <getopt.h>
#include <stdio.h>
#include <sys/param.h>
#include <sys/stat.h>
#include <sys/file.h>
Functions
void store_data (write_args *args)
int main (int argc, char **argv)
Function Documentation
void store_data (write_args *args)
Definition at line 44 of file write_file_blocking.c.
References ByteBuffer_AppendArray(), ByteBuffer_AppendCString(), ByteBuffer_BytesRemaining(), ByteBuffer_Consume(), ByteBuffer_Reset(), KineticEntry::key, Kinetic_GetStatusDescription(), KINETIC_OBJ_SIZE, KINETIC_STATUS_SUCCESS, KineticClient_Put(), and KineticEntry::value.
int main (intargc, char **argv)
Definition at line 81 of file write_file_blocking.c.
References ByteArray_CreateWithCString(), ByteBuffer_AppendCString(), ByteBuffer_Create(), KineticSession::config, KineticSessionConfig::host, KINETIC_ALGORITHM_SHA1, Kinetic_GetStatusDescription(), KINETIC_PORT, KINETIC_STATUS_SUCCESS, KINETIC_SYNCHRONIZATION_WRITEBACK, KineticClient_CreateConnection(), KineticClient_DestroyConnection(), KineticClient_Init(), KineticClient_Shutdown(), KineticClientConfig::logFile, and store_data().
Author
Generated automatically by Doxygen for kinetic-c from the source code.