write_file_blocking_threads.c
NAME
write_file_blocking_threads.c -
SYNOPSIS
#include 'kinetic_client.h'
#include 'kinetic_types.h'
#include 'byte_array.h'
#include <stdlib.h>
#include <getopt.h>
#include <stdio.h>
#include <sys/param.h>
#include <sys/stat.h>
#include <sys/file.h>
#include <pthread.h>
#include <errno.h>
Macros
#define NUM_FILES (3)
#define REPORT_ERRNO(en, msg) if(en != 0){errno = en; perror(msg);}
Functions
void * store_data (void *args)
int main (int argc, char **argv)
Macro Definition Documentation
#define NUM_FILES (3)
Definition at line 33 of file write_file_blocking_threads.c.
#define REPORT_ERRNO(en, msg) if(en != 0){errno = en; perror(msg);}
Definition at line 35 of file write_file_blocking_threads.c.
Function Documentation
void* store_data (void *args)
Definition at line 51 of file write_file_blocking_threads.c.
References ByteBuffer_AppendArray(), ByteBuffer_AppendCString(), ByteBuffer_BytesRemaining(), ByteBuffer_Consume(), ByteBuffer::bytesUsed, KineticEntry::key, Kinetic_GetStatusDescription(), KINETIC_OBJ_SIZE, KINETIC_STATUS_SUCCESS, KINETIC_SYNCHRONIZATION_WRITEBACK, KineticClient_Put(), KineticEntry::synchronization, and KineticEntry::value.
int main (intargc, char **argv)
Definition at line 80 of file write_file_blocking_threads.c.
References ByteArray_CreateWithCString(), ByteBuffer_Create(), ByteBuffer_CreateAndAppendCString(), KineticSessionConfig::host, KINETIC_ALGORITHM_SHA1, Kinetic_GetStatusDescription(), KINETIC_PORT, KINETIC_STATUS_SUCCESS, KineticClient_CreateSession(), KineticClient_DestroySession(), KineticClient_Init(), KineticClient_Shutdown(), KineticClientConfig::logFile, NUM_FILES, REPORT_ERRNO, and store_data().
Author
Generated automatically by Doxygen for kinetic-c from the source code.