.TH "yacht" 3 "Fri Mar 13 2015" "Version v0.12.0" "kinetic-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
yacht \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <yacht_internals\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "size_t \fBsize\fP"
.br
.RI "\fISize of bucket array\&. \fP"
.ti -1c
.RI "size_t \fBmask\fP"
.br
.RI "\fIMask for hash table bucket array\&. \fP"
.ti -1c
.RI "int * \fBbuckets\fP"
.br
.RI "\fIHash table buckets (keys)\&. \fP"
.ti -1c
.RI "void ** \fBvalues\fP"
.br
.RI "\fIValues associated with keys, if any\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 26 of file yacht_internals\&.h\&.
.SH "Field Documentation"
.PP 
.SS "size_t yacht::size"

.PP
Size of bucket array\&. 
.PP
Definition at line 27 of file yacht_internals\&.h\&.
.SS "size_t yacht::mask"

.PP
Mask for hash table bucket array\&. 
.PP
Definition at line 28 of file yacht_internals\&.h\&.
.SS "int* yacht::buckets"

.PP
Hash table buckets (keys)\&. 
.PP
Definition at line 29 of file yacht_internals\&.h\&.
.SS "void** yacht::values"

.PP
Values associated with keys, if any\&. 
.PP
Definition at line 30 of file yacht_internals\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kinetic-c from the source code\&.
