/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: kinetic.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "kinetic.pb-c.h"
void KineticProto_command__init(KineticProto_Command* message)
{
    static KineticProto_Command init_value = KINETIC_PROTO_COMMAND__INIT;
    *message = init_value;
}

void KineticProto_header__init(KineticProto_Header* message)
{
    static KineticProto_Header init_value = KINETIC_PROTO_HEADER__INIT;
    *message = init_value;
}

void KineticProto_body__init(KineticProto_Body* message)
{
    static KineticProto_Body init_value = KINETIC_PROTO_BODY__INIT;
    *message = init_value;
}

void KineticProto_status__init(KineticProto_Status* message)
{
    static KineticProto_Status init_value = KINETIC_PROTO_STATUS__INIT;
    *message = init_value;
}

void KineticProto_key_value__init(KineticProto_KeyValue* message)
{
    static KineticProto_KeyValue init_value = KINETIC_PROTO_KEY_VALUE__INIT;
    *message = init_value;
}

void KineticProto_range__init(KineticProto_Range* message)
{
    static KineticProto_Range init_value = KINETIC_PROTO_RANGE__INIT;
    *message = init_value;
}

void KineticProto_setup__init(KineticProto_Setup* message)
{
    static KineticProto_Setup init_value = KINETIC_PROTO_SETUP__INIT;
    *message = init_value;
}

void KineticProto_p2_poperation__operation__init(KineticProto_P2POperation__Operation* message)
{
    static KineticProto_P2POperation__Operation init_value = KINETIC_PROTO_P2_POPERATION__OPERATION__INIT;
    *message = init_value;
}

void KineticProto_p2_poperation__peer__init(KineticProto_P2POperation__Peer* message)
{
    static KineticProto_P2POperation__Peer init_value = KINETIC_PROTO_P2_POPERATION__PEER__INIT;
    *message = init_value;
}

void KineticProto_p2_poperation__init(KineticProto_P2POperation* message)
{
    static KineticProto_P2POperation init_value = KINETIC_PROTO_P2_POPERATION__INIT;
    *message = init_value;
}

void KineticProto_get_log__utilization__init(KineticProto_GetLog__Utilization* message)
{
    static KineticProto_GetLog__Utilization init_value = KINETIC_PROTO_GET_LOG__UTILIZATION__INIT;
    *message = init_value;
}

void KineticProto_get_log__temperature__init(KineticProto_GetLog__Temperature* message)
{
    static KineticProto_GetLog__Temperature init_value = KINETIC_PROTO_GET_LOG__TEMPERATURE__INIT;
    *message = init_value;
}

void KineticProto_get_log__capacity__init(KineticProto_GetLog__Capacity* message)
{
    static KineticProto_GetLog__Capacity init_value = KINETIC_PROTO_GET_LOG__CAPACITY__INIT;
    *message = init_value;
}

void KineticProto_get_log__configuration__interface__init(KineticProto_GetLog__Configuration__Interface* message)
{
    static KineticProto_GetLog__Configuration__Interface init_value = KINETIC_PROTO_GET_LOG__CONFIGURATION__INTERFACE__INIT;
    *message = init_value;
}

void KineticProto_get_log__configuration__init(KineticProto_GetLog__Configuration* message)
{
    static KineticProto_GetLog__Configuration init_value = KINETIC_PROTO_GET_LOG__CONFIGURATION__INIT;
    *message = init_value;
}

void KineticProto_get_log__statistics__init(KineticProto_GetLog__Statistics* message)
{
    static KineticProto_GetLog__Statistics init_value = KINETIC_PROTO_GET_LOG__STATISTICS__INIT;
    *message = init_value;
}

void KineticProto_get_log__limits__init(KineticProto_GetLog__Limits* message)
{
    static KineticProto_GetLog__Limits init_value = KINETIC_PROTO_GET_LOG__LIMITS__INIT;
    *message = init_value;
}

void KineticProto_get_log__init(KineticProto_GetLog* message)
{
    static KineticProto_GetLog init_value = KINETIC_PROTO_GET_LOG__INIT;
    *message = init_value;
}

void KineticProto_security__acl__scope__init(KineticProto_Security__ACL__Scope* message)
{
    static KineticProto_Security__ACL__Scope init_value = KINETIC_PROTO_SECURITY__ACL__SCOPE__INIT;
    *message = init_value;
}

void KineticProto_security__acl__init(KineticProto_Security__ACL* message)
{
    static KineticProto_Security__ACL init_value = KINETIC_PROTO_SECURITY__ACL__INIT;
    *message = init_value;
}

void KineticProto_security__init(KineticProto_Security* message)
{
    static KineticProto_Security init_value = KINETIC_PROTO_SECURITY__INIT;
    *message = init_value;
}

void KineticProto_init(KineticProto* message)
{
    static KineticProto init_value = KINETIC_PROTO_INIT;
    *message = init_value;
}

size_t KineticProto_get_packed_size(const KineticProto* message)
{
    assert(message->base.descriptor == &KineticProto_descriptor);
    return protobuf_c_message_get_packed_size((const ProtobufCMessage*)(message));
}

size_t KineticProto_pack(const KineticProto* message, uint8_t* out)
{
    assert(message->base.descriptor == &KineticProto_descriptor);
    return protobuf_c_message_pack((const ProtobufCMessage*)message, out);
}

size_t KineticProto_pack_to_buffer(const KineticProto* message, ProtobufCBuffer* buffer)
{
    assert(message->base.descriptor == &KineticProto_descriptor);
    return protobuf_c_message_pack_to_buffer((const ProtobufCMessage*)message, buffer);
}

KineticProto* KineticProto_unpack(ProtobufCAllocator* allocator, size_t len, const uint8_t* data)
{
    return (KineticProto*) protobuf_c_message_unpack(&KineticProto_descriptor, allocator, len, data);
}

void KineticProto_free_unpacked(KineticProto* message, ProtobufCAllocator* allocator)
{
    assert(message->base.descriptor == &KineticProto_descriptor);
    protobuf_c_message_free_unpacked((ProtobufCMessage*)message, allocator);
}

static const ProtobufCFieldDescriptor KineticProto_command__field_descriptors[3] =
{
    {
        "header",
        1,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_MESSAGE,
        0,   /* quantifier_offset */
        offsetof(KineticProto_Command, header),
        &KineticProto_header__descriptor,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "body",
        2,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_MESSAGE,
        0,   /* quantifier_offset */
        offsetof(KineticProto_Command, body),
        &KineticProto_body__descriptor,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "status",
        3,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_MESSAGE,
        0,   /* quantifier_offset */
        offsetof(KineticProto_Command, status),
        &KineticProto_status__descriptor,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
};

static const unsigned KineticProto_command__field_indices_by_name[] =
{
    1,   /* field[1] = body */
    0,   /* field[0] = header */
    2,   /* field[2] = status */
};

static const ProtobufCIntRange KineticProto_command__number_ranges[1 + 1] =
{
    { 1, 0 },
    { 0, 3 }
};

const ProtobufCMessageDescriptor KineticProto_command__descriptor =
{
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "com.seagate.kinetic.proto.Message.Command",
    "Command",
    "KineticProto_Command",
    "com.seagate.kinetic.proto",
    sizeof(KineticProto_Command),
    3,
    KineticProto_command__field_descriptors,
    KineticProto_command__field_indices_by_name,
    1,  KineticProto_command__number_ranges,
    (ProtobufCMessageInit) KineticProto_command__init,
    NULL, NULL, NULL  /* reserved[123] */
};

static const ProtobufCFieldDescriptor KineticProto_header__field_descriptors[9] =
{
    {
        "clusterVersion",
        1,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_INT64,
        offsetof(KineticProto_Header, has_clusterversion),
        offsetof(KineticProto_Header, clusterversion),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "identity",
        2,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_INT64,
        offsetof(KineticProto_Header, has_identity),
        offsetof(KineticProto_Header, identity),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "connectionID",
        3,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_INT64,
        offsetof(KineticProto_Header, has_connectionid),
        offsetof(KineticProto_Header, connectionid),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "sequence",
        4,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_INT64,
        offsetof(KineticProto_Header, has_sequence),
        offsetof(KineticProto_Header, sequence),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "ackSequence",
        6,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_INT64,
        offsetof(KineticProto_Header, has_acksequence),
        offsetof(KineticProto_Header, acksequence),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "messageType",
        7,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_ENUM,
        offsetof(KineticProto_Header, has_messagetype),
        offsetof(KineticProto_Header, messagetype),
        &KineticProto_message_type__descriptor,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "timeout",
        9,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_INT64,
        offsetof(KineticProto_Header, has_timeout),
        offsetof(KineticProto_Header, timeout),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "earlyExit",
        10,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_BOOL,
        offsetof(KineticProto_Header, has_earlyexit),
        offsetof(KineticProto_Header, earlyexit),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "backgroundScan",
        11,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_BOOL,
        offsetof(KineticProto_Header, has_backgroundscan),
        offsetof(KineticProto_Header, backgroundscan),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
};

static const unsigned KineticProto_header__field_indices_by_name[] =
{
    4,   /* field[4] = ackSequence */
    8,   /* field[8] = backgroundScan */
    0,   /* field[0] = clusterVersion */
    2,   /* field[2] = connectionID */
    7,   /* field[7] = earlyExit */
    1,   /* field[1] = identity */
    5,   /* field[5] = messageType */
    3,   /* field[3] = sequence */
    6,   /* field[6] = timeout */
};

static const ProtobufCIntRange KineticProto_header__number_ranges[3 + 1] =
{
    { 1, 0 },
    { 6, 4 },
    { 9, 6 },
    { 0, 9 }
};

const ProtobufCMessageDescriptor KineticProto_header__descriptor =
{
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "com.seagate.kinetic.proto.Message.Header",
    "Header",
    "KineticProto_Header",
    "com.seagate.kinetic.proto",
    sizeof(KineticProto_Header),
    9,
    KineticProto_header__field_descriptors,
    KineticProto_header__field_indices_by_name,
    3,  KineticProto_header__number_ranges,
    (ProtobufCMessageInit) KineticProto_header__init,
    NULL, NULL, NULL  /* reserved[123] */
};

static const ProtobufCFieldDescriptor KineticProto_body__field_descriptors[6] =
{
    {
        "keyValue",
        1,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_MESSAGE,
        0,   /* quantifier_offset */
        offsetof(KineticProto_Body, keyvalue),
        &KineticProto_key_value__descriptor,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "range",
        2,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_MESSAGE,
        0,   /* quantifier_offset */
        offsetof(KineticProto_Body, range),
        &KineticProto_range__descriptor,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "setup",
        3,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_MESSAGE,
        0,   /* quantifier_offset */
        offsetof(KineticProto_Body, setup),
        &KineticProto_setup__descriptor,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "p2pOperation",
        4,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_MESSAGE,
        0,   /* quantifier_offset */
        offsetof(KineticProto_Body, p2poperation),
        &KineticProto_p2_poperation__descriptor,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "getLog",
        6,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_MESSAGE,
        0,   /* quantifier_offset */
        offsetof(KineticProto_Body, getlog),
        &KineticProto_get_log__descriptor,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "security",
        7,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_MESSAGE,
        0,   /* quantifier_offset */
        offsetof(KineticProto_Body, security),
        &KineticProto_security__descriptor,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
};

static const unsigned KineticProto_body__field_indices_by_name[] =
{
    4,   /* field[4] = getLog */
    0,   /* field[0] = keyValue */
    3,   /* field[3] = p2pOperation */
    1,   /* field[1] = range */
    5,   /* field[5] = security */
    2,   /* field[2] = setup */
};

static const ProtobufCIntRange KineticProto_body__number_ranges[2 + 1] =
{
    { 1, 0 },
    { 6, 4 },
    { 0, 6 }
};

const ProtobufCMessageDescriptor KineticProto_body__descriptor =
{
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "com.seagate.kinetic.proto.Message.Body",
    "Body",
    "KineticProto_Body",
    "com.seagate.kinetic.proto",
    sizeof(KineticProto_Body),
    6,
    KineticProto_body__field_descriptors,
    KineticProto_body__field_indices_by_name,
    2,  KineticProto_body__number_ranges,
    (ProtobufCMessageInit) KineticProto_body__init,
    NULL, NULL, NULL  /* reserved[123] */
};

const ProtobufCEnumValue KineticProto_status__status_code__enum_values_by_number[19] =
{
    { "INVALID_STATUS_CODE", "KINETIC_PROTO_STATUS__STATUS_CODE__INVALID_STATUS_CODE", -1 },
    { "NOT_ATTEMPTED", "KINETIC_PROTO_STATUS__STATUS_CODE__NOT_ATTEMPTED", 0 },
    { "SUCCESS", "KINETIC_PROTO_STATUS__STATUS_CODE__SUCCESS", 1 },
    { "HMAC_FAILURE", "KINETIC_PROTO_STATUS__STATUS_CODE__HMAC_FAILURE", 2 },
    { "NOT_AUTHORIZED", "KINETIC_PROTO_STATUS__STATUS_CODE__NOT_AUTHORIZED", 3 },
    { "VERSION_FAILURE", "KINETIC_PROTO_STATUS__STATUS_CODE__VERSION_FAILURE", 4 },
    { "INTERNAL_ERROR", "KINETIC_PROTO_STATUS__STATUS_CODE__INTERNAL_ERROR", 5 },
    { "HEADER_REQUIRED", "KINETIC_PROTO_STATUS__STATUS_CODE__HEADER_REQUIRED", 6 },
    { "NOT_FOUND", "KINETIC_PROTO_STATUS__STATUS_CODE__NOT_FOUND", 7 },
    { "VERSION_MISMATCH", "KINETIC_PROTO_STATUS__STATUS_CODE__VERSION_MISMATCH", 8 },
    { "SERVICE_BUSY", "KINETIC_PROTO_STATUS__STATUS_CODE__SERVICE_BUSY", 9 },
    { "EXPIRED", "KINETIC_PROTO_STATUS__STATUS_CODE__EXPIRED", 10 },
    { "DATA_ERROR", "KINETIC_PROTO_STATUS__STATUS_CODE__DATA_ERROR", 11 },
    { "PERM_DATA_ERROR", "KINETIC_PROTO_STATUS__STATUS_CODE__PERM_DATA_ERROR", 12 },
    { "REMOTE_CONNECTION_ERROR", "KINETIC_PROTO_STATUS__STATUS_CODE__REMOTE_CONNECTION_ERROR", 13 },
    { "NO_SPACE", "KINETIC_PROTO_STATUS__STATUS_CODE__NO_SPACE", 14 },
    { "NO_SUCH_HMAC_ALGORITHM", "KINETIC_PROTO_STATUS__STATUS_CODE__NO_SUCH_HMAC_ALGORITHM", 15 },
    { "INVALID_REQUEST", "KINETIC_PROTO_STATUS__STATUS_CODE__INVALID_REQUEST", 16 },
    { "NESTED_OPERATION_ERRORS", "KINETIC_PROTO_STATUS__STATUS_CODE__NESTED_OPERATION_ERRORS", 17 },
};

static const ProtobufCIntRange KineticProto_status__status_code__value_ranges[] =
{
    { -1, 0}, {0, 19}
};

const ProtobufCEnumValueIndex KineticProto_status__status_code__enum_values_by_name[19] =
{
    { "DATA_ERROR", 12 },
    { "EXPIRED", 11 },
    { "HEADER_REQUIRED", 7 },
    { "HMAC_FAILURE", 3 },
    { "INTERNAL_ERROR", 6 },
    { "INVALID_REQUEST", 17 },
    { "INVALID_STATUS_CODE", 0 },
    { "NESTED_OPERATION_ERRORS", 18 },
    { "NOT_ATTEMPTED", 1 },
    { "NOT_AUTHORIZED", 4 },
    { "NOT_FOUND", 8 },
    { "NO_SPACE", 15 },
    { "NO_SUCH_HMAC_ALGORITHM", 16 },
    { "PERM_DATA_ERROR", 13 },
    { "REMOTE_CONNECTION_ERROR", 14 },
    { "SERVICE_BUSY", 10 },
    { "SUCCESS", 2 },
    { "VERSION_FAILURE", 5 },
    { "VERSION_MISMATCH", 9 },
};

const ProtobufCEnumDescriptor KineticProto_status__status_code__descriptor =
{
    PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
    "com.seagate.kinetic.proto.Message.Status.StatusCode",
    "StatusCode",
    "KineticProto_Status__StatusCode",
    "com.seagate.kinetic.proto",
    19,
    KineticProto_status__status_code__enum_values_by_number,
    19,
    KineticProto_status__status_code__enum_values_by_name,
    1,
    KineticProto_status__status_code__value_ranges,
    NULL, NULL, NULL, NULL /* reserved[1234] */
};

static const ProtobufCFieldDescriptor KineticProto_status__field_descriptors[3] =
{
    {
        "code",
        1,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_ENUM,
        offsetof(KineticProto_Status, has_code),
        offsetof(KineticProto_Status, code),
        &KineticProto_status__status_code__descriptor,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "statusMessage",
        2,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_STRING,
        0,   /* quantifier_offset */
        offsetof(KineticProto_Status, statusmessage),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "detailedMessage",
        3,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_BYTES,
        offsetof(KineticProto_Status, has_detailedmessage),
        offsetof(KineticProto_Status, detailedmessage),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
};

static const unsigned KineticProto_status__field_indices_by_name[] =
{
    0,   /* field[0] = code */
    2,   /* field[2] = detailedMessage */
    1,   /* field[1] = statusMessage */
};

static const ProtobufCIntRange KineticProto_status__number_ranges[1 + 1] =
{
    { 1, 0 },
    { 0, 3 }
};

const ProtobufCMessageDescriptor KineticProto_status__descriptor =
{
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "com.seagate.kinetic.proto.Message.Status",
    "Status",
    "KineticProto_Status",
    "com.seagate.kinetic.proto",
    sizeof(KineticProto_Status),
    3,
    KineticProto_status__field_descriptors,
    KineticProto_status__field_indices_by_name,
    1,  KineticProto_status__number_ranges,
    (ProtobufCMessageInit) KineticProto_status__init,
    NULL, NULL, NULL  /* reserved[123] */
};

static const ProtobufCFieldDescriptor KineticProto_key_value__field_descriptors[8] =
{
    {
        "newVersion",
        2,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_BYTES,
        offsetof(KineticProto_KeyValue, has_newversion),
        offsetof(KineticProto_KeyValue, newversion),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "key",
        3,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_BYTES,
        offsetof(KineticProto_KeyValue, has_key),
        offsetof(KineticProto_KeyValue, key),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "dbVersion",
        4,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_BYTES,
        offsetof(KineticProto_KeyValue, has_dbversion),
        offsetof(KineticProto_KeyValue, dbversion),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "tag",
        5,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_BYTES,
        offsetof(KineticProto_KeyValue, has_tag),
        offsetof(KineticProto_KeyValue, tag),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "algorithm",
        6,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_ENUM,
        offsetof(KineticProto_KeyValue, has_algorithm),
        offsetof(KineticProto_KeyValue, algorithm),
        &KineticProto_algorithm__descriptor,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "metadataOnly",
        7,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_BOOL,
        offsetof(KineticProto_KeyValue, has_metadataonly),
        offsetof(KineticProto_KeyValue, metadataonly),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "force",
        8,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_BOOL,
        offsetof(KineticProto_KeyValue, has_force),
        offsetof(KineticProto_KeyValue, force),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "synchronization",
        9,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_ENUM,
        offsetof(KineticProto_KeyValue, has_synchronization),
        offsetof(KineticProto_KeyValue, synchronization),
        &KineticProto_synchronization__descriptor,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
};

static const unsigned KineticProto_key_value__field_indices_by_name[] =
{
    4,   /* field[4] = algorithm */
    2,   /* field[2] = dbVersion */
    6,   /* field[6] = force */
    1,   /* field[1] = key */
    5,   /* field[5] = metadataOnly */
    0,   /* field[0] = newVersion */
    7,   /* field[7] = synchronization */
    3,   /* field[3] = tag */
};

static const ProtobufCIntRange KineticProto_key_value__number_ranges[1 + 1] =
{
    { 2, 0 },
    { 0, 8 }
};

const ProtobufCMessageDescriptor KineticProto_key_value__descriptor =
{
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "com.seagate.kinetic.proto.Message.KeyValue",
    "KeyValue",
    "KineticProto_KeyValue",
    "com.seagate.kinetic.proto",
    sizeof(KineticProto_KeyValue),
    8,
    KineticProto_key_value__field_descriptors,
    KineticProto_key_value__field_indices_by_name,
    1,  KineticProto_key_value__number_ranges,
    (ProtobufCMessageInit) KineticProto_key_value__init,
    NULL, NULL, NULL  /* reserved[123] */
};

static const ProtobufCFieldDescriptor KineticProto_range__field_descriptors[7] =
{
    {
        "startKey",
        1,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_BYTES,
        offsetof(KineticProto_Range, has_startkey),
        offsetof(KineticProto_Range, startkey),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "endKey",
        2,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_BYTES,
        offsetof(KineticProto_Range, has_endkey),
        offsetof(KineticProto_Range, endkey),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "startKeyInclusive",
        3,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_BOOL,
        offsetof(KineticProto_Range, has_startkeyinclusive),
        offsetof(KineticProto_Range, startkeyinclusive),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "endKeyInclusive",
        4,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_BOOL,
        offsetof(KineticProto_Range, has_endkeyinclusive),
        offsetof(KineticProto_Range, endkeyinclusive),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "maxReturned",
        5,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_INT32,
        offsetof(KineticProto_Range, has_maxreturned),
        offsetof(KineticProto_Range, maxreturned),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "reverse",
        6,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_BOOL,
        offsetof(KineticProto_Range, has_reverse),
        offsetof(KineticProto_Range, reverse),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "key",
        8,
        PROTOBUF_C_LABEL_REPEATED,
        PROTOBUF_C_TYPE_BYTES,
        offsetof(KineticProto_Range, n_key),
        offsetof(KineticProto_Range, key),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
};

static const unsigned KineticProto_range__field_indices_by_name[] =
{
    1,   /* field[1] = endKey */
    3,   /* field[3] = endKeyInclusive */
    6,   /* field[6] = key */
    4,   /* field[4] = maxReturned */
    5,   /* field[5] = reverse */
    0,   /* field[0] = startKey */
    2,   /* field[2] = startKeyInclusive */
};

static const ProtobufCIntRange KineticProto_range__number_ranges[2 + 1] =
{
    { 1, 0 },
    { 8, 6 },
    { 0, 7 }
};

const ProtobufCMessageDescriptor KineticProto_range__descriptor =
{
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "com.seagate.kinetic.proto.Message.Range",
    "Range",
    "KineticProto_Range",
    "com.seagate.kinetic.proto",
    sizeof(KineticProto_Range),
    7,
    KineticProto_range__field_descriptors,
    KineticProto_range__field_indices_by_name,
    2,  KineticProto_range__number_ranges,
    (ProtobufCMessageInit) KineticProto_range__init,
    NULL, NULL, NULL  /* reserved[123] */
};

static const ProtobufCFieldDescriptor KineticProto_setup__field_descriptors[5] =
{
    {
        "newClusterVersion",
        1,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_INT64,
        offsetof(KineticProto_Setup, has_newclusterversion),
        offsetof(KineticProto_Setup, newclusterversion),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "instantSecureErase",
        2,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_BOOL,
        offsetof(KineticProto_Setup, has_instantsecureerase),
        offsetof(KineticProto_Setup, instantsecureerase),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "setPin",
        3,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_BYTES,
        offsetof(KineticProto_Setup, has_setpin),
        offsetof(KineticProto_Setup, setpin),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "pin",
        4,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_BYTES,
        offsetof(KineticProto_Setup, has_pin),
        offsetof(KineticProto_Setup, pin),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "firmwareDownload",
        5,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_BOOL,
        offsetof(KineticProto_Setup, has_firmwaredownload),
        offsetof(KineticProto_Setup, firmwaredownload),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
};

static const unsigned KineticProto_setup__field_indices_by_name[] =
{
    4,   /* field[4] = firmwareDownload */
    1,   /* field[1] = instantSecureErase */
    0,   /* field[0] = newClusterVersion */
    3,   /* field[3] = pin */
    2,   /* field[2] = setPin */
};

static const ProtobufCIntRange KineticProto_setup__number_ranges[1 + 1] =
{
    { 1, 0 },
    { 0, 5 }
};

const ProtobufCMessageDescriptor KineticProto_setup__descriptor =
{
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "com.seagate.kinetic.proto.Message.Setup",
    "Setup",
    "KineticProto_Setup",
    "com.seagate.kinetic.proto",
    sizeof(KineticProto_Setup),
    5,
    KineticProto_setup__field_descriptors,
    KineticProto_setup__field_indices_by_name,
    1,  KineticProto_setup__number_ranges,
    (ProtobufCMessageInit) KineticProto_setup__init,
    NULL, NULL, NULL  /* reserved[123] */
};

static const ProtobufCFieldDescriptor KineticProto_p2_poperation__operation__field_descriptors[6] =
{
    {
        "key",
        3,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_BYTES,
        offsetof(KineticProto_P2POperation__Operation, has_key),
        offsetof(KineticProto_P2POperation__Operation, key),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "version",
        4,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_BYTES,
        offsetof(KineticProto_P2POperation__Operation, has_version),
        offsetof(KineticProto_P2POperation__Operation, version),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "newKey",
        5,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_BYTES,
        offsetof(KineticProto_P2POperation__Operation, has_newkey),
        offsetof(KineticProto_P2POperation__Operation, newkey),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "force",
        6,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_BOOL,
        offsetof(KineticProto_P2POperation__Operation, has_force),
        offsetof(KineticProto_P2POperation__Operation, force),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "status",
        7,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_MESSAGE,
        0,   /* quantifier_offset */
        offsetof(KineticProto_P2POperation__Operation, status),
        &KineticProto_status__descriptor,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "p2pop",
        8,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_MESSAGE,
        0,   /* quantifier_offset */
        offsetof(KineticProto_P2POperation__Operation, p2pop),
        &KineticProto_p2_poperation__descriptor,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
};

static const unsigned KineticProto_p2_poperation__operation__field_indices_by_name[] =
{
    3,   /* field[3] = force */
    0,   /* field[0] = key */
    2,   /* field[2] = newKey */
    5,   /* field[5] = p2pop */
    4,   /* field[4] = status */
    1,   /* field[1] = version */
};

static const ProtobufCIntRange KineticProto_p2_poperation__operation__number_ranges[1 + 1] =
{
    { 3, 0 },
    { 0, 6 }
};

const ProtobufCMessageDescriptor KineticProto_p2_poperation__operation__descriptor =
{
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "com.seagate.kinetic.proto.Message.P2POperation.Operation",
    "Operation",
    "KineticProto_P2POperation__Operation",
    "com.seagate.kinetic.proto",
    sizeof(KineticProto_P2POperation__Operation),
    6,
    KineticProto_p2_poperation__operation__field_descriptors,
    KineticProto_p2_poperation__operation__field_indices_by_name,
    1,  KineticProto_p2_poperation__operation__number_ranges,
    (ProtobufCMessageInit) KineticProto_p2_poperation__operation__init,
    NULL, NULL, NULL  /* reserved[123] */
};

static const ProtobufCFieldDescriptor KineticProto_p2_poperation__peer__field_descriptors[3] =
{
    {
        "hostname",
        1,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_STRING,
        0,   /* quantifier_offset */
        offsetof(KineticProto_P2POperation__Peer, hostname),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "port",
        2,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_INT32,
        offsetof(KineticProto_P2POperation__Peer, has_port),
        offsetof(KineticProto_P2POperation__Peer, port),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "tls",
        3,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_BOOL,
        offsetof(KineticProto_P2POperation__Peer, has_tls),
        offsetof(KineticProto_P2POperation__Peer, tls),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
};

static const unsigned KineticProto_p2_poperation__peer__field_indices_by_name[] =
{
    0,   /* field[0] = hostname */
    1,   /* field[1] = port */
    2,   /* field[2] = tls */
};

static const ProtobufCIntRange KineticProto_p2_poperation__peer__number_ranges[1 + 1] =
{
    { 1, 0 },
    { 0, 3 }
};

const ProtobufCMessageDescriptor KineticProto_p2_poperation__peer__descriptor =
{
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "com.seagate.kinetic.proto.Message.P2POperation.Peer",
    "Peer",
    "KineticProto_P2POperation__Peer",
    "com.seagate.kinetic.proto",
    sizeof(KineticProto_P2POperation__Peer),
    3,
    KineticProto_p2_poperation__peer__field_descriptors,
    KineticProto_p2_poperation__peer__field_indices_by_name,
    1,  KineticProto_p2_poperation__peer__number_ranges,
    (ProtobufCMessageInit) KineticProto_p2_poperation__peer__init,
    NULL, NULL, NULL  /* reserved[123] */
};

static const ProtobufCFieldDescriptor KineticProto_p2_poperation__field_descriptors[3] =
{
    {
        "peer",
        1,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_MESSAGE,
        0,   /* quantifier_offset */
        offsetof(KineticProto_P2POperation, peer),
        &KineticProto_p2_poperation__peer__descriptor,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "operation",
        2,
        PROTOBUF_C_LABEL_REPEATED,
        PROTOBUF_C_TYPE_MESSAGE,
        offsetof(KineticProto_P2POperation, n_operation),
        offsetof(KineticProto_P2POperation, operation),
        &KineticProto_p2_poperation__operation__descriptor,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "allChildOperationsSucceeded",
        3,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_BOOL,
        offsetof(KineticProto_P2POperation, has_allchildoperationssucceeded),
        offsetof(KineticProto_P2POperation, allchildoperationssucceeded),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
};

static const unsigned KineticProto_p2_poperation__field_indices_by_name[] =
{
    2,   /* field[2] = allChildOperationsSucceeded */
    1,   /* field[1] = operation */
    0,   /* field[0] = peer */
};

static const ProtobufCIntRange KineticProto_p2_poperation__number_ranges[1 + 1] =
{
    { 1, 0 },
    { 0, 3 }
};

const ProtobufCMessageDescriptor KineticProto_p2_poperation__descriptor =
{
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "com.seagate.kinetic.proto.Message.P2POperation",
    "P2POperation",
    "KineticProto_P2POperation",
    "com.seagate.kinetic.proto",
    sizeof(KineticProto_P2POperation),
    3,
    KineticProto_p2_poperation__field_descriptors,
    KineticProto_p2_poperation__field_indices_by_name,
    1,  KineticProto_p2_poperation__number_ranges,
    (ProtobufCMessageInit) KineticProto_p2_poperation__init,
    NULL, NULL, NULL  /* reserved[123] */
};

static const ProtobufCFieldDescriptor KineticProto_get_log__utilization__field_descriptors[2] =
{
    {
        "name",
        1,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_STRING,
        0,   /* quantifier_offset */
        offsetof(KineticProto_GetLog__Utilization, name),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "value",
        2,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_FLOAT,
        offsetof(KineticProto_GetLog__Utilization, has_value),
        offsetof(KineticProto_GetLog__Utilization, value),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
};

static const unsigned KineticProto_get_log__utilization__field_indices_by_name[] =
{
    0,   /* field[0] = name */
    1,   /* field[1] = value */
};

static const ProtobufCIntRange KineticProto_get_log__utilization__number_ranges[1 + 1] =
{
    { 1, 0 },
    { 0, 2 }
};

const ProtobufCMessageDescriptor KineticProto_get_log__utilization__descriptor =
{
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "com.seagate.kinetic.proto.Message.GetLog.Utilization",
    "Utilization",
    "KineticProto_GetLog__Utilization",
    "com.seagate.kinetic.proto",
    sizeof(KineticProto_GetLog__Utilization),
    2,
    KineticProto_get_log__utilization__field_descriptors,
    KineticProto_get_log__utilization__field_indices_by_name,
    1,  KineticProto_get_log__utilization__number_ranges,
    (ProtobufCMessageInit) KineticProto_get_log__utilization__init,
    NULL, NULL, NULL  /* reserved[123] */
};

static const ProtobufCFieldDescriptor KineticProto_get_log__temperature__field_descriptors[5] =
{
    {
        "name",
        1,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_STRING,
        0,   /* quantifier_offset */
        offsetof(KineticProto_GetLog__Temperature, name),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "current",
        2,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_FLOAT,
        offsetof(KineticProto_GetLog__Temperature, has_current),
        offsetof(KineticProto_GetLog__Temperature, current),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "minimum",
        3,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_FLOAT,
        offsetof(KineticProto_GetLog__Temperature, has_minimum),
        offsetof(KineticProto_GetLog__Temperature, minimum),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "maximum",
        4,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_FLOAT,
        offsetof(KineticProto_GetLog__Temperature, has_maximum),
        offsetof(KineticProto_GetLog__Temperature, maximum),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "target",
        5,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_FLOAT,
        offsetof(KineticProto_GetLog__Temperature, has_target),
        offsetof(KineticProto_GetLog__Temperature, target),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
};

static const unsigned KineticProto_get_log__temperature__field_indices_by_name[] =
{
    1,   /* field[1] = current */
    3,   /* field[3] = maximum */
    2,   /* field[2] = minimum */
    0,   /* field[0] = name */
    4,   /* field[4] = target */
};

static const ProtobufCIntRange KineticProto_get_log__temperature__number_ranges[1 + 1] =
{
    { 1, 0 },
    { 0, 5 }
};

const ProtobufCMessageDescriptor KineticProto_get_log__temperature__descriptor =
{
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "com.seagate.kinetic.proto.Message.GetLog.Temperature",
    "Temperature",
    "KineticProto_GetLog__Temperature",
    "com.seagate.kinetic.proto",
    sizeof(KineticProto_GetLog__Temperature),
    5,
    KineticProto_get_log__temperature__field_descriptors,
    KineticProto_get_log__temperature__field_indices_by_name,
    1,  KineticProto_get_log__temperature__number_ranges,
    (ProtobufCMessageInit) KineticProto_get_log__temperature__init,
    NULL, NULL, NULL  /* reserved[123] */
};

static const ProtobufCFieldDescriptor KineticProto_get_log__capacity__field_descriptors[2] =
{
    {
        "nominalCapacityInBytes",
        4,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_UINT64,
        offsetof(KineticProto_GetLog__Capacity, has_nominalcapacityinbytes),
        offsetof(KineticProto_GetLog__Capacity, nominalcapacityinbytes),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "portionFull",
        5,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_FLOAT,
        offsetof(KineticProto_GetLog__Capacity, has_portionfull),
        offsetof(KineticProto_GetLog__Capacity, portionfull),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
};

static const unsigned KineticProto_get_log__capacity__field_indices_by_name[] =
{
    0,   /* field[0] = nominalCapacityInBytes */
    1,   /* field[1] = portionFull */
};

static const ProtobufCIntRange KineticProto_get_log__capacity__number_ranges[1 + 1] =
{
    { 4, 0 },
    { 0, 2 }
};

const ProtobufCMessageDescriptor KineticProto_get_log__capacity__descriptor =
{
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "com.seagate.kinetic.proto.Message.GetLog.Capacity",
    "Capacity",
    "KineticProto_GetLog__Capacity",
    "com.seagate.kinetic.proto",
    sizeof(KineticProto_GetLog__Capacity),
    2,
    KineticProto_get_log__capacity__field_descriptors,
    KineticProto_get_log__capacity__field_indices_by_name,
    1,  KineticProto_get_log__capacity__number_ranges,
    (ProtobufCMessageInit) KineticProto_get_log__capacity__init,
    NULL, NULL, NULL  /* reserved[123] */
};

static const ProtobufCFieldDescriptor KineticProto_get_log__configuration__interface__field_descriptors[4] =
{
    {
        "name",
        1,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_STRING,
        0,   /* quantifier_offset */
        offsetof(KineticProto_GetLog__Configuration__Interface, name),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "MAC",
        2,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_BYTES,
        offsetof(KineticProto_GetLog__Configuration__Interface, has_mac),
        offsetof(KineticProto_GetLog__Configuration__Interface, mac),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "ipv4Address",
        3,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_BYTES,
        offsetof(KineticProto_GetLog__Configuration__Interface, has_ipv4address),
        offsetof(KineticProto_GetLog__Configuration__Interface, ipv4address),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "ipv6Address",
        4,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_BYTES,
        offsetof(KineticProto_GetLog__Configuration__Interface, has_ipv6address),
        offsetof(KineticProto_GetLog__Configuration__Interface, ipv6address),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
};

static const unsigned KineticProto_get_log__configuration__interface__field_indices_by_name[] =
{
    1,   /* field[1] = MAC */
    2,   /* field[2] = ipv4Address */
    3,   /* field[3] = ipv6Address */
    0,   /* field[0] = name */
};

static const ProtobufCIntRange KineticProto_get_log__configuration__interface__number_ranges[1 + 1] =
{
    { 1, 0 },
    { 0, 4 }
};

const ProtobufCMessageDescriptor KineticProto_get_log__configuration__interface__descriptor =
{
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "com.seagate.kinetic.proto.Message.GetLog.Configuration.Interface",
    "Interface",
    "KineticProto_GetLog__Configuration__Interface",
    "com.seagate.kinetic.proto",
    sizeof(KineticProto_GetLog__Configuration__Interface),
    4,
    KineticProto_get_log__configuration__interface__field_descriptors,
    KineticProto_get_log__configuration__interface__field_indices_by_name,
    1,  KineticProto_get_log__configuration__interface__number_ranges,
    (ProtobufCMessageInit) KineticProto_get_log__configuration__interface__init,
    NULL, NULL, NULL  /* reserved[123] */
};

static const ProtobufCFieldDescriptor KineticProto_get_log__configuration__field_descriptors[13] =
{
    {
        "vendor",
        5,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_STRING,
        0,   /* quantifier_offset */
        offsetof(KineticProto_GetLog__Configuration, vendor),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "model",
        6,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_STRING,
        0,   /* quantifier_offset */
        offsetof(KineticProto_GetLog__Configuration, model),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "serialNumber",
        7,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_BYTES,
        offsetof(KineticProto_GetLog__Configuration, has_serialnumber),
        offsetof(KineticProto_GetLog__Configuration, serialnumber),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "version",
        8,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_STRING,
        0,   /* quantifier_offset */
        offsetof(KineticProto_GetLog__Configuration, version),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "interface",
        9,
        PROTOBUF_C_LABEL_REPEATED,
        PROTOBUF_C_TYPE_MESSAGE,
        offsetof(KineticProto_GetLog__Configuration, n_interface),
        offsetof(KineticProto_GetLog__Configuration, interface),
        &KineticProto_get_log__configuration__interface__descriptor,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "port",
        10,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_INT32,
        offsetof(KineticProto_GetLog__Configuration, has_port),
        offsetof(KineticProto_GetLog__Configuration, port),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "tlsPort",
        11,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_INT32,
        offsetof(KineticProto_GetLog__Configuration, has_tlsport),
        offsetof(KineticProto_GetLog__Configuration, tlsport),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "compilationDate",
        12,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_STRING,
        0,   /* quantifier_offset */
        offsetof(KineticProto_GetLog__Configuration, compilationdate),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "sourceHash",
        13,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_STRING,
        0,   /* quantifier_offset */
        offsetof(KineticProto_GetLog__Configuration, sourcehash),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "worldWideName",
        14,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_BYTES,
        offsetof(KineticProto_GetLog__Configuration, has_worldwidename),
        offsetof(KineticProto_GetLog__Configuration, worldwidename),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "protocolVersion",
        15,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_STRING,
        0,   /* quantifier_offset */
        offsetof(KineticProto_GetLog__Configuration, protocolversion),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "protocolCompilationDate",
        16,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_STRING,
        0,   /* quantifier_offset */
        offsetof(KineticProto_GetLog__Configuration, protocolcompilationdate),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "protocolSourceHash",
        17,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_STRING,
        0,   /* quantifier_offset */
        offsetof(KineticProto_GetLog__Configuration, protocolsourcehash),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
};

static const unsigned KineticProto_get_log__configuration__field_indices_by_name[] =
{
    7,   /* field[7] = compilationDate */
    4,   /* field[4] = interface */
    1,   /* field[1] = model */
    5,   /* field[5] = port */
    11,   /* field[11] = protocolCompilationDate */
    12,   /* field[12] = protocolSourceHash */
    10,   /* field[10] = protocolVersion */
    2,   /* field[2] = serialNumber */
    8,   /* field[8] = sourceHash */
    6,   /* field[6] = tlsPort */
    0,   /* field[0] = vendor */
    3,   /* field[3] = version */
    9,   /* field[9] = worldWideName */
};

static const ProtobufCIntRange KineticProto_get_log__configuration__number_ranges[1 + 1] =
{
    { 5, 0 },
    { 0, 13 }
};

const ProtobufCMessageDescriptor KineticProto_get_log__configuration__descriptor =
{
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "com.seagate.kinetic.proto.Message.GetLog.Configuration",
    "Configuration",
    "KineticProto_GetLog__Configuration",
    "com.seagate.kinetic.proto",
    sizeof(KineticProto_GetLog__Configuration),
    13,
    KineticProto_get_log__configuration__field_descriptors,
    KineticProto_get_log__configuration__field_indices_by_name,
    1,  KineticProto_get_log__configuration__number_ranges,
    (ProtobufCMessageInit) KineticProto_get_log__configuration__init,
    NULL, NULL, NULL  /* reserved[123] */
};

static const ProtobufCFieldDescriptor KineticProto_get_log__statistics__field_descriptors[3] =
{
    {
        "messageType",
        1,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_ENUM,
        offsetof(KineticProto_GetLog__Statistics, has_messagetype),
        offsetof(KineticProto_GetLog__Statistics, messagetype),
        &KineticProto_message_type__descriptor,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "count",
        4,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_UINT64,
        offsetof(KineticProto_GetLog__Statistics, has_count),
        offsetof(KineticProto_GetLog__Statistics, count),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "bytes",
        5,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_UINT64,
        offsetof(KineticProto_GetLog__Statistics, has_bytes),
        offsetof(KineticProto_GetLog__Statistics, bytes),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
};

static const unsigned KineticProto_get_log__statistics__field_indices_by_name[] =
{
    2,   /* field[2] = bytes */
    1,   /* field[1] = count */
    0,   /* field[0] = messageType */
};

static const ProtobufCIntRange KineticProto_get_log__statistics__number_ranges[2 + 1] =
{
    { 1, 0 },
    { 4, 1 },
    { 0, 3 }
};

const ProtobufCMessageDescriptor KineticProto_get_log__statistics__descriptor =
{
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "com.seagate.kinetic.proto.Message.GetLog.Statistics",
    "Statistics",
    "KineticProto_GetLog__Statistics",
    "com.seagate.kinetic.proto",
    sizeof(KineticProto_GetLog__Statistics),
    3,
    KineticProto_get_log__statistics__field_descriptors,
    KineticProto_get_log__statistics__field_indices_by_name,
    2,  KineticProto_get_log__statistics__number_ranges,
    (ProtobufCMessageInit) KineticProto_get_log__statistics__init,
    NULL, NULL, NULL  /* reserved[123] */
};

static const ProtobufCFieldDescriptor KineticProto_get_log__limits__field_descriptors[9] =
{
    {
        "maxKeySize",
        1,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_UINT32,
        offsetof(KineticProto_GetLog__Limits, has_maxkeysize),
        offsetof(KineticProto_GetLog__Limits, maxkeysize),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "maxValueSize",
        2,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_UINT32,
        offsetof(KineticProto_GetLog__Limits, has_maxvaluesize),
        offsetof(KineticProto_GetLog__Limits, maxvaluesize),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "maxVersionSize",
        3,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_UINT32,
        offsetof(KineticProto_GetLog__Limits, has_maxversionsize),
        offsetof(KineticProto_GetLog__Limits, maxversionsize),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "maxTagSize",
        4,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_UINT32,
        offsetof(KineticProto_GetLog__Limits, has_maxtagsize),
        offsetof(KineticProto_GetLog__Limits, maxtagsize),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "maxConnections",
        5,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_UINT32,
        offsetof(KineticProto_GetLog__Limits, has_maxconnections),
        offsetof(KineticProto_GetLog__Limits, maxconnections),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "maxOutstandingReadRequests",
        6,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_UINT32,
        offsetof(KineticProto_GetLog__Limits, has_maxoutstandingreadrequests),
        offsetof(KineticProto_GetLog__Limits, maxoutstandingreadrequests),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "maxOutstandingWriteRequests",
        7,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_UINT32,
        offsetof(KineticProto_GetLog__Limits, has_maxoutstandingwriterequests),
        offsetof(KineticProto_GetLog__Limits, maxoutstandingwriterequests),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "maxMessageSize",
        8,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_UINT32,
        offsetof(KineticProto_GetLog__Limits, has_maxmessagesize),
        offsetof(KineticProto_GetLog__Limits, maxmessagesize),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "maxKeyRangeCount",
        9,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_UINT32,
        offsetof(KineticProto_GetLog__Limits, has_maxkeyrangecount),
        offsetof(KineticProto_GetLog__Limits, maxkeyrangecount),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
};

static const unsigned KineticProto_get_log__limits__field_indices_by_name[] =
{
    4,   /* field[4] = maxConnections */
    8,   /* field[8] = maxKeyRangeCount */
    0,   /* field[0] = maxKeySize */
    7,   /* field[7] = maxMessageSize */
    5,   /* field[5] = maxOutstandingReadRequests */
    6,   /* field[6] = maxOutstandingWriteRequests */
    3,   /* field[3] = maxTagSize */
    1,   /* field[1] = maxValueSize */
    2,   /* field[2] = maxVersionSize */
};

static const ProtobufCIntRange KineticProto_get_log__limits__number_ranges[1 + 1] =
{
    { 1, 0 },
    { 0, 9 }
};

const ProtobufCMessageDescriptor KineticProto_get_log__limits__descriptor =
{
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "com.seagate.kinetic.proto.Message.GetLog.Limits",
    "Limits",
    "KineticProto_GetLog__Limits",
    "com.seagate.kinetic.proto",
    sizeof(KineticProto_GetLog__Limits),
    9,
    KineticProto_get_log__limits__field_descriptors,
    KineticProto_get_log__limits__field_indices_by_name,
    1,  KineticProto_get_log__limits__number_ranges,
    (ProtobufCMessageInit) KineticProto_get_log__limits__init,
    NULL, NULL, NULL  /* reserved[123] */
};

const ProtobufCEnumValue KineticProto_get_log__type__enum_values_by_number[8] =
{
    { "INVALID_TYPE", "KINETIC_PROTO_GET_LOG__TYPE__INVALID_TYPE", -1 },
    { "UTILIZATIONS", "KINETIC_PROTO_GET_LOG__TYPE__UTILIZATIONS", 0 },
    { "TEMPERATURES", "KINETIC_PROTO_GET_LOG__TYPE__TEMPERATURES", 1 },
    { "CAPACITIES", "KINETIC_PROTO_GET_LOG__TYPE__CAPACITIES", 2 },
    { "CONFIGURATION", "KINETIC_PROTO_GET_LOG__TYPE__CONFIGURATION", 3 },
    { "STATISTICS", "KINETIC_PROTO_GET_LOG__TYPE__STATISTICS", 4 },
    { "MESSAGES", "KINETIC_PROTO_GET_LOG__TYPE__MESSAGES", 5 },
    { "LIMITS", "KINETIC_PROTO_GET_LOG__TYPE__LIMITS", 6 },
};

static const ProtobufCIntRange KineticProto_get_log__type__value_ranges[] =
{
    { -1, 0}, {0, 8}
};

const ProtobufCEnumValueIndex KineticProto_get_log__type__enum_values_by_name[8] =
{
    { "CAPACITIES", 3 },
    { "CONFIGURATION", 4 },
    { "INVALID_TYPE", 0 },
    { "LIMITS", 7 },
    { "MESSAGES", 6 },
    { "STATISTICS", 5 },
    { "TEMPERATURES", 2 },
    { "UTILIZATIONS", 1 },
};

const ProtobufCEnumDescriptor KineticProto_get_log__type__descriptor =
{
    PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
    "com.seagate.kinetic.proto.Message.GetLog.Type",
    "Type",
    "KineticProto_GetLog__Type",
    "com.seagate.kinetic.proto",
    8,
    KineticProto_get_log__type__enum_values_by_number,
    8,
    KineticProto_get_log__type__enum_values_by_name,
    1,
    KineticProto_get_log__type__value_ranges,
    NULL, NULL, NULL, NULL /* reserved[1234] */
};

static const ProtobufCFieldDescriptor KineticProto_get_log__field_descriptors[8] =
{
    {
        "type",
        1,
        PROTOBUF_C_LABEL_REPEATED,
        PROTOBUF_C_TYPE_ENUM,
        offsetof(KineticProto_GetLog, n_type),
        offsetof(KineticProto_GetLog, type),
        &KineticProto_get_log__type__descriptor,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "utilization",
        2,
        PROTOBUF_C_LABEL_REPEATED,
        PROTOBUF_C_TYPE_MESSAGE,
        offsetof(KineticProto_GetLog, n_utilization),
        offsetof(KineticProto_GetLog, utilization),
        &KineticProto_get_log__utilization__descriptor,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "temperature",
        3,
        PROTOBUF_C_LABEL_REPEATED,
        PROTOBUF_C_TYPE_MESSAGE,
        offsetof(KineticProto_GetLog, n_temperature),
        offsetof(KineticProto_GetLog, temperature),
        &KineticProto_get_log__temperature__descriptor,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "capacity",
        4,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_MESSAGE,
        0,   /* quantifier_offset */
        offsetof(KineticProto_GetLog, capacity),
        &KineticProto_get_log__capacity__descriptor,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "configuration",
        5,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_MESSAGE,
        0,   /* quantifier_offset */
        offsetof(KineticProto_GetLog, configuration),
        &KineticProto_get_log__configuration__descriptor,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "statistics",
        6,
        PROTOBUF_C_LABEL_REPEATED,
        PROTOBUF_C_TYPE_MESSAGE,
        offsetof(KineticProto_GetLog, n_statistics),
        offsetof(KineticProto_GetLog, statistics),
        &KineticProto_get_log__statistics__descriptor,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "messages",
        7,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_BYTES,
        offsetof(KineticProto_GetLog, has_messages),
        offsetof(KineticProto_GetLog, messages),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "limits",
        8,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_MESSAGE,
        0,   /* quantifier_offset */
        offsetof(KineticProto_GetLog, limits),
        &KineticProto_get_log__limits__descriptor,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
};

static const unsigned KineticProto_get_log__field_indices_by_name[] =
{
    3,   /* field[3] = capacity */
    4,   /* field[4] = configuration */
    7,   /* field[7] = limits */
    6,   /* field[6] = messages */
    5,   /* field[5] = statistics */
    2,   /* field[2] = temperature */
    0,   /* field[0] = type */
    1,   /* field[1] = utilization */
};

static const ProtobufCIntRange KineticProto_get_log__number_ranges[1 + 1] =
{
    { 1, 0 },
    { 0, 8 }
};

const ProtobufCMessageDescriptor KineticProto_get_log__descriptor =
{
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "com.seagate.kinetic.proto.Message.GetLog",
    "GetLog",
    "KineticProto_GetLog",
    "com.seagate.kinetic.proto",
    sizeof(KineticProto_GetLog),
    8,
    KineticProto_get_log__field_descriptors,
    KineticProto_get_log__field_indices_by_name,
    1,  KineticProto_get_log__number_ranges,
    (ProtobufCMessageInit) KineticProto_get_log__init,
    NULL, NULL, NULL  /* reserved[123] */
};

static const ProtobufCFieldDescriptor KineticProto_security__acl__scope__field_descriptors[4] =
{
    {
        "offset",
        1,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_INT64,
        offsetof(KineticProto_Security__ACL__Scope, has_offset),
        offsetof(KineticProto_Security__ACL__Scope, offset),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "value",
        2,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_BYTES,
        offsetof(KineticProto_Security__ACL__Scope, has_value),
        offsetof(KineticProto_Security__ACL__Scope, value),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "permission",
        3,
        PROTOBUF_C_LABEL_REPEATED,
        PROTOBUF_C_TYPE_ENUM,
        offsetof(KineticProto_Security__ACL__Scope, n_permission),
        offsetof(KineticProto_Security__ACL__Scope, permission),
        &KineticProto_security__acl__permission__descriptor,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "TlsRequired",
        4,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_BOOL,
        offsetof(KineticProto_Security__ACL__Scope, has_tlsrequired),
        offsetof(KineticProto_Security__ACL__Scope, tlsrequired),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
};

static const unsigned KineticProto_security__acl__scope__field_indices_by_name[] =
{
    3,   /* field[3] = TlsRequired */
    0,   /* field[0] = offset */
    2,   /* field[2] = permission */
    1,   /* field[1] = value */
};

static const ProtobufCIntRange KineticProto_security__acl__scope__number_ranges[1 + 1] =
{
    { 1, 0 },
    { 0, 4 }
};

const ProtobufCMessageDescriptor KineticProto_security__acl__scope__descriptor =
{
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "com.seagate.kinetic.proto.Message.Security.ACL.Scope",
    "Scope",
    "KineticProto_Security__ACL__Scope",
    "com.seagate.kinetic.proto",
    sizeof(KineticProto_Security__ACL__Scope),
    4,
    KineticProto_security__acl__scope__field_descriptors,
    KineticProto_security__acl__scope__field_indices_by_name,
    1,  KineticProto_security__acl__scope__number_ranges,
    (ProtobufCMessageInit) KineticProto_security__acl__scope__init,
    NULL, NULL, NULL  /* reserved[123] */
};

const ProtobufCEnumValue KineticProto_security__acl__hmacalgorithm__enum_values_by_number[2] =
{
    { "INVALID_HMAC_ALGORITHM", "KINETIC_PROTO_SECURITY__ACL__HMACALGORITHM__INVALID_HMAC_ALGORITHM", -1 },
    { "HmacSHA1", "KINETIC_PROTO_SECURITY__ACL__HMACALGORITHM__HmacSHA1", 1 },
};

static const ProtobufCIntRange KineticProto_security__acl__hmacalgorithm__value_ranges[] =
{
    { -1, 0}, {1, 1}, {0, 2}
};

const ProtobufCEnumValueIndex KineticProto_security__acl__hmacalgorithm__enum_values_by_name[2] =
{
    { "HmacSHA1", 1 },
    { "INVALID_HMAC_ALGORITHM", 0 },
};

const ProtobufCEnumDescriptor KineticProto_security__acl__hmacalgorithm__descriptor =
{
    PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
    "com.seagate.kinetic.proto.Message.Security.ACL.HMACAlgorithm",
    "HMACAlgorithm",
    "KineticProto_Security__ACL__HMACAlgorithm",
    "com.seagate.kinetic.proto",
    2,
    KineticProto_security__acl__hmacalgorithm__enum_values_by_number,
    2,
    KineticProto_security__acl__hmacalgorithm__enum_values_by_name,
    2,
    KineticProto_security__acl__hmacalgorithm__value_ranges,
    NULL, NULL, NULL, NULL /* reserved[1234] */
};

const ProtobufCEnumValue KineticProto_security__acl__permission__enum_values_by_number[9] =
{
    { "INVALID_PERMISSION", "KINETIC_PROTO_SECURITY__ACL__PERMISSION__INVALID_PERMISSION", -1 },
    { "READ", "KINETIC_PROTO_SECURITY__ACL__PERMISSION__READ", 0 },
    { "WRITE", "KINETIC_PROTO_SECURITY__ACL__PERMISSION__WRITE", 1 },
    { "DELETE", "KINETIC_PROTO_SECURITY__ACL__PERMISSION__DELETE", 2 },
    { "RANGE", "KINETIC_PROTO_SECURITY__ACL__PERMISSION__RANGE", 3 },
    { "SETUP", "KINETIC_PROTO_SECURITY__ACL__PERMISSION__SETUP", 4 },
    { "P2POP", "KINETIC_PROTO_SECURITY__ACL__PERMISSION__P2POP", 5 },
    { "GETLOG", "KINETIC_PROTO_SECURITY__ACL__PERMISSION__GETLOG", 7 },
    { "SECURITY", "KINETIC_PROTO_SECURITY__ACL__PERMISSION__SECURITY", 8 },
};

static const ProtobufCIntRange KineticProto_security__acl__permission__value_ranges[] =
{
    { -1, 0}, {7, 7}, {0, 9}
};

const ProtobufCEnumValueIndex KineticProto_security__acl__permission__enum_values_by_name[9] =
{
    { "DELETE", 3 },
    { "GETLOG", 7 },
    { "INVALID_PERMISSION", 0 },
    { "P2POP", 6 },
    { "RANGE", 4 },
    { "READ", 1 },
    { "SECURITY", 8 },
    { "SETUP", 5 },
    { "WRITE", 2 },
};

const ProtobufCEnumDescriptor KineticProto_security__acl__permission__descriptor =
{
    PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
    "com.seagate.kinetic.proto.Message.Security.ACL.Permission",
    "Permission",
    "KineticProto_Security__ACL__Permission",
    "com.seagate.kinetic.proto",
    9,
    KineticProto_security__acl__permission__enum_values_by_number,
    9,
    KineticProto_security__acl__permission__enum_values_by_name,
    2,
    KineticProto_security__acl__permission__value_ranges,
    NULL, NULL, NULL, NULL /* reserved[1234] */
};

static const ProtobufCFieldDescriptor KineticProto_security__acl__field_descriptors[4] =
{
    {
        "identity",
        1,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_INT64,
        offsetof(KineticProto_Security__ACL, has_identity),
        offsetof(KineticProto_Security__ACL, identity),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "key",
        2,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_BYTES,
        offsetof(KineticProto_Security__ACL, has_key),
        offsetof(KineticProto_Security__ACL, key),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "hmacAlgorithm",
        3,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_ENUM,
        offsetof(KineticProto_Security__ACL, has_hmacalgorithm),
        offsetof(KineticProto_Security__ACL, hmacalgorithm),
        &KineticProto_security__acl__hmacalgorithm__descriptor,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "scope",
        4,
        PROTOBUF_C_LABEL_REPEATED,
        PROTOBUF_C_TYPE_MESSAGE,
        offsetof(KineticProto_Security__ACL, n_scope),
        offsetof(KineticProto_Security__ACL, scope),
        &KineticProto_security__acl__scope__descriptor,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
};

static const unsigned KineticProto_security__acl__field_indices_by_name[] =
{
    2,   /* field[2] = hmacAlgorithm */
    0,   /* field[0] = identity */
    1,   /* field[1] = key */
    3,   /* field[3] = scope */
};

static const ProtobufCIntRange KineticProto_security__acl__number_ranges[1 + 1] =
{
    { 1, 0 },
    { 0, 4 }
};

const ProtobufCMessageDescriptor KineticProto_security__acl__descriptor =
{
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "com.seagate.kinetic.proto.Message.Security.ACL",
    "ACL",
    "KineticProto_Security__ACL",
    "com.seagate.kinetic.proto",
    sizeof(KineticProto_Security__ACL),
    4,
    KineticProto_security__acl__field_descriptors,
    KineticProto_security__acl__field_indices_by_name,
    1,  KineticProto_security__acl__number_ranges,
    (ProtobufCMessageInit) KineticProto_security__acl__init,
    NULL, NULL, NULL  /* reserved[123] */
};

static const ProtobufCFieldDescriptor KineticProto_security__field_descriptors[1] =
{
    {
        "acl",
        2,
        PROTOBUF_C_LABEL_REPEATED,
        PROTOBUF_C_TYPE_MESSAGE,
        offsetof(KineticProto_Security, n_acl),
        offsetof(KineticProto_Security, acl),
        &KineticProto_security__acl__descriptor,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
};

static const unsigned KineticProto_security__field_indices_by_name[] =
{
    0,   /* field[0] = acl */
};

static const ProtobufCIntRange KineticProto_security__number_ranges[1 + 1] =
{
    { 2, 0 },
    { 0, 1 }
};

const ProtobufCMessageDescriptor KineticProto_security__descriptor =
{
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "com.seagate.kinetic.proto.Message.Security",
    "Security",
    "KineticProto_Security",
    "com.seagate.kinetic.proto",
    sizeof(KineticProto_Security),
    1,
    KineticProto_security__field_descriptors,
    KineticProto_security__field_indices_by_name,
    1,  KineticProto_security__number_ranges,
    (ProtobufCMessageInit) KineticProto_security__init,
    NULL, NULL, NULL  /* reserved[123] */
};

const ProtobufCEnumValue KineticProto_synchronization__enum_values_by_number[4] =
{
    { "INVALID_SYNCHRONIZATION", "KINETIC_PROTO_SYNCHRONIZATION__INVALID_SYNCHRONIZATION", -1 },
    { "WRITETHROUGH", "KINETIC_PROTO_SYNCHRONIZATION__WRITETHROUGH", 1 },
    { "WRITEBACK", "KINETIC_PROTO_SYNCHRONIZATION__WRITEBACK", 2 },
    { "FLUSH", "KINETIC_PROTO_SYNCHRONIZATION__FLUSH", 3 },
};

static const ProtobufCIntRange KineticProto_synchronization__value_ranges[] =
{
    { -1, 0}, {1, 1}, {0, 4}
};

const ProtobufCEnumValueIndex KineticProto_synchronization__enum_values_by_name[4] =
{
    { "FLUSH", 3 },
    { "INVALID_SYNCHRONIZATION", 0 },
    { "WRITEBACK", 2 },
    { "WRITETHROUGH", 1 },
};

const ProtobufCEnumDescriptor KineticProto_synchronization__descriptor =
{
    PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
    "com.seagate.kinetic.proto.Message.Synchronization",
    "Synchronization",
    "KineticProto_Synchronization",
    "com.seagate.kinetic.proto",
    4,
    KineticProto_synchronization__enum_values_by_number,
    4,
    KineticProto_synchronization__enum_values_by_name,
    2,
    KineticProto_synchronization__value_ranges,
    NULL, NULL, NULL, NULL /* reserved[1234] */
};

const ProtobufCEnumValue KineticProto_algorithm__enum_values_by_number[6] =
{
    { "INVALID_ALGORITHM", "KINETIC_PROTO_ALGORITHM__INVALID_ALGORITHM", -1 },
    { "SHA1", "KINETIC_PROTO_ALGORITHM__SHA1", 1 },
    { "SHA2", "KINETIC_PROTO_ALGORITHM__SHA2", 2 },
    { "SHA3", "KINETIC_PROTO_ALGORITHM__SHA3", 3 },
    { "CRC32", "KINETIC_PROTO_ALGORITHM__CRC32", 4 },
    { "CRC64", "KINETIC_PROTO_ALGORITHM__CRC64", 5 },
};

static const ProtobufCIntRange KineticProto_algorithm__value_ranges[] =
{
    { -1, 0}, {1, 1}, {0, 6}
};

const ProtobufCEnumValueIndex KineticProto_algorithm__enum_values_by_name[6] =
{
    { "CRC32", 4 },
    { "CRC64", 5 },
    { "INVALID_ALGORITHM", 0 },
    { "SHA1", 1 },
    { "SHA2", 2 },
    { "SHA3", 3 },
};

const ProtobufCEnumDescriptor KineticProto_algorithm__descriptor =
{
    PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
    "com.seagate.kinetic.proto.Message.Algorithm",
    "Algorithm",
    "KineticProto_Algorithm",
    "com.seagate.kinetic.proto",
    6,
    KineticProto_algorithm__enum_values_by_number,
    6,
    KineticProto_algorithm__enum_values_by_name,
    2,
    KineticProto_algorithm__value_ranges,
    NULL, NULL, NULL, NULL /* reserved[1234] */
};

const ProtobufCEnumValue KineticProto_message_type__enum_values_by_number[27] =
{
    { "INVALID_MESSAGE_TYPE", "KINETIC_PROTO_MESSAGE_TYPE__INVALID_MESSAGE_TYPE", -1 },
    { "GET_RESPONSE", "KINETIC_PROTO_MESSAGE_TYPE__GET_RESPONSE", 1 },
    { "GET", "KINETIC_PROTO_MESSAGE_TYPE__GET", 2 },
    { "PUT_RESPONSE", "KINETIC_PROTO_MESSAGE_TYPE__PUT_RESPONSE", 3 },
    { "PUT", "KINETIC_PROTO_MESSAGE_TYPE__PUT", 4 },
    { "DELETE_RESPONSE", "KINETIC_PROTO_MESSAGE_TYPE__DELETE_RESPONSE", 5 },
    { "DELETE", "KINETIC_PROTO_MESSAGE_TYPE__DELETE", 6 },
    { "GETNEXT_RESPONSE", "KINETIC_PROTO_MESSAGE_TYPE__GETNEXT_RESPONSE", 7 },
    { "GETNEXT", "KINETIC_PROTO_MESSAGE_TYPE__GETNEXT", 8 },
    { "GETPREVIOUS_RESPONSE", "KINETIC_PROTO_MESSAGE_TYPE__GETPREVIOUS_RESPONSE", 9 },
    { "GETPREVIOUS", "KINETIC_PROTO_MESSAGE_TYPE__GETPREVIOUS", 10 },
    { "GETKEYRANGE_RESPONSE", "KINETIC_PROTO_MESSAGE_TYPE__GETKEYRANGE_RESPONSE", 11 },
    { "GETKEYRANGE", "KINETIC_PROTO_MESSAGE_TYPE__GETKEYRANGE", 12 },
    { "GETVERSION_RESPONSE", "KINETIC_PROTO_MESSAGE_TYPE__GETVERSION_RESPONSE", 15 },
    { "GETVERSION", "KINETIC_PROTO_MESSAGE_TYPE__GETVERSION", 16 },
    { "SETUP_RESPONSE", "KINETIC_PROTO_MESSAGE_TYPE__SETUP_RESPONSE", 21 },
    { "SETUP", "KINETIC_PROTO_MESSAGE_TYPE__SETUP", 22 },
    { "GETLOG_RESPONSE", "KINETIC_PROTO_MESSAGE_TYPE__GETLOG_RESPONSE", 23 },
    { "GETLOG", "KINETIC_PROTO_MESSAGE_TYPE__GETLOG", 24 },
    { "SECURITY_RESPONSE", "KINETIC_PROTO_MESSAGE_TYPE__SECURITY_RESPONSE", 25 },
    { "SECURITY", "KINETIC_PROTO_MESSAGE_TYPE__SECURITY", 26 },
    { "PEER2PEERPUSH_RESPONSE", "KINETIC_PROTO_MESSAGE_TYPE__PEER2PEERPUSH_RESPONSE", 27 },
    { "PEER2PEERPUSH", "KINETIC_PROTO_MESSAGE_TYPE__PEER2PEERPUSH", 28 },
    { "NOOP_RESPONSE", "KINETIC_PROTO_MESSAGE_TYPE__NOOP_RESPONSE", 29 },
    { "NOOP", "KINETIC_PROTO_MESSAGE_TYPE__NOOP", 30 },
    { "FLUSHALLDATA_RESPONSE", "KINETIC_PROTO_MESSAGE_TYPE__FLUSHALLDATA_RESPONSE", 31 },
    { "FLUSHALLDATA", "KINETIC_PROTO_MESSAGE_TYPE__FLUSHALLDATA", 32 },
};

static const ProtobufCIntRange KineticProto_message_type__value_ranges[] =
{
    { -1, 0}, {1, 1}, {15, 13}, {21, 15}, {0, 27}
};

const ProtobufCEnumValueIndex KineticProto_message_type__enum_values_by_name[27] =
{
    { "DELETE", 6 },
    { "DELETE_RESPONSE", 5 },
    { "FLUSHALLDATA", 26 },
    { "FLUSHALLDATA_RESPONSE", 25 },
    { "GET", 2 },
    { "GETKEYRANGE", 12 },
    { "GETKEYRANGE_RESPONSE", 11 },
    { "GETLOG", 18 },
    { "GETLOG_RESPONSE", 17 },
    { "GETNEXT", 8 },
    { "GETNEXT_RESPONSE", 7 },
    { "GETPREVIOUS", 10 },
    { "GETPREVIOUS_RESPONSE", 9 },
    { "GETVERSION", 14 },
    { "GETVERSION_RESPONSE", 13 },
    { "GET_RESPONSE", 1 },
    { "INVALID_MESSAGE_TYPE", 0 },
    { "NOOP", 24 },
    { "NOOP_RESPONSE", 23 },
    { "PEER2PEERPUSH", 22 },
    { "PEER2PEERPUSH_RESPONSE", 21 },
    { "PUT", 4 },
    { "PUT_RESPONSE", 3 },
    { "SECURITY", 20 },
    { "SECURITY_RESPONSE", 19 },
    { "SETUP", 16 },
    { "SETUP_RESPONSE", 15 },
};

const ProtobufCEnumDescriptor KineticProto_message_type__descriptor =
{
    PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
    "com.seagate.kinetic.proto.Message.MessageType",
    "MessageType",
    "KineticProto_MessageType",
    "com.seagate.kinetic.proto",
    27,
    KineticProto_message_type__enum_values_by_number,
    27,
    KineticProto_message_type__enum_values_by_name,
    4,
    KineticProto_message_type__value_ranges,
    NULL, NULL, NULL, NULL /* reserved[1234] */
};

static const ProtobufCFieldDescriptor KineticProto_field_descriptors[2] =
{
    {
        "command",
        1,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_MESSAGE,
        0,   /* quantifier_offset */
        offsetof(KineticProto, command),
        &KineticProto_command__descriptor,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
    {
        "hmac",
        3,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_BYTES,
        offsetof(KineticProto, has_hmac),
        offsetof(KineticProto, hmac),
        NULL,
        NULL,
        0,             /* flags */
        0, NULL, NULL  /* reserved1,reserved2, etc */
    },
};

static const unsigned KineticProto_field_indices_by_name[] =
{
    0,   /* field[0] = command */
    1,   /* field[1] = hmac */
};

static const ProtobufCIntRange KineticProto_number_ranges[2 + 1] =
{
    { 1, 0 },
    { 3, 1 },
    { 0, 2 }
};

const ProtobufCMessageDescriptor KineticProto_descriptor =
{
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "com.seagate.kinetic.proto.Message",
    "Message",
    "KineticProto",
    "com.seagate.kinetic.proto",
    sizeof(KineticProto),
    2,
    KineticProto_field_descriptors,
    KineticProto_field_indices_by_name,
    2,  KineticProto_number_ranges,
    (ProtobufCMessageInit) KineticProto_init,
    NULL, NULL, NULL  /* reserved[123] */
};
