title Kinetic C message handling (w/ send error/hangup)

Client -> Client: pack request
activate Client

Client -> Listener: hold responses for <FD, SEQ_ID>
activate Listener

Client -> Drive: send request
activate Drive

Drive -> Client: HANG UP (error)
deactivate Drive

Client -> Threadpool: Transfer callback with send error
activate Threadpool
deactivate Client

Threadpool -->> Client: callback(socket error)
deactivate Threadpool

Listener -> Listener: (wait)

note right of Listener: TIME OUT
deactivate Listener
