title Kinetic C message handling (w/ response time-out)

Client -> Client: pack request
activate Client

Client -> Listener: hold responses for <FD, SEQ_ID>
activate Listener

Client -> Drive: send request
activate Drive

Client -> Listener: expect response for <FD, SEQ_ID>
Listener -> Client: acknowledgement with backpressure

Client -> Client: backpressure
deactivate Client

Listener -> Listener: wait

note right of Listener: TIME OUT
deactivate Listener

Listener -> Threadpool: Transfer callback with receive timeout
activate Threadpool

Threadpool -->> Client: callback(receive timeout)
deactivate Threadpool
